BibliaKJV.cantares = {
	libro: "Song of Songs",
	numCapitulos: 8,

c1: {
versiculos:[
{name:'2211',l:'22',c:'1',v:'1',texto:"The song of songs, which is Solomon's."},
{name:'2212',l:'22',c:'1',v:'2',texto:"Let him kiss me with the kisses of his mouth: for thy love is better than wine."},
{name:'2213',l:'22',c:'1',v:'3',texto:"Because of the savour of thy good ointments thy name is as ointment poured forth, therefore do the virgins love thee."},
{name:'2214',l:'22',c:'1',v:'4',texto:"Draw me, we will run after thee: the king hath brought me into his chambers: we will be glad and rejoice in thee, we will remember thy love more than wine: the upright love thee."},
{name:'2215',l:'22',c:'1',v:'5',texto:"I am black, but comely, O ye daughters of Jerusalem, as the tents of Kedar, as the curtains of Solomon."},
{name:'2216',l:'22',c:'1',v:'6',texto:"Look not upon me, because I am black, because the sun hath looked upon me: my mother's children were angry with me; they made me the keeper of the vineyards; but mine own vineyard have I not kept."},
{name:'2217',l:'22',c:'1',v:'7',texto:"Tell me, O thou whom my soul loveth, where thou feedest, where thou makest thy flock to rest at noon: for why should I be as one that turneth aside by the flocks of thy companions?"},
{name:'2218',l:'22',c:'1',v:'8',texto:"If thou know not, O thou fairest among women, go thy way forth by the footsteps of the flock, and feed thy kids beside the shepherds' tents."},
{name:'2219',l:'22',c:'1',v:'9',texto:"I have compared thee, O my love, to a company of horses in Pharaoh's chariots."},
{name:'22110',l:'22',c:'1',v:'10',texto:"Thy cheeks are comely with rows of jewels, thy neck with chains of gold."},
{name:'22111',l:'22',c:'1',v:'11',texto:"We will make thee borders of gold with studs of silver."},
{name:'22112',l:'22',c:'1',v:'12',texto:"While the king sitteth at his table, my spikenard sendeth forth the smell thereof."},
{name:'22113',l:'22',c:'1',v:'13',texto:"A bundle of myrrh is my wellbeloved unto me; he shall lie all night betwixt my breasts."},
{name:'22114',l:'22',c:'1',v:'14',texto:"My beloved is unto me as a cluster of camphire in the vineyards of Engedi."},
{name:'22115',l:'22',c:'1',v:'15',texto:"Behold, thou art fair, my love; behold, thou art fair; thou hast doves' eyes."},
{name:'22116',l:'22',c:'1',v:'16',texto:"Behold, thou art fair, my beloved, yea, pleasant: also our bed is green."},
{name:'22117',l:'22',c:'1',v:'17',texto:"The beams of our house are cedar, and our rafters of fir."},
],
numVersiculos: 17,
},

c2: {
versiculos:[
{name:'2221',l:'22',c:'2',v:'1',texto:"I am the rose of Sharon, and the lily of the valleys."},
{name:'2222',l:'22',c:'2',v:'2',texto:"As the lily among thorns, so is my love among the daughters."},
{name:'2223',l:'22',c:'2',v:'3',texto:"As the apple tree among the trees of the wood, so is my beloved among the sons. I sat down under his shadow with great delight, and his fruit was sweet to my taste."},
{name:'2224',l:'22',c:'2',v:'4',texto:"He brought me to the banqueting house, and his banner over me was love."},
{name:'2225',l:'22',c:'2',v:'5',texto:"Stay me with flagons, comfort me with apples: for I am sick of love."},
{name:'2226',l:'22',c:'2',v:'6',texto:"His left hand is under my head, and his right hand doth embrace me."},
{name:'2227',l:'22',c:'2',v:'7',texto:"I charge you, O ye daughters of Jerusalem, by the roes, and by the hinds of the field, that ye stir not up, nor awake my love, till he please."},
{name:'2228',l:'22',c:'2',v:'8',texto:"The voice of my beloved! behold, he cometh leaping upon the mountains, skipping upon the hills."},
{name:'2229',l:'22',c:'2',v:'9',texto:"My beloved is like a roe or a young hart: behold, he standeth behind our wall, he looketh forth at the windows, shewing himself through the lattice."},
{name:'22210',l:'22',c:'2',v:'10',texto:"My beloved spake, and said unto me, Rise up, my love, my fair one, and come away."},
{name:'22211',l:'22',c:'2',v:'11',texto:"For, lo, the winter is past, the rain is over and gone;"},
{name:'22212',l:'22',c:'2',v:'12',texto:"The flowers appear on the earth; the time of the singing of birds is come, and the voice of the turtle is heard in our land;"},
{name:'22213',l:'22',c:'2',v:'13',texto:"The fig tree putteth forth her green figs, and the vines with the tender grape give a good smell. Arise, my love, my fair one, and come away."},
{name:'22214',l:'22',c:'2',v:'14',texto:"O my dove, that art in the clefts of the rock, in the secret places of the stairs, let me see thy countenance, let me hear thy voice; for sweet is thy voice, and thy countenance is comely."},
{name:'22215',l:'22',c:'2',v:'15',texto:"Take us the foxes, the little foxes, that spoil the vines: for our vines have tender grapes."},
{name:'22216',l:'22',c:'2',v:'16',texto:"My beloved is mine, and I am his: he feedeth among the lilies."},
{name:'22217',l:'22',c:'2',v:'17',texto:"Until the day break, and the shadows flee away, turn, my beloved, and be thou like a roe or a young hart upon the mountains of Bether."},
],
numVersiculos: 17,
},

c3: {
versiculos:[
{name:'2231',l:'22',c:'3',v:'1',texto:"By night on my bed I sought him whom my soul loveth: I sought him, but I found him not."},
{name:'2232',l:'22',c:'3',v:'2',texto:"I will rise now, and go about the city in the streets, and in the broad ways I will seek him whom my soul loveth: I sought him, but I found him not."},
{name:'2233',l:'22',c:'3',v:'3',texto:"The watchmen that go about the city found me: to whom I said, Saw ye him whom my soul loveth?"},
{name:'2234',l:'22',c:'3',v:'4',texto:"It was but a little that I passed from them, but I found him whom my soul loveth: I held him, and would not let him go, until I had brought him into my mother's house, and into the chamber of her that conceived me."},
{name:'2235',l:'22',c:'3',v:'5',texto:"I charge you, O ye daughters of Jerusalem, by the roes, and by the hinds of the field, that ye stir not up, nor awake my love, till he please."},
{name:'2236',l:'22',c:'3',v:'6',texto:"Who is this that cometh out of the wilderness like pillars of smoke, perfumed with myrrh and frankincense, with all powders of the merchant?"},
{name:'2237',l:'22',c:'3',v:'7',texto:"Behold his bed, which is Solomon's; threescore valiant men are about it, of the valiant of Israel."},
{name:'2238',l:'22',c:'3',v:'8',texto:"They all hold swords, being expert in war: every man hath his sword upon his thigh because of fear in the night."},
{name:'2239',l:'22',c:'3',v:'9',texto:"King Solomon made himself a chariot of the wood of Lebanon."},
{name:'22310',l:'22',c:'3',v:'10',texto:"He made the pillars thereof of silver, the bottom thereof of gold, the covering of it of purple, the midst thereof being paved with love, for the daughters of Jerusalem."},
{name:'22311',l:'22',c:'3',v:'11',texto:"Go forth, O ye daughters of Zion, and behold king Solomon with the crown wherewith his mother crowned him in the day of his espousals, and in the day of the gladness of his heart."},
],
numVersiculos: 11,
},

c4: {
versiculos:[
{name:'2241',l:'22',c:'4',v:'1',texto:"Behold, thou art fair, my love; behold, thou art fair; thou hast doves' eyes within thy locks: thy hair is as a flock of goats, that appear from mount Gilead."},
{name:'2242',l:'22',c:'4',v:'2',texto:"Thy teeth are like a flock of sheep that are even shorn, which came up from the washing; whereof every one bear twins, and none is barren among them."},
{name:'2243',l:'22',c:'4',v:'3',texto:"Thy lips are like a thread of scarlet, and thy speech is comely: thy temples are like a piece of a pomegranate within thy locks."},
{name:'2244',l:'22',c:'4',v:'4',texto:"Thy neck is like the tower of David builded for an armoury, whereon there hang a thousand bucklers, all shields of mighty men."},
{name:'2245',l:'22',c:'4',v:'5',texto:"Thy two breasts are like two young roes that are twins, which feed among the lilies."},
{name:'2246',l:'22',c:'4',v:'6',texto:"Until the day break, and the shadows flee away, I will get me to the mountain of myrrh, and to the hill of frankincense."},
{name:'2247',l:'22',c:'4',v:'7',texto:"Thou art all fair, my love; there is no spot in thee."},
{name:'2248',l:'22',c:'4',v:'8',texto:"Come with me from Lebanon, my spouse, with me from Lebanon: look from the top of Amana, from the top of Shenir and Hermon, from the lions' dens, from the mountains of the leopards."},
{name:'2249',l:'22',c:'4',v:'9',texto:"Thou hast ravished my heart, my sister, my spouse; thou hast ravished my heart with one of thine eyes, with one chain of thy neck."},
{name:'22410',l:'22',c:'4',v:'10',texto:"How fair is thy love, my sister, my spouse! how much better is thy love than wine! and the smell of thine ointments than all spices!"},
{name:'22411',l:'22',c:'4',v:'11',texto:"Thy lips, O my spouse, drop as the honeycomb: honey and milk are under thy tongue; and the smell of thy garments is like the smell of Lebanon."},
{name:'22412',l:'22',c:'4',v:'12',texto:"A garden inclosed is my sister, my spouse; a spring shut up, a fountain sealed."},
{name:'22413',l:'22',c:'4',v:'13',texto:"Thy plants are an orchard of pomegranates, with pleasant fruits; camphire, with spikenard,"},
{name:'22414',l:'22',c:'4',v:'14',texto:"Spikenard and saffron; calamus and cinnamon, with all trees of frankincense; myrrh and aloes, with all the chief spices:"},
{name:'22415',l:'22',c:'4',v:'15',texto:"A fountain of gardens, a well of living waters, and streams from Lebanon."},
{name:'22416',l:'22',c:'4',v:'16',texto:"Awake, O north wind; and come, thou south; blow upon my garden, that the spices thereof may flow out. Let my beloved come into his garden, and eat his pleasant fruits."},
],
numVersiculos: 16,
},

c5: {
versiculos:[
{name:'2251',l:'22',c:'5',v:'1',texto:"I am come into my garden, my sister, my spouse: I have gathered my myrrh with my spice; I have eaten my honeycomb with my honey; I have drunk my wine with my milk: eat, O friends; drink, yea, drink abundantly, O beloved."},
{name:'2252',l:'22',c:'5',v:'2',texto:"I sleep, but my heart waketh: it is the voice of my beloved that knocketh, saying, Open to me, my sister, my love, my dove, my undefiled: for my head is filled with dew, and my locks with the drops of the night."},
{name:'2253',l:'22',c:'5',v:'3',texto:"I have put off my coat; how shall I put it on? I have washed my feet; how shall I defile them?"},
{name:'2254',l:'22',c:'5',v:'4',texto:"My beloved put in his hand by the hole of the door, and my bowels were moved for him."},
{name:'2255',l:'22',c:'5',v:'5',texto:"I rose up to open to my beloved; and my hands dropped with myrrh, and my fingers with sweet smelling myrrh, upon the handles of the lock."},
{name:'2256',l:'22',c:'5',v:'6',texto:"I opened to my beloved; but my beloved had withdrawn himself, and was gone: my soul failed when he spake: I sought him, but I could not find him; I called him, but he gave me no answer."},
{name:'2257',l:'22',c:'5',v:'7',texto:"The watchmen that went about the city found me, they smote me, they wounded me; the keepers of the walls took away my veil from me."},
{name:'2258',l:'22',c:'5',v:'8',texto:"I charge you, O daughters of Jerusalem, if ye find my beloved, that ye tell him, that I am sick of love."},
{name:'2259',l:'22',c:'5',v:'9',texto:"What is thy beloved more than another beloved, O thou fairest among women? what is thy beloved more than another beloved, that thou dost so charge us?"},
{name:'22510',l:'22',c:'5',v:'10',texto:"My beloved is white and ruddy, the chiefest among ten thousand."},
{name:'22511',l:'22',c:'5',v:'11',texto:"His head is as the most fine gold, his locks are bushy, and black as a raven."},
{name:'22512',l:'22',c:'5',v:'12',texto:"His eyes are as the eyes of doves by the rivers of waters, washed with milk, and fitly set."},
{name:'22513',l:'22',c:'5',v:'13',texto:"His cheeks are as a bed of spices, as sweet flowers: his lips like lilies, dropping sweet smelling myrrh."},
{name:'22514',l:'22',c:'5',v:'14',texto:"His hands are as gold rings set with the beryl: his belly is as bright ivory overlaid with sapphires."},
{name:'22515',l:'22',c:'5',v:'15',texto:"His legs are as pillars of marble, set upon sockets of fine gold: his countenance is as Lebanon, excellent as the cedars."},
{name:'22516',l:'22',c:'5',v:'16',texto:"His mouth is most sweet: yea, he is altogether lovely. This is my beloved, and this is my friend, O daughters of Jerusalem."},
],
numVersiculos: 16,
},

c6: {
versiculos:[
{name:'2261',l:'22',c:'6',v:'1',texto:"Whither is thy beloved gone, O thou fairest among women? whither is thy beloved turned aside? that we may seek him with thee."},
{name:'2262',l:'22',c:'6',v:'2',texto:"My beloved is gone down into his garden, to the beds of spices, to feed in the gardens, and to gather lilies."},
{name:'2263',l:'22',c:'6',v:'3',texto:"I am my beloved's, and my beloved is mine: he feedeth among the lilies."},
{name:'2264',l:'22',c:'6',v:'4',texto:"Thou art beautiful, O my love, as Tirzah, comely as Jerusalem, terrible as an army with banners."},
{name:'2265',l:'22',c:'6',v:'5',texto:"Turn away thine eyes from me, for they have overcome me: thy hair is as a flock of goats that appear from Gilead."},
{name:'2266',l:'22',c:'6',v:'6',texto:"Thy teeth are as a flock of sheep which go up from the washing, whereof every one beareth twins, and there is not one barren among them."},
{name:'2267',l:'22',c:'6',v:'7',texto:"As a piece of a pomegranate are thy temples within thy locks."},
{name:'2268',l:'22',c:'6',v:'8',texto:"There are threescore queens, and fourscore concubines, and virgins without number."},
{name:'2269',l:'22',c:'6',v:'9',texto:"My dove, my undefiled is but one; she is the only one of her mother, she is the choice one of her that bare her. The daughters saw her, and blessed her; yea, the queens and the concubines, and they praised her."},
{name:'22610',l:'22',c:'6',v:'10',texto:"Who is she that looketh forth as the morning, fair as the moon, clear as the sun, and terrible as an army with banners?"},
{name:'22611',l:'22',c:'6',v:'11',texto:"I went down into the garden of nuts to see the fruits of the valley, and to see whether the vine flourished, and the pomegranates budded."},
{name:'22612',l:'22',c:'6',v:'12',texto:"Or ever I was aware, my soul made me like the chariots of Amminadib."},
{name:'22613',l:'22',c:'6',v:'13',texto:"Return, return, O Shulamite; return, return, that we may look upon thee. What will ye see in the Shulamite? As it were the company of two armies."},
],
numVersiculos: 13,
},

c7: {
versiculos:[
{name:'2271',l:'22',c:'7',v:'1',texto:"How beautiful are thy feet with shoes, O prince's daughter! the joints of thy thighs are like jewels, the work of the hands of a cunning workman."},
{name:'2272',l:'22',c:'7',v:'2',texto:"Thy navel is like a round goblet, which wanteth not liquor: thy belly is like an heap of wheat set about with lilies."},
{name:'2273',l:'22',c:'7',v:'3',texto:"Thy two breasts are like two young roes that are twins."},
{name:'2274',l:'22',c:'7',v:'4',texto:"Thy neck is as a tower of ivory; thine eyes like the fishpools in Heshbon, by the gate of Bathrabbim: thy nose is as the tower of Lebanon which looketh toward Damascus."},
{name:'2275',l:'22',c:'7',v:'5',texto:"Thine head upon thee is like Carmel, and the hair of thine head like purple; the king is held in the galleries."},
{name:'2276',l:'22',c:'7',v:'6',texto:"How fair and how pleasant art thou, O love, for delights!"},
{name:'2277',l:'22',c:'7',v:'7',texto:"This thy stature is like to a palm tree, and thy breasts to clusters of grapes."},
{name:'2278',l:'22',c:'7',v:'8',texto:"I said, I will go up to the palm tree, I will take hold of the boughs thereof: now also thy breasts shall be as clusters of the vine, and the smell of thy nose like apples;"},
{name:'2279',l:'22',c:'7',v:'9',texto:"And the roof of thy mouth like the best wine for my beloved, that goeth down sweetly, causing the lips of those that are asleep to speak."},
{name:'22710',l:'22',c:'7',v:'10',texto:"I am my beloved's, and his desire is toward me."},
{name:'22711',l:'22',c:'7',v:'11',texto:"Come, my beloved, let us go forth into the field; let us lodge in the villages."},
{name:'22712',l:'22',c:'7',v:'12',texto:"Let us get up early to the vineyards; let us see if the vine flourish, whether the tender grape appear, and the pomegranates bud forth: there will I give thee my loves."},
{name:'22713',l:'22',c:'7',v:'13',texto:"The mandrakes give a smell, and at our gates are all manner of pleasant fruits, new and old, which I have laid up for thee, O my beloved."},
],
numVersiculos: 13,
},

c8: {
versiculos:[
{name:'2281',l:'22',c:'8',v:'1',texto:"O that thou wert as my brother, that sucked the breasts of my mother! when I should find thee without, I would kiss thee; yea, I should not be despised."},
{name:'2282',l:'22',c:'8',v:'2',texto:"I would lead thee, and bring thee into my mother's house, who would instruct me: I would cause thee to drink of spiced wine of the juice of my pomegranate."},
{name:'2283',l:'22',c:'8',v:'3',texto:"His left hand should be under my head, and his right hand should embrace me."},
{name:'2284',l:'22',c:'8',v:'4',texto:"I charge you, O daughters of Jerusalem, that ye stir not up, nor awake my love, until he please."},
{name:'2285',l:'22',c:'8',v:'5',texto:"Who is this that cometh up from the wilderness, leaning upon her beloved? I raised thee up under the apple tree: there thy mother brought thee forth: there she brought thee forth that bare thee."},
{name:'2286',l:'22',c:'8',v:'6',texto:"Set me as a seal upon thine heart, as a seal upon thine arm: for love is strong as death; jealousy is cruel as the grave: the coals thereof are coals of fire, which hath a most vehement flame."},
{name:'2287',l:'22',c:'8',v:'7',texto:"Many waters cannot quench love, neither can the floods drown it: if a man would give all the substance of his house for love, it would utterly be contemned."},
{name:'2288',l:'22',c:'8',v:'8',texto:"We have a little sister, and she hath no breasts: what shall we do for our sister in the day when she shall be spoken for?"},
{name:'2289',l:'22',c:'8',v:'9',texto:"If she be a wall, we will build upon her a palace of silver: and if she be a door, we will inclose her with boards of cedar."},
{name:'22810',l:'22',c:'8',v:'10',texto:"I am a wall, and my breasts like towers: then was I in his eyes as one that found favour."},
{name:'22811',l:'22',c:'8',v:'11',texto:"Solomon had a vineyard at Baalhamon; he let out the vineyard unto keepers; every one for the fruit thereof was to bring a thousand pieces of silver."},
{name:'22812',l:'22',c:'8',v:'12',texto:"My vineyard, which is mine, is before me: thou, O Solomon, must have a thousand, and those that keep the fruit thereof two hundred."},
{name:'22813',l:'22',c:'8',v:'13',texto:"Thou that dwellest in the gardens, the companions hearken to thy voice: cause me to hear it."},
{name:'22814',l:'22',c:'8',v:'14',texto:"Make haste, my beloved, and be thou like to a roe or to a young hart upon the mountains of spices."},
],
numVersiculos: 14,
},
	

};
