BibliaKJV.joel = {
	libro: "Joel",
	numCapitulos: 3,

c1: {
versiculos:[
{name:'2911',l:'29',c:'1',v:'1',texto:"The word of the LORD that came to Joel the son of Pethuel."},
{name:'2912',l:'29',c:'1',v:'2',texto:"Hear this, ye old men, and give ear, all ye inhabitants of the land. Hath this been in your days, or even in the days of your fathers?"},
{name:'2913',l:'29',c:'1',v:'3',texto:"Tell ye your children of it, and let your children tell their children, and their children another generation."},
{name:'2914',l:'29',c:'1',v:'4',texto:"That which the palmerworm hath left hath the locust eaten; and that which the locust hath left hath the cankerworm eaten; and that which the cankerworm hath left hath the caterpiller eaten."},
{name:'2915',l:'29',c:'1',v:'5',texto:"Awake, ye drunkards, and weep; and howl, all ye drinkers of wine, because of the new wine; for it is cut off from your mouth."},
{name:'2916',l:'29',c:'1',v:'6',texto:"For a nation is come up upon my land, strong, and without number, whose teeth are the teeth of a lion, and he hath the cheek teeth of a great lion."},
{name:'2917',l:'29',c:'1',v:'7',texto:"He hath laid my vine waste, and barked my fig tree: he hath made it clean bare, and cast it away; the branches thereof are made white."},
{name:'2918',l:'29',c:'1',v:'8',texto:"Lament like a virgin girded with sackcloth for the husband of her youth."},
{name:'2919',l:'29',c:'1',v:'9',texto:"The meat offering and the drink offering is cut off from the house of the LORD; the priests, the LORD'S ministers, mourn."},
{name:'29110',l:'29',c:'1',v:'10',texto:"The field is wasted, the land mourneth; for the corn is wasted: the new wine is dried up, the oil languisheth."},
{name:'29111',l:'29',c:'1',v:'11',texto:"Be ye ashamed, O ye husbandmen; howl, O ye vinedressers, for the wheat and for the barley; because the harvest of the field is perished."},
{name:'29112',l:'29',c:'1',v:'12',texto:"The vine is dried up, and the fig tree languisheth; the pomegranate tree, the palm tree also, and the apple tree, even all the trees of the field, are withered: because joy is withered away from the sons of men."},
{name:'29113',l:'29',c:'1',v:'13',texto:"Gird yourselves, and lament, ye priests: howl, ye ministers of the altar: come, lie all night in sackcloth, ye ministers of my God: for the meat offering and the drink offering is withholden from the house of your God."},
{name:'29114',l:'29',c:'1',v:'14',texto:"Sanctify ye a fast, call a solemn assembly, gather the elders and all the inhabitants of the land into the house of the LORD your God, and cry unto the LORD,"},
{name:'29115',l:'29',c:'1',v:'15',texto:"Alas for the day! for the day of the LORD is at hand, and as a destruction from the Almighty shall it come."},
{name:'29116',l:'29',c:'1',v:'16',texto:"Is not the meat cut off before our eyes, yea, joy and gladness from the house of our God?"},
{name:'29117',l:'29',c:'1',v:'17',texto:"The seed is rotten under their clods, the garners are laid desolate, the barns are broken down; for the corn is withered."},
{name:'29118',l:'29',c:'1',v:'18',texto:"How do the beasts groan! the herds of cattle are perplexed, because they have no pasture; yea, the flocks of sheep are made desolate."},
{name:'29119',l:'29',c:'1',v:'19',texto:"O LORD, to thee will I cry: for the fire hath devoured the pastures of the wilderness, and the flame hath burned all the trees of the field."},
{name:'29120',l:'29',c:'1',v:'20',texto:"The beasts of the field cry also unto thee: for the rivers of waters are dried up, and the fire hath devoured the pastures of the wilderness."},
],
numVersiculos: 20,
},

c2: {
versiculos:[
{name:'2921',l:'29',c:'2',v:'1',texto:"Blow ye the trumpet in Zion, and sound an alarm in my holy mountain: let all the inhabitants of the land tremble: for the day of the LORD cometh, for it is nigh at hand;"},
{name:'2922',l:'29',c:'2',v:'2',texto:"A day of darkness and of gloominess, a day of clouds and of thick darkness, as the morning spread upon the mountains: a great people and a strong; there hath not been ever the like, neither shall be any more after it, even to the years of many generations."},
{name:'2923',l:'29',c:'2',v:'3',texto:"A fire devoureth before them; and behind them a flame burneth: the land is as the garden of Eden before them, and behind them a desolate wilderness; yea, and nothing shall escape them."},
{name:'2924',l:'29',c:'2',v:'4',texto:"The appearance of them is as the appearance of horses; and as horsemen, so shall they run."},
{name:'2925',l:'29',c:'2',v:'5',texto:"Like the noise of chariots on the tops of mountains shall they leap, like the noise of a flame of fire that devoureth the stubble, as a strong people set in battle array."},
{name:'2926',l:'29',c:'2',v:'6',texto:"Before their face the people shall be much pained: all faces shall gather blackness."},
{name:'2927',l:'29',c:'2',v:'7',texto:"They shall run like mighty men; they shall climb the wall like men of war; and they shall march every one on his ways, and they shall not break their ranks:"},
{name:'2928',l:'29',c:'2',v:'8',texto:"Neither shall one thrust another; they shall walk every one in his path: and when they fall upon the sword, they shall not be wounded."},
{name:'2929',l:'29',c:'2',v:'9',texto:"They shall run to and fro in the city; they shall run upon the wall, they shall climb up upon the houses; they shall enter in at the windows like a thief."},
{name:'29210',l:'29',c:'2',v:'10',texto:"The earth shall quake before them; the heavens shall tremble: the sun and the moon shall be dark, and the stars shall withdraw their shining:"},
{name:'29211',l:'29',c:'2',v:'11',texto:"And the LORD shall utter his voice before his army: for his camp is very great: for he is strong that executeth his word: for the day of the LORD is great and very terrible; and who can abide it?"},
{name:'29212',l:'29',c:'2',v:'12',texto:"Therefore also now, saith the LORD, turn ye even to me with all your heart, and with fasting, and with weeping, and with mourning:"},
{name:'29213',l:'29',c:'2',v:'13',texto:"And rend your heart, and not your garments, and turn unto the LORD your God: for he is gracious and merciful, slow to anger, and of great kindness, and repenteth him of the evil."},
{name:'29214',l:'29',c:'2',v:'14',texto:"Who knoweth if he will return and repent, and leave a blessing behind him; even a meat offering and a drink offering unto the LORD your God?"},
{name:'29215',l:'29',c:'2',v:'15',texto:"Blow the trumpet in Zion, sanctify a fast, call a solemn assembly:"},
{name:'29216',l:'29',c:'2',v:'16',texto:"Gather the people, sanctify the congregation, assemble the elders, gather the children, and those that suck the breasts: let the bridegroom go forth of his chamber, and the bride out of her closet."},
{name:'29217',l:'29',c:'2',v:'17',texto:"Let the priests, the ministers of the LORD, weep between the porch and the altar, and let them say, Spare thy people, O LORD, and give not thine heritage to reproach, that the heathen should rule over them: wherefore should they say among the people, Where is their God?"},
{name:'29218',l:'29',c:'2',v:'18',texto:"Then will the LORD be jealous for his land, and pity his people."},
{name:'29219',l:'29',c:'2',v:'19',texto:"Yea, the LORD will answer and say unto his people, Behold, I will send you corn, and wine, and oil, and ye shall be satisfied therewith: and I will no more make you a reproach among the heathen:"},
{name:'29220',l:'29',c:'2',v:'20',texto:"But I will remove far off from you the northern army, and will drive him into a land barren and desolate, with his face toward the east sea, and his hinder part toward the utmost sea, and his stink shall come up, and his ill savour shall come up, because he hath done great things."},
{name:'29221',l:'29',c:'2',v:'21',texto:"Fear not, O land; be glad and rejoice: for the LORD will do great things."},
{name:'29222',l:'29',c:'2',v:'22',texto:"Be not afraid, ye beasts of the field: for the pastures of the wilderness do spring, for the tree beareth her fruit, the fig tree and the vine do yield their strength."},
{name:'29223',l:'29',c:'2',v:'23',texto:"Be glad then, ye children of Zion, and rejoice in the LORD your God: for he hath given you the former rain moderately, and he will cause to come down for you the rain, the former rain, and the latter rain in the first month."},
{name:'29224',l:'29',c:'2',v:'24',texto:"And the floors shall be full of wheat, and the fats shall overflow with wine and oil."},
{name:'29225',l:'29',c:'2',v:'25',texto:"And I will restore to you the years that the locust hath eaten, the cankerworm, and the caterpiller, and the palmerworm, my great army which I sent among you."},
{name:'29226',l:'29',c:'2',v:'26',texto:"And ye shall eat in plenty, and be satisfied, and praise the name of the LORD your God, that hath dealt wondrously with you: and my people shall never be ashamed."},
{name:'29227',l:'29',c:'2',v:'27',texto:"And ye shall know that I am in the midst of Israel, and that I am the LORD your God, and none else: and my people shall never be ashamed."},
{name:'29228',l:'29',c:'2',v:'28',texto:"And it shall come to pass afterward, that I will pour out my spirit upon all flesh; and your sons and your daughters shall prophesy, your old men shall dream dreams, your young men shall see visions:"},
{name:'29229',l:'29',c:'2',v:'29',texto:"And also upon the servants and upon the handmaids in those days will I pour out my spirit."},
{name:'29230',l:'29',c:'2',v:'30',texto:"And I will shew wonders in the heavens and in the earth, blood, and fire, and pillars of smoke."},
{name:'29231',l:'29',c:'2',v:'31',texto:"The sun shall be turned into darkness, and the moon into blood, before the great and the terrible day of the LORD come."},
{name:'29232',l:'29',c:'2',v:'32',texto:"And it shall come to pass, that whosoever shall call on the name of the LORD shall be delivered: for in mount Zion and in Jerusalem shall be deliverance, as the LORD hath said, and in the remnant whom the LORD shall call."},
],
numVersiculos: 32,
},

c3: {
versiculos:[
{name:'2931',l:'29',c:'3',v:'1',texto:"For, behold, in those days, and in that time, when I shall bring again the captivity of Judah and Jerusalem,"},
{name:'2932',l:'29',c:'3',v:'2',texto:"I will also gather all nations, and will bring them down into the valley of Jehoshaphat, and will plead with them there for my people and for my heritage Israel, whom they have scattered among the nations, and parted my land."},
{name:'2933',l:'29',c:'3',v:'3',texto:"And they have cast lots for my people; and have given a boy for an harlot, and sold a girl for wine, that they might drink."},
{name:'2934',l:'29',c:'3',v:'4',texto:"Yea, and what have ye to do with me, O Tyre, and Zidon, and all the coasts of Palestine? will ye render me a recompence? and if ye recompense me, swiftly and speedily will I return your recompence upon your own head;"},
{name:'2935',l:'29',c:'3',v:'5',texto:"Because ye have taken my silver and my gold, and have carried into your temples my goodly pleasant things:"},
{name:'2936',l:'29',c:'3',v:'6',texto:"The children also of Judah and the children of Jerusalem have ye sold unto the Grecians, that ye might remove them far from their border."},
{name:'2937',l:'29',c:'3',v:'7',texto:"Behold, I will raise them out of the place whither ye have sold them, and will return your recompence upon your own head:"},
{name:'2938',l:'29',c:'3',v:'8',texto:"And I will sell your sons and your daughters into the hand of the children of Judah, and they shall sell them to the Sabeans, to a people far off: for the LORD hath spoken it."},
{name:'2939',l:'29',c:'3',v:'9',texto:"Proclaim ye this among the Gentiles; Prepare war, wake up the mighty men, let all the men of war draw near; let them come up:"},
{name:'29310',l:'29',c:'3',v:'10',texto:"Beat your plowshares into swords, and your pruninghooks into spears: let the weak say, I am strong."},
{name:'29311',l:'29',c:'3',v:'11',texto:"Assemble yourselves, and come, all ye heathen, and gather yourselves together round about: thither cause thy mighty ones to come down, O LORD."},
{name:'29312',l:'29',c:'3',v:'12',texto:"Let the heathen be wakened, and come up to the valley of Jehoshaphat: for there will I sit to judge all the heathen round about."},
{name:'29313',l:'29',c:'3',v:'13',texto:"Put ye in the sickle, for the harvest is ripe: come, get you down; for the press is full, the fats overflow; for their wickedness is great."},
{name:'29314',l:'29',c:'3',v:'14',texto:"Multitudes, multitudes in the valley of decision: for the day of the LORD is near in the valley of decision."},
{name:'29315',l:'29',c:'3',v:'15',texto:"The sun and the moon shall be darkened, and the stars shall withdraw their shining."},
{name:'29316',l:'29',c:'3',v:'16',texto:"The LORD also shall roar out of Zion, and utter his voice from Jerusalem; and the heavens and the earth shall shake: but the LORD will be the hope of his people, and the strength of the children of Israel."},
{name:'29317',l:'29',c:'3',v:'17',texto:"So shall ye know that I am the LORD your God dwelling in Zion, my holy mountain: then shall Jerusalem be holy, and there shall no strangers pass through her any more."},
{name:'29318',l:'29',c:'3',v:'18',texto:"And it shall come to pass in that day, that the mountains shall drop down new wine, and the hills shall flow with milk, and all the rivers of Judah shall flow with waters, and a fountain shall come forth of the house of the LORD, and shall water the valley of Shittim."},
{name:'29319',l:'29',c:'3',v:'19',texto:"Egypt shall be a desolation, and Edom shall be a desolate wilderness, for the violence against the children of Judah, because they have shed innocent blood in their land."},
{name:'29320',l:'29',c:'3',v:'20',texto:"But Judah shall dwell for ever, and Jerusalem from generation to generation."},
{name:'29321',l:'29',c:'3',v:'21',texto:"For I will cleanse their blood that I have not cleansed: for the LORD dwelleth in Zion."},
],
numVersiculos: 21,
},


};
