BibliaJFA.esdras = {
	libro: "Esdras",
	numCapitulos: 10,

c1: {
versiculos:[
{name:'1511',l:'15',c:'1',v:'1',texto:"No primeiro ano de Ciro, rei da Pérsia ( para que se cumprisse a palavra do SENHOR, por boca de Jeremias ), despertou o SENHOR o espírito de Ciro, rei da Pérsia, o qual fez passar pregão por todo o seu reino, como também por escrito, dizendo:" },
{name:'1512',l:'15',c:'1',v:'2',texto:"Assim diz Ciro, rei da Pérsia: O SENHOR, Deus dos céus, me deu todos os reinos da terra; e ele me encarregou de lhe edificar uma casa em Jerusalém, que é em Judá." },
{name:'1513',l:'15',c:'1',v:'3',texto:"Quem há entre vós, de todo o seu povo, seja seu Deus com ele, e suba a Jerusalém, que é em Judá, e edifique a Casa do SENHOR, Deus de Israel; ele é o Deus que habita em Jerusalém." },
{name:'1514',l:'15',c:'1',v:'4',texto:"E todo aquele que ficar em alguns lugares em que andar peregrinando, os homens do seu lugar o ajudarão com prata, e com ouro, e com fazenda, e com gados, afora as dádivas voluntárias para a Casa de Deus, que habita em Jerusalém." },
{name:'1515',l:'15',c:'1',v:'5',texto:"Então, se levantaram os chefes dos pais de Judá e Benjamim, e os sacerdotes, e os levitas, com todos aqueles cujo espírito Deus despertou, para subirem a edificar a Casa do SENHOR, que está em Jerusalém." },
{name:'1516',l:'15',c:'1',v:'6',texto:"E todos os que habitavam nos arredores lhes confortaram as mãos com objetos de prata, e com ouro, e com fazenda, e com gados, e com coisas preciosas, afora tudo o que voluntariamente se deu." },
{name:'1517',l:'15',c:'1',v:'7',texto:"Também o rei Ciro tirou os utensílios da Casa do SENHOR, que Nabucodonosor tinha trazido de Jerusalém e que tinha posto na casa de seus deuses." },
{name:'1518',l:'15',c:'1',v:'8',texto:"Estes tirou Ciro, rei da Pérsia, pela mão de Mitredate, o tesoureiro, que os deu por conta a Sesbazar, príncipe de Judá." },
{name:'1519',l:'15',c:'1',v:'9',texto:"E este é o número deles: trinta bacias de ouro, mil bacias de prata, vinte e nove facas," },
{name:'15110',l:'15',c:'1',v:'10',texto:"trinta taças de ouro, quatrocentas e dez taças de prata doutra espécie e mil outros objetos." },
{name:'15111',l:'15',c:'1',v:'11',texto:"Todos os utensílios de ouro e de prata foram cinco mil e quatrocentos; todos estes levou Sesbazar, quando os do cativeiro subiram de Babilônia para Jerusalém." },
],
numVersiculos: 11,
},

c2: {
versiculos:[
{name:'1521',l:'15',c:'2',v:'1',texto:"Estes são os filhos da província que subiram do cativeiro, dos transportados que Nabucodonosor, rei de Babilônia, tinha levado para Babilônia, e tornaram a Jerusalém e a Judá, cada um para a sua casa," },
{name:'1522',l:'15',c:'2',v:'2',texto:"os quais vieram com Zorobabel, Jesua, Neemias, Seraías, Reelaías, Mardoqueu, Bilsã, Mispar, Bigvai, Reum e Baaná. O número dos homens do povo de Israel:" },
{name:'1523',l:'15',c:'2',v:'3',texto:"os filhos de Parós, dois mil cento e setenta e dois." },
{name:'1524',l:'15',c:'2',v:'4',texto:"Os filhos de Sefatias, trezentos e setenta e dois." },
{name:'1525',l:'15',c:'2',v:'5',texto:"Os filhos de Ará, setecentos e setenta e cinco." },
{name:'1526',l:'15',c:'2',v:'6',texto:"Os filhos de Paate-Moabe, dos filhos de Jesua-Joabe, dois mil oitocentos e doze." },
{name:'1527',l:'15',c:'2',v:'7',texto:"Os filhos de Elão, mil duzentos e cinqüenta e quatro." },
{name:'1528',l:'15',c:'2',v:'8',texto:"Os filhos de Zatu, novecentos e quarenta e cinco." },
{name:'1529',l:'15',c:'2',v:'9',texto:"Os filhos de Zacai, setecentos e sessenta." },
{name:'15210',l:'15',c:'2',v:'10',texto:"Os filhos de Bani, seiscentos e quarenta e dois." },
{name:'15211',l:'15',c:'2',v:'11',texto:"Os filhos de Bebai, seiscentos e vinte e três." },
{name:'15212',l:'15',c:'2',v:'12',texto:"Os filhos de Azgade, mil duzentos e vinte e dois." },
{name:'15213',l:'15',c:'2',v:'13',texto:"Os filhos de Adonicão, seiscentos e sessenta e seis." },
{name:'15214',l:'15',c:'2',v:'14',texto:"Os filhos de Bigvai, dois mil e cinqüenta e seis." },
{name:'15215',l:'15',c:'2',v:'15',texto:"Os filhos de Adim, quatrocentos e cinqüenta e quatro." },
{name:'15216',l:'15',c:'2',v:'16',texto:"Os filhos de Ater, de Ezequias, noventa e oito." },
{name:'15217',l:'15',c:'2',v:'17',texto:"Os filhos de Besai, trezentos e vinte e três." },
{name:'15218',l:'15',c:'2',v:'18',texto:"Os filhos de Jora, cento e doze." },
{name:'15219',l:'15',c:'2',v:'19',texto:"Os filhos de Hasum, duzentos e vinte e três." },
{name:'15220',l:'15',c:'2',v:'20',texto:"Os filhos de Gibar, noventa e cinco." },
{name:'15221',l:'15',c:'2',v:'21',texto:"Os filhos de Belém, cento e vinte e três." },
{name:'15222',l:'15',c:'2',v:'22',texto:"Os homens de Netofa, cinqüenta e seis." },
{name:'15223',l:'15',c:'2',v:'23',texto:"Os homens de Anatote, cento e vinte e oito." },
{name:'15224',l:'15',c:'2',v:'24',texto:"Os filhos de Azmavete, quarenta e dois." },
{name:'15225',l:'15',c:'2',v:'25',texto:"Os filhos de Quiriate-Arim, Cefira e Beerote, setecentos e quarenta e três." },
{name:'15226',l:'15',c:'2',v:'26',texto:"Os filhos de Ramá e Gibeá, seiscentos e vinte e um." },
{name:'15227',l:'15',c:'2',v:'27',texto:"Os homens de Micmás, cento e vinte e dois." },
{name:'15228',l:'15',c:'2',v:'28',texto:"Os homens de Betel e Ai, duzentos e vinte e três." },
{name:'15229',l:'15',c:'2',v:'29',texto:"Os filhos de Nebo, cinqüenta e dois." },
{name:'15230',l:'15',c:'2',v:'30',texto:"Os filhos de Magbis, cento e cinqüenta e seis." },
{name:'15231',l:'15',c:'2',v:'31',texto:"Os filhos do outro Elão, mil duzentos e cinqüenta e quatro." },
{name:'15232',l:'15',c:'2',v:'32',texto:"Os filhos de Harim, trezentos e vinte." },
{name:'15233',l:'15',c:'2',v:'33',texto:"Os filhos de Lode, Hadide e Ono, setecentos e vinte e cinco." },
{name:'15234',l:'15',c:'2',v:'34',texto:"Os filhos de Jericó, trezentos e quarenta e cinco." },
{name:'15235',l:'15',c:'2',v:'35',texto:"Os filhos de Senaá, três mil seiscentos e trinta." },
{name:'15236',l:'15',c:'2',v:'36',texto:"Os sacerdotes: os filhos de Jedaías, da casa de Jesua, novecentos e setenta e três." },
{name:'15237',l:'15',c:'2',v:'37',texto:"Os filhos de Imer, mil e cinqüenta e dois." },
{name:'15238',l:'15',c:'2',v:'38',texto:"Os filhos de Pasur, mil duzentos e quarenta e sete." },
{name:'15239',l:'15',c:'2',v:'39',texto:"Os filhos de Harim, mil e dezessete." },
{name:'15240',l:'15',c:'2',v:'40',texto:"Os levitas: os filhos de Jesua e Cadmiel, dos filhos de Hodavias, setenta e quatro." },
{name:'15241',l:'15',c:'2',v:'41',texto:"Os cantores: os filhos de Asafe, cento e vinte e oito." },
{name:'15242',l:'15',c:'2',v:'42',texto:"Os filhos dos porteiros: os filhos de Salum, os filhos de Ater, os filhos de Talmom, os filhos de Acube, os filhos de Hatita, os filhos de Sobai, por todos, cento e trinta e nove." },
{name:'15243',l:'15',c:'2',v:'43',texto:"Os netineus: os filhos de Zia, os filhos de Hasufa, os filhos de Tabaote," },
{name:'15244',l:'15',c:'2',v:'44',texto:"os filhos de Queros, os filhos de Sia, os filhos de Padom," },
{name:'15245',l:'15',c:'2',v:'45',texto:"os filhos de Lebana, os filhos de Hagaba, os filhos de Acube," },
{name:'15246',l:'15',c:'2',v:'46',texto:"os filhos de Hagabe, os filhos de Sanlai, os filhos de Hanã," },
{name:'15247',l:'15',c:'2',v:'47',texto:"os filhos de Gidel, os filhos de Gaar, os filhos de Reaías," },
{name:'15248',l:'15',c:'2',v:'48',texto:"os filhos de Rezim, os filhos de Necoda, os filhos de Gazão," },
{name:'15249',l:'15',c:'2',v:'49',texto:"os filhos de Uzá, os filhos de Paséia, os filhos de Besai," },
{name:'15250',l:'15',c:'2',v:'50',texto:"os filhos de Asná, os filhos dos meunitas, os filhos dos nefuseus," },
{name:'15251',l:'15',c:'2',v:'51',texto:"os filhos de Baquebuque, os filhos de Hacufa, os filhos de Harur," },
{name:'15252',l:'15',c:'2',v:'52',texto:"os filhos de Baslute, os filhos de Meida, os filhos de Harsa," },
{name:'15253',l:'15',c:'2',v:'53',texto:"os filhos de Barcos, os filhos de Sísera, os filhos de Temá," },
{name:'15254',l:'15',c:'2',v:'54',texto:"os filhos de Nesias, os filhos de Hatifa," },
{name:'15255',l:'15',c:'2',v:'55',texto:"os filhos dos servos de Salomão: os filhos de Sotai, os filhos de Soferete, os filhos de Peruda," },
{name:'15256',l:'15',c:'2',v:'56',texto:"os filhos de Jaala, os filhos de Darcom, os filhos de Gidel," },
{name:'15257',l:'15',c:'2',v:'57',texto:"os filhos de Sefatias, os filhos de Hatil, os filhos de Poquerete-Hazebaim, os filhos de Ami." },
{name:'15258',l:'15',c:'2',v:'58',texto:"Todos os netineus e os filhos dos servos de Salomão, trezentos e noventa e dois." },
{name:'15259',l:'15',c:'2',v:'59',texto:"Também estes subiram de Tel-Melá e Tel-Harsa, Querube, Adã e Imer, porém não puderam mostrar a casa de seus pais e sua linhagem, se de Israel eram." },
{name:'15260',l:'15',c:'2',v:'60',texto:"Os filhos de Delaías, os filhos de Tobias, os filhos de Necoda, seiscentos e cinqüenta e dois." },
{name:'15261',l:'15',c:'2',v:'61',texto:"E dos filhos dos sacerdotes: os filhos de Habaías, os filhos de Coz, os filhos de Barzilai, que tomou mulher das filhas de Barzilai, o gileadita, e que foi chamado do seu nome." },
{name:'15262',l:'15',c:'2',v:'62',texto:"Estes buscaram o seu registro entre os que estavam registrados nas genealogias, mas não se acharam nelas; pelo que por imundos foram rejeitados do sacerdócio." },
{name:'15263',l:'15',c:'2',v:'63',texto:"E o tirsata lhes disse que não comessem das coisas sagradas até que houvesse sacerdote com Urim e com Tumim." },
{name:'15264',l:'15',c:'2',v:'64',texto:"Toda essa congregação junta foi de quarenta e dois mil trezentos e sessenta," },
{name:'15265',l:'15',c:'2',v:'65',texto:"afora os seus servos e as suas servas, que foram sete mil trezentos e trinta e sete; também tinham duzentos cantores e cantoras." },
{name:'15266',l:'15',c:'2',v:'66',texto:"Os seus cavalos, setecentos e trinta e seis; os seus mulos, duzentos e quarenta e cinco;" },
{name:'15267',l:'15',c:'2',v:'67',texto:"os seus camelos, quatrocentos e trinta e cinco; os jumentos, seis mil setecentos e vinte." },
{name:'15268',l:'15',c:'2',v:'68',texto:"E alguns dos chefes dos pais, vindo à Casa do SENHOR, que habita em Jerusalém, deram voluntárias ofertas para a Casa de Deus, para a fundarem no seu lugar." },
{name:'15269',l:'15',c:'2',v:'69',texto:"Conforme o seu poder, deram para o tesouro da obra, em ouro, sessenta e um mil daricos, e, em prata, cinco mil arráteis, e cem vestes sacerdotais." },
{name:'15270',l:'15',c:'2',v:'70',texto:"E habitaram os sacerdotes, e os levitas, e alguns do povo, tanto os cantores como os porteiros e os netineus nas suas cidades, como também todo o Israel nas suas cidades." },
],
numVersiculos: 70,
},

c3: {
versiculos:[
{name:'1531',l:'15',c:'3',v:'1',texto:"Chegando, pois, o sétimo mês e estando os filhos de Israel já nas cidades, se ajuntou o povo, como um só homem, em Jerusalém." },
{name:'1532',l:'15',c:'3',v:'2',texto:"E levantou-se Jesua, filho de Jozadaque, e seus irmãos, os sacerdotes, e Zorobabel, filho de Sealtiel, e seus irmãos e edificaram o altar do Deus de Israel, para oferecerem sobre ele holocaustos, como está escrito na Lei de Moisés, o homem de Deus." },
{name:'1533',l:'15',c:'3',v:'3',texto:"E firmaram o altar sobre as suas bases, porque o terror estava sobre eles, por causa dos povos das terras; e ofereceram sobre ele holocaustos ao SENHOR, holocaustos de manhã e de tarde." },
{name:'1534',l:'15',c:'3',v:'4',texto:"E celebraram a Festa dos Tabernáculos, como está escrito, e ofereceram holocaustos de dia em dia, por ordem, conforme o rito, cada coisa no seu dia;" },
{name:'1535',l:'15',c:'3',v:'5',texto:"e, depois disso, o holocausto contínuo e os das luas novas e de todas as solenidades consagradas ao SENHOR, como também de qualquer que oferecia oferta voluntária ao SENHOR." },
{name:'1536',l:'15',c:'3',v:'6',texto:"Desde o primeiro dia do sétimo mês, começaram a oferecer holocaustos ao SENHOR; porém ainda não estavam postos os fundamentos do templo do SENHOR." },
{name:'1537',l:'15',c:'3',v:'7',texto:"Deram, pois, o dinheiro aos cortadores e artífices, como também comida, e bebida, e azeite aos sidônios e aos tírios, para trazerem do Líbano madeira de cedro ao mar, para Jope, segundo a concessão que lhes tinha feito Ciro, rei da Pérsia." },
{name:'1538',l:'15',c:'3',v:'8',texto:"E, no segundo ano da sua vinda à Casa de Deus, em Jerusalém, no segundo mês, começaram Zorobabel, filho de Sealtiel, e Jesua, filho de Jozadaque, e os outros seus irmãos, os sacerdotes e os levitas, e todos os que vieram do cativeiro a Jerusalém e constituíram levitas da idade de vinte anos e daí para cima, para que aviassem a obra da Casa do SENHOR." },
{name:'1539',l:'15',c:'3',v:'9',texto:"Então, se levantou Jesua, seus filhos e seus irmãos, Cadmiel e seus filhos, os filhos de Judá, como um só homem, para vigiarem os que faziam a obra na Casa de Deus, os filhos de Henadade, seus filhos e seus irmãos, os levitas." },
{name:'15310',l:'15',c:'3',v:'10',texto:"Quando, pois, os edificadores lançaram os alicerces do templo do SENHOR, então, apresentaram-se os sacerdotes, já paramentados e com trombetas, e os levitas, filhos de Asafe, com saltérios, para louvarem ao SENHOR, conforme a instituição de Davi, rei de Israel." },
{name:'15311',l:'15',c:'3',v:'11',texto:"E cantavam a revezes, louvando e celebrando ao SENHOR, porque é bom; porque a sua benignidade dura para sempre sobre Israel. E todo o povo jubilou com grande júbilo, quando louvou o SENHOR, pela fundação da Casa do SENHOR." },
{name:'15312',l:'15',c:'3',v:'12',texto:"Porém muitos dos sacerdotes, e levitas, e chefes dos pais, já velhos, que viram a primeira casa sobre o seu fundamento, vendo perante os seus olhos esta casa, choraram em altas vozes; mas muitos levantaram as vozes com júbilo e com alegria." },
{name:'15313',l:'15',c:'3',v:'13',texto:"De maneira que não discernia o povo as vozes de alegria das vozes do choro do povo; porque o povo jubilava com tão grande júbilo, que as vozes se ouviam de mui longe." },
],
numVersiculos: 13,
},

c4: {
versiculos:[
{name:'1541',l:'15',c:'4',v:'1',texto:"Ouvindo, pois, os adversários de Judá e Benjamim que os que tornaram do cativeiro edificavam o templo ao SENHOR, Deus de Israel," },
{name:'1542',l:'15',c:'4',v:'2',texto:"chegaram-se a Zorobabel e aos chefes dos pais e disseram-lhes: Deixai-nos edificar convosco, porque, como vós, buscaremos a vosso Deus; como também já lhe sacrificamos desde os dias de Esar-Hadom, rei da Assíria, que nos mandou vir para aqui." },
{name:'1543',l:'15',c:'4',v:'3',texto:"Porém Zorobabel, e Jesua, e os outros chefes dos pais de Israel lhes disseram: Não convém que vós e nós edifiquemos casa a nosso Deus; mas nós, sós, a edificaremos ao SENHOR, Deus de Israel, como nos ordenou o rei Ciro, rei da Pérsia." },
{name:'1544',l:'15',c:'4',v:'4',texto:"Todavia, o povo da terra debilitava as mãos do povo de Judá e inquietava-os no edificar." },
{name:'1545',l:'15',c:'4',v:'5',texto:"E alugaram contra eles conselheiros para frustrarem o seu plano, todos os dias de Ciro, rei da Pérsia, até ao reinado de Dario, rei da Pérsia." },
{name:'1546',l:'15',c:'4',v:'6',texto:"E sob o reinado de Assuero, no princípio do seu reinado, escreveram uma acusação contra os habitantes de Judá e de Jerusalém." },
{name:'1547',l:'15',c:'4',v:'7',texto:"E, nos dias de Artaxerxes, escreveu Bislão, Mitredate, Tabeel e os outros da sua companhia a Artaxerxes, rei da Pérsia; e a carta estava escrita em caracteres aramaicos e na língua siríaca." },
{name:'1548',l:'15',c:'4',v:'8',texto:"Escreveram, pois, Reum, o chanceler, e Sinsai, o escrivão, uma carta contra Jerusalém, ao rei Artaxerxes, nesta maneira." },
{name:'1549',l:'15',c:'4',v:'9',texto:"Então, escreveu Reum, o chanceler, e Sinsai, o escrivão, e os outros da sua companhia: dinaítas e afarsaquitas, tarpelitas, afarsitas, arquevitas, babilônios, susanquitas, deavitas, elamitas" },
{name:'15410',l:'15',c:'4',v:'10',texto:"e outros povos, que o grande e afamado Osnapar transportou e que fez habitar na cidade de Samaria, e os outros dalém do rio e em tal tempo." },
{name:'15411',l:'15',c:'4',v:'11',texto:"Este, pois, é o teor da carta que ao rei Artaxerxes lhe mandaram: Teus servos, os homens daquém do rio e em tal tempo." },
{name:'15412',l:'15',c:'4',v:'12',texto:"Saiba o rei que os judeus que subiram de ti vieram a nós a Jerusalém, e edificam aquela rebelde e malvada cidade, e vão restaurando os seus muros, e reparando os seus fundamentos." },
{name:'15413',l:'15',c:'4',v:'13',texto:"Agora, saiba o rei que, se aquela cidade se reedificar, e os muros se restaurarem, eles não pagarão os direitos, os tributos e as rendas; e assim se danificará a fazenda dos reis." },
{name:'15414',l:'15',c:'4',v:'14',texto:"Agora, pois, como somos assalariados do paço, e não nos convém ver a desonra do rei, por isso mandamos dar aviso ao rei," },
{name:'15415',l:'15',c:'4',v:'15',texto:"para que se busque no livro das crônicas de teus pais, e, então, acharás no livro das crônicas e saberás que aquela foi uma cidade rebelde e danosa aos reis e províncias e que nela houve rebelião em tempos antigos; pelo que foi aquela cidade destruída." },
{name:'15416',l:'15',c:'4',v:'16',texto:"Nós, pois, fazemos notório ao rei que, se aquela cidade se reedificar e os seus muros se restaurarem, desta maneira não terás porção alguma desta banda do rio." },
{name:'15417',l:'15',c:'4',v:'17',texto:"E o rei enviou esta resposta a Reum, o chanceler, e a Sinsai, o escrivão, e aos mais da sua companhia, que habitavam em Samaria; como também ao resto dos que estavam dalém do rio: Paz! E em tal tempo." },
{name:'15418',l:'15',c:'4',v:'18',texto:"A carta que nos enviastes foi explicitamente lida diante de mim." },
{name:'15419',l:'15',c:'4',v:'19',texto:"E, ordenando-o eu, buscaram e acharam que, de tempos antigos, aquela cidade se levantou contra os reis, e nela se tem feito rebelião e sedição." },
{name:'15420',l:'15',c:'4',v:'20',texto:"Também houve reis poderosos sobre Jerusalém, que dalém do rio dominaram em todo lugar, e se lhes pagaram direitos, e tributos, e rendas." },
{name:'15421',l:'15',c:'4',v:'21',texto:"Agora, pois, dai ordem para que aqueles homens parem, a fim de que não se edifique aquela cidade, até que se dê uma ordem por mim." },
{name:'15422',l:'15',c:'4',v:'22',texto:"E guardai-vos de cometerdes erro nisso; por que cresceria o dano para prejuízo dos reis?" },
{name:'15423',l:'15',c:'4',v:'23',texto:"Então, depois que a cópia da carta do rei Artaxerxes se leu perante Reum, e Sinsai, o escrivão, e seus companheiros, apressadamente foram eles a Jerusalém, aos judeus, e os impediram à força de braço e com violência." },
{name:'15424',l:'15',c:'4',v:'24',texto:"Então, cessou a obra da Casa de Deus, que estava em Jerusalém, e cessou até ao ano segundo do reinado de Dario, rei da Pérsia." },
],
numVersiculos: 24,
},

c5: {
versiculos:[
{name:'1551',l:'15',c:'5',v:'1',texto:"E Ageu, profeta, e Zacarias, filho de Ido, profeta, profetizaram aos judeus que estavam em Judá e em Jerusalém; em nome do Deus de Israel lhes profetizaram." },
{name:'1552',l:'15',c:'5',v:'2',texto:"Então, se levantaram Zorobabel, filho de Sealtiel, e Jesua, filho de Jozadaque, e começaram a edificar a Casa de Deus, que está em Jerusalém; e com eles os profetas de Deus, que os ajudavam." },
{name:'1553',l:'15',c:'5',v:'3',texto:"Naquele tempo, veio a eles Tatenai, governador daquém do rio, e Setar-Bozenai, e os seus companheiros e disseram-lhes assim: Quem vos deu ordem para edificardes esta casa e restaurardes este muro?" },
{name:'1554',l:'15',c:'5',v:'4',texto:"Então, assim lhes dissemos: E quais são os nomes dos homens que construíram este edifício?" },
{name:'1555',l:'15',c:'5',v:'5',texto:"Porém os olhos de Deus estavam sobre os anciãos dos judeus, e não os impediram, até que o negócio veio a Dario, e, então, responderam por carta sobre isso." },
{name:'1556',l:'15',c:'5',v:'6',texto:"Cópia da carta que Tatenai, o governador daquém do rio, com Setar-Bozenai e os seus companheiros, os afarsaquitas, que estavam daquém do rio, enviaram ao rei Dario." },
{name:'1557',l:'15',c:'5',v:'7',texto:"Enviaram-lhe uma relação; e assim estava escrito nela: Toda a paz ao rei Dario." },
{name:'1558',l:'15',c:'5',v:'8',texto:"Seja notório ao rei que nós fomos à província de Judá, à casa do grande Deus, que se edifica com grandes pedras, e já a madeira se está pondo sobre as paredes; e essa obra apressuradamente se faz e se adianta em suas mãos." },
{name:'1559',l:'15',c:'5',v:'9',texto:"Então, perguntamos aos anciãos e assim lhes dissemos: Quem vos deu ordem para edificardes esta casa e restaurardes este muro?" },
{name:'15510',l:'15',c:'5',v:'10',texto:"Demais disto, lhes perguntamos também pelos seus nomes, para tos declararmos, para que te pudéssemos escrever os nomes dos homens que são entre eles os chefes." },
{name:'15511',l:'15',c:'5',v:'11',texto:"E esta resposta nos deram, dizendo: Nós somos servos do Deus dos céus e da terra e reedificamos a casa que foi edificada muitos anos antes; porque um grande rei de Israel a edificou e a aperfeiçoou." },
{name:'15512',l:'15',c:'5',v:'12',texto:"Mas, depois que nossos pais provocaram à ira o Deus dos céus, ele os entregou nas mãos de Nabucodonosor, rei de Babilônia, o caldeu, o qual destruiu esta casa e transportou o seu povo para Babilônia." },
{name:'15513',l:'15',c:'5',v:'13',texto:"Porém, no primeiro ano de Ciro, rei de Babilônia, o rei Ciro deu ordem para que esta Casa de Deus se edificasse." },
{name:'15514',l:'15',c:'5',v:'14',texto:"E até os utensílios de ouro e de prata, da Casa de Deus, que Nabucodonosor tomou do templo que estava em Jerusalém e os meteu no templo de Babilônia, o rei Ciro os tirou do templo de Babilônia, e foram dados a um homem cujo nome era Sesbazar, a quem nomeou governador." },
{name:'15515',l:'15',c:'5',v:'15',texto:"E disse-lhe: Toma estes utensílios, e vai, e leva-os ao templo que está em Jerusalém, e faze edificar a Casa de Deus, no seu lugar." },
{name:'15516',l:'15',c:'5',v:'16',texto:"Então, veio o dito Sesbazar e pôs os fundamentos da Casa de Deus, que está em Jerusalém; e desde então para cá se está edificando e ainda não está acabada." },
{name:'15517',l:'15',c:'5',v:'17',texto:"Agora, pois, se parece bem ao rei, busque-se lá na casa dos tesouros do rei, que está em Babilônia, se é verdade haver uma ordem do rei Ciro para edificar esta Casa de Deus em Jerusalém; e sobre isso nos faça o rei saber a sua vontade." },
],
numVersiculos: 17,
},

c6: {
versiculos:[
{name:'1561',l:'15',c:'6',v:'1',texto:"Então, o rei Dario deu ordem, e buscaram na chancelaria, onde se metiam os tesouros em Babilônia." },
{name:'1562',l:'15',c:'6',v:'2',texto:"E em Acmetá, no palácio que está na província de Média, se achou um rolo, e nele estava escrito um memorial, que dizia assim:" },
{name:'1563',l:'15',c:'6',v:'3',texto:"No ano primeiro do rei Ciro, o rei Ciro deu esta ordem: Com respeito à Casa de Deus em Jerusalém, essa casa se edificará para lugar em que se ofereçam sacrifícios, e seus fundamentos serão firmes; a sua altura, de sessenta côvados, e a sua largura, de sessenta côvados," },
{name:'1564',l:'15',c:'6',v:'4',texto:"com três carreiras de grandes pedras e uma carreira de madeira nova; e a despesa se fará da casa do rei." },
{name:'1565',l:'15',c:'6',v:'5',texto:"Demais disto, os utensílios de ouro e de prata da Casa de Deus, que Nabucodonosor transportou do templo que estava em Jerusalém e levou para Babilônia, se tornarão a dar, para que vão ao seu lugar, ao templo que está em Jerusalém, e os levarão à Casa de Deus." },
{name:'1566',l:'15',c:'6',v:'6',texto:"Agora, pois, Tatenai, governador de além do rio, Setar-Bozenai e os seus companheiros, os afarsaquitas, que estais de além do rio, apartai-vos dali." },
{name:'1567',l:'15',c:'6',v:'7',texto:"Deixa-os na obra desta Casa de Deus, para que o governador dos judeus e os judeus edifiquem esta Casa de Deus no seu lugar." },
{name:'1568',l:'15',c:'6',v:'8',texto:"Também por mim se decreta o que haveis de fazer com os anciãos dos judeus, para que edifiquem a Casa de Deus, a saber, que da fazenda do rei, dos tributos dalém do rio, se pague prontamente a despesa a estes homens, para que não sejam impedidos." },
{name:'1569',l:'15',c:'6',v:'9',texto:"E o que for necessário, como bezerros, e carneiros, e cordeiros, para holocausto ao Deus dos céus, trigo, sal, vinho e azeite, segundo o rito dos sacerdotes que estão em Jerusalém, dê-se-lhes de dia em dia, para que não haja falta;" },
{name:'15610',l:'15',c:'6',v:'10',texto:"para que ofereçam sacrifícios de cheiro suave ao Deus dos céus e orem pela vida do rei e de seus filhos." },
{name:'15611',l:'15',c:'6',v:'11',texto:"Também por mim se decreta que todo homem que mudar este decreto, um madeiro se arrancará da sua casa, e, levantado, o pendurarão nele, e da sua casa se fará por isso um monturo." },
{name:'15612',l:'15',c:'6',v:'12',texto:"O Deus, pois, que fez habitar ali o seu nome derribe a todos os reis e povos que estenderem a sua mão para o mudarem e para destruírem esta Casa de Deus, que está em Jerusalém. Eu, Dario, dei o decreto; apressuradamente se execute." },
{name:'15613',l:'15',c:'6',v:'13',texto:"Então, Tatenai, o governador de além do rio, Setar-Bozenai e os seus companheiros assim fizeram apressuradamente, conforme o que decretara o rei Dario." },
{name:'15614',l:'15',c:'6',v:'14',texto:"E os anciãos dos judeus iam edificando e prosperando pela profecia do profeta Ageu e de Zacarias, filho de Ido; e edificaram a casa e a aperfeiçoaram conforme o mandado do Deus de Israel, e conforme o mandado de Ciro, e de Dario, e de Artaxerxes, rei da Pérsia." },
{name:'15615',l:'15',c:'6',v:'15',texto:"E acabou-se esta casa no dia terceiro do mês de Adar, que era o sexto ano do reinado do rei Dario." },
{name:'15616',l:'15',c:'6',v:'16',texto:"E os filhos de Israel, e os sacerdotes, e os levitas, e o resto dos filhos do cativeiro fizeram a consagração desta Casa de Deus com alegria." },
{name:'15617',l:'15',c:'6',v:'17',texto:"E ofereceram para a consagração desta Casa de Deus cem novilhos, duzentos carneiros, quatrocentos cordeiros e doze cabritos, por expiação do pecado de todo o Israel, segundo o número das tribos de Israel." },
{name:'15618',l:'15',c:'6',v:'18',texto:"E puseram os sacerdotes nas suas turmas e os levitas nas suas divisões, para o ministério de Deus, que está em Jerusalém, conforme o escrito do livro de Moisés." },
{name:'15619',l:'15',c:'6',v:'19',texto:"E os que vieram do cativeiro celebraram a Páscoa no dia catorze do primeiro mês;" },
{name:'15620',l:'15',c:'6',v:'20',texto:"porque os sacerdotes e levitas se tinham purificado como se fossem um só homem, e todos estavam limpos; e mataram o cordeiro da Páscoa para todos os filhos do cativeiro, e para seus irmãos, os sacerdotes, e para si mesmos." },
{name:'15621',l:'15',c:'6',v:'21',texto:"Assim, comeram a Páscoa os filhos de Israel que tinham voltado do cativeiro, com todos os que a eles se apartavam da imundícia das nações da terra, para buscarem o SENHOR, Deus de Israel." },
{name:'15622',l:'15',c:'6',v:'22',texto:"E celebraram a Festa dos Pães Asmos os sete dias com alegria, porque o SENHOR os tinha alegrado e tinha mudado o coração do rei da Assíria a favor deles, para lhes fortalecer as mãos na obra da Casa de Deus, o Deus de Israel." },
],
numVersiculos: 22,
},

c7: {
versiculos:[
{name:'1571',l:'15',c:'7',v:'1',texto:"E, passadas essas coisas, no reinado de Artaxerxes, rei da Pérsia, Esdras, filho de Seraías, filho de Azarias, filho de Hilquias," },
{name:'1572',l:'15',c:'7',v:'2',texto:"filho de Salum, filho de Zadoque, filho de Aitube," },
{name:'1573',l:'15',c:'7',v:'3',texto:"filho de Amarias, filho de Azarias, filho de Meraiote," },
{name:'1574',l:'15',c:'7',v:'4',texto:"filho de Zeraías, filho de Uzi, filho de Buqui," },
{name:'1575',l:'15',c:'7',v:'5',texto:"filho de Abisua, filho de Finéias, filho de Eleazar, filho de Arão, o sumo sacerdote," },
{name:'1576',l:'15',c:'7',v:'6',texto:"este Esdras subiu de Babilônia; e era escriba hábil na Lei de Moisés, dada pelo SENHOR, Deus de Israel; e, segundo a mão do SENHOR, seu Deus, que estava sobre ele, o rei lhe deu tudo quanto lhe pedira." },
{name:'1577',l:'15',c:'7',v:'7',texto:"Também subiram a Jerusalém alguns dos filhos de Israel, e dos sacerdotes, e dos levitas, e dos cantores, e dos porteiros, e dos netineus, no ano sétimo do rei Artaxerxes." },
{name:'1578',l:'15',c:'7',v:'8',texto:"E, no mês quinto, veio ele a Jerusalém; e era o sétimo ano desse rei;" },
{name:'1579',l:'15',c:'7',v:'9',texto:"porque, no primeiro dia do primeiro mês, foi o princípio da sua subida de Babilônia; e, no primeiro dia do quinto mês, chegou a Jerusalém, segundo a boa mão do seu Deus sobre ele." },
{name:'15710',l:'15',c:'7',v:'10',texto:"Porque Esdras tinha preparado o seu coração para buscar a Lei do SENHOR, e para a cumprir, e para ensinar em Israel os seus estatutos e os seus direitos." },
{name:'15711',l:'15',c:'7',v:'11',texto:"Esta é, pois, a cópia da carta que o rei Artaxerxes deu ao sacerdote Esdras, o escriba das palavras, dos mandamentos do SENHOR e dos seus estatutos sobre Israel:" },
{name:'15712',l:'15',c:'7',v:'12',texto:"Artaxerxes, rei dos reis, ao sacerdote Esdras, escriba da Lei do Deus do céu, paz perfeita!" },
{name:'15713',l:'15',c:'7',v:'13',texto:"Por mim se decreta que, no meu reino, todo aquele do povo de Israel e dos seus sacerdotes e levitas que quiser ir contigo a Jerusalém, vá." },
{name:'15714',l:'15',c:'7',v:'14',texto:"Porquanto da parte do rei e dos seus sete conselheiros és mandado, para fazeres inquirição em Judá e em Jerusalém, conforme a Lei do teu Deus, que está na tua mão;" },
{name:'15715',l:'15',c:'7',v:'15',texto:"e para levares a prata e o ouro que o rei e os seus conselheiros voluntariamente deram ao Deus de Israel, cuja habitação está em Jerusalém;" },
{name:'15716',l:'15',c:'7',v:'16',texto:"e toda a prata e o ouro que achares em toda a província de Babilônia, com as ofertas voluntárias do povo e dos sacerdotes, que voluntariamente oferecerem, para a Casa de seu Deus, que está em Jerusalém." },
{name:'15717',l:'15',c:'7',v:'17',texto:"Portanto, comprarás com este dinheiro novilhos, carneiros, cordeiros, com as suas ofertas de manjares e as suas libações e oferece-as sobre o altar da Casa do vosso Deus, que está em Jerusalém." },
{name:'15718',l:'15',c:'7',v:'18',texto:"Também o que a ti e a teus irmãos bem parecer fazerdes do resto da prata e do ouro, o fareis conforme a vontade do vosso Deus." },
{name:'15719',l:'15',c:'7',v:'19',texto:"E os utensílios que te foram dados para o serviço da Casa de teu Deus, restitui-os perante o Deus de Jerusalém." },
{name:'15720',l:'15',c:'7',v:'20',texto:"E o resto do que for necessário para a Casa de teu Deus, que te convenha dar, o darás da casa dos tesouros do rei." },
{name:'15721',l:'15',c:'7',v:'21',texto:"E por mim mesmo, o rei Artaxerxes, se decreta a todos os tesoureiros que estão dalém do rio que tudo quanto vos pedir o sacerdote Esdras, escriba da Lei do Deus dos céus, apressuradamente se faça." },
{name:'15722',l:'15',c:'7',v:'22',texto:"Até cem talentos de prata, e até cem coros de trigo, e até cem batos de vinho, e até cem batos de azeite, e sal sem conta." },
{name:'15723',l:'15',c:'7',v:'23',texto:"Tudo quanto se ordenar, segundo o mandado do Deus do céu, prontamente se faça para a Casa do Deus dos céus, porque para que haveria grande ira sobre o reino do rei e de seus filhos?" },
{name:'15724',l:'15',c:'7',v:'24',texto:"Também vos fazemos saber acerca de todos os sacerdotes, levitas, cantores, porteiros, netineus e ministros desta Casa de Deus que se lhes não possa impor nem direito, nem antigo tributo, nem renda." },
{name:'15725',l:'15',c:'7',v:'25',texto:"E tu, Esdras, conforme a sabedoria do teu Deus, que está na tua mão, põe regedores e juízes que julguem a todo o povo que está dalém do rio, a todos os que sabem as leis de teu Deus, e ao que as não sabe as fareis saber." },
{name:'15726',l:'15',c:'7',v:'26',texto:"E todo aquele que não observar a lei do teu Deus e a lei do rei, logo se faça justiça dele, quer seja morte, quer degredo, quer multa sobre os seus bens, quer prisão." },
{name:'15727',l:'15',c:'7',v:'27',texto:"Bendito seja o SENHOR, Deus de nossos pais, que tal inspirou ao coração do rei, para ornarmos a Casa do SENHOR, que está em Jerusalém;" },
{name:'15728',l:'15',c:'7',v:'28',texto:"e que estendeu para mim a sua beneficência perante o rei, e os seus conselheiros, e todos os príncipes poderosos do rei. Assim, me esforcei, segundo a mão do SENHOR sobre mim, e ajuntei dentre Israel alguns chefes para subirem comigo." },
],
numVersiculos: 28,
},

c8: {
versiculos:[
{name:'1581',l:'15',c:'8',v:'1',texto:"Estes, pois, são os chefes de seus pais, com as suas genealogias, os que subiram comigo de Babilônia no reinado do rei Artaxerxes:" },
{name:'1582',l:'15',c:'8',v:'2',texto:"dos filhos de Finéias, Gérson; dos filhos de Itamar, Daniel; dos filhos de Davi, Hatus;" },
{name:'1583',l:'15',c:'8',v:'3',texto:"dos filhos de Secanias e dos filhos de Parós, Zacarias, e com ele por genealogias se contaram até cento e cinqüenta homens;" },
{name:'1584',l:'15',c:'8',v:'4',texto:"dos filhos de Paate-Moabe, Elioenai, filho de Zeraías, e, com ele, duzentos homens;" },
{name:'1585',l:'15',c:'8',v:'5',texto:"dos filhos de Secanias, o filho de Jaaziel, e, com ele, trezentos homens;" },
{name:'1586',l:'15',c:'8',v:'6',texto:"e dos filhos de Adim, Ebede, filho de Jônatas, e, com ele, cinqüenta homens;" },
{name:'1587',l:'15',c:'8',v:'7',texto:"e dos filhos de Elão, Jesaías, filho de Atalias, e, com ele, setenta homens;" },
{name:'1588',l:'15',c:'8',v:'8',texto:"e dos filhos de Sefatias, Zebadias, filho de Micael, e, com ele, oitenta homens;" },
{name:'1589',l:'15',c:'8',v:'9',texto:"dos filhos de Joabe, Obadias, filho de Jeiel, e, com ele, duzentos e dezoito homens;" },
{name:'15810',l:'15',c:'8',v:'10',texto:"e dos filhos de Selomite, o filho de Josifias, e, com ele, cento e sessenta homens;" },
{name:'15811',l:'15',c:'8',v:'11',texto:"e dos filhos de Bebai, Zacarias, o filho de Bebai, e, com ele, vinte e oito homens;" },
{name:'15812',l:'15',c:'8',v:'12',texto:"e dos filhos de Azgade, Joanã, o filho de Hacatã, e, com ele, cento e dez homens;" },
{name:'15813',l:'15',c:'8',v:'13',texto:"e dos últimos filhos de Adonicão, seus nomes eram estes: Elifelete, Jeiel e Semaías, e, com eles, sessenta homens;" },
{name:'15814',l:'15',c:'8',v:'14',texto:"e dos filhos de Bigvai, Utai e Zabude, e, com eles, setenta homens." },
{name:'15815',l:'15',c:'8',v:'15',texto:"E ajuntei-os perto do rio que vai a Aava, e ficamos ali acampados três dias; então, atentei para o povo e para os sacerdotes e não achei ali nenhum dos filhos de Levi." },
{name:'15816',l:'15',c:'8',v:'16',texto:"Enviei, pois, Eliézer, Ariel, Semaías, Elnatã, Jaribe, Elnatã, Natã, Zacarias e Mesulão, os chefes, como também a Joiaribe e a Elnatã, que eram sábios." },
{name:'15817',l:'15',c:'8',v:'17',texto:"E dei-lhes mandado para Ido, chefe no lugar de Casifia, e lhes pus palavras na boca para dizerem a Ido, seu irmão, e aos netineus, no lugar de Casifia, que nos trouxessem ministros para a Casa do nosso Deus." },
{name:'15818',l:'15',c:'8',v:'18',texto:"E trouxeram-nos, segundo a boa mão de Deus sobre nós, um homem sábio, dos filhos de Mali, filho de Levi, filho de Israel, a saber, Serebias, com os seus filhos e irmãos, dezoito;" },
{name:'15819',l:'15',c:'8',v:'19',texto:"e a Hasabias e com ele Jesaías, dos filhos de Merari, com seus irmãos e os filhos deles, vinte;" },
{name:'15820',l:'15',c:'8',v:'20',texto:"e dos netineus, que Davi e os príncipes deram para o ministério dos levitas, duzentos e vinte netineus, que todos foram expressos por seus nomes." },
{name:'15821',l:'15',c:'8',v:'21',texto:"Então, apregoei ali um jejum junto ao rio Aava, para nos humilharmos diante da face de nosso Deus, para lhe pedirmos caminho direito para nós, e para nossos filhos, e para toda a nossa fazenda." },
{name:'15822',l:'15',c:'8',v:'22',texto:"Porque me envergonhei de pedir ao rei exército e cavaleiros para nos defenderem do inimigo no caminho, porquanto tínhamos falado ao rei, dizendo: A mão do nosso Deus é sobre todos os que o buscam para o bem, mas a sua força e a sua ira, sobre todos os que o deixam." },
{name:'15823',l:'15',c:'8',v:'23',texto:"Nós, pois, jejuamos e pedimos isso ao nosso Deus, e moveu-se pelas nossas orações." },
{name:'15824',l:'15',c:'8',v:'24',texto:"Então, separei doze dos maiorais dos sacerdotes: Serebias, Hasabias e com eles dez dos seus irmãos." },
{name:'15825',l:'15',c:'8',v:'25',texto:"E pesei-lhes a prata, e o ouro, e os utensílios, que eram a oferta para a Casa de nosso Deus, a qual ofereceram o rei, e os seus conselheiros, e os seus príncipes, e todo o Israel que ali se achou." },
{name:'15826',l:'15',c:'8',v:'26',texto:"E pesei em suas mãos seiscentos e cinqüenta talentos de prata, e em objetos de prata cem talentos, e cem talentos de ouro." },
{name:'15827',l:'15',c:'8',v:'27',texto:"E vinte taças de ouro de mil daricos e dois vasos de bom metal lustroso, tão desejável como ouro." },
{name:'15828',l:'15',c:'8',v:'28',texto:"E disse-lhes: Consagrados sois do SENHOR, e sagrados são estes vasos, como também esta prata e este ouro, oferta voluntária, oferecida ao SENHOR, Deus de vossos pais." },
{name:'15829',l:'15',c:'8',v:'29',texto:"Vigiai, pois, e guardai-os até que os peseis na presença dos maiorais dos sacerdotes, e dos levitas, e dos príncipes dos pais de Israel, em Jerusalém, nas câmaras da Casa do SENHOR." },
{name:'15830',l:'15',c:'8',v:'30',texto:"Então, receberam os sacerdotes e os levitas o peso da prata, e do ouro, e dos vasos, para trazerem a Jerusalém, à Casa de nosso Deus." },
{name:'15831',l:'15',c:'8',v:'31',texto:"E partimos do rio de Aava, no dia doze do primeiro mês, para irmos para Jerusalém; e a boa mão do nosso Deus estava sobre nós e livrou-nos da mão dos inimigos e dos que nos armavam ciladas no caminho." },
{name:'15832',l:'15',c:'8',v:'32',texto:"E viemos a Jerusalém e repousamos ali três dias." },
{name:'15833',l:'15',c:'8',v:'33',texto:"E no dia quatro se pesou a prata, e o ouro, e os vasos, na Casa do nosso Deus, por mão de Meremote, filho do sacerdote Urias; e com ele estava Eleazar, filho de Finéias, e com eles, Jozabade, filho de Jesua, e Noadias, filho de Binui, levitas;" },
{name:'15834',l:'15',c:'8',v:'34',texto:"conforme o número e conforme o peso de tudo aquilo; e todo o peso se descreveu no mesmo tempo." },
{name:'15835',l:'15',c:'8',v:'35',texto:"E os transportados que vieram do cativeiro ofereceram holocaustos ao Deus de Israel: doze novilhos por todo o Israel, noventa e seis carneiros, setenta e sete cordeiros e doze bodes em sacrifício pelo pecado; tudo em holocausto ao SENHOR." },
{name:'15836',l:'15',c:'8',v:'36',texto:"Então, deram as ordens do rei aos sátrapas do rei e aos governadores de aquém do rio; e ajudaram o povo e a Casa de Deus." },
],
numVersiculos: 36,
},

c9: {
versiculos:[
{name:'1591',l:'15',c:'9',v:'1',texto:"Acabadas, pois, essas coisas, chegaram-se a mim os príncipes, dizendo: O povo de Israel, e os sacerdotes, e os levitas não se têm separado dos povos destas terras, seguindo as abominações dos cananeus, dos heteus, dos ferezeus, dos jebuseus, dos amonitas, dos moabitas, dos egípcios e dos amorreus," },
{name:'1592',l:'15',c:'9',v:'2',texto:"porque tomaram das suas filhas para si e para seus filhos, e assim se misturou a semente santa com os povos destas terras, e até a mão dos príncipes e magistrados foi a primeira nesta transgressão." },
{name:'1593',l:'15',c:'9',v:'3',texto:"E, ouvindo eu tal coisa, rasguei a minha veste e o meu manto, e arranquei os cabelos da minha cabeça e da minha barba, e me assentei atônito." },
{name:'1594',l:'15',c:'9',v:'4',texto:"Então, se ajuntaram a mim todos os que tremiam das palavras do Deus de Israel, por causa da transgressão dos do cativeiro; porém eu me fiquei assentado atônito até ao sacrifício da tarde." },
{name:'1595',l:'15',c:'9',v:'5',texto:"E, perto do sacrifício da tarde, me levantei da minha aflição, havendo já rasgado a minha veste e o meu manto, e me pus de joelhos, e estendi as minhas mãos para o SENHOR, meu Deus." },
{name:'1596',l:'15',c:'9',v:'6',texto:"E disse: Meu Deus! Estou confuso e envergonhado, para levantar a ti a minha face, meu Deus, porque as nossas iniqüidades se multiplicaram sobre a nossa cabeça, e a nossa culpa tem crescido até aos céus." },
{name:'1597',l:'15',c:'9',v:'7',texto:"Desde os dias de nossos pais até ao dia de hoje, estamos em grande culpa e, por causa das nossas iniqüidades, fomos entregues, nós, os nossos reis e os nossos sacerdotes, nas mãos dos reis das terras, à espada, ao cativeiro, ao roubo e à confusão do rosto, como hoje se vê." },
{name:'1598',l:'15',c:'9',v:'8',texto:"E, agora, como por um pequeno momento, se nos fez graça da parte do SENHOR, nosso Deus, para nos deixar alguns que escapem e para dar-nos uma estabilidade no seu santo lugar; para nos alumiar os olhos; ó Deus nosso, e para nos dar um pouco de vida na nossa servidão;" },
{name:'1599',l:'15',c:'9',v:'9',texto:"porque servos somos, porém na nossa servidão não nos desamparou o nosso Deus; antes, estendeu sobre nós beneficência perante os reis da Pérsia, para revivermos, e para levantarmos a Casa do nosso Deus, e para restaurarmos as suas assolações, e para que nos desse uma parede em Judá e em Jerusalém." },
{name:'15910',l:'15',c:'9',v:'10',texto:"Agora, pois, ó nosso Deus, que diremos depois disso? Pois deixamos os teus mandamentos," },
{name:'15911',l:'15',c:'9',v:'11',texto:"os quais mandaste pelo ministério de teus servos, os profetas, dizendo: A terra em que entrais para a possuir terra imunda é pelas imundícias dos seus povos, pelas abominações com que, na sua corrupção, a encheram de uma extremidade à outra." },
{name:'15912',l:'15',c:'9',v:'12',texto:"Agora, pois, vossas filhas não dareis a seus filhos, e suas filhas não tomareis para vossos filhos, e nunca procurareis a sua paz e o seu bem; para que vos fortaleçais, e comais o bem da terra, e a façais possuir a vossos filhos para sempre." },
{name:'15913',l:'15',c:'9',v:'13',texto:"E, depois de tudo o que nos tem sucedido por causa das nossas más obras e da nossa grande culpa, ainda assim tu, ó nosso Deus, estorvaste que fôssemos destruídos, por causa da nossa iniqüidade, e ainda nos deste livramento como este," },
{name:'15914',l:'15',c:'9',v:'14',texto:"tornaremos, pois, agora a violar os teus mandamentos e a aparentar-nos com os povos destas abominações? Não te indignarias tu, assim, contra nós até de todo nos consumires, até que não ficasse resto nem quem escapasse?" },
{name:'15915',l:'15',c:'9',v:'15',texto:"Ah! SENHOR, Deus de Israel, justo és, pois ficamos escapos, como hoje se vê; eis que estamos diante de ti no nosso delito, porque ninguém há que possa estar na tua presença por causa disso." },
],
numVersiculos: 15,
},

c10: {
versiculos:[
{name:'15101',l:'15',c:'10',v:'1',texto:"E orando Esdras assim, e fazendo esta confissão, e chorando, e prostrando-se diante da Casa de Deus, ajuntou-se a ele de Israel uma mui grande congregação de homens e mulheres e de crianças, porque o povo chorava com grande choro." },
{name:'15102',l:'15',c:'10',v:'2',texto:"Então, respondeu Secanias, filho de Jeiel, um dos filhos de Elão, e disse a Esdras: Nós temos transgredido contra o nosso Deus e casamos com mulheres estranhas do povo da terra, mas, no tocante a isso, ainda há esperança para Israel." },
{name:'15103',l:'15',c:'10',v:'3',texto:"Agora, pois, façamos concerto com o nosso Deus, de que despediremos todas as mulheres e tudo o que é nascido delas, conforme o conselho do Senhor e dos que tremem no mandado do nosso Deus; e faça-se conforme a Lei." },
{name:'15104',l:'15',c:'10',v:'4',texto:"Levanta-te, pois, porque te pertence este negócio, e nós seremos contigo; esforça-te e faze assim." },
{name:'15105',l:'15',c:'10',v:'5',texto:"Então, Esdras se levantou e ajuramentou os maiorais dos sacerdotes e dos levitas e todo o Israel, de que fariam conforme esta palavra; e eles juraram." },
{name:'15106',l:'15',c:'10',v:'6',texto:"E Esdras se levantou de diante da Casa de Deus, e entrou na câmara de Jeoanã, filho de Eliasibe, e, vindo lá, pão não comeu, e água não bebeu, porque estava angustiado pela transgressão dos do cativeiro." },
{name:'15107',l:'15',c:'10',v:'7',texto:"E fizeram passar pregão, por Judá e Jerusalém, a todos os que vieram do cativeiro, para que se ajuntassem em Jerusalém;" },
{name:'15108',l:'15',c:'10',v:'8',texto:"e que todo aquele que, em três dias, não viesse, segundo o conselho dos príncipes e dos anciãos, toda a sua fazenda se poria em interdito, e ele seria separado da congregação dos do cativeiro." },
{name:'15109',l:'15',c:'10',v:'9',texto:"Então, todos os homens de Judá e Benjamim, em três dias, se ajuntaram em Jerusalém; era o nono mês, no dia vinte do mês; e todo o povo se assentou na praça da Casa de Deus, tremendo por este negócio e por causa das grandes chuvas." },
{name:'151010',l:'15',c:'10',v:'10',texto:"Então, se levantou Esdras, o sacerdote, e disse-lhes: Vós tendes transgredido e casastes com mulheres estranhas, multiplicando o delito de Israel." },
{name:'151011',l:'15',c:'10',v:'11',texto:"Agora, pois, fazei confissão ao SENHOR, Deus de vossos pais, e fazei a sua vontade; apartai-vos dos povos das terras e das mulheres estranhas." },
{name:'151012',l:'15',c:'10',v:'12',texto:"E respondeu toda a congregação e disse em altas vozes: Assim seja; conforme as tuas palavras, nos convém fazer." },
{name:'151013',l:'15',c:'10',v:'13',texto:"Porém o povo é muito, e também é tempo de grandes chuvas, e não se pode estar aqui fora; nem é obra de um dia nem de dois, porque somos muitos os que transgredimos neste negócio." },
{name:'151014',l:'15',c:'10',v:'14',texto:"Ora, ponham-se os nossos príncipes, por toda a congregação, sobre este negócio; e todos os que, em nossas cidades, casaram com mulheres estranhas venham em tempos apontados, e com eles os anciãos de cada cidade, e os seus juízes, até que desviemos de nós o ardor da ira do nosso Deus, por esta causa." },
{name:'151015',l:'15',c:'10',v:'15',texto:"Porém somente Jônatas, filho de Asael, e Jazeías, filho de Ticva, se puseram sobre este negócio; e Mesulão e Sabetai, levita, os ajudaram." },
{name:'151016',l:'15',c:'10',v:'16',texto:"E assim o fizeram os que tornaram do cativeiro; e apartaram-se o sacerdote Esdras e os homens, cabeças dos pais segundo a casa de seus pais, e todos pelos seus nomes; e assentaram-se no primeiro dia do décimo mês, para inquirirem neste negócio." },
{name:'151017',l:'15',c:'10',v:'17',texto:"E acabaram de tratar com todos os homens que casaram com mulheres estranhas, até ao primeiro dia do primeiro mês." },
{name:'151018',l:'15',c:'10',v:'18',texto:"E acharam-se dos filhos dos sacerdotes que casaram com mulheres estranhas: dos filhos de Jesua, filho de Jozadaque, e seus irmãos, Maaséias, e Eliézer, e Jaribe, e Gedalias." },
{name:'151019',l:'15',c:'10',v:'19',texto:"E deram-se as mãos, prometendo que despediriam suas mulheres, e, achando-se culpados, ofereceram um carneiro do rebanho pelo seu delito." },
{name:'151020',l:'15',c:'10',v:'20',texto:"E dos filhos de Imer: Hanani e Zebadias." },
{name:'151021',l:'15',c:'10',v:'21',texto:"E dos filhos de Harim: Maaséias, e Elias, e Semaías, e Jeiel, e Uzias." },
{name:'151022',l:'15',c:'10',v:'22',texto:"E dos filhos de Pasur: Elioenai, Maaséias, Ismael, Natanael, Jozabade e Elasa." },
{name:'151023',l:'15',c:'10',v:'23',texto:"E dos levitas: Jozabade, e Simei, e Quelaías ( este é Quelita ), e Petaías, e Judá, e Eliézer." },
{name:'151024',l:'15',c:'10',v:'24',texto:"E dos cantores: Eliasibe; e dos porteiros: Salum, e Telém, e Uri." },
{name:'151025',l:'15',c:'10',v:'25',texto:"E de Israel, dos filhos de Parós: Ramias, e Jezias, e Malquias, e Miamim, e Eleazar, e Malquias, e Benaia." },
{name:'151026',l:'15',c:'10',v:'26',texto:"E dos filhos de Elão: Matanias, e Zacarias, e Jeiel, e Abdi, e Jeremote, e Elias." },
{name:'151027',l:'15',c:'10',v:'27',texto:"E dos filhos de Zatu: Elioenai, e Eliasibe, e Matanias, e Jeremote, e Zabade, e Aziza." },
{name:'151028',l:'15',c:'10',v:'28',texto:"E dos filhos de Bebai: Jeoanã, Hananias, Zabai e Atlai." },
{name:'151029',l:'15',c:'10',v:'29',texto:"E dos filhos de Bani: Mesulão, e Maluque, e Adaías, e Jasube, e Seal, e Jeremote." },
{name:'151030',l:'15',c:'10',v:'30',texto:"E dos filhos de Paate-Moabe: Adna, e Quelal, e Benaia, e Maaséias, e Matanias, e Bezalel, e Binui, e Manassés." },
{name:'151031',l:'15',c:'10',v:'31',texto:"E dos filhos de Harim: Eliézer, Issias, Malquias, Semaías, Simeão," },
{name:'151032',l:'15',c:'10',v:'32',texto:"Benjamim, Maluque e Semarias." },
{name:'151033',l:'15',c:'10',v:'33',texto:"Dos filhos de Hasum: Matenai, Matatá, Zabade, Elifelete, Jeremai, Manassés e Simei." },
{name:'151034',l:'15',c:'10',v:'34',texto:"Dos filhos de Bani: Maadai, Anrão, e Uel," },
{name:'151035',l:'15',c:'10',v:'35',texto:"Benaia, Bedias, Queluí," },
{name:'151036',l:'15',c:'10',v:'36',texto:"Vanias, Meremote, Eliasibe," },
{name:'151037',l:'15',c:'10',v:'37',texto:"Matanias, Matenai, Jaasai," },
{name:'151038',l:'15',c:'10',v:'38',texto:"Bani, Binui, Simei," },
{name:'151039',l:'15',c:'10',v:'39',texto:"Selemias, Natã, Adaías," },
{name:'151040',l:'15',c:'10',v:'40',texto:"Macnadebai, Sasai, Sarai," },
{name:'151041',l:'15',c:'10',v:'41',texto:"Azarel, Selemias, Semarias," },
{name:'151042',l:'15',c:'10',v:'42',texto:"Salum, Amarias e José." },
{name:'151043',l:'15',c:'10',v:'43',texto:"Dos filhos de Nebo: Jeiel, Matitias, Zabade, Zebina, Jadai, Joel e Benaia." },
{name:'151044',l:'15',c:'10',v:'44',texto:"Todos estes tinham tomado mulheres estranhas; e alguns deles tinham mulheres de quem alcançaram filhos." },
],
numVersiculos: 44,
},


};
