BibliaJFA.nehemias = {
	libro: "Neemias",
	numCapitulos: 13,

c1: {
versiculos:[
{name:'1611',l:'16',c:'1',v:'1',texto:"As palavras de Neemias, filho de Hacalias. E sucedeu no mês de quisleu, no ano vigésimo, estando eu em Susã, a fortaleza," },
{name:'1612',l:'16',c:'1',v:'2',texto:"que veio Hanani, um de meus irmãos, ele e alguns de Judá; e perguntei-lhes pelos judeus que escaparam e que restaram do cativeiro e acerca de Jerusalém." },
{name:'1613',l:'16',c:'1',v:'3',texto:"E disseram-me: Os restantes, que não foram levados para o cativeiro, lá na província estão em grande miséria e desprezo, e o muro de Jerusalém, fendido, e as suas portas, queimadas a fogo." },
{name:'1614',l:'16',c:'1',v:'4',texto:"E sucedeu que, ouvindo eu essas palavras, assentei-me, e chorei, e lamentei por alguns dias; e estive jejuando e orando perante o Deus dos céus." },
{name:'1615',l:'16',c:'1',v:'5',texto:"E disse: Ah! SENHOR, Deus dos céus, Deus grande e terrível, que guardas o concerto e a benignidade para com aqueles que te amam e guardam os teus mandamentos!" },
{name:'1616',l:'16',c:'1',v:'6',texto:"Estejam, pois, atentos os teus ouvidos, e os teus olhos, abertos, para ouvires a oração do teu servo, que eu hoje faço perante ti, de dia e de noite, pelos filhos de Israel, teus servos; e faço confissão pelos pecados dos filhos de Israel, que pecamos contra ti; também eu e a casa de meu pai pecamos." },
{name:'1617',l:'16',c:'1',v:'7',texto:"De todo nos corrompemos contra ti e não guardamos os mandamentos, nem os estatutos, nem os juízos que ordenaste a Moisés, teu servo." },
{name:'1618',l:'16',c:'1',v:'8',texto:"Lembra-te, pois, da palavra que ordenaste a Moisés, teu servo, dizendo: Vós transgredireis, e eu vos espalharei entre os povos." },
{name:'1619',l:'16',c:'1',v:'9',texto:"E vós vos convertereis a mim, e guardareis os meus mandamentos, e os fareis; então, ainda que os vossos rejeitados estejam no cabo do céu, de lá os ajuntarei e os trarei ao lugar que tenho escolhido para ali fazer habitar o meu nome." },
{name:'16110',l:'16',c:'1',v:'10',texto:"Estes ainda são teus servos e o teu povo que resgataste com a tua grande força e com a tua forte mão." },
{name:'16111',l:'16',c:'1',v:'11',texto:"Ah! Senhor, estejam, pois, atentos os teus ouvidos à oração do teu servo e à oração dos teus servos que desejam temer o teu nome; e faze prosperar hoje o teu servo e dá-lhe graça perante este homem. Então, era eu copeiro do rei." },
],
numVersiculos: 11,
},

c2: {
versiculos:[
{name:'1621',l:'16',c:'2',v:'1',texto:"Sucedeu, pois, no mês de nisã, no ano vigésimo do rei Artaxerxes, que estava posto vinho diante dele, e eu tomei o vinho e o dei ao rei; porém nunca, antes, estivera triste diante dele." },
{name:'1622',l:'16',c:'2',v:'2',texto:"E o rei me disse: Por que está triste o teu rosto, pois não estás doente? Não é isso senão tristeza de coração. Então, temi muito em grande maneira" },
{name:'1623',l:'16',c:'2',v:'3',texto:"e disse ao rei: Viva o rei para sempre! Como não estaria triste o meu rosto, estando a cidade, o lugar dos sepulcros de meus pais, assolada, e tendo sido consumidas as suas portas a fogo?" },
{name:'1624',l:'16',c:'2',v:'4',texto:"E o rei me disse: Que me pedes agora? Então, orei ao Deus dos céus" },
{name:'1625',l:'16',c:'2',v:'5',texto:"e disse ao rei: Se é do agrado do rei, e se o teu servo é aceito em tua presença, peço-te que me envies a Judá, à cidade dos sepulcros de meus pais, para que eu a edifique." },
{name:'1626',l:'16',c:'2',v:'6',texto:"Então, o rei me disse, estando a rainha assentada junto a ele: Quanto durará a tua viagem, e quando voltarás? E aprouve ao rei enviar-me, apontando-lhe eu um certo tempo." },
{name:'1627',l:'16',c:'2',v:'7',texto:"Disse mais ao rei: Se ao rei parece bem, dêem-se-me cartas para os governadores dalém do rio, para que me dêem passagem até que chegue a Judá;" },
{name:'1628',l:'16',c:'2',v:'8',texto:"como também uma carta para Asafe, guarda do jardim do rei, para que me dê madeira para cobrir as portas do paço da casa, e para o muro da cidade, e para a casa em que eu houver de entrar. E o rei mas deu, segundo a boa mão de Deus sobre mim." },
{name:'1629',l:'16',c:'2',v:'9',texto:"Então, vim aos governadores dalém do rio e dei-lhes as cartas do rei; e o rei tinha enviado comigo chefes do exército e cavaleiros." },
{name:'16210',l:'16',c:'2',v:'10',texto:"O que ouvindo Sambalate, o horonita, e Tobias, o servo amonita, lhes desagradou com grande desagrado que alguém viesse a procurar o bem dos filhos de Israel." },
{name:'16211',l:'16',c:'2',v:'11',texto:"E cheguei a Jerusalém e estive ali três dias." },
{name:'16212',l:'16',c:'2',v:'12',texto:"E, de noite, me levantei, eu e poucos homens comigo, e não declarei a ninguém o que o meu Deus me pôs no coração para fazer em Jerusalém; e não havia comigo animal algum, senão aquele em que estava montado." },
{name:'16213',l:'16',c:'2',v:'13',texto:"E, de noite, saí pela Porta do Vale, para a banda da Fonte do Dragão e para a Porta do Monturo e contemplei os muros de Jerusalém, que estavam fendidos, e as suas portas, que tinham sido consumidas pelo fogo." },
{name:'16214',l:'16',c:'2',v:'14',texto:"E passei à Porta da Fonte e ao viveiro do rei; e não havia lugar por onde pudesse passar a cavalgadura que estava debaixo de mim." },
{name:'16215',l:'16',c:'2',v:'15',texto:"Então, de noite, subi pelo ribeiro e contemplei o muro; e voltei, e entrei pela Porta do Vale, e assim voltei." },
{name:'16216',l:'16',c:'2',v:'16',texto:"E não souberam os magistrados aonde eu fui nem o que eu fazia; porque ainda até então nem aos judeus, nem aos nobres, nem aos magistrados, nem aos mais que faziam a obra tinha declarado coisa alguma." },
{name:'16217',l:'16',c:'2',v:'17',texto:"Então, lhes disse: Bem vedes vós a miséria em que estamos, que Jerusalém está assolada e que as suas portas têm sido queimadas; vinde, pois, e reedifiquemos o muro de Jerusalém e não estejamos mais em opróbrio." },
{name:'16218',l:'16',c:'2',v:'18',texto:"Então, lhes declarei como a mão do meu Deus me fora favorável, como também as palavras do rei, que ele me tinha dito. Então, disseram: Levantemo-nos e edifiquemos. E esforçaram as suas mãos para o bem." },
{name:'16219',l:'16',c:'2',v:'19',texto:"O que ouvindo Sambalate, o horonita, e Tobias, o servo amonita, e Gesém, o arábio, zombaram de nós, e desprezaram-nos, e disseram: Que é isso que fazeis? Quereis rebelar-vos contra o rei?" },
{name:'16220',l:'16',c:'2',v:'20',texto:"Então, lhes respondi e disse: O Deus dos céus é o que nos fará prosperar; e nós, seus servos, nos levantaremos e edificaremos; mas vós não tendes parte, nem justiça, nem memória em Jerusalém." },
],
numVersiculos: 20,
},

c3: {
versiculos:[
{name:'1631',l:'16',c:'3',v:'1',texto:"E levantou-se Eliasibe, o sumo sacerdote, com os seus irmãos, os sacerdotes, edificaram a Porta do Gado, a qual consagraram, e levantaram as suas portas; e até a Torre de Meá consagraram e até a Torre de Hananel." },
{name:'1632',l:'16',c:'3',v:'2',texto:"E, junto a ele, edificaram os homens de Jericó; também, ao seu lado, edificou Zacur, filho de Inri." },
{name:'1633',l:'16',c:'3',v:'3',texto:"E a Porta do Peixe edificaram os filhos de Hassenaá, a qual emadeiraram, e levantaram as suas portas com as suas fechaduras e os seus ferrolhos." },
{name:'1634',l:'16',c:'3',v:'4',texto:"E, ao seu lado, reparou Meremote, filho de Urias, filho de Coz; e, ao seu lado, reparou Mesulão, filho de Berequias, filho de Mesezabel; e, ao seu lado, reparou Zadoque, filho de Baaná." },
{name:'1635',l:'16',c:'3',v:'5',texto:"E, ao seu lado, repararam os tecoítas; porém os seus nobres não meteram o seu pescoço ao serviço de seu senhor." },
{name:'1636',l:'16',c:'3',v:'6',texto:"E a Porta Velha repararam-na Joiada, filho de Paséia; e Mesulão, filho de Besodias; estes a emadeiraram e levantaram as suas portas com as suas fechaduras e os seus ferrolhos." },
{name:'1637',l:'16',c:'3',v:'7',texto:"E, ao seu lado, repararam Melatias, o gibeonita, e Jadom, meronotita, homens de Gibeão e Mispa, que pertenciam ao domínio do governador daquém do rio." },
{name:'1638',l:'16',c:'3',v:'8',texto:"Ao seu lado, reparou Uziel, filho de Haraías, um dos ourives; e, ao seu lado, reparou Hananias, filho de um dos boticários; e fortificaram a Jerusalém até ao Muro Largo." },
{name:'1639',l:'16',c:'3',v:'9',texto:"E, ao seu lado, reparou Refaías, filho de Hur, maioral da metade de Jerusalém." },
{name:'16310',l:'16',c:'3',v:'10',texto:"E, ao seu lado, reparou Jedaías, filho de Harumafe, e defronte de sua casa; e, ao seu lado, reparou Hatus, filho de Hasabnéias." },
{name:'16311',l:'16',c:'3',v:'11',texto:"A outra porção reparou Malquias, filho de Harim, e Hassube, filho de Paate-Moabe, como também a Torre dos Fornos." },
{name:'16312',l:'16',c:'3',v:'12',texto:"E, ao seu lado, reparou Salum, filho de Haloés, maioral da outra meia parte de Jerusalém, ele e suas filhas." },
{name:'16313',l:'16',c:'3',v:'13',texto:"A Porta do Vale, reparou-a Hanum e os moradores de Zanoa; estes a edificaram e lhe levantaram as portas com fechaduras e os seus ferrolhos, como também mil côvados do muro, até à Porta do Monturo." },
{name:'16314',l:'16',c:'3',v:'14',texto:"E a Porta do Monturo, reparou-a Malquias, filho de Recabe, maioral do distrito de Bete-Haquerém; este a edificou e lhe levantou as portas com as suas fechaduras e os seus ferrolhos." },
{name:'16315',l:'16',c:'3',v:'15',texto:"E a Porta da Fonte reparou-a Salum, filho de Col-Hozé, maioral do distrito de Mispa; este a edificou, e a cobriu, e lhe levantou as portas com as suas fechaduras e os seus ferrolhos, como também o muro do viveiro de Selá, ao pé do jardim do rei, mesmo até aos degraus que descem da Cidade de Davi." },
{name:'16316',l:'16',c:'3',v:'16',texto:"Depois dele, edificou Neemias, filho de Azbuque, maioral da metade de Bete-Zur, até defronte dos sepulcros de Davi, e até ao viveiro artificial, e até à casa dos varões." },
{name:'16317',l:'16',c:'3',v:'17',texto:"Depois dele, repararam os levitas, Reum, filho de Bani, e, ao seu lado, reparou Hasabias, maioral da metade de Queila, no seu distrito." },
{name:'16318',l:'16',c:'3',v:'18',texto:"Depois dele, repararam seus irmãos: Bavai, filho de Henadade, maioral da outra meia parte de Queila;" },
{name:'16319',l:'16',c:'3',v:'19',texto:"ao seu lado, reparou Ezer, filho de Jesua, maioral de Mispa, outra porção, defronte da subida para a casa das armas, à esquina." },
{name:'16320',l:'16',c:'3',v:'20',texto:"Depois dele, reparou com grande ardor Baruque, filho de Zabai, outra medida, desde a esquina até à porta da casa de Eliasibe, o sumo sacerdote." },
{name:'16321',l:'16',c:'3',v:'21',texto:"Depois dele, reparou Meremote, filho de Urias, filho de Coz, outra porção, desde a porta da casa de Eliasibe até à extremidade da casa de Eliasibe." },
{name:'16322',l:'16',c:'3',v:'22',texto:"E, depois dele, repararam os sacerdotes que habitavam na campina." },
{name:'16323',l:'16',c:'3',v:'23',texto:"Depois, repararam Benjamim e Hassube, defronte da sua casa; depois deles, reparou Azarias, filho de Maaséias, filho de Ananias, junto à sua casa." },
{name:'16324',l:'16',c:'3',v:'24',texto:"Depois dele, reparou Binui, filho de Henadade, outra porção, desde a casa de Azarias até à esquina e até ao canto." },
{name:'16325',l:'16',c:'3',v:'25',texto:"Palal, filho de Uzai, reparou defronte da esquina e a torre que sai da casa real superior, que está junto ao pátio da prisão; depois dele, reparou Pedaías, filho de Parós," },
{name:'16326',l:'16',c:'3',v:'26',texto:"e os netineus, que habitavam em Ofel, até defronte da Porta das Águas, para o oriente, e até à torre alta." },
{name:'16327',l:'16',c:'3',v:'27',texto:"Depois, repararam os tecoítas outra porção, defronte da torre grande e alta e até ao Muro de Ofel." },
{name:'16328',l:'16',c:'3',v:'28',texto:"Desde a Porta dos Cavalos, repararam os sacerdotes, cada um defronte da sua casa." },
{name:'16329',l:'16',c:'3',v:'29',texto:"Depois deles, reparou Zadoque, filho de Imer, defronte de sua casa, e, depois dele, reparou Semaías, filho de Secanias, guarda da Porta Oriental." },
{name:'16330',l:'16',c:'3',v:'30',texto:"Depois dele, reparou Hananias, filho de Selemias, e Hanum, filho de Zalafe, o sexto, outra porção; depois deles reparou Mesulão, filho de Berequias, defronte da sua câmara." },
{name:'16331',l:'16',c:'3',v:'31',texto:"Depois dele, reparou Malquias, filho de um ourives, até à casa dos netineus e mercadores, defronte da Porta de Mifcade, e até à câmara do canto." },
{name:'16332',l:'16',c:'3',v:'32',texto:"E, entre a câmara do canto e a Porta do Gado, repararam os ourives e os mercadores." },
],
numVersiculos: 32,
},

c4: {
versiculos:[
{name:'1641',l:'16',c:'4',v:'1',texto:"E sucedeu que, ouvindo Sambalate que edificávamos o muro, ardeu em ira, e se indignou muito, e escarneceu dos judeus." },
{name:'1642',l:'16',c:'4',v:'2',texto:"E falou na presença de seus irmãos e do exército de Samaria e disse: Que fazem estes fracos judeus? Permitir-se-lhes-á isso? Sacrificarão? Acabá-lo-ão num só dia? Vivificarão dos montões do pó as pedras que foram queimadas?" },
{name:'1643',l:'16',c:'4',v:'3',texto:"E estava com ele Tobias, o amonita, e disse: Ainda que edifiquem, vindo uma raposa, derrubará facilmente o seu muro de pedra." },
{name:'1644',l:'16',c:'4',v:'4',texto:"Ouve, ó nosso Deus, que somos tão desprezados, e caia o seu opróbrio sobre a sua cabeça, e faze com que sejam um despojo, numa terra de cativeiro." },
{name:'1645',l:'16',c:'4',v:'5',texto:"E não cubras a sua iniqüidade, e não se risque diante de ti o seu pecado, pois que te irritaram defronte dos edificadores." },
{name:'1646',l:'16',c:'4',v:'6',texto:"Assim, edificamos o muro, e todo o muro se cerrou até sua metade; porque o coração do povo se inclinava a trabalhar." },
{name:'1647',l:'16',c:'4',v:'7',texto:"E sucedeu que, ouvindo Sambalate, e Tobias, e os arábios, e os amonitas, e os asdoditas que tanto ia crescendo a reparação dos muros de Jerusalém, que já as roturas se começavam a tapar, iraram-se sobremodo." },
{name:'1648',l:'16',c:'4',v:'8',texto:"E ligaram-se entre si todos, para virem atacar Jerusalém e para os desviarem do seu intento." },
{name:'1649',l:'16',c:'4',v:'9',texto:"Porém nós oramos ao nosso Deus e pusemos uma guarda contra eles, de dia e de noite, por causa deles." },
{name:'16410',l:'16',c:'4',v:'10',texto:"Então, disse Judá: Já desfaleceram as forças dos acarretadores, e o pó é muito, e nós não poderemos edificar o muro." },
{name:'16411',l:'16',c:'4',v:'11',texto:"Disseram, porém, os nossos inimigos: Nada saberão disso, nem verão, até que entremos no meio deles e os matemos; assim, faremos cessar a obra." },
{name:'16412',l:'16',c:'4',v:'12',texto:"E sucedeu que, vindo os judeus que habitavam entre eles, dez vezes nos disseram que, de todos os lugares, tornavam a nós." },
{name:'16413',l:'16',c:'4',v:'13',texto:"Pelo que pus guardas nos lugares baixos por detrás do muro e nos altos; e pus o povo, pelas suas famílias, com as suas espadas, com as suas lanças e com os seus arcos." },
{name:'16414',l:'16',c:'4',v:'14',texto:"E olhei, e levantei-me, e disse aos nobres, e aos magistrados, e ao resto do povo: Não os temais; lembrai-vos do Senhor, grande e terrível, e pelejai pelos vossos irmãos, vossos filhos, vossas mulheres e vossas casas." },
{name:'16415',l:'16',c:'4',v:'15',texto:"E sucedeu que, ouvindo os nossos inimigos que já o sabíamos e que Deus tinha dissipado o conselho deles, todos voltamos ao muro, cada um à sua obra." },
{name:'16416',l:'16',c:'4',v:'16',texto:"E sucedeu que, desde aquele dia, metade dos meus moços trabalhava na obra, e a outra metade deles tinha as lanças, os escudos, os arcos e as couraças; e os chefes estavam por detrás de toda a casa de Judá." },
{name:'16417',l:'16',c:'4',v:'17',texto:"Os que edificavam o muro, e os que traziam as cargas, e os que carregavam, cada um com uma mão fazia a obra e na outra tinha as armas." },
{name:'16418',l:'16',c:'4',v:'18',texto:"E os edificadores cada um trazia a sua espada cingida aos lombos, e edificavam; e o que tocava a trombeta estava junto comigo." },
{name:'16419',l:'16',c:'4',v:'19',texto:"E disse eu aos nobres, e aos magistrados, e ao resto do povo: Grande e extensa é a obra, e nós estamos apartados do muro, longe uns dos outros." },
{name:'16420',l:'16',c:'4',v:'20',texto:"No lugar onde ouvirdes o som da buzina, ali vos ajuntareis conosco; o nosso Deus pelejará por nós." },
{name:'16421',l:'16',c:'4',v:'21',texto:"Assim trabalhávamos na obra; e metade deles tinha as lanças desde a subida da alva até ao sair das estrelas." },
{name:'16422',l:'16',c:'4',v:'22',texto:"Também, naquele tempo, disse ao povo: Cada um com o seu moço fique em Jerusalém, para que, de noite, nos sirvam de guarda e, de dia, na obra." },
{name:'16423',l:'16',c:'4',v:'23',texto:"E nem eu, nem meus irmãos, nem meus moços, nem os homens da guarda que me seguiam largávamos as nossas vestes; cada um ia com suas armas à água." },
],
numVersiculos: 23,
},

c5: {
versiculos:[
{name:'1651',l:'16',c:'5',v:'1',texto:"Foi, porém, grande o clamor do povo e de suas mulheres contra os judeus, seus irmãos." },
{name:'1652',l:'16',c:'5',v:'2',texto:"Porque havia quem dizia: Com nossos filhos e nossas filhas, nós somos muitos; pelo que tomemos trigo, para que comamos e vivamos." },
{name:'1653',l:'16',c:'5',v:'3',texto:"Também havia quem dizia: As nossas terras, as nossas vinhas e as nossas casas empenhamos, para tomarmos trigo nesta fome." },
{name:'1654',l:'16',c:'5',v:'4',texto:"Também havia quem dizia: Tomamos dinheiro emprestado até para o tributo do rei, sobre as nossas terras e as nossas vinhas." },
{name:'1655',l:'16',c:'5',v:'5',texto:"Agora, pois, a nossa carne é como a carne de nossos irmãos, e nossos filhos, como seus filhos; e eis que sujeitamos nossos filhos e nossas filhas para serem servos, e até algumas de nossas filhas são tão sujeitas, que já não estão no poder de nossas mãos; e outros têm as nossas terras e as nossas vinhas." },
{name:'1656',l:'16',c:'5',v:'6',texto:"Ouvindo eu, pois, o seu clamor e essas palavras, muito me enfadei." },
{name:'1657',l:'16',c:'5',v:'7',texto:"E considerei comigo mesmo no meu coração; depois, pelejei com os nobres e com os magistrados e disse-lhes: Usura tomais cada um de seu irmão. E ajuntei contra eles um grande ajuntamento." },
{name:'1658',l:'16',c:'5',v:'8',texto:"E disse-lhes: Nós resgatamos os judeus, nossos irmãos, que foram vendidos às gentes, segundo nossas posses; e vós outra vez venderíeis vossos irmãos ou vender-se-iam a nós? Então, se calaram e não acharam que responder." },
{name:'1659',l:'16',c:'5',v:'9',texto:"Disse mais: Não é bom o que fazeis: Porventura, não devíeis andar no temor do nosso Deus, por causa do opróbrio dos gentios, os nossos inimigos?" },
{name:'16510',l:'16',c:'5',v:'10',texto:"Também eu, meus irmãos e meus moços, a juro, lhes temos dado dinheiro e trigo. Deixemos este ganho." },
{name:'16511',l:'16',c:'5',v:'11',texto:"Restituí-lhes hoje, vos peço, as suas terras, as suas vinhas, os seus olivais e as suas casas, como também o centésimo do dinheiro, do trigo, do mosto e do azeite, que vós exigis deles." },
{name:'16512',l:'16',c:'5',v:'12',texto:"Então, disseram: Restituir-lho-emos e nada procuraremos deles; faremos assim como dizes. Então, chamei os sacerdotes e os fiz jurar que fariam conforme esta palavra." },
{name:'16513',l:'16',c:'5',v:'13',texto:"Também o meu regaço sacudi e disse: Assim sacuda Deus a todo homem da sua casa e do seu trabalho que não cumprir esta palavra; e assim seja sacudido e vazio. E toda a congregação disse: Amém! E louvaram o SENHOR; e o povo fez conforme esta palavra." },
{name:'16514',l:'16',c:'5',v:'14',texto:"Também desde o dia em que fui nomeado seu governador na terra de Judá, desde o ano vinte até ao ano trinta e dois do rei Artaxerxes, doze anos, nem eu nem meus irmãos comemos o pão do governador." },
{name:'16515',l:'16',c:'5',v:'15',texto:"Mas os primeiros governadores, que foram antes de mim, oprimiram o povo e tomaram-lhe pão e vinho e, além disso, quarenta siclos de prata; ainda também os seus moços dominavam sobre o povo; porém eu assim não fiz, por causa do temor de Deus." },
{name:'16516',l:'16',c:'5',v:'16',texto:"Antes, também na obra deste muro fiz reparação, e terra nenhuma compramos; e todos os meus moços se ajuntaram ali para a obra." },
{name:'16517',l:'16',c:'5',v:'17',texto:"Também cento e cinqüenta homens dos judeus e dos magistrados e os que vinham a nós, dentre as gentes que estão à roda de nós, se punham à minha mesa." },
{name:'16518',l:'16',c:'5',v:'18',texto:"E o que se preparava para cada dia era um boi e seis ovelhas escolhidas; também aves se me preparavam e, de dez em dez dias, de todo o vinho muitíssimo; e nem por isso exigi o pão do governador, porquanto a servidão deste povo era grande." },
{name:'16519',l:'16',c:'5',v:'19',texto:"Lembra-te de mim para bem, ó meu Deus, e de tudo quanto fiz a este povo." },
],
numVersiculos: 19,
},

c6: {
versiculos:[
{name:'1661',l:'16',c:'6',v:'1',texto:"Sucedeu mais que, ouvindo Sambalate, Tobias, Gesém, o arábio, e o resto dos nossos inimigos que eu tinha edificado o muro e que nele já não havia brecha alguma, ainda que até este tempo não tinha posto as portas nos portais," },
{name:'1662',l:'16',c:'6',v:'2',texto:"Sambalate e Gesém enviaram a dizer: Vem, e congreguemo-nos juntamente nas aldeias, no vale de Ono. Porém intentavam fazer-me mal." },
{name:'1663',l:'16',c:'6',v:'3',texto:"E enviei-lhes mensageiros a dizer: Estou fazendo uma grande obra, de modo que não poderei descer; por que cessaria esta obra, enquanto eu a deixasse e fosse ter convosco?" },
{name:'1664',l:'16',c:'6',v:'4',texto:"E da mesma maneira enviaram a mim quatro vezes; e da mesma maneira lhes respondi." },
{name:'1665',l:'16',c:'6',v:'5',texto:"Então, Sambalate, da mesma maneira, pela quinta vez, me enviou o seu moço com uma carta aberta na sua mão," },
{name:'1666',l:'16',c:'6',v:'6',texto:"e na qual estava escrito: Entre as gentes se ouviu e Gesém diz que tu e os judeus intentais revoltar-vos, pelo que edificais o muro; e que tu te farás rei deles segundo estas palavras;" },
{name:'1667',l:'16',c:'6',v:'7',texto:"e que puseste profetas para pregarem de ti em Jerusalém, dizendo: Este é rei em Judá. Ora, o rei o ouvirá, segundo estas palavras; vem, pois, agora, e consultemos juntamente." },
{name:'1668',l:'16',c:'6',v:'8',texto:"Porém eu enviei a dizer-lhe: De tudo o que dizes coisa nenhuma sucedeu; mas tu, do teu coração, o inventas." },
{name:'1669',l:'16',c:'6',v:'9',texto:"Porque todos eles nos procuravam atemorizar, dizendo: As suas mãos largarão a obra, e não se efetuará. Agora, pois, ó Deus, esforça as minhas mãos." },
{name:'16610',l:'16',c:'6',v:'10',texto:"E, entrando eu em casa de Semaías, filho de Delaías, o filho de Meetabel ( que estava encerrado ), disse ele: Vamos juntamente à Casa de Deus, ao meio do templo, e fechemos as portas do templo; porque virão matar-te; sim, de noite virão matar-te." },
{name:'16611',l:'16',c:'6',v:'11',texto:"Porém eu disse: Um homem, como eu, fugiria? E quem há, como eu, que entre no templo e viva? De maneira nenhuma entrarei." },
{name:'16612',l:'16',c:'6',v:'12',texto:"E conheci que eis que não era Deus quem o enviara; mas essa profecia falou contra mim, porquanto Tobias e Sambalate o subornaram." },
{name:'16613',l:'16',c:'6',v:'13',texto:"Para isso o subornaram, para me atemorizar, e para que eu assim fizesse e pecasse, para que tivessem alguma causa a fim de me infamarem e assim me vituperarem." },
{name:'16614',l:'16',c:'6',v:'14',texto:"Lembra-te, meu Deus, de Tobias e de Sambalate, conforme estas suas obras, e também da profetisa Noadias e dos mais profetas que procuraram atemorizar-me." },
{name:'16615',l:'16',c:'6',v:'15',texto:"Acabou-se, pois, o muro aos vinte e cinco de elul, em cinqüenta e dois dias." },
{name:'16616',l:'16',c:'6',v:'16',texto:"E sucedeu que, ouvindo-o todos os nossos inimigos, temeram todos os gentios que havia em roda de nós e abateram-se muito em seus próprios olhos; porque reconheceram que o nosso Deus fizera esta obra." },
{name:'16617',l:'16',c:'6',v:'17',texto:"Também, naqueles dias, alguns nobres de Judá escreveram muitas cartas, que iam para Tobias, e as cartas de Tobias vinham para eles." },
{name:'16618',l:'16',c:'6',v:'18',texto:"Porque muitos em Judá se lhe ajuramentaram, porque era genro de Secanias, filho de Ará; e seu filho Joanã tomara a filha de Mesulão, filho de Berequias." },
{name:'16619',l:'16',c:'6',v:'19',texto:"Também as suas bondades contavam perante mim, e as minhas palavras lhe levavam a ele; portanto, Tobias escrevia cartas para me atemorizar." },
],
numVersiculos: 19,
},

c7: {
versiculos:[
{name:'1671',l:'16',c:'7',v:'1',texto:"Sucedeu mais que, depois que o muro fora edificado, eu levantei as portas; e foram estabelecidos os porteiros, e os cantores, e os levitas." },
{name:'1672',l:'16',c:'7',v:'2',texto:"Eu nomeei a Hanani, meu irmão, e a Hananias, maioral da fortaleza, sobre Jerusalém, porque era homem fiel e temente a Deus, mais do que muitos;" },
{name:'1673',l:'16',c:'7',v:'3',texto:"e disse-lhes: Não se abram as portas de Jerusalém até que o sol aqueça; e, enquanto assistirem ali, fechem as portas, e, vós, trancai-as; e ponham-se guardas dos moradores de Jerusalém, cada um na sua guarda e cada um diante da sua casa." },
{name:'1674',l:'16',c:'7',v:'4',texto:"E era a cidade larga de espaço e grande, porém pouco povo havia dentro dela; e ainda as casas não estavam edificadas." },
{name:'1675',l:'16',c:'7',v:'5',texto:"Então, o meu Deus me pôs no coração que ajuntasse os nobres, e os magistrados, e o povo, para registrar as genealogias. E achei o livro da genealogia dos que subiram primeiro e assim achei escrito nele:" },
{name:'1676',l:'16',c:'7',v:'6',texto:"Estes são os filhos da província, que subiram do cativeiro, os transportados, que transportara Nabucodonosor, rei de Babilônia; e voltaram para Jerusalém e para Judá, cada um para a sua cidade;" },
{name:'1677',l:'16',c:'7',v:'7',texto:"os quais vieram com Zorobabel, Jesua, Neemias, Azarias, Raamias, Naamani, Mardoqueu, Bilsã, Misperete, Bigvai, Neum e Baaná; este é o número dos homens do povo de Israel:" },
{name:'1678',l:'16',c:'7',v:'8',texto:"foram os filhos de Parós, dois mil cento e setenta e dois." },
{name:'1679',l:'16',c:'7',v:'9',texto:"Os filhos de Sefatias, trezentos e setenta e dois." },
{name:'16710',l:'16',c:'7',v:'10',texto:"Os filhos de Ará, seiscentos e cinqüenta e dois." },
{name:'16711',l:'16',c:'7',v:'11',texto:"Os filhos de Paate-Moabe, dos filhos de Jesua e de Joabe, dois mil oitocentos e dezoito." },
{name:'16712',l:'16',c:'7',v:'12',texto:"Os filhos de Elão, mil duzentos e cinqüenta e quatro." },
{name:'16713',l:'16',c:'7',v:'13',texto:"Os filhos de Zatu, oitocentos e quarenta e cinco." },
{name:'16714',l:'16',c:'7',v:'14',texto:"Os filhos de Zacai, setecentos e sessenta." },
{name:'16715',l:'16',c:'7',v:'15',texto:"Os filhos de Binui, seiscentos e quarenta e oito." },
{name:'16716',l:'16',c:'7',v:'16',texto:"Os filhos de Bebai, seiscentos e vinte e oito." },
{name:'16717',l:'16',c:'7',v:'17',texto:"Os filhos de Azgade, dois mil trezentos e vinte e dois." },
{name:'16718',l:'16',c:'7',v:'18',texto:"Os filhos de Adonicão, seiscentos e sessenta e sete." },
{name:'16719',l:'16',c:'7',v:'19',texto:"Os filhos de Bigvai, dois mil e sessenta e sete." },
{name:'16720',l:'16',c:'7',v:'20',texto:"Os filhos de Adim, seiscentos e cinqüenta e cinco." },
{name:'16721',l:'16',c:'7',v:'21',texto:"Os filhos de Ater, de Ezequias, noventa e oito." },
{name:'16722',l:'16',c:'7',v:'22',texto:"Os filhos de Hasum, trezentos e vinte e oito." },
{name:'16723',l:'16',c:'7',v:'23',texto:"Os filhos de Besai, trezentos e vinte e quatro." },
{name:'16724',l:'16',c:'7',v:'24',texto:"Os filhos de Harife, cento e doze." },
{name:'16725',l:'16',c:'7',v:'25',texto:"Os filhos de Gibeão, noventa e cinco." },
{name:'16726',l:'16',c:'7',v:'26',texto:"Os homens de Belém e de Netofa, cento e oitenta e oito." },
{name:'16727',l:'16',c:'7',v:'27',texto:"Os homens de Anatote, cento e vinte e oito." },
{name:'16728',l:'16',c:'7',v:'28',texto:"Os homens de Bete-Azmavete, quarenta e dois." },
{name:'16729',l:'16',c:'7',v:'29',texto:"Os homens de Quiriate-Jearim, Cefira e Beerote, setecentos e quarenta e três." },
{name:'16730',l:'16',c:'7',v:'30',texto:"Os homens de Ramá e Geba, seiscentos e vinte e um." },
{name:'16731',l:'16',c:'7',v:'31',texto:"Os homens de Micmás, cento e vinte e dois." },
{name:'16732',l:'16',c:'7',v:'32',texto:"Os homens de Betel e Ai, cento e vinte e três." },
{name:'16733',l:'16',c:'7',v:'33',texto:"Os homens doutra Nebo, cinqüenta e dois." },
{name:'16734',l:'16',c:'7',v:'34',texto:"Os filhos do outro Elão, mil duzentos e cinqüenta e quatro." },
{name:'16735',l:'16',c:'7',v:'35',texto:"Os filhos de Harim, trezentos e vinte." },
{name:'16736',l:'16',c:'7',v:'36',texto:"Os filhos de Jericó, trezentos e quarenta e cinco." },
{name:'16737',l:'16',c:'7',v:'37',texto:"Os filhos de Lode, Hadide e Ono, setecentos e vinte e um." },
{name:'16738',l:'16',c:'7',v:'38',texto:"Os filhos de Senaá, três mil novecentos e trinta." },
{name:'16739',l:'16',c:'7',v:'39',texto:"Os sacerdotes: os filhos de Jedaías, da casa de Jesua, novecentos e setenta e três." },
{name:'16740',l:'16',c:'7',v:'40',texto:"Os filhos de Imer, mil e cinqüenta e dois." },
{name:'16741',l:'16',c:'7',v:'41',texto:"Os filhos de Pasur, mil duzentos e quarenta e sete." },
{name:'16742',l:'16',c:'7',v:'42',texto:"Os filhos de Harim, mil e dezessete." },
{name:'16743',l:'16',c:'7',v:'43',texto:"Os levitas: os filhos de Jesua, de Cadmiel, dos filhos de Hodeva, setenta e quatro." },
{name:'16744',l:'16',c:'7',v:'44',texto:"Os cantores: os filhos de Asafe, cento e quarenta e oito." },
{name:'16745',l:'16',c:'7',v:'45',texto:"Os porteiros: os filhos de Salum, os filhos de Ater, os filhos de Talmom, os filhos de Acube, os filhos de Hatita, os filhos de Sobai, cento e trinta e oito." },
{name:'16746',l:'16',c:'7',v:'46',texto:"Os netineus: os filhos de Zia, os filhos de Hasufa, os filhos de Tabaote," },
{name:'16747',l:'16',c:'7',v:'47',texto:"os filhos de Queros, os filhos de Sia, os filhos de Padom," },
{name:'16748',l:'16',c:'7',v:'48',texto:"os filhos de Lebana, os filhos de Hagaba, os filhos de Salmai," },
{name:'16749',l:'16',c:'7',v:'49',texto:"os filhos de Hanã, os filhos de Gidel, os filhos de Gaar," },
{name:'16750',l:'16',c:'7',v:'50',texto:"os filhos de Reaías, os filhos de Rezim, os filhos de Necoda," },
{name:'16751',l:'16',c:'7',v:'51',texto:"os filhos de Gazão, os filhos de Uzá, os filhos de Paséia," },
{name:'16752',l:'16',c:'7',v:'52',texto:"os filhos de Besai, os filhos de Meunim, os filhos de Nefusesim," },
{name:'16753',l:'16',c:'7',v:'53',texto:"os filhos de Baquebuque, os filhos de Hacufa, os filhos de Harur," },
{name:'16754',l:'16',c:'7',v:'54',texto:"os filhos de Bazlite, os filhos de Meida, os filhos de Harsa," },
{name:'16755',l:'16',c:'7',v:'55',texto:"os filhos de Barcos, os filhos de Sísera, os filhos de Tama," },
{name:'16756',l:'16',c:'7',v:'56',texto:"os filhos de Nesias, os filhos de Hatifa." },
{name:'16757',l:'16',c:'7',v:'57',texto:"Os filhos dos servos de Salomão: os filhos de Sotai, os filhos de Soferete, os filhos de Perida," },
{name:'16758',l:'16',c:'7',v:'58',texto:"os filhos de Jaala, os filhos de Darcom, os filhos de Gidel," },
{name:'16759',l:'16',c:'7',v:'59',texto:"os filhos de Sefatias, os filhos de Hatil, os filhos de Poquerete-Hazebaim, os filhos de Amom." },
{name:'16760',l:'16',c:'7',v:'60',texto:"Todos os netineus e os filhos dos servos de Salomão, trezentos e noventa e dois." },
{name:'16761',l:'16',c:'7',v:'61',texto:"Também estes subiram de Tel-Melá, Tel-Harsa, Querube, Adom e Imer, porém não puderam mostrar a casa de seus pais e a sua linhagem, se eram de Israel:" },
{name:'16762',l:'16',c:'7',v:'62',texto:"os filhos de Delaías, os filhos de Tobias, os filhos de Necoda, seiscentos e quarenta e dois." },
{name:'16763',l:'16',c:'7',v:'63',texto:"E dos sacerdotes: os filhos de Habaías, os filhos de Coz, os filhos de Barzilai, que tomara uma mulher das filhas de Barzilai, o gileadita, e se chamou do nome delas." },
{name:'16764',l:'16',c:'7',v:'64',texto:"Estes buscaram o seu registro, querendo contar a sua geração, porém não se achou; pelo que, como imundos, foram excluídos do sacerdócio." },
{name:'16765',l:'16',c:'7',v:'65',texto:"E o tirsata lhes disse que não comessem das coisas sagradas, até que se aprestasse um sacerdote com Urim e Tumim." },
{name:'16766',l:'16',c:'7',v:'66',texto:"Toda essa congregação junta foi de quarenta e dois mil trezentos e sessenta," },
{name:'16767',l:'16',c:'7',v:'67',texto:"afora os seus servos e as suas servas, que foram sete mil trezentos e trinta e sete; e tinham duzentos e quarenta e cinco cantores e cantoras." },
{name:'16768',l:'16',c:'7',v:'68',texto:"Os seus cavalos, setecentos e trinta e seis; os seus mulos, duzentos e quarenta e cinco." },
{name:'16769',l:'16',c:'7',v:'69',texto:"Camelos, quatrocentos e trinta e cinco; jumentos, seis mil setecentos e vinte." },
{name:'16770',l:'16',c:'7',v:'70',texto:"E uma parte dos cabeças dos pais deram para a obra; o tirsata deu para o tesouro, em ouro, mil daricos, cinqüenta bacias e quinhentas e trinta vestes sacerdotais." },
{name:'16771',l:'16',c:'7',v:'71',texto:"E alguns mais dos cabeças dos pais deram para o tesouro da obra, em ouro, vinte mil daricos; e, em prata, dois mil e duzentos arráteis." },
{name:'16772',l:'16',c:'7',v:'72',texto:"E o que deu o resto do povo foi, em ouro, vinte mil daricos; e, em prata, dois mil arráteis; e sessenta e sete vestes sacerdotais." },
{name:'16773',l:'16',c:'7',v:'73',texto:"E habitaram os sacerdotes, e os levitas, e os porteiros, e os cantores, e alguns do povo, e os netineus, e todo o Israel nas suas cidades." },
],
numVersiculos: 73,
},

c8: {
versiculos:[
{name:'1681',l:'16',c:'8',v:'1',texto:"E chegado o sétimo mês, e estando os filhos de Israel nas suas cidades, todo o povo se ajuntou como um só homem, na praça, diante da Porta das Águas; e disseram a Esdras, o escriba, que trouxesse o livro da Lei de Moisés, que o SENHOR tinha ordenado a Israel." },
{name:'1682',l:'16',c:'8',v:'2',texto:"E Esdras, o sacerdote, trouxe a Lei perante a congregação, assim de homens como de mulheres e de todos os sábios para ouvirem, no primeiro dia do sétimo mês." },
{name:'1683',l:'16',c:'8',v:'3',texto:"E leu nela, diante da praça, que está diante da Porta das Águas, desde a alva até ao meio-dia, perante homens, e mulheres, e sábios; e os ouvidos de todo o povo estavam atentos ao livro da Lei." },
{name:'1684',l:'16',c:'8',v:'4',texto:"E Esdras, o escriba, estava sobre um púlpito de madeira, que fizeram para aquele fim; e estavam em pé junto a ele, à sua mão direita, Matitias, e Sema, e Anaías, e Urias, e Hilquias, e Maaséias; e à sua mão esquerda, Pedaías, e Misael, e Malquias, e Hasum, e Hasbadana, e Zacarias, e Mesulão." },
{name:'1685',l:'16',c:'8',v:'5',texto:"E Esdras abriu o livro perante os olhos de todo o povo; porque estava acima de todo o povo; e, abrindo-o ele, todo o povo se pôs em pé." },
{name:'1686',l:'16',c:'8',v:'6',texto:"E Esdras louvou o SENHOR, o grande Deus; e todo o povo respondeu: Amém! Amém! —, levantando as mãos; e inclinaram-se e adoraram o SENHOR, com o rosto em terra." },
{name:'1687',l:'16',c:'8',v:'7',texto:"E Jesua, e Bani, e Serebias, e Jamim, e Acube, e Sabetai, e Hodias, e Maaséias, e Quelita, e Azarias, e Jozabade, e Hanã, e Pelaías, e os levitas ensinavam ao povo na Lei; e o povo estava no seu posto." },
{name:'1688',l:'16',c:'8',v:'8',texto:"E leram o livro, na Lei de Deus, e declarando e explicando o sentido, faziam que, lendo, se entendesse." },
{name:'1689',l:'16',c:'8',v:'9',texto:"E Neemias ( que era o tirsata ), e o sacerdote Esdras, o escriba, e os levitas que ensinavam ao povo disseram a todo o povo: Este dia é consagrado ao SENHOR, vosso Deus, pelo que não vos lamenteis, nem choreis. Porque todo o povo chorava, ouvindo as palavras da Lei." },
{name:'16810',l:'16',c:'8',v:'10',texto:"Disse-lhes mais: Ide, e comei as gorduras, e bebei as doçuras, e enviai porções aos que não têm nada preparado para si; porque esse dia é consagrado ao nosso Senhor; portanto, não vos entristeçais, porque a alegria do SENHOR é a vossa força." },
{name:'16811',l:'16',c:'8',v:'11',texto:"E os levitas fizeram calar todo o povo, dizendo: Calai-vos, porque este dia é santo; por isso, não vos entristeçais." },
{name:'16812',l:'16',c:'8',v:'12',texto:"Então, todo o povo se foi a comer, e a beber, e a enviar porções, e a fazer grandes festas, porque entenderam as palavras que lhes fizeram saber." },
{name:'16813',l:'16',c:'8',v:'13',texto:"E, no dia seguinte, ajuntaram-se os cabeças dos pais de todo o povo, os sacerdotes e os levitas, a Esdras, o escriba, e isso para atentarem nas palavras da Lei." },
{name:'16814',l:'16',c:'8',v:'14',texto:"E acharam escrito na Lei que o SENHOR ordenara pelo ministério de Moisés que os filhos de Israel habitassem em cabanas, na solenidade da festa, no sétimo mês." },
{name:'16815',l:'16',c:'8',v:'15',texto:"Assim, o publicaram e fizeram passar pregão por todas as suas cidades e em Jerusalém, dizendo: Saí ao monte e trazei ramos de oliveira, e ramos de zambujeiros, e ramos de murtas, e ramos de palmeiras, e ramos de árvores espessas, para fazer cabanas, como está escrito." },
{name:'16816',l:'16',c:'8',v:'16',texto:"Saiu, pois, o povo, e de tudo trouxeram e fizeram para si cabanas, cada um no seu terraço, e nos seus pátios, e nos átrios da Casa de Deus, e na praça da Porta das Águas, e na praça da Porta de Efraim." },
{name:'16817',l:'16',c:'8',v:'17',texto:"E toda a congregação dos que voltaram do cativeiro fez cabanas e habitou nas cabanas; porque nunca fizeram assim os filhos de Israel, desde os dias de Josué, filho de Num, até àquele dia; e houve mui grande alegria." },
{name:'16818',l:'16',c:'8',v:'18',texto:"E, de dia em dia, ele lia o livro da Lei de Deus, desde o primeiro dia até ao derradeiro; e celebraram a solenidade da festa sete dias e, no oitavo dia, a festa do encerramento, segundo o rito." },
],
numVersiculos: 18,
},

c9: {
versiculos:[
{name:'1691',l:'16',c:'9',v:'1',texto:"E, no dia vinte e quatro deste mês, se ajuntaram os filhos de Israel com jejum e com pano de saco e traziam terra sobre si." },
{name:'1692',l:'16',c:'9',v:'2',texto:"E a geração de Israel se apartou de todos os estranhos, e puseram-se em pé e fizeram confissão dos seus pecados e das iniqüidades de seus pais." },
{name:'1693',l:'16',c:'9',v:'3',texto:"E, levantando-se no seu posto, leram no livro da Lei do SENHOR, seu Deus, uma quarta parte do dia; e, na outra quarta parte, fizeram confissão; e adoraram o SENHOR, seu Deus." },
{name:'1694',l:'16',c:'9',v:'4',texto:"E Jesua, Bani, Cadmiel, Sebanias, Buni, Serebias, Bani e Quenani se puseram em pé no lugar alto dos levitas e clamaram em alta voz ao SENHOR, seu Deus." },
{name:'1695',l:'16',c:'9',v:'5',texto:"E os levitas, Jesua, Cadmiel, Bani, Hasabnéias, Serebias, Hodias, Sebanias e Petaías disseram: Levantai-vos, bendizei ao SENHOR, vosso Deus, de eternidade em eternidade; ora, bendigam o nome da tua glória, que está levantado sobre toda bênção e louvor." },
{name:'1696',l:'16',c:'9',v:'6',texto:"Tu só és SENHOR, tu fizeste o céu, o céu dos céus e todo o seu exército, a terra e tudo quanto nela há, os mares e tudo quanto neles há; e tu os guardas em vida a todos, e o exército dos céus te adora." },
{name:'1697',l:'16',c:'9',v:'7',texto:"Tu és SENHOR, o Deus, que elegeste Abrão, e o tiraste de Ur dos caldeus, e lhe puseste por nome Abraão." },
{name:'1698',l:'16',c:'9',v:'8',texto:"E achaste o seu coração fiel perante ti e fizeste com ele o concerto, que lhe darias a terra dos cananeus, e dos heteus, e dos amorreus, e dos ferezeus, e dos jebuseus, e dos girgaseus, para a dares à sua semente; e confirmaste as tuas palavras, porquanto és justo." },
{name:'1699',l:'16',c:'9',v:'9',texto:"E viste a aflição de nossos pais no Egito e ouviste o seu clamor junto ao mar Vermelho." },
{name:'16910',l:'16',c:'9',v:'10',texto:"E mostraste sinais e prodígios a Faraó, e a todos os seus servos, e a todo o povo da sua terra, porque soubeste que soberbamente os trataram; e assim te adquiriste nome, como hoje se vê." },
{name:'16911',l:'16',c:'9',v:'11',texto:"E o mar fendeste perante eles, e passaram pelo meio do mar, em seco; e lançaste os seus perseguidores nas profundezas, como uma pedra nas águas violentas." },
{name:'16912',l:'16',c:'9',v:'12',texto:"E os guiaste, de dia por uma coluna de nuvem e de noite por uma coluna de fogo, para os alumiares no caminho por onde haviam de ir." },
{name:'16913',l:'16',c:'9',v:'13',texto:"E sobre o monte de Sinai desceste, e falaste com eles desde os céus, e deste-lhes juízos retos e leis verdadeiras, estatutos e mandamentos bons." },
{name:'16914',l:'16',c:'9',v:'14',texto:"E o teu santo sábado lhes fizeste conhecer; e preceitos, e estatutos, e lei lhes mandaste pelo ministério de Moisés, teu servo." },
{name:'16915',l:'16',c:'9',v:'15',texto:"E pão dos céus lhes deste na sua fome e água da rocha lhes produziste na sua sede; e lhes disseste que entrassem para possuírem a terra pela qual alçaste a tua mão, que lha havias de dar." },
{name:'16916',l:'16',c:'9',v:'16',texto:"Porém eles, nossos pais, se houveram soberbamente, e endureceram a sua cerviz, e não deram ouvidos aos teus mandamentos." },
{name:'16917',l:'16',c:'9',v:'17',texto:"E recusaram ouvir-te, e não se lembraram das tuas maravilhas, que lhes fizeste, e endureceram a sua cerviz, e na sua rebelião levantaram um chefe, a fim de voltarem para a sua servidão; porém tu, ó Deus perdoador, clemente e misericordioso, tardio em irar-te, e grande em beneficência, tu os não desamparaste," },
{name:'16918',l:'16',c:'9',v:'18',texto:"ainda mesmo quando eles fizeram para si um bezerro de fundição, e disseram: Este é o teu Deus, que te tirou do Egito, e cometeram grandes blasfêmias;" },
{name:'16919',l:'16',c:'9',v:'19',texto:"todavia, tu, pela multidão das tuas misericórdias, os não deixaste no deserto. A coluna de nuvem nunca deles se apartou de dia, para os guiar pelo caminho, nem a coluna de fogo de noite, para os alumiar e mostrar o caminho por onde haviam de ir." },
{name:'16920',l:'16',c:'9',v:'20',texto:"E deste o teu bom espírito, para os ensinar; e o teu maná não retiraste da sua boca; e água lhes deste na sua sede." },
{name:'16921',l:'16',c:'9',v:'21',texto:"Desse modo os sustentaste quarenta anos no deserto; falta nenhuma tiveram; as suas vestes não se envelheceram, e os seus pés não se incharam." },
{name:'16922',l:'16',c:'9',v:'22',texto:"Também lhes deste reinos e povos e os repartiste em porções; e eles possuíram a terra de Seom, a saber, a terra do rei de Hesbom, e a terra de Ogue, rei de Basã." },
{name:'16923',l:'16',c:'9',v:'23',texto:"E multiplicaste os seus filhos como as estrelas do céu e trouxeste-os à terra de que tinhas dito a seus pais que entrariam nela para a possuírem." },
{name:'16924',l:'16',c:'9',v:'24',texto:"Assim, entraram nela os filhos e tomaram aquela terra; e abateste perante eles os moradores da terra, os cananeus, e lhos entregaste na mão, como também os reis e os povos da terra, para fazerem deles conforme a sua vontade." },
{name:'16925',l:'16',c:'9',v:'25',texto:"E tomaram cidades fortes e terra gorda e possuíram casas cheias de toda fartura, cisternas cavadas, vinhas, e olivais, e árvores de mantimento, em abundância; e comeram, e se fartaram, e engordaram, e viveram em delícias, pela tua grande bondade." },
{name:'16926',l:'16',c:'9',v:'26',texto:"Porém se obstinaram, e se revoltaram contra ti, e lançaram a tua lei para trás das suas costas, e mataram os teus profetas, que protestavam contra eles, para que voltassem para ti; assim fizeram grandes abominações." },
{name:'16927',l:'16',c:'9',v:'27',texto:"Pelo que os entregaste na mão dos seus angustiadores, que os angustiaram; mas no tempo de sua angústia, clamando a ti, desde os céus tu os ouviste; e, segundo a tua grande misericórdia, lhes deste libertadores que os libertaram da mão de seus angustiadores." },
{name:'16928',l:'16',c:'9',v:'28',texto:"Porém, em tendo repouso, tornavam a fazer o mal diante de ti; e tu os deixavas na mão dos seus inimigos, para que dominassem sobre eles; e, convertendo-se eles e clamando a ti, tu os ouviste desde os céus e, segundo a tua misericórdia, os livraste muitas vezes." },
{name:'16929',l:'16',c:'9',v:'29',texto:"E protestaste contra eles, para que voltassem para a tua lei; porém eles se houveram soberbamente e não deram ouvidos aos teus mandamentos, mas pecaram contra os teus juízos, pelos quais o homem que os cumprir viverá; e retiraram os seus ombros, e endureceram a sua cerviz, e não ouviram." },
{name:'16930',l:'16',c:'9',v:'30',texto:"Porém estendeste a tua benignidade sobre eles por muitos anos e protestaste contra eles pelo teu Espírito, pelo ministério dos teus profetas; porém eles não deram ouvidos; pelo que os entregaste na mão dos povos das terras." },
{name:'16931',l:'16',c:'9',v:'31',texto:"Mas, pela tua grande misericórdia, não os destruíste nem desamparaste; porque és um Deus clemente e misericordioso." },
{name:'16932',l:'16',c:'9',v:'32',texto:"Agora, pois, ó Deus nosso, ó Deus grande, poderoso e terrível, que guardas o concerto e a beneficência, não tenhas em pouca conta toda a aflição que nos alcançou a nós, e aos nossos reis, e aos nossos príncipes, e aos nossos sacerdotes, e aos nossos profetas, e aos nossos pais, e a todo o teu povo, desde os dias dos reis da Assíria até ao dia de hoje." },
{name:'16933',l:'16',c:'9',v:'33',texto:"Porém tu és justo em tudo quanto tem vindo sobre nós; porque tu fielmente te houveste, e nós impiamente nos houvemos." },
{name:'16934',l:'16',c:'9',v:'34',texto:"E os nossos reis, os nossos príncipes, os nossos sacerdotes e os nossos pais não guardaram a tua lei e não deram ouvidos aos teus mandamentos e aos teus testemunhos, que testificaste contra eles." },
{name:'16935',l:'16',c:'9',v:'35',texto:"Porque eles nem no seu reino, nem na muita abundância de bens que lhes deste, nem na terra espaçosa e gorda que puseste diante deles te serviram, nem se converteram de suas más obras." },
{name:'16936',l:'16',c:'9',v:'36',texto:"Eis que hoje somos servos; e até na terra que deste a nossos pais, para comerem o seu fruto e o seu bem, eis que somos servos nela." },
{name:'16937',l:'16',c:'9',v:'37',texto:"E ela multiplica os seus produtos para os reis que puseste sobre nós por causa dos nossos pecados; e, conforme a sua vontade, dominam sobre os nossos corpos e sobre o nosso gado; e estamos numa grande angústia." },
{name:'16938',l:'16',c:'9',v:'38',texto:"E, com tudo isso, fizemos um firme concerto e o escrevemos; e selaram-no os nossos príncipes, os nossos levitas e os nossos sacerdotes." },
],
numVersiculos: 38,
},

c10: {
versiculos:[
{name:'16101',l:'16',c:'10',v:'1',texto:"E os que selaram foram Neemias, o tirsata, filho de Hacalias, e Zedequias," },
{name:'16102',l:'16',c:'10',v:'2',texto:"Seraías, Azarias, Jeremias," },
{name:'16103',l:'16',c:'10',v:'3',texto:"Pasur, Amarias, Malquias," },
{name:'16104',l:'16',c:'10',v:'4',texto:"Hatus, Sebanias, Maluque," },
{name:'16105',l:'16',c:'10',v:'5',texto:"Harim, Meremote, Obadias," },
{name:'16106',l:'16',c:'10',v:'6',texto:"Daniel, Ginetom, Baruque," },
{name:'16107',l:'16',c:'10',v:'7',texto:"Mesulão, Abias, Miamim," },
{name:'16108',l:'16',c:'10',v:'8',texto:"Maaséias, Bilgai, Semaías; estes foram os sacerdotes." },
{name:'16109',l:'16',c:'10',v:'9',texto:"E os levitas: Jesua, filho de Azanias, Binui, dos filhos de Henadade, Cadmiel" },
{name:'161010',l:'16',c:'10',v:'10',texto:"e seus irmãos: Sebanias, Hodias, Quelita, Pelaías, Hanã," },
{name:'161011',l:'16',c:'10',v:'11',texto:"Mica, Reobe, Hasabias," },
{name:'161012',l:'16',c:'10',v:'12',texto:"Zacur, Serebias, Sebanias," },
{name:'161013',l:'16',c:'10',v:'13',texto:"Hodias, Bani, Beninu." },
{name:'161014',l:'16',c:'10',v:'14',texto:"Os chefes do povo: Parós, Paate-Moabe, Elão, Zatu, Bani," },
{name:'161015',l:'16',c:'10',v:'15',texto:"Buni, Azgade, Bebai," },
{name:'161016',l:'16',c:'10',v:'16',texto:"Adonias, Bigvai, Adim," },
{name:'161017',l:'16',c:'10',v:'17',texto:"Ater, Ezequias, Azur," },
{name:'161018',l:'16',c:'10',v:'18',texto:"Hodias, Hasum, Besai," },
{name:'161019',l:'16',c:'10',v:'19',texto:"Harife, Anatote, Nebai," },
{name:'161020',l:'16',c:'10',v:'20',texto:"Magpias, Mesulão, Hezir," },
{name:'161021',l:'16',c:'10',v:'21',texto:"Mesezabel, Zadoque, Jadua," },
{name:'161022',l:'16',c:'10',v:'22',texto:"Pelatias, Hanã, Anaías," },
{name:'161023',l:'16',c:'10',v:'23',texto:"Oséias, Hananias, Hassube," },
{name:'161024',l:'16',c:'10',v:'24',texto:"Haloés, Pileá, Sobeque," },
{name:'161025',l:'16',c:'10',v:'25',texto:"Reum, Hasabna, Maaséias;" },
{name:'161026',l:'16',c:'10',v:'26',texto:"Aías, Hanã, Anã," },
{name:'161027',l:'16',c:'10',v:'27',texto:"Maluque, Harim e Baaná." },
{name:'161028',l:'16',c:'10',v:'28',texto:"E o resto do povo, os sacerdotes, os levitas, os porteiros, os cantores, os netineus e todos os que se tinham separado dos povos das terras para a Lei de Deus, suas mulheres, seus filhos e suas filhas, todos os sábios e os que tinham capacidade para entender" },
{name:'161029',l:'16',c:'10',v:'29',texto:"firmemente aderiram a seus irmãos, os mais nobres de entre eles, e convieram num anátema e num juramento, de que andariam na Lei de Deus, que foi dada pelo ministério de Moisés, servo de Deus; e de que guardariam e cumpririam todos os mandamentos do SENHOR, nosso Senhor, e os seus juízos e os seus estatutos;" },
{name:'161030',l:'16',c:'10',v:'30',texto:"e que não daríamos as nossas filhas aos povos da terra, nem tomaríamos as filhas deles para os nossos filhos;" },
{name:'161031',l:'16',c:'10',v:'31',texto:"e de que, trazendo os povos da terra no dia de sábado algumas fazendas e qualquer grão para venderem, nada tomaríamos deles no sábado, nem no dia santificado; e livre deixaríamos o ano sétimo e toda e qualquer cobrança." },
{name:'161032',l:'16',c:'10',v:'32',texto:"Também sobre nós pusemos preceitos, impondo-nos cada ano a terça parte de um siclo, para o ministério da Casa do nosso Deus;" },
{name:'161033',l:'16',c:'10',v:'33',texto:"para os pães da proposição, e para a contínua oferta de manjares, e para o contínuo holocausto dos sábados, das luas novas, e para as festas solenes, e para as coisas sagradas, e para os sacrifícios pelo pecado, para reconciliar a Israel, e para toda a obra da Casa do nosso Deus." },
{name:'161034',l:'16',c:'10',v:'34',texto:"Também lançamos as sortes entre os sacerdotes, levitas e o povo, acerca da oferta da lenha que se havia de trazer à Casa do nosso Deus, segundo as casas de nossos pais, a tempos determinados, de ano em ano, para se queimar sobre o altar do SENHOR, nosso Deus, como está escrito na Lei." },
{name:'161035',l:'16',c:'10',v:'35',texto:"E que também traríamos as primeiras novidades da nossa terra e todos os primeiros frutos de todas as árvores, de ano em ano, à Casa do SENHOR;" },
{name:'161036',l:'16',c:'10',v:'36',texto:"e os primogênitos dos nossos filhos e os do nosso gado, como está escrito na Lei; e que os primogênitos das nossas vacas e das nossas ovelhas traríamos à Casa do nosso Deus, aos sacerdotes que ministram na Casa do SENHOR;" },
{name:'161037',l:'16',c:'10',v:'37',texto:"e que as primícias da nossa massa, e as nossas ofertas alçadas, e o fruto de toda árvore, e o mosto, e o azeite traríamos aos sacerdotes, às câmaras da Casa do nosso Deus; e os dízimos da nossa terra aos levitas; e que os levitas pagariam os dízimos em todas as cidades da nossa lavoura;" },
{name:'161038',l:'16',c:'10',v:'38',texto:"e que o sacerdote, filho de Arão, estaria com os levitas quando os levitas recebessem os dízimos, e que os levitas trariam os dízimos dos dízimos à Casa do nosso Deus, às câmaras da casa do tesouro." },
{name:'161039',l:'16',c:'10',v:'39',texto:"Porque àquelas câmaras os filhos de Israel e os filhos de Levi devem trazer ofertas alçadas do grão, do mosto e do azeite; porquanto ali estão os utensílios do santuário, como também os sacerdotes que ministram, e os porteiros, e os cantores; e que assim não desampararíamos a Casa do nosso Deus." },
],
numVersiculos: 39,
},

c11: {
versiculos:[
{name:'16111',l:'16',c:'11',v:'1',texto:"E os príncipes do povo habitaram em Jerusalém, mas o resto do povo lançou sortes para tirar um de dez, para que habitasse na santa cidade de Jerusalém, e as nove partes, nas outras cidades." },
{name:'16112',l:'16',c:'11',v:'2',texto:"E o povo bendisse a todos os homens que voluntariamente se ofereciam para habitar em Jerusalém." },
{name:'16113',l:'16',c:'11',v:'3',texto:"E estes são os chefes da província que habitaram em Jerusalém ( porém nas cidades de Judá habitou cada um na sua possessão, nas suas cidades, a saber, Israel, os sacerdotes, e os levitas, e os netineus, e os filhos dos servos de Salomão )." },
{name:'16114',l:'16',c:'11',v:'4',texto:"Habitaram, pois, em Jerusalém alguns dos filhos de Judá e dos filhos de Benjamim. Dos filhos de Judá: Ataías, filho de Uzias, filho de Zacarias, filho de Amarias, filho de Sefatias, filho de Maalalel, dos filhos de Perez;" },
{name:'16115',l:'16',c:'11',v:'5',texto:"e Maaséias, filho de Baruque, filho de Col-Hozé, filho de Hazaías, filho de Adaías, filho de Joiaribe, filho de Zacarias, filho do silonita." },
{name:'16116',l:'16',c:'11',v:'6',texto:"Todos os filhos de Perez, que habitaram em Jerusalém, foram quatrocentos e sessenta e oito homens valentes." },
{name:'16117',l:'16',c:'11',v:'7',texto:"E estes são os filhos de Benjamim: Salu, filho de Mesulão, filho de Joede, filho de Pedaías, filho de Colaías, filho de Maaséias, filho de Itiel, filho de Jesaías." },
{name:'16118',l:'16',c:'11',v:'8',texto:"E, depois dele, Gabai e Salai: novecentos e vinte e oito." },
{name:'16119',l:'16',c:'11',v:'9',texto:"E Joel, filho de Zicri, superintendente sobre eles; e Judá, filho de Senua, segundo sobre a cidade." },
{name:'161110',l:'16',c:'11',v:'10',texto:"Dos sacerdotes: Jedaías, filho de Joiaribe, Jaquim," },
{name:'161111',l:'16',c:'11',v:'11',texto:"Seraías, filho de Hilquias, filho de Mesulão, filho de Zadoque, filho de Meraiote, filho de Aitube, maioral da Casa de Deus," },
{name:'161112',l:'16',c:'11',v:'12',texto:"e seus irmãos, que faziam a obra da casa, oitocentos e vinte e dois; e Adaías, filho de Jeroão, filho de Pelalias, filho de Anzi, filho de Zacarias, filho de Pasur, filho de Malquias," },
{name:'161113',l:'16',c:'11',v:'13',texto:"e seus irmãos, cabeças dos pais, duzentos e quarenta e dois; e Amasai, filho de Azarel, filho de Azai, filho de Mesilemote, filho de Imer," },
{name:'161114',l:'16',c:'11',v:'14',texto:"e os irmãos deles, varões valentes, cento e vinte e oito, e superintendente sobre eles Zabdiel, filho de Gedolim." },
{name:'161115',l:'16',c:'11',v:'15',texto:"E dos levitas: Semaías, filho de Hassube, filho de Azricão, filho de Hasabias, filho de Buni;" },
{name:'161116',l:'16',c:'11',v:'16',texto:"e Sabetai e Jozabade, dos cabeças dos levitas, presidiam sobre a obra de fora da Casa de Deus;" },
{name:'161117',l:'16',c:'11',v:'17',texto:"e Matanias, filho de Mica, filho de Zabdi, filho de Asafe, o chefe, que era quem começava a dar graças na oração, e Baquebuquias, o segundo de seus irmãos; depois, Abda, filho de Samua, filho de Galal, filho de Jedutum." },
{name:'161118',l:'16',c:'11',v:'18',texto:"Todos os levitas na santa cidade foram duzentos e oitenta e quatro." },
{name:'161119',l:'16',c:'11',v:'19',texto:"E os porteiros: Acube, Talmom, com seus irmãos, os guardas das portas, cento e setenta e dois." },
{name:'161120',l:'16',c:'11',v:'20',texto:"E o resto de Israel, dos sacerdotes e levitas, esteve em todas as cidades de Judá, cada um na sua herdade." },
{name:'161121',l:'16',c:'11',v:'21',texto:"E os netineus habitaram em Ofel; e Zia e Gispa presidiam sobre os netineus." },
{name:'161122',l:'16',c:'11',v:'22',texto:"E o superintendente dos levitas em Jerusalém foi Uzi, filho de Bani, filho de Hasabias, filho de Matanias, filho de Mica, dos filhos de Asafe, os cantores, ao serviço da Casa de Deus." },
{name:'161123',l:'16',c:'11',v:'23',texto:"Porque havia um mandado do rei acerca deles, a saber, uma certa porção para os cantores, cada qual no seu dia." },
{name:'161124',l:'16',c:'11',v:'24',texto:"E Petaías, filho de Mesezabel, dos filhos de Zerá, filho de Judá, estava à mão do rei, em todos os negócios do povo." },
{name:'161125',l:'16',c:'11',v:'25',texto:"E, quanto às aldeias, com as suas terras, alguns dos filhos de Judá habitaram em Quiriate-Arba e nos lugares da sua jurisdição; e em Dibom e nos lugares da sua jurisdição; e em Jecabzeel e nas suas aldeias," },
{name:'161126',l:'16',c:'11',v:'26',texto:"e em Jesua, e em Molada, e em Bete-Palete," },
{name:'161127',l:'16',c:'11',v:'27',texto:"e em Hasar-Sual, e em Berseba, e nos lugares da sua jurisdição;" },
{name:'161128',l:'16',c:'11',v:'28',texto:"e em Ziclague, e em Mecona, e nos lugares da sua jurisdição;" },
{name:'161129',l:'16',c:'11',v:'29',texto:"e em En-Rimom, e em Zorá, e em Jarmute;" },
{name:'161130',l:'16',c:'11',v:'30',texto:"em Zanoa, Adulão e nas suas aldeias; em Laquis e nas suas terras; em Azeca e nos lugares da sua jurisdição. E acamparam-se desde Berseba até ao vale de Hinom." },
{name:'161131',l:'16',c:'11',v:'31',texto:"E os filhos de Benjamim, de Geba, habitaram em Micmás, e Aia, e Betel, e nos lugares da sua jurisdição;" },
{name:'161132',l:'16',c:'11',v:'32',texto:"e em Anatote, em Nobe, em Ananias," },
{name:'161133',l:'16',c:'11',v:'33',texto:"em Hazor, em Ramá, em Gitaim," },
{name:'161134',l:'16',c:'11',v:'34',texto:"em Hadide, em Zeboim, em Nebalate," },
{name:'161135',l:'16',c:'11',v:'35',texto:"em Lode e em Ono, no vale dos Artífices." },
{name:'161136',l:'16',c:'11',v:'36',texto:"E alguns dos levitas habitaram nos repartimentos de Judá e de Benjamim." },
],
numVersiculos: 36,
},

c12: {
versiculos:[
{name:'16121',l:'16',c:'12',v:'1',texto:"Estes são os sacerdotes e levitas que subiram com Zorobabel, filho de Sealtiel, e com Jesua: Seraías, Jeremias, Esdras," },
{name:'16122',l:'16',c:'12',v:'2',texto:"Amarias, Maluque, Hatus," },
{name:'16123',l:'16',c:'12',v:'3',texto:"Secanias, Reum, Meremote," },
{name:'16124',l:'16',c:'12',v:'4',texto:"Ido, Ginetoi, Abias," },
{name:'16125',l:'16',c:'12',v:'5',texto:"Miamim, Maadias, Bilga," },
{name:'16126',l:'16',c:'12',v:'6',texto:"Semaías, Joiaribe, Jedaías," },
{name:'16127',l:'16',c:'12',v:'7',texto:"Salu, Amoque, Hilquias e Jedaías; estes foram os chefes dos sacerdotes e de seus irmãos, nos dias de Jesua." },
{name:'16128',l:'16',c:'12',v:'8',texto:"E foram os levitas: Jesua, Binui, Cadmiel, Serebias, Judá e Matanias; este e seus irmãos presidiam sobre os louvores." },
{name:'16129',l:'16',c:'12',v:'9',texto:"E Baquebuquias e Uni, seus irmãos, estavam defronte dele nas guardas." },
{name:'161210',l:'16',c:'12',v:'10',texto:"E Jesua gerou a Joiaquim, e Joiaquim gerou a Eliasibe, e Eliasibe gerou a Joiada," },
{name:'161211',l:'16',c:'12',v:'11',texto:"e Joiada gerou a Jônatas, e Jônatas gerou a Jadua." },
{name:'161212',l:'16',c:'12',v:'12',texto:"E, nos dias de Joiaquim, foram sacerdotes, chefes das casas dos pais: de Seraías, Meraías; de Jeremias, Hananias;" },
{name:'161213',l:'16',c:'12',v:'13',texto:"de Esdras, Mesulão; de Amarias, Joanã;" },
{name:'161214',l:'16',c:'12',v:'14',texto:"de Maluqui, Jônatas; de Sebanias, José;" },
{name:'161215',l:'16',c:'12',v:'15',texto:"de Harim, Adna; de Meraiote, Helcai;" },
{name:'161216',l:'16',c:'12',v:'16',texto:"de Ido, Zacarias; de Ginetom, Mesulão;" },
{name:'161217',l:'16',c:'12',v:'17',texto:"de Abias, Zicri; de Miniamim e de Moadias, Piltai;" },
{name:'161218',l:'16',c:'12',v:'18',texto:"de Bilga, Samua; de Semaías, Jônatas;" },
{name:'161219',l:'16',c:'12',v:'19',texto:"e de Joiaribe, Matenai; de Jedaías, Uzi;" },
{name:'161220',l:'16',c:'12',v:'20',texto:"de Salai, Calai; de Amoque, Héber;" },
{name:'161221',l:'16',c:'12',v:'21',texto:"de Hilquias, Hasabias; de Jedaías, Netanel." },
{name:'161222',l:'16',c:'12',v:'22',texto:"Dos levitas foram, nos dias de Eliasibe, inscritos como chefes das casas dos pais, Joiada, e Jonã, e Jadua, como também os sacerdotes, até ao reinado de Dario, o persa." },
{name:'161223',l:'16',c:'12',v:'23',texto:"Os filhos de Levi foram inscritos como chefes das casas dos pais no livro das crônicas, até aos dias de Joanã, filho de Eliasibe." },
{name:'161224',l:'16',c:'12',v:'24',texto:"Foram, pois, os chefes dos levitas: Hasabias, Serebias e Jesua, filho de Cadmiel; e seus irmãos estavam defronte deles para louvarem e darem graças, segundo o mandado de Davi, homem de Deus, guarda contra guarda." },
{name:'161225',l:'16',c:'12',v:'25',texto:"Matanias, Baquebuquias, Obadias, Mesulão, Talmom e Acube eram porteiros que faziam a guarda às tesourarias das portas." },
{name:'161226',l:'16',c:'12',v:'26',texto:"Estes foram nos dias de Joiaquim, filho de Jesua, filho de Jozadaque, como também nos dias de Neemias, o governador, e do sacerdote Esdras, o escriba." },
{name:'161227',l:'16',c:'12',v:'27',texto:"E, na dedicação dos muros de Jerusalém, buscaram os levitas de todos os seus lugares, para os trazerem, a fim de fazerem a dedicação com alegria, louvores, canto, saltérios, alaúdes e harpas." },
{name:'161228',l:'16',c:'12',v:'28',texto:"E se ajuntaram os filhos dos cantores, tanto da campina dos arredores de Jerusalém como das aldeias de Netofa," },
{name:'161229',l:'16',c:'12',v:'29',texto:"como também da casa de Gilgal e dos campos de Gibeá e Azmavete; porque os cantores tinham edificado para si aldeias nos arredores de Jerusalém." },
{name:'161230',l:'16',c:'12',v:'30',texto:"E purificaram-se os sacerdotes e os levitas; e logo purificaram o povo, e as portas, e o muro." },
{name:'161231',l:'16',c:'12',v:'31',texto:"Então, fiz subir os príncipes de Judá sobre o muro e ordenei dois grandes coros e procissões, sendo um à mão direita sobre o muro da banda da Porta do Monturo." },
{name:'161232',l:'16',c:'12',v:'32',texto:"E, após eles, ia Hosaías, e a metade dos príncipes de Judá," },
{name:'161233',l:'16',c:'12',v:'33',texto:"e Azarias, Esdras, Mesulão," },
{name:'161234',l:'16',c:'12',v:'34',texto:"Judá, Benjamim, Semaías e Jeremias;" },
{name:'161235',l:'16',c:'12',v:'35',texto:"e dos filhos dos sacerdotes, com trombetas: Zacarias, filho de Jônatas, filho de Semaías, filho de Matanias, filho de Micaías, filho de Zacur, filho de Asafe," },
{name:'161236',l:'16',c:'12',v:'36',texto:"e seus irmãos, Semaías, Azarel, Milalai, Gilalai, Maai, Netanel, Judá e Hanani, com os instrumentos músicos de Davi, homem de Deus; e Esdras, o escriba, ia adiante deles." },
{name:'161237',l:'16',c:'12',v:'37',texto:"Indo assim para a Porta da Fonte e defronte deles, subiram as escadas da Cidade de Davi pela subida do muro, desde cima da casa de Davi até à Porta das Águas, da banda do oriente." },
{name:'161238',l:'16',c:'12',v:'38',texto:"E o segundo coro ia em frente, e eu, após ele; e a metade do povo ia sobre o muro, desde a Torre dos Fornos até à Muralha Larga;" },
{name:'161239',l:'16',c:'12',v:'39',texto:"e desde a Porta de Efraim, e desde a Porta Velha, e desde a Porta do Peixe e a Torre de Hananel e a Torre de Meá até à Porta do Gado; e pararam à Porta da Prisão." },
{name:'161240',l:'16',c:'12',v:'40',texto:"Então, ambos os coros pararam na Casa de Deus, como também eu e a metade dos magistrados comigo." },
{name:'161241',l:'16',c:'12',v:'41',texto:"E os sacerdotes Eliaquim, Maaséias, Miniamim, Micaías, Elioenai, Zacarias e Hananias iam com trombetas," },
{name:'161242',l:'16',c:'12',v:'42',texto:"como também Maaséias, e Semaías, e Eleazar, e Uzi, e Joanã, e Malquias, e Elão, e Ezer; e faziam-se ouvir os cantores, juntamente com Jezraías, o superintendente." },
{name:'161243',l:'16',c:'12',v:'43',texto:"E sacrificaram, no mesmo dia, grandes sacrifícios e se alegraram, porque Deus os alegrara com grande alegria; e até as mulheres e os meninos se alegraram, de modo que a alegria de Jerusalém se ouviu até de longe." },
{name:'161244',l:'16',c:'12',v:'44',texto:"Também, no mesmo dia, se nomearam homens sobre as câmaras, para os tesouros, para as ofertas alçadas, para as primícias e para os dízimos, para ajuntarem nelas, das terras das cidades, as porções designadas pela Lei para os sacerdotes e para os levitas; porque Judá estava alegre por causa dos sacerdotes e dos levitas que assistiam ali." },
{name:'161245',l:'16',c:'12',v:'45',texto:"E faziam a guarda do seu Deus e a guarda da purificação; como também os cantores e porteiros, conforme o mandado de Davi e de seu filho Salomão." },
{name:'161246',l:'16',c:'12',v:'46',texto:"Porque, já nos dias de Davi e de Asafe, desde a antiguidade, havia chefes dos cantores, e cânticos de louvores, e ação de graças a Deus." },
{name:'161247',l:'16',c:'12',v:'47',texto:"Pelo que todo o Israel, já nos dias de Zorobabel e nos dias de Neemias, dava as porções dos cantores e dos porteiros, a cada um no seu dia; e santificavam as porções para os levitas, e os levitas santificavam para os filhos de Arão." },
],
numVersiculos: 47,
},

c13: {
versiculos:[
{name:'16131',l:'16',c:'13',v:'1',texto:"Naquele dia, leu-se no livro de Moisés aos ouvidos do povo; e achou-se escrito nele que os amonitas e os moabitas não entrassem jamais na congregação de Deus," },
{name:'16132',l:'16',c:'13',v:'2',texto:"porquanto não tinham saído ao encontro dos filhos de Israel com pão e água; antes, assalariaram contra eles a Balaão para os amaldiçoar, ainda que o nosso Deus converteu a maldição em bênção." },
{name:'16133',l:'16',c:'13',v:'3',texto:"Sucedeu, pois, que, ouvindo eles esta lei, apartaram de Israel toda mistura." },
{name:'16134',l:'16',c:'13',v:'4',texto:"Ora, antes disso, Eliasibe, sacerdote, que presidia sobre a câmara da Casa do nosso Deus, se tinha aparentado com Tobias;" },
{name:'16135',l:'16',c:'13',v:'5',texto:"e fizera-lhe uma câmara grande, onde dantes se metiam as ofertas de manjares, o incenso, os utensílios e os dízimos do grão, do mosto e do azeite, que se ordenaram para os levitas, e cantores, e porteiros, como também a oferta alçada para os sacerdotes." },
{name:'16136',l:'16',c:'13',v:'6',texto:"Mas, durante tudo isso, não estava eu em Jerusalém, porque, no ano trinta e dois de Artaxerxes, rei de Babilônia, vim eu ter com o rei; mas, ao cabo de alguns dias, tornei a alcançar licença do rei." },
{name:'16137',l:'16',c:'13',v:'7',texto:"E vim a Jerusalém e compreendi o mal que Eliasibe fizera para beneficiar a Tobias, fazendo-lhe uma câmara nos pátios da Casa de Deus," },
{name:'16138',l:'16',c:'13',v:'8',texto:"o que muito me desagradou; de sorte que lancei todos os móveis da casa de Tobias fora da câmara." },
{name:'16139',l:'16',c:'13',v:'9',texto:"E, ordenando-o eu, purificaram as câmaras; e tornei a trazer ali os utensílios da Casa de Deus, com as ofertas de manjares e o incenso." },
{name:'161310',l:'16',c:'13',v:'10',texto:"Também entendi que o quinhão dos levitas se lhes não dava, de maneira que os levitas e os cantores, que faziam a obra, tinham fugido cada um para a sua terra." },
{name:'161311',l:'16',c:'13',v:'11',texto:"Então, contendi com os magistrados e disse: Por que se desamparou a Casa de Deus? Porém eu os ajuntei e os restaurei no seu posto." },
{name:'161312',l:'16',c:'13',v:'12',texto:"Então, todo o Judá trouxe os dízimos do grão, e do mosto, e do azeite aos celeiros." },
{name:'161313',l:'16',c:'13',v:'13',texto:"E por tesoureiros pus sobre os celeiros a Selemias, o sacerdote, e a Zadoque, o escrivão, e a Pedaías, dentre os levitas; e com eles Hanã, filho de Zacur, filho de Matanias; porque se tinham achado fiéis, e se lhes encarregou a eles a distribuição para seus irmãos." },
{name:'161314',l:'16',c:'13',v:'14',texto:"( Por isto, Deus meu, lembra-te de mim e não risques as beneficências que eu fiz à Casa de meu Deus e às suas guardas. )" },
{name:'161315',l:'16',c:'13',v:'15',texto:"Naqueles dias, vi em Judá os que pisavam lagares ao sábado e traziam feixes que carregavam sobre os jumentos; como também vinho, uvas e figos e toda casta de cargas, que traziam a Jerusalém no dia de sábado; e protestei contra eles no dia em que vendiam mantimentos." },
{name:'161316',l:'16',c:'13',v:'16',texto:"Também tírios habitavam dentro e traziam peixe e toda mercadoria, que no sábado vendiam aos filhos de Judá e em Jerusalém." },
{name:'161317',l:'16',c:'13',v:'17',texto:"E contendi com os nobres de Judá e lhes disse: Que mal é este que fazeis, profanando o dia de sábado?" },
{name:'161318',l:'16',c:'13',v:'18',texto:"Porventura, não fizeram vossos pais assim, e nosso Deus não trouxe todo este mal sobre nós e sobre esta cidade? E vós ainda mais acrescentais o ardor de sua ira sobre Israel, profanando o sábado." },
{name:'161319',l:'16',c:'13',v:'19',texto:"Sucedeu, pois, que, dando as portas de Jerusalém já sombra antes do sábado, ordenando-o eu, as portas se fecharam; e mandei que não as abrissem até passado o sábado; e pus às portas alguns de meus moços, para que nenhuma carga entrasse no dia de sábado." },
{name:'161320',l:'16',c:'13',v:'20',texto:"Então, os negociantes e os vendedores de toda mercadoria passaram a noite fora de Jerusalém, uma ou duas vezes." },
{name:'161321',l:'16',c:'13',v:'21',texto:"Protestei, pois, contra eles e lhes disse: Por que passais a noite defronte do muro? Se outra vez o fizerdes, hei de lançar mão sobre vós. Daquele tempo em diante, não vieram no sábado." },
{name:'161322',l:'16',c:'13',v:'22',texto:"Também disse aos levitas que se purificassem e viessem guardar as portas, para santificar o sábado. ( Nisso também, Deus meu, lembra-te de mim; e perdoa-me segundo a abundância da tua benignidade. )" },
{name:'161323',l:'16',c:'13',v:'23',texto:"Vi também, naqueles dias, judeus que tinham casado com mulheres asdoditas, amonitas e moabitas." },
{name:'161324',l:'16',c:'13',v:'24',texto:"E seus filhos falavam meio asdodita e não podiam falar judaico, senão segundo a língua de cada povo." },
{name:'161325',l:'16',c:'13',v:'25',texto:"E contendi com eles, e os amaldiçoei, e espanquei alguns deles, e lhes arranquei os cabelos, e os fiz jurar por Deus, dizendo: Não dareis mais vossas filhas a seus filhos e não tomareis mais suas filhas, nem para vossos filhos nem para vós mesmos." },
{name:'161326',l:'16',c:'13',v:'26',texto:"Porventura, não pecou nisso Salomão, rei de Israel, não havendo entre muitas nações rei semelhante a ele, e sendo amado de seu Deus, e pondo-o Deus rei sobre todo o Israel? E, contudo, as mulheres estranhas o fizeram pecar." },
{name:'161327',l:'16',c:'13',v:'27',texto:"E dar-vos-íamos nós ouvidos, para fazermos todo este grande mal, prevaricando contra o nosso Deus, casando com mulheres estranhas?" },
{name:'161328',l:'16',c:'13',v:'28',texto:"Também um dos filhos de Joiada, filho de Eliasibe, o sumo sacerdote, era genro de Sambalate, o horonita, pelo que o afugentei de mim." },
{name:'161329',l:'16',c:'13',v:'29',texto:"Lembra-te deles, Deus meu, pois contaminaram o sacerdócio, como também o concerto do sacerdócio e dos levitas." },
{name:'161330',l:'16',c:'13',v:'30',texto:"Assim, os alimpei de todos os estranhos e designei os cargos dos sacerdotes e dos levitas, cada um na sua obra," },
{name:'161331',l:'16',c:'13',v:'31',texto:"como também para as ofertas da lenha em tempos determinados e para as primícias. Lembra-te de mim, Deus meu, para o bem." },
],
numVersiculos: 31,
},


};
