BibliaJFA.eclesiastes = {
	libro: "Eclesiastes",
	numCapitulos: 12,

c1: {
versiculos:[
{name:'2111',l:'21',c:'1',v:'1',texto:"Palavras do pregador, filho de Davi, rei em Jerusalém:" },
{name:'2112',l:'21',c:'1',v:'2',texto:"Vaidade de vaidades! —diz o pregador, vaidade de vaidades! É tudo vaidade." },
{name:'2113',l:'21',c:'1',v:'3',texto:"Que vantagem tem o homem de todo o seu trabalho, que ele faz debaixo do sol?" },
{name:'2114',l:'21',c:'1',v:'4',texto:"Uma geração vai, e outra geração vem; mas a terra para sempre permanece." },
{name:'2115',l:'21',c:'1',v:'5',texto:"E nasce o sol, e põe-se o sol, e volta ao seu lugar, de onde nasceu." },
{name:'2116',l:'21',c:'1',v:'6',texto:"O vento vai para o sul e faz o seu giro para o norte; continuamente vai girando o vento e volta fazendo os seus circuitos." },
{name:'2117',l:'21',c:'1',v:'7',texto:"Todos os ribeiros vão para o mar, e, contudo, o mar não se enche; para o lugar para onde os ribeiros vão, para aí tornam eles a ir." },
{name:'2118',l:'21',c:'1',v:'8',texto:"Todas essas coisas se cansam tanto, que ninguém o pode declarar; os olhos não se fartam de ver, nem os ouvidos de ouvir." },
{name:'2119',l:'21',c:'1',v:'9',texto:"O que foi, isso é o que há de ser; e o que se fez, isso se tornará a fazer; de modo que nada há novo debaixo do sol." },
{name:'21110',l:'21',c:'1',v:'10',texto:"Há alguma coisa de que se possa dizer: Vê, isto é novo? Já foi nos séculos passados, que foram antes de nós." },
{name:'21111',l:'21',c:'1',v:'11',texto:"Já não há lembrança das coisas que precederam; e das coisas que hão de ser também delas não haverá lembrança, nos que hão de vir depois." },
{name:'21112',l:'21',c:'1',v:'12',texto:"Eu, o pregador, fui rei sobre Israel em Jerusalém." },
{name:'21113',l:'21',c:'1',v:'13',texto:"E apliquei o meu coração a esquadrinhar e a informar-me com sabedoria de tudo quanto sucede debaixo do céu; essa enfadonha ocupação deu Deus aos filhos dos homens, para nela os exercitar." },
{name:'21114',l:'21',c:'1',v:'14',texto:"Atentei para todas as obras que se fazem debaixo do sol, e eis que tudo era vaidade e aflição de espírito." },
{name:'21115',l:'21',c:'1',v:'15',texto:"Aquilo que é torto não se pode endireitar; aquilo que falta não pode ser calculado." },
{name:'21116',l:'21',c:'1',v:'16',texto:"Falei eu com o meu coração, dizendo: Eis que eu me engrandeci e sobrepujei em sabedoria a todos os que houve antes de mim, em Jerusalém; na verdade, o meu coração contemplou abundantemente a sabedoria e a ciência." },
{name:'21117',l:'21',c:'1',v:'17',texto:"E apliquei o meu coração a conhecer a sabedoria e a conhecer os desvarios e as loucuras e vim a saber que também isso era aflição de espírito." },
{name:'21118',l:'21',c:'1',v:'18',texto:"Porque, na muita sabedoria, há muito enfado; e o que aumenta em ciência aumenta em trabalho." },
],
numVersiculos: 18,
},

c2: {
versiculos:[
{name:'2121',l:'21',c:'2',v:'1',texto:"Disse eu no meu coração: Ora, vem, eu te provarei com a alegria; portanto, goza o prazer; mas eis que também isso era vaidade." },
{name:'2122',l:'21',c:'2',v:'2',texto:"Do riso disse: Está doido; e da alegria: De que serve esta?" },
{name:'2123',l:'21',c:'2',v:'3',texto:"Busquei no meu coração como me daria ao vinho ( regendo, porém, o meu coração com sabedoria ) e como reteria a loucura, até ver o que seria melhor que os filhos dos homens fizessem debaixo do céu, durante o número dos dias de sua vida." },
{name:'2124',l:'21',c:'2',v:'4',texto:"Fiz para mim obras magníficas; edifiquei para mim casas; plantei para mim vinhas." },
{name:'2125',l:'21',c:'2',v:'5',texto:"Fiz para mim hortas e jardins e plantei neles árvores de toda espécie de fruto." },
{name:'2126',l:'21',c:'2',v:'6',texto:"Fiz para mim tanques de águas, para regar com eles o bosque em que reverdeciam as árvores." },
{name:'2127',l:'21',c:'2',v:'7',texto:"Adquiri servos e servas e tive servos nascidos em casa; também tive grande possessão de vacas e ovelhas, mais do que todos os que houve antes de mim, em Jerusalém." },
{name:'2128',l:'21',c:'2',v:'8',texto:"Amontoei também para mim prata, e ouro, e jóias de reis e das províncias; provi-me de cantores, e de cantoras, e das delícias dos filhos dos homens, e de instrumentos de música de toda sorte." },
{name:'2129',l:'21',c:'2',v:'9',texto:"E engrandeci-me e aumentei mais do que todos os que houve antes de mim, em Jerusalém; perseverou também comigo a minha sabedoria." },
{name:'21210',l:'21',c:'2',v:'10',texto:"E tudo quanto desejaram os meus olhos não lhos neguei, nem privei o meu coração de alegria alguma; mas o meu coração se alegrou por todo o meu trabalho, e esta foi a minha porção de todo o meu trabalho." },
{name:'21211',l:'21',c:'2',v:'11',texto:"E olhei eu para todas as obras que fizeram as minhas mãos, como também para o trabalho que eu, trabalhando, tinha feito; e eis que tudo era vaidade e aflição de espírito e que proveito nenhum havia debaixo do sol." },
{name:'21212',l:'21',c:'2',v:'12',texto:"Então, passei à contemplação da sabedoria, e dos desvarios, e da doidice; porque que fará o homem que seguir ao rei? O mesmo que outros já fizeram." },
{name:'21213',l:'21',c:'2',v:'13',texto:"Então, vi eu que a sabedoria é mais excelente do que a estultícia, quanto a luz é mais excelente do que as trevas." },
{name:'21214',l:'21',c:'2',v:'14',texto:"Os olhos do sábio estão na sua cabeça, mas o louco anda em trevas; também, então, entendi eu que o mesmo lhes sucede a todos." },
{name:'21215',l:'21',c:'2',v:'15',texto:"Pelo que eu disse no meu coração: Como acontece ao tolo, assim me sucederá a mim; por que, então, busquei eu mais a sabedoria? Então, disse no meu coração que também isso era vaidade." },
{name:'21216',l:'21',c:'2',v:'16',texto:"Porque nunca haverá mais lembrança do sábio do que do tolo; porquanto de tudo nos dias futuros total esquecimento haverá. E como morre o sábio, assim morre o tolo!" },
{name:'21217',l:'21',c:'2',v:'17',texto:"Pelo que aborreci esta vida, porque a obra que se faz debaixo do sol me era penosa; sim, tudo é vaidade e aflição de espírito." },
{name:'21218',l:'21',c:'2',v:'18',texto:"Também eu aborreci todo o meu trabalho, em que trabalhei debaixo do sol, visto como eu havia de deixá-lo ao homem que viesse depois de mim." },
{name:'21219',l:'21',c:'2',v:'19',texto:"E quem sabe se será sábio ou tolo? Contudo, ele se assenhoreará de todo o meu trabalho em que trabalhei e em que me houve sabiamente debaixo do sol; também isso é vaidade." },
{name:'21220',l:'21',c:'2',v:'20',texto:"Pelo que eu me apliquei a fazer que o meu coração perdesse a esperança de todo trabalho em que trabalhei debaixo do sol." },
{name:'21221',l:'21',c:'2',v:'21',texto:"Porque há homem cujo trabalho é feito com sabedoria, e ciência, e destreza; contudo, a um homem que não trabalhou nele, o deixará como porção sua; também isso é vaidade e grande enfado." },
{name:'21222',l:'21',c:'2',v:'22',texto:"Porque que mais tem o homem de todo o seu trabalho e da fadiga do seu coração, em que ele anda trabalhando debaixo do sol?" },
{name:'21223',l:'21',c:'2',v:'23',texto:"Porque todos os seus dias são dores, e a sua ocupação é desgosto; até de noite não descansa o seu coração; também isso é vaidade." },
{name:'21224',l:'21',c:'2',v:'24',texto:"Não é, pois, bom para o homem que coma e beba e que faça gozar a sua alma do bem do seu trabalho? Isso também eu vi que vem da mão de Deus." },
{name:'21225',l:'21',c:'2',v:'25',texto:"( Porque quem pode comer ou quem pode gozar melhor do que eu? )" },
{name:'21226',l:'21',c:'2',v:'26',texto:"Porque ao homem que é bom diante dele, dá Deus sabedoria, e conhecimento, e alegria; mas ao pecador dá trabalho, para que ele ajunte, e amontoe, e o dê ao bom perante a sua face. Também isso é vaidade e aflição de espírito." },
],
numVersiculos: 26,
},

c3: {
versiculos:[
{name:'2131',l:'21',c:'3',v:'1',texto:"Tudo tem o seu tempo determinado, e há tempo para todo o propósito debaixo do céu:" },
{name:'2132',l:'21',c:'3',v:'2',texto:"há tempo de nascer e tempo de morrer; tempo de plantar e tempo de arrancar o que se plantou;" },
{name:'2133',l:'21',c:'3',v:'3',texto:"tempo de matar e tempo de curar; tempo de derribar e tempo de edificar;" },
{name:'2134',l:'21',c:'3',v:'4',texto:"tempo de chorar e tempo de rir; tempo de prantear e tempo de saltar;" },
{name:'2135',l:'21',c:'3',v:'5',texto:"tempo de espalhar pedras e tempo de ajuntar pedras; tempo de abraçar e tempo de afastar-se de abraçar;" },
{name:'2136',l:'21',c:'3',v:'6',texto:"tempo de buscar e tempo de perder; tempo de guardar e tempo de deitar fora;" },
{name:'2137',l:'21',c:'3',v:'7',texto:"tempo de rasgar e tempo de coser; tempo de estar calado e tempo de falar;" },
{name:'2138',l:'21',c:'3',v:'8',texto:"tempo de amar e tempo de aborrecer; tempo de guerra e tempo de paz." },
{name:'2139',l:'21',c:'3',v:'9',texto:"Que vantagem tem o trabalhador naquilo em que trabalha?" },
{name:'21310',l:'21',c:'3',v:'10',texto:"Tenho visto o trabalho que Deus deu aos filhos dos homens, para com ele os afligir." },
{name:'21311',l:'21',c:'3',v:'11',texto:"Tudo fez formoso em seu tempo; também pôs o mundo no coração deles, sem que o homem possa descobrir a obra que Deus fez desde o princípio até ao fim." },
{name:'21312',l:'21',c:'3',v:'12',texto:"Já tenho conhecido que não há coisa melhor para eles do que se alegrarem e fazerem bem na sua vida;" },
{name:'21313',l:'21',c:'3',v:'13',texto:"e também que todo homem coma e beba e goze do bem de todo o seu trabalho. Isso é um dom de Deus." },
{name:'21314',l:'21',c:'3',v:'14',texto:"Eu sei que tudo quanto Deus faz durará eternamente; nada se lhe deve acrescentar e nada se lhe deve tirar. E isso faz Deus para que haja temor diante dele." },
{name:'21315',l:'21',c:'3',v:'15',texto:"O que é já foi; e o que há de ser também já foi; e Deus pede conta do que passou." },
{name:'21316',l:'21',c:'3',v:'16',texto:"Vi mais debaixo do sol: no lugar do juízo, impiedade; e no lugar da justiça, impiedade ainda." },
{name:'21317',l:'21',c:'3',v:'17',texto:"Eu disse no meu coração: Deus julgará o justo e o ímpio; porque há um tempo para todo intento e para toda obra." },
{name:'21318',l:'21',c:'3',v:'18',texto:"Disse eu no meu coração: é por causa dos filhos dos homens, para que Deus possa prová-los, e eles possam ver que são em si mesmos como os animais." },
{name:'21319',l:'21',c:'3',v:'19',texto:"Porque o que sucede aos filhos dos homens, isso mesmo também sucede aos animais; a mesma coisa lhes sucede: como morre um, assim morre o outro, todos têm o mesmo fôlego; e a vantagem dos homens sobre os animais não é nenhuma, porque todos são vaidade." },
{name:'21320',l:'21',c:'3',v:'20',texto:"Todos vão para um lugar; todos são pó e todos ao pó tornarão." },
{name:'21321',l:'21',c:'3',v:'21',texto:"Quem adverte que o fôlego dos filhos dos homens sobe para cima e que o fôlego dos animais desce para baixo da terra?" },
{name:'21322',l:'21',c:'3',v:'22',texto:"Assim que tenho visto que não há coisa melhor do que alegrar-se o homem nas suas obras, porque essa é a sua porção; porque quem o fará voltar para ver o que será depois dele?" },
],
numVersiculos: 22,
},

c4: {
versiculos:[
{name:'2141',l:'21',c:'4',v:'1',texto:"Depois, voltei-me e atentei para todas as opressões que se fazem debaixo do sol; e eis que vi as lágrimas dos que foram oprimidos e dos que não têm consolador; e a força estava da banda dos seus opressores; mas eles não tinham nenhum consolador." },
{name:'2142',l:'21',c:'4',v:'2',texto:"Pelo que eu louvei os que já morreram, mais do que os que vivem ainda." },
{name:'2143',l:'21',c:'4',v:'3',texto:"E melhor que uns e outros é aquele que ainda não é; que não viu as más obras que se fazem debaixo do sol." },
{name:'2144',l:'21',c:'4',v:'4',texto:"Também vi eu que todo trabalho e toda destreza em obras trazem ao homem a inveja do seu próximo. Também isso é vaidade e aflição de espírito." },
{name:'2145',l:'21',c:'4',v:'5',texto:"O tolo cruza as suas mãos e come a sua própria carne." },
{name:'2146',l:'21',c:'4',v:'6',texto:"Melhor é uma mão cheia com descanso do que ambas as mãos cheias com trabalho e aflição de espírito." },
{name:'2147',l:'21',c:'4',v:'7',texto:"Outra vez me voltei e vi vaidade debaixo do sol." },
{name:'2148',l:'21',c:'4',v:'8',texto:"Há um que é só e não tem segundo; sim, ele não tem filho nem irmã; e, contudo, de todo o seu trabalho não há fim, nem os seus olhos se fartam de riquezas; e não diz: Para quem trabalho eu, privando a minha alma do bem? Também isso é vaidade e enfadonha ocupação." },
{name:'2149',l:'21',c:'4',v:'9',texto:"Melhor é serem dois do que um, porque têm melhor paga do seu trabalho." },
{name:'21410',l:'21',c:'4',v:'10',texto:"Porque, se um cair, o outro levanta o seu companheiro; mas ai do que estiver só; pois, caindo, não haverá outro que o levante." },
{name:'21411',l:'21',c:'4',v:'11',texto:"Também se dois dormirem juntos, eles se aquentarão; mas um só como se aquentará?" },
{name:'21412',l:'21',c:'4',v:'12',texto:"E, se alguém quiser prevalecer contra um, os dois lhe resistirão; e o cordão de três dobras não se quebra tão depressa." },
{name:'21413',l:'21',c:'4',v:'13',texto:"Melhor é o jovem pobre e sábio do que o rei velho e insensato, que se não deixa mais admoestar." },
{name:'21414',l:'21',c:'4',v:'14',texto:"Porque um sai do cárcere para reinar; sim, um que nasceu pobre no seu reino." },
{name:'21415',l:'21',c:'4',v:'15',texto:"Vi todos os viventes andarem debaixo do sol com o jovem, o sucessor, que ficará em seu lugar." },
{name:'21416',l:'21',c:'4',v:'16',texto:"Não tem fim todo o povo, todo o que ele domina; tampouco os descendentes se alegrarão dele. Na verdade que também isso é vaidade e aflição de espírito." },
],
numVersiculos: 16,
},

c5: {
versiculos:[
{name:'2151',l:'21',c:'5',v:'1',texto:"Guarda o teu pé, quando entrares na Casa de Deus; e inclina-te mais a ouvir do que a oferecer sacrifícios de tolos, pois não sabem que fazem mal." },
{name:'2152',l:'21',c:'5',v:'2',texto:"Não te precipites com a tua boca, nem o teu coração se apresse a pronunciar palavra alguma diante de Deus; porque Deus está nos céus, e tu estás sobre a terra; pelo que sejam poucas as tuas palavras." },
{name:'2153',l:'21',c:'5',v:'3',texto:"Porque da muita ocupação vêm os sonhos, e a voz do tolo, da multidão das palavras." },
{name:'2154',l:'21',c:'5',v:'4',texto:"Quando a Deus fizeres algum voto, não tardes em cumpri-lo; porque não se agrada de tolos; o que votares, paga-o." },
{name:'2155',l:'21',c:'5',v:'5',texto:"Melhor é que não votes do que votes e não pagues." },
{name:'2156',l:'21',c:'5',v:'6',texto:"Não consintas que a tua boca faça pecar a tua carne, nem digas diante do anjo que foi erro; por que razão se iraria Deus contra a tua voz, de sorte que destruísse a obra das tuas mãos?" },
{name:'2157',l:'21',c:'5',v:'7',texto:"Porque, como na multidão dos sonhos há vaidades, assim também nas muitas palavras; mas tu, teme a Deus." },
{name:'2158',l:'21',c:'5',v:'8',texto:"Se vires em alguma província opressão de pobres e a violência em lugar do juízo e da justiça, não te maravilhes de semelhante caso; porque o que mais alto é do que os altos para isso atenta; e há mais altos do que eles." },
{name:'2159',l:'21',c:'5',v:'9',texto:"O proveito da terra é para todos; até o rei se serve do campo." },
{name:'21510',l:'21',c:'5',v:'10',texto:"O que amar o dinheiro nunca se fartará de dinheiro; e quem amar a abundância nunca se fartará da renda; também isso é vaidade." },
{name:'21511',l:'21',c:'5',v:'11',texto:"Onde a fazenda se multiplica, aí se multiplicam também os que a comem; que mais proveito, pois, têm os seus donos do que a verem com os seus olhos?" },
{name:'21512',l:'21',c:'5',v:'12',texto:"Doce é o sono do trabalhador, quer coma pouco quer muito; mas a fartura do rico não o deixa dormir." },
{name:'21513',l:'21',c:'5',v:'13',texto:"Há mal que vi debaixo do sol e atrai enfermidades: as riquezas que os seus donos guardam para o próprio dano." },
{name:'21514',l:'21',c:'5',v:'14',texto:"Porque as mesmas riquezas se perdem por qualquer má aventura; e, havendo algum filho, nada fica na sua mão." },
{name:'21515',l:'21',c:'5',v:'15',texto:"Como saiu do ventre de sua mãe, assim nu voltará, indo-se como veio; e nada tomará do seu trabalho, que possa levar na sua mão." },
{name:'21516',l:'21',c:'5',v:'16',texto:"Também isto é um mal que causa enfermidades: que, infalivelmente, como veio, assim ele vai; e que proveito lhe vem de trabalhar para o vento," },
{name:'21517',l:'21',c:'5',v:'17',texto:"e de haver comido todos os seus dias nas trevas, e de haver padecido muito enfado, e enfermidades, e cruel furor?" },
{name:'21518',l:'21',c:'5',v:'18',texto:"Eis aqui o que eu vi, uma boa e bela coisa: comer, e beber, e gozar cada um do bem de todo o seu trabalho, em que trabalhou debaixo do sol, todos os dias da sua vida que Deus lhe deu; porque esta é a sua porção." },
{name:'21519',l:'21',c:'5',v:'19',texto:"E quanto ao homem, a quem Deus deu riquezas e fazenda e lhe deu poder para delas comer, e tomar a sua porção, e gozar do seu trabalho, isso é dom de Deus." },
{name:'21520',l:'21',c:'5',v:'20',texto:"Porque não se lembrará muito dos dias da sua vida; porquanto Deus lhe responde na alegria do seu coração." },
],
numVersiculos: 20,
},

c6: {
versiculos:[
{name:'2161',l:'21',c:'6',v:'1',texto:"Há um mal que tenho visto debaixo do sol e que mui freqüente é entre os homens:" },
{name:'2162',l:'21',c:'6',v:'2',texto:"um homem a quem Deus deu riquezas, fazenda e honra, e nada lhe falta de tudo quanto a sua alma deseja, mas Deus não lhe dá poder para daí comer; antes, o estranho lho come; também isso é vaidade e má enfermidade." },
{name:'2163',l:'21',c:'6',v:'3',texto:"Se o homem gerar cem filhos e viver muitos anos, e os dias dos seus anos forem muitos, e se a sua alma se não fartar do bem, e além disso não tiver um enterro, digo que um aborto é melhor do que ele," },
{name:'2164',l:'21',c:'6',v:'4',texto:"porquanto debalde veio e em trevas se vai, e de trevas se cobre o seu nome." },
{name:'2165',l:'21',c:'6',v:'5',texto:"E, ainda que nunca viu o sol, nem o conheceu, mais descanso tem do que o tal." },
{name:'2166',l:'21',c:'6',v:'6',texto:"E certamente, ainda que vivesse duas vezes mil anos, mas não gozasse o bem, não vão todos para um mesmo lugar?" },
{name:'2167',l:'21',c:'6',v:'7',texto:"Todo trabalho do homem é para a sua boca, e, contudo, nunca se satisfaz a sua cobiça." },
{name:'2168',l:'21',c:'6',v:'8',texto:"Porque, que mais tem o sábio do que o tolo? E que mais tem o pobre que sabe andar perante os vivos?" },
{name:'2169',l:'21',c:'6',v:'9',texto:"Melhor é a vista dos olhos do que o vaguear da cobiça; também isso é vaidade e aflição de espírito." },
{name:'21610',l:'21',c:'6',v:'10',texto:"Seja qualquer o que for, já o seu nome foi nomeado, e sabe-se que é homem e que não pode contender com o que é mais forte do que ele." },
{name:'21611',l:'21',c:'6',v:'11',texto:"Sendo certo que há muitas coisas que aumentam a vaidade, que mais tem o homem de melhor?" },
{name:'21612',l:'21',c:'6',v:'12',texto:"Porque, quem sabe o que é bom nesta vida para o homem, por todos os dias da sua vaidade, os quais gasta como sombra? Porque, quem declarará ao homem o que será depois dele debaixo do sol?" },
],
numVersiculos: 12,
},

c7: {
versiculos:[
{name:'2171',l:'21',c:'7',v:'1',texto:"Melhor é a boa fama do que o melhor ungüento, e o dia da morte, do que o dia do nascimento de alguém." },
{name:'2172',l:'21',c:'7',v:'2',texto:"Melhor é ir à casa onde há luto do que ir à casa onde há banquete, porque ali se vê o fim de todos os homens; e os vivos o aplicam ao seu coração." },
{name:'2173',l:'21',c:'7',v:'3',texto:"Melhor é a tristeza do que o riso, porque com a tristeza do rosto se faz melhor o coração." },
{name:'2174',l:'21',c:'7',v:'4',texto:"O coração dos sábios está na casa do luto, mas o coração dos tolos, na casa da alegria." },
{name:'2175',l:'21',c:'7',v:'5',texto:"Melhor é ouvir a repreensão do sábio do que ouvir alguém a canção do tolo." },
{name:'2176',l:'21',c:'7',v:'6',texto:"Porque qual o crepitar dos espinhos debaixo de uma panela, tal é o riso do tolo; também isso é vaidade." },
{name:'2177',l:'21',c:'7',v:'7',texto:"Verdadeiramente a opressão faz endoidecer até o sábio, e o suborno corrompe o coração." },
{name:'2178',l:'21',c:'7',v:'8',texto:"Melhor é o fim das coisas do que o princípio delas; melhor é o longânimo do que o altivo de coração." },
{name:'2179',l:'21',c:'7',v:'9',texto:"Não te apresses no teu espírito a irar-te, porque a ira abriga-se no seio dos tolos." },
{name:'21710',l:'21',c:'7',v:'10',texto:"Nunca digas: Por que foram os dias passados melhores do que estes? Porque nunca com sabedoria isso perguntarias." },
{name:'21711',l:'21',c:'7',v:'11',texto:"Tão boa é a sabedoria como a herança, e dela tiram proveito os que vêem o sol." },
{name:'21712',l:'21',c:'7',v:'12',texto:"Porque a sabedoria serve de sombra, como de sombra serve o dinheiro; mas a excelência da sabedoria é que ela dá vida ao seu possuidor." },
{name:'21713',l:'21',c:'7',v:'13',texto:"Atenta para a obra de Deus; porque quem poderá endireitar o que ele fez torto?" },
{name:'21714',l:'21',c:'7',v:'14',texto:"No dia da prosperidade, goza do bem, mas, no dia da adversidade, considera; porque também Deus fez este em oposição àquele, para que o homem nada ache que tenha de vir depois dele." },
{name:'21715',l:'21',c:'7',v:'15',texto:"Tudo isso vi nos dias da minha vaidade; há um justo que perece na sua justiça, e há um ímpio que prolonga os seus dias na sua maldade." },
{name:'21716',l:'21',c:'7',v:'16',texto:"Não sejas demasiadamente justo, nem demasiadamente sábio; por que te destruirias a ti mesmo?" },
{name:'21717',l:'21',c:'7',v:'17',texto:"Não sejas demasiadamente ímpio, nem sejas louco; por que morrerias fora de teu tempo?" },
{name:'21718',l:'21',c:'7',v:'18',texto:"Bom é que retenhas isso e também disso não retires a tua mão; porque quem teme a Deus escapa de tudo isso." },
{name:'21719',l:'21',c:'7',v:'19',texto:"A sabedoria fortalece o sábio, mais do que dez governadores que haja na cidade." },
{name:'21720',l:'21',c:'7',v:'20',texto:"Na verdade, não há homem justo sobre a terra, que faça bem e nunca peque." },
{name:'21721',l:'21',c:'7',v:'21',texto:"Tampouco apliques o teu coração a todas as palavras que se disserem, para que não venhas a ouvir que o teu servo te amaldiçoa." },
{name:'21722',l:'21',c:'7',v:'22',texto:"Porque o teu coração também já confessou muitas vezes que tu amaldiçoaste a outros." },
{name:'21723',l:'21',c:'7',v:'23',texto:"Tudo isso inquiri com sabedoria e disse: Sabedoria adquirirei; mas ela ainda estava longe de mim." },
{name:'21724',l:'21',c:'7',v:'24',texto:"Longe está o que foi e profundíssimo; quem o achará?" },
{name:'21725',l:'21',c:'7',v:'25',texto:"Eu tornei a voltar-me e determinei em meu coração saber, e inquirir, e buscar a sabedoria e a razão, e conhecer a loucura da impiedade e a doidice dos desvarios." },
{name:'21726',l:'21',c:'7',v:'26',texto:"E eu achei uma coisa mais amarga do que a morte: a mulher cujo coração são redes e laços e cujas mãos são ataduras; quem for bom diante de Deus escapará dela, mas o pecador virá a ser preso por ela." },
{name:'21727',l:'21',c:'7',v:'27',texto:"Vedes aqui, isso achei, diz o Pregador, conferindo uma coisa com a outra para achar a causa," },
{name:'21728',l:'21',c:'7',v:'28',texto:"causa que a minha alma ainda busca, mas não a achei; um homem entre mil achei eu, mas uma mulher entre todas estas não achei." },
{name:'21729',l:'21',c:'7',v:'29',texto:"Vede, isto tão-somente achei: que Deus fez ao homem reto, mas ele buscou muitas invenções." },
],
numVersiculos: 29,
},

c8: {
versiculos:[
{name:'2181',l:'21',c:'8',v:'1',texto:"Quem é como o sábio? E quem sabe a interpretação das coisas? A sabedoria do homem faz brilhar o seu rosto, e a dureza do seu rosto se muda." },
{name:'2182',l:'21',c:'8',v:'2',texto:"Eu digo: observa o mandamento do rei, e isso em consideração para com o juramento de Deus." },
{name:'2183',l:'21',c:'8',v:'3',texto:"Não te apresses a sair da presença dele, nem persistas em alguma coisa má, porque ele faz tudo o que quer." },
{name:'2184',l:'21',c:'8',v:'4',texto:"Porque a palavra do rei tem poder; e quem lhe dirá: Que fazes?" },
{name:'2185',l:'21',c:'8',v:'5',texto:"Quem guardar o mandamento não experimentará nenhum mal; e o coração do sábio discernirá o tempo e o modo." },
{name:'2186',l:'21',c:'8',v:'6',texto:"Porque para todo propósito há tempo e modo; porquanto o mal do homem é grande sobre ele." },
{name:'2187',l:'21',c:'8',v:'7',texto:"Porque não sabe o que há de suceder; e, como haja de suceder, quem lho dará a entender?" },
{name:'2188',l:'21',c:'8',v:'8',texto:"Nenhum homem há que tenha domínio sobre o espírito, para reter o espírito; nem tem poder sobre o dia da morte; nem há armas nessa peleja; nem tampouco a impiedade livrará aos ímpios." },
{name:'2189',l:'21',c:'8',v:'9',texto:"Tudo isso vi quando apliquei o meu coração a toda obra que se faz debaixo do sol; tempo há em que um homem tem domínio sobre outro homem, para desgraça sua." },
{name:'21810',l:'21',c:'8',v:'10',texto:"Assim também vi os ímpios sepultados, e eis que havia quem fosse à sua sepultura; e os que fizeram bem e saíam do lugar santo foram esquecidos na cidade; também isso é vaidade." },
{name:'21811',l:'21',c:'8',v:'11',texto:"Visto como se não executa logo o juízo sobre a má obra, por isso o coração dos filhos dos homens está inteiramente disposto para praticar o mal." },
{name:'21812',l:'21',c:'8',v:'12',texto:"Ainda que o pecador faça mal cem vezes, e os dias se lhe prolonguem, eu sei com certeza que bem sucede aos que temem a Deus, aos que temerem diante dele." },
{name:'21813',l:'21',c:'8',v:'13',texto:"Mas ao ímpio não irá bem, e ele não prolongará os seus dias; será como a sombra, visto que ele não teme diante de Deus." },
{name:'21814',l:'21',c:'8',v:'14',texto:"Ainda há outra vaidade que se faz sobre a terra: há justos a quem sucede segundo as obras dos ímpios, e há ímpios a quem sucede segundo as obras dos justos. Digo que também isso é vaidade." },
{name:'21815',l:'21',c:'8',v:'15',texto:"Então, exaltei eu a alegria, porquanto o homem nenhuma coisa melhor tem debaixo do sol do que comer, beber e alegrar-se; porque isso o acompanhará no seu trabalho nos dias da sua vida que Deus lhe dá debaixo do sol." },
{name:'21816',l:'21',c:'8',v:'16',texto:"Aplicando eu o meu coração a conhecer a sabedoria e a ver o trabalho que há sobre a terra ( pois nem de dia nem de noite vê o homem sono nos seus olhos )," },
{name:'21817',l:'21',c:'8',v:'17',texto:"então, vi toda a obra de Deus, que o homem não pode alcançar a obra que se faz debaixo do sol; por mais que trabalhe o homem para a buscar, não a achará; e, ainda que diga o sábio que a virá a conhecer, nem por isso a poderá alcançar." },
],
numVersiculos: 17,
},

c9: {
versiculos:[
{name:'2191',l:'21',c:'9',v:'1',texto:"Deveras revolvi todas essas coisas no meu coração, para claramente entender tudo isto: que os justos, e os sábios, e as suas obras estão nas mãos de Deus, e também que o homem não conhece nem o amor nem o ódio; tudo passa perante a sua face." },
{name:'2192',l:'21',c:'9',v:'2',texto:"Tudo sucede igualmente a todos: o mesmo sucede ao justo e ao ímpio, ao bom e ao puro, como ao impuro; assim ao que sacrifica como ao que não sacrifica; assim ao bom como ao pecador; ao que jura como ao que teme o juramento." },
{name:'2193',l:'21',c:'9',v:'3',texto:"Este é o mal que há entre tudo quanto se faz debaixo do sol: que a todos sucede o mesmo; que também o coração dos filhos dos homens está cheio de maldade; que há desvarios no seu coração, na sua vida, e que depois se vão aos mortos." },
{name:'2194',l:'21',c:'9',v:'4',texto:"Ora, para o que acompanha com todos os vivos há esperança ( porque melhor é o cão vivo do que o leão morto )." },
{name:'2195',l:'21',c:'9',v:'5',texto:"Porque os vivos sabem que hão de morrer, mas os mortos não sabem coisa nenhuma, nem tampouco eles têm jamais recompensa, mas a sua memória ficou entregue ao esquecimento." },
{name:'2196',l:'21',c:'9',v:'6',texto:"Até o seu amor, o seu ódio e a sua inveja já pereceram e já não têm parte alguma neste século, em coisa alguma do que se faz debaixo do sol." },
{name:'2197',l:'21',c:'9',v:'7',texto:"Vai, pois, come com alegria o teu pão e bebe com bom coração o teu vinho, pois já Deus se agrada das tuas obras." },
{name:'2198',l:'21',c:'9',v:'8',texto:"Em todo tempo sejam alvas as tuas vestes, e nunca falte o óleo sobre a tua cabeça." },
{name:'2199',l:'21',c:'9',v:'9',texto:"Goza a vida com a mulher que amas, todos os dias de vida da tua vaidade; os quais Deus te deu debaixo do sol, todos os dias da tua vaidade; porque esta é a tua porção nesta vida e do teu trabalho que tu fizeste debaixo do sol." },
{name:'21910',l:'21',c:'9',v:'10',texto:"Tudo quanto te vier à mão para fazer, faze-o conforme as tuas forças, porque na sepultura, para onde tu vais, não há obra, nem indústria, nem ciência, nem sabedoria alguma." },
{name:'21911',l:'21',c:'9',v:'11',texto:"Voltei-me e vi debaixo do sol que não é dos ligeiros a carreira, nem dos valentes, a peleja, nem tampouco dos sábios, o pão, nem ainda dos prudentes, a riqueza, nem dos inteligentes o favor, mas que o tempo e a sorte pertencem a todos." },
{name:'21912',l:'21',c:'9',v:'12',texto:"Que também o homem não conhece o seu tempo; como os peixes que se pescam com a rede maligna e como os passarinhos que se prendem com o laço, assim se enlaçam também os filhos dos homens no mau tempo, quando cai de repente sobre eles." },
{name:'21913',l:'21',c:'9',v:'13',texto:"Também vi sabedoria debaixo do sol, que foi para mim grande." },
{name:'21914',l:'21',c:'9',v:'14',texto:"Houve uma pequena cidade em que havia poucos homens, e veio contra ela um grande rei, e a cercou, e levantou contra ela grandes tranqueiras." },
{name:'21915',l:'21',c:'9',v:'15',texto:"E vivia nela um sábio pobre, que livrou aquela cidade pela sua sabedoria, e ninguém se lembrava daquele pobre homem." },
{name:'21916',l:'21',c:'9',v:'16',texto:"Então, disse eu: Melhor é a sabedoria do que a força, ainda que a sabedoria do pobre foi desprezada e as suas palavras não foram ouvidas." },
{name:'21917',l:'21',c:'9',v:'17',texto:"As palavras dos sábios devem em silêncio ser ouvidas, mais do que o clamor do que domina sobre os tolos." },
{name:'21918',l:'21',c:'9',v:'18',texto:"Melhor é a sabedoria do que as armas de guerra, mas um só pecador destrói muitos bens." },
],
numVersiculos: 18,
},

c10: {
versiculos:[
{name:'21101',l:'21',c:'10',v:'1',texto:"Assim como a mosca morta faz exalar mau cheiro e inutilizar o ungüento do perfumador, assim é para o famoso em sabedoria e em honra um pouco de estultícia." },
{name:'21102',l:'21',c:'10',v:'2',texto:"O coração do sábio está à sua mão direita, mas o coração do tolo está à sua esquerda." },
{name:'21103',l:'21',c:'10',v:'3',texto:"E, até quando o tolo vai pelo caminho, lhe falta entendimento, e diz a todos que é tolo." },
{name:'21104',l:'21',c:'10',v:'4',texto:"Levantando-se contra ti o espírito do governador, não deixes o teu lugar, porque o acordo é um remédio que aquieta grandes pecados." },
{name:'21105',l:'21',c:'10',v:'5',texto:"Ainda há um mal que vi debaixo do sol, como o erro que procede do governador:" },
{name:'21106',l:'21',c:'10',v:'6',texto:"o tolo, assentam-no em grandes alturas, mas os ricos estão assentados em lugar baixo." },
{name:'21107',l:'21',c:'10',v:'7',texto:"Vi servos a cavalo e príncipes que andavam a pé como servos sobre a terra." },
{name:'21108',l:'21',c:'10',v:'8',texto:"Quem fizer uma cova cairá nela, e quem romper um muro, uma cobra o morderá." },
{name:'21109',l:'21',c:'10',v:'9',texto:"Quem acarretar pedras será maltratado por elas, e o que rachar lenha expõe-se ao perigo." },
{name:'211010',l:'21',c:'10',v:'10',texto:"Se estiver embotado o ferro, e não se afiar o corte, então, se deve pôr mais forças; mas a sabedoria é excelente para dirigir." },
{name:'211011',l:'21',c:'10',v:'11',texto:"Se a cobra morder antes de estar encantada, então, remédio nenhum haverá no mais hábil encantador." },
{name:'211012',l:'21',c:'10',v:'12',texto:"Nas palavras da boca do sábio, há favor, mas os lábios do tolo o devoram." },
{name:'211013',l:'21',c:'10',v:'13',texto:"O princípio das palavras da sua boca é a estultícia, e o fim da sua boca, um desvario péssimo." },
{name:'211014',l:'21',c:'10',v:'14',texto:"Bem que o tolo multiplique as palavras, não sabe o homem o que será; e quem lhe fará saber o que será depois dele?" },
{name:'211015',l:'21',c:'10',v:'15',texto:"O trabalho dos tolos a cada um deles fatiga, pois não sabem como ir à cidade." },
{name:'211016',l:'21',c:'10',v:'16',texto:"Ai de ti, ó terra, cujo rei é criança e cujos príncipes comem de manhã." },
{name:'211017',l:'21',c:'10',v:'17',texto:"Bem-aventurada, tu, ó terra cujo rei é filho dos nobres e cujos príncipes comem a tempo, para refazerem as forças e não para bebedice." },
{name:'211018',l:'21',c:'10',v:'18',texto:"Pela muita preguiça se enfraquece o teto, e pela frouxidão das mãos goteja a casa." },
{name:'211019',l:'21',c:'10',v:'19',texto:"Para rir se fazem convites, e o vinho alegra a vida, e por tudo o dinheiro responde." },
{name:'211020',l:'21',c:'10',v:'20',texto:"Nem ainda no teu pensamento amaldiçoes o rei, nem tampouco no mais interior da tua recâmara amaldiçoes o rico; porque as aves dos céus levariam a voz e o que tem asas daria notícia da palavra." },
],
numVersiculos: 20,
},

c11: {
versiculos:[
{name:'21111',l:'21',c:'11',v:'1',texto:"Lança o teu pão sobre as águas, porque, depois de muitos dias, o acharás." },
{name:'21112',l:'21',c:'11',v:'2',texto:"Reparte com sete e ainda até com oito, porque não sabes que mal haverá sobre a terra." },
{name:'21113',l:'21',c:'11',v:'3',texto:"Estando as nuvens cheias, derramam a chuva sobre a terra, e, caindo a árvore para o sul ou para o norte, no lugar em que a árvore cair, ali ficará." },
{name:'21114',l:'21',c:'11',v:'4',texto:"Quem observa o vento nunca semeará, e o que olha para as nuvens nunca segará." },
{name:'21115',l:'21',c:'11',v:'5',texto:"Assim como tu não sabes qual o caminho do vento, nem como se formam os ossos no ventre da que está grávida, assim também não sabes as obras de Deus, que faz todas as coisas." },
{name:'21116',l:'21',c:'11',v:'6',texto:"Pela manhã, semeia a tua semente e, à tarde, não retires a tua mão, porque tu não sabes qual prosperará; se esta, se aquela ou se ambas igualmente serão boas." },
{name:'21117',l:'21',c:'11',v:'7',texto:"Verdadeiramente suave é a luz, e agradável é aos olhos ver o sol." },
{name:'21118',l:'21',c:'11',v:'8',texto:"Mas, se o homem viver muitos anos e em todos eles se alegrar, também se deve lembrar dos dias das trevas, porque hão de ser muitos. Tudo quanto sucede é vaidade." },
{name:'21119',l:'21',c:'11',v:'9',texto:"Alegra-te, jovem, na tua mocidade, e alegre-se o teu coração nos dias da tua mocidade, e anda pelos caminhos do teu coração e pela vista dos teus olhos; sabe, porém, que por todas essas coisas te trará Deus a juízo." },
{name:'211110',l:'21',c:'11',v:'10',texto:"Afasta, pois, a ira do teu coração e remove da tua carne o mal, porque a adolescência e a juventude são vaidade." },
],
numVersiculos: 10,
},

c12: {
versiculos:[
{name:'21121',l:'21',c:'12',v:'1',texto:"Lembra-te do teu Criador nos dias da tua mocidade, antes que venham os maus dias, e cheguem os anos dos quais venhas a dizer: Não tenho neles contentamento;" },
{name:'21122',l:'21',c:'12',v:'2',texto:"antes que se escureçam o sol, e a luz, e a lua, e as estrelas, e tornem a vir as nuvens depois da chuva;" },
{name:'21123',l:'21',c:'12',v:'3',texto:"no dia em que tremerem os guardas da casa, e se curvarem os homens fortes, e cessarem os moedores, por já serem poucos, e se escurecerem os que olham pelas janelas;" },
{name:'21124',l:'21',c:'12',v:'4',texto:"e as duas portas da rua se fecharem por causa do baixo ruído da moedura, e se levantar à voz das aves, e todas as vozes do canto se baixarem;" },
{name:'21125',l:'21',c:'12',v:'5',texto:"como também quando temerem o que está no alto, e houver espantos no caminho, e florescer a amendoeira, e o gafanhoto for um peso, e perecer o apetite; porque o homem se vai à sua eterna casa, e os pranteadores andarão rodeando pela praça;" },
{name:'21126',l:'21',c:'12',v:'6',texto:"antes que se quebre a cadeia de prata, e se despedace o copo de ouro, e se despedace o cântaro junto à fonte, e se despedace a roda junto ao poço," },
{name:'21127',l:'21',c:'12',v:'7',texto:"e o pó volte à terra, como o era, e o espírito volte a Deus, que o deu." },
{name:'21128',l:'21',c:'12',v:'8',texto:"Vaidade de vaidade, diz o Pregador, tudo é vaidade." },
{name:'21129',l:'21',c:'12',v:'9',texto:"E, quanto mais sábio foi o Pregador, tanto mais sabedoria ao povo ensinou; e atentou, e esquadrinhou, e compôs muitos provérbios." },
{name:'211210',l:'21',c:'12',v:'10',texto:"Procurou o Pregador achar palavras agradáveis; e o escrito é a retidão, palavras de verdade." },
{name:'211211',l:'21',c:'12',v:'11',texto:"As palavras dos sábios são como aguilhões e como pregos bem fixados pelos mestres das congregações, que nos foram dadas pelo único Pastor." },
{name:'211212',l:'21',c:'12',v:'12',texto:"E, de mais disso, filho meu, atenta: não há limite para fazer livros, e o muito estudar enfado é da carne." },
{name:'211213',l:'21',c:'12',v:'13',texto:"De tudo o que se tem ouvido, o fim é: Teme a Deus e guarda os seus mandamentos; porque este é o dever de todo homem." },
{name:'211214',l:'21',c:'12',v:'14',texto:"Porque Deus há de trazer a juízo toda obra e até tudo o que está encoberto, quer seja bom, quer seja mau." },
],
numVersiculos: 14,
},
	

};
