BibliaJFA.lamentaciones = {
	libro: "Lamentações",
	numCapitulos: 5,

c1: {
versiculos:[
{name:'2511',l:'25',c:'1',v:'1',texto:"Como se acha solitária aquela cidade dantes tão populosa! Tornou-se como viúva a que foi grande entre as nações; e princesa entre as províncias tornou-se tributária!" },
{name:'2512',l:'25',c:'1',v:'2',texto:"Continuamente chora de noite, e as suas lágrimas correm pelas suas faces; não tem quem a console entre todos os seus amadores; todos os seus amigos se houveram aleivosamente com ela, tornaram-se seus inimigos." },
{name:'2513',l:'25',c:'1',v:'3',texto:"Judá passou ao cativeiro por causa da aflição e por causa da grandeza da sua servidão; habita entre as nações, não acha descanso; todos os seus perseguidores a surpreenderam nas suas angústias." },
{name:'2514',l:'25',c:'1',v:'4',texto:"Os caminhos de Sião pranteiam, porque não há quem venha à reunião solene; todas as suas portas estão desoladas; os seus sacerdotes suspiram; as suas virgens estão tristes, e ela mesma tem amargura." },
{name:'2515',l:'25',c:'1',v:'5',texto:"Os seus adversários a dominaram, os seus inimigos prosperam; porque o SENHOR a entristeceu, por causa da multidão das suas prevaricações; os seus filhinhos vão em cativeiro na frente do adversário." },
{name:'2516',l:'25',c:'1',v:'6',texto:"E da filha de Sião foi-se toda a sua glória; os seus príncipes ficaram sendo como corços que não acham pasto e caminham sem força na frente do perseguidor." },
{name:'2517',l:'25',c:'1',v:'7',texto:"Lembra-se Jerusalém, nos dias da sua aflição e das suas rebeliões, de todas as suas mais queridas coisas, que tivera dos tempos antigos; quando caía o seu povo na mão do adversário, e ela não tinha quem a socorresse, os adversários a viram e fizeram escárnio da sua queda." },
{name:'2518',l:'25',c:'1',v:'8',texto:"Jerusalém gravemente pecou; por isso, se fez instável; todos os que a honravam a desprezaram, porque viram a sua nudez; ela também suspirou e voltou para trás." },
{name:'2519',l:'25',c:'1',v:'9',texto:"A sua imundícia está nas suas saias, nunca se lembrou do seu fim; por isso, foi pasmosamente abatida, não tem consolador. Vê, SENHOR, a minha aflição, porque o inimigo se engrandece." },
{name:'25110',l:'25',c:'1',v:'10',texto:"Estendeu o adversário a sua mão a todas as coisas mais preciosas dela; pois viu entrar no seu santuário as nações acerca das quais mandaste que não entrassem na tua congregação." },
{name:'25111',l:'25',c:'1',v:'11',texto:"Todo o seu povo anda suspirando, buscando o pão; deram as suas coisas mais preciosas a troco de mantimento para refrescarem a alma; vê, SENHOR, e contempla, pois me tornei desprezível." },
{name:'25112',l:'25',c:'1',v:'12',texto:"Não vos comove isso, a todos vós que passais pelo caminho? Atendei e vede se há dor como a minha dor, que veio sobre mim, com que me entristeceu o SENHOR, no dia do furor da sua ira." },
{name:'25113',l:'25',c:'1',v:'13',texto:"Desde o alto enviou fogo a meus ossos, o qual se assenhoreou deles; estendeu uma rede aos meus pés, fez-me voltar para trás, fez-me assolada e enferma todo o dia." },
{name:'25114',l:'25',c:'1',v:'14',texto:"Já o jugo das minhas prevaricações está atado pela sua mão; elas estão entretecidas, subiram sobre o meu pescoço, e ele abateu a minha força; entregou-me o Senhor na suas mãos, e eu não posso levantar-me." },
{name:'25115',l:'25',c:'1',v:'15',texto:"O Senhor atropelou todos os meus valentes no meio de mim; apregoou contra mim um ajuntamento, para quebrantar os meus jovens; o Senhor pisou, como em um lagar, a virgem filha de Judá." },
{name:'25116',l:'25',c:'1',v:'16',texto:"Por essas coisas, choro eu; os meus olhos, os meus olhos se desfazem em águas; porque se afastou de mim o consolador que devia restaurar a minha alma; os meus filhos estão desolados, porque prevaleceu o inimigo." },
{name:'25117',l:'25',c:'1',v:'17',texto:"Estende Sião as suas mãos, não há quem a console; mandou o SENHOR acerca de Jacó que fossem inimigos os que estão em redor dele; Jerusalém é para eles como uma coisa imunda." },
{name:'25118',l:'25',c:'1',v:'18',texto:"Justo é o SENHOR, pois me rebelei contra os seus mandamentos; ouvi, pois, todos os povos e vede a minha dor; as minhas virgens e os meus jovens se foram para o cativeiro." },
{name:'25119',l:'25',c:'1',v:'19',texto:"Chamei os meus amadores, mas eles me enganaram; os meus sacerdotes e os meus anciãos expiraram na cidade, enquanto buscavam para si mantimento, para refrescarem a sua alma." },
{name:'25120',l:'25',c:'1',v:'20',texto:"Olha, SENHOR, quanto estou angustiada; turbada está a minha alma, o meu coração está transtornado no meio de mim, porque gravemente me rebelei; fora, me desfilhou a espada, dentro de mim está a morte." },
{name:'25121',l:'25',c:'1',v:'21',texto:"Ouvem que eu suspiro, mas não tenho quem me console; todos os meus inimigos que souberam do meu mal folgam, porque tu o determinaste; mas, em trazendo tu o dia que apregoaste, serão como eu." },
{name:'25122',l:'25',c:'1',v:'22',texto:"Venha toda a sua iniqüidade à tua presença, e faze-lhes como me fizeste a mim por causa de todas as minhas prevaricações; porque os meus suspiros são muitos, e o meu coração está desfalecido." },
],
numVersiculos: 22,
},

c2: {
versiculos:[
{name:'2521',l:'25',c:'2',v:'1',texto:"Como cobriu o Senhor de nuvens, na sua ira, a filha de Sião! Derribou do céu à terra a glória de Israel e não se lembrou do escabelo de seus pés, no dia da sua ira." },
{name:'2522',l:'25',c:'2',v:'2',texto:"Devorou o Senhor todas as moradas de Jacó e não se apiedou; derribou no seu furor as fortalezas da filha de Judá e as abateu até à terra; profanou o reino e os seus príncipes." },
{name:'2523',l:'25',c:'2',v:'3',texto:"Cortou, no furor da sua ira, toda a força de Israel; retirou para trás a sua destra de diante do inimigo; e ardeu contra Jacó, como labareda de fogo que tudo consome em redor." },
{name:'2524',l:'25',c:'2',v:'4',texto:"Armou o seu arco como inimigo, firmou a sua destra como adversário e matou tudo o que era formoso à vista; derramou a sua indignação, como fogo na tenda da filha de Sião." },
{name:'2525',l:'25',c:'2',v:'5',texto:"Tornou-se o Senhor como inimigo; devorou Israel, devorou todos os seus palácios, destruiu as suas fortalezas; e multiplicou na filha de Judá a lamentação e a tristeza." },
{name:'2526',l:'25',c:'2',v:'6',texto:"E arrancou a sua cabana com violência, como se fosse a de uma horta; destruiu a sua congregação; o SENHOR, em Sião, pôs em esquecimento a solenidade e o sábado e, na indignação da sua ira, rejeitou com desprezo o rei e o sacerdote." },
{name:'2527',l:'25',c:'2',v:'7',texto:"Rejeitou o Senhor o seu altar, detestou o seu santuário; entregou na mão do inimigo os muros dos seus palácios; deram gritos na Casa do SENHOR, como em dia de reunião solene." },
{name:'2528',l:'25',c:'2',v:'8',texto:"Intentou o SENHOR destruir o muro da filha de Sião; estendeu o cordel, não retirou a sua mão destruidora; fez gemer o antemuro e o muro; eles estão juntamente enfraquecidos." },
{name:'2529',l:'25',c:'2',v:'9',texto:"Abateram as suas portas; ele destruiu e quebrou os seus ferrolhos; o seu rei e os seus príncipes estão entre as nações onde não há lei, nem acham visão alguma do SENHOR os seus profetas." },
{name:'25210',l:'25',c:'2',v:'10',texto:"Estão sentados na terra, silenciosos, os anciãos da filha de Sião; lançam pó sobre a sua cabeça, cingiram panos de saco; as virgens de Jerusalém abaixam a sua cabeça até à terra." },
{name:'25211',l:'25',c:'2',v:'11',texto:"Já se consumiram os meus olhos com lágrimas, turbada está a minha alma, o meu coração se derramou pela terra, por causa do quebrantamento da filha do meu povo; pois desfalecem os meninos e as crianças de peito pelas ruas da cidade." },
{name:'25212',l:'25',c:'2',v:'12',texto:"Dizem a suas mães: Onde há trigo e vinho? Quando desfalecem como o ferido pelas ruas da cidade, derramando-se a sua alma no regaço de suas mães." },
{name:'25213',l:'25',c:'2',v:'13',texto:"Que testemunho te trarei? A quem te compararei, ó filha de Jerusalém? A quem te assemelharei, para te consolar a ti, ó virgem filha de Sião? Porque grande como o mar é a tua ferida; quem te sarará?" },
{name:'25214',l:'25',c:'2',v:'14',texto:"Os teus profetas viram para ti vaidade e loucura e não manifestaram a tua maldade, para afastarem o teu cativeiro; mas viram para ti cargas vãs e motivos de expulsão." },
{name:'25215',l:'25',c:'2',v:'15',texto:"Todos os que passam pelo caminho batem palmas, assobiam e meneiam a cabeça sobre a filha de Jerusalém, dizendo: É esta a cidade que denominavam perfeita em formosura, gozo de toda a terra?" },
{name:'25216',l:'25',c:'2',v:'16',texto:"Todos os teus inimigos abrem a boca contra ti, assobiam e rangem os dentes; dizem: Devoramo-la; certamente este é o dia que esperávamos; achamo-lo e vimo-lo." },
{name:'25217',l:'25',c:'2',v:'17',texto:"Fez o SENHOR o que intentou; cumpriu a sua palavra, que ordenou desde os dias da antiguidade: derribou e não se apiedou; fez que o inimigo se alegrasse por tua causa, exaltou o poder dos teus adversários." },
{name:'25218',l:'25',c:'2',v:'18',texto:"O coração deles clamou ao Senhor: Ó muralha da filha de Sião, corram as tuas lágrimas como um ribeiro, de dia e de noite; não te dês descanso, nem parem as meninas de teus olhos." },
{name:'25219',l:'25',c:'2',v:'19',texto:"Levanta-te, clama de noite no princípio das vigílias; derrama o teu coração como águas diante da face do Senhor; levanta a ele as tuas mãos, pela vida de teus filhinhos, que desfalecem de fome à entrada de todas as ruas." },
{name:'25220',l:'25',c:'2',v:'20',texto:"Vê, ó SENHOR, e considera a quem fizeste assim! Hão de as mulheres comer o fruto de si mesmas, as crianças que trazem nos braços? Ou matar-se-á no santuário do Senhor o sacerdote e o profeta?" },
{name:'25221',l:'25',c:'2',v:'21',texto:"Jazem em terra pelas ruas o moço e o velho; as minhas virgens e os meus jovens vieram a cair à espada; tu os mataste no dia da tua ira; degolaste-os e não te apiedaste deles." },
{name:'25222',l:'25',c:'2',v:'22',texto:"Convocaste de toda parte os meus receios, como em um dia de solenidade; não houve no dia da ira do SENHOR quem escapasse ou ficasse; aqueles que trouxe nas mãos e sustentei, o meu inimigo os consumiu." },
],
numVersiculos: 22,
},

c3: {
versiculos:[
{name:'2531',l:'25',c:'3',v:'1',texto:"Eu sou o homem que viu a aflição pela vara do seu furor." },
{name:'2532',l:'25',c:'3',v:'2',texto:"Ele me levou e me fez andar em trevas e não na luz." },
{name:'2533',l:'25',c:'3',v:'3',texto:"Deveras se tornou contra mim; virou contra mim de contínuo, a mão todo o dia." },
{name:'2534',l:'25',c:'3',v:'4',texto:"Fez envelhecer a minha carne e a minha pele, quebrantou os meus ossos." },
{name:'2535',l:'25',c:'3',v:'5',texto:"Edificou contra mim e me cercou de fel e trabalho." },
{name:'2536',l:'25',c:'3',v:'6',texto:"Assentou-me em lugares tenebrosos, como os que estavam mortos há muito." },
{name:'2537',l:'25',c:'3',v:'7',texto:"Circunvalou-me, e não posso sair; agravou os meus grilhões." },
{name:'2538',l:'25',c:'3',v:'8',texto:"Ainda quando clamo e grito, ele exclui a minha oração." },
{name:'2539',l:'25',c:'3',v:'9',texto:"Circunvalou os meus caminhos com pedras lavradas, fez tortuosas as minhas veredas." },
{name:'25310',l:'25',c:'3',v:'10',texto:"Fez-me como urso de emboscada, um leão em esconderijos." },
{name:'25311',l:'25',c:'3',v:'11',texto:"Desviou os meus caminhos e fez-me em pedaços; deixou-me assolado." },
{name:'25312',l:'25',c:'3',v:'12',texto:"Armou o seu arco, e me pôs como alvo à flecha." },
{name:'25313',l:'25',c:'3',v:'13',texto:"Fez entrar nos meus rins as flechas da sua aljava." },
{name:'25314',l:'25',c:'3',v:'14',texto:"Fui feito um objeto de escárnio para todo o meu povo e a sua canção todo o dia." },
{name:'25315',l:'25',c:'3',v:'15',texto:"Fartou-me de amarguras, saciou-me de absinto." },
{name:'25316',l:'25',c:'3',v:'16',texto:"Quebrou com pedrinhas de areia os meus dentes; cobriu-me de cinza." },
{name:'25317',l:'25',c:'3',v:'17',texto:"E afastaste da paz a minha alma; esqueci-me do bem." },
{name:'25318',l:'25',c:'3',v:'18',texto:"Então, disse eu: Já pereceu a minha força, como também a minha esperança no SENHOR." },
{name:'25319',l:'25',c:'3',v:'19',texto:"Lembra-te da minha aflição e do meu pranto, do absinto e do fel." },
{name:'25320',l:'25',c:'3',v:'20',texto:"Minha alma, certamente, se lembra e se abate dentro de mim." },
{name:'25321',l:'25',c:'3',v:'21',texto:"Disso me recordarei no meu coração; por isso, tenho esperança." },
{name:'25322',l:'25',c:'3',v:'22',texto:"As misericórdias do SENHOR são a causa de não sermos consumidos; porque as suas misericórdias não têm fim." },
{name:'25323',l:'25',c:'3',v:'23',texto:"Novas são cada manhã; grande é a tua fidelidade." },
{name:'25324',l:'25',c:'3',v:'24',texto:"A minha porção é o SENHOR, diz a minha alma; portanto, esperarei nele." },
{name:'25325',l:'25',c:'3',v:'25',texto:"Bom é o SENHOR para os que se atêm a ele, para a alma que o busca." },
{name:'25326',l:'25',c:'3',v:'26',texto:"Bom é ter esperança e aguardar em silêncio a salvação do SENHOR." },
{name:'25327',l:'25',c:'3',v:'27',texto:"Bom é para o homem suportar o jugo na sua mocidade;" },
{name:'25328',l:'25',c:'3',v:'28',texto:"assentar-se solitário e ficar em silêncio; porquanto Deus o pôs sobre ele." },
{name:'25329',l:'25',c:'3',v:'29',texto:"Ponha a boca no pó; talvez assim haja esperança." },
{name:'25330',l:'25',c:'3',v:'30',texto:"Dê a face ao que o fere; farte-se de afronta." },
{name:'25331',l:'25',c:'3',v:'31',texto:"Porque o Senhor não rejeitará para sempre." },
{name:'25332',l:'25',c:'3',v:'32',texto:"Pois, ainda que entristeça a alguém, usará de compaixão segundo a grandeza das suas misericórdias." },
{name:'25333',l:'25',c:'3',v:'33',texto:"Porque não aflige nem entristece de bom grado os filhos dos homens." },
{name:'25334',l:'25',c:'3',v:'34',texto:"Pisar debaixo dos pés todos os presos da terra," },
{name:'25335',l:'25',c:'3',v:'35',texto:"perverter o direito do homem perante a face do Altíssimo," },
{name:'25336',l:'25',c:'3',v:'36',texto:"subverter o homem no seu pleito, não o veria o Senhor?" },
{name:'25337',l:'25',c:'3',v:'37',texto:"Quem é aquele que diz, e assim acontece, quando o Senhor o não mande?" },
{name:'25338',l:'25',c:'3',v:'38',texto:"Porventura da boca do Altíssimo não sai o mal e o bem?" },
{name:'25339',l:'25',c:'3',v:'39',texto:"De que se queixa, pois, o homem vivente? Queixe-se cada um dos seus pecados." },
{name:'25340',l:'25',c:'3',v:'40',texto:"Esquadrinhemos os nossos caminhos, experimentemo-los e voltemos para o SENHOR." },
{name:'25341',l:'25',c:'3',v:'41',texto:"Levantemos o coração juntamente com as mãos para Deus nos céus, dizendo:" },
{name:'25342',l:'25',c:'3',v:'42',texto:"Nós prevaricamos e fomos rebeldes; por isso, tu não perdoaste." },
{name:'25343',l:'25',c:'3',v:'43',texto:"Cobriste-nos de ira e nos perseguiste; mataste, não perdoaste." },
{name:'25344',l:'25',c:'3',v:'44',texto:"Cobriste-te de nuvens, para que não passe a nossa oração." },
{name:'25345',l:'25',c:'3',v:'45',texto:"Como cisco e rejeitamento, nos puseste no meio dos povos." },
{name:'25346',l:'25',c:'3',v:'46',texto:"Todos os nossos inimigos abriram contra nós a sua boca." },
{name:'25347',l:'25',c:'3',v:'47',texto:"Temor e cova vieram sobre nós, assolação e quebrantamento." },
{name:'25348',l:'25',c:'3',v:'48',texto:"Torrentes de águas derramaram os meus olhos, por causa da destruição da filha do meu povo." },
{name:'25349',l:'25',c:'3',v:'49',texto:"Os meus olhos choram e não cessam, porque não há descanso," },
{name:'25350',l:'25',c:'3',v:'50',texto:"até que o SENHOR atente e veja desde os céus." },
{name:'25351',l:'25',c:'3',v:'51',texto:"O meu olho move a minha alma, por causa de todas as filhas da minha cidade." },
{name:'25352',l:'25',c:'3',v:'52',texto:"Como ave, me caçaram os que são meus inimigos sem causa." },
{name:'25353',l:'25',c:'3',v:'53',texto:"Arrancaram a minha vida na cova e lançaram pedras sobre mim." },
{name:'25354',l:'25',c:'3',v:'54',texto:"Águas correram sobre a minha cabeça; eu disse: Estou cortado." },
{name:'25355',l:'25',c:'3',v:'55',texto:"Invoquei o teu nome, SENHOR, desde a mais profunda cova." },
{name:'25356',l:'25',c:'3',v:'56',texto:"Ouviste a minha voz; não escondas o teu ouvido ao meu suspiro, ao meu clamor." },
{name:'25357',l:'25',c:'3',v:'57',texto:"Tu te aproximaste no dia em que te invoquei; disseste: Não temas." },
{name:'25358',l:'25',c:'3',v:'58',texto:"Pleiteaste, Senhor, os pleitos da minha alma, remiste a minha vida." },
{name:'25359',l:'25',c:'3',v:'59',texto:"Viste, SENHOR, a injustiça que me fizeram; julga a minha causa." },
{name:'25360',l:'25',c:'3',v:'60',texto:"Viste toda a sua vingança, todos os seus pensamentos contra mim." },
{name:'25361',l:'25',c:'3',v:'61',texto:"Ouviste as suas afrontas, SENHOR, todos os seus pensamentos contra mim;" },
{name:'25362',l:'25',c:'3',v:'62',texto:"os lábios dos que se levantam contra mim e as suas imaginações contra mim todo o dia." },
{name:'25363',l:'25',c:'3',v:'63',texto:"Observa-os ao se assentarem e ao se levantarem; eu sou a sua canção." },
{name:'25364',l:'25',c:'3',v:'64',texto:"Tu lhes darás a recompensa, SENHOR, conforme a obra das suas mãos." },
{name:'25365',l:'25',c:'3',v:'65',texto:"Tu lhes darás ânsia de coração, maldição tua sobre eles." },
{name:'25366',l:'25',c:'3',v:'66',texto:"Na tua ira, os perseguirás, e eles serão desfeitos debaixo dos céus do SENHOR." },
],
numVersiculos: 66,
},

c4: {
versiculos:[
{name:'2541',l:'25',c:'4',v:'1',texto:"Como se escureceu o ouro! Como se mudou o ouro fino e bom! Como estão espalhadas as pedras do santuário ao canto de todas as ruas!" },
{name:'2542',l:'25',c:'4',v:'2',texto:"Os preciosos filhos de Sião, comparáveis a puro ouro, como são, agora, reputados por vasos de barro, obra das mãos do oleiro!" },
{name:'2543',l:'25',c:'4',v:'3',texto:"Até os chacais abaixam o peito, dão de mamar aos seus filhos; mas a filha do meu povo tornou-se cruel como os avestruzes no deserto." },
{name:'2544',l:'25',c:'4',v:'4',texto:"A língua do que mama fica pegada pela sede ao seu paladar; os meninos pedem pão, e ninguém lho dá." },
{name:'2545',l:'25',c:'4',v:'5',texto:"Os que comiam iguarias delicadas desfalecem nas ruas; os que se criaram em carmesim abraçam o esterco." },
{name:'2546',l:'25',c:'4',v:'6',texto:"Porque maior é a maldade da filha do meu povo do que o pecado de Sodoma, a qual se subverteu como em um momento, sem que trabalhassem nela mãos algumas." },
{name:'2547',l:'25',c:'4',v:'7',texto:"Os seus nazireus eram mais alvos do que a neve, eram mais brancos do que o leite, eram mais roxos de corpo do que os rubins, mais polidos do que a safira." },
{name:'2548',l:'25',c:'4',v:'8',texto:"Mas, agora, escureceu-se o seu parecer mais do que o negrume, não se conhecem nas ruas; a sua pele se lhes pegou aos ossos, secou-se, tornou-se como um pedaço de pau." },
{name:'2549',l:'25',c:'4',v:'9',texto:"Os mortos à espada mais ditosos são do que os mortos à fome; porque estes se esgotam como traspassados, por falta dos frutos dos campos." },
{name:'25410',l:'25',c:'4',v:'10',texto:"As mãos das mulheres piedosas cozeram seus próprios filhos; serviram-lhes de alimento na destruição da filha do meu povo." },
{name:'25411',l:'25',c:'4',v:'11',texto:"Deu o SENHOR cumprimento ao seu furor; derramou o ardor da sua ira e acendeu fogo em Sião, que consumiu os seus fundamentos." },
{name:'25412',l:'25',c:'4',v:'12',texto:"Não creram os reis da terra, nem todos os moradores do mundo, que entrasse o adversário e o inimigo pelas portas de Jerusalém." },
{name:'25413',l:'25',c:'4',v:'13',texto:"Foi por causa dos pecados dos profetas, das maldades dos seus sacerdotes, que derramaram o sangue dos justos no meio dela." },
{name:'25414',l:'25',c:'4',v:'14',texto:"Erram como cegos nas ruas, andam contaminados de sangue; de tal sorte que ninguém pode tocar nas suas roupas." },
{name:'25415',l:'25',c:'4',v:'15',texto:"Desviai-vos, bradavam eles. Imundo! Desviai-vos, desviai-vos, não toqueis; quando fugiram e erraram, disseram entre as nações: Nunca mais morarão aqui." },
{name:'25416',l:'25',c:'4',v:'16',texto:"A ira do SENHOR os dividiu; ele nunca mais tornará a olhar para eles; não reverenciaram a face dos sacerdotes, nem se compadeceram dos velhos." },
{name:'25417',l:'25',c:'4',v:'17',texto:"Os nossos olhos desfaleciam, esperando vão socorro; olhávamos atentamente para gente que não pode livrar." },
{name:'25418',l:'25',c:'4',v:'18',texto:"Espiaram os nossos passos, de maneira que não podíamos andar pelas nossas ruas; está chegando o nosso fim, estão cumpridos os nossos dias, porque é vindo o nosso fim." },
{name:'25419',l:'25',c:'4',v:'19',texto:"Os nossos perseguidores foram mais ligeiros do que as aves dos céus; sobre os montes nos perseguiram, no deserto nos armaram ciladas." },
{name:'25420',l:'25',c:'4',v:'20',texto:"O respiro das nossas narinas, o ungido do SENHOR, foi preso nas suas covas; dele dizíamos: Debaixo da sua sombra viveremos entre as nações." },
{name:'25421',l:'25',c:'4',v:'21',texto:"Regozija-te e alegra-te, ó filha de Edom, que habitas na terra de Uz; o cálice chegará também para ti; embebedar-te-ás e te descobrirás." },
{name:'25422',l:'25',c:'4',v:'22',texto:"O castigo da tua maldade está consumado, ó filha de Sião; ele nunca mais te levará para o cativeiro; ele visitará a tua maldade, ó filha de Edom, descobrirá os teus pecados." },
],
numVersiculos: 22,
},

c5: {
versiculos:[
{name:'2551',l:'25',c:'5',v:'1',texto:"Lembra-te, SENHOR, do que nos tem sucedido; considera e olha para o nosso opróbrio." },
{name:'2552',l:'25',c:'5',v:'2',texto:"A nossa herdade passou a estranhos, e as nossas casas, a forasteiros." },
{name:'2553',l:'25',c:'5',v:'3',texto:"Órfãos somos sem pai, nossas mães são como viúvas." },
{name:'2554',l:'25',c:'5',v:'4',texto:"A nossa água por dinheiro a bebemos, por preço vem a nossa lenha." },
{name:'2555',l:'25',c:'5',v:'5',texto:"Os nossos perseguidores estão sobre os nossos pescoços; estamos cansados e não temos descanso." },
{name:'2556',l:'25',c:'5',v:'6',texto:"Aos egípcios estendemos as mãos, e aos assírios, para nos fartarem de pão." },
{name:'2557',l:'25',c:'5',v:'7',texto:"Nossos pais pecaram e já não existem; nós levamos as suas maldades." },
{name:'2558',l:'25',c:'5',v:'8',texto:"Servos dominam sobre nós; ninguém há que nos arranque da sua mão." },
{name:'2559',l:'25',c:'5',v:'9',texto:"Com perigo de nossas vidas, trazemos o nosso pão, por causa da espada do deserto." },
{name:'25510',l:'25',c:'5',v:'10',texto:"Nossa pele se enegreceu como um forno, por causa do ardor da fome." },
{name:'25511',l:'25',c:'5',v:'11',texto:"Forçaram as mulheres em Sião; as virgens, nas cidades de Judá." },
{name:'25512',l:'25',c:'5',v:'12',texto:"Os príncipes foram enforcados pelas mãos deles; as faces dos velhos não foram reverenciadas." },
{name:'25513',l:'25',c:'5',v:'13',texto:"Aos jovens obrigam a moer, e os moços tropeçaram debaixo da lenha." },
{name:'25514',l:'25',c:'5',v:'14',texto:"Os velhos já não têm assento à porta, os jovens já não cantam." },
{name:'25515',l:'25',c:'5',v:'15',texto:"Cessou o gozo de nosso coração, converteu-se em lamentação a nossa dança." },
{name:'25516',l:'25',c:'5',v:'16',texto:"Caiu a coroa da nossa cabeça; ai de nós, porque pecamos." },
{name:'25517',l:'25',c:'5',v:'17',texto:"Por isso, desmaiou o nosso coração; por isso, se escureceram os nossos olhos." },
{name:'25518',l:'25',c:'5',v:'18',texto:"Pelo monte de Sião, que está assolado, andam as raposas." },
{name:'25519',l:'25',c:'5',v:'19',texto:"Tu, SENHOR, permaneces eternamente, e o teu trono, de geração em geração." },
{name:'25520',l:'25',c:'5',v:'20',texto:"Por que te esquecerias de nós para sempre? Por que nos desampararias por tanto tempo?" },
{name:'25521',l:'25',c:'5',v:'21',texto:"Converte-nos, SENHOR, a ti, e nós nos converteremos; renova os nossos dias como dantes." },
{name:'25522',l:'25',c:'5',v:'22',texto:"Por que nos rejeitarias totalmente? Por que te enfurecerias contra nós em tão grande maneira?" },
],
numVersiculos: 22,
},
	

};
