BibliaJFA.oseas = {
	libro: "Oseias",
	numCapitulos: 14,

c1: {
versiculos:[
{name:'2811',l:'28',c:'1',v:'1',texto:"Palavra do SENHOR que foi dita a Oséias, filho de Beeri, nos dias de Uzias, Jotão, Acaz, Ezequias, reis de Judá, e nos dias de Jeroboão, filho de Joás, rei de Israel." },
{name:'2812',l:'28',c:'1',v:'2',texto:"O princípio da palavra do SENHOR por Oséias; disse, pois, o SENHOR a Oséias: Vai, toma uma mulher de prostituições e filhos de prostituição; porque a terra se prostituiu, desviando-se do SENHOR." },
{name:'2813',l:'28',c:'1',v:'3',texto:"E foi-se e tomou a Gomer, filha de Diblaim, e ela concebeu e lhe deu um filho." },
{name:'2814',l:'28',c:'1',v:'4',texto:"E disse-lhe o SENHOR: Põe-lhe o nome de Jezreel; porque daqui a pouco visitarei o sangue de Jezreel sobre a casa de Jeú e farei cessar o reino da casa de Israel." },
{name:'2815',l:'28',c:'1',v:'5',texto:"E será, naquele dia, que quebrarei o arco de Israel no vale de Jezreel." },
{name:'2816',l:'28',c:'1',v:'6',texto:"E tornou ela a conceber e deu à luz uma filha; e ele disse: Põe-lhe o nome de Lo-Ruama; porque eu não me tornarei mais a compadecer da casa de Israel, mas tudo lhe tirarei." },
{name:'2817',l:'28',c:'1',v:'7',texto:"Mas da casa de Judá me compadecerei e os salvarei pelo SENHOR, seu Deus; pois não os salvarei pelo arco, nem pela espada, nem pela guerra, nem pelos cavalos, nem pelos cavaleiros." },
{name:'2818',l:'28',c:'1',v:'8',texto:"E, depois de haver desmamado a Lo-Ruama, concebeu e deu à luz um filho." },
{name:'2819',l:'28',c:'1',v:'9',texto:"E ele disse: Põe-lhe o nome de Lo-Ami, porque vós não sois meu povo, nem eu serei vosso Deus." },
{name:'28110',l:'28',c:'1',v:'10',texto:"Todavia, o número dos filhos de Israel será como a areia do mar, que não pode medir-se nem contar-se; e acontecerá que, no lugar onde se lhes dizia: Vós não sois meu povo, se lhes dirá: Vós sois filhos do Deus vivo." },
{name:'28111',l:'28',c:'1',v:'11',texto:"E os filhos de Judá e os filhos de Israel juntos se congregarão, e constituirão sobre si uma única cabeça, e subirão da terra; porque grande será o dia de Jezreel." },
],
numVersiculos: 11,
},

c2: {
versiculos:[
{name:'2821',l:'28',c:'2',v:'1',texto:"Dizei a vossos irmãos: Ami; e a vossas irmãs: Ruama." },
{name:'2822',l:'28',c:'2',v:'2',texto:"Contendei com vossa mãe, contendei, porque ela não é minha mulher, e eu não sou seu marido; e desvie ela as suas prostituições da sua face e os seus adultérios de entre os seus peitos." },
{name:'2823',l:'28',c:'2',v:'3',texto:"Para que eu não a deixe despida, e a ponha como no dia em que nasceu, e a faça como um deserto, e a ponha como uma terra seca, e a mate à sede," },
{name:'2824',l:'28',c:'2',v:'4',texto:"e não me compadeça de seus filhos, porque são filhos de prostituições." },
{name:'2825',l:'28',c:'2',v:'5',texto:"Porque sua mãe se prostituiu, aquela que os concebeu houve-se torpemente porque diz: Irei atrás de meus namorados, que me dão o meu pão e a minha água, a minha lã e o meu linho, o meu óleo e as minhas bebidas." },
{name:'2826',l:'28',c:'2',v:'6',texto:"Portanto, eis que cercarei o teu caminho com espinhos; e levantarei uma parede de sebe, para que ela não ache as suas veredas." },
{name:'2827',l:'28',c:'2',v:'7',texto:"E irá em seguimento de seus amantes, mas não os alcançará; e buscá-los-á, mas não os achará; então, dirá: Ir-me-ei e tornar-me-ei a meu primeiro marido, porque melhor me ia, então, do que agora." },
{name:'2828',l:'28',c:'2',v:'8',texto:"Ela, pois, não reconhece que eu lhe dei o grão, e o mosto, e o óleo e lhe multipliquei a prata e o ouro, que eles usaram para Baal." },
{name:'2829',l:'28',c:'2',v:'9',texto:"Portanto, tornar-me-ei e, a seu tempo, tirarei o meu grão e o meu mosto, no seu determinado tempo; e arrebatarei a minha lã e o meu linho, com que cobriam a sua nudez." },
{name:'28210',l:'28',c:'2',v:'10',texto:"E, agora, descobrirei a sua vileza diante dos olhos dos seus namorados, e ninguém a livrará da minha mão." },
{name:'28211',l:'28',c:'2',v:'11',texto:"E farei cessar todo o seu gozo, e as suas festas, e as suas luas novas, e os seus sábados, e todas as suas festividades." },
{name:'28212',l:'28',c:'2',v:'12',texto:"E devastarei a sua vide e a sua figueira, de que ela diz: É esta a paga que me deram os meus amantes; eu, pois, farei delas um bosque, e as bestas-feras do campo as devorarão." },
{name:'28213',l:'28',c:'2',v:'13',texto:"E sobre ela visitarei os dias de Baal, nos quais lhe queimou incenso, e se adornou dos seus pendentes e das suas gargantilhas, e andou atrás de seus namorados, mas de mim se esqueceu, diz o SENHOR." },
{name:'28214',l:'28',c:'2',v:'14',texto:"Portanto, eis que eu a atrairei, e a levarei para o deserto, e lhe falarei ao coração." },
{name:'28215',l:'28',c:'2',v:'15',texto:"E lhe darei as suas vinhas dali e o vale de Acor, por porta de esperança; e ali cantará, como nos dias da sua mocidade e como no dia em que subiu da terra do Egito." },
{name:'28216',l:'28',c:'2',v:'16',texto:"E acontecerá naquele dia, diz o SENHOR, que me chamarás: Meu marido e não me chamarás mais: Meu Baal." },
{name:'28217',l:'28',c:'2',v:'17',texto:"E da sua boca tirarei os nomes de baalins, e os seus nomes não virão mais em memória." },
{name:'28218',l:'28',c:'2',v:'18',texto:"E, naquele dia, farei por eles aliança com as bestas-feras do campo, e com as aves do céu, e com os répteis da terra; e da terra tirarei o arco, e a espada, e a guerra e os farei deitar em segurança." },
{name:'28219',l:'28',c:'2',v:'19',texto:"E desposar-te-ei comigo para sempre; desposar-te-ei comigo em justiça, e em juízo, e em benignidade, e em misericórdias." },
{name:'28220',l:'28',c:'2',v:'20',texto:"E desposar-te-ei comigo em fidelidade, e conhecerás o SENHOR." },
{name:'28221',l:'28',c:'2',v:'21',texto:"E acontecerá, naquele dia, que eu responderei, diz o SENHOR, eu responderei aos céus, e estes responderão à terra." },
{name:'28222',l:'28',c:'2',v:'22',texto:"E a terra responderá ao trigo, e ao mosto, e ao óleo; e estes responderão a Jezreel." },
{name:'28223',l:'28',c:'2',v:'23',texto:"E semeá-la-ei para mim na terra e compadecer-me-ei de Lo-Ruama; e a Lo-Ami direi: Tu és meu povo! E ele dirá: Tu és o meu Deus!" },
],
numVersiculos: 23,
},

c3: {
versiculos:[
{name:'2831',l:'28',c:'3',v:'1',texto:"E o SENHOR me disse: Vai outra vez, ama uma mulher, amada de seu amigo e adúltera, como o SENHOR ama os filhos de Israel, embora eles olhem para outros deuses e amem os bolos de uvas." },
{name:'2832',l:'28',c:'3',v:'2',texto:"E a comprei para mim por quinze peças de prata, e um ômer de cevada, e meio ômer de cevada;" },
{name:'2833',l:'28',c:'3',v:'3',texto:"e lhe disse: Tu ficarás comigo muitos dias; não te prostituirás, nem serás de outro homem; assim quero eu ser também para ti." },
{name:'2834',l:'28',c:'3',v:'4',texto:"Porque os filhos de Israel ficarão por muitos dias sem rei, e sem príncipe, e sem sacrifício, e sem estátua, e sem éfode ou terafins." },
{name:'2835',l:'28',c:'3',v:'5',texto:"Depois, tornarão os filhos de Israel e buscarão o SENHOR, seu Deus, e Davi, seu rei; e temerão o SENHOR e a sua bondade, no fim dos dias." },
],
numVersiculos: 5,
},

c4: {
versiculos:[
{name:'2841',l:'28',c:'4',v:'1',texto:"Ouvi a palavra do SENHOR, vós, filhos de Israel, porque o SENHOR tem uma contenda com os habitantes da terra, porque não há verdade, nem benignidade, nem conhecimento de Deus na terra." },
{name:'2842',l:'28',c:'4',v:'2',texto:"Só prevalecem o perjurar, e o mentir, e o matar, e o furtar, e o adulterar, e há homicídios sobre homicídios." },
{name:'2843',l:'28',c:'4',v:'3',texto:"Por isso, a terra se lamentará, e qualquer que morar nela desfalecerá com os animais do campo e com as aves do céu; e até os peixes do mar serão tirados." },
{name:'2844',l:'28',c:'4',v:'4',texto:"Todavia, ninguém contenda, nem qualquer repreenda; porque o teu povo é como os que contendem com o sacerdote." },
{name:'2845',l:'28',c:'4',v:'5',texto:"Por isso, cairás de dia, e o profeta contigo cairá de noite; e destruirei a tua mãe." },
{name:'2846',l:'28',c:'4',v:'6',texto:"O meu povo foi destruído, porque lhe faltou o conhecimento; porque tu rejeitaste o conhecimento, também eu te rejeitarei, para que não sejas sacerdote diante de mim; visto que te esqueceste da lei do teu Deus, também eu me esquecerei de teus filhos." },
{name:'2847',l:'28',c:'4',v:'7',texto:"Como eles se multiplicaram, assim contra mim pecaram; eu mudarei a sua honra em vergonha." },
{name:'2848',l:'28',c:'4',v:'8',texto:"Alimentam-se do pecado do meu povo e da maldade dele têm desejo ardente." },
{name:'2849',l:'28',c:'4',v:'9',texto:"Por isso, como é o povo, assim será o sacerdote; e visitarei sobre ele os seus caminhos e lhe darei a recompensa das suas obras." },
{name:'28410',l:'28',c:'4',v:'10',texto:"Comerão, mas não se fartarão; entregar-se-ão à luxúria, mas não se multiplicarão; porque deixaram de olhar para o SENHOR." },
{name:'28411',l:'28',c:'4',v:'11',texto:"A incontinência, e o vinho, e o mosto tiram a inteligência." },
{name:'28412',l:'28',c:'4',v:'12',texto:"O meu povo consulta a sua madeira, e a sua vara lhe responde, porque o espírito de luxúria os engana, e eles se corrompem, apartando-se da sujeição do seu Deus." },
{name:'28413',l:'28',c:'4',v:'13',texto:"Sacrificam sobre os cumes dos montes e queimam incenso sobre os outeiros, debaixo do carvalho, e do álamo, e do olmeiro, porque é boa a sua sombra; por isso, vossas filhas se prostituem, e as vossas noras adulteram." },
{name:'28414',l:'28',c:'4',v:'14',texto:"Eu não castigarei vossas filhas, que se prostituem, nem vossas noras, quando adulteram; porque eles mesmos com as prostitutas se desviam e com as meretrizes sacrificam, pois o povo que não tem entendimento será transtornado." },
{name:'28415',l:'28',c:'4',v:'15',texto:"Se tu, ó Israel, queres corromper-te, não se faça culpado Judá; não venhais a Gilgal, e não subais a Bete-Áven, e não jureis, dizendo: Vive o SENHOR." },
{name:'28416',l:'28',c:'4',v:'16',texto:"Porque, como uma vaca rebelde, se rebelou Israel; agora, o SENHOR os apascentará como a um cordeiro em um lugar espaçoso." },
{name:'28417',l:'28',c:'4',v:'17',texto:"Efraim está entregue aos ídolos; deixa-o." },
{name:'28418',l:'28',c:'4',v:'18',texto:"A sua bebida se foi; eles corrompem-se cada vez mais; certamente amaram a vergonha os seus príncipes." },
{name:'28419',l:'28',c:'4',v:'19',texto:"Um vento os envolveu nas suas asas, e envergonhar-se-ão por causa dos seus sacrifícios." },
],
numVersiculos: 19,
},

c5: {
versiculos:[
{name:'2851',l:'28',c:'5',v:'1',texto:"Ouvi isto, ó sacerdotes, e escutai, ó casa de Israel, e escutai, ó casa do rei, porque a vós pertence este juízo, visto que fostes um laço para Mispa e rede estendida sobre o Tabor." },
{name:'2852',l:'28',c:'5',v:'2',texto:"Os transviados têm descido até ao profundo, na matança; mas eu serei a correção de todos eles." },
{name:'2853',l:'28',c:'5',v:'3',texto:"Eu conheço Efraim, e Israel não se esconde de mim; porque, agora, te tens prostituído, ó Efraim, e se contaminou Israel." },
{name:'2854',l:'28',c:'5',v:'4',texto:"Não querem ordenar as suas ações, a fim de voltarem para o seu Deus; porque o espírito da prostituição está no meio deles, e não conhecem o SENHOR." },
{name:'2855',l:'28',c:'5',v:'5',texto:"Asoberba de Israel testificará, pois, no seu rosto; e Israel e Efraim cairão pela sua injustiça, e Judá cairá juntamente com eles." },
{name:'2856',l:'28',c:'5',v:'6',texto:"Eles irão com as suas ovelhas e com as suas vacas, para buscarem o SENHOR, mas não o acharão: ele se retirou deles." },
{name:'2857',l:'28',c:'5',v:'7',texto:"Aleivosamente se houveram contra o SENHOR, porque geraram filhos estranhos; agora, a lua nova os consumirá com as suas porções." },
{name:'2858',l:'28',c:'5',v:'8',texto:"Tocai a buzina em Gibeá, a trombeta em Ramá; gritai altamente em Bete-Áven; após ti, ó Benjamim." },
{name:'2859',l:'28',c:'5',v:'9',texto:"Efraim será para assolação no dia do castigo; entre as tribos de Israel manifestei o que certo está." },
{name:'28510',l:'28',c:'5',v:'10',texto:"Os príncipes de Judá são como os que traspassam os limites; derramarei, pois, o meu furor sobre eles como água." },
{name:'28511',l:'28',c:'5',v:'11',texto:"Efraim está oprimido e quebrantado no juízo, porque quis andar após a vaidade." },
{name:'28512',l:'28',c:'5',v:'12',texto:"Portanto, para Efraim serei como a traça e para a casa de Judá, como a podridão." },
{name:'28513',l:'28',c:'5',v:'13',texto:"Quando Efraim viu a sua enfermidade, e Judá, a sua chaga, subiu Efraim à Assíria e enviou ao rei Jarebe; mas ele não poderá curar-vos, nem sarar a vossa chaga." },
{name:'28514',l:'28',c:'5',v:'14',texto:"Porque, para Efraim, serei como um leão e como um leãozinho, para a casa de Judá; eu, eu despedaçarei e ir-me-ei embora; arrebatarei, e não haverá quem livre." },
{name:'28515',l:'28',c:'5',v:'15',texto:"Irei e voltarei para o meu lugar, até que se reconheçam culpados e busquem a minha face; estando eles angustiados, de madrugada me buscarão." },
],
numVersiculos: 15,
},

c6: {
versiculos:[
{name:'2861',l:'28',c:'6',v:'1',texto:"Vinde, e tornemos para o SENHOR, porque ele despedaçou e nos sarará, fez a ferida e a ligará." },
{name:'2862',l:'28',c:'6',v:'2',texto:"Depois de dois dias, nos dará a vida; ao terceiro dia, nos ressuscitará, e viveremos diante dele." },
{name:'2863',l:'28',c:'6',v:'3',texto:"Conheçamos e prossigamos em conhecer o SENHOR: como a alva, será a sua saída; e ele a nós virá como a chuva, como chuva serôdia que rega a terra." },
{name:'2864',l:'28',c:'6',v:'4',texto:"Que te farei, ó Efraim? Que te farei, ó Judá? Porque a vossa beneficência é como a nuvem da manhã e como o orvalho da madrugada, que cedo passa." },
{name:'2865',l:'28',c:'6',v:'5',texto:"Por isso, os abati pelos profetas; pela palavra da minha boca, os matei; e os teus juízos sairão como a luz." },
{name:'2866',l:'28',c:'6',v:'6',texto:"Porque eu quero misericórdia e não sacrifício; e o conhecimento de Deus, mais do que holocaustos." },
{name:'2867',l:'28',c:'6',v:'7',texto:"Mas eles traspassaram o concerto, como Adão; eles se portaram aleivosamente contra mim." },
{name:'2868',l:'28',c:'6',v:'8',texto:"Gileade é a cidade dos que praticam a iniqüidade, calcada de sangue." },
{name:'2869',l:'28',c:'6',v:'9',texto:"Como hordas de salteadores que espreitam alguém, assim é a companhia dos sacerdotes que matam no caminho para Siquém; sim, eles têm praticado abominações." },
{name:'28610',l:'28',c:'6',v:'10',texto:"Vejo uma coisa horrenda na casa de Israel: ali está a prostituição de Efraim; Israel é contaminado." },
{name:'28611',l:'28',c:'6',v:'11',texto:"Também para ti, ó Judá, foi assinada uma ceifa, quando eu remover o cativeiro do meu povo." },
],
numVersiculos: 11,
},

c7: {
versiculos:[
{name:'2871',l:'28',c:'7',v:'1',texto:"Sarando eu a Israel, se descobriu a iniqüidade de Efraim, como também as maldades de Samaria, porque praticaram a falsidade; e o ladrão entra, e a horda dos salteadores rouba cá fora." },
{name:'2872',l:'28',c:'7',v:'2',texto:"E não dizem no seu coração que eu me lembro de toda a sua maldade; agora, pois, os cercam as suas obras; diante da minha face estão." },
{name:'2873',l:'28',c:'7',v:'3',texto:"Com a sua malícia alegram ao rei e com as suas mentiras, aos príncipes." },
{name:'2874',l:'28',c:'7',v:'4',texto:"Todos eles são adúlteros: semelhantes são ao forno aceso pelo padeiro, que cessa de atear o fogo, desde que amassou a massa até que seja levedada." },
{name:'2875',l:'28',c:'7',v:'5',texto:"E, no dia do nosso rei, os príncipes se tornaram doentes com a excitação do vinho; ele estendeu a sua mão com os escarnecedores." },
{name:'2876',l:'28',c:'7',v:'6',texto:"Porque, como um forno, aplicaram o coração, emboscando-se; toda a noite dorme o seu padeiro, pela manhã, arde como fogo de chama." },
{name:'2877',l:'28',c:'7',v:'7',texto:"Eles estão todos quentes como um forno e consomem os seus juízes; todos os seus reis caem; ninguém entre eles há que me invoque." },
{name:'2878',l:'28',c:'7',v:'8',texto:"Efraim com os povos se mistura; Efraim é um bolo que não foi virado." },
{name:'2879',l:'28',c:'7',v:'9',texto:"Estrangeiros lhe devoraram a força, e ele não o sabe; também as cãs se espalharam sobre ele, e não o sabe." },
{name:'28710',l:'28',c:'7',v:'10',texto:"E a soberba de Israel testificará em sua face; todavia, não voltarão para o SENHOR, seu Deus, nem o buscarão em tudo isso." },
{name:'28711',l:'28',c:'7',v:'11',texto:"Porque Efraim é como uma pomba enganada, sem entendimento; invocam o Egito, vão para a Assíria." },
{name:'28712',l:'28',c:'7',v:'12',texto:"Quando forem, sobre eles estenderei a minha rede e, como aves do céu, os farei descer; castigá-los-ei, conforme o que eles têm ouvido na sua congregação." },
{name:'28713',l:'28',c:'7',v:'13',texto:"Ai deles, porque fugiram de mim; destruição sobre eles, porque se rebelaram contra mim; eu os remi, mas disseram mentiras contra mim." },
{name:'28714',l:'28',c:'7',v:'14',texto:"E não clamaram a mim com seu coração, mas davam uivos nas suas camas; para o trigo e para o vinho se ajuntam, mas contra mim se rebelam." },
{name:'28715',l:'28',c:'7',v:'15',texto:"Eu os ensinei e lhes fortaleci os braços, mas pensam mal contra mim." },
{name:'28716',l:'28',c:'7',v:'16',texto:"Eles voltam, mas não para o Altíssimo. Fizeram-se como um arco enganador; caem à espada os seus príncipes por causa da violência da sua língua; este será o seu escárnio na terra do Egito." },
],
numVersiculos: 16,
},

c8: {
versiculos:[
{name:'2881',l:'28',c:'8',v:'1',texto:"Põe a trombeta à tua boca. Ele vem como águia contra a casa do SENHOR, porque traspassaram o meu concerto e se rebelaram contra a minha lei." },
{name:'2882',l:'28',c:'8',v:'2',texto:"E a mim clamarão: Deus meu! Nós, Israel, te conhecemos." },
{name:'2883',l:'28',c:'8',v:'3',texto:"Israel rejeitou o bem; o inimigo persegui-lo-á." },
{name:'2884',l:'28',c:'8',v:'4',texto:"Eles fizeram reis, mas não por mim; constituíram príncipes, mas eu não o soube; da sua prata e do seu ouro fizeram ídolos para si, para serem destruídos." },
{name:'2885',l:'28',c:'8',v:'5',texto:"O teu bezerro, ó Samaria, foi rejeitado; a minha ira se acendeu contra eles; até quando serão eles incapazes de alcançar a inocência?" },
{name:'2886',l:'28',c:'8',v:'6',texto:"Porque isso é mesmo de Israel; um artífice o fez, e não é Deus; mas em pedaços será desfeito o bezerro de Samaria." },
{name:'2887',l:'28',c:'8',v:'7',texto:"Porque semearam ventos e segarão tormentas; não há seara; a erva não dará farinha; se a der, tragá-la-ão os estrangeiros." },
{name:'2888',l:'28',c:'8',v:'8',texto:"Israel foi devorado; agora, está entre as nações como coisa em que ninguém tem prazer." },
{name:'2889',l:'28',c:'8',v:'9',texto:"Porque subiram à Assíria, como um jumento montês, por si só; mercou Efraim amores." },
{name:'28810',l:'28',c:'8',v:'10',texto:"Todavia, ainda que eles merquem entre as nações, eu os congregarei; já começaram a ser diminuídos por causa da carga do rei dos príncipes." },
{name:'28811',l:'28',c:'8',v:'11',texto:"Porquanto Efraim multiplicou os altares para pecar; teve altares para pecar." },
{name:'28812',l:'28',c:'8',v:'12',texto:"Escrevi para eles as grandezas da minha lei; mas isso é para eles como coisa estranha." },
{name:'28813',l:'28',c:'8',v:'13',texto:"Quanto aos sacrifícios dos meus dons, sacrificam carne e a comem, mas o SENHOR não a aceitou; agora, se lembrará da sua injustiça e visitará os seus pecados; eles voltarão para o Egito." },
{name:'28814',l:'28',c:'8',v:'14',texto:"Porque Israel se esqueceu do seu Criador e edificou palácios, e Judá multiplicou cidades fortes; mas eu enviarei um fogo contra as suas cidades, e ele consumirá os seus palácios." },
],
numVersiculos: 14,
},

c9: {
versiculos:[
{name:'2891',l:'28',c:'9',v:'1',texto:"Não te alegres, ó Israel, até saltar, como os povos; porque te foste do teu Deus como uma meretriz; amaste a paga sobre todas as eiras de trigo." },
{name:'2892',l:'28',c:'9',v:'2',texto:"A eira e o lagar não os manterão; e o mosto lhes faltará." },
{name:'2893',l:'28',c:'9',v:'3',texto:"Na terra do SENHOR, não permanecerão; mas Efraim tornará ao Egito, e na Assíria comerão comida imunda." },
{name:'2894',l:'28',c:'9',v:'4',texto:"Não derramarão vinho perante o SENHOR, nem as suas ofertas serão para ele suaves; os seus sacrifícios para eles serão como pão de pranteadores; todos os que dele comessem seriam imundos, porque o seu pão será para o seu apetite; não entrará na casa do SENHOR." },
{name:'2895',l:'28',c:'9',v:'5',texto:"Que fareis vós no dia da solenidade e no dia da festa do SENHOR?" },
{name:'2896',l:'28',c:'9',v:'6',texto:"Porque eis que eles se foram por causa da destruição, mas o Egito os recolherá, Mênfis os sepultará; o desejável da sua prata as urtigas o possuirão por herança; espinhos haverá nas suas moradas." },
{name:'2897',l:'28',c:'9',v:'7',texto:"Chegaram os dias da visitação, chegaram os dias da retribuição; Israel o saberá; o profeta é um insensato, o homem de espírito é um louco; por causa da abundância da tua iniqüidade, também avultará o ódio." },
{name:'2898',l:'28',c:'9',v:'8',texto:"Efraim era vigia junto com o meu Deus, mas o profeta é como um laço de caçador de aves em todos os seus caminhos, um inimigo na casa do seu Deus." },
{name:'2899',l:'28',c:'9',v:'9',texto:"Mui profundamente se corromperam, como nos dias de Gibeá. Ele lembrar-se-á das suas injustiças, visitará os pecados deles." },
{name:'28910',l:'28',c:'9',v:'10',texto:"Achei Israel como uvas no deserto, vi a vossos pais como a fruta temporã da figueira no seu princípio; mas eles foram para Baal-Peor, e se consagraram a essa coisa vergonhosa, e se tornaram abomináveis como aquilo que amaram." },
{name:'28911',l:'28',c:'9',v:'11',texto:"Quanto a Efraim, a sua glória, como ave, voará; não haverá nascimento, não haverá filho, nem concepção." },
{name:'28912',l:'28',c:'9',v:'12',texto:"Ainda que venham a criar seus filhos, eu os privarei deles, para que não fique nenhum homem; porque também ai deles, quando deles me apartar!" },
{name:'28913',l:'28',c:'9',v:'13',texto:"Efraim, assim como vi Tiro, está plantado em um lugar deleitoso; mas Efraim levará seus filhos ao matador." },
{name:'28914',l:'28',c:'9',v:'14',texto:"Dá-lhes, ó SENHOR; mas que lhes darás? Dá-lhes uma madre que aborte e seios secos." },
{name:'28915',l:'28',c:'9',v:'15',texto:"Toda a sua malícia se acha em Gilgal, porque ali os aborreci; por causa da maldade das suas obras, os lançarei fora de minha casa; não os amarei mais; todos os seus príncipes são rebeldes." },
{name:'28916',l:'28',c:'9',v:'16',texto:"Efraim foi ferido, secou-se a sua raiz; não darão fruto; sim, ainda que gerem, eu matarei os frutos desejáveis do seu ventre." },
{name:'28917',l:'28',c:'9',v:'17',texto:"O meu Deus os rejeitará, porque não o ouvem; e desocupados andarão entre as nações." },
],
numVersiculos: 17,
},

c10: {
versiculos:[
{name:'28101',l:'28',c:'10',v:'1',texto:"Israel é uma vide frondosa; dá fruto para si mesmo; conforme a abundância do seu fruto, assim multiplicou os altares; conforme a bondade da terra, assim fizeram boas estátuas." },
{name:'28102',l:'28',c:'10',v:'2',texto:"O seu coração está dividido; por isso, serão culpados; cortará os seus altares e destruirá as estátuas." },
{name:'28103',l:'28',c:'10',v:'3',texto:"Certamente, agora, dirão: Não temos rei, porque não tememos o SENHOR; que, pois, nos faria o rei?" },
{name:'28104',l:'28',c:'10',v:'4',texto:"Multiplicaram palavras, jurando falsamente, fazendo um concerto; por isso, florescerá o juízo como erva peçonhenta nos regos dos campos." },
{name:'28105',l:'28',c:'10',v:'5',texto:"Os moradores de Samaria serão atemorizados pelo bezerro de Bete-Áven, porquanto o seu povo se lamentará por causa dele, como também os seus sacerdotes ( que nele se alegravam ), e por causa da sua glória, que se apartou dela." },
{name:'28106',l:'28',c:'10',v:'6',texto:"Também a Assíria será levada como um presente ao rei Jarebe; Efraim ficará confuso, e Israel se envergonhará por causa do seu próprio conselho." },
{name:'28107',l:'28',c:'10',v:'7',texto:"O rei de Samaria será desfeito como a espuma sobre a face da água." },
{name:'28108',l:'28',c:'10',v:'8',texto:"E os altos de Áven, pecado de Israel, serão destruídos; espinhos e cardos crescerão sobre os seus altares; e dirão aos montes: Cobri-nos! E aos outeiros: Caí sobre nós!" },
{name:'28109',l:'28',c:'10',v:'9',texto:"Desde os dias de Gibeá, pecaste, ó Israel; ali permaneceram; a peleja em Gibeá contra os filhos da perversidade não os surpreenderá." },
{name:'281010',l:'28',c:'10',v:'10',texto:"Eu os castigarei na medida do meu desejo; e congregar-se-ão contra eles os povos, quando os atar às suas transgressões." },
{name:'281011',l:'28',c:'10',v:'11',texto:"Porque Efraim é uma bezerra domada, que gosta de trilhar; passei sobre a formosura do seu pescoço; farei cavalgar Efraim. Judá lavrará, Jacó lhe desfará os torrões." },
{name:'281012',l:'28',c:'10',v:'12',texto:"Semeai para vós em justiça, ceifai segundo a misericórdia; lavrai o campo de lavoura; porque é tempo de buscar o SENHOR, até que venha, e chova a justiça sobre vós." },
{name:'281013',l:'28',c:'10',v:'13',texto:"Lavrastes a impiedade, segastes a perversidade e comestes o fruto da mentira; porque confiaste no teu caminho, na multidão dos teus valentes." },
{name:'281014',l:'28',c:'10',v:'14',texto:"Portanto, entre o teu povo se levantará um grande tumulto, e todas as tuas fortalezas serão destruídas, como Salmã destruiu a Bete-Arbel no dia da guerra; a mãe ali foi despedaçada com os filhos." },
{name:'281015',l:'28',c:'10',v:'15',texto:"Assim vos fará Betel, por causa da vossa malícia; o rei de Israel, de madrugada, será totalmente destruído." },
],
numVersiculos: 15,
},

c11: {
versiculos:[
{name:'28111',l:'28',c:'11',v:'1',texto:"Quando Israel era menino, eu o amei; e do Egito chamei a meu filho." },
{name:'28112',l:'28',c:'11',v:'2',texto:"Mas, como os chamavam, assim se iam da sua face; sacrificavam a baalins e queimavam incenso às imagens de escultura." },
{name:'28113',l:'28',c:'11',v:'3',texto:"Todavia, eu ensinei a andar a Efraim; tomei-os pelos seus braços, mas não conheceram que eu os curava." },
{name:'28114',l:'28',c:'11',v:'4',texto:"Atraí-os com cordas humanas, com cordas de amor; e fui para eles como os que tiram o jugo de sobre as suas queixadas; e lhes dei mantimento." },
{name:'28115',l:'28',c:'11',v:'5',texto:"Não voltará para a terra do Egito, mas a Assíria será seu rei, porque recusam converter-se." },
{name:'28116',l:'28',c:'11',v:'6',texto:"E cairá a espada sobre as suas cidades, e consumirá os seus ferrolhos, e os devorará, por causa dos seus conselhos." },
{name:'28117',l:'28',c:'11',v:'7',texto:"Porque o meu povo é inclinado a desviar-se de mim; bem que clamam ao Altíssimo, nenhum deles o exalta." },
{name:'28118',l:'28',c:'11',v:'8',texto:"Como te deixaria, ó Efraim? Como te entregaria, ó Israel? Como te faria como Admá? Pôr-te-ia como Zeboim? Está mudado em mim o meu coração, todos os meus pesares juntamente estão acesos." },
{name:'28119',l:'28',c:'11',v:'9',texto:"Não executarei o furor da minha ira; não voltarei para destruir Efraim, porque eu sou Deus e não homem, o Santo no meio de ti; eu não entrarei na cidade." },
{name:'281110',l:'28',c:'11',v:'10',texto:"Andarão após o SENHOR; ele bramará como leão; bramando ele, os filhos do Ocidente tremerão." },
{name:'281111',l:'28',c:'11',v:'11',texto:"Tremendo, virão, como um passarinho, os do Egito, e, como uma pomba, os da terra da Assíria, e os farei habitar em suas casas, diz o SENHOR." },
{name:'281112',l:'28',c:'11',v:'12',texto:"Efraim me cercou com mentira, e a casa de Israel, com engano; mas Judá ainda domina com Deus e com o Santo está fiel." },
],
numVersiculos: 12,
},

c12: {
versiculos:[
{name:'28121',l:'28',c:'12',v:'1',texto:"Efraim se apascenta de vento e segue o vento leste; todo o dia multiplica a mentira e a destruição, e fazem aliança com a Assíria, e o azeite se leva ao Egito." },
{name:'28122',l:'28',c:'12',v:'2',texto:"O SENHOR também com Judá tem contenda e castigará Jacó segundo os seus caminhos; segundo as suas obras, o recompensará." },
{name:'28123',l:'28',c:'12',v:'3',texto:"No ventre, pegou do calcanhar de seu irmão e, pela sua força, como príncipe, se houve com Deus." },
{name:'28124',l:'28',c:'12',v:'4',texto:"Como príncipe, lutou com o anjo e prevaleceu; chorou e lhe suplicou; em Betel o achou, e ali falou conosco;" },
{name:'28125',l:'28',c:'12',v:'5',texto:"sim, com o SENHOR, o Deus dos Exércitos; o SENHOR é o seu memorial." },
{name:'28126',l:'28',c:'12',v:'6',texto:"Tu, pois, converte-te a teu Deus; guarda a beneficência e o juízo e em teu Deus espera sempre." },
{name:'28127',l:'28',c:'12',v:'7',texto:"É um mercador; tem balança enganadora em sua mão; ele ama a opressão." },
{name:'28128',l:'28',c:'12',v:'8',texto:"E diz Efraim: Contudo, eu tenho-me enriquecido, tenho adquirido para mim grandes bens; em todo o meu trabalho, não acharão em mim iniqüidade alguma que seja pecado." },
{name:'28129',l:'28',c:'12',v:'9',texto:"Mas eu sou o SENHOR, teu Deus, desde a terra do Egito; eu ainda te farei habitar em tendas, como nos dias da reunião solene." },
{name:'281210',l:'28',c:'12',v:'10',texto:"E falarei aos profetas e multiplicarei a visão; e, pelo ministério dos profetas, proporei símiles." },
{name:'281211',l:'28',c:'12',v:'11',texto:"Não é Gileade iniqüidade? Pura vaidade eles são; em Gilgal sacrificam bois; os seus altares são como montões de pedras nos regos dos campos." },
{name:'281212',l:'28',c:'12',v:'12',texto:"Jacó fugiu para o campo da Síria, e Israel serviu por uma mulher e por uma mulher guardou o gado." },
{name:'281213',l:'28',c:'12',v:'13',texto:"Mas o SENHOR, por meio de um profeta, fez subir a Israel do Egito, e, por um profeta, foi ele guardado." },
{name:'281214',l:'28',c:'12',v:'14',texto:"Efraim mui amargosamente provocou a sua ira; portanto, deixará ficar sobre ele o seu sangue e o seu Senhor fará cair sobre ele o seu opróbrio." },
],
numVersiculos: 14,
},

c13: {
versiculos:[
{name:'28131',l:'28',c:'13',v:'1',texto:"Quando Efraim falava, tremia-se; foi exalçado em Israel; mas ele fez-se culpado em Baal e morreu." },
{name:'28132',l:'28',c:'13',v:'2',texto:"E, agora, multiplicaram pecados e da sua prata fizeram uma imagem de fundição, ídolos segundo o seu entendimento, todos obra de artífices, dos quais dizem: Os homens que sacrificam beijam os bezerros." },
{name:'28133',l:'28',c:'13',v:'3',texto:"Por isso, serão como a nuvem de manhã e como o orvalho da madrugada, que cedo passa, como o folhelho, que a tempestade lança da eira, e como a fumaça da chaminé." },
{name:'28134',l:'28',c:'13',v:'4',texto:"Todavia, eu sou o SENHOR, teu Deus, desde a terra do Egito; portanto, não reconhecerás outro deus além de mim, porque não há Salvador, senão eu." },
{name:'28135',l:'28',c:'13',v:'5',texto:"Eu te conheci no deserto, em terra muito seca." },
{name:'28136',l:'28',c:'13',v:'6',texto:"Depois, eles se fartaram em proporção do seu pasto; estando fartos, ensoberbeceu-se o seu coração; por isso, se esqueceram de mim." },
{name:'28137',l:'28',c:'13',v:'7',texto:"Serei, pois, para eles como leão; como leopardo, espiarei no caminho." },
{name:'28138',l:'28',c:'13',v:'8',texto:"Como urso que tem perdido seus filhos, os encontrarei, lhes romperei as teias do seu coração; e ali os devorarei como leão; as feras do campo os despedaçarão." },
{name:'28139',l:'28',c:'13',v:'9',texto:"Para tua perda, ó Israel, te rebelaste contra mim, contra o teu ajudador." },
{name:'281310',l:'28',c:'13',v:'10',texto:"Onde está, agora, o teu rei, para que te guarde em todas as tuas cidades? E os teus juízes, dos quais disseste: Dá-me rei e príncipes?" },
{name:'281311',l:'28',c:'13',v:'11',texto:"Dei-te um rei na minha ira e to tirei no meu furor." },
{name:'281312',l:'28',c:'13',v:'12',texto:"A iniqüidade de Efraim está atada, o seu pecado está armazenado." },
{name:'281313',l:'28',c:'13',v:'13',texto:"Dores de mulher de parto lhe virão; ele é um filho insensato, porque é tempo, e não está no lugar em que deve vir à luz." },
{name:'281314',l:'28',c:'13',v:'14',texto:"Eu os remirei da violência do inferno e os resgatarei da morte; onde estão, ó morte, as tuas pragas? Onde está, ó inferno, a tua perdição? O arrependimento será escondido de meus olhos." },
{name:'281315',l:'28',c:'13',v:'15',texto:"Ainda que ele dê fruto entre os irmãos, virá o vento leste, vento do SENHOR, subindo do deserto, e secar-se-á a sua nascente, e secar-se-á a sua fonte; ele saqueará o tesouro de todos os vasos desejáveis." },
{name:'281316',l:'28',c:'13',v:'16',texto:"Samaria virá a ser deserta, porque se rebelou contra o seu Deus; cairão à espada, seus filhos serão despedaçados, e as suas mulheres grávidas serão abertas pelo meio." },
],
numVersiculos: 16,
},

c14: {
versiculos:[
{name:'28141',l:'28',c:'14',v:'1',texto:"Converte-te, ó Israel, ao SENHOR, teu Deus; porque, pelos teus pecados, tens caído." },
{name:'28142',l:'28',c:'14',v:'2',texto:"Tomai convosco palavras e convertei-vos ao SENHOR; dizei-lhe: Expulsa toda a iniqüidade e recebe o bem; e daremos como bezerros os sacrifícios dos nossos lábios." },
{name:'28143',l:'28',c:'14',v:'3',texto:"Não nos salvará a Assíria, não iremos montados em cavalos e à obra das nossas mãos não diremos mais: Tu és o nosso Deus; porque, por ti, o órfão alcançará misericórdia." },
{name:'28144',l:'28',c:'14',v:'4',texto:"Eu sararei a sua perversão, eu voluntariamente os amarei; porque a minha ira se apartou deles." },
{name:'28145',l:'28',c:'14',v:'5',texto:"Eu serei, para Israel, como orvalho; ele florescerá como o lírio e espalhará as suas raízes como o Líbano." },
{name:'28146',l:'28',c:'14',v:'6',texto:"Estender-se-ão as suas vergônteas, e a sua glória será como a da oliveira, o seu odor, como o do Líbano." },
{name:'28147',l:'28',c:'14',v:'7',texto:"Voltarão os que se assentarem à sua sombra; serão vivificados como o trigo e florescerão como a vide; a sua memória será como o vinho do Líbano." },
{name:'28148',l:'28',c:'14',v:'8',texto:"Efraim dirá: Que mais tenho eu com os ídolos? Eu o tenho ouvido e isso considerarei; eu sou como a faia verde; de mim é achado o teu fruto." },
{name:'28149',l:'28',c:'14',v:'9',texto:"Quem é sábio, para que entenda estas coisas? Prudente, para que as saiba? Porque os caminhos do SENHOR são retos, e os justos andarão neles, mas os transgressores neles cairão." },
],
numVersiculos: 9,
},


};
