BibliaJFA.joel = {
	libro: "Joel",
	numCapitulos: 3,

c1: {
versiculos:[
{name:'2911',l:'29',c:'1',v:'1',texto:"Palavra do SENHOR que foi dirigida a Joel, filho de Petuel." },
{name:'2912',l:'29',c:'1',v:'2',texto:"Ouvi isto, vós, anciãos, e escutai, todos os moradores da terra: Aconteceu isto em vossos dias? Ou também nos dias de vossos pais?" },
{name:'2913',l:'29',c:'1',v:'3',texto:"Fazei sobre isto uma narração a vossos filhos, e vossos filhos, a seus filhos, e os filhos destes, à outra geração." },
{name:'2914',l:'29',c:'1',v:'4',texto:"O que ficou da lagarta, o comeu o gafanhoto, e o que ficou do gafanhoto, o comeu a locusta, e o que ficou da locusta, o comeu o pulgão." },
{name:'2915',l:'29',c:'1',v:'5',texto:"Despertai, ébrios, e chorai; gemei, todos os que bebeis vinho, por causa do mosto, porque tirado é da vossa boca." },
{name:'2916',l:'29',c:'1',v:'6',texto:"Porque uma nação subiu sobre a minha terra, poderosa e sem número; os seus dentes são dentes de leão, e tem queixadas de um leão velho." },
{name:'2917',l:'29',c:'1',v:'7',texto:"Fez da minha vide uma assolação, e tirou a casca da minha figueira, e despiu-a toda, e a lançou por terra; os seus sarmentos se embranqueceram." },
{name:'2918',l:'29',c:'1',v:'8',texto:"Lamenta como a virgem que está cingida de pano de saco pelo marido da sua mocidade." },
{name:'2919',l:'29',c:'1',v:'9',texto:"Foi cortada a oferta de manjar e a libação da Casa do SENHOR; os sacerdotes, servos do SENHOR, estão entristecidos." },
{name:'29110',l:'29',c:'1',v:'10',texto:"O campo está assolado, e a terra, triste; porque o trigo está destruído, o mosto se secou, o óleo falta." },
{name:'29111',l:'29',c:'1',v:'11',texto:"Os lavradores se envergonham, os vinhateiros gemem sobre o trigo e sobre a cevada; porque a colheita do campo pereceu." },
{name:'29112',l:'29',c:'1',v:'12',texto:"A vide se secou, a figueira se murchou; a romeira também, e a palmeira, e a macieira; todas as árvores do campo se secaram, e a alegria se secou entre os filhos dos homens." },
{name:'29113',l:'29',c:'1',v:'13',texto:"Cingi-vos e lamentai-vos, sacerdotes; gemei, ministros do altar; entrai e passai, vestidos de panos de saco, durante a noite, ministros do meu Deus; porque a oferta de manjares e a libação cortadas foram da Casa de vosso Deus." },
{name:'29114',l:'29',c:'1',v:'14',texto:"Santificai um jejum, apregoai um dia de proibição, congregai os anciãos e todos os moradores desta terra, na Casa do SENHOR, vosso Deus, e clamai ao SENHOR." },
{name:'29115',l:'29',c:'1',v:'15',texto:"Ah! Aquele dia! Porque o dia do SENHOR está perto e virá como uma assolação do Todo-poderoso." },
{name:'29116',l:'29',c:'1',v:'16',texto:"Porventura o mantimento não está cortado de diante de nossos olhos? A alegria e o regozijo, da Casa de nosso Deus?" },
{name:'29117',l:'29',c:'1',v:'17',texto:"A semente apodreceu debaixo dos seus torrões, os celeiros foram assolados, os armazéns, derribados, porque se secou o trigo." },
{name:'29118',l:'29',c:'1',v:'18',texto:"Como geme o gado! As manadas de vacas estão confusas, porque não têm pasto; também os rebanhos de ovelhas são destruídos." },
{name:'29119',l:'29',c:'1',v:'19',texto:"A ti, ó SENHOR, clamo, porque o fogo consumiu os pastos do deserto, e a chama abrasou todas as árvores do campo." },
{name:'29120',l:'29',c:'1',v:'20',texto:"Também todos os animais do campo bramam a ti; porque os rios se secaram, e o fogo consumiu os pastos do deserto." },
],
numVersiculos: 20,
},

c2: {
versiculos:[
{name:'2921',l:'29',c:'2',v:'1',texto:"Tocai a buzina em Sião e clamai em alta voz no monte da minha santidade; perturbem-se todos os moradores da terra, porque o dia do SENHOR vem, ele está perto;" },
{name:'2922',l:'29',c:'2',v:'2',texto:"dia de trevas e de tristeza; dia de nuvens e de trevas espessas; como a alva espalhada sobre os montes, povo grande e poderoso, qual desde o tempo antigo nunca houve, nem depois dele haverá pelos anos adiante, de geração em geração." },
{name:'2923',l:'29',c:'2',v:'3',texto:"Diante dele um fogo consome; e atrás dele uma chama abrasa; a terra diante dele é como o jardim do Éden, mas atrás dele um desolado deserto; sim, nada lhe escapará." },
{name:'2924',l:'29',c:'2',v:'4',texto:"O seu parecer é como o parecer de cavalos; e correrão como cavaleiros." },
{name:'2925',l:'29',c:'2',v:'5',texto:"Como o estrondo de carros sobre os cumes dos montes, irão eles saltando; como o ruído da chama de fogo que consome a pragana, como um povo poderoso, ordenado para o combate." },
{name:'2926',l:'29',c:'2',v:'6',texto:"Diante dele temerão os povos; todos os rostos são como a tisnadura da panela." },
{name:'2927',l:'29',c:'2',v:'7',texto:"Como valentes correrão, como homens de guerra subirão os muros; e irá cada um nos seus caminhos, e não se desviarão da sua fileira." },
{name:'2928',l:'29',c:'2',v:'8',texto:"Ninguém apertará a seu irmão; irá cada um pelo seu carreiro; sobre a mesma espada se arremessarão e não serão feridos." },
{name:'2929',l:'29',c:'2',v:'9',texto:"Irão pela cidade, correrão pelos muros, subirão às casas, pelas janelas entrarão como o ladrão." },
{name:'29210',l:'29',c:'2',v:'10',texto:"Diante dele tremerá a terra, abalar-se-ão os céus; o sol e a lua se enegrecerão, e as estrelas retirarão o seu resplendor." },
{name:'29211',l:'29',c:'2',v:'11',texto:"E o SENHOR levanta a sua voz diante do seu exército; porque muitíssimos são os seus arraiais; porque poderoso é, executando a sua palavra; porque o dia do SENHOR é grande e mui terrível, e quem o poderá sofrer?" },
{name:'29212',l:'29',c:'2',v:'12',texto:"Ainda assim, agora mesmo diz o SENHOR: Convertei-vos a mim de todo o vosso coração; e isso com jejuns, e com choro, e com pranto." },
{name:'29213',l:'29',c:'2',v:'13',texto:"E rasgai o vosso coração, e não as vossas vestes, e convertei-vos ao SENHOR, vosso Deus; porque ele é misericordioso, e compassivo, e tardio em irar-se, e grande em beneficência e se arrepende do mal." },
{name:'29214',l:'29',c:'2',v:'14',texto:"Quem sabe se se voltará, e se arrependerá, e deixará após si uma bênção, em oferta de manjar e libação para o SENHOR, vosso Deus?" },
{name:'29215',l:'29',c:'2',v:'15',texto:"Tocai a buzina em Sião, santificai um jejum, proclamai um dia de proibição." },
{name:'29216',l:'29',c:'2',v:'16',texto:"Congregai o povo, santificai a congregação, ajuntai os anciãos, congregai os filhinhos e os que mamam; saia o noivo da sua recâmara, e a noiva, do seu tálamo." },
{name:'29217',l:'29',c:'2',v:'17',texto:"Chorem os sacerdotes, ministros do SENHOR, entre o alpendre e o altar, e digam: Poupa o teu povo, ó SENHOR, e não entregues a tua herança ao opróbrio, para que as nações façam escárnio dele; porque diriam entre os povos: Onde está o seu Deus?" },
{name:'29218',l:'29',c:'2',v:'18',texto:"Então, o SENHOR terá zelo da sua terra e se compadecerá do seu povo." },
{name:'29219',l:'29',c:'2',v:'19',texto:"E o SENHOR responderá e dirá ao seu povo: Eis que vos envio o trigo, e o mosto, e o óleo, e deles sereis fartos, e vos não entregarei mais ao opróbrio entre as nações." },
{name:'29220',l:'29',c:'2',v:'20',texto:"E aquele que é do Norte farei partir para longe de vós, e lançá-lo-ei em uma terra seca e deserta; a sua frente para o mar oriental, e a sua retaguarda para o mar ocidental; e subirá o seu mau cheiro, e subirá a sua podridão; porque fez grandes coisas." },
{name:'29221',l:'29',c:'2',v:'21',texto:"Não temas, ó terra; regozija-te e alegra-te; porque o SENHOR fez grandes coisas." },
{name:'29222',l:'29',c:'2',v:'22',texto:"Não temais, animais do campo, porque os pastos do deserto reverdecerão, porque o arvoredo dará o seu fruto, a vide e a figueira darão a sua força." },
{name:'29223',l:'29',c:'2',v:'23',texto:"E vós, filhos de Sião, regozijai-vos e alegrai-vos no SENHOR, vosso Deus, porque ele vos dará ensinador de justiça e fará descer a chuva, a temporã e a serôdia, no primeiro mês." },
{name:'29224',l:'29',c:'2',v:'24',texto:"E as eiras se encherão de trigo, e os lagares transbordarão de mosto e de óleo." },
{name:'29225',l:'29',c:'2',v:'25',texto:"E restituir-vos-ei os anos que foram consumidos pelo gafanhoto, e a locusta, e o pulgão, e a oruga, o meu grande exército que enviei contra vós." },
{name:'29226',l:'29',c:'2',v:'26',texto:"E comereis fartamente, e ficareis satisfeitos, e louvareis o nome do SENHOR, vosso Deus, que procedeu para convosco maravilhosamente; e o meu povo não será mais envergonhado." },
{name:'29227',l:'29',c:'2',v:'27',texto:"E vós sabereis que eu estou no meio de Israel e que eu sou o SENHOR, vosso Deus, e ninguém mais; e o meu povo não será envergonhado para sempre." },
{name:'29228',l:'29',c:'2',v:'28',texto:"E há de ser que, depois, derramarei o meu Espírito sobre toda a carne, e vossos filhos e vossas filhas profetizarão, os vossos velhos terão sonhos, os vossos jovens terão visões." },
{name:'29229',l:'29',c:'2',v:'29',texto:"E também sobre os servos e sobre as servas, naqueles dias, derramarei o meu Espírito." },
{name:'29230',l:'29',c:'2',v:'30',texto:"E mostrarei prodígios no céu e na terra, sangue, e fogo, e colunas de fumaça." },
{name:'29231',l:'29',c:'2',v:'31',texto:"O sol se converterá em trevas, e a lua, em sangue, antes que venha o grande e terrível dia do SENHOR." },
{name:'29232',l:'29',c:'2',v:'32',texto:"E há de ser que todo aquele que invocar o nome do SENHOR será salvo; porque no monte Sião e em Jerusalém haverá livramento, assim como o SENHOR tem dito, e nos restantes que o SENHOR chamar." },
],
numVersiculos: 32,
},

c3: {
versiculos:[
{name:'2931',l:'29',c:'3',v:'1',texto:"Porquanto eis que, naqueles dias e naquele tempo, em que removerei o cativeiro de Judá e de Jerusalém," },
{name:'2932',l:'29',c:'3',v:'2',texto:"congregarei todas as nações e as farei descer ao vale de Josafá; e ali com elas entrarei em juízo, por causa do meu povo e da minha herança, Israel, a quem eles espalharam entre as nações, repartindo a minha terra." },
{name:'2933',l:'29',c:'3',v:'3',texto:"E lançaram a sorte sobre o meu povo, e deram um menino por uma meretriz, e venderam uma menina por vinho, para beberem." },
{name:'2934',l:'29',c:'3',v:'4',texto:"E também que tendes vós comigo, Tiro e Sidom e todos os termos da Fenícia? É tal o pago que vós me dais? Pois, se me pagais assim, bem depressa farei cair a vossa paga sobre a vossa cabeça." },
{name:'2935',l:'29',c:'3',v:'5',texto:"Visto como levastes a minha prata e o meu ouro e as minhas coisas desejáveis e formosas metestes nos vossos templos;" },
{name:'2936',l:'29',c:'3',v:'6',texto:"e vendestes os filhos de Judá e os filhos de Jerusalém aos filhos dos gregos, para os apartar para longe dos seus termos;" },
{name:'2937',l:'29',c:'3',v:'7',texto:"eis que eu os moverei do lugar para onde os vendestes; e farei cair a vossa paga sobre a vossa própria cabeça." },
{name:'2938',l:'29',c:'3',v:'8',texto:"E venderei vossos filhos e vossas filhas pela mão dos filhos de Judá, que os venderão aos de Seba, a uma nação remota, porque o SENHOR o disse." },
{name:'2939',l:'29',c:'3',v:'9',texto:"Proclamai isso entre as nações, santificai uma guerra; suscitai os valentes; cheguem-se, subam todos os homens de guerra." },
{name:'29310',l:'29',c:'3',v:'10',texto:"Forjai espadas das vossas enxadas e lanças das vossas foices; diga o fraco: Eu sou forte." },
{name:'29311',l:'29',c:'3',v:'11',texto:"Ajuntai-vos, e vinde, todos os povos em redor, e congregai-vos ( ó SENHOR, faze descer ali os teus fortes! );" },
{name:'29312',l:'29',c:'3',v:'12',texto:"movam-se as nações e subam ao vale de Josafá; porque ali me assentarei, para julgar todas as nações em redor." },
{name:'29313',l:'29',c:'3',v:'13',texto:"Lançai a foice, porque já está madura a seara; vinde, descei, porque o lagar está cheio, os vasos dos lagares transbordam; porquanto a sua malícia é grande." },
{name:'29314',l:'29',c:'3',v:'14',texto:"Multidões, multidões no vale da Decisão! Porque o dia do SENHOR está perto, no vale da Decisão." },
{name:'29315',l:'29',c:'3',v:'15',texto:"O sol e a lua se enegrecerão, e as estrelas retirarão o seu resplendor." },
{name:'29316',l:'29',c:'3',v:'16',texto:"E o SENHOR bramará de Sião e dará a sua voz de Jerusalém, e os céus e a terra tremerão; mas o SENHOR será o refúgio do seu povo e a fortaleza dos filhos de Israel." },
{name:'29317',l:'29',c:'3',v:'17',texto:"E vós sabereis que eu sou o SENHOR, vosso Deus, que habito em Sião, o monte da minha santidade; e Jerusalém será santidade; estranhos não passarão mais por ela." },
{name:'29318',l:'29',c:'3',v:'18',texto:"E há de ser que, naquele dia, os montes destilarão mosto, e dos outeiros manará leite, e todos os rios de Judá estarão cheios de águas; e sairá uma fonte da Casa do SENHOR e regará o vale de Sitim." },
{name:'29319',l:'29',c:'3',v:'19',texto:"O Egito se tornará uma assolação, e Edom se fará um deserto de solidão, por causa da violência que fizeram aos filhos de Judá, em cuja terra derramaram sangue inocente." },
{name:'29320',l:'29',c:'3',v:'20',texto:"Mas Judá será habitada para sempre, e Jerusalém, de geração em geração." },
{name:'29321',l:'29',c:'3',v:'21',texto:"E purificarei o sangue dos que eu não tinha purificado, porque o SENHOR habitará em Sião." },
],
numVersiculos: 21,
},


};
