BibliaJFA.amos = {
	libro: "Amós",
	numCapitulos: 9,

c1: {
versiculos:[
{name:'3011',l:'30',c:'1',v:'1',texto:"As palavras de Amós, que estava entre os pastores de Tecoa, o que ele viu a respeito de Israel, nos dias de Uzias, rei de Judá, e nos dias de Jeroboão, filho de Joás, rei de Israel, dois anos antes do terremoto." },
{name:'3012',l:'30',c:'1',v:'2',texto:"E disse: O SENHOR bramará de Sião e de Jerusalém dará a sua voz; nas habitações dos pastores haverá pranto, e secar-se-á o cume do Carmelo." },
{name:'3013',l:'30',c:'1',v:'3',texto:"Assim diz o SENHOR: Por três transgressões de Damasco e por quatro, não retirarei o castigo, porque trilharam a Gileade com trilhos de ferro." },
{name:'3014',l:'30',c:'1',v:'4',texto:"Por isso, porei fogo à casa de Hazael, e ele consumirá os palácios de Ben-Hadade." },
{name:'3015',l:'30',c:'1',v:'5',texto:"E quebrarei o ferrolho de Damasco e exterminarei o morador de Biqueate-Áven e ao que tem o cetro de Bete-Éden; e o povo da Síria será levado em cativeiro a Quir, diz o SENHOR." },
{name:'3016',l:'30',c:'1',v:'6',texto:"Assim diz o SENHOR: Por três transgressões de Gaza e por quatro, não retirarei o castigo, porque levaram em cativeiro todos os cativos para os entregarem a Edom." },
{name:'3017',l:'30',c:'1',v:'7',texto:"Por isso porei fogo ao muro de Gaza, e ele consumirá os seus palácios." },
{name:'3018',l:'30',c:'1',v:'8',texto:"E exterminarei o morador de Asdode e o que tem o cetro de Asquelom e tornarei a minha mão contra Ecrom; e o resto dos filisteus perecerá, diz o Senhor JEOVÁ." },
{name:'3019',l:'30',c:'1',v:'9',texto:"Assim diz o SENHOR: Por três transgressões de Tiro e por quatro, não retirarei o castigo, porque entregaram todos os cativos a Edom e não se lembraram da aliança dos irmãos." },
{name:'30110',l:'30',c:'1',v:'10',texto:"Por isso, porei fogo ao muro de Tiro, e ele consumirá os seus palácios." },
{name:'30111',l:'30',c:'1',v:'11',texto:"Assim diz o SENHOR: Por três transgressões de Edom e por quatro, não retirarei o castigo, porque perseguiu a seu irmão à espada e baniu toda a misericórdia; e a sua ira despedaça eternamente, e retém a sua indignação para sempre." },
{name:'30112',l:'30',c:'1',v:'12',texto:"Por isso, porei fogo a Temã, e ele consumirá os palácios de Bozra." },
{name:'30113',l:'30',c:'1',v:'13',texto:"Assim diz o SENHOR: Por três transgressões dos filhos de Amom e por quatro, não retirarei o castigo, porque fenderam as grávidas de Gileade, para dilatarem os seus termos." },
{name:'30114',l:'30',c:'1',v:'14',texto:"Por isso, porei fogo ao muro de Rabá, e ele consumirá os seus palácios, com alarido no dia da batalha, com tempestade no dia da tormenta." },
{name:'30115',l:'30',c:'1',v:'15',texto:"E o seu rei irá para o cativeiro, ele e os seus príncipes juntamente, diz o SENHOR." },
],
numVersiculos: 15,
},

c2: {
versiculos:[
{name:'3021',l:'30',c:'2',v:'1',texto:"Assim diz o SENHOR: Por três transgressões de Moabe e por quatro, não retirarei o castigo, porque queimou os ossos do rei de Edom, até os reduzir a cal." },
{name:'3022',l:'30',c:'2',v:'2',texto:"Por isso, porei fogo a Moabe, e ele consumirá os palácios de Queriote; e Moabe morrerá com grande estrondo, com alarido, com som de buzina." },
{name:'3023',l:'30',c:'2',v:'3',texto:"E tirarei o juiz do meio dele e a todos os seus príncipes com ele matarei, diz o SENHOR." },
{name:'3024',l:'30',c:'2',v:'4',texto:"Assim diz o SENHOR: Por três transgressões de Judá e por quatro, não retirarei o castigo, porque rejeitaram a lei do SENHOR e não guardaram os seus estatutos; antes, se deixaram enganar por suas próprias mentiras, após as quais andaram seus pais." },
{name:'3025',l:'30',c:'2',v:'5',texto:"Por isso, porei fogo a Judá, e ele consumirá os palácios de Jerusalém." },
{name:'3026',l:'30',c:'2',v:'6',texto:"Assim diz o SENHOR: Por três transgressões de Israel e por quatro, não retirarei o castigo, porque vendem o justo por dinheiro e o necessitado por um par de sapatos." },
{name:'3027',l:'30',c:'2',v:'7',texto:"Suspirando pelo pó da terra sobre a cabeça dos pobres, eles pervertem o caminho dos mansos; e um homem e seu pai entram à mesma moça, para profanarem o meu santo nome." },
{name:'3028',l:'30',c:'2',v:'8',texto:"E se deitam junto a qualquer altar sobre roupas empenhadas e na casa de seus deuses bebem o vinho dos que tinham multado." },
{name:'3029',l:'30',c:'2',v:'9',texto:"Não obstante eu ter destruído o amorreu diante deles, a altura do qual era como a altura dos cedros, e cuja força era como a dos carvalhos; mas destruí o seu fruto por cima e as suas raízes por baixo." },
{name:'30210',l:'30',c:'2',v:'10',texto:"Também vos fiz subir da terra do Egito e quarenta anos vos guiei no deserto, para que possuísseis a terra do amorreu." },
{name:'30211',l:'30',c:'2',v:'11',texto:"E dentre vossos filhos levantei profetas e dentre os vossos jovens, nazireus. Não é isso assim, filhos de Israel? Diz o SENHOR." },
{name:'30212',l:'30',c:'2',v:'12',texto:"Mas vós aos nazireus destes vinho a beber e aos profetas ordenastes, dizendo: Não profetizeis." },
{name:'30213',l:'30',c:'2',v:'13',texto:"Eis que eu vos apertarei no vosso lugar como se aperta um carro cheio de manolhos." },
{name:'30214',l:'30',c:'2',v:'14',texto:"Assim que de nada valerá a fuga ao ágil; nem o forte corroborará a sua força, nem o valente livrará a sua vida." },
{name:'30215',l:'30',c:'2',v:'15',texto:"E não ficará em pé o que leva o arco, nem o ligeiro de pés se livrará, nem tampouco o que vai montado a cavalo livrará a sua alma." },
{name:'30216',l:'30',c:'2',v:'16',texto:"E o mais animoso entre os valentes fugirá nu naquele dia, disse o SENHOR." },
],
numVersiculos: 16,
},

c3: {
versiculos:[
{name:'3031',l:'30',c:'3',v:'1',texto:"Ouvi esta palavra que o SENHOR fala contra vós, filhos de Israel, contra toda a geração que fiz subir da terra do Egito, dizendo:" },
{name:'3032',l:'30',c:'3',v:'2',texto:"De todas as famílias da terra a vós somente conheci; portanto, todas as vossas injustiças visitarei sobre vós." },
{name:'3033',l:'30',c:'3',v:'3',texto:"Andarão dois juntos, se não estiverem de acordo?" },
{name:'3034',l:'30',c:'3',v:'4',texto:"Bramirá o leão no bosque, sem que tenha presa? Levantará o leãozinho no covil a sua voz, se nada tiver apanhado?" },
{name:'3035',l:'30',c:'3',v:'5',texto:"Cairá a ave no laço em terra, se não houver laço para ela? Levantar-se-á o laço da terra, sem que tenha apanhado alguma coisa?" },
{name:'3036',l:'30',c:'3',v:'6',texto:"Tocar-se-á a buzina na cidade, e o povo não estremecerá? Sucederá qualquer mal à cidade, e o SENHOR não o terá feito?" },
{name:'3037',l:'30',c:'3',v:'7',texto:"Certamente o Senhor JEOVÁ não fará coisa alguma, sem ter revelado o seu segredo aos seus servos, os profetas." },
{name:'3038',l:'30',c:'3',v:'8',texto:"Bramiu o leão, quem não temerá? Falou o Senhor JEOVÁ, quem não profetizará?" },
{name:'3039',l:'30',c:'3',v:'9',texto:"Fazei ouvir isto nos palácios de Asdode e nos palácios da terra do Egito e dizei: Ajuntai-vos sobre os montes de Samaria e vede os grandes alvoroços no meio dela e os oprimidos dentro dela." },
{name:'30310',l:'30',c:'3',v:'10',texto:"Porque não sabem fazer o que é reto, diz o SENHOR, entesourando nos seus palácios a violência e a destruição." },
{name:'30311',l:'30',c:'3',v:'11',texto:"Portanto, o Senhor JEOVÁ diz assim: Um inimigo surgirá, e cercará a tua terra, e derribará a tua fortaleza, e os teus palácios serão saqueados." },
{name:'30312',l:'30',c:'3',v:'12',texto:"Assim diz o SENHOR: Como o pastor livra da boca do leão as duas pernas ou um pedacinho da orelha, assim serão livrados os filhos de Israel que habitam em Samaria, no canto da liteira e na barra do leito." },
{name:'30313',l:'30',c:'3',v:'13',texto:"Ouvi e protestai contra a casa de Jacó, diz o Senhor JEOVÁ, o Deus dos Exércitos:" },
{name:'30314',l:'30',c:'3',v:'14',texto:"No dia em que eu visitar as transgressões de Israel sobre ele, também visitarei os altares de Betel; e os chifres do altar serão cortados e cairão por terra." },
{name:'30315',l:'30',c:'3',v:'15',texto:"E derribarei a casa de inverno com a casa de verão; e as casas de marfim perecerão, e as grandes casas terão fim, diz o SENHOR." },
],
numVersiculos: 15,
},

c4: {
versiculos:[
{name:'3041',l:'30',c:'4',v:'1',texto:"Ouvi esta palavra, vós, vacas de Basã, que estais no monte de Samaria, que oprimis os pobres, que quebrantais os necessitados, que dizeis a seus senhores: Dai cá, e bebamos." },
{name:'3042',l:'30',c:'4',v:'2',texto:"Jurou o Senhor JEOVÁ, pela sua santidade, que dias estão para vir sobre vós, em que vos levarão com anzóis e a vossos descendentes com anzóis de pesca." },
{name:'3043',l:'30',c:'4',v:'3',texto:"E saireis pelas brechas, uma após outra, e vos lançareis para Hermom, disse o SENHOR." },
{name:'3044',l:'30',c:'4',v:'4',texto:"Vinde a Betel e transgredi; a Gilgal, e multiplicai as transgressões; e, cada manhã, trazei os vossos sacrifícios e, de três em três dias, os vossos dízimos." },
{name:'3045',l:'30',c:'4',v:'5',texto:"E oferecei sacrifício de louvores do que é levedado, e apregoai sacrifícios voluntários, e publicai-os; porque disso gostais, ó filhos de Israel, disse o Senhor JEOVÁ." },
{name:'3046',l:'30',c:'4',v:'6',texto:"Por isso, também vos dei limpeza de dentes em todas as vossas cidades e falta de pão em todos os vossos lugares; contudo, não vos convertestes a mim, disse o SENHOR." },
{name:'3047',l:'30',c:'4',v:'7',texto:"Além disso, retive de vós a chuva, faltando ainda três meses para a ceifa; e fiz chover sobre uma cidade e sobre outra cidade não fiz chover; sobre um campo choveu, mas o outro, sobre o qual não choveu, se secou." },
{name:'3048',l:'30',c:'4',v:'8',texto:"E andaram errantes duas ou três cidades, indo a outra cidade, para beberem água, mas não se saciaram; contudo, não vos convertestes a mim, disse o SENHOR." },
{name:'3049',l:'30',c:'4',v:'9',texto:"Feri-vos com queimadura e com ferrugem; a multidão das vossas hortas, e das vossas vinhas, e das vossas figueiras, e das vossas oliveiras foi comida pela locusta; contudo, não vos convertestes a mim, disse o SENHOR." },
{name:'30410',l:'30',c:'4',v:'10',texto:"Enviei a peste contra vós, à maneira do Egito; os vossos jovens matei à espada, e os vossos cavalos deixei levar presos, e o fedor dos vossos exércitos fiz subir ao vosso nariz; contudo, não vos convertestes a mim, disse o SENHOR." },
{name:'30411',l:'30',c:'4',v:'11',texto:"Subverti alguns dentre vós, como Deus subverteu a Sodoma e Gomorra, e vós fostes como um tição arrebatado do incêndio; contudo, não vos convertestes a mim, disse o SENHOR." },
{name:'30412',l:'30',c:'4',v:'12',texto:"Portanto, assim te farei, ó Israel! E, porque isso te farei, prepara-te, ó Israel, para te encontrares com o teu Deus." },
{name:'30413',l:'30',c:'4',v:'13',texto:"Porque é ele o que forma os montes, e cria o vento, e declara ao homem qual é o seu pensamento, o que faz da manhã trevas e pisa os altos da terra; SENHOR, o Deus dos Exércitos, é o seu nome." },
],
numVersiculos: 13,
},

c5: {
versiculos:[
{name:'3051',l:'30',c:'5',v:'1',texto:"Ouvi esta palavra que levanto como uma lamentação sobre vós, ó casa de Israel." },
{name:'3052',l:'30',c:'5',v:'2',texto:"A virgem de Israel caiu, nunca mais tornará a levantar-se; desamparada está na sua terra, não há quem a levante." },
{name:'3053',l:'30',c:'5',v:'3',texto:"Porque assim diz o Senhor JEOVÁ: A cidade da qual saem mil conservará cem, e aquela da qual saem cem conservará dez à casa de Israel." },
{name:'3054',l:'30',c:'5',v:'4',texto:"Porque assim diz o SENHOR à casa de Israel: Buscai-me e vivei." },
{name:'3055',l:'30',c:'5',v:'5',texto:"Mas não busqueis a Betel, nem venhais a Gilgal, nem passeis a Berseba, porque Gilgal certamente será levado cativo, e Betel será desfeito em nada." },
{name:'3056',l:'30',c:'5',v:'6',texto:"Buscai o SENHOR e vivei, para que não se lance na casa de José como um fogo, e a consuma, e não haja em Betel quem o apague." },
{name:'3057',l:'30',c:'5',v:'7',texto:"Vós que converteis o juízo em alosna e deitais por terra a justiça," },
{name:'3058',l:'30',c:'5',v:'8',texto:"procurai o que faz o Sete-estrelo e o Órion, e torna a sombra da noite em manhã, e escurece o dia como a noite; o que chama as águas do mar e as derrama sobre a terra; SENHOR é o seu nome." },
{name:'3059',l:'30',c:'5',v:'9',texto:"O que faz vir súbita destruição sobre o forte, de sorte que vem a assolação contra a fortaleza." },
{name:'30510',l:'30',c:'5',v:'10',texto:"Aborrecem na porta ao que os repreende e abominam o que fala sinceramente." },
{name:'30511',l:'30',c:'5',v:'11',texto:"Portanto, visto que pisais o pobre e dele exigis um tributo de trigo, edificareis casas de pedras lavradas, mas nelas não habitareis; vinhas desejáveis plantareis, mas não bebereis do seu vinho." },
{name:'30512',l:'30',c:'5',v:'12',texto:"Porque sei que são muitas as vossas transgressões e enormes os vossos pecados; afligis o justo, tomais resgate e rejeitais os necessitados na porta." },
{name:'30513',l:'30',c:'5',v:'13',texto:"Portanto, o que for prudente guardará silêncio naquele tempo, porque o tempo será mau." },
{name:'30514',l:'30',c:'5',v:'14',texto:"Buscai o bem e não o mal, para que vivais; e assim o SENHOR, o Deus dos Exércitos, estará convosco, como dizeis." },
{name:'30515',l:'30',c:'5',v:'15',texto:"Aborrecei o mal, e amai o bem, e estabelecei o juízo na porta; talvez o SENHOR, o Deus dos Exércitos, tenha piedade do resto de José." },
{name:'30516',l:'30',c:'5',v:'16',texto:"Portanto, assim diz o SENHOR, Deus dos Exércitos, o Senhor: Em todas as ruas haverá pranto, e em todos os bairros dirão: Ai! Ai! E ao lavrador chamarão para choro e para pranto os que souberem prantear." },
{name:'30517',l:'30',c:'5',v:'17',texto:"E em todas as vinhas haverá pranto; porque passarei pelo meio de ti, diz o SENHOR." },
{name:'30518',l:'30',c:'5',v:'18',texto:"Ai daqueles que desejam o dia do SENHOR! Para que quereis vós este dia do SENHOR? Trevas será e não luz." },
{name:'30519',l:'30',c:'5',v:'19',texto:"Como se um homem fugisse de diante do leão, e se encontrasse com ele o urso ou como se, entrando em uma casa, a sua mão encostasse à parede, e fosse mordido por uma cobra." },
{name:'30520',l:'30',c:'5',v:'20',texto:"Não será, pois, o dia do SENHOR trevas e não luz? Não será completa escuridade sem nenhum resplendor?" },
{name:'30521',l:'30',c:'5',v:'21',texto:"Aborreço, desprezo as vossas festas, e as vossas assembléias solenes não me dão nenhum prazer." },
{name:'30522',l:'30',c:'5',v:'22',texto:"E, ainda que me ofereçais holocaustos e ofertas de manjares, não me agradarei delas, nem atentarei para as ofertas pacíficas de vossos animais gordos." },
{name:'30523',l:'30',c:'5',v:'23',texto:"Afasta de mim o estrépito dos teus cânticos; porque não ouvirei as melodias dos teus instrumentos." },
{name:'30524',l:'30',c:'5',v:'24',texto:"Corra, porém, o juízo como as águas, e a justiça, como o ribeiro impetuoso." },
{name:'30525',l:'30',c:'5',v:'25',texto:"Oferecestes-me vós sacrifícios e oblações no deserto por quarenta anos, ó casa de Israel?" },
{name:'30526',l:'30',c:'5',v:'26',texto:"Antes, levastes a tenda de vosso Moloque, e o altar das vossas imagens, e a estrela do vosso deus, que fizestes para vós mesmos." },
{name:'30527',l:'30',c:'5',v:'27',texto:"Portanto, vos levarei cativos, para além de Damasco, diz o SENHOR, cujo nome é Deus dos Exércitos." },
],
numVersiculos: 27,
},

c6: {
versiculos:[
{name:'3061',l:'30',c:'6',v:'1',texto:"Ai dos que repousam em Sião e dos que estão seguros no monte de Samaria; que têm nome entre as primeiras nações, e aos quais vem a casa de Israel!" },
{name:'3062',l:'30',c:'6',v:'2',texto:"Passai a Calné e vede; e dali ide à grande Hamate; depois descei a Gate dos filisteus; serão melhores que estes reinos? Ou será maior o seu termo do que o vosso termo?" },
{name:'3063',l:'30',c:'6',v:'3',texto:"Vós que dilatais o dia mau e vos chegais ao lugar de violência;" },
{name:'3064',l:'30',c:'6',v:'4',texto:"que dormis em camas de marfim, e vos estendeis sobre os vossos leitos, e comeis os cordeiros do rebanho e os bezerros do meio da manada;" },
{name:'3065',l:'30',c:'6',v:'5',texto:"que cantais ao som do alaúde e inventais para vós instrumentos músicos, como Davi;" },
{name:'3066',l:'30',c:'6',v:'6',texto:"que bebeis vinho em taças e vos ungis com o mais excelente óleo, mas não vos afligis pela quebra de José:" },
{name:'3067',l:'30',c:'6',v:'7',texto:"eis que, agora, ireis em cativeiro entre os primeiros que forem cativos, e cessarão os festins dos regalados." },
{name:'3068',l:'30',c:'6',v:'8',texto:"Jurou o Senhor JEOVÁ pela sua alma, o SENHOR, Deus dos Exércitos: Tenho abominação pela soberba de Jacó e aborreço os seus palácios; e entregarei a cidade e tudo o que nela há." },
{name:'3069',l:'30',c:'6',v:'9',texto:"E acontecerá que, ficando de resto dez homens em uma casa, morrerão." },
{name:'30610',l:'30',c:'6',v:'10',texto:"E a alguém tomará o seu tio ou o que o queima, para levar os ossos para fora da casa; e dirá ao que estiver nos cantos da casa: Está ainda alguém contigo? E ele dirá: Ninguém. E dirá este: Cala-te, porque não podemos fazer menção do nome do SENHOR." },
{name:'30611',l:'30',c:'6',v:'11',texto:"Porque eis que o SENHOR manda, e será ferida a casa grande de quebraduras, e a casa pequena, de fendas." },
{name:'30612',l:'30',c:'6',v:'12',texto:"Poderão correr cavalos na rocha? Poderão lavrá-la com bois? Por que haveis vós tornado o juízo em fel e o fruto da justiça em alosna?" },
{name:'30613',l:'30',c:'6',v:'13',texto:"Vós que vos alegrais de nada, vós que dizeis: Não nos temos nós tornado poderosos por nossa força?" },
{name:'30614',l:'30',c:'6',v:'14',texto:"Porque eis que eu levantarei sobre vós, ó casa de Israel, um povo, diz o SENHOR, Deus dos Exércitos, e oprimir-vos-á, desde a entrada de Hamate até ao ribeiro da planície." },
],
numVersiculos: 14,
},

c7: {
versiculos:[
{name:'3071',l:'30',c:'7',v:'1',texto:"O Senhor JEOVÁ assim me fez ver: eis que ele formava gafanhotos no princípio do rebento da erva serôdia, e eis que era a erva serôdia depois da segada do rei." },
{name:'3072',l:'30',c:'7',v:'2',texto:"E aconteceu que, como eles tivessem comido completamente a erva da terra, eu disse: Senhor JEOVÁ, perdoa; como se levantará agora Jacó? Pois ele é pequeno." },
{name:'3073',l:'30',c:'7',v:'3',texto:"Então, o SENHOR se arrependeu disso. Não acontecerá, disse o SENHOR." },
{name:'3074',l:'30',c:'7',v:'4',texto:"Assim me mostrou o Senhor JEOVÁ: eis que o Senhor JEOVÁ clamava que queria contender por meio do fogo; e consumiu o grande abismo e também queria consumir a terra." },
{name:'3075',l:'30',c:'7',v:'5',texto:"Então, eu disse: Senhor JEOVÁ, cessa agora; como se levantará Jacó? Pois ele é pequeno." },
{name:'3076',l:'30',c:'7',v:'6',texto:"E o SENHOR se arrependeu disso. Nem isso acontecerá, disse o Senhor JEOVÁ." },
{name:'3077',l:'30',c:'7',v:'7',texto:"Mostrou-me também assim: eis que o Senhor estava sobre um muro levantado a prumo; e tinha um prumo na sua mão." },
{name:'3078',l:'30',c:'7',v:'8',texto:"E o SENHOR me disse: Que vês tu, Amós? E eu disse: Um prumo. Então, disse o Senhor: Eis que eu porei o prumo no meio do meu povo Israel; nunca mais passarei por ele." },
{name:'3079',l:'30',c:'7',v:'9',texto:"Mas os altos de Isaque serão assolados, e destruídos os santuários de Israel; e levantar-me-ei com a espada contra a casa de Jeroboão." },
{name:'30710',l:'30',c:'7',v:'10',texto:"Então, Amazias, o sacerdote de Betel, mandou dizer a Jeroboão, rei de Israel: Amós tem conspirado contra ti, no meio da casa de Israel; a terra não poderá sofrer todas as suas palavras." },
{name:'30711',l:'30',c:'7',v:'11',texto:"Porque assim diz Amós: Jeroboão morrerá à espada, e Israel certamente será levado para fora da sua terra em cativeiro." },
{name:'30712',l:'30',c:'7',v:'12',texto:"Depois, Amazias disse a Amós: Vai-te, ó vidente, foge para a terra de Judá, e ali come o pão, e ali profetiza;" },
{name:'30713',l:'30',c:'7',v:'13',texto:"mas, em Betel, daqui por diante, não profetizarás mais, porque é o santuário do rei e a casa do reino." },
{name:'30714',l:'30',c:'7',v:'14',texto:"E respondeu Amós e disse a Amazias: Eu não era profeta, nem filho de profeta, mas boieiro e cultivador de sicômoros." },
{name:'30715',l:'30',c:'7',v:'15',texto:"Mas o SENHOR me tirou de após o gado e o SENHOR me disse: Vai e profetiza ao meu povo Israel." },
{name:'30716',l:'30',c:'7',v:'16',texto:"Ora, pois, ouve a palavra do SENHOR. Tu dizes: Não profetizarás contra Israel, nem falarás contra a casa de Isaque." },
{name:'30717',l:'30',c:'7',v:'17',texto:"Portanto, assim diz o SENHOR: Tua mulher se prostituirá na cidade, e teus filhos e tuas filhas cairão à espada, e a tua terra será repartida a cordel, e tu morrerás na terra imunda, e Israel certamente será levado cativo para fora da sua terra." },
],
numVersiculos: 17,
},

c8: {
versiculos:[
{name:'3081',l:'30',c:'8',v:'1',texto:"O Senhor JEOVÁ assim me fez ver: e eis aqui um cesto de frutos do verão." },
{name:'3082',l:'30',c:'8',v:'2',texto:"E disse: Que vês, Amós? E eu disse: Um cesto de frutos do verão. Então, o SENHOR me disse: Chegou o fim sobre o meu povo Israel; daqui por diante nunca mais passarei por ele." },
{name:'3083',l:'30',c:'8',v:'3',texto:"Mas os cânticos do templo serão ouvidos naquele dia, diz o Senhor JEOVÁ; multiplicar-se-ão os cadáveres; em todos os lugares serão lançados fora em silêncio." },
{name:'3084',l:'30',c:'8',v:'4',texto:"Ouvi isto, vós que anelais o abatimento do necessitado e destruís os miseráveis da terra," },
{name:'3085',l:'30',c:'8',v:'5',texto:"dizendo: Quando passará a lua nova, para vendermos o grão? E o sábado, para abrirmos os celeiros de trigo, diminuindo o efa, e aumentando o siclo, e procedendo dolosamente com balanças enganadoras," },
{name:'3086',l:'30',c:'8',v:'6',texto:"para comprarmos os pobres por dinheiro e os necessitados por um par de sapatos? E, depois, venderemos as cascas do trigo." },
{name:'3087',l:'30',c:'8',v:'7',texto:"Jurou o SENHOR pela glória de Jacó: Eu não me esquecerei de todas as suas obras para sempre!" },
{name:'3088',l:'30',c:'8',v:'8',texto:"Por causa disso, não se comoverá a terra? E não chorará todo aquele que habita nela? Certamente, levantar-se-á toda como o grande rio, e será arrojada, e se submergirá como o rio do Egito." },
{name:'3089',l:'30',c:'8',v:'9',texto:"E sucederá que, naquele dia, diz o SENHOR, farei que o sol se ponha ao meio-dia e a terra se entenebreça em dia de luz." },
{name:'30810',l:'30',c:'8',v:'10',texto:"E tornarei as vossas festas em luto e todos os vossos cânticos em lamentações, e aparecerá pano de saco sobre todos os lombos e calva sobre toda cabeça; e farei que isso seja como luto de filho único e o seu fim como dia de amarguras." },
{name:'30811',l:'30',c:'8',v:'11',texto:"Eis que vêm dias, diz o Senhor JEOVÁ, em que enviarei fome sobre a terra, não fome de pão, nem sede de água, mas de ouvir as palavras do SENHOR." },
{name:'30812',l:'30',c:'8',v:'12',texto:"E irão errantes de um mar até outro mar e do Norte até ao Oriente; correrão por toda parte, buscando a palavra do SENHOR, e não a acharão." },
{name:'30813',l:'30',c:'8',v:'13',texto:"Naquele dia, as virgens formosas e os jovens desmaiarão de sede." },
{name:'30814',l:'30',c:'8',v:'14',texto:"Os que juram pelo delito de Samaria, dizendo: Como é certo viver o teu deus, ó Dã; e: Como é certo viver o caminho de Berseba; esses mesmos cairão e não se levantarão mais." },
],
numVersiculos: 14,
},

c9: {
versiculos:[
{name:'3091',l:'30',c:'9',v:'1',texto:"Vi o Senhor, que estava em pé sobre o altar, e me disse: Fere o capitel, e estremeçam os umbrais, e faze tudo em pedaços sobre a cabeça de todos eles; e eu matarei à espada até ao último deles; o que fugir dentre eles não escapará, nem o que escapar dentre eles se salvará." },
{name:'3092',l:'30',c:'9',v:'2',texto:"Ainda que cavem até ao inferno, a minha mão os tirará dali; e, se subirem ao céu, dali os farei descer." },
{name:'3093',l:'30',c:'9',v:'3',texto:"E, se se esconderem no cume do Carmelo, buscá-los-ei e dali os tirarei; e, se se ocultarem aos meus olhos no fundo do mar, ali darei ordem à serpente, e ela os morderá." },
{name:'3094',l:'30',c:'9',v:'4',texto:"E, se forem para o cativeiro diante de seus inimigos, ali darei ordem à espada para que os mate; e eu porei os meus olhos sobre eles para mal e não para bem." },
{name:'3095',l:'30',c:'9',v:'5',texto:"Porque o Senhor, o SENHOR dos Exércitos, é o que toca a terra, e ela se derrete, e todos os que habitam nela chorarão; e ela subirá toda como o grande rio e se submergirá como o Egito." },
{name:'3096',l:'30',c:'9',v:'6',texto:"Ele é o que edifica as suas câmaras no céu, e a sua abóbada fundou na terra, e o que chama as águas do mar, e as derrama sobre a terra; o SENHOR é o seu nome." },
{name:'3097',l:'30',c:'9',v:'7',texto:"Não sois vós para mim, ó filhos de Israel, como os filhos dos etíopes? Diz o SENHOR. Não fiz eu subir a Israel da terra do Egito, e aos filisteus, de Caftor, e aos siros, de Quir?" },
{name:'3098',l:'30',c:'9',v:'8',texto:"Eis que os olhos do Senhor JEOVÁ estão contra este reino pecador, e eu o destruirei de sobre a face da terra; mas não destruirei de todo a casa de Jacó, diz o SENHOR." },
{name:'3099',l:'30',c:'9',v:'9',texto:"Porque eis que darei ordem e sacudirei a casa de Israel entre todas as nações, assim como se sacode grão no crivo, sem que caia na terra um só grão." },
{name:'30910',l:'30',c:'9',v:'10',texto:"Todos os pecadores do meu povo morrerão à espada, os quais dizem: Não se avizinhará nem nos encontrará o mal." },
{name:'30911',l:'30',c:'9',v:'11',texto:"Naquele dia, tornarei a levantar a tenda de Davi, que caiu, e taparei as suas aberturas, e tornarei a levantar as suas ruínas, e a edificarei como nos dias da antiguidade;" },
{name:'30912',l:'30',c:'9',v:'12',texto:"para que possuam o restante de Edom e todas as nações que são chamadas pelo meu nome, diz o SENHOR, que faz estas coisas." },
{name:'30913',l:'30',c:'9',v:'13',texto:"Eis que vêm dias, diz o SENHOR, em que o que lavra alcançará ao que sega, e o que pisa as uvas, ao que lança a semente; e os montes destilarão mosto, e todos os outeiros se derreterão." },
{name:'30914',l:'30',c:'9',v:'14',texto:"E removerei o cativeiro do meu povo Israel, e reedificarão as cidades assoladas, e nelas habitarão, e plantarão vinhas, e beberão o seu vinho, e farão pomares, e lhes comerão o fruto." },
{name:'30915',l:'30',c:'9',v:'15',texto:"E os plantarei na sua terra, e não serão mais arrancados da sua terra que lhes dei, diz o SENHOR, teu Deus." },
],
numVersiculos: 15,
},
	

};
