BibliaJFA.miqueas = {
	libro: "Miqueias",
	numCapitulos: 7,

c1: {
versiculos:[
{name:'3311',l:'33',c:'1',v:'1',texto:"Palavra do SENHOR que veio a Miquéias, morastita, nos dias de Jotão, Acaz e Ezequias, reis de Judá, a qual ele viu sobre Samaria e Jerusalém." },
{name:'3312',l:'33',c:'1',v:'2',texto:"Ouvi, todos os povos, presta atenção, ó terra, em tua plenitude, e seja o Senhor JEOVÁ testemunha contra vós, o Senhor, desde o templo da sua santidade." },
{name:'3313',l:'33',c:'1',v:'3',texto:"Porque eis que o SENHOR sai do seu lugar, e descerá, e andará sobre as alturas da terra." },
{name:'3314',l:'33',c:'1',v:'4',texto:"E os montes debaixo dele se derreterão, e os vales se fenderão, como a cera diante do fogo, como as águas que se precipitam em um abismo." },
{name:'3315',l:'33',c:'1',v:'5',texto:"Tudo isso por causa da prevaricação de Jacó e dos pecados da casa de Israel; qual é a transgressão de Jacó? Não é Samaria? E quais os altos de Judá? Não é Jerusalém?" },
{name:'3316',l:'33',c:'1',v:'6',texto:"Por isso, farei de Samaria um montão de pedras do campo, uma terra de plantar vinhas, e farei rebolar as suas pedras no vale, e descobrirei os seus fundamentos." },
{name:'3317',l:'33',c:'1',v:'7',texto:"E todas as suas imagens de escultura serão despedaçadas, e todos os seus salários serão queimados pelo fogo, e de todos os seus ídolos eu farei uma assolação, porque do preço de sua prostituição os ajuntou, e em recompensa de prostituta se volverão." },
{name:'3318',l:'33',c:'1',v:'8',texto:"Por isso, lamentarei, e uivarei, e andarei despojado e nu; farei lamentação como de dragões e pranto como de avestruzes." },
{name:'3319',l:'33',c:'1',v:'9',texto:"Porque a sua chaga é incurável, porque chegou até Judá; estendeu-se até à porta do meu povo, até Jerusalém." },
{name:'33110',l:'33',c:'1',v:'10',texto:"Não o anuncieis em Gate, nem choreis muito; revolve-te no pó, em Bete-Leafra." },
{name:'33111',l:'33',c:'1',v:'11',texto:"Passa, ó moradora de Safir, com nudez vergonhosa; a moradora de Zaanã não saiu; o pranto de Bete-Ezel receberá de vós a sua morada." },
{name:'33112',l:'33',c:'1',v:'12',texto:"Porque a moradora de Marote teve dor pelo bem; porque desceu do SENHOR o mal até à porta de Jerusalém." },
{name:'33113',l:'33',c:'1',v:'13',texto:"Ata os animais ligeiros ao carro, ó moradora de Laquis ( esta foi o princípio do pecado para a filha de Sião ), porque em ti se acharam as transgressões de Israel." },
{name:'33114',l:'33',c:'1',v:'14',texto:"Por isso, darás presentes a Moresete-Gate; as casas de Aczibe serão uma mentira para os reis de Israel." },
{name:'33115',l:'33',c:'1',v:'15',texto:"Ainda te trarei um herdeiro, ó moradora de Maressa; chegará até Adulão a glória de Israel." },
{name:'33116',l:'33',c:'1',v:'16',texto:"Faze-te calva e tosquia-te, por causa dos filhos das tuas delícias; alarga a tua calva como a águia, porque de ti foram levados para o cativeiro." },
],
numVersiculos: 16,
},

c2: {
versiculos:[
{name:'3321',l:'33',c:'2',v:'1',texto:"Ai daqueles que, nas suas camas, intentam a iniqüidade e maquinam o mal; à luz da alva o praticam, porque está no poder da sua mão!" },
{name:'3322',l:'33',c:'2',v:'2',texto:"E cobiçam campos, e os arrebatam, e casas, e as tomam; assim fazem violência a um homem e à sua casa, a uma pessoa e à sua herança." },
{name:'3323',l:'33',c:'2',v:'3',texto:"Portanto, assim diz o SENHOR: Eis que projeto um mal contra esta geração, do qual não tirareis os vossos pescoços; e não andareis tão altivos, porque o tempo será mau." },
{name:'3324',l:'33',c:'2',v:'4',texto:"Naquele dia, se levantará um provérbio sobre vós, e se levantará pranto lastimoso, dizendo: Nós estamos inteiramente desolados! A porção do meu povo, ele a troca! Como me despoja! Tira os nossos campos e os reparte!" },
{name:'3325',l:'33',c:'2',v:'5',texto:"Portanto, não terás tu na congregação do SENHOR quem lance o cordel pela sorte." },
{name:'3326',l:'33',c:'2',v:'6',texto:"Não profetizeis; os que profetizam, não profetizem deste modo, que se não apartará a vergonha." },
{name:'3327',l:'33',c:'2',v:'7',texto:"Ó vós que sois chamados a casa de Jacó, tem-se restringido o Espírito do SENHOR? São estas as suas obras? E não é assim que fazem bem as minhas palavras ao que anda retamente?" },
{name:'3328',l:'33',c:'2',v:'8',texto:"Mas há pouco se levantou o meu povo como um inimigo; de sobre a vestidura tirastes a capa daqueles que passavam seguros, como homens que voltavam da guerra." },
{name:'3329',l:'33',c:'2',v:'9',texto:"Lançastes fora as mulheres do meu povo, da casa das suas delícias; dos seus meninos tirastes o meu louvor para sempre." },
{name:'33210',l:'33',c:'2',v:'10',texto:"Levantai-vos e andai, porque não será aqui o vosso descanso; por causa da corrupção que destrói, sim, que destrói grandemente." },
{name:'33211',l:'33',c:'2',v:'11',texto:"Se houver algum que siga o seu espírito de falsidade, mentindo e dizendo: Eu te profetizarei acerca do vinho e da bebida forte; será esse tal o profeta deste povo." },
{name:'33212',l:'33',c:'2',v:'12',texto:"Certamente te ajuntarei todo inteiro, ó Jacó; certamente congregarei o restante de Israel; pô-los-ei todos juntos, como ovelhas de Bozra; como rebanho no meio do seu curral, farão estrondo por causa da multidão dos homens." },
{name:'33213',l:'33',c:'2',v:'13',texto:"Subirá diante deles o arroteador; eles romperão, e entrarão pela porta, e sairão por ela; e o rei irá adiante deles, e o SENHOR, à testa deles." },
],
numVersiculos: 13,
},

c3: {
versiculos:[
{name:'3331',l:'33',c:'3',v:'1',texto:"Mais disse eu: Ouvi agora vós, chefes de Jacó, e vós, príncipes da casa de Israel: não é a vós que pertence saber o direito?" },
{name:'3332',l:'33',c:'3',v:'2',texto:"A vós que aborreceis o bem e amais o mal, que arrancais a pele de cima deles e a sua carne de cima dos seus ossos," },
{name:'3333',l:'33',c:'3',v:'3',texto:"e que comeis a carne do meu povo, e lhes arrancais a pele, e lhes esmiuçais os ossos, e os repartis como para a panela e como carne do meio do caldeirão." },
{name:'3334',l:'33',c:'3',v:'4',texto:"Então, clamarão ao SENHOR, mas não os ouvirá, antes esconderá deles a sua face naquele tempo, visto que eles fizeram mal nas suas obras." },
{name:'3335',l:'33',c:'3',v:'5',texto:"Assim diz o SENHOR contra os profetas que fazem errar o meu povo, que mordem com os seus dentes e clamam: Paz! Mas contra aquele que nada lhes mete na boca preparam guerra." },
{name:'3336',l:'33',c:'3',v:'6',texto:"Portanto, se vos fará noite, para que não haja profecia, e haverá trevas, para que não haja adivinhação, e se porá o sol sobre esses profetas, e o dia sobre eles se enegrecerá." },
{name:'3337',l:'33',c:'3',v:'7',texto:"E os videntes se envergonharão, e os adivinhadores se confundirão, sim, todos eles cobrirão os seus lábios, porque não haverá resposta de Deus." },
{name:'3338',l:'33',c:'3',v:'8',texto:"Mas, decerto, eu sou cheio da força do Espírito do SENHOR e cheio de juízo e de ânimo, para anunciar a Jacó a sua transgressão e a Israel o seu pecado." },
{name:'3339',l:'33',c:'3',v:'9',texto:"Ouvi agora isto, vós, chefes da casa de Jacó, e vós, maiorais da casa de Israel, que abominais o juízo e perverteis tudo o que é direito," },
{name:'33310',l:'33',c:'3',v:'10',texto:"edificando a Sião com sangue e a Jerusalém com injustiça." },
{name:'33311',l:'33',c:'3',v:'11',texto:"Os seus chefes dão as sentenças por presentes, e os seus sacerdotes ensinam por interesse, e os seus profetas adivinham por dinheiro; e ainda se encostam ao SENHOR, dizendo: Não está o SENHOR no meio de nós? Nenhum mal nos sobrevirá." },
{name:'33312',l:'33',c:'3',v:'12',texto:"Portanto, por causa de vós, Sião será lavrado como um campo, e Jerusalém se tornará em montões de pedras, e o monte desta casa, em lugares altos de um bosque." },
],
numVersiculos: 12,
},

c4: {
versiculos:[
{name:'3341',l:'33',c:'4',v:'1',texto:"Mas, nos últimos dias, acontecerá que o monte da Casa do SENHOR será estabelecido no cume dos montes e se elevará sobre os outeiros, e concorrerão a ele os povos." },
{name:'3342',l:'33',c:'4',v:'2',texto:"E irão muitas nações e dirão: Vinde, e subamos ao monte do SENHOR e à Casa do Deus de Jacó, para que nos ensine os seus caminhos, e nós andemos pelas suas veredas; porque de Sião sairá a lei, e a palavra do SENHOR, de Jerusalém." },
{name:'3343',l:'33',c:'4',v:'3',texto:"E julgará entre muitos povos e castigará poderosas nações até mui longe; e converterão as suas espadas em enxadas e as suas lanças em foices; uma nação não levantará a espada contra outra nação, nem aprenderão mais a guerra." },
{name:'3344',l:'33',c:'4',v:'4',texto:"Mas assentar-se-á cada um debaixo da sua videira e debaixo da sua figueira, e não haverá quem os espante, porque a boca do SENHOR dos Exércitos o disse." },
{name:'3345',l:'33',c:'4',v:'5',texto:"Porque todos os povos andarão, cada um em nome do seu deus; mas nós andaremos no nome do SENHOR, nosso Deus, eternamente e para sempre." },
{name:'3346',l:'33',c:'4',v:'6',texto:"Naquele dia, diz o SENHOR, congregarei a que coxeava e recolherei a que eu tinha expulsado e a que eu tinha maltratado." },
{name:'3347',l:'33',c:'4',v:'7',texto:"E da que coxeava farei a parte restante, e da que tinha sido arrojada para longe, uma nação poderosa; e o SENHOR reinará sobre eles no monte Sião, desde agora e para sempre." },
{name:'3348',l:'33',c:'4',v:'8',texto:"E a ti, ó torre do rebanho, monte da filha de Sião, a ti virá; sim, a ti virá o primeiro domínio, o reino da filha de Jerusalém." },
{name:'3349',l:'33',c:'4',v:'9',texto:"E, agora, porque farás tão grande pranto? Não há em ti rei? Pereceu o teu conselheiro? Apoderou-se de ti dor, como da que está de parto?" },
{name:'33410',l:'33',c:'4',v:'10',texto:"Sofre dores e trabalhos, ó filha de Sião, como a que está de parto, porque agora sairás da cidade, e morarás no campo, e virás até Babilônia; ali, porém, serás livrada; ali te remirá o SENHOR da mão de teus inimigos." },
{name:'33411',l:'33',c:'4',v:'11',texto:"Agora, se congregaram muitas nações contra ti, que dizem: Seja profanada, e os nossos olhos verão seus desejos sobre Sião." },
{name:'33412',l:'33',c:'4',v:'12',texto:"Mas não sabem os pensamentos do SENHOR, nem entendem o seu conselho, porque as ajuntou como gavelas em uma eira." },
{name:'33413',l:'33',c:'4',v:'13',texto:"Levanta-te e trilha, ó filha de Sião; porque eu farei de ferro a tua ponta e de cobre, as tuas unhas, e esmiuçarás a muitos povos, e o seu ganho será consagrado ao SENHOR, e a sua fazenda, ao Senhor de toda a terra." },
],
numVersiculos: 13,
},

c5: {
versiculos:[
{name:'3351',l:'33',c:'5',v:'1',texto:"Agora, ajunta-te em esquadrões, ó filha de esquadrões; pôr-se-á cerco contra nós; ferirão com a vara no queixo ao juiz de Israel." },
{name:'3352',l:'33',c:'5',v:'2',texto:"E tu, Belém Efrata, posto que pequena entre milhares de Judá, de ti me sairá o que será Senhor em Israel, e cujas origens são desde os tempos antigos, desde os dias da eternidade." },
{name:'3353',l:'33',c:'5',v:'3',texto:"Portanto, os entregará até ao tempo em que a que está de parto tiver dado à luz; então, o resto de seus irmãos voltará com os filhos de Israel." },
{name:'3354',l:'33',c:'5',v:'4',texto:"E ele permanecerá e apascentará o povo na força do SENHOR, na excelência do nome do SENHOR, seu Deus; e eles permanecerão, porque agora será ele engrandecido até aos fins da terra." },
{name:'3355',l:'33',c:'5',v:'5',texto:"E este será a nossa paz. Quando a Assíria vier à nossa terra e quando passar sobre os nossos palácios, levantaremos contra ela sete pastores e oito príncipes dentre os homens." },
{name:'3356',l:'33',c:'5',v:'6',texto:"Esses consumirão a terra da Assíria à espada e a terra de Ninrode, nas suas entradas. Assim, nos livrará da Assíria, quando vier à nossa terra e quando calcar os nossos termos." },
{name:'3357',l:'33',c:'5',v:'7',texto:"E estará o resto de Jacó no meio de muitos povos, como orvalho do SENHOR, como chuvisco sobre a erva, que não espera pelo homem, nem aguarda filhos de homens." },
{name:'3358',l:'33',c:'5',v:'8',texto:"E o resto de Jacó estará entre as nações, no meio de muitos povos, como um leão entre os animais do bosque, como um leãozinho entre os rebanhos de ovelhas, o qual, quando passar, as pisará e despedaçará, sem que haja quem as livre." },
{name:'3359',l:'33',c:'5',v:'9',texto:"A tua mão se exaltará sobre os teus adversários; e todos os teus inimigos serão exterminados." },
{name:'33510',l:'33',c:'5',v:'10',texto:"E sucederá, naquele dia, diz o SENHOR, que eu exterminarei no meio de ti os teus cavalos e destruirei os teus carros;" },
{name:'33511',l:'33',c:'5',v:'11',texto:"e destruirei as cidades da tua terra e derribarei todas as tuas fortalezas;" },
{name:'33512',l:'33',c:'5',v:'12',texto:"e tirarei as feitiçarias da tua mão, e não terás agoureiros;" },
{name:'33513',l:'33',c:'5',v:'13',texto:"e arrancarei do meio de ti as tuas imagens de escultura e as tuas estátuas; e tu não te inclinarás mais diante da obra das tuas mãos." },
{name:'33514',l:'33',c:'5',v:'14',texto:"E arrancarei os teus bosques do meio de ti; e destruirei as tuas cidades." },
{name:'33515',l:'33',c:'5',v:'15',texto:"E, com ira e com furor, exercerei vingança sobre as nações que não ouvem." },
],
numVersiculos: 15,
},

c6: {
versiculos:[
{name:'3361',l:'33',c:'6',v:'1',texto:"Ouvi, agora, o que diz o SENHOR: Levanta-te, contende com os montes, e ouçam os outeiros a tua voz." },
{name:'3362',l:'33',c:'6',v:'2',texto:"Ouvi, montes, a contenda do SENHOR, e vós, fortes fundamentos da terra; porque o SENHOR tem uma contenda com o seu povo e com Israel entrará em juízo." },
{name:'3363',l:'33',c:'6',v:'3',texto:"Ó povo meu! Que te tenho feito? E em que te enfadei? Testifica contra mim." },
{name:'3364',l:'33',c:'6',v:'4',texto:"Certamente, te fiz subir da terra do Egito e da casa da servidão te remi; e pus diante de ti a Moisés, Arão e Miriã." },
{name:'3365',l:'33',c:'6',v:'5',texto:"Povo meu, ora, lembra-te da consulta de Balaque, rei de Moabe, e do que lhe respondeu Balaão, filho de Beor, desde Sitim até Gilgal; para que conheças as justiças do SENHOR." },
{name:'3366',l:'33',c:'6',v:'6',texto:"Com que me apresentarei ao SENHOR e me inclinarei ante o Deus Altíssimo? Virei perante ele com holocaustos, com bezerros de um ano?" },
{name:'3367',l:'33',c:'6',v:'7',texto:"Agradar-se-á o SENHOR de milhares de carneiros? De dez mil ribeiros de azeite? Darei o meu primogênito pela minha transgressão? O fruto do meu ventre, pelo pecado da minha alma?" },
{name:'3368',l:'33',c:'6',v:'8',texto:"Ele te declarou, ó homem, o que é bom; e que é o que o SENHOR pede de ti, senão que pratiques a justiça, e ames a beneficência, e andes humildemente com o teu Deus?" },
{name:'3369',l:'33',c:'6',v:'9',texto:"A voz do SENHOR clama à cidade, e o sábio verá o teu nome: Ouvi a vara e quem a ordenou." },
{name:'33610',l:'33',c:'6',v:'10',texto:"Ainda há na casa do ímpio tesouros de impiedade? E efa pequeno, que é detestável?" },
{name:'33611',l:'33',c:'6',v:'11',texto:"Seria eu limpo com balanças falsas? E com um saco de pesos enganosos?" },
{name:'33612',l:'33',c:'6',v:'12',texto:"Porque os seus ricos estão cheios de violência, e os seus habitantes falam mentiras; e a sua língua é enganosa na sua boca." },
{name:'33613',l:'33',c:'6',v:'13',texto:"Assim, eu também te enfraquecerei, ferindo-te e assolando-te por causa dos teus pecados." },
{name:'33614',l:'33',c:'6',v:'14',texto:"Tu comerás, mas não te fartarás; e a tua humilhação estará no meio de ti; removerás, mas não livrarás; e aquilo que livrares, eu o entregarei à espada." },
{name:'33615',l:'33',c:'6',v:'15',texto:"Tu semearás, mas não segarás; pisarás a azeitona, mas não te ungirás com azeite; e o mosto, mas não beberás vinho." },
{name:'33616',l:'33',c:'6',v:'16',texto:"Porque se observam os estatutos de Onri e toda a obra da casa de Acabe, e vós andais nos conselhos deles; para que eu faça de ti uma desolação e dos seus habitantes um assobio; assim, trareis sobre vós o opróbrio do meu povo." },
],
numVersiculos: 16,
},

c7: {
versiculos:[
{name:'3371',l:'33',c:'7',v:'1',texto:"Ai de mim! Porque estou como quando são colhidas as frutas do verão, como os rabiscos da vindima: não há cacho de uvas para comer, nem figos temporãos que a minha alma desejou." },
{name:'3372',l:'33',c:'7',v:'2',texto:"Pereceu o benigno da terra, e não há entre os homens um que seja reto; todos armam ciladas para sangue; caça cada um a seu irmão com uma rede." },
{name:'3373',l:'33',c:'7',v:'3',texto:"As suas mãos fazem diligentemente o mal; o príncipe inquire, e o juiz se apressa à recompensa, e o grande fala da corrupção da sua alma, e assim todos eles são perturbadores." },
{name:'3374',l:'33',c:'7',v:'4',texto:"O melhor deles é como um espinho; o mais reto é pior do que o espinhal; veio o dia dos teus vigias, veio a tua visitação; agora será a sua confusão." },
{name:'3375',l:'33',c:'7',v:'5',texto:"Não creiais no amigo, nem confieis no vosso guia; daquela que repousa no teu seio guarda as portas da tua boca." },
{name:'3376',l:'33',c:'7',v:'6',texto:"Porque o filho despreza o pai, a filha se levanta contra sua mãe, a nora, contra sua sogra, os inimigos do homem são os da sua própria casa." },
{name:'3377',l:'33',c:'7',v:'7',texto:"Eu, porém, esperarei no SENHOR; esperei no Deus da minha salvação; o meu Deus me ouvirá." },
{name:'3378',l:'33',c:'7',v:'8',texto:"Ó inimiga minha, não te alegres a meu respeito; ainda que eu tenha caído, levantar-me-ei; se morar nas trevas, o SENHOR será a minha luz." },
{name:'3379',l:'33',c:'7',v:'9',texto:"Sofrerei a ira do SENHOR, porque pequei contra ele, até que julgue a minha causa e execute o meu direito; ele me trará à luz, e eu verei a sua justiça." },
{name:'33710',l:'33',c:'7',v:'10',texto:"E a minha inimiga verá isso, e cobri-la-á a confusão, a ela que me diz: Onde está o SENHOR, teu Deus? Os meus olhos a verão sendo pisada como a lama das ruas." },
{name:'33711',l:'33',c:'7',v:'11',texto:"No dia em que reedificar os teus muros, nesse dia, longe estará ainda o estatuto." },
{name:'33712',l:'33',c:'7',v:'12',texto:"Naquele dia, virão a ti, desde a Assíria até às cidades fortes, e das fortalezas até ao rio, e do mar até ao mar, e da montanha até à montanha." },
{name:'33713',l:'33',c:'7',v:'13',texto:"Mas esta terra será posta em desolação, por causa dos seus moradores, por causa do fruto das suas obras." },
{name:'33714',l:'33',c:'7',v:'14',texto:"Apascenta o teu povo com a tua vara, o rebanho da tua herança, que mora só no bosque, no meio da terra fértil; apascentem-se em Basã e Gileade, como nos dias da antiguidade." },
{name:'33715',l:'33',c:'7',v:'15',texto:"Eu lhes mostrarei maravilhas, como nos dias da tua saída da terra do Egito." },
{name:'33716',l:'33',c:'7',v:'16',texto:"As nações o verão e envergonhar-se-ão, por causa de todo o seu poder; porão a mão sobre a boca, e os seus ouvidos ficarão surdos." },
{name:'33717',l:'33',c:'7',v:'17',texto:"Lamberão o pó como serpentes; como uns répteis da terra, tremendo, sairão dos seus encerramentos; com pavor virão ao SENHOR, nosso Deus, e terão medo de ti." },
{name:'33718',l:'33',c:'7',v:'18',texto:"Quem, ó Deus, é semelhante a ti, que perdoas a iniqüidade e que te esqueces da rebelião do restante da tua herança? O SENHOR não retém a sua ira para sempre, porque tem prazer na benignidade." },
{name:'33719',l:'33',c:'7',v:'19',texto:"Tornará a apiedar-se de nós, subjugará as nossas iniqüidades e lançará todos os nossos pecados nas profundezas do mar." },
{name:'33720',l:'33',c:'7',v:'20',texto:"Darás a Jacó a fidelidade e a Abraão, a benignidade que juraste a nossos pais, desde os dias antigos." },
],
numVersiculos: 20,
},


};
