BibliaJFA.habacuc = {
	libro: "Habacuque",
	numCapitulos: 3,

c1: {
versiculos:[
{name:'3511',l:'35',c:'1',v:'1',texto:"O peso que viu o profeta Habacuque." },
{name:'3512',l:'35',c:'1',v:'2',texto:"Até quando, SENHOR, clamarei eu, e tu não me escutarás? Gritarei: Violência! E não salvarás?" },
{name:'3513',l:'35',c:'1',v:'3',texto:"Por que razão me fazes ver a iniqüidade e ver a vexação? Porque a destruição e a violência estão diante de mim; há também quem suscite a contenda e o litígio." },
{name:'3514',l:'35',c:'1',v:'4',texto:"Por esta causa, a lei se afrouxa, e a sentença nunca sai; porque o ímpio cerca o justo, e sai o juízo pervertido." },
{name:'3515',l:'35',c:'1',v:'5',texto:"Vede entre as nações, e olhai, e maravilhai-vos, e admirai-vos; porque realizo, em vossos dias, uma obra, que vós não crereis, quando vos for contada." },
{name:'3516',l:'35',c:'1',v:'6',texto:"Porque eis que suscito os caldeus, nação amarga e apressada, que marcha sobre a largura da terra, para possuir moradas não suas." },
{name:'3517',l:'35',c:'1',v:'7',texto:"Horrível e terrível é; dela mesma sairá o seu juízo e a sua grandeza." },
{name:'3518',l:'35',c:'1',v:'8',texto:"Os seus cavalos são mais ligeiros do que os leopardos e mais perspicazes do que os lobos à tarde; os seus cavaleiros espalham-se por toda parte; sim, os seus cavaleiros virão de longe, voarão como águias que se apressam à comida." },
{name:'3519',l:'35',c:'1',v:'9',texto:"Eles todos virão com violência; o seu rosto buscará o oriente, e eles congregarão os cativos como areia." },
{name:'35110',l:'35',c:'1',v:'10',texto:"E escarnecerão dos reis e dos príncipes farão zombarias; eles se rirão de todas as fortalezas, porque, amontoando terra, as tomarão." },
{name:'35111',l:'35',c:'1',v:'11',texto:"Então, passarão como um vento, e pisarão, e se farão culpados, atribuindo este poder ao seu deus." },
{name:'35112',l:'35',c:'1',v:'12',texto:"Não és tu desde sempre, ó SENHOR, meu Deus, meu Santo? Nós não morreremos. Ó SENHOR, para juízo o puseste, e tu, ó Rocha, o fundaste para castigar." },
{name:'35113',l:'35',c:'1',v:'13',texto:"Tu és tão puro de olhos, que não podes ver o mal e a vexação não podes contemplar; por que, pois, olhas para os que procedem aleivosamente e te calas quando o ímpio devora aquele que é mais justo do que ele?" },
{name:'35114',l:'35',c:'1',v:'14',texto:"E farias os homens como os peixes do mar, como os répteis, que não têm quem os governe?" },
{name:'35115',l:'35',c:'1',v:'15',texto:"Ele a todos levanta com o anzol, e apanha-os com a sua rede, e os ajunta na sua rede varredoura; por isso, ele se alegra e se regozija." },
{name:'35116',l:'35',c:'1',v:'16',texto:"Por isso, sacrifica à sua rede e queima incenso à sua draga; porque, com elas, se engordou a sua porção, e se engrossou a sua comida." },
{name:'35117',l:'35',c:'1',v:'17',texto:"Porventura, por isso, esvaziará a sua rede e não deixaria de matar os povos continuamente?" },
],
numVersiculos: 17,
},

c2: {
versiculos:[
{name:'3521',l:'35',c:'2',v:'1',texto:"Sobre a minha guarda estarei, e sobre a fortaleza me apresentarei, e vigiarei, para ver o que fala comigo e o que eu responderei, quando eu for argüido." },
{name:'3522',l:'35',c:'2',v:'2',texto:"Então, o SENHOR me respondeu e disse: Escreve a visão e torna-a bem legível sobre tábuas, para que a possa ler o que correndo passa." },
{name:'3523',l:'35',c:'2',v:'3',texto:"Porque a visão é ainda para o tempo determinado, e até ao fim falará, e não mentirá; se tardar, espera-o, porque certamente virá, não tardará." },
{name:'3524',l:'35',c:'2',v:'4',texto:"Eis que a sua alma se incha, não é reta nele; mas o justo, pela sua fé, viverá." },
{name:'3525',l:'35',c:'2',v:'5',texto:"Tanto mais que, por ser dado ao vinho, é desleal; um homem soberbo, que não se contém, que alarga como o sepulcro o seu desejo e, como a morte, que não se farta, ajunta a si todas as nações e congrega a si todos os povos." },
{name:'3526',l:'35',c:'2',v:'6',texto:"Não levantarão, pois, todos estes contra ele uma parábola e um dito agudo contra ele, dizendo: Ai daquele que multiplica o que não é seu ( até quando! ) e daquele que se carrega a si mesmo de dívidas!" },
{name:'3527',l:'35',c:'2',v:'7',texto:"Não se levantarão de repente os que te hão de morder? E não despertarão os que te hão de abalar? E não lhes servirás tu de despojo?" },
{name:'3528',l:'35',c:'2',v:'8',texto:"Visto como despojaste muitas nações, todos os mais povos te despojarão a ti, por causa do sangue dos homens e da violência para com a terra, a cidade e todos os que habitam nela." },
{name:'3529',l:'35',c:'2',v:'9',texto:"Ai daquele que ajunta em sua casa bens mal adquiridos, para pôr o seu ninho no alto, a fim de se livrar da mão do mal!" },
{name:'35210',l:'35',c:'2',v:'10',texto:"Vergonha maquinaste para a tua casa; destruindo tu a muitos povos, pecaste contra a tua alma." },
{name:'35211',l:'35',c:'2',v:'11',texto:"Porque a pedra clamará da parede, e a trave lhe responderá do madeiramento." },
{name:'35212',l:'35',c:'2',v:'12',texto:"Ai daquele que edifica a cidade com sangue e que funda a cidade com iniqüidade!" },
{name:'35213',l:'35',c:'2',v:'13',texto:"Eis que não vem do SENHOR dos Exércitos que os povos trabalhem para o fogo e os homens se cansem pela vaidade." },
{name:'35214',l:'35',c:'2',v:'14',texto:"Porque a terra se encherá do conhecimento da glória do SENHOR, como as águas cobrem o mar." },
{name:'35215',l:'35',c:'2',v:'15',texto:"Ai daquele que dá de beber ao seu companheiro! Tu, que lhe chegas o teu odre e o embebedas, para ver a sua nudez," },
{name:'35216',l:'35',c:'2',v:'16',texto:"serás farto de ignomínia em lugar de honra; bebe tu também e sê como um incircunciso; o cálice da mão direita do SENHOR se voltará sobre ti, e vômito ignominioso cairá sobre a tua glória." },
{name:'35217',l:'35',c:'2',v:'17',texto:"Porque a violência cometida contra o Líbano te cobrirá, e a destruição dos animais ferozes os assombrará, por causa do sangue dos homens, e da violência para com a terra, a cidade e todos os seus moradores." },
{name:'35218',l:'35',c:'2',v:'18',texto:"Que aproveitará a imagem de escultura, que esculpiu o seu artífice? E a imagem de fundição, que ensina a mentira, para que o artífice confie na obra, fazendo ídolos mudos?" },
{name:'35219',l:'35',c:'2',v:'19',texto:"Ai daquele que diz ao pau: Acorda! E à pedra muda: Desperta! Pode isso ensinar? Eis que está coberto de ouro e de prata, mas no meio dele não há espírito algum." },
{name:'35220',l:'35',c:'2',v:'20',texto:"Mas o SENHOR está no seu santo templo; cale-se diante dele toda a terra." },
],
numVersiculos: 20,
},

c3: {
versiculos:[
{name:'3531',l:'35',c:'3',v:'1',texto:"Oração do profeta Habacuque sob a forma de canto." },
{name:'3532',l:'35',c:'3',v:'2',texto:"Ouvi, SENHOR, a tua palavra e temi; aviva, ó SENHOR, a tua obra no meio dos anos, no meio dos anos a notifica; na ira lembra-te da misericórdia." },
{name:'3533',l:'35',c:'3',v:'3',texto:"Deus veio de Temã, e o Santo, do monte de Parã. ( Selá ) A sua glória cobriu os céus, e a terra encheu-se do seu louvor." },
{name:'3534',l:'35',c:'3',v:'4',texto:"E o seu resplendor era como a luz, raios brilhantes saíam da sua mão, e ali estava o esconderijo da sua força." },
{name:'3535',l:'35',c:'3',v:'5',texto:"Adiante dele ia a peste, e raios de fogo, sob os seus pés." },
{name:'3536',l:'35',c:'3',v:'6',texto:"Parou e mediu a terra; olhou e separou as nações; e os montes perpétuos foram esmiuçados, os outeiros eternos se encurvaram; o andar eterno é seu." },
{name:'3537',l:'35',c:'3',v:'7',texto:"Vi as tendas de Cusã em aflição; as cortinas da terra de Midiã tremiam." },
{name:'3538',l:'35',c:'3',v:'8',texto:"Acaso é contra os rios, SENHOR, que estás irado? Contra os ribeiros foi a tua ira ou contra o mar foi o teu furor, para que andasses montado sobre os teus cavalos, sobre os teus carros de salvação?" },
{name:'3539',l:'35',c:'3',v:'9',texto:"Descoberto se fez o teu arco; os juramentos feitos às tribos foram uma palavra segura. ( Selá ) Tu fendeste a terra com rios." },
{name:'35310',l:'35',c:'3',v:'10',texto:"Os montes te viram e tremeram; a inundação das águas passou; deu o abismo a sua voz, levantou as suas mãos ao alto." },
{name:'35311',l:'35',c:'3',v:'11',texto:"O sol e a lua pararam nas suas moradas; andaram à luz das tuas flechas, ao resplendor do relâmpago da tua lança." },
{name:'35312',l:'35',c:'3',v:'12',texto:"Com indignação marchaste pela terra, com ira trilhaste as nações." },
{name:'35313',l:'35',c:'3',v:'13',texto:"Tu saíste para salvamento do teu povo, para salvamento do teu ungido; tu feriste a cabeça da casa do ímpio, descobrindo os fundamentos até ao pescoço. ( Selá )" },
{name:'35314',l:'35',c:'3',v:'14',texto:"Tu abriste com os seus próprios cajados a cabeça dos seus guerreiros; eles me acometeram tempestuosos para me espalharem; alegravam-se, como se estivessem para devorar o pobre em segredo." },
{name:'35315',l:'35',c:'3',v:'15',texto:"Tu, com os teus cavalos, marchaste pelo mar, pela massa de grandes águas." },
{name:'35316',l:'35',c:'3',v:'16',texto:"Ouvindo-o eu, o meu ventre se comoveu, à sua voz tremeram os meus lábios; entrou a podridão nos meus ossos, e estremeci dentro de mim; descanse eu no dia da angústia, quando ele vier contra o povo que nos destruirá." },
{name:'35317',l:'35',c:'3',v:'17',texto:"Porquanto, ainda que a figueira não floresça, nem haja fruto na vide; o produto da oliveira minta, e os campos não produzam mantimento; as ovelhas da malhada sejam arrebatadas, e nos currais não haja vacas," },
{name:'35318',l:'35',c:'3',v:'18',texto:"todavia, eu me alegrarei no SENHOR, exultarei no Deus da minha salvação." },
{name:'35319',l:'35',c:'3',v:'19',texto:"JEOVÁ, o Senhor, é minha força, e fará os meus pés como os das cervas, e me fará andar sobre as minhas alturas. (Para o cantor-mor sobre os meus instrumentos de música.)" },
],
numVersiculos: 19,
},


};

