BibliaJFA.sofonias = {
	libro: "Sofonias",
	numCapitulos: 3,

c1: {
versiculos:[
{name:'3611',l:'36',c:'1',v:'1',texto:"Palavra do SENHOR vinda a Sofonias, filho de Cusi, filho de Gedalias, filho de Amarias, filho de Ezequias, nos dias de Josias, filho de Amom, rei de Judá." },
{name:'3612',l:'36',c:'1',v:'2',texto:"Inteiramente consumirei tudo sobre a face da terra, diz o SENHOR." },
{name:'3613',l:'36',c:'1',v:'3',texto:"Arrebatarei os homens e os animais, consumirei as aves do céu, e os peixes do mar, e os tropeços com os ímpios; e exterminarei os homens de cima da terra, disse o SENHOR." },
{name:'3614',l:'36',c:'1',v:'4',texto:"E estenderei a minha mão contra Judá e contra todos os habitantes de Jerusalém e exterminarei deste lugar o resto de Baal e o nome dos quemarins com os sacerdotes;" },
{name:'3615',l:'36',c:'1',v:'5',texto:"e os que sobre os telhados se curvam ao exército do céu; e os que se inclinam jurando ao SENHOR e juram por Malcã;" },
{name:'3616',l:'36',c:'1',v:'6',texto:"e os que deixam de andar em seguimento do SENHOR, e os que não buscam ao SENHOR, nem perguntam por ele." },
{name:'3617',l:'36',c:'1',v:'7',texto:"Cala-te diante do Senhor JEOVÁ, porque o dia do SENHOR está perto, porque o SENHOR preparou o sacrifício e santificou os seus convidados." },
{name:'3618',l:'36',c:'1',v:'8',texto:"E acontecerá que, no dia do sacrifício do SENHOR, hei de castigar os príncipes, e os filhos do rei, e todos os que se vestem de vestidura estranha." },
{name:'3619',l:'36',c:'1',v:'9',texto:"Castigarei também, naquele dia, todos aqueles que saltam sobre o umbral, que enchem de violência e engano a casa dos seus senhores." },
{name:'36110',l:'36',c:'1',v:'10',texto:"E, naquele dia, diz o SENHOR, far-se-á ouvir uma voz de clamor desde a Porta do Peixe, e um uivo desde a segunda parte, e grande quebranto desde os outeiros." },
{name:'36111',l:'36',c:'1',v:'11',texto:"Uivai vós, moradores de Mactés, porque todo o povo de Canaã está arruinado, todos os carregados de dinheiro são destruídos." },
{name:'36112',l:'36',c:'1',v:'12',texto:"E há de ser que, naquele tempo, esquadrinharei Jerusalém com lanternas e castigarei os homens que estão assentados sobre as suas fezes, que dizem no seu coração: O SENHOR não faz bem nem faz mal." },
{name:'36113',l:'36',c:'1',v:'13',texto:"Por isso, será saqueada a sua fazenda, e assoladas as suas casas; e edificarão casas, mas não habitarão nelas, e plantarão vinhas, mas não lhes beberão o vinho." },
{name:'36114',l:'36',c:'1',v:'14',texto:"O grande dia do SENHOR está perto, está perto, e se apressa muito a voz do dia do SENHOR; amargamente clamará ali o homem poderoso." },
{name:'36115',l:'36',c:'1',v:'15',texto:"Aquele dia é um dia de indignação, dia de angústia e de ânsia, dia de alvoroço e de desolação, dia de trevas e de escuridão, dia de nuvens e de densas trevas," },
{name:'36116',l:'36',c:'1',v:'16',texto:"dia de trombeta e de alarido contra as cidades fortes e contra as torres altas." },
{name:'36117',l:'36',c:'1',v:'17',texto:"E angustiarei os homens, e eles andarão como cegos, porque pecaram contra o SENHOR; e o seu sangue se derramará como pó, e a sua carne, como esterco." },
{name:'36118',l:'36',c:'1',v:'18',texto:"Nem a sua prata nem o seu ouro os poderá livrar no dia do furor do SENHOR, mas, pelo fogo do seu zelo, toda esta terra será consumida, porque certamente fará de todos os moradores da terra uma destruição total e apressada." },
],
numVersiculos: 18,
},

c2: {
versiculos:[
{name:'3621',l:'36',c:'2',v:'1',texto:"Congrega-te, sim, congrega-te, ó nação que não tens desejo," },
{name:'3622',l:'36',c:'2',v:'2',texto:"antes que saia o decreto, e o dia passe como a palha; antes que venha sobre vós a ira do SENHOR; sim, antes que venha sobre vós o dia da ira do SENHOR." },
{name:'3623',l:'36',c:'2',v:'3',texto:"Buscai o SENHOR, vós todos os mansos da terra, que pondes por obra o seu juízo; buscai a justiça, buscai a mansidão; porventura sereis escondidos no dia da ira do SENHOR." },
{name:'3624',l:'36',c:'2',v:'4',texto:"Porque Gaza será desamparada, e Asquelom, assolada; Asdode ao meio-dia será expelida, e Ecrom, desarraigada." },
{name:'3625',l:'36',c:'2',v:'5',texto:"Ai dos habitantes da borda do mar, do povo dos quereteus! A palavra do SENHOR será contra vós, ó Canaã, terra dos filisteus, e eu vos farei destruir, até que não haja morador." },
{name:'3626',l:'36',c:'2',v:'6',texto:"E a borda do mar será de pastagens, com cabanas para os pastores e currais para os rebanhos." },
{name:'3627',l:'36',c:'2',v:'7',texto:"E será a costa para o resto da casa de Judá para que nela apascentem; à tarde, se assentarão nas casas de Asquelom, porque o SENHOR, seu Deus, os visitará e reconduzirá os seus cativos." },
{name:'3628',l:'36',c:'2',v:'8',texto:"Eu ouvi o escárnio de Moabe e as injuriosas palavras dos filhos de Amom, com que escarneceram do meu povo e se engrandeceram contra o seu termo." },
{name:'3629',l:'36',c:'2',v:'9',texto:"Portanto, tão certo como eu vivo, diz o SENHOR dos Exércitos, o Deus de Israel, Moabe será como Sodoma, e os filhos de Amom, como Gomorra, campo de urtigas, e poços de sal, e assolação perpétua; o resto do meu povo os saqueará, e o restante do meu povo os possuirá." },
{name:'36210',l:'36',c:'2',v:'10',texto:"Isso terão em recompensa da sua soberba, porque escarneceram e se engrandeceram contra o povo do SENHOR dos Exércitos." },
{name:'36211',l:'36',c:'2',v:'11',texto:"O SENHOR será terrível para eles, porque aniquilará todos os deuses da terra; e todos virão adorá-lo, cada um desde o seu lugar, todas as ilhas das nações." },
{name:'36212',l:'36',c:'2',v:'12',texto:"Também vós, ó etíopes, sereis mortos com a minha espada." },
{name:'36213',l:'36',c:'2',v:'13',texto:"Estenderá também a sua mão contra o Norte e destruirá a Assíria; e fará de Nínive uma assolação, terra seca como o deserto." },
{name:'36214',l:'36',c:'2',v:'14',texto:"E, no meio dela, repousarão os rebanhos, todos os animais dos povos; e alojar-se-ão nos seus capitéis assim o pelicano como o ouriço; a voz do seu canto retinirá nas janelas, a assolação estará no umbral, quando tiver descoberto a sua obra de cedro." },
{name:'36215',l:'36',c:'2',v:'15',texto:"Esta é a cidade alegre e descuidada, que dizia no seu coração: Eu sou, e não há outra além de mim; como se tornou em assolação, em pousada de animais! Qualquer que passar por ela assobiará e meneará a sua mão." },
],
numVersiculos: 15,
},

c3: {
versiculos:[
{name:'3631',l:'36',c:'3',v:'1',texto:"Ai da rebelde e manchada, da cidade opressora!" },
{name:'3632',l:'36',c:'3',v:'2',texto:"Não ouve a voz, não aceita o castigo, não confia no SENHOR, nem se aproximou do seu Deus." },
{name:'3633',l:'36',c:'3',v:'3',texto:"Os seus príncipes são leões rugidores no meio dela; os seus juízes são lobos da tarde, que não deixam os ossos para o outro dia." },
{name:'3634',l:'36',c:'3',v:'4',texto:"Os seus profetas são levianos e criaturas aleivosas; os seus sacerdotes profanaram o santuário e fizeram violência à lei." },
{name:'3635',l:'36',c:'3',v:'5',texto:"O SENHOR é justo, no meio dela; ele não comete iniqüidade; cada manhã traz o seu juízo à luz; nunca falta; mas o perverso não conhece a vergonha." },
{name:'3636',l:'36',c:'3',v:'6',texto:"Exterminei as nações, as suas torres estão assoladas; fiz desertas as suas praças, a ponto de não ficar quem passe por elas; as suas cidades foram destruídas, até não ficar ninguém, até não haver quem as habite." },
{name:'3637',l:'36',c:'3',v:'7',texto:"Eu dizia: Certamente me temerás e aceitarás a correção; e assim a sua morada não seria destruída, conforme o que havia determinado; mas eles se levantaram de madrugada, corromperam todas as suas obras." },
{name:'3638',l:'36',c:'3',v:'8',texto:"Portanto, esperai-me a mim, diz o SENHOR, no dia em que eu me levantar para o despojo; porque o meu juízo é ajuntar as nações e congregar os reinos, para sobre eles derramar a minha indignação e todo o ardor da minha ira; porque toda esta terra será consumida pelo fogo do meu zelo." },
{name:'3639',l:'36',c:'3',v:'9',texto:"Porque, então, darei lábios puros aos povos, para que todos invoquem o nome do SENHOR, para que o sirvam com um mesmo espírito." },
{name:'36310',l:'36',c:'3',v:'10',texto:"Dalém dos rios da Etiópia os meus zelosos adoradores, a filha da minha dispersão, me trarão sacrifício." },
{name:'36311',l:'36',c:'3',v:'11',texto:"Naquele dia, não te envergonharás de nenhuma das tuas obras, com que te rebelaste contra mim; porque então tirarei do meio de ti os que exultam na sua soberba, e tu nunca mais te ensoberbecerás no meu monte santo." },
{name:'36312',l:'36',c:'3',v:'12',texto:"Mas deixarei no meio de ti um povo humilde e pobre; e eles confiarão no nome do SENHOR." },
{name:'36313',l:'36',c:'3',v:'13',texto:"O remanescente de Israel não cometerá iniqüidade, nem proferirá mentira, e na sua boca não se achará língua enganosa; porque serão apascentados, deitar-se-ão, e não haverá quem os espante." },
{name:'36314',l:'36',c:'3',v:'14',texto:"Canta alegremente, ó filha de Sião; rejubila, ó Israel; regozija-te e exulta de todo o coração, ó filha de Jerusalém." },
{name:'36315',l:'36',c:'3',v:'15',texto:"O SENHOR afastou os teus juízos, exterminou o teu inimigo; o SENHOR, o rei de Israel, está no meio de ti; tu não verás mais mal algum." },
{name:'36316',l:'36',c:'3',v:'16',texto:"Naquele dia, se dirá a Jerusalém: Não temas, ó Sião, não se enfraqueçam as tuas mãos." },
{name:'36317',l:'36',c:'3',v:'17',texto:"O SENHOR, teu Deus, está no meio de ti, poderoso para te salvar; ele se deleitará em ti com alegria; calar-se-á por seu amor, regozijar-se-á em ti com júbilo." },
{name:'36318',l:'36',c:'3',v:'18',texto:"Os que em ti se entristeceram, por causa da reunião solene, eu os congregarei; esses para os quais o peso foi uma afronta." },
{name:'36319',l:'36',c:'3',v:'19',texto:"Eis que, naquele tempo, procederei contra todos os que te afligem, e salvarei os que coxeiam, e recolherei os que foram expulsos; e lhes darei um louvor e um nome em toda a terra em que foram envergonhados." },
{name:'36320',l:'36',c:'3',v:'20',texto:"Naquele tempo, vos trarei, naquele tempo, vos recolherei; certamente, vos darei um nome e um louvor entre todos os povos da terra, quando reconduzir os vossos cativos diante dos vossos olhos, diz o SENHOR." },
],
numVersiculos: 20,
},
	

};
