BibliaJFA.hageo = {
	libro: "Ageu",
	numCapitulos: 2,

c1: {
versiculos:[
{name:'3711',l:'37',c:'1',v:'1',texto:"No ano segundo do rei Dario, no sexto mês, no primeiro dia do mês, veio a palavra do SENHOR, pelo ministério do profeta Ageu, a Zorobabel, filho de Sealtiel, príncipe de Judá, e a Josué, filho de Jozadaque, o sumo sacerdote, dizendo:" },
{name:'3712',l:'37',c:'1',v:'2',texto:"Assim fala o SENHOR dos Exércitos, dizendo: Este povo diz: Não veio ainda o tempo, o tempo em que a Casa do SENHOR deve ser edificada." },
{name:'3713',l:'37',c:'1',v:'3',texto:"Veio, pois, a palavra do SENHOR, pelo ministério do profeta Ageu, dizendo:" },
{name:'3714',l:'37',c:'1',v:'4',texto:"É para vós tempo de habitardes nas vossas casas estucadas, e esta casa há de ficar deserta?" },
{name:'3715',l:'37',c:'1',v:'5',texto:"Ora, pois, assim diz o SENHOR dos Exércitos: Aplicai o vosso coração aos vossos caminhos." },
{name:'3716',l:'37',c:'1',v:'6',texto:"Semeais muito e recolheis pouco; comeis, mas não vos fartais; bebeis, mas não vos saciais; vestis-vos, mas ninguém se aquece; e o que recebe salário recebe salário num saquitel furado." },
{name:'3717',l:'37',c:'1',v:'7',texto:"Assim diz o SENHOR dos Exércitos: Aplicai o vosso coração aos vossos caminhos." },
{name:'3718',l:'37',c:'1',v:'8',texto:"Subi o monte, e trazei madeira, e edificai a casa; e dela me agradarei e eu serei glorificado, diz o SENHOR." },
{name:'3719',l:'37',c:'1',v:'9',texto:"Olhastes para muito, mas eis que alcançastes pouco; e esse pouco, quando o trouxestes para casa, eu lhe assoprei. Por quê? —disse o SENHOR dos Exércitos. Por causa da minha casa, que está deserta, e cada um de vós corre à sua própria casa." },
{name:'37110',l:'37',c:'1',v:'10',texto:"Por isso, retêm os céus o seu orvalho, e a terra retém os seus frutos." },
{name:'37111',l:'37',c:'1',v:'11',texto:"E fiz vir a seca sobre a terra, e sobre os montes, e sobre o trigo, e sobre o mosto, e sobre o azeite, e sobre o que a terra produz, como também sobre os homens, e sobre os animais, e sobre todo o trabalho das mãos." },
{name:'37112',l:'37',c:'1',v:'12',texto:"Então, ouviu Zorobabel, filho de Sealtiel, e Josué, filho de Jozadaque, sumo sacerdote, e todo o resto do povo a voz do SENHOR, seu Deus, e as palavras do profeta Ageu, como o SENHOR, seu Deus, o tinha enviado; e temeu o povo diante do SENHOR." },
{name:'37113',l:'37',c:'1',v:'13',texto:"Então, Ageu, o embaixador do SENHOR, falou ao povo, conforme a mensagem do SENHOR, dizendo: Eu sou convosco, diz o SENHOR." },
{name:'37114',l:'37',c:'1',v:'14',texto:"E o SENHOR levantou o espírito de Zorobabel, filho de Sealtiel, príncipe de Judá, e o espírito de Josué, filho de Jozadaque, sumo sacerdote, e o espírito do resto de todo o povo, e vieram e trabalharam na Casa do SENHOR dos Exércitos, seu Deus," },
{name:'37115',l:'37',c:'1',v:'15',texto:"ao vigésimo quarto dia do sexto mês, no segundo ano do rei Dario." },
],
numVersiculos: 15,
},

c2: {
versiculos:[
{name:'3721',l:'37',c:'2',v:'1',texto:"No sétimo mês, ao vigésimo primeiro do mês, veio a palavra do SENHOR pelo ministério do profeta Ageu, dizendo:" },
{name:'3722',l:'37',c:'2',v:'2',texto:"Fala agora a Zorobabel, filho de Sealtiel, príncipe de Judá, e a Josué, filho de Jozadaque, sumo sacerdote, e ao resto do povo, dizendo:" },
{name:'3723',l:'37',c:'2',v:'3',texto:"Quem há entre vós que, tendo ficado, viu esta casa na sua primeira glória? E como a vedes agora? Não é esta como nada em vossos olhos, comparada com aquela?" },
{name:'3724',l:'37',c:'2',v:'4',texto:"Ora, pois, esforça-te, Zorobabel, diz o SENHOR, e esforça-te, Josué, filho de Jozadaque, sumo sacerdote, e esforçai-vos, todo o povo da terra, diz o SENHOR, e trabalhai; porque eu sou convosco, diz o SENHOR dos Exércitos," },
{name:'3725',l:'37',c:'2',v:'5',texto:"segundo a palavra que concertei convosco, quando saístes do Egito, e o meu Espírito habitava no meio de vós; não temais." },
{name:'3726',l:'37',c:'2',v:'6',texto:"Porque assim diz o SENHOR dos Exércitos: Ainda uma vez, daqui a pouco, e farei tremer os céus, e a terra, e o mar, e a terra seca;" },
{name:'3727',l:'37',c:'2',v:'7',texto:"e farei tremer todas as nações, e virá o Desejado de todas as nações, e encherei esta casa de glória, diz o SENHOR dos Exércitos." },
{name:'3728',l:'37',c:'2',v:'8',texto:"Minha é a prata, e meu é o ouro, disse o SENHOR dos Exércitos." },
{name:'3729',l:'37',c:'2',v:'9',texto:"A glória desta última casa será maior do que a da primeira, diz o SENHOR dos Exércitos, e neste lugar darei a paz, diz o SENHOR dos Exércitos." },
{name:'37210',l:'37',c:'2',v:'10',texto:"Ao vigésimo quarto dia do mês nono, no segundo ano de Dario, veio a palavra do SENHOR pelo ministério do profeta Ageu, dizendo:" },
{name:'37211',l:'37',c:'2',v:'11',texto:"Assim diz o SENHOR dos Exércitos: Pergunta, agora, aos sacerdotes, acerca da lei, dizendo:" },
{name:'37212',l:'37',c:'2',v:'12',texto:"Se alguém leva carne santa na aba da sua veste e com a sua aba tocar no pão, ou no guisado, ou no vinho, ou no azeite, ou em qualquer outro mantimento, ficará este santificado? E os sacerdotes, respondendo, diziam: Não." },
{name:'37213',l:'37',c:'2',v:'13',texto:"E disse Ageu: Se alguém, que se tinha tornado impuro pelo contato com um corpo morto, tocar nalguma destas coisas, ficará isso imundo? E os sacerdotes, respondendo, diziam: Ficará imunda." },
{name:'37214',l:'37',c:'2',v:'14',texto:"Então, respondeu Ageu e disse: Assim é este povo, e assim é esta nação diante do meu rosto, disse o SENHOR; e assim é toda a obra das suas mãos; e tudo o que ali oferecem imundo é." },
{name:'37215',l:'37',c:'2',v:'15',texto:"Agora, pois, aplicai o vosso coração a isso, desde este dia em diante, antes de pordes pedra sobre pedra no templo do SENHOR." },
{name:'37216',l:'37',c:'2',v:'16',texto:"Depois daquele tempo, veio alguém a um monte de vinte medidas, e havia somente dez; vindo ao lagar para tirar cinqüenta, havia somente vinte." },
{name:'37217',l:'37',c:'2',v:'17',texto:"Feri-vos com queimadura, e com ferrugem, e com saraiva, em toda a obra das vossas mãos; e não houve entre vós quem voltasse para mim, diz o SENHOR." },
{name:'37218',l:'37',c:'2',v:'18',texto:"Ponde, pois, eu vos rogo, desde este dia em diante, desde o vigésimo quarto dia do mês nono, desde o dia em que se fundou o templo do SENHOR, ponde o vosso coração nestas coisas." },
{name:'37219',l:'37',c:'2',v:'19',texto:"Há ainda semente no celeiro? Nem a videira, nem a figueira, nem a romeira, nem a oliveira têm dado os seus frutos; mas desde este dia vos abençoarei." },
{name:'37220',l:'37',c:'2',v:'20',texto:"E veio a palavra do SENHOR segunda vez a Ageu, aos vinte e quatro do mês, dizendo:" },
{name:'37221',l:'37',c:'2',v:'21',texto:"Fala a Zorobabel, príncipe de Judá, dizendo: Farei tremer os céus e a terra;" },
{name:'37222',l:'37',c:'2',v:'22',texto:"e derribarei o trono dos reinos e destruirei a força dos reinos das nações; e destruirei o carro e os que nele se assentam; e os cavalos e os que andam montados neles cairão, cada um pela espada do seu irmão." },
{name:'37223',l:'37',c:'2',v:'23',texto:"Naquele dia, diz o SENHOR dos Exércitos, te tomarei, ó Zorobabel, filho de Sealtiel, servo meu, diz o SENHOR, e te farei como um anel de selar; porque te escolhi, diz o SENHOR dos Exércitos." },
],
numVersiculos: 23,
},


};
