BibliaJFA.malaquias = {
	libro: "Malaquias",
	numCapitulos: 4,

c1: {
versiculos:[
{name:'3911',l:'39',c:'1',v:'1',texto:"Peso da palavra do SENHOR contra Israel, pelo ministério de Malaquias." },
{name:'3912',l:'39',c:'1',v:'2',texto:"Eu vos amei, diz o SENHOR; mas vós dizeis: Em que nos amaste? Não foi Esaú irmão de Jacó? —disse o SENHOR; todavia amei a Jacó" },
{name:'3913',l:'39',c:'1',v:'3',texto:"e aborreci a Esaú; e fiz dos seus montes uma assolação e dei a sua herança aos dragões do deserto." },
{name:'3914',l:'39',c:'1',v:'4',texto:"Ainda que Edom diga: Empobrecidos somos, porém tornaremos a edificar os lugares desertos, assim diz o SENHOR dos Exércitos: Eles edificarão, e eu destruirei, e lhes chamarão Termo-de-Impiedade e Povo-Contra-Quem-O-SENHOR-Está-Irado-Para-Sempre." },
{name:'3915',l:'39',c:'1',v:'5',texto:"E os vossos olhos o verão, e direis: O SENHOR seja engrandecido desde os termos de Israel." },
{name:'3916',l:'39',c:'1',v:'6',texto:"O filho honrará o pai, e o servo, ao seu senhor; e, se eu sou Pai, onde está a minha honra? E, se eu sou Senhor, onde está o meu temor? —diz o SENHOR dos Exércitos a vós, ó sacerdotes, que desprezais o meu nome e dizeis: Em que desprezamos nós o teu nome?" },
{name:'3917',l:'39',c:'1',v:'7',texto:"Ofereceis sobre o meu altar pão imundo e dizeis: Em que te havemos profanado? Nisto, que dizeis: A mesa do SENHOR é desprezível." },
{name:'3918',l:'39',c:'1',v:'8',texto:"Porque, quando trazeis animal cego para o sacrificardes, não faz mal! E, quando ofereceis o coxo ou o enfermo, não faz mal! Ora, apresenta-o ao teu príncipe; terá ele agrado em ti? Ou aceitará ele a tua pessoa? —diz o SENHOR dos Exércitos." },
{name:'3919',l:'39',c:'1',v:'9',texto:"Agora, pois, suplicai o favor de Deus, e ele terá piedade de nós; isto veio da vossa mão; aceitará ele a vossa pessoa? —diz o SENHOR dos Exércitos." },
{name:'39110',l:'39',c:'1',v:'10',texto:"Quem há também entre vós que feche as portas e não acenda debalde o fogo do meu altar? Eu não tenho prazer em vós, diz o SENHOR dos Exércitos, nem aceitarei da vossa mão a oblação." },
{name:'39111',l:'39',c:'1',v:'11',texto:"Mas, desde o nascente do sol até ao poente, será grande entre as nações o meu nome; e, em todo lugar, se oferecerá ao meu nome incenso e uma oblação pura; porque o meu nome será grande entre as nações, diz o SENHOR dos Exércitos." },
{name:'39112',l:'39',c:'1',v:'12',texto:"Mas vós o profanais, quando dizeis: A mesa do SENHOR é impura, e o seu produto, a sua comida, é desprezível." },
{name:'39113',l:'39',c:'1',v:'13',texto:"E dizeis: Eis aqui, que canseira! E o lançastes ao desprezo, diz o SENHOR dos Exércitos: vós ofereceis o roubado, e o coxo, e o enfermo; assim fazeis a oferta; ser-me-á aceito isto de vossa mão? —diz o SENHOR." },
{name:'39114',l:'39',c:'1',v:'14',texto:"Pois maldito seja o enganador, que, tendo animal no seu rebanho, promete e oferece ao SENHOR uma coisa vil; porque eu sou grande Rei, diz o SENHOR dos Exércitos, o meu nome será tremendo entre as nações." },
],
numVersiculos: 14,
},

c2: {
versiculos:[
{name:'3921',l:'39',c:'2',v:'1',texto:"E, agora, ó sacerdotes, este mandamento vos toca a vós." },
{name:'3922',l:'39',c:'2',v:'2',texto:"Se o não ouvirdes e se não propuserdes no vosso coração dar honra ao meu nome, diz o SENHOR dos Exércitos, enviarei a maldição contra vós e amaldiçoarei as vossas bênçãos; e já as tenho amaldiçoado, porque vós não pondes isso no coração." },
{name:'3923',l:'39',c:'2',v:'3',texto:"Eis que vos corromperei a semente e espalharei esterco sobre o vosso rosto, o esterco das vossas festas; e com ele sereis tirados." },
{name:'3924',l:'39',c:'2',v:'4',texto:"Então, sabereis que eu vos enviei este mandamento, para que o meu concerto seja com Levi, diz o SENHOR dos Exércitos." },
{name:'3925',l:'39',c:'2',v:'5',texto:"Meu concerto com ele foi de vida e de paz, e eu lhas dei para que me temesse, e me temeu e assombrou-se por causa do meu nome." },
{name:'3926',l:'39',c:'2',v:'6',texto:"A lei da verdade esteve na sua boca, e a iniqüidade não se achou nos seus lábios; andou comigo em paz e em retidão e apartou a muitos da iniqüidade." },
{name:'3927',l:'39',c:'2',v:'7',texto:"Porque os lábios do sacerdote guardarão a ciência, e da sua boca buscarão a lei, porque ele é o anjo do SENHOR dos Exércitos." },
{name:'3928',l:'39',c:'2',v:'8',texto:"Mas vós vos desviastes do caminho, a muitos fizestes tropeçar na lei: corrompestes o concerto de Levi, diz o SENHOR dos Exércitos." },
{name:'3929',l:'39',c:'2',v:'9',texto:"Por isso, também eu vos fiz desprezíveis e indignos diante de todo o povo, visto que não guardastes os meus caminhos, mas fizestes acepção de pessoas na lei." },
{name:'39210',l:'39',c:'2',v:'10',texto:"Não temos nós todos um mesmo Pai? Não nos criou um mesmo Deus? Por que seremos desleais uns para com os outros, profanando o concerto de nossos pais?" },
{name:'39211',l:'39',c:'2',v:'11',texto:"Judá foi desleal, e abominação se cometeu em Israel e em Jerusalém; porque Judá profanou a santidade do SENHOR, a qual ele ama, e se casou com a filha de deus estranho." },
{name:'39212',l:'39',c:'2',v:'12',texto:"O SENHOR extirpará das tendas de Jacó o homem que fizer isso, o que vela, e o que responde, e o que oferece dons ao SENHOR dos Exércitos." },
{name:'39213',l:'39',c:'2',v:'13',texto:"Ainda fazeis isto: cobris o altar do SENHOR de lágrimas, de choros e de gemidos; de sorte que ele não olha mais para a oferta, nem a aceitará com prazer da vossa mão." },
{name:'39214',l:'39',c:'2',v:'14',texto:"E dizeis: Por quê? Porque o SENHOR foi testemunha entre ti e a mulher da tua mocidade, com a qual tu foste desleal, sendo ela a tua companheira e a mulher do teu concerto." },
{name:'39215',l:'39',c:'2',v:'15',texto:"E não fez ele somente um, sobejando-lhe espírito? E por que somente um? Ele buscava uma semente de piedosos; portanto, guardai-vos em vosso espírito, e ninguém seja desleal para com a mulher da sua mocidade." },
{name:'39216',l:'39',c:'2',v:'16',texto:"Porque o SENHOR, Deus de Israel, diz que aborrece o repúdio e aquele que encobre a violência com a sua veste, diz o SENHOR dos Exércitos; portanto, guardai-vos em vosso espírito e não sejais desleais." },
{name:'39217',l:'39',c:'2',v:'17',texto:"Enfadais ao SENHOR com vossas palavras; e ainda dizeis: Em que o enfadamos? Nisto, que dizeis: Qualquer que faz o mal passa por bom aos olhos do SENHOR, e desses é que ele se agrada; ou onde está o Deus do juízo?" },
],
numVersiculos: 17,
},

c3: {
versiculos:[
{name:'3931',l:'39',c:'3',v:'1',texto:"Eis que eu envio o meu anjo, que preparará o caminho diante de mim; e, de repente, virá ao seu templo o Senhor, a quem vós buscais, o anjo do concerto, a quem vós desejais; eis que vem, diz o SENHOR dos Exércitos." },
{name:'3932',l:'39',c:'3',v:'2',texto:"Mas quem suportará o dia da sua vinda? E quem subsistirá, quando ele aparecer? Porque ele será como o fogo do ourives e como o sabão dos lavandeiros." },
{name:'3933',l:'39',c:'3',v:'3',texto:"E assentar-se-á, afinando e purificando a prata; e purificará os filhos de Levi e os afinará como ouro e como prata; então, ao SENHOR trarão ofertas em justiça." },
{name:'3934',l:'39',c:'3',v:'4',texto:"E a oferta de Judá e de Jerusalém será suave ao SENHOR, como nos dias antigos e como nos primeiros anos." },
{name:'3935',l:'39',c:'3',v:'5',texto:"E chegar-me-ei a vós para juízo, e serei uma testemunha veloz contra os feiticeiros, e contra os adúlteros, e contra os que juram falsamente, e contra os que defraudam o jornaleiro, e pervertem o direito da viúva, e do órfão, e do estrangeiro, e não me temem, diz o SENHOR dos Exércitos." },
{name:'3936',l:'39',c:'3',v:'6',texto:"Porque eu, o SENHOR, não mudo; por isso, vós, ó filhos de Jacó, não sois consumidos." },
{name:'3937',l:'39',c:'3',v:'7',texto:"Desde os dias de vossos pais, vos desviastes dos meus estatutos e não os guardastes; tornai vós para mim, e eu tornarei para vós, diz o SENHOR dos Exércitos; mas vós dizeis: Em que havemos de tornar?" },
{name:'3938',l:'39',c:'3',v:'8',texto:"Roubará o homem a Deus? Todavia, vós me roubais e dizeis: Em que te roubamos? Nos dízimos e nas ofertas alçadas." },
{name:'3939',l:'39',c:'3',v:'9',texto:"Com maldição sois amaldiçoados, porque me roubais a mim, vós, toda a nação." },
{name:'39310',l:'39',c:'3',v:'10',texto:"Trazei todos os dízimos à casa do tesouro, para que haja mantimento na minha casa, e depois fazei prova de mim, diz o SENHOR dos Exércitos, se eu não vos abrir as janelas do céu e não derramar sobre vós uma bênção tal, que dela vos advenha a maior abastança." },
{name:'39311',l:'39',c:'3',v:'11',texto:"E, por causa de vós, repreenderei o devorador, para que não vos consuma o fruto da terra; e a vide no campo não vos será estéril, diz o SENHOR dos Exércitos." },
{name:'39312',l:'39',c:'3',v:'12',texto:"E todas as nações vos chamarão bem-aventurados; porque vós sereis uma terra deleitosa, diz o SENHOR dos Exércitos." },
{name:'39313',l:'39',c:'3',v:'13',texto:"As vossas palavras foram agressivas para mim, diz o SENHOR; mas vós dizeis: Que temos falado contra ti?" },
{name:'39314',l:'39',c:'3',v:'14',texto:"Vós dizeis: Inútil é servir a Deus; que nos aproveitou termos cuidado em guardar os seus preceitos e em andar de luto diante do SENHOR dos Exércitos?" },
{name:'39315',l:'39',c:'3',v:'15',texto:"Ora, pois, nós reputamos por bem-aventurados os soberbos; também os que cometem impiedade se edificam; sim, eles tentam ao SENHOR e escapam." },
{name:'39316',l:'39',c:'3',v:'16',texto:"Então, aqueles que temem ao SENHOR falam cada um com o seu companheiro; e o SENHOR atenta e ouve; e há um memorial escrito diante dele, para os que temem ao SENHOR e para os que se lembram do seu nome." },
{name:'39317',l:'39',c:'3',v:'17',texto:"E eles serão meus, diz o SENHOR dos Exércitos, naquele dia que farei, serão para mim particular tesouro; poupá-los-ei como um homem poupa a seu filho que o serve." },
{name:'39318',l:'39',c:'3',v:'18',texto:"Então, vereis outra vez a diferença entre o justo e o ímpio; entre o que serve a Deus e o que não o serve." },
],
numVersiculos: 18,
},

c4: {
versiculos:[
{name:'3941',l:'39',c:'4',v:'1',texto:"Porque eis que aquele dia vem ardendo como forno; todos os soberbos e todos os que cometem impiedade serão como palha; e o dia que está para vir os abrasará, diz o SENHOR dos Exércitos, de sorte que lhes não deixará nem raiz nem ramo." },
{name:'3942',l:'39',c:'4',v:'2',texto:"Mas para vós que temeis o meu nome nascerá o sol da justiça e salvação trará debaixo das suas asas; e saireis e crescereis como os bezerros do cevadouro." },
{name:'3943',l:'39',c:'4',v:'3',texto:"E pisareis os ímpios, porque se farão cinza debaixo das plantas de vossos pés, naquele dia que farei, diz o SENHOR dos Exércitos." },
{name:'3944',l:'39',c:'4',v:'4',texto:"Lembrai-vos da Lei de Moisés, meu servo, a qual lhe mandei em Horebe para todo o Israel, a qual são os estatutos e juízos." },
{name:'3945',l:'39',c:'4',v:'5',texto:"Eis que eu vos envio o profeta Elias, antes que venha o dia grande e terrível do SENHOR;" },
{name:'3946',l:'39',c:'4',v:'6',texto:"e converterá o coração dos pais aos filhos e o coração dos filhos a seus pais; para que eu não venha e fira a terra com maldição." },
],
numVersiculos: 6,
},
	

};
