BibliaJFA.romanos = {
	libro: "Romanos",
	numCapitulos: 16,

c1: {
versiculos:[
{name:'4511',l:'45',c:'1',v:'1',texto:"Paulo, servo de Jesus Cristo, chamado para apóstolo, separado para o evangelho de Deus," },
{name:'4512',l:'45',c:'1',v:'2',texto:"o qual antes havia prometido pelos seus profetas nas Santas Escrituras," },
{name:'4513',l:'45',c:'1',v:'3',texto:"acerca de seu Filho, que nasceu da descendência de Davi segundo a carne," },
{name:'4514',l:'45',c:'1',v:'4',texto:"declarado Filho de Deus em poder, segundo o Espírito de santificação, pela ressurreição dos mortos, —Jesus Cristo, nosso Senhor," },
{name:'4515',l:'45',c:'1',v:'5',texto:"pelo qual recebemos a graça e o apostolado, para a obediência da fé entre todas as gentes pelo seu nome," },
{name:'4516',l:'45',c:'1',v:'6',texto:"entre as quais sois também vós chamados para serdes de Jesus Cristo." },
{name:'4517',l:'45',c:'1',v:'7',texto:"A todos os que estais em Roma, amados de Deus, chamados santos: Graça e paz de Deus, nosso Pai, e do Senhor Jesus Cristo." },
{name:'4518',l:'45',c:'1',v:'8',texto:"Primeiramente, dou graças ao meu Deus por Jesus Cristo, acerca de vós todos, porque em todo o mundo é anunciada a vossa fé." },
{name:'4519',l:'45',c:'1',v:'9',texto:"Porque Deus, a quem sirvo em meu espírito, no evangelho de seu Filho, me é testemunha de como incessantemente faço menção de vós," },
{name:'45110',l:'45',c:'1',v:'10',texto:"pedindo sempre em minhas orações que, nalgum tempo, pela vontade de Deus, se me ofereça boa ocasião de ir ter convosco." },
{name:'45111',l:'45',c:'1',v:'11',texto:"Porque desejo ver-vos, para vos comunicar algum dom espiritual, a fim de que sejais confortados," },
{name:'45112',l:'45',c:'1',v:'12',texto:"isto é, para que juntamente convosco eu seja consolado pela fé mútua, tanto vossa como minha." },
{name:'45113',l:'45',c:'1',v:'13',texto:"Não quero, porém, irmãos, que ignoreis que muitas vezes propus ir ter convosco ( mas até agora tenho sido impedido ) para também ter entre vós algum fruto, como também entre os demais gentios." },
{name:'45114',l:'45',c:'1',v:'14',texto:"Eu sou devedor tanto a gregos como a bárbaros, tanto a sábios como a ignorantes." },
{name:'45115',l:'45',c:'1',v:'15',texto:"E assim, quanto está em mim, estou pronto para também vos anunciar o evangelho, a vós que estais em Roma." },
{name:'45116',l:'45',c:'1',v:'16',texto:"Porque não me envergonho do evangelho de Cristo, pois é o poder de Deus para salvação de todo aquele que crê, primeiro do judeu e também do grego." },
{name:'45117',l:'45',c:'1',v:'17',texto:"Porque nele se descobre a justiça de Deus de fé em fé, como está escrito: Mas o justo viverá da fé." },
{name:'45118',l:'45',c:'1',v:'18',texto:"Porque do céu se manifesta a ira de Deus sobre toda impiedade e injustiça dos homens que detêm a verdade em injustiça;" },
{name:'45119',l:'45',c:'1',v:'19',texto:"porquanto o que de Deus se pode conhecer neles se manifesta, porque Deus lho manifestou." },
{name:'45120',l:'45',c:'1',v:'20',texto:"Porque as suas coisas invisíveis, desde a criação do mundo, tanto o seu eterno poder como a sua divindade, se entendem e claramente se vêem pelas coisas que estão criadas, para que eles fiquem inescusáveis;" },
{name:'45121',l:'45',c:'1',v:'21',texto:"porquanto, tendo conhecido a Deus, não o glorificaram como Deus, nem lhe deram graças; antes, em seus discursos se desvaneceram, e o seu coração insensato se obscureceu." },
{name:'45122',l:'45',c:'1',v:'22',texto:"Dizendo-se sábios, tornaram-se loucos." },
{name:'45123',l:'45',c:'1',v:'23',texto:"E mudaram a glória do Deus incorruptível em semelhança da imagem de homem corruptível, e de aves, e de quadrúpedes, e de répteis." },
{name:'45124',l:'45',c:'1',v:'24',texto:"Pelo que também Deus os entregou às concupiscências do seu coração, à imundícia, para desonrarem o seu corpo entre si;" },
{name:'45125',l:'45',c:'1',v:'25',texto:"pois mudaram a verdade de Deus em mentira e honraram e serviram mais a criatura do que o Criador, que é bendito eternamente. Amém!" },
{name:'45126',l:'45',c:'1',v:'26',texto:"Pelo que Deus os abandonou às paixões infames. Porque até as suas mulheres mudaram o uso natural, no contrário à natureza." },
{name:'45127',l:'45',c:'1',v:'27',texto:"E, semelhantemente, também os varões, deixando o uso natural da mulher, se inflamaram em sua sensualidade uns para com os outros, varão com varão, cometendo torpeza e recebendo em si mesmos a recompensa que convinha ao seu erro." },
{name:'45128',l:'45',c:'1',v:'28',texto:"E, como eles se não importaram de ter conhecimento de Deus, assim Deus os entregou a um sentimento perverso, para fazerem coisas que não convém;" },
{name:'45129',l:'45',c:'1',v:'29',texto:"estando cheios de toda iniqüidade, prostituição, malícia, avareza, maldade; cheios de inveja, homicídio, contenda, engano, malignidade;" },
{name:'45130',l:'45',c:'1',v:'30',texto:"sendo murmuradores, detratores, aborrecedores de Deus, injuriadores, soberbos, presunçosos, inventores de males, desobedientes ao pai e à mãe;" },
{name:'45131',l:'45',c:'1',v:'31',texto:"néscios, infiéis nos contratos, sem afeição natural, irreconciliáveis, sem misericórdia;" },
{name:'45132',l:'45',c:'1',v:'32',texto:"os quais, conhecendo a justiça de Deus ( que são dignos de morte os que tais coisas praticam ), não somente as fazem, mas também consentem aos que as fazem." },
],
numVersiculos: 32,
},

c2: {
versiculos:[
{name:'4521',l:'45',c:'2',v:'1',texto:"Portanto, és inescusável quando julgas, ó homem, quem quer que sejas, porque te condenas a ti mesmo naquilo em que julgas a outro; pois tu, que julgas, fazes o mesmo." },
{name:'4522',l:'45',c:'2',v:'2',texto:"E bem sabemos que o juízo de Deus é segundo a verdade sobre os que tais coisas fazem." },
{name:'4523',l:'45',c:'2',v:'3',texto:"E tu, ó homem, que julgas os que fazem tais coisas, cuidas que, fazendo-as tu, escaparás ao juízo de Deus?" },
{name:'4524',l:'45',c:'2',v:'4',texto:"Ou desprezas tu as riquezas da sua benignidade, e paciência, e longanimidade, ignorando que a benignidade de Deus te leva ao arrependimento?" },
{name:'4525',l:'45',c:'2',v:'5',texto:"Mas, segundo a tua dureza e teu coração impenitente, entesouras ira para ti no dia da ira e da manifestação do juízo de Deus," },
{name:'4526',l:'45',c:'2',v:'6',texto:"o qual recompensará cada um segundo as suas obras," },
{name:'4527',l:'45',c:'2',v:'7',texto:"a saber: a vida eterna aos que, com perseverança em fazer bem, procuram glória, e honra, e incorrupção;" },
{name:'4528',l:'45',c:'2',v:'8',texto:"mas indignação e ira aos que são contenciosos e desobedientes à verdade e obedientes à iniqüidade;" },
{name:'4529',l:'45',c:'2',v:'9',texto:"tribulação e angústia sobre toda alma do homem que faz o mal, primeiramente do judeu e também do grego;" },
{name:'45210',l:'45',c:'2',v:'10',texto:"glória, porém, e honra e paz a qualquer que faz o bem, primeiramente ao judeu e também ao grego;" },
{name:'45211',l:'45',c:'2',v:'11',texto:"porque, para com Deus, não há acepção de pessoas." },
{name:'45212',l:'45',c:'2',v:'12',texto:"Porque todos os que sem lei pecaram sem lei também perecerão; e todos os que sob a lei pecaram pela lei serão julgados." },
{name:'45213',l:'45',c:'2',v:'13',texto:"Porque os que ouvem a lei não são justos diante de Deus, mas os que praticam a lei hão de ser justificados." },
{name:'45214',l:'45',c:'2',v:'14',texto:"Porque, quando os gentios, que não têm lei, fazem naturalmente as coisas que são da lei, não tendo eles lei, para si mesmos são lei," },
{name:'45215',l:'45',c:'2',v:'15',texto:"os quais mostram a obra da lei escrita no seu coração, testificando juntamente a sua consciência e os seus pensamentos, quer acusando-os, quer defendendo-os," },
{name:'45216',l:'45',c:'2',v:'16',texto:"no dia em que Deus há de julgar os segredos dos homens, por Jesus Cristo, segundo o meu evangelho." },
{name:'45217',l:'45',c:'2',v:'17',texto:"Eis que tu, que tens por sobrenome judeu, e repousas na lei, e te glorias em Deus;" },
{name:'45218',l:'45',c:'2',v:'18',texto:"e sabes a sua vontade, e aprovas as coisas excelentes, sendo instruído por lei;" },
{name:'45219',l:'45',c:'2',v:'19',texto:"e confias que és guia dos cegos, luz dos que estão em trevas," },
{name:'45220',l:'45',c:'2',v:'20',texto:"instruidor dos néscios, mestre de crianças, que tens a forma da ciência e da verdade na lei;" },
{name:'45221',l:'45',c:'2',v:'21',texto:"tu, pois, que ensinas a outro, não te ensinas a ti mesmo? Tu, que pregas que não se deve furtar, furtas?" },
{name:'45222',l:'45',c:'2',v:'22',texto:"Tu, que dizes que não se deve adulterar, adulteras? Tu, que abominas os ídolos, cometes sacrilégio?" },
{name:'45223',l:'45',c:'2',v:'23',texto:"Tu, que te glorias na lei, desonras a Deus pela transgressão da lei?" },
{name:'45224',l:'45',c:'2',v:'24',texto:"Porque, como está escrito, o nome de Deus é blasfemado entre os gentios por causa de vós." },
{name:'45225',l:'45',c:'2',v:'25',texto:"Porque a circuncisão é, na verdade, proveitosa, se tu guardares a lei; mas, se tu és transgressor da lei, a tua circuncisão se torna em incircuncisão." },
{name:'45226',l:'45',c:'2',v:'26',texto:"Se, pois, a incircuncisão guardar os preceitos da lei, porventura, a incircuncisão não será reputada como circuncisão?" },
{name:'45227',l:'45',c:'2',v:'27',texto:"E a incircuncisão que por natureza o é, se cumpre a lei, não te julgará, porventura, a ti, que pela letra e circuncisão és transgressor da lei?" },
{name:'45228',l:'45',c:'2',v:'28',texto:"Porque não é judeu o que o é exteriormente, nem é circuncisão a que o é exteriormente na carne." },
{name:'45229',l:'45',c:'2',v:'29',texto:"Mas é judeu o que o é no interior, e circuncisão, a que é do coração, no espírito, não na letra, cujo louvor não provém dos homens, mas de Deus." },
],
numVersiculos: 29,
},

c3: {
versiculos:[
{name:'4531',l:'45',c:'3',v:'1',texto:"Qual é, logo, a vantagem do judeu? Ou qual a utilidade da circuncisão?" },
{name:'4532',l:'45',c:'3',v:'2',texto:"Muita, em toda maneira, porque, primeiramente, as palavras de Deus lhe foram confiadas." },
{name:'4533',l:'45',c:'3',v:'3',texto:"Pois quê? Se alguns foram incrédulos, a sua incredulidade aniquilará a fidelidade de Deus?" },
{name:'4534',l:'45',c:'3',v:'4',texto:"De maneira nenhuma! Sempre seja Deus verdadeiro, e todo homem mentiroso, como está escrito: Para que sejas justificado em tuas palavras e venças quando fores julgado." },
{name:'4535',l:'45',c:'3',v:'5',texto:"E, se a nossa injustiça for causa da justiça de Deus, que diremos? Porventura, será Deus injusto, trazendo ira sobre nós? ( Falo como homem. )" },
{name:'4536',l:'45',c:'3',v:'6',texto:"De maneira nenhuma! Doutro modo, como julgará Deus o mundo?" },
{name:'4537',l:'45',c:'3',v:'7',texto:"Mas, se pela minha mentira abundou mais a verdade de Deus para glória sua, por que sou eu ainda julgado também como pecador?" },
{name:'4538',l:'45',c:'3',v:'8',texto:"E por que não dizemos ( como somos blasfemados, e como alguns dizem que dizemos ): Façamos males, para que venham bens? A condenação desses é justa." },
{name:'4539',l:'45',c:'3',v:'9',texto:"Pois quê? Somos nós mais excelentes? De maneira nenhuma! Pois já dantes demonstramos que, tanto judeus como gregos, todos estão debaixo do pecado," },
{name:'45310',l:'45',c:'3',v:'10',texto:"como está escrito: Não há um justo, nem um sequer." },
{name:'45311',l:'45',c:'3',v:'11',texto:"Não há ninguém que entenda; não há ninguém que busque a Deus." },
{name:'45312',l:'45',c:'3',v:'12',texto:"Todos se extraviaram e juntamente se fizeram inúteis. Não há quem faça o bem, não há nem um só." },
{name:'45313',l:'45',c:'3',v:'13',texto:"A sua garganta é um sepulcro aberto; com a língua tratam enganosamente; peçonha de áspides está debaixo de seus lábios;" },
{name:'45314',l:'45',c:'3',v:'14',texto:"cuja boca está cheia de maldição e amargura." },
{name:'45315',l:'45',c:'3',v:'15',texto:"Os seus pés são ligeiros para derramar sangue." },
{name:'45316',l:'45',c:'3',v:'16',texto:"Em seus caminhos há destruição e miséria;" },
{name:'45317',l:'45',c:'3',v:'17',texto:"e não conheceram o caminho da paz." },
{name:'45318',l:'45',c:'3',v:'18',texto:"Não há temor de Deus diante de seus olhos." },
{name:'45319',l:'45',c:'3',v:'19',texto:"Ora, nós sabemos que tudo o que a lei diz aos que estão debaixo da lei o diz, para que toda boca esteja fechada e todo o mundo seja condenável diante de Deus." },
{name:'45320',l:'45',c:'3',v:'20',texto:"Por isso, nenhuma carne será justificada diante dele pelas obras da lei, porque pela lei vem o conhecimento do pecado." },
{name:'45321',l:'45',c:'3',v:'21',texto:"Mas, agora, se manifestou, sem a lei, a justiça de Deus, tendo o testemunho da Lei e dos Profetas," },
{name:'45322',l:'45',c:'3',v:'22',texto:"isto é, a justiça de Deus pela fé em Jesus Cristo para todos e sobre todos os que crêem; porque não há diferença." },
{name:'45323',l:'45',c:'3',v:'23',texto:"Porque todos pecaram e destituídos estão da glória de Deus," },
{name:'45324',l:'45',c:'3',v:'24',texto:"sendo justificados gratuitamente pela sua graça, pela redenção que há em Cristo Jesus," },
{name:'45325',l:'45',c:'3',v:'25',texto:"ao qual Deus propôs para propiciação pela fé no seu sangue, para demonstrar a sua justiça pela remissão dos pecados dantes cometidos, sob a paciência de Deus;" },
{name:'45326',l:'45',c:'3',v:'26',texto:"para demonstração da sua justiça neste tempo presente, para que ele seja justo e justificador daquele que tem fé em Jesus." },
{name:'45327',l:'45',c:'3',v:'27',texto:"Onde está, logo, a jactância? É excluída. Por qual lei? Das obras? Não! Mas pela lei da fé." },
{name:'45328',l:'45',c:'3',v:'28',texto:"Concluímos, pois, que o homem é justificado pela fé, sem as obras da lei." },
{name:'45329',l:'45',c:'3',v:'29',texto:"É, porventura, Deus somente dos judeus? E não o é também dos gentios? Também dos gentios, certamente." },
{name:'45330',l:'45',c:'3',v:'30',texto:"Se Deus é um só, que justifica, pela fé, a circuncisão e, por meio da fé, a incircuncisão," },
{name:'45331',l:'45',c:'3',v:'31',texto:"anulamos, pois, a lei pela fé? De maneira nenhuma! Antes, estabelecemos a lei." },
],
numVersiculos: 31,
},

c4: {
versiculos:[
{name:'4541',l:'45',c:'4',v:'1',texto:"Que diremos, pois, ter alcançado Abraão, nosso pai segundo a carne?" },
{name:'4542',l:'45',c:'4',v:'2',texto:"Porque, se Abraão foi justificado pelas obras, tem de que se gloriar, mas não diante de Deus." },
{name:'4543',l:'45',c:'4',v:'3',texto:"Pois, que diz a Escritura? Creu Abraão em Deus, e isso lhe foi imputado como justiça." },
{name:'4544',l:'45',c:'4',v:'4',texto:"Ora, àquele que faz qualquer obra, não lhe é imputado o galardão segundo a graça, mas segundo a dívida." },
{name:'4545',l:'45',c:'4',v:'5',texto:"Mas, àquele que não pratica, porém crê naquele que justifica o ímpio, a sua fé lhe é imputada como justiça." },
{name:'4546',l:'45',c:'4',v:'6',texto:"Assim também Davi declara bem-aventurado o homem a quem Deus imputa a justiça sem as obras, dizendo:" },
{name:'4547',l:'45',c:'4',v:'7',texto:"Bem-aventurados aqueles cujas maldades são perdoadas, e cujos pecados são cobertos." },
{name:'4548',l:'45',c:'4',v:'8',texto:"Bem-aventurado o homem a quem o Senhor não imputa o pecado." },
{name:'4549',l:'45',c:'4',v:'9',texto:"Vem, pois, esta bem-aventurança sobre a circuncisão somente ou também sobre a incircuncisão? Porque dizemos que a fé foi imputada como justiça a Abraão." },
{name:'45410',l:'45',c:'4',v:'10',texto:"Como lhe foi, pois, imputada? Estando na circuncisão ou na incircuncisão? Não na circuncisão, mas na incircuncisão." },
{name:'45411',l:'45',c:'4',v:'11',texto:"E recebeu o sinal da circuncisão, selo da justiça da fé, quando estava na incircuncisão, para que fosse pai de todos os que crêem ( estando eles também na incircuncisão, a fim de que também a justiça lhes seja imputada )," },
{name:'45412',l:'45',c:'4',v:'12',texto:"e fosse pai da circuncisão, daqueles que não somente são da circuncisão, mas que também andam nas pisadas daquela fé de Abraão, nosso pai, que tivera na incircuncisão." },
{name:'45413',l:'45',c:'4',v:'13',texto:"Porque a promessa de que havia de ser herdeiro do mundo não foi feita pela lei a Abraão ou à sua posteridade, mas pela justiça da fé." },
{name:'45414',l:'45',c:'4',v:'14',texto:"Pois, se os que são da lei são herdeiros, logo a fé é vã e a promessa é aniquilada." },
{name:'45415',l:'45',c:'4',v:'15',texto:"Porque a lei opera a ira; porque onde não há lei também não há transgressão." },
{name:'45416',l:'45',c:'4',v:'16',texto:"Portanto, é pela fé, para que seja segundo a graça, a fim de que a promessa seja firme a toda a posteridade, não somente à que é da lei, mas também à que é da fé de Abraão, o qual é pai de todos nós" },
{name:'45417',l:'45',c:'4',v:'17',texto:"( como está escrito: Por pai de muitas nações te constituí. ), perante aquele no qual creu, a saber, Deus, o qual vivifica os mortos e chama as coisas que não são como se já fossem." },
{name:'45418',l:'45',c:'4',v:'18',texto:"O qual, em esperança, creu contra a esperança que seria feito pai de muitas nações, conforme o que lhe fora dito: Assim será a tua descendência." },
{name:'45419',l:'45',c:'4',v:'19',texto:"E não enfraqueceu na fé, nem atentou para o seu próprio corpo já amortecido ( pois era já de quase cem anos ), nem tampouco para o amortecimento do ventre de Sara." },
{name:'45420',l:'45',c:'4',v:'20',texto:"E não duvidou da promessa de Deus por incredulidade, mas foi fortificado na fé, dando glória a Deus;" },
{name:'45421',l:'45',c:'4',v:'21',texto:"e estando certíssimo de que o que ele tinha prometido também era poderoso para o fazer." },
{name:'45422',l:'45',c:'4',v:'22',texto:"Pelo que isso lhe foi também imputado como justiça." },
{name:'45423',l:'45',c:'4',v:'23',texto:"Ora, não só por causa dele está escrito que lhe fosse tomado em conta," },
{name:'45424',l:'45',c:'4',v:'24',texto:"mas também por nós, a quem será tomado em conta, os que cremos naquele que dos mortos ressuscitou a Jesus, nosso Senhor," },
{name:'45425',l:'45',c:'4',v:'25',texto:"o qual por nossos pecados foi entregue e ressuscitou para nossa justificação." },
],
numVersiculos: 25,
},

c5: {
versiculos:[
{name:'4551',l:'45',c:'5',v:'1',texto:"Sendo, pois, justificados pela fé, temos paz com Deus por nosso Senhor Jesus Cristo;" },
{name:'4552',l:'45',c:'5',v:'2',texto:"pelo qual também temos entrada pela fé a esta graça, na qual estamos firmes; e nos gloriamos na esperança da glória de Deus." },
{name:'4553',l:'45',c:'5',v:'3',texto:"E não somente isto, mas também nos gloriamos nas tribulações, sabendo que a tribulação produz a paciência;" },
{name:'4554',l:'45',c:'5',v:'4',texto:"e a paciência, a experiência; e a experiência, a esperança." },
{name:'4555',l:'45',c:'5',v:'5',texto:"E a esperança não traz confusão, porquanto o amor de Deus está derramado em nosso coração pelo Espírito Santo que nos foi dado." },
{name:'4556',l:'45',c:'5',v:'6',texto:"Porque Cristo, estando nós ainda fracos, morreu a seu tempo pelos ímpios." },
{name:'4557',l:'45',c:'5',v:'7',texto:"Porque apenas alguém morrerá por um justo; pois poderá ser que pelo bom alguém ouse morrer." },
{name:'4558',l:'45',c:'5',v:'8',texto:"Mas Deus prova o seu amor para conosco em que Cristo morreu por nós, sendo nós ainda pecadores." },
{name:'4559',l:'45',c:'5',v:'9',texto:"Logo, muito mais agora, sendo justificados pelo seu sangue, seremos por ele salvos da ira." },
{name:'45510',l:'45',c:'5',v:'10',texto:"Porque, se nós, sendo inimigos, fomos reconciliados com Deus pela morte de seu Filho, muito mais, estando já reconciliados, seremos salvos pela sua vida." },
{name:'45511',l:'45',c:'5',v:'11',texto:"E não somente isto, mas também nos gloriamos em Deus por nosso Senhor Jesus Cristo, pelo qual agora alcançamos a reconciliação." },
{name:'45512',l:'45',c:'5',v:'12',texto:"Pelo que, como por um homem entrou o pecado no mundo, e pelo pecado, a morte, assim também a morte passou a todos os homens, por isso que todos pecaram." },
{name:'45513',l:'45',c:'5',v:'13',texto:"Porque até à lei estava o pecado no mundo, mas o pecado não é imputado não havendo lei." },
{name:'45514',l:'45',c:'5',v:'14',texto:"No entanto, a morte reinou desde Adão até Moisés, até sobre aqueles que não pecaram à semelhança da transgressão de Adão, o qual é a figura daquele que havia de vir." },
{name:'45515',l:'45',c:'5',v:'15',texto:"Mas não é assim o dom gratuito como a ofensa; porque, se, pela ofensa de um, morreram muitos, muito mais a graça de Deus e o dom pela graça, que é de um só homem, Jesus Cristo, abundou sobre muitos." },
{name:'45516',l:'45',c:'5',v:'16',texto:"E não foi assim o dom como a ofensa, por um só que pecou; porque o juízo veio de uma só ofensa, na verdade, para condenação, mas o dom gratuito veio de muitas ofensas para justificação." },
{name:'45517',l:'45',c:'5',v:'17',texto:"Porque, se, pela ofensa de um só, a morte reinou por esse, muito mais os que recebem a abundância da graça e do dom da justiça reinarão em vida por um só, Jesus Cristo." },
{name:'45518',l:'45',c:'5',v:'18',texto:"Pois assim como por uma só ofensa veio o juízo sobre todos os homens para condenação, assim também por um só ato de justiça veio a graça sobre todos os homens para justificação de vida." },
{name:'45519',l:'45',c:'5',v:'19',texto:"Porque, como, pela desobediência de um só homem, muitos foram feitos pecadores, assim, pela obediência de um, muitos serão feitos justos." },
{name:'45520',l:'45',c:'5',v:'20',texto:"Veio, porém, a lei para que a ofensa abundasse; mas, onde o pecado abundou, superabundou a graça;" },
{name:'45521',l:'45',c:'5',v:'21',texto:"para que, assim como o pecado reinou na morte, também a graça reinasse pela justiça para a vida eterna, por Jesus Cristo, nosso Senhor." },
],
numVersiculos: 21,
},

c6: {
versiculos:[
{name:'4561',l:'45',c:'6',v:'1',texto:"Que diremos, pois? Permaneceremos no pecado, para que a graça seja mais abundante?" },
{name:'4562',l:'45',c:'6',v:'2',texto:"De modo nenhum! Nós que estamos mortos para o pecado, como viveremos ainda nele?" },
{name:'4563',l:'45',c:'6',v:'3',texto:"Ou não sabeis que todos quantos fomos batizados em Jesus Cristo fomos batizados na sua morte?" },
{name:'4564',l:'45',c:'6',v:'4',texto:"De sorte que fomos sepultados com ele pelo batismo na morte; para que, como Cristo ressuscitou dos mortos pela glória do Pai, assim andemos nós também em novidade de vida." },
{name:'4565',l:'45',c:'6',v:'5',texto:"Porque, se fomos plantados juntamente com ele na semelhança da sua morte, também o seremos na da sua ressurreição;" },
{name:'4566',l:'45',c:'6',v:'6',texto:"sabendo isto: que o nosso velho homem foi com ele crucificado, para que o corpo do pecado seja desfeito, a fim de que não sirvamos mais ao pecado." },
{name:'4567',l:'45',c:'6',v:'7',texto:"Porque aquele que está morto está justificado do pecado." },
{name:'4568',l:'45',c:'6',v:'8',texto:"Ora, se já morremos com Cristo, cremos que também com ele viveremos;" },
{name:'4569',l:'45',c:'6',v:'9',texto:"sabendo que, havendo Cristo ressuscitado dos mortos, já não morre; a morte não mais terá domínio sobre ele." },
{name:'45610',l:'45',c:'6',v:'10',texto:"Pois, quanto a ter morrido, de uma vez morreu para o pecado; mas, quanto a viver, vive para Deus." },
{name:'45611',l:'45',c:'6',v:'11',texto:"Assim também vós considerai-vos como mortos para o pecado, mas vivos para Deus, em Cristo Jesus, nosso Senhor." },
{name:'45612',l:'45',c:'6',v:'12',texto:"Não reine, portanto, o pecado em vosso corpo mortal, para lhe obedecerdes em suas concupiscências;" },
{name:'45613',l:'45',c:'6',v:'13',texto:"nem tampouco apresenteis os vossos membros ao pecado por instrumentos de iniqüidade; mas apresentai-vos a Deus, como vivos dentre mortos, e os vossos membros a Deus, como instrumentos de justiça." },
{name:'45614',l:'45',c:'6',v:'14',texto:"Porque o pecado não terá domínio sobre vós, pois não estais debaixo da lei, mas debaixo da graça." },
{name:'45615',l:'45',c:'6',v:'15',texto:"Pois quê? Pecaremos porque não estamos debaixo da lei, mas debaixo da graça? De modo nenhum!" },
{name:'45616',l:'45',c:'6',v:'16',texto:"Não sabeis vós que a quem vos apresentardes por servos para lhe obedecer, sois servos daquele a quem obedeceis, ou do pecado para a morte, ou da obediência para a justiça?" },
{name:'45617',l:'45',c:'6',v:'17',texto:"Mas graças a Deus que, tendo sido servos do pecado, obedecestes de coração à forma de doutrina a que fostes entregues." },
{name:'45618',l:'45',c:'6',v:'18',texto:"E, libertados do pecado, fostes feitos servos da justiça." },
{name:'45619',l:'45',c:'6',v:'19',texto:"Falo como homem, pela fraqueza da vossa carne; pois que, assim como apresentastes os vossos membros para servirem à imundícia e à maldade para a maldade, assim apresentai agora os vossos membros para servirem à justiça para a santificação." },
{name:'45620',l:'45',c:'6',v:'20',texto:"Porque, quando éreis servos do pecado, estáveis livres da justiça." },
{name:'45621',l:'45',c:'6',v:'21',texto:"E que fruto tínheis, então, das coisas de que agora vos envergonhais? Porque o fim delas é a morte." },
{name:'45622',l:'45',c:'6',v:'22',texto:"Mas, agora, libertados do pecado e feitos servos de Deus, tendes o vosso fruto para santificação, e por fim a vida eterna." },
{name:'45623',l:'45',c:'6',v:'23',texto:"Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna, por Cristo Jesus, nosso Senhor." },
],
numVersiculos: 23,
},

c7: {
versiculos:[
{name:'4571',l:'45',c:'7',v:'1',texto:"Não sabeis vós, irmãos ( pois que falo aos que sabem a lei ), que a lei tem domínio sobre o homem por todo o tempo que vive?" },
{name:'4572',l:'45',c:'7',v:'2',texto:"Porque a mulher que está sujeita ao marido, enquanto ele viver, está-lhe ligada pela lei; mas, morto o marido, está livre da lei do marido." },
{name:'4573',l:'45',c:'7',v:'3',texto:"De sorte que, vivendo o marido, será chamada adúltera se for doutro marido; mas, morto o marido, livre está da lei e assim não será adúltera se for doutro marido." },
{name:'4574',l:'45',c:'7',v:'4',texto:"Assim, meus irmãos, também vós estais mortos para a lei pelo corpo de Cristo, para que sejais doutro, daquele que ressuscitou de entre os mortos, a fim de que demos fruto para Deus." },
{name:'4575',l:'45',c:'7',v:'5',texto:"Porque, quando estávamos na carne, as paixões dos pecados, que são pela lei, operavam em nossos membros para darem fruto para a morte." },
{name:'4576',l:'45',c:'7',v:'6',texto:"Mas, agora, estamos livres da lei, pois morremos para aquilo em que estávamos retidos; para que sirvamos em novidade de espírito, e não na velhice da letra." },
{name:'4577',l:'45',c:'7',v:'7',texto:"Que diremos, pois? É a lei pecado? De modo nenhum! Mas eu não conheci o pecado senão pela lei; porque eu não conheceria a concupiscência, se a lei não dissesse: Não cobiçarás." },
{name:'4578',l:'45',c:'7',v:'8',texto:"Mas o pecado, tomando ocasião pelo mandamento, despertou em mim toda a concupiscência: porquanto, sem a lei, estava morto o pecado." },
{name:'4579',l:'45',c:'7',v:'9',texto:"E eu, nalgum tempo, vivia sem lei, mas, vindo o mandamento, reviveu o pecado, e eu morri;" },
{name:'45710',l:'45',c:'7',v:'10',texto:"e o mandamento que era para vida, achei eu que me era para morte." },
{name:'45711',l:'45',c:'7',v:'11',texto:"Porque o pecado, tomando ocasião pelo mandamento, me enganou e, por ele, me matou." },
{name:'45712',l:'45',c:'7',v:'12',texto:"Assim, a lei é santa; e o mandamento, santo, justo e bom." },
{name:'45713',l:'45',c:'7',v:'13',texto:"Logo, tornou-se-me o bom em morte? De modo nenhum! Mas o pecado, para que se mostrasse pecado, operou em mim a morte pelo bem, a fim de que pelo mandamento o pecado se fizesse excessivamente maligno." },
{name:'45714',l:'45',c:'7',v:'14',texto:"Porque bem sabemos que a lei é espiritual; mas eu sou carnal, vendido sob o pecado." },
{name:'45715',l:'45',c:'7',v:'15',texto:"Porque o que faço, não o aprovo, pois o que quero, isso não faço; mas o que aborreço, isso faço." },
{name:'45716',l:'45',c:'7',v:'16',texto:"E, se faço o que não quero, consinto com a lei, que é boa." },
{name:'45717',l:'45',c:'7',v:'17',texto:"De maneira que, agora, já não sou eu que faço isto, mas o pecado que habita em mim." },
{name:'45718',l:'45',c:'7',v:'18',texto:"Porque eu sei que em mim, isto é, na minha carne, não habita bem algum; e, com efeito, o querer está em mim, mas não consigo realizar o bem." },
{name:'45719',l:'45',c:'7',v:'19',texto:"Porque não faço o bem que quero, mas o mal que não quero, esse faço." },
{name:'45720',l:'45',c:'7',v:'20',texto:"Ora, se eu faço o que não quero, já o não faço eu, mas o pecado que habita em mim." },
{name:'45721',l:'45',c:'7',v:'21',texto:"Acho, então, esta lei em mim: que, quando quero fazer o bem, o mal está comigo." },
{name:'45722',l:'45',c:'7',v:'22',texto:"Porque, segundo o homem interior, tenho prazer na lei de Deus." },
{name:'45723',l:'45',c:'7',v:'23',texto:"Mas vejo nos meus membros outra lei que batalha contra a lei do meu entendimento e me prende debaixo da lei do pecado que está nos meus membros." },
{name:'45724',l:'45',c:'7',v:'24',texto:"Miserável homem que eu sou! Quem me livrará do corpo desta morte?" },
{name:'45725',l:'45',c:'7',v:'25',texto:"Dou graças a Deus por Jesus Cristo, nosso Senhor. Assim que eu mesmo, com o entendimento, sirvo à lei de Deus, mas, com a carne, à lei do pecado." },
],
numVersiculos: 25,
},

c8: {
versiculos:[
{name:'4581',l:'45',c:'8',v:'1',texto:"Portanto, agora, nenhuma condenação há para os que estão em Cristo Jesus, que não andam segundo a carne, mas segundo o espírito." },
{name:'4582',l:'45',c:'8',v:'2',texto:"Porque a lei do Espírito de vida, em Cristo Jesus, me livrou da lei do pecado e da morte." },
{name:'4583',l:'45',c:'8',v:'3',texto:"Porquanto, o que era impossível à lei, visto como estava enferma pela carne, Deus, enviando o seu Filho em semelhança da carne do pecado, pelo pecado condenou o pecado na carne," },
{name:'4584',l:'45',c:'8',v:'4',texto:"para que a justiça da lei se cumprisse em nós, que não andamos segundo a carne, mas segundo o Espírito." },
{name:'4585',l:'45',c:'8',v:'5',texto:"Porque os que são segundo a carne inclinam-se para as coisas da carne; mas os que são segundo o Espírito, para as coisas do Espírito." },
{name:'4586',l:'45',c:'8',v:'6',texto:"Porque a inclinação da carne é morte; mas a inclinação do Espírito é vida e paz." },
{name:'4587',l:'45',c:'8',v:'7',texto:"Porquanto a inclinação da carne é inimizade contra Deus, pois não é sujeita à lei de Deus, nem, em verdade, o pode ser." },
{name:'4588',l:'45',c:'8',v:'8',texto:"Portanto, os que estão na carne não podem agradar a Deus." },
{name:'4589',l:'45',c:'8',v:'9',texto:"Vós, porém, não estais na carne, mas no Espírito, se é que o Espírito de Deus habita em vós. Mas, se alguém não tem o Espírito de Cristo, esse tal não é dele." },
{name:'45810',l:'45',c:'8',v:'10',texto:"E, se Cristo está em vós, o corpo, na verdade, está morto por causa do pecado, mas o espírito vive por causa da justiça." },
{name:'45811',l:'45',c:'8',v:'11',texto:"E, se o Espírito daquele que dos mortos ressuscitou a Jesus habita em vós, aquele que dos mortos ressuscitou a Cristo também vivificará o vosso corpo mortal, pelo seu Espírito que em vós habita." },
{name:'45812',l:'45',c:'8',v:'12',texto:"De maneira que, irmãos, somos devedores, não à carne para viver segundo a carne," },
{name:'45813',l:'45',c:'8',v:'13',texto:"porque, se viverdes segundo a carne, morrereis; mas, se pelo espírito mortificardes as obras do corpo, vivereis." },
{name:'45814',l:'45',c:'8',v:'14',texto:"Porque todos os que são guiados pelo Espírito de Deus, esses são filhos de Deus." },
{name:'45815',l:'45',c:'8',v:'15',texto:"Porque não recebestes o espírito de escravidão, para, outra vez, estardes em temor, mas recebestes o espírito de adoção de filhos, pelo qual clamamos: Aba, Pai." },
{name:'45816',l:'45',c:'8',v:'16',texto:"O mesmo Espírito testifica com o nosso espírito que somos filhos de Deus." },
{name:'45817',l:'45',c:'8',v:'17',texto:"E, se nós somos filhos, somos, logo, herdeiros também, herdeiros de Deus e co-herdeiros de Cristo; se é certo que com ele padecemos, para que também com ele sejamos glorificados." },
{name:'45818',l:'45',c:'8',v:'18',texto:"Porque para mim tenho por certo que as aflições deste tempo presente não são para comparar com a glória que em nós há de ser revelada." },
{name:'45819',l:'45',c:'8',v:'19',texto:"Porque a ardente expectação da criatura espera a manifestação dos filhos de Deus." },
{name:'45820',l:'45',c:'8',v:'20',texto:"Porque a criação ficou sujeita à vaidade, não por sua vontade, mas por causa do que a sujeitou," },
{name:'45821',l:'45',c:'8',v:'21',texto:"na esperança de que também a mesma criatura será libertada da servidão da corrupção, para a liberdade da glória dos filhos de Deus." },
{name:'45822',l:'45',c:'8',v:'22',texto:"Porque sabemos que toda a criação geme e está juntamente com dores de parto até agora." },
{name:'45823',l:'45',c:'8',v:'23',texto:"E não só ela, mas nós mesmos, que temos as primícias do Espírito, também gememos em nós mesmos, esperando a adoção, a saber, a redenção do nosso corpo." },
{name:'45824',l:'45',c:'8',v:'24',texto:"Porque, em esperança, somos salvos. Ora, a esperança que se vê não é esperança; porque o que alguém vê, como o esperará?" },
{name:'45825',l:'45',c:'8',v:'25',texto:"Mas, se esperamos o que não vemos, com paciência o esperamos." },
{name:'45826',l:'45',c:'8',v:'26',texto:"E da mesma maneira também o Espírito ajuda as nossas fraquezas; porque não sabemos o que havemos de pedir como convém, mas o mesmo Espírito intercede por nós com gemidos inexprimíveis." },
{name:'45827',l:'45',c:'8',v:'27',texto:"E aquele que examina os corações sabe qual é a intenção do Espírito; e é ele que segundo Deus intercede pelos santos." },
{name:'45828',l:'45',c:'8',v:'28',texto:"E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus, daqueles que são chamados por seu decreto." },
{name:'45829',l:'45',c:'8',v:'29',texto:"Porque os que dantes conheceu, também os predestinou para serem conformes à imagem de seu Filho, a fim de que ele seja o primogênito entre muitos irmãos." },
{name:'45830',l:'45',c:'8',v:'30',texto:"E aos que predestinou, a esses também chamou; e aos que chamou, a esses também justificou; e aos que justificou, a esses também glorificou." },
{name:'45831',l:'45',c:'8',v:'31',texto:"Que diremos, pois, a estas coisas? Se Deus é por nós, quem será contra nós?" },
{name:'45832',l:'45',c:'8',v:'32',texto:"Aquele que nem mesmo a seu próprio Filho poupou, antes, o entregou por todos nós, como nos não dará também com ele todas as coisas?" },
{name:'45833',l:'45',c:'8',v:'33',texto:"Quem intentará acusação contra os escolhidos de Deus? É Deus quem os justifica." },
{name:'45834',l:'45',c:'8',v:'34',texto:"Quem os condenará? Pois é Cristo quem morreu ou, antes, quem ressuscitou dentre os mortos, o qual está à direita de Deus, e também intercede por nós." },
{name:'45835',l:'45',c:'8',v:'35',texto:"Quem nos separará do amor de Cristo? A tribulação, ou a angústia, ou a perseguição, ou a fome, ou a nudez, ou o perigo, ou a espada?" },
{name:'45836',l:'45',c:'8',v:'36',texto:"Como está escrito: Por amor de ti somos entregues à morte todo o dia: fomos reputados como ovelhas para o matadouro." },
{name:'45837',l:'45',c:'8',v:'37',texto:"Mas em todas estas coisas somos mais do que vencedores, por aquele que nos amou." },
{name:'45838',l:'45',c:'8',v:'38',texto:"Porque estou certo de que nem a morte, nem a vida, nem os anjos, nem os principados, nem as potestades, nem o presente, nem o porvir," },
{name:'45839',l:'45',c:'8',v:'39',texto:"nem a altura, nem a profundidade, nem alguma outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus, nosso Senhor!" },
],
numVersiculos: 39,
},

c9: {
versiculos:[
{name:'4591',l:'45',c:'9',v:'1',texto:"Em Cristo digo a verdade, não minto ( dando-me testemunho a minha consciência no Espírito Santo ):" },
{name:'4592',l:'45',c:'9',v:'2',texto:"tenho grande tristeza e contínua dor no meu coração." },
{name:'4593',l:'45',c:'9',v:'3',texto:"Porque eu mesmo poderia desejar ser separado de Cristo, por amor de meus irmãos, que são meus parentes segundo a carne;" },
{name:'4594',l:'45',c:'9',v:'4',texto:"que são israelitas, dos quais é a adoção de filhos, e a glória, e os concertos, e a lei, e o culto, e as promessas;" },
{name:'4595',l:'45',c:'9',v:'5',texto:"dos quais são os pais, e dos quais é Cristo, segundo a carne, o qual é sobre todos, Deus bendito eternamente. Amém!" },
{name:'4596',l:'45',c:'9',v:'6',texto:"Não que a palavra de Deus haja faltado, porque nem todos os que são de Israel são israelitas;" },
{name:'4597',l:'45',c:'9',v:'7',texto:"nem por serem descendência de Abraão são todos filhos; mas: Em Isaque será chamada a tua descendência." },
{name:'4598',l:'45',c:'9',v:'8',texto:"Isto é, não são os filhos da carne que são filhos de Deus, mas os filhos da promessa são contados como descendência." },
{name:'4599',l:'45',c:'9',v:'9',texto:"Porque a palavra da promessa é esta: Por este tempo virei, e Sara terá um filho." },
{name:'45910',l:'45',c:'9',v:'10',texto:"E não somente esta, mas também Rebeca, quando concebeu de um, de Isaque, nosso pai;" },
{name:'45911',l:'45',c:'9',v:'11',texto:"porque, não tendo eles ainda nascido, nem tendo feito bem ou mal ( para que o propósito de Deus, segundo a eleição, ficasse firme, não por causa das obras, mas por aquele que chama )," },
{name:'45912',l:'45',c:'9',v:'12',texto:"foi-lhe dito a ela: O maior servirá o menor." },
{name:'45913',l:'45',c:'9',v:'13',texto:"Como está escrito: Amei Jacó e aborreci Esaú." },
{name:'45914',l:'45',c:'9',v:'14',texto:"Que diremos, pois? Que há injustiça da parte de Deus? De maneira nenhuma!" },
{name:'45915',l:'45',c:'9',v:'15',texto:"Pois diz a Moisés: Compadecer-me-ei de quem me compadecer e terei misericórdia de quem eu tiver misericórdia." },
{name:'45916',l:'45',c:'9',v:'16',texto:"Assim, pois, isto não depende do que quer, nem do que corre, mas de Deus, que se compadece." },
{name:'45917',l:'45',c:'9',v:'17',texto:"Porque diz a Escritura a Faraó: Para isto mesmo te levantei, para em ti mostrar o meu poder e para que o meu nome seja anunciado em toda a terra." },
{name:'45918',l:'45',c:'9',v:'18',texto:"Logo, pois, compadece-se de quem quer e endurece a quem quer." },
{name:'45919',l:'45',c:'9',v:'19',texto:"Dir-me-ás, então: Por que se queixa ele ainda? Porquanto, quem resiste à sua vontade?" },
{name:'45920',l:'45',c:'9',v:'20',texto:"Mas, ó homem, quem és tu, que a Deus replicas? Porventura, a coisa formada dirá ao que a formou: Por que me fizeste assim?" },
{name:'45921',l:'45',c:'9',v:'21',texto:"Ou não tem o oleiro poder sobre o barro, para da mesma massa fazer um vaso para honra e outro para desonra?" },
{name:'45922',l:'45',c:'9',v:'22',texto:"E que direis se Deus, querendo mostrar a sua ira e dar a conhecer o seu poder, suportou com muita paciência os vasos da ira, preparados para perdição," },
{name:'45923',l:'45',c:'9',v:'23',texto:"para que também desse a conhecer as riquezas da sua glória nos vasos de misericórdia, que para glória já dantes preparou," },
{name:'45924',l:'45',c:'9',v:'24',texto:"os quais somos nós, a quem também chamou, não só dentre os judeus, mas também dentre os gentios?" },
{name:'45925',l:'45',c:'9',v:'25',texto:"Como também diz em Oséias: Chamarei meu povo ao que não era meu povo; e amada, à que não era amada." },
{name:'45926',l:'45',c:'9',v:'26',texto:"E sucederá que no lugar em que lhes foi dito: Vós não sois meu povo, aí serão chamados filhos do Deus vivo." },
{name:'45927',l:'45',c:'9',v:'27',texto:"Também Isaías clamava acerca de Israel: Ainda que o número dos filhos de Israel seja como a areia do mar, o remanescente é que será salvo." },
{name:'45928',l:'45',c:'9',v:'28',texto:"Porque o Senhor executará a sua palavra sobre a terra, completando-a e abreviando-a." },
{name:'45929',l:'45',c:'9',v:'29',texto:"E como antes disse Isaías: Se o Senhor dos Exércitos nos não deixara descendência, teríamos sido feitos como Sodoma e seríamos semelhantes a Gomorra." },
{name:'45930',l:'45',c:'9',v:'30',texto:"Que diremos, pois? Que os gentios, que não buscavam a justiça, alcançaram a justiça? Sim, mas a justiça que é pela fé." },
{name:'45931',l:'45',c:'9',v:'31',texto:"Mas Israel, que buscava a lei da justiça, não chegou à lei da justiça." },
{name:'45932',l:'45',c:'9',v:'32',texto:"Por quê? Porque não foi pela fé, mas como que pelas obras da lei. Tropeçaram na pedra de tropeço," },
{name:'45933',l:'45',c:'9',v:'33',texto:"como está escrito: Eis que eu ponho em Sião uma pedra de tropeço e uma rocha de escândalo; e todo aquele que crer nela não será confundido." },
],
numVersiculos: 33,
},

c10: {
versiculos:[
{name:'45101',l:'45',c:'10',v:'1',texto:"Irmãos, o bom desejo do meu coração e a oração a Deus por Israel é para sua salvação." },
{name:'45102',l:'45',c:'10',v:'2',texto:"Porque lhes dou testemunho de que têm zelo de Deus, mas não com entendimento." },
{name:'45103',l:'45',c:'10',v:'3',texto:"Porquanto, não conhecendo a justiça de Deus e procurando estabelecer a sua própria justiça, não se sujeitaram à justiça de Deus." },
{name:'45104',l:'45',c:'10',v:'4',texto:"Porque o fim da lei é Cristo para justiça de todo aquele que crê." },
{name:'45105',l:'45',c:'10',v:'5',texto:"Ora, Moisés descreve a justiça que é pela lei, dizendo: O homem que fizer estas coisas viverá por elas." },
{name:'45106',l:'45',c:'10',v:'6',texto:"Mas a justiça que é pela fé diz assim: Não digas em teu coração: Quem subirá ao céu ( isto é, a trazer do alto a Cristo )?" },
{name:'45107',l:'45',c:'10',v:'7',texto:"Ou: Quem descerá ao abismo ( isto é, a tornar a trazer dentre os mortos a Cristo )?" },
{name:'45108',l:'45',c:'10',v:'8',texto:"Mas que diz? A palavra está junto de ti, na tua boca e no teu coração; esta é a palavra da fé, que pregamos," },
{name:'45109',l:'45',c:'10',v:'9',texto:"a saber: Se, com a tua boca, confessares ao Senhor Jesus e, em teu coração, creres que Deus o ressuscitou dos mortos, serás salvo." },
{name:'451010',l:'45',c:'10',v:'10',texto:"Visto que com o coração se crê para a justiça, e com a boca se faz confissão para a salvação." },
{name:'451011',l:'45',c:'10',v:'11',texto:"Porque a Escritura diz: Todo aquele que nele crer não será confundido." },
{name:'451012',l:'45',c:'10',v:'12',texto:"Porquanto não há diferença entre judeu e grego, porque um mesmo é o Senhor de todos, rico para com todos os que o invocam." },
{name:'451013',l:'45',c:'10',v:'13',texto:"Porque todo aquele que invocar o nome do Senhor será salvo." },
{name:'451014',l:'45',c:'10',v:'14',texto:"Como, pois, invocarão aquele em quem não creram? E como crerão naquele de quem não ouviram? E como ouvirão, se não há quem pregue?" },
{name:'451015',l:'45',c:'10',v:'15',texto:"E como pregarão, se não forem enviados? Como está escrito: Quão formosos os pés dos que anunciam a paz, dos que anunciam coisas boas!" },
{name:'451016',l:'45',c:'10',v:'16',texto:"Mas nem todos obedecem ao evangelho; pois Isaías diz: Senhor, quem creu na nossa pregação?" },
{name:'451017',l:'45',c:'10',v:'17',texto:"De sorte que a fé é pelo ouvir, e o ouvir pela palavra de Deus." },
{name:'451018',l:'45',c:'10',v:'18',texto:"Mas digo: Porventura, não ouviram? Sim, por certo, pois por toda a terra saiu a voz deles, e as suas palavras até aos confins do mundo." },
{name:'451019',l:'45',c:'10',v:'19',texto:"Mas digo: Porventura, Israel não o soube? Primeiramente, diz Moisés: Eu vos meterei em ciúmes com aqueles que não são povo, com gente insensata vos provocarei à ira." },
{name:'451020',l:'45',c:'10',v:'20',texto:"E Isaías ousadamente diz: Fui achado pelos que me não buscavam, fui manifestado aos que por mim não perguntavam." },
{name:'451021',l:'45',c:'10',v:'21',texto:"Mas contra Israel diz: Todo o dia estendi as minhas mãos a um povo rebelde e contradizente." },
],
numVersiculos: 21,
},

c11: {
versiculos:[
{name:'45111',l:'45',c:'11',v:'1',texto:"Digo, pois: porventura, rejeitou Deus o seu povo? De modo nenhum! Porque também eu sou israelita, da descendência de Abraão, da tribo de Benjamim." },
{name:'45112',l:'45',c:'11',v:'2',texto:"Deus não rejeitou o seu povo, que antes conheceu. Ou não sabeis o que a Escritura diz de Elias, como fala a Deus contra Israel, dizendo:" },
{name:'45113',l:'45',c:'11',v:'3',texto:"Senhor, mataram os teus profetas e derribaram os teus altares; e só eu fiquei, e buscam a minha alma?" },
{name:'45114',l:'45',c:'11',v:'4',texto:"Mas que lhe diz a resposta divina? Reservei para mim sete mil varões, que não dobraram os joelhos diante de Baal." },
{name:'45115',l:'45',c:'11',v:'5',texto:"Assim, pois, também agora neste tempo ficou um resto, segundo a eleição da graça." },
{name:'45116',l:'45',c:'11',v:'6',texto:"Mas, se é por graça, já não é pelas obras; de outra maneira, a graça já não é graça." },
{name:'45117',l:'45',c:'11',v:'7',texto:"Pois quê? O que Israel buscava não o alcançou; mas os eleitos o alcançaram, e os outros foram endurecidos." },
{name:'45118',l:'45',c:'11',v:'8',texto:"Como está escrito: Deus lhes deu espírito de profundo sono: olhos para não verem e ouvidos para não ouvirem, até ao dia de hoje." },
{name:'45119',l:'45',c:'11',v:'9',texto:"E Davi diz: Torne-se-lhes a sua mesa em laço, e em armadilha, e em tropeço, por sua retribuição;" },
{name:'451110',l:'45',c:'11',v:'10',texto:"escureçam-se-lhes os olhos para não verem, e encurvem-se-lhes continuamente as costas." },
{name:'451111',l:'45',c:'11',v:'11',texto:"Digo, pois: porventura, tropeçaram, para que caíssem? De modo nenhum! Mas, pela sua queda, veio a salvação aos gentios, para os incitar à emulação." },
{name:'451112',l:'45',c:'11',v:'12',texto:"E, se a sua queda é a riqueza do mundo, e a sua diminuição, a riqueza dos gentios, quanto mais a sua plenitude!" },
{name:'451113',l:'45',c:'11',v:'13',texto:"Porque convosco falo, gentios, que, enquanto for apóstolo dos gentios, glorificarei o meu ministério;" },
{name:'451114',l:'45',c:'11',v:'14',texto:"para ver se de alguma maneira posso incitar à emulação os da minha carne e salvar alguns deles." },
{name:'451115',l:'45',c:'11',v:'15',texto:"Porque, se a sua rejeição é a reconciliação do mundo, qual será a sua admissão, senão a vida dentre os mortos?" },
{name:'451116',l:'45',c:'11',v:'16',texto:"E, se as primícias são santas, também a massa o é; se a raiz é santa, também os ramos o são." },
{name:'451117',l:'45',c:'11',v:'17',texto:"E se alguns dos ramos foram quebrados, e tu, sendo zambujeiro, foste enxertado em lugar deles e feito participante da raiz e da seiva da oliveira," },
{name:'451118',l:'45',c:'11',v:'18',texto:"não te glories contra os ramos; e, se contra eles te gloriares, não és tu que sustentas a raiz, mas a raiz a ti." },
{name:'451119',l:'45',c:'11',v:'19',texto:"Dirás, pois: Os ramos foram quebrados, para que eu fosse enxertado." },
{name:'451120',l:'45',c:'11',v:'20',texto:"Está bem! Pela sua incredulidade foram quebrados, e tu estás em pé pela fé; então, não te ensoberbeças, mas teme." },
{name:'451121',l:'45',c:'11',v:'21',texto:"Porque, se Deus não poupou os ramos naturais, teme que te não poupe a ti também." },
{name:'451122',l:'45',c:'11',v:'22',texto:"Considera, pois, a bondade e a severidade de Deus: para com os que caíram, severidade; mas, para contigo, a benignidade de Deus, se permaneceres na sua benignidade; de outra maneira, também tu serás cortado." },
{name:'451123',l:'45',c:'11',v:'23',texto:"E também eles, se não permanecerem na incredulidade, serão enxertados; porque poderoso é Deus para os tornar a enxertar." },
{name:'451124',l:'45',c:'11',v:'24',texto:"Porque, se tu foste cortado do natural zambujeiro e, contra a natureza, enxertado na boa oliveira, quanto mais esses, que são naturais, serão enxertados na sua própria oliveira!" },
{name:'451125',l:'45',c:'11',v:'25',texto:"Porque não quero, irmãos, que ignoreis este segredo ( para que não presumais de vós mesmos ): que o endurecimento veio em parte sobre Israel, até que a plenitude dos gentios haja entrado." },
{name:'451126',l:'45',c:'11',v:'26',texto:"E, assim, todo o Israel será salvo, como está escrito: De Sião virá o Libertador, e desviará de Jacó as impiedades." },
{name:'451127',l:'45',c:'11',v:'27',texto:"E este será o meu concerto com eles, quando eu tirar os seus pecados." },
{name:'451128',l:'45',c:'11',v:'28',texto:"Assim que, quanto ao evangelho, são inimigos por causa de vós; mas, quanto à eleição, amados por causa dos pais." },
{name:'451129',l:'45',c:'11',v:'29',texto:"Porque os dons e a vocação de Deus são sem arrependimento." },
{name:'451130',l:'45',c:'11',v:'30',texto:"Porque assim como vós também, antigamente, fostes desobedientes a Deus, mas, agora, alcançastes misericórdia pela desobediência deles," },
{name:'451131',l:'45',c:'11',v:'31',texto:"assim também estes, agora, foram desobedientes, para também alcançarem misericórdia pela misericórdia a vós demonstrada." },
{name:'451132',l:'45',c:'11',v:'32',texto:"Porque Deus encerrou a todos debaixo da desobediência, para com todos usar de misericórdia." },
{name:'451133',l:'45',c:'11',v:'33',texto:"Ó profundidade das riquezas, tanto da sabedoria, como da ciência de Deus! Quão insondáveis são os seus juízos, e quão inescrutáveis, os seus caminhos!" },
{name:'451134',l:'45',c:'11',v:'34',texto:"Porque quem compreendeu o intento do Senhor? Ou quem foi seu conselheiro?" },
{name:'451135',l:'45',c:'11',v:'35',texto:"Ou quem lhe deu primeiro a ele, para que lhe seja recompensado?" },
{name:'451136',l:'45',c:'11',v:'36',texto:"Porque dele, e por ele, e para ele são todas as coisas; glória, pois, a ele eternamente. Amém!" },
],
numVersiculos: 36,
},

c12: {
versiculos:[
{name:'45121',l:'45',c:'12',v:'1',texto:"Rogo-vos, pois, irmãos, pela compaixão de Deus, que apresenteis o vosso corpo em sacrifício vivo, santo e agradável a Deus, que é o vosso culto racional." },
{name:'45122',l:'45',c:'12',v:'2',texto:"E não vos conformeis com este mundo, mas transformai-vos pela renovação do vosso entendimento, para que experimenteis qual seja a boa, agradável e perfeita vontade de Deus." },
{name:'45123',l:'45',c:'12',v:'3',texto:"Porque, pela graça que me é dada, digo a cada um dentre vós que não saiba mais do que convém saber, mas que saiba com temperança, conforme a medida da fé que Deus repartiu a cada um." },
{name:'45124',l:'45',c:'12',v:'4',texto:"Porque assim como em um corpo temos muitos membros, e nem todos os membros têm a mesma operação," },
{name:'45125',l:'45',c:'12',v:'5',texto:"assim nós, que somos muitos, somos um só corpo em Cristo, mas individualmente somos membros uns dos outros." },
{name:'45126',l:'45',c:'12',v:'6',texto:"De modo que, tendo diferentes dons, segundo a graça que nos é dada: se é profecia, seja ela segundo a medida da fé;" },
{name:'45127',l:'45',c:'12',v:'7',texto:"se é ministério, seja em ministrar; se é ensinar, haja dedicação ao ensino;" },
{name:'45128',l:'45',c:'12',v:'8',texto:"ou o que exorta, use esse dom em exortar; o que reparte, faça-o com liberalidade; o que preside, com cuidado; o que exercita misericórdia, com alegria." },
{name:'45129',l:'45',c:'12',v:'9',texto:"O amor seja não fingido. Aborrecei o mal e apegai-vos ao bem." },
{name:'451210',l:'45',c:'12',v:'10',texto:"Amai-vos cordialmente uns aos outros com amor fraternal, preferindo-vos em honra uns aos outros." },
{name:'451211',l:'45',c:'12',v:'11',texto:"Não sejais vagarosos no cuidado; sede fervorosos no espírito, servindo ao Senhor;" },
{name:'451212',l:'45',c:'12',v:'12',texto:"alegrai-vos na esperança, sede pacientes na tribulação, perseverai na oração;" },
{name:'451213',l:'45',c:'12',v:'13',texto:"comunicai com os santos nas suas necessidades, segui a hospitalidade;" },
{name:'451214',l:'45',c:'12',v:'14',texto:"abençoai aos que vos perseguem; abençoai e não amaldiçoeis." },
{name:'451215',l:'45',c:'12',v:'15',texto:"Alegrai-vos com os que se alegram e chorai com os que choram." },
{name:'451216',l:'45',c:'12',v:'16',texto:"Sede unânimes entre vós; não ambicioneis coisas altas, mas acomodai-vos às humildes; não sejais sábios em vós mesmos." },
{name:'451217',l:'45',c:'12',v:'17',texto:"A ninguém torneis mal por mal; procurai as coisas honestas perante todos os homens." },
{name:'451218',l:'45',c:'12',v:'18',texto:"Se for possível, quanto estiver em vós, tende paz com todos os homens." },
{name:'451219',l:'45',c:'12',v:'19',texto:"Não vos vingueis a vós mesmos, amados, mas dai lugar à ira, porque está escrito: Minha é a vingança; eu recompensarei, diz o Senhor." },
{name:'451220',l:'45',c:'12',v:'20',texto:"Portanto, se o teu inimigo tiver fome, dá-lhe de comer; se tiver sede, dá-lhe de beber; porque, fazendo isto, amontoarás brasas de fogo sobre a sua cabeça." },
{name:'451221',l:'45',c:'12',v:'21',texto:"Não te deixes vencer do mal, mas vence o mal com o bem." },
],
numVersiculos: 21,
},

c13: {
versiculos:[
{name:'45131',l:'45',c:'13',v:'1',texto:"Toda alma esteja sujeita às autoridades superiores; porque não há autoridade que não venha de Deus; e as autoridades que há foram ordenadas por Deus." },
{name:'45132',l:'45',c:'13',v:'2',texto:"Por isso, quem resiste à autoridade resiste à ordenação de Deus; e os que resistem trarão sobre si mesmos a condenação." },
{name:'45133',l:'45',c:'13',v:'3',texto:"Porque os magistrados não são terror para as boas obras, mas para as más. Queres tu, pois, não temer a autoridade? Faze o bem e terás louvor dela." },
{name:'45134',l:'45',c:'13',v:'4',texto:"Porque ela é ministro de Deus para teu bem. Mas, se fizeres o mal, teme, pois não traz debalde a espada; porque é ministro de Deus e vingador para castigar o que faz o mal." },
{name:'45135',l:'45',c:'13',v:'5',texto:"Portanto, é necessário que lhe estejais sujeitos, não somente pelo castigo, mas também pela consciência." },
{name:'45136',l:'45',c:'13',v:'6',texto:"Por esta razão também pagais tributos, porque são ministros de Deus, atendendo sempre a isto mesmo." },
{name:'45137',l:'45',c:'13',v:'7',texto:"Portanto, dai a cada um o que deveis: a quem tributo, tributo; a quem imposto, imposto; a quem temor, temor; a quem honra, honra." },
{name:'45138',l:'45',c:'13',v:'8',texto:"A ninguém devais coisa alguma, a não ser o amor com que vos ameis uns aos outros; porque quem ama aos outros cumpriu a lei." },
{name:'45139',l:'45',c:'13',v:'9',texto:"Com efeito: Não adulterarás, não matarás, não furtarás, não darás falso testemunho, não cobiçarás, e, se há algum outro mandamento, tudo nesta palavra se resume: Amarás ao teu próximo como a ti mesmo." },
{name:'451310',l:'45',c:'13',v:'10',texto:"O amor não faz mal ao próximo; de sorte que o cumprimento da lei é o amor." },
{name:'451311',l:'45',c:'13',v:'11',texto:"E isto digo, conhecendo o tempo, que é já hora de despertarmos do sono; porque a nossa salvação está, agora, mais perto de nós do que quando aceitamos a fé." },
{name:'451312',l:'45',c:'13',v:'12',texto:"A noite é passada, e o dia é chegado. Rejeitemos, pois, as obras das trevas e vistamo-nos das armas da luz." },
{name:'451313',l:'45',c:'13',v:'13',texto:"Andemos honestamente, como de dia, não em glutonarias, nem em bebedeiras, nem em desonestidades, nem em dissoluções, nem em contendas e inveja." },
{name:'451314',l:'45',c:'13',v:'14',texto:"Mas revesti-vos do Senhor Jesus Cristo e não tenhais cuidado da carne em suas concupiscências." },
],
numVersiculos: 14,
},

c14: {
versiculos:[
{name:'45141',l:'45',c:'14',v:'1',texto:"Ora, quanto ao que está enfermo na fé, recebei-o, não em contendas sobre dúvidas." },
{name:'45142',l:'45',c:'14',v:'2',texto:"Porque um crê que de tudo se pode comer, e outro, que é fraco, come legumes." },
{name:'45143',l:'45',c:'14',v:'3',texto:"O que come não despreze o que não come; e o que não come não julgue o que come; porque Deus o recebeu por seu." },
{name:'45144',l:'45',c:'14',v:'4',texto:"Quem és tu que julgas o servo alheio? Para seu próprio senhor ele está em pé ou cai; mas estará firme, porque poderoso é Deus para o firmar." },
{name:'45145',l:'45',c:'14',v:'5',texto:"Um faz diferença entre dia e dia, mas outro julga iguais todos os dias. Cada um esteja inteiramente seguro em seu próprio ânimo." },
{name:'45146',l:'45',c:'14',v:'6',texto:"Aquele que faz caso do dia, para o Senhor o faz. O que come para o Senhor come, porque dá graças a Deus; e o que não come para o Senhor não come e dá graças a Deus." },
{name:'45147',l:'45',c:'14',v:'7',texto:"Porque nenhum de nós vive para si e nenhum morre para si." },
{name:'45148',l:'45',c:'14',v:'8',texto:"Porque, se vivemos, para o Senhor vivemos; se morremos, para o Senhor morremos. De sorte que, ou vivamos ou morramos, somos do Senhor." },
{name:'45149',l:'45',c:'14',v:'9',texto:"Foi para isto que morreu Cristo e tornou a viver; para ser Senhor tanto dos mortos como dos vivos." },
{name:'451410',l:'45',c:'14',v:'10',texto:"Mas tu, por que julgas teu irmão? Ou tu, também, por que desprezas teu irmão? Pois todos havemos de comparecer ante o tribunal de Cristo." },
{name:'451411',l:'45',c:'14',v:'11',texto:"Porque está escrito: Pela minha vida, diz o Senhor, todo joelho se dobrará diante de mim, e toda língua confessará a Deus." },
{name:'451412',l:'45',c:'14',v:'12',texto:"De maneira que cada um de nós dará conta de si mesmo a Deus." },
{name:'451413',l:'45',c:'14',v:'13',texto:"Assim que não nos julguemos mais uns aos outros; antes, seja o vosso propósito não pôr tropeço ou escândalo ao irmão." },
{name:'451414',l:'45',c:'14',v:'14',texto:"Eu sei e estou certo, no Senhor Jesus, que nenhuma coisa é de si mesma imunda, a não ser para aquele que a tem por imunda; para esse é imunda." },
{name:'451415',l:'45',c:'14',v:'15',texto:"Mas, se por causa da comida se contrista teu irmão, já não andas conforme o amor. Não destruas por causa da tua comida aquele por quem Cristo morreu." },
{name:'451416',l:'45',c:'14',v:'16',texto:"Não seja, pois, blasfemado o vosso bem;" },
{name:'451417',l:'45',c:'14',v:'17',texto:"porque o Reino de Deus não é comida nem bebida, mas justiça, e paz, e alegria no Espírito Santo." },
{name:'451418',l:'45',c:'14',v:'18',texto:"Porque quem nisto serve a Cristo agradável é a Deus e aceito aos homens." },
{name:'451419',l:'45',c:'14',v:'19',texto:"Sigamos, pois, as coisas que servem para a paz e para a edificação de uns para com os outros." },
{name:'451420',l:'45',c:'14',v:'20',texto:"Não destruas por causa da comida a obra de Deus. É verdade que tudo é limpo, mas mal vai para o homem que come com escândalo." },
{name:'451421',l:'45',c:'14',v:'21',texto:"Bom é não comer carne, nem beber vinho, nem fazer outras coisas em que teu irmão tropece, ou se escandalize, ou se enfraqueça." },
{name:'451422',l:'45',c:'14',v:'22',texto:"Tens tu fé? Tem-na em ti mesmo diante de Deus. Bem-aventurado aquele que não se condena a si mesmo naquilo que aprova." },
{name:'451423',l:'45',c:'14',v:'23',texto:"Mas aquele que tem dúvidas, se come, está condenado, porque não come por fé; e tudo o que não é de fé é pecado." },
],
numVersiculos: 23,
},

c15: {
versiculos:[
{name:'45151',l:'45',c:'15',v:'1',texto:"Mas nós que somos fortes devemos suportar as fraquezas dos fracos e não agradar a nós mesmos." },
{name:'45152',l:'45',c:'15',v:'2',texto:"Portanto, cada um de nós agrade ao seu próximo no que é bom para edificação." },
{name:'45153',l:'45',c:'15',v:'3',texto:"Porque também Cristo não agradou a si mesmo, mas, como está escrito: Sobre mim caíram as injúrias dos que te injuriavam." },
{name:'45154',l:'45',c:'15',v:'4',texto:"Porque tudo que dantes foi escrito para nosso ensino foi escrito, para que, pela paciência e consolação das Escrituras, tenhamos esperança." },
{name:'45155',l:'45',c:'15',v:'5',texto:"Ora, o Deus de paciência e consolação vos conceda o mesmo sentimento uns para com os outros, segundo Cristo Jesus," },
{name:'45156',l:'45',c:'15',v:'6',texto:"para que concordes, a uma boca, glorifiqueis ao Deus e Pai de nosso Senhor Jesus Cristo." },
{name:'45157',l:'45',c:'15',v:'7',texto:"Portanto, recebei-vos uns aos outros, como também Cristo nos recebeu para glória de Deus." },
{name:'45158',l:'45',c:'15',v:'8',texto:"Digo, pois, que Jesus Cristo foi ministro da circuncisão, por causa da verdade de Deus, para que confirmasse as promessas feitas aos pais;" },
{name:'45159',l:'45',c:'15',v:'9',texto:"e para que os gentios glorifiquem a Deus pela sua misericórdia, como está escrito: Portanto, eu te louvarei entre os gentios e cantarei ao teu nome." },
{name:'451510',l:'45',c:'15',v:'10',texto:"E outra vez diz: Alegrai-vos, gentios, com o seu povo." },
{name:'451511',l:'45',c:'15',v:'11',texto:"E outra vez: Louvai ao Senhor, todos os gentios, e celebrai-o todos os povos." },
{name:'451512',l:'45',c:'15',v:'12',texto:"E outra vez diz Isaías: Uma raiz em Jessé haverá, e, naquele que se levantar para reger os gentios, os gentios esperarão." },
{name:'451513',l:'45',c:'15',v:'13',texto:"Ora, o Deus de esperança vos encha de todo o gozo e paz em crença, para que abundeis em esperança pela virtude do Espírito Santo." },
{name:'451514',l:'45',c:'15',v:'14',texto:"Eu próprio, meus irmãos, certo estou, a respeito de vós, que vós mesmos estais cheios de bondade, cheios de todo o conhecimento, podendo admoestar-vos uns aos outros." },
{name:'451515',l:'45',c:'15',v:'15',texto:"Mas, irmãos, em parte vos escrevi mais ousadamente, como para vos trazer outra vez isto à memória, pela graça que por Deus me foi dada," },
{name:'451516',l:'45',c:'15',v:'16',texto:"que eu seja ministro de Jesus Cristo entre os gentios, ministrando o evangelho de Deus, para que seja agradável a oferta dos gentios, santificada pelo Espírito Santo." },
{name:'451517',l:'45',c:'15',v:'17',texto:"De sorte que tenho glória em Jesus Cristo nas coisas que pertencem a Deus." },
{name:'451518',l:'45',c:'15',v:'18',texto:"Porque não ousaria dizer coisa alguma, que Cristo por mim não tenha feito, para obediência dos gentios, por palavra e por obras;" },
{name:'451519',l:'45',c:'15',v:'19',texto:"pelo poder dos sinais e prodígios, na virtude do Espírito de Deus; de maneira que, desde Jerusalém e arredores até ao Ilírico, tenho pregado o evangelho de Jesus Cristo." },
{name:'451520',l:'45',c:'15',v:'20',texto:"E desta maneira me esforcei por anunciar o evangelho, não onde Cristo houvera sido nomeado, para não edificar sobre fundamento alheio;" },
{name:'451521',l:'45',c:'15',v:'21',texto:"antes, como está escrito: Aqueles a quem não foi anunciado o verão, e os que não ouviram o entenderão." },
{name:'451522',l:'45',c:'15',v:'22',texto:"Pelo que também muitas vezes tenho sido impedido de ir ter convosco." },
{name:'451523',l:'45',c:'15',v:'23',texto:"Mas, agora, que não tenho mais demora nestes sítios, e tendo já há muitos anos grande desejo de ir ter convosco," },
{name:'451524',l:'45',c:'15',v:'24',texto:"quando partir para a Espanha, irei ter convosco; pois espero que, de passagem, vos verei e que para lá seja encaminhado por vós, depois de ter gozado um pouco da vossa companhia." },
{name:'451525',l:'45',c:'15',v:'25',texto:"Mas, agora, vou a Jerusalém para ministrar aos santos." },
{name:'451526',l:'45',c:'15',v:'26',texto:"Porque pareceu bem à Macedônia e à Acaia fazerem uma coleta para os pobres dentre os santos que estão em Jerusalém." },
{name:'451527',l:'45',c:'15',v:'27',texto:"Isto lhes pareceu bem, como devedores que são para com eles. Porque, se os gentios foram participantes dos seus bens espirituais, devem também ministrar-lhes os temporais." },
{name:'451528',l:'45',c:'15',v:'28',texto:"Assim que, concluído isto, e havendo-lhes consignado este fruto, de lá, passando por vós, irei à Espanha." },
{name:'451529',l:'45',c:'15',v:'29',texto:"E bem sei que, indo ter convosco, chegarei com a plenitude da bênção do evangelho de Cristo." },
{name:'451530',l:'45',c:'15',v:'30',texto:"E rogo-vos, irmãos, por nosso Senhor Jesus Cristo e pelo amor do Espírito, que combatais comigo nas vossas orações por mim a Deus," },
{name:'451531',l:'45',c:'15',v:'31',texto:"para que seja livre dos rebeldes que estão na Judéia, e que esta minha administração, que em Jerusalém faço, seja bem aceita pelos santos;" },
{name:'451532',l:'45',c:'15',v:'32',texto:"a fim de que, pela vontade de Deus, chegue a vós com alegria e possa recrear-me convosco." },
{name:'451533',l:'45',c:'15',v:'33',texto:"E o Deus de paz seja com todos vós. Amém!" },
],
numVersiculos: 33,
},

c16: {
versiculos:[
{name:'45161',l:'45',c:'16',v:'1',texto:"Recomendo-vos, pois, Febe, nossa irmã, a qual serve na igreja que está em Cencréia," },
{name:'45162',l:'45',c:'16',v:'2',texto:"para que a recebais no Senhor, como convém aos santos, e a ajudeis em qualquer coisa que de vós necessitar; porque tem hospedado a muitos, como também a mim mesmo." },
{name:'45163',l:'45',c:'16',v:'3',texto:"Saudai a Priscila e a Áqüila, meus cooperadores em Cristo Jesus," },
{name:'45164',l:'45',c:'16',v:'4',texto:"os quais pela minha vida expuseram a sua cabeça; o que não só eu lhes agradeço, mas também todas as igrejas dos gentios." },
{name:'45165',l:'45',c:'16',v:'5',texto:"Saudai também a igreja que está em sua casa. Saudai a Epêneto, meu amado, que é as primícias da Ásia em Cristo." },
{name:'45166',l:'45',c:'16',v:'6',texto:"Saudai a Maria, que trabalhou muito por nós." },
{name:'45167',l:'45',c:'16',v:'7',texto:"Saudai a Andrônico e a Júnia, meus parentes e meus companheiros na prisão, os quais se distinguiram entre os apóstolos e que foram antes de mim em Cristo." },
{name:'45168',l:'45',c:'16',v:'8',texto:"Saudai a Amplíato, meu amado no Senhor." },
{name:'45169',l:'45',c:'16',v:'9',texto:"Saudai a Urbano, nosso cooperador em Cristo, e a Estáquis, meu amado." },
{name:'451610',l:'45',c:'16',v:'10',texto:"Saudai a Apeles, aprovado em Cristo. Saudai aos da família de Aristóbulo." },
{name:'451611',l:'45',c:'16',v:'11',texto:"Saudai a Herodião, meu parente. Saudai aos da família de Narciso, os que estão no Senhor." },
{name:'451612',l:'45',c:'16',v:'12',texto:"Saudai a Trifena e a Trifosa, as quais trabalham no Senhor. Saudai à amada Pérside, a qual muito trabalhou no Senhor." },
{name:'451613',l:'45',c:'16',v:'13',texto:"Saudai a Rufo, eleito no Senhor, e a sua mãe e minha." },
{name:'451614',l:'45',c:'16',v:'14',texto:"Saudai a Asíncrito, a Flegonte, a Hermas, a Pátrobas, a Hermes, e aos irmãos que estão com eles." },
{name:'451615',l:'45',c:'16',v:'15',texto:"Saudai a Filólogo e a Júlia, a Nereu e a sua irmã, e a Olimpas, e a todos os santos que com eles estão." },
{name:'451616',l:'45',c:'16',v:'16',texto:"Saudai-vos uns aos outros com santo ósculo. As igrejas de Cristo vos saúdam." },
{name:'451617',l:'45',c:'16',v:'17',texto:"E rogo-vos, irmãos, que noteis os que promovem dissensões e escândalos contra a doutrina que aprendestes; desviai-vos deles." },
{name:'451618',l:'45',c:'16',v:'18',texto:"Porque os tais não servem a nosso Senhor Jesus Cristo, mas ao seu ventre; e, com suaves palavras e lisonjas, enganam o coração dos símplices." },
{name:'451619',l:'45',c:'16',v:'19',texto:"Quanto à vossa obediência, é ela conhecida de todos. Comprazo-me, pois, em vós; e quero que sejais sábios no bem, mas símplices no mal." },
{name:'451620',l:'45',c:'16',v:'20',texto:"E o Deus de paz esmagará em breve Satanás debaixo dos vossos pés. A graça de nosso Senhor Jesus Cristo seja convosco. Amém!" },
{name:'451621',l:'45',c:'16',v:'21',texto:"Saúdam-vos Timóteo, meu cooperador, e Lúcio, e Jasom, e Sosípatro, meus parentes." },
{name:'451622',l:'45',c:'16',v:'22',texto:"Eu, Tércio, que esta carta escrevi, vos saúdo no Senhor." },
{name:'451623',l:'45',c:'16',v:'23',texto:"Saúda-vos Gaio, meu hospedeiro e de toda a igreja. Saúda-vos Erasto, procurador da cidade, e também o irmão Quarto." },
{name:'451624',l:'45',c:'16',v:'24',texto:"A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém!" },
{name:'451625',l:'45',c:'16',v:'25',texto:"Ora, àquele que é poderoso para vos confirmar segundo o meu evangelho e a pregação de Jesus Cristo, conforme a revelação do mistério que desde tempos eternos esteve oculto," },
{name:'451626',l:'45',c:'16',v:'26',texto:"mas que se manifestou agora e se notificou pelas Escrituras dos profetas, segundo o mandamento do Deus eterno, a todas as nações para obediência da fé," },
{name:'451627',l:'45',c:'16',v:'27',texto:"ao único Deus, sábio, seja dada glória por Jesus Cristo para todo o sempre. Amém!" },
],
numVersiculos: 27,
},
	

};
