BibliaJFA.corintios1 = {
	libro: "1 Coríntios",
	numCapitulos: 16,

c1: {
versiculos:[
{name:'4611',l:'46',c:'1',v:'1',texto:"Paulo ( chamado apóstolo de Jesus Cristo, pela vontade de Deus ) e o irmão Sóstenes," },
{name:'4612',l:'46',c:'1',v:'2',texto:"à igreja de Deus que está em Corinto, aos santificados em Cristo Jesus, chamados santos, com todos os que em todo lugar invocam o nome de nosso Senhor Jesus Cristo, Senhor deles e nosso:" },
{name:'4613',l:'46',c:'1',v:'3',texto:"graça e paz, da parte de Deus, nosso Pai, e do Senhor Jesus Cristo." },
{name:'4614',l:'46',c:'1',v:'4',texto:"Sempre dou graças ao meu Deus por vós pela graça de Deus que vos foi dada em Jesus Cristo." },
{name:'4615',l:'46',c:'1',v:'5',texto:"Porque em tudo fostes enriquecidos nele, em toda a palavra e em todo o conhecimento" },
{name:'4616',l:'46',c:'1',v:'6',texto:"( como foi mesmo o testemunho de Cristo confirmado entre vós )." },
{name:'4617',l:'46',c:'1',v:'7',texto:"De maneira que nenhum dom vos falta, esperando a manifestação de nosso Senhor Jesus Cristo," },
{name:'4618',l:'46',c:'1',v:'8',texto:"o qual vos confirmará também até ao fim, para serdes irrepreensíveis no Dia de nosso Senhor Jesus Cristo." },
{name:'4619',l:'46',c:'1',v:'9',texto:"Fiel é Deus, pelo qual fostes chamados para a comunhão de seu Filho Jesus Cristo, nosso Senhor." },
{name:'46110',l:'46',c:'1',v:'10',texto:"Rogo-vos, porém, irmãos, pelo nome de nosso Senhor Jesus Cristo, que digais todos uma mesma coisa e que não haja entre vós dissensões; antes, sejais unidos, em um mesmo sentido e em um mesmo parecer." },
{name:'46111',l:'46',c:'1',v:'11',texto:"Porque a respeito de vós, irmãos meus, me foi comunicado pelos da família de Cloe que há contendas entre vós." },
{name:'46112',l:'46',c:'1',v:'12',texto:"Quero dizer, com isso, que cada um de vós diz: Eu sou de Paulo, e eu, de Apolo, e eu, de Cefas, e eu, de Cristo." },
{name:'46113',l:'46',c:'1',v:'13',texto:"Está Cristo dividido? Foi Paulo crucificado por vós? Ou fostes vós batizados em nome de Paulo?" },
{name:'46114',l:'46',c:'1',v:'14',texto:"Dou graças a Deus, porque a nenhum de vós batizei, senão a Crispo e a Gaio;" },
{name:'46115',l:'46',c:'1',v:'15',texto:"para que ninguém diga que fostes batizados em meu nome." },
{name:'46116',l:'46',c:'1',v:'16',texto:"E batizei também a família de Estéfanas; além destes, não sei se batizei algum outro." },
{name:'46117',l:'46',c:'1',v:'17',texto:"Porque Cristo enviou-me não para batizar, mas para evangelizar; não em sabedoria de palavras, para que a cruz de Cristo se não faça vã." },
{name:'46118',l:'46',c:'1',v:'18',texto:"Porque a palavra da cruz é loucura para os que perecem; mas para nós, que somos salvos, é o poder de Deus." },
{name:'46119',l:'46',c:'1',v:'19',texto:"Porque está escrito: Destruirei a sabedoria dos sábios e aniquilarei a inteligência dos inteligentes." },
{name:'46120',l:'46',c:'1',v:'20',texto:"Onde está o sábio? Onde está o escriba? Onde está o inquiridor deste século? Porventura, não tornou Deus louca a sabedoria deste mundo?" },
{name:'46121',l:'46',c:'1',v:'21',texto:"Visto como, na sabedoria de Deus, o mundo não conheceu a Deus pela sua sabedoria, aprouve a Deus salvar os crentes pela loucura da pregação." },
{name:'46122',l:'46',c:'1',v:'22',texto:"Porque os judeus pedem sinal, e os gregos buscam sabedoria;" },
{name:'46123',l:'46',c:'1',v:'23',texto:"mas nós pregamos a Cristo crucificado, que é escândalo para os judeus e loucura para os gregos." },
{name:'46124',l:'46',c:'1',v:'24',texto:"Mas, para os que são chamados, tanto judeus como gregos, lhes pregamos a Cristo, poder de Deus e sabedoria de Deus." },
{name:'46125',l:'46',c:'1',v:'25',texto:"Porque a loucura de Deus é mais sábia do que os homens; e a fraqueza de Deus é mais forte do que os homens." },
{name:'46126',l:'46',c:'1',v:'26',texto:"Porque vede, irmãos, a vossa vocação, que não são muitos os sábios segundo a carne, nem muitos os poderosos, nem muitos os nobres que são chamados." },
{name:'46127',l:'46',c:'1',v:'27',texto:"Mas Deus escolheu as coisas loucas deste mundo para confundir as sábias; e Deus escolheu as coisas fracas deste mundo para confundir as fortes." },
{name:'46128',l:'46',c:'1',v:'28',texto:"E Deus escolheu as coisas vis deste mundo, e as desprezíveis, e as que não são para aniquilar as que são;" },
{name:'46129',l:'46',c:'1',v:'29',texto:"para que nenhuma carne se glorie perante ele." },
{name:'46130',l:'46',c:'1',v:'30',texto:"Mas vós sois dele, em Jesus Cristo, o qual para nós foi feito por Deus sabedoria, e justiça, e santificação, e redenção;" },
{name:'46131',l:'46',c:'1',v:'31',texto:"para que, como está escrito: Aquele que se gloria, glorie-se no Senhor." },
],
numVersiculos: 31,
},

c2: {
versiculos:[
{name:'4621',l:'46',c:'2',v:'1',texto:"E eu, irmãos, quando fui ter convosco, anunciando-vos o testemunho de Deus, não fui com sublimidade de palavras ou de sabedoria." },
{name:'4622',l:'46',c:'2',v:'2',texto:"Porque nada me propus saber entre vós, senão a Jesus Cristo e este crucificado." },
{name:'4623',l:'46',c:'2',v:'3',texto:"E eu estive convosco em fraqueza, e em temor, e em grande tremor." },
{name:'4624',l:'46',c:'2',v:'4',texto:"A minha palavra e a minha pregação não consistiram em palavras persuasivas de sabedoria humana, mas em demonstração do Espírito e de poder," },
{name:'4625',l:'46',c:'2',v:'5',texto:"para que a vossa fé não se apoiasse em sabedoria dos homens, mas no poder de Deus." },
{name:'4626',l:'46',c:'2',v:'6',texto:"Todavia, falamos sabedoria entre os perfeitos; não, porém, a sabedoria deste mundo, nem dos príncipes deste mundo, que se aniquilam;" },
{name:'4627',l:'46',c:'2',v:'7',texto:"mas falamos a sabedoria de Deus, oculta em mistério, a qual Deus ordenou antes dos séculos para nossa glória;" },
{name:'4628',l:'46',c:'2',v:'8',texto:"a qual nenhum dos príncipes deste mundo conheceu; porque, se a conhecessem, nunca crucificariam ao Senhor da glória." },
{name:'4629',l:'46',c:'2',v:'9',texto:"Mas, como está escrito: As coisas que o olho não viu, e o ouvido não ouviu, e não subiram ao coração do homem são as que Deus preparou para os que o amam." },
{name:'46210',l:'46',c:'2',v:'10',texto:"Mas Deus no-las revelou pelo seu Espírito; porque o Espírito penetra todas as coisas, ainda as profundezas de Deus." },
{name:'46211',l:'46',c:'2',v:'11',texto:"Porque qual dos homens sabe as coisas do homem, senão o espírito do homem, que nele está? Assim também ninguém sabe as coisas de Deus, senão o Espírito de Deus." },
{name:'46212',l:'46',c:'2',v:'12',texto:"Mas nós não recebemos o espírito do mundo, mas o Espírito que provém de Deus, para que pudéssemos conhecer o que nos é dado gratuitamente por Deus." },
{name:'46213',l:'46',c:'2',v:'13',texto:"As quais também falamos, não com palavras de sabedoria humana, mas com as que o Espírito Santo ensina, comparando as coisas espirituais com as espirituais." },
{name:'46214',l:'46',c:'2',v:'14',texto:"Ora, o homem natural não compreende as coisas do Espírito de Deus, porque lhe parecem loucura; e não pode entendê-las, porque elas se discernem espiritualmente." },
{name:'46215',l:'46',c:'2',v:'15',texto:"Mas o que é espiritual discerne bem tudo, e ele de ninguém é discernido." },
{name:'46216',l:'46',c:'2',v:'16',texto:"Porque quem conheceu a mente do Senhor, para que possa instruí-lo? Mas nós temos a mente de Cristo." },
],
numVersiculos: 16,
},

c3: {
versiculos:[
{name:'4631',l:'46',c:'3',v:'1',texto:"E eu, irmãos, não vos pude falar como a espirituais, mas como a carnais, como a meninos em Cristo." },
{name:'4632',l:'46',c:'3',v:'2',texto:"Com leite vos criei e não com manjar, porque ainda não podíeis, nem tampouco ainda agora podeis;" },
{name:'4633',l:'46',c:'3',v:'3',texto:"porque ainda sois carnais, pois, havendo entre vós inveja, contendas e dissensões, não sois, porventura, carnais e não andais segundo os homens?" },
{name:'4634',l:'46',c:'3',v:'4',texto:"Porque, dizendo um: Eu sou de Paulo; e outro: Eu, de Apolo; porventura, não sois carnais?" },
{name:'4635',l:'46',c:'3',v:'5',texto:"Pois quem é Paulo e quem é Apolo, senão ministros pelos quais crestes, e conforme o que o Senhor deu a cada um?" },
{name:'4636',l:'46',c:'3',v:'6',texto:"Eu plantei, Apolo regou; mas Deus deu o crescimento." },
{name:'4637',l:'46',c:'3',v:'7',texto:"Pelo que nem o que planta é alguma coisa, nem o que rega, mas Deus, que dá o crescimento." },
{name:'4638',l:'46',c:'3',v:'8',texto:"Ora, o que planta e o que rega são um; mas cada um receberá o seu galardão, segundo o seu trabalho." },
{name:'4639',l:'46',c:'3',v:'9',texto:"Porque nós somos cooperadores de Deus; vós sois lavoura de Deus e edifício de Deus." },
{name:'46310',l:'46',c:'3',v:'10',texto:"Segundo a graça de Deus que me foi dada, pus eu, como sábio arquiteto, o fundamento, e outro edifica sobre ele; mas veja cada um como edifica sobre ele." },
{name:'46311',l:'46',c:'3',v:'11',texto:"Porque ninguém pode pôr outro fundamento, além do que já está posto, o qual é Jesus Cristo." },
{name:'46312',l:'46',c:'3',v:'12',texto:"E, se alguém sobre este fundamento formar um edifício de ouro, prata, pedras preciosas, madeira, feno, palha," },
{name:'46313',l:'46',c:'3',v:'13',texto:"a obra de cada um se manifestará; na verdade, o Dia a declarará, porque pelo fogo será descoberta; e o fogo provará qual seja a obra de cada um." },
{name:'46314',l:'46',c:'3',v:'14',texto:"Se a obra que alguém edificou nessa parte permanecer, esse receberá galardão." },
{name:'46315',l:'46',c:'3',v:'15',texto:"Se a obra de alguém se queimar, sofrerá detrimento; mas o tal será salvo, todavia como pelo fogo." },
{name:'46316',l:'46',c:'3',v:'16',texto:"Não sabeis vós que sois o templo de Deus e que o Espírito de Deus habita em vós?" },
{name:'46317',l:'46',c:'3',v:'17',texto:"Se alguém destruir o templo de Deus, Deus o destruirá; porque o templo de Deus, que sois vós, é santo." },
{name:'46318',l:'46',c:'3',v:'18',texto:"Ninguém se engane a si mesmo: se alguém dentre vós se tem por sábio neste mundo, faça-se louco para ser sábio." },
{name:'46319',l:'46',c:'3',v:'19',texto:"Porque a sabedoria deste mundo é loucura diante de Deus; pois está escrito: Ele apanha os sábios na sua própria astúcia." },
{name:'46320',l:'46',c:'3',v:'20',texto:"E outra vez: O Senhor conhece os pensamentos dos sábios, que são vãos." },
{name:'46321',l:'46',c:'3',v:'21',texto:"Portanto, ninguém se glorie nos homens; porque tudo é vosso:" },
{name:'46322',l:'46',c:'3',v:'22',texto:"seja Paulo, seja Apolo, seja Cefas, seja o mundo, seja a vida, seja a morte, seja o presente, seja o futuro, tudo é vosso," },
{name:'46323',l:'46',c:'3',v:'23',texto:"e vós, de Cristo, e Cristo, de Deus." },
],
numVersiculos: 23,
},

c4: {
versiculos:[
{name:'4641',l:'46',c:'4',v:'1',texto:"Que os homens nos considerem como ministros de Cristo e despenseiros dos mistérios de Deus." },
{name:'4642',l:'46',c:'4',v:'2',texto:"Além disso, requer-se nos despenseiros que cada um se ache fiel." },
{name:'4643',l:'46',c:'4',v:'3',texto:"Todavia, a mim mui pouco se me dá de ser julgado por vós ou por algum juízo humano; nem eu tampouco a mim mesmo me julgo." },
{name:'4644',l:'46',c:'4',v:'4',texto:"Porque em nada me sinto culpado; mas nem por isso me considero justificado, pois quem me julga é o Senhor." },
{name:'4645',l:'46',c:'4',v:'5',texto:"Portanto, nada julgueis antes de tempo, até que o Senhor venha, o qual também trará à luz as coisas ocultas das trevas e manifestará os desígnios dos corações; e, então, cada um receberá de Deus o louvor." },
{name:'4646',l:'46',c:'4',v:'6',texto:"E eu, irmãos, apliquei essas coisas, por semelhança, a mim e a Apolo, por amor de vós, para que, em nós, aprendais a não ir além do que está escrito, não vos ensoberbecendo a favor de um contra outro." },
{name:'4647',l:'46',c:'4',v:'7',texto:"Porque quem te diferença? E que tens tu que não tenhas recebido? E, se o recebeste, por que te glorias como se não o houveras recebido?" },
{name:'4648',l:'46',c:'4',v:'8',texto:"Já estais fartos! Já estais ricos! Sem nós reinais! E prouvera Deus reinásseis para que também nós reinemos convosco!" },
{name:'4649',l:'46',c:'4',v:'9',texto:"Porque tenho para mim que Deus a nós, apóstolos, nos pôs por últimos, como condenados à morte; pois somos feitos espetáculo ao mundo, aos anjos e aos homens." },
{name:'46410',l:'46',c:'4',v:'10',texto:"Nós somos loucos por amor de Cristo, e vós, sábios em Cristo; nós, fracos, e vós, fortes; vós, ilustres, e nós, vis." },
{name:'46411',l:'46',c:'4',v:'11',texto:"Até esta presente hora, sofremos fome e sede, e estamos nus, e recebemos bofetadas, e não temos pousada certa," },
{name:'46412',l:'46',c:'4',v:'12',texto:"e nos afadigamos, trabalhando com nossas próprias mãos; somos injuriados e bendizemos; somos perseguidos e sofremos;" },
{name:'46413',l:'46',c:'4',v:'13',texto:"somos blasfemados e rogamos; até ao presente, temos chegado a ser como o lixo deste mundo e como a escória de todos." },
{name:'46414',l:'46',c:'4',v:'14',texto:"Não escrevo essas coisas para vos envergonhar; mas admoesto-vos como meus filhos amados." },
{name:'46415',l:'46',c:'4',v:'15',texto:"Porque, ainda que tivésseis dez mil aios em Cristo, não teríeis, contudo, muitos pais; porque eu, pelo evangelho, vos gerei em Jesus Cristo." },
{name:'46416',l:'46',c:'4',v:'16',texto:"Admoesto-vos, portanto, a que sejais meus imitadores." },
{name:'46417',l:'46',c:'4',v:'17',texto:"Por esta causa vos mandei Timóteo, que é meu filho amado e fiel no Senhor, o qual vos lembrará os meus caminhos em Cristo, como por toda parte ensino em cada igreja." },
{name:'46418',l:'46',c:'4',v:'18',texto:"Mas alguns andam inchados, como se eu não houvesse de ir ter convosco." },
{name:'46419',l:'46',c:'4',v:'19',texto:"Mas, em breve, irei ter convosco, se o Senhor quiser, e então conhecerei, não as palavras dos que andam inchados, mas a virtude." },
{name:'46420',l:'46',c:'4',v:'20',texto:"Porque o Reino de Deus não consiste em palavras, mas em virtude." },
{name:'46421',l:'46',c:'4',v:'21',texto:"Que quereis? Irei ter convosco com vara ou com amor e espírito de mansidão?" },
],
numVersiculos: 21,
},

c5: {
versiculos:[
{name:'4651',l:'46',c:'5',v:'1',texto:"Geralmente, se ouve que há entre vós fornicação e fornicação tal, qual nem ainda entre os gentios, como é haver quem abuse da mulher de seu pai." },
{name:'4652',l:'46',c:'5',v:'2',texto:"Estais inchados e nem ao menos vos entristecestes, por não ter sido dentre vós tirado quem cometeu tal ação." },
{name:'4653',l:'46',c:'5',v:'3',texto:"Eu, na verdade, ainda que ausente no corpo, mas presente no espírito, já determinei, como se estivesse presente, que o que tal ato praticou," },
{name:'4654',l:'46',c:'5',v:'4',texto:"em nome de nosso Senhor Jesus Cristo, juntos vós e o meu espírito, pelo poder de nosso Senhor Jesus Cristo," },
{name:'4655',l:'46',c:'5',v:'5',texto:"seja entregue a Satanás para destruição da carne, para que o espírito seja salvo no Dia do Senhor Jesus." },
{name:'4656',l:'46',c:'5',v:'6',texto:"Não é boa a vossa jactância. Não sabeis que um pouco de fermento faz levedar toda a massa?" },
{name:'4657',l:'46',c:'5',v:'7',texto:"Alimpai-vos, pois, do fermento velho, para que sejais uma nova massa, assim como estais sem fermento. Porque Cristo, nossa páscoa, foi sacrificado por nós." },
{name:'4658',l:'46',c:'5',v:'8',texto:"Pelo que façamos festa, não com o fermento velho, nem com o fermento da maldade e da malícia, mas com os asmos da sinceridade e da verdade." },
{name:'4659',l:'46',c:'5',v:'9',texto:"Já por carta vos tenho escrito que não vos associeis com os que se prostituem;" },
{name:'46510',l:'46',c:'5',v:'10',texto:"isso não quer dizer absolutamente com os devassos deste mundo, ou com os avarentos, ou com os roubadores, ou com os idólatras; porque então vos seria necessário sair do mundo." },
{name:'46511',l:'46',c:'5',v:'11',texto:"Mas, agora, escrevi que não vos associeis com aquele que, dizendo-se irmão, for devasso, ou avarento, ou idólatra, ou maldizente, ou beberrão, ou roubador; com o tal nem ainda comais." },
{name:'46512',l:'46',c:'5',v:'12',texto:"Porque que tenho eu em julgar também os que estão de fora? Não julgais vós os que estão dentro?" },
{name:'46513',l:'46',c:'5',v:'13',texto:"Mas Deus julga os que estão de fora. Tirai, pois, dentre vós a esse iníquo." },
],
numVersiculos: 13,
},

c6: {
versiculos:[
{name:'4661',l:'46',c:'6',v:'1',texto:"Ousa algum de vós, tendo algum negócio contra outro, ir a juízo perante os injustos e não perante os santos?" },
{name:'4662',l:'46',c:'6',v:'2',texto:"Não sabeis vós que os santos hão de julgar o mundo? Ora, se o mundo deve ser julgado por vós, sois, porventura, indignos de julgar as coisas mínimas?" },
{name:'4663',l:'46',c:'6',v:'3',texto:"Não sabeis vós que havemos de julgar os anjos? Quanto mais as coisas pertencentes a esta vida?" },
{name:'4664',l:'46',c:'6',v:'4',texto:"Então, se tiverdes negócios em juízo, pertencentes a esta vida, pondes na cadeira aos que são de menos estima na igreja?" },
{name:'4665',l:'46',c:'6',v:'5',texto:"Para vos envergonhar o digo: Não há, pois, entre vós sábios, nem mesmo um, que possa julgar entre seus irmãos?" },
{name:'4666',l:'46',c:'6',v:'6',texto:"Mas o irmão vai a juízo com o irmão, e isso perante infiéis." },
{name:'4667',l:'46',c:'6',v:'7',texto:"Na verdade, é já realmente uma falta entre vós terdes demandas uns contra os outros. Por que não sofreis, antes, a injustiça? Por que não sofreis, antes, o dano?" },
{name:'4668',l:'46',c:'6',v:'8',texto:"Mas vós mesmos fazeis a injustiça e fazeis o dano e isso aos irmãos." },
{name:'4669',l:'46',c:'6',v:'9',texto:"Não sabeis que os injustos não hão de herdar o Reino de Deus?" },
{name:'46610',l:'46',c:'6',v:'10',texto:"Não erreis: nem os devassos, nem os idólatras, nem os adúlteros, nem os efeminados, nem os sodomitas, nem os ladrões, nem os avarentos, nem os bêbados, nem os maldizentes, nem os roubadores herdarão o Reino de Deus." },
{name:'46611',l:'46',c:'6',v:'11',texto:"E é o que alguns têm sido, mas haveis sido lavados, mas haveis sido santificados, mas haveis sido justificados em nome do Senhor Jesus e pelo Espírito do nosso Deus." },
{name:'46612',l:'46',c:'6',v:'12',texto:"Todas as coisas me são lícitas, mas nem todas as coisas convêm; todas as coisas me são lícitas, mas eu não me deixarei dominar por nenhuma." },
{name:'46613',l:'46',c:'6',v:'13',texto:"Os manjares são para o ventre, e o ventre, para os manjares; Deus, porém, aniquilará tanto um como os outros. Mas o corpo não é para a prostituição, senão para o Senhor, e o Senhor para o corpo." },
{name:'46614',l:'46',c:'6',v:'14',texto:"Ora, Deus, que também ressuscitou o Senhor, nos ressuscitará a nós pelo seu poder." },
{name:'46615',l:'46',c:'6',v:'15',texto:"Não sabeis vós que os vossos corpos são membros de Cristo? Tomarei, pois, os membros de Cristo e fá-los-ei membros de uma meretriz? Não, por certo." },
{name:'46616',l:'46',c:'6',v:'16',texto:"Ou não sabeis que o que se ajunta com a meretriz faz-se um corpo com ela? Porque serão, disse, dois numa só carne." },
{name:'46617',l:'46',c:'6',v:'17',texto:"Mas o que se ajunta com o Senhor é um mesmo espírito." },
{name:'46618',l:'46',c:'6',v:'18',texto:"Fugi da prostituição. Todo pecado que o homem comete é fora do corpo; mas o que se prostitui peca contra o seu próprio corpo." },
{name:'46619',l:'46',c:'6',v:'19',texto:"Ou não sabeis que o nosso corpo é o templo do Espírito Santo, que habita em vós, proveniente de Deus, e que não sois de vós mesmos?" },
{name:'46620',l:'46',c:'6',v:'20',texto:"Porque fostes comprados por bom preço; glorificai, pois, a Deus no vosso corpo e no vosso espírito, os quais pertencem a Deus." },
],
numVersiculos: 20,
},

c7: {
versiculos:[
{name:'4671',l:'46',c:'7',v:'1',texto:"Ora, quanto às coisas que me escrevestes, bom seria que o homem não tocasse em mulher;" },
{name:'4672',l:'46',c:'7',v:'2',texto:"mas, por causa da prostituição, cada um tenha a sua própria mulher, e cada uma tenha o seu próprio marido." },
{name:'4673',l:'46',c:'7',v:'3',texto:"O marido pague à mulher a devida benevolência, e da mesma sorte a mulher, ao marido." },
{name:'4674',l:'46',c:'7',v:'4',texto:"A mulher não tem poder sobre o seu próprio corpo, mas tem-no o marido; e também, da mesma maneira, o marido não tem poder sobre o seu próprio corpo, mas tem-no a mulher." },
{name:'4675',l:'46',c:'7',v:'5',texto:"Não vos defraudeis um ao outro, senão por consentimento mútuo, por algum tempo, para vos aplicardes à oração; e, depois, ajuntai-vos outra vez, para que Satanás vos não tente pela vossa incontinência." },
{name:'4676',l:'46',c:'7',v:'6',texto:"Digo, porém, isso como que por permissão e não por mandamento." },
{name:'4677',l:'46',c:'7',v:'7',texto:"Porque quereria que todos os homens fossem como eu mesmo; mas cada um tem de Deus o seu próprio dom, um de uma maneira, e outro de outra." },
{name:'4678',l:'46',c:'7',v:'8',texto:"Digo, porém, aos solteiros e às viúvas, que lhes é bom se ficarem como eu." },
{name:'4679',l:'46',c:'7',v:'9',texto:"Mas, se não podem conter-se, casem-se. Porque é melhor casar do que abrasar-se." },
{name:'46710',l:'46',c:'7',v:'10',texto:"Todavia, aos casados, mando, não eu, mas o Senhor, que a mulher se não aparte do marido." },
{name:'46711',l:'46',c:'7',v:'11',texto:"Se, porém, se apartar, que fique sem casar ou que se reconcilie com o marido; e que o marido não deixe a mulher." },
{name:'46712',l:'46',c:'7',v:'12',texto:"Mas, aos outros, digo eu, não o Senhor: se algum irmão tem mulher descrente, e ela consente em habitar com ele, não a deixe." },
{name:'46713',l:'46',c:'7',v:'13',texto:"E se alguma mulher tem marido descrente, e ele consente em habitar com ela, não o deixe." },
{name:'46714',l:'46',c:'7',v:'14',texto:"Porque o marido descrente é santificado pela mulher, e a mulher descrente é santificada pelo marido. Doutra sorte, os vossos filhos seriam imundos; mas, agora, são santos." },
{name:'46715',l:'46',c:'7',v:'15',texto:"Mas, se o descrente se apartar, aparte-se; porque neste caso o irmão, ou irmã, não está sujeito à servidão; mas Deus chamou-nos para a paz." },
{name:'46716',l:'46',c:'7',v:'16',texto:"Porque, donde sabes, ó mulher, se salvarás teu marido? Ou, donde sabes, ó marido, se salvarás tua mulher?" },
{name:'46717',l:'46',c:'7',v:'17',texto:"E, assim, cada um ande como Deus lhe repartiu, cada um, como o Senhor o chamou. É o que ordeno em todas as igrejas." },
{name:'46718',l:'46',c:'7',v:'18',texto:"É alguém chamado, estando circuncidado? Fique circuncidado. É alguém chamado, estando incircuncidado? Não se circuncide." },
{name:'46719',l:'46',c:'7',v:'19',texto:"A circuncisão é nada, e a incircuncisão nada é, mas, sim, a observância dos mandamentos de Deus." },
{name:'46720',l:'46',c:'7',v:'20',texto:"Cada um fique na vocação em que foi chamado." },
{name:'46721',l:'46',c:'7',v:'21',texto:"Foste chamado sendo servo? Não te dê cuidado; e, se ainda podes ser livre, aproveita a ocasião." },
{name:'46722',l:'46',c:'7',v:'22',texto:"Porque o que é chamado pelo Senhor, sendo servo, é liberto do Senhor; e, da mesma maneira, também o que é chamado, sendo livre, servo é de Cristo." },
{name:'46723',l:'46',c:'7',v:'23',texto:"Fostes comprados por bom preço; não vos façais servos dos homens." },
{name:'46724',l:'46',c:'7',v:'24',texto:"Irmãos, cada um fique diante de Deus no estado em que foi chamado." },
{name:'46725',l:'46',c:'7',v:'25',texto:"Ora, quanto às virgens, não tenho mandamento do Senhor; dou, porém, o meu parecer, como quem tem alcançado misericórdia do Senhor para ser fiel." },
{name:'46726',l:'46',c:'7',v:'26',texto:"Tenho, pois, por bom, por causa da instante necessidade, que é bom para o homem o estar assim." },
{name:'46727',l:'46',c:'7',v:'27',texto:"Estás ligado à mulher? Não busques separar-te. Estás livre de mulher? Não busques mulher." },
{name:'46728',l:'46',c:'7',v:'28',texto:"Mas, se te casares, não pecas; e, se a virgem se casar, não peca. Todavia, os tais terão tribulações na carne, e eu quereria poupar-vos." },
{name:'46729',l:'46',c:'7',v:'29',texto:"Isto, porém, vos digo, irmãos: que o tempo se abrevia; o que resta é que também os que têm mulheres sejam como se as não tivessem;" },
{name:'46730',l:'46',c:'7',v:'30',texto:"e os que choram, como se não chorassem; e os que folgam, como se não folgassem; e os que compram, como se não possuíssem;" },
{name:'46731',l:'46',c:'7',v:'31',texto:"e os que usam deste mundo, como se dele não abusassem, porque a aparência deste mundo passa." },
{name:'46732',l:'46',c:'7',v:'32',texto:"E bem quisera eu que estivésseis sem cuidado. O solteiro cuida das coisas do Senhor, em como há de agradar ao Senhor;" },
{name:'46733',l:'46',c:'7',v:'33',texto:"mas o que é casado cuida das coisas do mundo, em como há de agradar à mulher." },
{name:'46734',l:'46',c:'7',v:'34',texto:"Há diferença entre a mulher casada e a virgem: a solteira cuida das coisas do Senhor para ser santa, tanto no corpo como no espírito; porém a casada cuida das coisas do mundo, em como há de agradar ao marido." },
{name:'46735',l:'46',c:'7',v:'35',texto:"E digo isso para proveito vosso; não para vos enlaçar, mas para o que é decente e conveniente, para vos unirdes ao Senhor, sem distração alguma." },
{name:'46736',l:'46',c:'7',v:'36',texto:"Mas, se alguém julga que trata dignamente a sua virgem, se tiver passado a flor da idade, e se for necessário, que faça o tal o que quiser; não peca; casem-se." },
{name:'46737',l:'46',c:'7',v:'37',texto:"Todavia, o que está firme em seu coração, não tendo necessidade, mas com poder sobre a sua própria vontade, se resolveu no seu coração guardar a sua virgem, faz bem." },
{name:'46738',l:'46',c:'7',v:'38',texto:"De sorte que, o que a dá em casamento faz bem; mas o que a não dá em casamento faz melhor." },
{name:'46739',l:'46',c:'7',v:'39',texto:"A mulher casada está ligada pela lei todo o tempo em que o seu marido vive; mas, se falecer o seu marido, fica livre para casar com quem quiser, contanto que seja no Senhor." },
{name:'46740',l:'46',c:'7',v:'40',texto:"Será, porém, mais bem-aventurada se ficar assim, segundo o meu parecer, e também eu cuido que tenho o Espírito de Deus." },
],
numVersiculos: 40,
},

c8: {
versiculos:[
{name:'4681',l:'46',c:'8',v:'1',texto:"Ora, no tocante às coisas sacrificadas aos ídolos, sabemos que todos temos ciência. A ciência incha, mas o amor edifica." },
{name:'4682',l:'46',c:'8',v:'2',texto:"E, se alguém cuida saber alguma coisa, ainda não sabe como convém saber." },
{name:'4683',l:'46',c:'8',v:'3',texto:"Mas, se alguém ama a Deus, esse é conhecido dele." },
{name:'4684',l:'46',c:'8',v:'4',texto:"Assim que, quanto ao comer das coisas sacrificadas aos ídolos, sabemos que o ídolo nada é no mundo e que não há outro Deus, senão um só." },
{name:'4685',l:'46',c:'8',v:'5',texto:"Porque, ainda que haja também alguns que se chamem deuses, quer no céu quer na terra ( como há muitos deuses e muitos senhores )," },
{name:'4686',l:'46',c:'8',v:'6',texto:"todavia, para nós há um só Deus, o Pai, de quem é tudo e para quem nós vivemos; e um só Senhor, Jesus Cristo, pelo qual são todas as coisas, e nós por ele." },
{name:'4687',l:'46',c:'8',v:'7',texto:"Mas nem em todos há conhecimento; porque alguns até agora comem, no seu costume para com o ídolo, coisas sacrificadas ao ídolo; e a sua consciência, sendo fraca, fica contaminada." },
{name:'4688',l:'46',c:'8',v:'8',texto:"Ora, o manjar não nos faz agradáveis a Deus, porque, se comemos, nada temos de mais, e, se não comemos, nada nos falta." },
{name:'4689',l:'46',c:'8',v:'9',texto:"Mas vede que essa liberdade não seja de alguma maneira escândalo para os fracos." },
{name:'46810',l:'46',c:'8',v:'10',texto:"Porque, se alguém te vir a ti, que tens ciência, sentado à mesa no templo dos ídolos, não será a consciência do que é fraco induzida a comer das coisas sacrificadas aos ídolos?" },
{name:'46811',l:'46',c:'8',v:'11',texto:"E, pela tua ciência, perecerá o irmão fraco, pelo qual Cristo morreu." },
{name:'46812',l:'46',c:'8',v:'12',texto:"Ora, pecando assim contra os irmãos e ferindo a sua fraca consciência, pecais contra Cristo." },
{name:'46813',l:'46',c:'8',v:'13',texto:"Pelo que, se o manjar escandalizar a meu irmão, nunca mais comerei carne, para que meu irmão não se escandalize." },
],
numVersiculos: 13,
},

c9: {
versiculos:[
{name:'4691',l:'46',c:'9',v:'1',texto:"Não sou eu apóstolo? Não sou livre? Não vi eu a Jesus Cristo, Senhor nosso? Não sois vós a minha obra no Senhor?" },
{name:'4692',l:'46',c:'9',v:'2',texto:"Se eu não sou apóstolo para os outros, ao menos o sou para vós; porque vós sois o selo do meu apostolado no Senhor." },
{name:'4693',l:'46',c:'9',v:'3',texto:"Esta é a minha defesa para com os que me condenam." },
{name:'4694',l:'46',c:'9',v:'4',texto:"Não temos nós direito de comer e de beber?" },
{name:'4695',l:'46',c:'9',v:'5',texto:"Não temos nós direito de levar conosco uma mulher irmã, como também os demais apóstolos, e os irmãos do Senhor, e Cefas?" },
{name:'4696',l:'46',c:'9',v:'6',texto:"Ou só eu e Barnabé não temos direito de deixar de trabalhar?" },
{name:'4697',l:'46',c:'9',v:'7',texto:"Quem jamais milita à sua própria custa? Quem planta a vinha e não come do seu fruto? Ou quem apascenta o gado e não come do leite do gado?" },
{name:'4698',l:'46',c:'9',v:'8',texto:"Digo eu isso segundo os homens? Ou não diz a lei também o mesmo?" },
{name:'4699',l:'46',c:'9',v:'9',texto:"Porque na lei de Moisés está escrito: Não atarás a boca ao boi que trilha o grão. Porventura, tem Deus cuidado dos bois?" },
{name:'46910',l:'46',c:'9',v:'10',texto:"Ou não o diz certamente por nós? Certamente que por nós está escrito; porque o que lavra deve lavrar com esperança, e o que debulha deve debulhar com esperança de ser participante." },
{name:'46911',l:'46',c:'9',v:'11',texto:"Se nós vos semeamos as coisas espirituais, será muito que de vós recolhamos as carnais?" },
{name:'46912',l:'46',c:'9',v:'12',texto:"Se outros participam deste poder sobre vós, por que não, mais justamente, nós? Mas nós não usamos deste direito; antes, suportamos tudo, para não pormos impedimento algum ao evangelho de Cristo." },
{name:'46913',l:'46',c:'9',v:'13',texto:"Não sabeis vós que os que administram o que é sagrado comem do que é do templo? E que os que de contínuo estão junto ao altar participam do altar?" },
{name:'46914',l:'46',c:'9',v:'14',texto:"Assim ordenou também o Senhor aos que anunciam o evangelho, que vivam do evangelho." },
{name:'46915',l:'46',c:'9',v:'15',texto:"Mas eu de nenhuma destas coisas usei e não escrevi isso para que assim se faça comigo; porque melhor me fora morrer do que alguém fazer vã esta minha glória." },
{name:'46916',l:'46',c:'9',v:'16',texto:"Porque, se anuncio o evangelho, não tenho de que me gloriar, pois me é imposta essa obrigação; e ai de mim se não anunciar o evangelho!" },
{name:'46917',l:'46',c:'9',v:'17',texto:"E, por isso, se o faço de boa mente, terei prêmio; mas, se de má vontade, apenas uma dispensação me é confiada." },
{name:'46918',l:'46',c:'9',v:'18',texto:"Logo, que prêmio tenho? Que, evangelizando, proponha de graça o evangelho de Cristo, para não abusar do meu poder no evangelho." },
{name:'46919',l:'46',c:'9',v:'19',texto:"Porque, sendo livre para com todos, fiz-me servo de todos, para ganhar ainda mais." },
{name:'46920',l:'46',c:'9',v:'20',texto:"E fiz-me como judeu para os judeus, para ganhar os judeus; para os que estão debaixo da lei, como se estivera debaixo da lei, para ganhar os que estão debaixo da lei." },
{name:'46921',l:'46',c:'9',v:'21',texto:"Para os que estão sem lei, como se estivera sem lei ( não estando sem lei para com Deus, mas debaixo da lei de Cristo ), para ganhar os que estão sem lei." },
{name:'46922',l:'46',c:'9',v:'22',texto:"Fiz-me como fraco para os fracos, para ganhar os fracos. Fiz-me tudo para todos, para, por todos os meios, chegar a salvar alguns." },
{name:'46923',l:'46',c:'9',v:'23',texto:"E eu faço isso por causa do evangelho, para ser também participante dele." },
{name:'46924',l:'46',c:'9',v:'24',texto:"Não sabeis vós que os que correm no estádio, todos, na verdade, correm, mas um só leva o prêmio? Correi de tal maneira que o alcanceis." },
{name:'46925',l:'46',c:'9',v:'25',texto:"E todo aquele que luta de tudo se abstém; eles o fazem para alcançar uma coroa corruptível, nós, porém, uma incorruptível." },
{name:'46926',l:'46',c:'9',v:'26',texto:"Pois eu assim corro, não como a coisa incerta; assim combato, não como batendo no ar." },
{name:'46927',l:'46',c:'9',v:'27',texto:"Antes, subjugo o meu corpo e o reduzo à servidão, para que, pregando aos outros, eu mesmo não venha de alguma maneira a ficar reprovado." },
],
numVersiculos: 27,
},

c10: {
versiculos:[
{name:'46101',l:'46',c:'10',v:'1',texto:"Ora, irmãos, não quero que ignoreis que nossos pais estiveram todos debaixo da nuvem; e todos passaram pelo mar," },
{name:'46102',l:'46',c:'10',v:'2',texto:"e todos foram batizados em Moisés, na nuvem e no mar," },
{name:'46103',l:'46',c:'10',v:'3',texto:"e todos comeram de um mesmo manjar espiritual," },
{name:'46104',l:'46',c:'10',v:'4',texto:"e beberam todos de uma mesma bebida espiritual, porque bebiam da pedra espiritual que os seguia; e a pedra era Cristo." },
{name:'46105',l:'46',c:'10',v:'5',texto:"Mas Deus não se agradou da maior parte deles, pelo que foram prostrados no deserto." },
{name:'46106',l:'46',c:'10',v:'6',texto:"E essas coisas foram-nos feitas em figura, para que não cobicemos as coisas más, como eles cobiçaram." },
{name:'46107',l:'46',c:'10',v:'7',texto:"Não vos façais, pois, idólatras, como alguns deles; conforme está escrito: O povo assentou-se a comer e a beber e levantou-se para folgar." },
{name:'46108',l:'46',c:'10',v:'8',texto:"E não nos prostituamos, como alguns deles fizeram e caíram num dia vinte e três mil." },
{name:'46109',l:'46',c:'10',v:'9',texto:"E não tentemos a Cristo, como alguns deles também tentaram e pereceram pelas serpentes." },
{name:'461010',l:'46',c:'10',v:'10',texto:"E não murmureis, como também alguns deles murmuraram e pereceram pelo destruidor." },
{name:'461011',l:'46',c:'10',v:'11',texto:"Ora, tudo isso lhes sobreveio como figuras, e estão escritas para aviso nosso, para quem já são chegados os fins dos séculos." },
{name:'461012',l:'46',c:'10',v:'12',texto:"Aquele, pois, que cuida estar em pé, olhe que não caia." },
{name:'461013',l:'46',c:'10',v:'13',texto:"Não veio sobre vós tentação, senão humana; mas fiel é Deus, que vos não deixará tentar acima do que podeis; antes, com a tentação dará também o escape, para que a possais suportar." },
{name:'461014',l:'46',c:'10',v:'14',texto:"Portanto, meus amados, fugi da idolatria." },
{name:'461015',l:'46',c:'10',v:'15',texto:"Falo como a sábios; julgai vós mesmos o que digo." },
{name:'461016',l:'46',c:'10',v:'16',texto:"Porventura, o cálice de bênção que abençoamos não é a comunhão do sangue de Cristo? O pão que partimos não é, porventura, a comunhão do corpo de Cristo?" },
{name:'461017',l:'46',c:'10',v:'17',texto:"Porque nós, sendo muitos, somos um só pão e um só corpo; porque todos participamos do mesmo pão." },
{name:'461018',l:'46',c:'10',v:'18',texto:"Vede a Israel segundo a carne; os que comem os sacrifícios não são, porventura, participantes do altar?" },
{name:'461019',l:'46',c:'10',v:'19',texto:"Mas que digo? Que o ídolo é alguma coisa? Ou que o sacrificado ao ídolo é alguma coisa?" },
{name:'461020',l:'46',c:'10',v:'20',texto:"Antes, digo que as coisas que os gentios sacrificam, as sacrificam aos demônios e não a Deus. E não quero que sejais participantes com os demônios." },
{name:'461021',l:'46',c:'10',v:'21',texto:"Não podeis beber o cálice do Senhor e o cálice dos demônios; não podeis ser participantes da mesa do Senhor e da mesa dos demônios." },
{name:'461022',l:'46',c:'10',v:'22',texto:"Ou irritaremos o Senhor? Somos nós mais fortes do que ele?" },
{name:'461023',l:'46',c:'10',v:'23',texto:"Todas as coisas me são lícitas, mas nem todas as coisas convêm; todas as coisas me são lícitas, mas nem todas as coisas edificam." },
{name:'461024',l:'46',c:'10',v:'24',texto:"Ninguém busque o proveito próprio; antes, cada um, o que é de outrem." },
{name:'461025',l:'46',c:'10',v:'25',texto:"Comei de tudo quanto se vende no açougue, sem perguntar nada, por causa da consciência." },
{name:'461026',l:'46',c:'10',v:'26',texto:"Porque a terra é do Senhor e toda a sua plenitude." },
{name:'461027',l:'46',c:'10',v:'27',texto:"E, se algum dos infiéis vos convidar e quiserdes ir, comei de tudo o que se puser diante de vós, sem nada perguntar, por causa da consciência." },
{name:'461028',l:'46',c:'10',v:'28',texto:"Mas, se alguém vos disser: Isto foi sacrificado aos ídolos, não comais, por causa daquele que vos advertiu e por causa da consciência; porque a terra é do Senhor e toda a sua plenitude." },
{name:'461029',l:'46',c:'10',v:'29',texto:"Digo, porém, a consciência, não a tua, mas a do outro. Pois por que há de a minha liberdade ser julgada pela consciência de outrem?" },
{name:'461030',l:'46',c:'10',v:'30',texto:"E, se eu com graça participo, por que sou blasfemado naquilo por que dou graças?" },
{name:'461031',l:'46',c:'10',v:'31',texto:"Portanto, quer comais, quer bebais ou façais outra qualquer coisa, fazei tudo para a glória de Deus." },
{name:'461032',l:'46',c:'10',v:'32',texto:"Portai-vos de modo que não deis escândalo nem aos judeus, nem aos gregos, nem à igreja de Deus." },
{name:'461033',l:'46',c:'10',v:'33',texto:"Como também eu em tudo agrado a todos, não buscando o meu próprio proveito, mas o de muitos, para que assim se possam salvar." },
],
numVersiculos: 33,
},

c11: {
versiculos:[
{name:'46111',l:'46',c:'11',v:'1',texto:"Sede meus imitadores, como também eu, de Cristo." },
{name:'46112',l:'46',c:'11',v:'2',texto:"E louvo-vos, irmãos, porque em tudo vos lembrais de mim e retendes os preceitos como vo-los entreguei." },
{name:'46113',l:'46',c:'11',v:'3',texto:"Mas quero que saibais que Cristo é a cabeça de todo varão, e o varão, a cabeça da mulher; e Deus, a cabeça de Cristo." },
{name:'46114',l:'46',c:'11',v:'4',texto:"Todo homem que ora ou profetiza, tendo a cabeça coberta, desonra a sua própria cabeça." },
{name:'46115',l:'46',c:'11',v:'5',texto:"Mas toda mulher que ora ou profetiza com a cabeça descoberta desonra a sua própria cabeça, porque é como se estivesse rapada." },
{name:'46116',l:'46',c:'11',v:'6',texto:"Portanto, se a mulher não se cobre com véu, tosquie-se também. Mas, se para a mulher é coisa indecente tosquiar-se ou rapar-se, que ponha o véu." },
{name:'46117',l:'46',c:'11',v:'7',texto:"O varão, pois, não deve cobrir a cabeça, porque é a imagem e glória de Deus, mas a mulher é a glória do varão." },
{name:'46118',l:'46',c:'11',v:'8',texto:"Porque o varão não provém da mulher, mas a mulher, do varão." },
{name:'46119',l:'46',c:'11',v:'9',texto:"Porque também o varão não foi criado por causa da mulher, mas a mulher, por causa do varão." },
{name:'461110',l:'46',c:'11',v:'10',texto:"Portanto, a mulher deve ter sobre a cabeça sinal de poderio, por causa dos anjos." },
{name:'461111',l:'46',c:'11',v:'11',texto:"Todavia, nem o varão é sem a mulher, nem a mulher, sem o varão, no Senhor." },
{name:'461112',l:'46',c:'11',v:'12',texto:"Porque, como a mulher provém do varão, assim também o varão provém da mulher, mas tudo vem de Deus." },
{name:'461113',l:'46',c:'11',v:'13',texto:"Julgai entre vós mesmos: é decente que a mulher ore a Deus descoberta?" },
{name:'461114',l:'46',c:'11',v:'14',texto:"Ou não vos ensina a mesma natureza que é desonra para o varão ter cabelo crescido?" },
{name:'461115',l:'46',c:'11',v:'15',texto:"Mas ter a mulher cabelo crescido lhe é honroso, porque o cabelo lhe foi dado em lugar de véu." },
{name:'461116',l:'46',c:'11',v:'16',texto:"Mas, se alguém quiser ser contencioso, nós não temos tal costume, nem as igrejas de Deus." },
{name:'461117',l:'46',c:'11',v:'17',texto:"Nisto, porém, que vou dizer-vos, não vos louvo, porquanto vos ajuntais, não para melhor, senão para pior." },
{name:'461118',l:'46',c:'11',v:'18',texto:"Porque, antes de tudo, ouço que, quando vos ajuntais na igreja, há entre vós dissensões; e em parte o creio." },
{name:'461119',l:'46',c:'11',v:'19',texto:"E até importa que haja entre vós heresias, para que os que são sinceros se manifestem entre vós." },
{name:'461120',l:'46',c:'11',v:'20',texto:"De sorte que, quando vos ajuntais num lugar, não é para comer a Ceia do Senhor." },
{name:'461121',l:'46',c:'11',v:'21',texto:"Porque, comendo, cada um toma antecipadamente a sua própria ceia; e assim um tem fome, e outro embriaga-se." },
{name:'461122',l:'46',c:'11',v:'22',texto:"Não tendes, porventura, casas para comer e para beber? Ou desprezais a igreja de Deus e envergonhais os que nada têm? Que vos direi? Louvar-vos-ei? Nisso não vos louvo." },
{name:'461123',l:'46',c:'11',v:'23',texto:"Porque eu recebi do Senhor o que também vos ensinei: que o Senhor Jesus, na noite em que foi traído, tomou o pão;" },
{name:'461124',l:'46',c:'11',v:'24',texto:"e, tendo dado graças, o partiu e disse: Tomai, comei; isto é o meu corpo que é partido por vós; fazei isto em memória de mim." },
{name:'461125',l:'46',c:'11',v:'25',texto:"Semelhantemente também, depois de cear, tomou o cálice, dizendo: Este cálice é o Novo Testamento no meu sangue; fazei isto, todas as vezes que beberdes, em memória de mim." },
{name:'461126',l:'46',c:'11',v:'26',texto:"Porque, todas as vezes que comerdes este pão e beberdes este cálice, anunciais a morte do Senhor, até que venha." },
{name:'461127',l:'46',c:'11',v:'27',texto:"Portanto, qualquer que comer este pão ou beber o cálice do Senhor, indignamente, será culpado do corpo e do sangue do Senhor." },
{name:'461128',l:'46',c:'11',v:'28',texto:"Examine-se, pois, o homem a si mesmo, e assim coma deste pão, e beba deste cálice." },
{name:'461129',l:'46',c:'11',v:'29',texto:"Porque o que come e bebe indignamente come e bebe para sua própria condenação, não discernindo o corpo do Senhor." },
{name:'461130',l:'46',c:'11',v:'30',texto:"Por causa disso, há entre vós muitos fracos e doentes e muitos que dormem." },
{name:'461131',l:'46',c:'11',v:'31',texto:"Porque, se nós nos julgássemos a nós mesmos, não seríamos julgados." },
{name:'461132',l:'46',c:'11',v:'32',texto:"Mas, quando somos julgados, somos repreendidos pelo Senhor, para não sermos condenados com o mundo." },
{name:'461133',l:'46',c:'11',v:'33',texto:"Portanto, meus irmãos, quando vos ajuntais para comer, esperai uns pelos outros." },
{name:'461134',l:'46',c:'11',v:'34',texto:"Mas, se algum tiver fome, coma em casa, para que vos não ajunteis para condenação. Quanto às demais coisas, ordená-las-ei quando for ter convosco." },
],
numVersiculos: 34,
},

c12: {
versiculos:[
{name:'46121',l:'46',c:'12',v:'1',texto:"Acerca dos dons espirituais, não quero, irmãos, que sejais ignorantes." },
{name:'46122',l:'46',c:'12',v:'2',texto:"Vós bem sabeis que éreis gentios, levados aos ídolos mudos, conforme éreis guiados." },
{name:'46123',l:'46',c:'12',v:'3',texto:"Portanto, vos quero fazer compreender que ninguém que fala pelo Espírito de Deus diz: Jesus é anátema! E ninguém pode dizer que Jesus é o Senhor, senão pelo Espírito Santo." },
{name:'46124',l:'46',c:'12',v:'4',texto:"Ora, há diversidade de dons, mas o Espírito é o mesmo." },
{name:'46125',l:'46',c:'12',v:'5',texto:"E há diversidade de ministérios, mas o Senhor é o mesmo." },
{name:'46126',l:'46',c:'12',v:'6',texto:"E há diversidade de operações, mas é o mesmo Deus que opera tudo em todos." },
{name:'46127',l:'46',c:'12',v:'7',texto:"Mas a manifestação do Espírito é dada a cada um para o que for útil." },
{name:'46128',l:'46',c:'12',v:'8',texto:"Porque a um, pelo Espírito, é dada a palavra da sabedoria; e a outro, pelo mesmo Espírito, a palavra da ciência;" },
{name:'46129',l:'46',c:'12',v:'9',texto:"e a outro, pelo mesmo Espírito, a fé; e a outro, pelo mesmo Espírito, os dons de curar;" },
{name:'461210',l:'46',c:'12',v:'10',texto:"e a outro, a operação de maravilhas; e a outro, a profecia; e a outro, o dom de discernir os espíritos; e a outro, a variedade de línguas; e a outro, a interpretação das línguas." },
{name:'461211',l:'46',c:'12',v:'11',texto:"Mas um só e o mesmo Espírito opera todas essas coisas, repartindo particularmente a cada um como quer." },
{name:'461212',l:'46',c:'12',v:'12',texto:"Porque, assim como o corpo é um e tem muitos membros, e todos os membros, sendo muitos, são um só corpo, assim é Cristo também." },
{name:'461213',l:'46',c:'12',v:'13',texto:"Pois todos nós fomos batizados em um Espírito, formando um corpo, quer judeus, quer gregos, quer servos, quer livres, e todos temos bebido de um Espírito." },
{name:'461214',l:'46',c:'12',v:'14',texto:"Porque também o corpo não é um só membro, mas muitos." },
{name:'461215',l:'46',c:'12',v:'15',texto:"Se o pé disser: Porque não sou mão, não sou do corpo; não será por isso do corpo?" },
{name:'461216',l:'46',c:'12',v:'16',texto:"E, se a orelha disser: Porque não sou olho, não sou do corpo; não será por isso do corpo?" },
{name:'461217',l:'46',c:'12',v:'17',texto:"Se todo o corpo fosse olho, onde estaria o ouvido? Se todo fosse ouvido, onde estaria o olfato?" },
{name:'461218',l:'46',c:'12',v:'18',texto:"Mas, agora, Deus colocou os membros no corpo, cada um deles como quis." },
{name:'461219',l:'46',c:'12',v:'19',texto:"E, se todos fossem um só membro, onde estaria o corpo?" },
{name:'461220',l:'46',c:'12',v:'20',texto:"Agora, pois, há muitos membros, mas um corpo." },
{name:'461221',l:'46',c:'12',v:'21',texto:"E o olho não pode dizer à mão: Não tenho necessidade de ti; nem ainda a cabeça, aos pés: Não tenho necessidade de vós." },
{name:'461222',l:'46',c:'12',v:'22',texto:"Antes, os membros do corpo que parecem ser os mais fracos são necessários." },
{name:'461223',l:'46',c:'12',v:'23',texto:"E os que reputamos serem menos honrosos no corpo, a esses honramos muito mais; e aos que em nós são menos decorosos damos muito mais honra." },
{name:'461224',l:'46',c:'12',v:'24',texto:"Porque os que em nós são mais honestos não têm necessidade disso, mas Deus assim formou o corpo, dando muito mais honra ao que tinha falta dela," },
{name:'461225',l:'46',c:'12',v:'25',texto:"para que não haja divisão no corpo, mas, antes, tenham os membros igual cuidado uns dos outros." },
{name:'461226',l:'46',c:'12',v:'26',texto:"De maneira que, se um membro padece, todos os membros padecem com ele; e, se um membro é honrado, todos os membros se regozijam com ele." },
{name:'461227',l:'46',c:'12',v:'27',texto:"Ora, vós sois o corpo de Cristo e seus membros em particular." },
{name:'461228',l:'46',c:'12',v:'28',texto:"E a uns pôs Deus na igreja, primeiramente, apóstolos, em segundo lugar, profetas, em terceiro, doutores, depois, milagres, depois, dons de curar, socorros, governos, variedades de línguas." },
{name:'461229',l:'46',c:'12',v:'29',texto:"Porventura, são todos apóstolos? São todos profetas? São todos doutores? São todos operadores de milagres?" },
{name:'461230',l:'46',c:'12',v:'30',texto:"Têm todos o dom de curar? Falam todos diversas línguas? Interpretam todos?" },
{name:'461231',l:'46',c:'12',v:'31',texto:"Portanto, procurai com zelo os melhores dons; e eu vos mostrarei um caminho ainda mais excelente." },
],
numVersiculos: 31,
},

c13: {
versiculos:[
{name:'46131',l:'46',c:'13',v:'1',texto:"Ainda que eu falasse as línguas dos homens e dos anjos e não tivesse caridade, seria como o metal que soa ou como o sino que tine." },
{name:'46132',l:'46',c:'13',v:'2',texto:"E ainda que tivesse o dom de profecia, e conhecesse todos os mistérios e toda a ciência, e ainda que tivesse toda a fé, de maneira tal que transportasse os montes, e não tivesse caridade, nada seria." },
{name:'46133',l:'46',c:'13',v:'3',texto:"E ainda que distribuísse toda a minha fortuna para sustento dos pobres, e ainda que entregasse o meu corpo para ser queimado, e não tivesse caridade, nada disso me aproveitaria." },
{name:'46134',l:'46',c:'13',v:'4',texto:"A caridade é sofredora, é benigna; a caridade não é invejosa; a caridade não trata com leviandade, não se ensoberbece," },
{name:'46135',l:'46',c:'13',v:'5',texto:"não se porta com indecência, não busca os seus interesses, não se irrita, não suspeita mal;" },
{name:'46136',l:'46',c:'13',v:'6',texto:"não folga com a injustiça, mas folga com a verdade;" },
{name:'46137',l:'46',c:'13',v:'7',texto:"tudo sofre, tudo crê, tudo espera, tudo suporta." },
{name:'46138',l:'46',c:'13',v:'8',texto:"A caridade nunca falha; mas, havendo profecias, serão aniquiladas; havendo línguas, cessarão; havendo ciência, desaparecerá;" },
{name:'46139',l:'46',c:'13',v:'9',texto:"porque, em parte, conhecemos e, em parte, profetizamos." },
{name:'461310',l:'46',c:'13',v:'10',texto:"Mas, quando vier o que é perfeito, então, o que o é em parte será aniquilado." },
{name:'461311',l:'46',c:'13',v:'11',texto:"Quando eu era menino, falava como menino, sentia como menino, discorria como menino, mas, logo que cheguei a ser homem, acabei com as coisas de menino." },
{name:'461312',l:'46',c:'13',v:'12',texto:"Porque, agora, vemos por espelho em enigma; mas, então, veremos face a face; agora, conheço em parte, mas, então, conhecerei como também sou conhecido." },
{name:'461313',l:'46',c:'13',v:'13',texto:"Agora, pois, permanecem a fé, a esperança e a caridade, estas três; mas a maior destas é a caridade." },
],
numVersiculos: 13,
},

c14: {
versiculos:[
{name:'46141',l:'46',c:'14',v:'1',texto:"Segui a caridade e procurai com zelo os dons espirituais, mas principalmente o de profetizar." },
{name:'46142',l:'46',c:'14',v:'2',texto:"Porque o que fala língua estranha não fala aos homens, senão a Deus; porque ninguém o entende, e em espírito fala de mistérios." },
{name:'46143',l:'46',c:'14',v:'3',texto:"Mas o que profetiza fala aos homens para edificação, exortação e consolação." },
{name:'46144',l:'46',c:'14',v:'4',texto:"O que fala língua estranha edifica-se a si mesmo, mas o que profetiza edifica a igreja." },
{name:'46145',l:'46',c:'14',v:'5',texto:"E eu quero que todos vós faleis línguas estranhas; mas muito mais que profetizeis, porque o que profetiza é maior do que o que fala línguas estranhas, a não ser que também interprete, para que a igreja receba edificação." },
{name:'46146',l:'46',c:'14',v:'6',texto:"E, agora, irmãos, se eu for ter convosco falando línguas estranhas, que vos aproveitaria, se vos não falasse ou por meio da revelação, ou da ciência, ou da profecia, ou da doutrina?" },
{name:'46147',l:'46',c:'14',v:'7',texto:"Da mesma sorte, se as coisas inanimadas que fazem som, seja flauta, seja cítara, não formarem sons distintos, como se conhecerá o que se toca com a flauta ou com a cítara?" },
{name:'46148',l:'46',c:'14',v:'8',texto:"Porque, se a trombeta der sonido incerto, quem se preparará para a batalha?" },
{name:'46149',l:'46',c:'14',v:'9',texto:"Assim, também vós, se, com a língua, não pronunciardes palavras bem inteligíveis, como se entenderá o que se diz? Porque estareis como que falando ao ar." },
{name:'461410',l:'46',c:'14',v:'10',texto:"Há, por exemplo, tanta espécie de vozes no mundo, e nenhuma delas é sem significação." },
{name:'461411',l:'46',c:'14',v:'11',texto:"Mas, se eu ignorar o sentido da voz, serei bárbaro para aquele a quem falo, e o que fala será bárbaro para mim." },
{name:'461412',l:'46',c:'14',v:'12',texto:"Assim, também vós, como desejais dons espirituais, procurai sobejar neles, para a edificação da igreja." },
{name:'461413',l:'46',c:'14',v:'13',texto:"Pelo que, o que fala língua estranha, ore para que a possa interpretar." },
{name:'461414',l:'46',c:'14',v:'14',texto:"Porque, se eu orar em língua estranha, o meu espírito ora bem, mas o meu entendimento fica sem fruto." },
{name:'461415',l:'46',c:'14',v:'15',texto:"Que farei, pois? Orarei com o espírito, mas também orarei com o entendimento; cantarei com o espírito, mas também cantarei com o entendimento." },
{name:'461416',l:'46',c:'14',v:'16',texto:"Doutra maneira, se tu bendisseres com o espírito, como dirá o que ocupa o lugar de indouto o Amém sobre a tua ação de graças, visto que não sabe o que dizes?" },
{name:'461417',l:'46',c:'14',v:'17',texto:"Porque realmente tu dás bem as graças, mas o outro não é edificado." },
{name:'461418',l:'46',c:'14',v:'18',texto:"Dou graças ao meu Deus, porque falo mais línguas do que vós todos." },
{name:'461419',l:'46',c:'14',v:'19',texto:"Todavia eu antes quero falar na igreja cinco palavras na minha própria inteligência, para que possa também instruir os outros, do que dez mil palavras em língua desconhecida." },
{name:'461420',l:'46',c:'14',v:'20',texto:"Irmãos, não sejais meninos no entendimento, mas sede meninos na malícia e adultos no entendimento." },
{name:'461421',l:'46',c:'14',v:'21',texto:"Está escrito na lei: Por gente doutras línguas e por outros lábios, falarei a este povo; e ainda assim me não ouvirão, diz o Senhor." },
{name:'461422',l:'46',c:'14',v:'22',texto:"De sorte que as línguas são um sinal, não para os fiéis, mas para os infiéis; e a profecia não é sinal para os infiéis, mas para os fiéis." },
{name:'461423',l:'46',c:'14',v:'23',texto:"Se, pois, toda a igreja se congregar num lugar, e todos falarem línguas estranhas, e entrarem indoutos ou infiéis, não dirão, porventura, que estais loucos?" },
{name:'461424',l:'46',c:'14',v:'24',texto:"Mas, se todos profetizarem, e algum indouto ou infiel entrar, de todos é convencido, de todos é julgado." },
{name:'461425',l:'46',c:'14',v:'25',texto:"Os segredos do seu coração ficarão manifestos, e assim, lançando-se sobre o seu rosto, adorará a Deus, publicando que Deus está verdadeiramente entre vós." },
{name:'461426',l:'46',c:'14',v:'26',texto:"Que fareis, pois, irmãos? Quando vos ajuntais, cada um de vós tem salmo, tem doutrina, tem revelação, tem língua, tem interpretação. Faça-se tudo para edificação." },
{name:'461427',l:'46',c:'14',v:'27',texto:"E, se alguém falar língua estranha, faça-se isso por dois ou, quando muito, três, e por sua vez, e haja intérprete." },
{name:'461428',l:'46',c:'14',v:'28',texto:"Mas, se não houver intérprete, esteja calado na igreja e fale consigo mesmo e com Deus." },
{name:'461429',l:'46',c:'14',v:'29',texto:"E falem dois ou três profetas, e os outros julguem." },
{name:'461430',l:'46',c:'14',v:'30',texto:"Mas, se a outro, que estiver assentado, for revelada alguma coisa, cale-se o primeiro." },
{name:'461431',l:'46',c:'14',v:'31',texto:"Porque todos podereis profetizar, uns depois dos outros, para que todos aprendam e todos sejam consolados." },
{name:'461432',l:'46',c:'14',v:'32',texto:"E os espíritos dos profetas estão sujeitos aos profetas." },
{name:'461433',l:'46',c:'14',v:'33',texto:"Porque Deus não é Deus de confusão, senão de paz, como em todas as igrejas dos santos." },
{name:'461434',l:'46',c:'14',v:'34',texto:"As mulheres estejam caladas nas igrejas, porque lhes não é permitido falar; mas estejam sujeitas, como também ordena a lei." },
{name:'461435',l:'46',c:'14',v:'35',texto:"E, se querem aprender alguma coisa, interroguem em casa a seus próprios maridos; porque é indecente que as mulheres falem na igreja." },
{name:'461436',l:'46',c:'14',v:'36',texto:"Porventura, saiu dentre vós a palavra de Deus? Ou veio ela somente para vós?" },
{name:'461437',l:'46',c:'14',v:'37',texto:"Se alguém cuida ser profeta ou espiritual, reconheça que as coisas que vos escrevo são mandamentos do Senhor." },
{name:'461438',l:'46',c:'14',v:'38',texto:"Mas, se alguém ignora isso, que ignore." },
{name:'461439',l:'46',c:'14',v:'39',texto:"Portanto, irmãos, procurai, com zelo, profetizar e não proibais falar línguas." },
{name:'461440',l:'46',c:'14',v:'40',texto:"Mas faça-se tudo decentemente e com ordem." },
],
numVersiculos: 40,
},

c15: {
versiculos:[
{name:'46151',l:'46',c:'15',v:'1',texto:"Também vos notifico, irmãos, o evangelho que já vos tenho anunciado, o qual também recebestes e no qual também permaneceis;" },
{name:'46152',l:'46',c:'15',v:'2',texto:"pelo qual também sois salvos, se o retiverdes tal como vo-lo tenho anunciado, se não é que crestes em vão." },
{name:'46153',l:'46',c:'15',v:'3',texto:"Porque primeiramente vos entreguei o que também recebi: que Cristo morreu por nossos pecados, segundo as Escrituras," },
{name:'46154',l:'46',c:'15',v:'4',texto:"e que foi sepultado, e que ressuscitou ao terceiro dia, segundo as Escrituras," },
{name:'46155',l:'46',c:'15',v:'5',texto:"e que foi visto por Cefas e depois pelos doze." },
{name:'46156',l:'46',c:'15',v:'6',texto:"Depois, foi visto, uma vez, por mais de quinhentos irmãos, dos quais vive ainda a maior parte, mas alguns já dormem também." },
{name:'46157',l:'46',c:'15',v:'7',texto:"Depois, foi visto por Tiago, depois, por todos os apóstolos" },
{name:'46158',l:'46',c:'15',v:'8',texto:"e, por derradeiro de todos, me apareceu também a mim, como a um abortivo." },
{name:'46159',l:'46',c:'15',v:'9',texto:"Porque eu sou o menor dos apóstolos, que não sou digno de ser chamado apóstolo, pois que persegui a igreja de Deus." },
{name:'461510',l:'46',c:'15',v:'10',texto:"Mas, pela graça de Deus, sou o que sou; e a sua graça para comigo não foi vã; antes, trabalhei muito mais do que todos eles; todavia, não eu, mas a graça de Deus, que está comigo." },
{name:'461511',l:'46',c:'15',v:'11',texto:"Então, ou seja eu ou sejam eles, assim pregamos, e assim haveis crido." },
{name:'461512',l:'46',c:'15',v:'12',texto:"Ora, se se prega que Cristo ressuscitou dos mortos, como dizem alguns dentre vós que não há ressurreição de mortos?" },
{name:'461513',l:'46',c:'15',v:'13',texto:"E, se não há ressurreição de mortos, também Cristo não ressuscitou." },
{name:'461514',l:'46',c:'15',v:'14',texto:"E, se Cristo não ressuscitou, logo é vã a nossa pregação, e também é vã a vossa fé." },
{name:'461515',l:'46',c:'15',v:'15',texto:"E assim somos também considerados como falsas testemunhas de Deus, pois testificamos de Deus, que ressuscitou a Cristo, ao qual, porém, não ressuscitou, se, na verdade, os mortos não ressuscitam." },
{name:'461516',l:'46',c:'15',v:'16',texto:"Porque, se os mortos não ressuscitam, também Cristo não ressuscitou." },
{name:'461517',l:'46',c:'15',v:'17',texto:"E, se Cristo não ressuscitou, é vã a vossa fé, e ainda permaneceis nos vossos pecados." },
{name:'461518',l:'46',c:'15',v:'18',texto:"E também os que dormiram em Cristo estão perdidos." },
{name:'461519',l:'46',c:'15',v:'19',texto:"Se esperamos em Cristo só nesta vida, somos os mais miseráveis de todos os homens." },
{name:'461520',l:'46',c:'15',v:'20',texto:"Mas, agora, Cristo ressuscitou dos mortos e foi feito as primícias dos que dormem." },
{name:'461521',l:'46',c:'15',v:'21',texto:"Porque, assim como a morte veio por um homem, também a ressurreição dos mortos veio por um homem." },
{name:'461522',l:'46',c:'15',v:'22',texto:"Porque, assim como todos morrem em Adão, assim também todos serão vivificados em Cristo." },
{name:'461523',l:'46',c:'15',v:'23',texto:"Mas cada um por sua ordem: Cristo, as primícias; depois, os que são de Cristo, na sua vinda." },
{name:'461524',l:'46',c:'15',v:'24',texto:"Depois, virá o fim, quando tiver entregado o Reino a Deus, ao Pai, e quando houver aniquilado todo império e toda potestade e força." },
{name:'461525',l:'46',c:'15',v:'25',texto:"Porque convém que reine até que haja posto a todos os inimigos debaixo de seus pés." },
{name:'461526',l:'46',c:'15',v:'26',texto:"Ora, o último inimigo que há de ser aniquilado é a morte." },
{name:'461527',l:'46',c:'15',v:'27',texto:"Porque todas as coisas sujeitou debaixo de seus pés. Mas, quando diz que todas as coisas lhe estão sujeitas, claro está que se excetua aquele que sujeitou todas as coisas." },
{name:'461528',l:'46',c:'15',v:'28',texto:"E, quando todas as coisas lhe estiverem sujeitas, então, também o mesmo Filho se sujeitará àquele que todas as coisas lhe sujeitou, para que Deus seja tudo em todos." },
{name:'461529',l:'46',c:'15',v:'29',texto:"Doutra maneira, que farão os que se batizam pelos mortos, se absolutamente os mortos não ressuscitam? Por que se batizam eles, então, pelos mortos?" },
{name:'461530',l:'46',c:'15',v:'30',texto:"Por que estamos nós também a toda hora em perigo?" },
{name:'461531',l:'46',c:'15',v:'31',texto:"Eu protesto que cada dia morro gloriando-me em vós, irmãos, por Cristo Jesus, nosso Senhor." },
{name:'461532',l:'46',c:'15',v:'32',texto:"Se, como homem, combati em Éfeso contra as bestas, que me aproveita isso, se os mortos não ressuscitam? Comamos e bebamos, que amanhã morreremos." },
{name:'461533',l:'46',c:'15',v:'33',texto:"Não vos enganeis: as más conversações corrompem os bons costumes." },
{name:'461534',l:'46',c:'15',v:'34',texto:"Vigiai justamente e não pequeis; porque alguns ainda não têm o conhecimento de Deus; digo-o para vergonha vossa." },
{name:'461535',l:'46',c:'15',v:'35',texto:"Mas alguém dirá: Como ressuscitarão os mortos? E com que corpo virão?" },
{name:'461536',l:'46',c:'15',v:'36',texto:"Insensato! O que tu semeias não é vivificado, se primeiro não morrer." },
{name:'461537',l:'46',c:'15',v:'37',texto:"E, quando semeias, não semeias o corpo que há de nascer, mas o simples grão, como de trigo ou doutra qualquer semente." },
{name:'461538',l:'46',c:'15',v:'38',texto:"Mas Deus dá-lhe o corpo como quer e a cada semente, o seu próprio corpo." },
{name:'461539',l:'46',c:'15',v:'39',texto:"Nem toda carne é uma mesma carne; mas uma é a carne dos homens, e outra, a carne dos animais, e outra, a dos peixes, e outra, a das aves." },
{name:'461540',l:'46',c:'15',v:'40',texto:"E há corpos celestes e corpos terrestres, mas uma é a glória dos celestes, e outra, a dos terrestres." },
{name:'461541',l:'46',c:'15',v:'41',texto:"Uma é a glória do sol, e outra, a glória da lua, e outra, a glória das estrelas; porque uma estrela difere em glória de outra estrela." },
{name:'461542',l:'46',c:'15',v:'42',texto:"Assim também a ressurreição dos mortos. Semeia-se o corpo em corrupção, ressuscitará em incorrupção." },
{name:'461543',l:'46',c:'15',v:'43',texto:"Semeia-se em ignomínia, ressuscitará em glória. Semeia-se em fraqueza, ressuscitará com vigor." },
{name:'461544',l:'46',c:'15',v:'44',texto:"Semeia-se corpo animal, ressuscitará corpo espiritual. Se há corpo animal, há também corpo espiritual." },
{name:'461545',l:'46',c:'15',v:'45',texto:"Assim está também escrito: O primeiro homem, Adão, foi feito em alma vivente; o último Adão, em espírito vivificante." },
{name:'461546',l:'46',c:'15',v:'46',texto:"Mas não é primeiro o espiritual, senão o animal; depois, o espiritual." },
{name:'461547',l:'46',c:'15',v:'47',texto:"O primeiro homem, da terra, é terreno; o segundo homem, o Senhor, é do céu." },
{name:'461548',l:'46',c:'15',v:'48',texto:"Qual o terreno, tais são também os terrenos; e, qual o celestial, tais também os celestiais." },
{name:'461549',l:'46',c:'15',v:'49',texto:"E, assim como trouxemos a imagem do terreno, assim traremos também a imagem do celestial." },
{name:'461550',l:'46',c:'15',v:'50',texto:"E, agora, digo isto, irmãos: que carne e sangue não podem herdar o Reino de Deus, nem a corrupção herda a incorrupção." },
{name:'461551',l:'46',c:'15',v:'51',texto:"Eis aqui vos digo um mistério: Na verdade, nem todos dormiremos, mas todos seremos transformados," },
{name:'461552',l:'46',c:'15',v:'52',texto:"num momento, num abrir e fechar de olhos, ante a última trombeta; porque a trombeta soará, e os mortos ressuscitarão incorruptíveis, e nós seremos transformados." },
{name:'461553',l:'46',c:'15',v:'53',texto:"Porque convém que isto que é corruptível se revista da incorruptibilidade e que isto que é mortal se revista da imortalidade." },
{name:'461554',l:'46',c:'15',v:'54',texto:"E, quando isto que é corruptível se revestir da incorruptibilidade, e isto que é mortal se revestir da imortalidade, então, cumprir-se-á a palavra que está escrita: Tragada foi a morte na vitória." },
{name:'461555',l:'46',c:'15',v:'55',texto:"Onde está, ó morte, o teu aguilhão? Onde está, ó inferno, a tua vitória?" },
{name:'461556',l:'46',c:'15',v:'56',texto:"Ora, o aguilhão da morte é o pecado, e a força do pecado é a lei." },
{name:'461557',l:'46',c:'15',v:'57',texto:"Mas graças a Deus, que nos dá a vitória por nosso Senhor Jesus Cristo." },
{name:'461558',l:'46',c:'15',v:'58',texto:"Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor." },
],
numVersiculos: 58,
},

c16: {
versiculos:[
{name:'46161',l:'46',c:'16',v:'1',texto:"Ora, quanto à coleta que se faz para os santos, fazei vós também o mesmo que ordenei às igrejas da Galácia." },
{name:'46162',l:'46',c:'16',v:'2',texto:"No primeiro dia da semana, cada um de vós ponha de parte o que puder ajuntar, conforme a sua prosperidade, para que se não façam as coletas quando eu chegar." },
{name:'46163',l:'46',c:'16',v:'3',texto:"E, quando tiver chegado, mandarei os que, por cartas, aprovardes, para levar a vossa dádiva a Jerusalém." },
{name:'46164',l:'46',c:'16',v:'4',texto:"E, se valer a pena que eu também vá, irão comigo." },
{name:'46165',l:'46',c:'16',v:'5',texto:"Irei, porém, ter convosco depois de ter passado pela Macedônia ( porque tenho de passar pela Macedônia )." },
{name:'46166',l:'46',c:'16',v:'6',texto:"E bem pode ser que fique convosco e passe também o inverno, para que me acompanheis aonde quer que eu for." },
{name:'46167',l:'46',c:'16',v:'7',texto:"Porque não vos quero agora ver de passagem, mas espero ficar convosco algum tempo, se o Senhor o permitir." },
{name:'46168',l:'46',c:'16',v:'8',texto:"Ficarei, porém, em Éfeso até ao Pentecostes;" },
{name:'46169',l:'46',c:'16',v:'9',texto:"porque uma porta grande e eficaz se me abriu; e há muitos adversários." },
{name:'461610',l:'46',c:'16',v:'10',texto:"E, se for Timóteo, vede que esteja sem temor convosco; porque trabalha na obra do Senhor, como eu também." },
{name:'461611',l:'46',c:'16',v:'11',texto:"Portanto, ninguém o despreze, mas acompanhai-o em paz, para que venha ter comigo, pois o espero com os irmãos." },
{name:'461612',l:'46',c:'16',v:'12',texto:"E, acerca do irmão Apolo, roguei-lhe muito que fosse com os irmãos ter convosco, mas, na verdade, não teve vontade de ir agora; irá, porém, quando se lhe ofereça boa ocasião." },
{name:'461613',l:'46',c:'16',v:'13',texto:"Vigiai, estai firmes na fé, portai-vos varonilmente e fortalecei-vos." },
{name:'461614',l:'46',c:'16',v:'14',texto:"Todas as vossas coisas sejam feitas com caridade." },
{name:'461615',l:'46',c:'16',v:'15',texto:"Agora, vos rogo, irmãos ( sabeis que a família de Estéfanas é as primícias da Acaia e que se tem dedicado ao ministério dos santos )," },
{name:'461616',l:'46',c:'16',v:'16',texto:"que também vos sujeiteis aos tais e a todo aquele que auxilia na obra e trabalha." },
{name:'461617',l:'46',c:'16',v:'17',texto:"Folgo, porém, com a vinda de Estéfanas, e de Fortunato, e de Acaico; porque estes supriram o que da vossa parte me faltava." },
{name:'461618',l:'46',c:'16',v:'18',texto:"Porque recrearam o meu espírito e o vosso. Reconhecei, pois, aos tais." },
{name:'461619',l:'46',c:'16',v:'19',texto:"As igrejas da Ásia vos saúdam. Saúdam-vos afetuosamente no Senhor Áqüila e Prisca, com a igreja que está em sua casa." },
{name:'461620',l:'46',c:'16',v:'20',texto:"Todos os irmãos vos saúdam. Saudai-vos uns aos outros com ósculo santo." },
{name:'461621',l:'46',c:'16',v:'21',texto:"Saudação da minha própria mão, de Paulo." },
{name:'461622',l:'46',c:'16',v:'22',texto:"Se alguém não ama o Senhor Jesus Cristo, seja anátema; maranata!" },
{name:'461623',l:'46',c:'16',v:'23',texto:"A graça do Senhor Jesus Cristo seja convosco." },
{name:'461624',l:'46',c:'16',v:'24',texto:"O meu amor seja com todos vós, em Cristo Jesus. Amém!" },
],
numVersiculos: 24,
},


};
