BibliaJFA.galatas = {
	libro: "Gálatas",
	numCapitulos: 6,

c1: {
versiculos:[
{name:'4811',l:'48',c:'1',v:'1',texto:"Paulo, apóstolo ( não da parte dos homens, nem por homem algum, mas por Jesus Cristo e por Deus Pai, que o ressuscitou dos mortos )," },
{name:'4812',l:'48',c:'1',v:'2',texto:"e todos os irmãos que estão comigo, às igrejas da Galácia:" },
{name:'4813',l:'48',c:'1',v:'3',texto:"graça e paz, da parte de Deus Pai e da de nosso Senhor Jesus Cristo," },
{name:'4814',l:'48',c:'1',v:'4',texto:"o qual se deu a si mesmo por nossos pecados, para nos livrar do presente século mau, segundo a vontade de Deus, nosso Pai," },
{name:'4815',l:'48',c:'1',v:'5',texto:"ao qual glória para todo o sempre. Amém!" },
{name:'4816',l:'48',c:'1',v:'6',texto:"Maravilho-me de que tão depressa passásseis daquele que vos chamou à graça de Cristo para outro evangelho," },
{name:'4817',l:'48',c:'1',v:'7',texto:"o qual não é outro, mas há alguns que vos inquietam e querem transtornar o evangelho de Cristo." },
{name:'4818',l:'48',c:'1',v:'8',texto:"Mas, ainda que nós mesmos ou um anjo do céu vos anuncie outro evangelho além do que já vos tenho anunciado, seja anátema." },
{name:'4819',l:'48',c:'1',v:'9',texto:"Assim como já vo-lo dissemos, agora de novo também vo-lo digo: se alguém vos anunciar outro evangelho além do que já recebestes, seja anátema." },
{name:'48110',l:'48',c:'1',v:'10',texto:"Porque persuado eu agora a homens ou a Deus? Ou procuro agradar a homens? Se estivesse ainda agradando aos homens, não seria servo de Cristo." },
{name:'48111',l:'48',c:'1',v:'11',texto:"Mas faço-vos saber, irmãos, que o evangelho que por mim foi anunciado não é segundo os homens," },
{name:'48112',l:'48',c:'1',v:'12',texto:"porque não o recebi, nem aprendi de homem algum, mas pela revelação de Jesus Cristo." },
{name:'48113',l:'48',c:'1',v:'13',texto:"Porque já ouvistes qual foi antigamente a minha conduta no judaísmo, como sobremaneira perseguia a igreja de Deus e a assolava." },
{name:'48114',l:'48',c:'1',v:'14',texto:"E, na minha nação, excedia em judaísmo a muitos da minha idade, sendo extremamente zeloso das tradições de meus pais." },
{name:'48115',l:'48',c:'1',v:'15',texto:"Mas, quando aprouve a Deus, que desde o ventre de minha mãe me separou e me chamou pela sua graça," },
{name:'48116',l:'48',c:'1',v:'16',texto:"revelar seu Filho em mim, para que o pregasse entre os gentios, não consultei carne nem sangue," },
{name:'48117',l:'48',c:'1',v:'17',texto:"nem tornei a Jerusalém, a ter com os que já antes de mim eram apóstolos, mas parti para a Arábia e voltei outra vez a Damasco." },
{name:'48118',l:'48',c:'1',v:'18',texto:"Depois, passados três anos, fui a Jerusalém para ver a Pedro e fiquei com ele quinze dias." },
{name:'48119',l:'48',c:'1',v:'19',texto:"E não vi a nenhum outro dos apóstolos, senão a Tiago, irmão do Senhor." },
{name:'48120',l:'48',c:'1',v:'20',texto:"Ora, acerca do que vos escrevo, eis que diante de Deus testifico que não minto." },
{name:'48121',l:'48',c:'1',v:'21',texto:"Depois, fui para as partes da Síria e da Cilícia." },
{name:'48122',l:'48',c:'1',v:'22',texto:"E não era conhecido de vista das igrejas da Judéia, que estavam em Cristo;" },
{name:'48123',l:'48',c:'1',v:'23',texto:"mas somente tinham ouvido dizer: Aquele que já nos perseguiu anuncia, agora, a fé que, antes, destruía." },
{name:'48124',l:'48',c:'1',v:'24',texto:"E glorificavam a Deus a respeito de mim." },
],
numVersiculos: 24,
},

c2: {
versiculos:[
{name:'4821',l:'48',c:'2',v:'1',texto:"Depois, passados catorze anos, subi outra vez a Jerusalém com Barnabé, levando também comigo Tito." },
{name:'4822',l:'48',c:'2',v:'2',texto:"E subi por uma revelação e lhes expus o evangelho que prego entre os gentios e particularmente aos que estavam em estima, para que de maneira alguma não corresse ou não tivesse corrido em vão." },
{name:'4823',l:'48',c:'2',v:'3',texto:"Mas nem ainda Tito, que estava comigo, sendo grego, foi constrangido a circuncidar-se." },
{name:'4824',l:'48',c:'2',v:'4',texto:"E isso por causa dos falsos irmãos que se tinham entremetido e secretamente entraram a espiar a nossa liberdade que temos em Cristo Jesus, para nos porem em servidão;" },
{name:'4825',l:'48',c:'2',v:'5',texto:"aos quais, nem ainda por uma hora, cedemos com sujeição, para que a verdade do evangelho permanecesse entre vós." },
{name:'4826',l:'48',c:'2',v:'6',texto:"E, quanto àqueles que pareciam ser alguma coisa ( quais tenham sido noutro tempo, não se me dá; Deus não aceita a aparência do homem ), esses, digo, que pareciam ser alguma coisa, nada me comunicaram;" },
{name:'4827',l:'48',c:'2',v:'7',texto:"antes, pelo contrário, quando viram que o evangelho da incircuncisão me estava confiado, como a Pedro o da circuncisão" },
{name:'4828',l:'48',c:'2',v:'8',texto:"( porque aquele que operou eficazmente em Pedro para o apostolado da circuncisão, esse operou também em mim com eficácia para com os gentios )," },
{name:'4829',l:'48',c:'2',v:'9',texto:"e conhecendo Tiago, Cefas e João, que eram considerados como as colunas, a graça que se me havia dado, deram-nos as destras, em comunhão comigo e com Barnabé, para que nós fôssemos aos gentios e eles, à circuncisão;" },
{name:'48210',l:'48',c:'2',v:'10',texto:"recomendando-nos somente que nos lembrássemos dos pobres, o que também procurei fazer com diligência." },
{name:'48211',l:'48',c:'2',v:'11',texto:"E, chegando Pedro à Antioquia, lhe resisti na cara, porque era repreensível." },
{name:'48212',l:'48',c:'2',v:'12',texto:"Porque, antes que alguns tivessem chegado da parte de Tiago, comia com os gentios; mas, depois que chegaram, se foi retirando e se apartou deles, temendo os que eram da circuncisão." },
{name:'48213',l:'48',c:'2',v:'13',texto:"E os outros judeus também dissimulavam com ele, de maneira que até Barnabé se deixou levar pela sua dissimulação." },
{name:'48214',l:'48',c:'2',v:'14',texto:"Mas, quando vi que não andavam bem e direitamente conforme a verdade do evangelho, disse a Pedro na presença de todos: Se tu, sendo judeu, vives como os gentios e não como judeu, por que obrigas os gentios a viverem como judeus?" },
{name:'48215',l:'48',c:'2',v:'15',texto:"Nós somos judeus por natureza e não pecadores dentre os gentios." },
{name:'48216',l:'48',c:'2',v:'16',texto:"Sabendo que o homem não é justificado pelas obras da lei, mas pela fé em Jesus Cristo, temos também crido em Jesus Cristo, para sermos justificados pela fé de Cristo e não pelas obras da lei, porquanto pelas obras da lei nenhuma carne será justificada." },
{name:'48217',l:'48',c:'2',v:'17',texto:"Pois, se nós, que procuramos ser justificados em Cristo, nós mesmos também somos achados pecadores, é, porventura, Cristo ministro do pecado? De maneira nenhuma." },
{name:'48218',l:'48',c:'2',v:'18',texto:"Porque, se torno a edificar aquilo que destruí, constituo-me a mim mesmo transgressor." },
{name:'48219',l:'48',c:'2',v:'19',texto:"Porque eu, pela lei, estou morto para a lei, para viver para Deus." },
{name:'48220',l:'48',c:'2',v:'20',texto:"Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim; e a vida que agora vivo na carne vivo-a na fé do Filho de Deus, o qual me amou e se entregou a si mesmo por mim." },
{name:'48221',l:'48',c:'2',v:'21',texto:"Não aniquilo a graça de Deus; porque, se a justiça provém da lei, segue-se que Cristo morreu debalde." },
],
numVersiculos: 21,
},

c3: {
versiculos:[
{name:'4831',l:'48',c:'3',v:'1',texto:"Ó insensatos gálatas! Quem vos fascinou para não obedecerdes à verdade, a vós, perante os olhos de quem Jesus Cristo foi já representado como crucificado?" },
{name:'4832',l:'48',c:'3',v:'2',texto:"Só quisera saber isto de vós: recebestes o Espírito pelas obras da lei ou pela pregação da fé?" },
{name:'4833',l:'48',c:'3',v:'3',texto:"Sois vós tão insensatos que, tendo começado pelo Espírito, acabeis agora pela carne?" },
{name:'4834',l:'48',c:'3',v:'4',texto:"Será em vão que tenhais padecido tanto? Se é que isso também foi em vão." },
{name:'4835',l:'48',c:'3',v:'5',texto:"Aquele, pois, que vos dá o Espírito e que opera maravilhas entre vós o faz pelas obras da lei ou pela pregação da fé?" },
{name:'4836',l:'48',c:'3',v:'6',texto:"É o caso de Abraão, que creu em Deus, e isso lhe foi imputado como justiça." },
{name:'4837',l:'48',c:'3',v:'7',texto:"Sabei, pois, que os que são da fé são filhos de Abraão." },
{name:'4838',l:'48',c:'3',v:'8',texto:"Ora, tendo a Escritura previsto que Deus havia de justificar pela fé os gentios, anunciou primeiro o evangelho a Abraão, dizendo: Todas as nações serão benditas em ti." },
{name:'4839',l:'48',c:'3',v:'9',texto:"De sorte que os que são da fé são benditos com o crente Abraão." },
{name:'48310',l:'48',c:'3',v:'10',texto:"Todos aqueles, pois, que são das obras da lei estão debaixo da maldição; porque escrito está: Maldito todo aquele que não permanecer em todas as coisas que estão escritas no livro da lei, para fazê-las." },
{name:'48311',l:'48',c:'3',v:'11',texto:"E é evidente que, pela lei, ninguém será justificado diante de Deus, porque o justo viverá da fé." },
{name:'48312',l:'48',c:'3',v:'12',texto:"Ora, a lei não é da fé, mas o homem que fizer estas coisas por elas viverá." },
{name:'48313',l:'48',c:'3',v:'13',texto:"Cristo nos resgatou da maldição da lei, fazendo-se maldição por nós, porque está escrito: Maldito todo aquele que for pendurado no madeiro;" },
{name:'48314',l:'48',c:'3',v:'14',texto:"para que a bênção de Abraão chegasse aos gentios por Jesus Cristo e para que, pela fé, nós recebamos a promessa do Espírito." },
{name:'48315',l:'48',c:'3',v:'15',texto:"Irmãos, como homem falo. Se o testamento de um homem for confirmado, ninguém o anula nem lhe acrescenta alguma coisa." },
{name:'48316',l:'48',c:'3',v:'16',texto:"Ora, as promessas foram feitas a Abraão e à sua posteridade. Não diz: E às posteridades, como falando de muitas, mas como de uma só: E à tua posteridade, que é Cristo." },
{name:'48317',l:'48',c:'3',v:'17',texto:"Mas digo isto: que tendo sido o testamento anteriormente confirmado por Deus, a lei, que veio quatrocentos e trinta anos depois, não o invalida, de forma a abolir a promessa." },
{name:'48318',l:'48',c:'3',v:'18',texto:"Porque, se a herança provém da lei, já não provém da promessa; mas Deus, pela promessa, a deu gratuitamente a Abraão." },
{name:'48319',l:'48',c:'3',v:'19',texto:"Logo, para que é a lei? Foi ordenada por causa das transgressões, até que viesse a posteridade a quem a promessa tinha sido feita, e foi posta pelos anjos na mão de um medianeiro." },
{name:'48320',l:'48',c:'3',v:'20',texto:"Ora, o medianeiro não o é de um só, mas Deus é um." },
{name:'48321',l:'48',c:'3',v:'21',texto:"Logo, a lei é contra as promessas de Deus? De nenhuma sorte; porque, se dada fosse uma lei que pudesse vivificar, a justiça, na verdade, teria sido pela lei." },
{name:'48322',l:'48',c:'3',v:'22',texto:"Mas a Escritura encerrou tudo debaixo do pecado, para que a promessa pela fé em Jesus Cristo fosse dada aos crentes." },
{name:'48323',l:'48',c:'3',v:'23',texto:"Mas, antes que a fé viesse, estávamos guardados debaixo da lei e encerrados para aquela fé que se havia de manifestar." },
{name:'48324',l:'48',c:'3',v:'24',texto:"De maneira que a lei nos serviu de aio, para nos conduzir a Cristo, para que, pela fé, fôssemos justificados." },
{name:'48325',l:'48',c:'3',v:'25',texto:"Mas, depois que a fé veio, já não estamos debaixo de aio." },
{name:'48326',l:'48',c:'3',v:'26',texto:"Porque todos sois filhos de Deus pela fé em Cristo Jesus;" },
{name:'48327',l:'48',c:'3',v:'27',texto:"porque todos quantos fostes batizados em Cristo já vos revestistes de Cristo." },
{name:'48328',l:'48',c:'3',v:'28',texto:"Nisto não há judeu nem grego; não há servo nem livre; não há macho nem fêmea; porque todos vós sois um em Cristo Jesus." },
{name:'48329',l:'48',c:'3',v:'29',texto:"E, se sois de Cristo, então, sois descendência de Abraão e herdeiros conforme a promessa." },
],
numVersiculos: 29,
},

c4: {
versiculos:[
{name:'4841',l:'48',c:'4',v:'1',texto:"Digo, pois, que, todo o tempo em que o herdeiro é menino, em nada difere do servo, ainda que seja senhor de tudo." },
{name:'4842',l:'48',c:'4',v:'2',texto:"Mas está debaixo de tutores e curadores até ao tempo determinado pelo pai." },
{name:'4843',l:'48',c:'4',v:'3',texto:"Assim também nós, quando éramos meninos, estávamos reduzidos à servidão debaixo dos primeiros rudimentos do mundo;" },
{name:'4844',l:'48',c:'4',v:'4',texto:"mas, vindo a plenitude dos tempos, Deus enviou seu Filho, nascido de mulher, nascido sob a lei," },
{name:'4845',l:'48',c:'4',v:'5',texto:"para remir os que estavam debaixo da lei, a fim de recebermos a adoção de filhos." },
{name:'4846',l:'48',c:'4',v:'6',texto:"E, porque sois filhos, Deus enviou aos nossos corações o Espírito de seu Filho, que clama: Aba, Pai." },
{name:'4847',l:'48',c:'4',v:'7',texto:"Assim que já não és mais servo, mas filho; e, se és filho, és também herdeiro de Deus por Cristo." },
{name:'4848',l:'48',c:'4',v:'8',texto:"Mas, quando não conhecíeis a Deus, servíeis aos que por natureza não são deuses." },
{name:'4849',l:'48',c:'4',v:'9',texto:"Mas agora, conhecendo a Deus ou, antes, sendo conhecidos de Deus, como tornais outra vez a esses rudimentos fracos e pobres, aos quais de novo quereis servir?" },
{name:'48410',l:'48',c:'4',v:'10',texto:"Guardais dias, e meses, e tempos, e anos." },
{name:'48411',l:'48',c:'4',v:'11',texto:"Receio de vós que haja eu trabalhado em vão para convosco." },
{name:'48412',l:'48',c:'4',v:'12',texto:"Irmãos, rogo-vos que sejais como eu, porque também eu sou como vós; nenhum mal me fizestes." },
{name:'48413',l:'48',c:'4',v:'13',texto:"E vós sabeis que primeiro vos anunciei o evangelho estando em fraqueza da carne." },
{name:'48414',l:'48',c:'4',v:'14',texto:"E não rejeitastes, nem desprezastes isso que era uma tentação na minha carne; antes, me recebestes como um anjo de Deus, como Jesus Cristo mesmo." },
{name:'48415',l:'48',c:'4',v:'15',texto:"Qual é, logo, a vossa bem-aventurança? Porque vos dou testemunho de que, se possível fora, arrancaríeis os olhos, e mos daríeis." },
{name:'48416',l:'48',c:'4',v:'16',texto:"Fiz-me, acaso, vosso inimigo, dizendo a verdade?" },
{name:'48417',l:'48',c:'4',v:'17',texto:"Eles têm zelo por vós, não como convém; mas querem excluir-vos, para que vós tenhais zelo por eles." },
{name:'48418',l:'48',c:'4',v:'18',texto:"É bom ser zeloso, mas sempre do bem e não somente quando estou presente convosco." },
{name:'48419',l:'48',c:'4',v:'19',texto:"Meus filhinhos, por quem de novo sinto as dores de parto, até que Cristo seja formado em vós;" },
{name:'48420',l:'48',c:'4',v:'20',texto:"eu bem quisera, agora, estar presente convosco e mudar a minha voz; porque estou perplexo a vosso respeito." },
{name:'48421',l:'48',c:'4',v:'21',texto:"Dizei-me vós, os que quereis estar debaixo da lei: não ouvis vós a lei?" },
{name:'48422',l:'48',c:'4',v:'22',texto:"Porque está escrito que Abraão teve dois filhos, um da escrava e outro da livre." },
{name:'48423',l:'48',c:'4',v:'23',texto:"Todavia, o que era da escrava nasceu segundo a carne, mas o que era da livre, por promessa," },
{name:'48424',l:'48',c:'4',v:'24',texto:"o que se entende por alegoria; porque estes são os dois concertos: um, do monte Sinai, gerando filhos para a servidão, que é Agar." },
{name:'48425',l:'48',c:'4',v:'25',texto:"Ora, esta Agar é Sinai, um monte da Arábia, que corresponde à Jerusalém que agora existe, pois é escrava com seus filhos." },
{name:'48426',l:'48',c:'4',v:'26',texto:"Mas a Jerusalém que é de cima é livre, a qual é mãe de todos nós;" },
{name:'48427',l:'48',c:'4',v:'27',texto:"porque está escrito: Alegra-te, estéril, que não dás à luz, esforça-te e clama, tu que não estás de parto; porque os filhos da solitária são mais do que os da que tem marido." },
{name:'48428',l:'48',c:'4',v:'28',texto:"Mas nós, irmãos, somos filhos da promessa, como Isaque." },
{name:'48429',l:'48',c:'4',v:'29',texto:"Mas, como, então, aquele que era gerado segundo a carne perseguia o que o era segundo o Espírito, assim é também, agora." },
{name:'48430',l:'48',c:'4',v:'30',texto:"Mas que diz a Escritura? Lança fora a escrava e seu filho, porque, de modo algum, o filho da escrava herdará com o filho da livre." },
{name:'48431',l:'48',c:'4',v:'31',texto:"De maneira que, irmãos, somos filhos não da escrava, mas da livre." },
],
numVersiculos: 31,
},

c5: {
versiculos:[
{name:'4851',l:'48',c:'5',v:'1',texto:"Estai, pois, firmes na liberdade com que Cristo nos libertou e não torneis a meter-vos debaixo do jugo da servidão." },
{name:'4852',l:'48',c:'5',v:'2',texto:"Eis que eu, Paulo, vos digo que, se vos deixardes circuncidar, Cristo de nada vos aproveitará." },
{name:'4853',l:'48',c:'5',v:'3',texto:"E, de novo, protesto a todo homem que se deixa circuncidar que está obrigado a guardar toda a lei." },
{name:'4854',l:'48',c:'5',v:'4',texto:"Separados estais de Cristo, vós os que vos justificais pela lei; da graça tendes caído." },
{name:'4855',l:'48',c:'5',v:'5',texto:"Porque nós, pelo espírito da fé, aguardamos a esperança da justiça." },
{name:'4856',l:'48',c:'5',v:'6',texto:"Porque, em Jesus Cristo, nem a circuncisão nem a incircuncisão têm virtude alguma, mas, sim, a fé que opera por caridade." },
{name:'4857',l:'48',c:'5',v:'7',texto:"Corríeis bem; quem vos impediu, para que não obedeçais à verdade?" },
{name:'4858',l:'48',c:'5',v:'8',texto:"Esta persuasão não vem daquele que vos chamou." },
{name:'4859',l:'48',c:'5',v:'9',texto:"Um pouco de fermento leveda toda a massa." },
{name:'48510',l:'48',c:'5',v:'10',texto:"Confio de vós, no Senhor, que nenhuma outra coisa sentireis; mas aquele que vos inquieta, seja ele quem for, sofrerá a condenação." },
{name:'48511',l:'48',c:'5',v:'11',texto:"Eu, porém, irmãos, se prego ainda a circuncisão, por que sou, pois, perseguido? Logo, o escândalo da cruz está aniquilado." },
{name:'48512',l:'48',c:'5',v:'12',texto:"Eu quereria que fossem cortados aqueles que vos andam inquietando." },
{name:'48513',l:'48',c:'5',v:'13',texto:"Porque vós, irmãos, fostes chamados à liberdade. Não useis, então, da liberdade para dar ocasião à carne, mas servi-vos uns aos outros pela caridade." },
{name:'48514',l:'48',c:'5',v:'14',texto:"Porque toda a lei se cumpre numa só palavra, nesta: Amarás o teu próximo como a ti mesmo." },
{name:'48515',l:'48',c:'5',v:'15',texto:"Se vós, porém, vos mordeis e devorais uns aos outros, vede não vos consumais também uns aos outros." },
{name:'48516',l:'48',c:'5',v:'16',texto:"Digo, porém: Andai em Espírito e não cumprireis a concupiscência da carne." },
{name:'48517',l:'48',c:'5',v:'17',texto:"Porque a carne cobiça contra o Espírito, e o Espírito, contra a carne; e estes opõem-se um ao outro; para que não façais o que quereis." },
{name:'48518',l:'48',c:'5',v:'18',texto:"Mas, se sois guiados pelo Espírito, não estais debaixo da lei." },
{name:'48519',l:'48',c:'5',v:'19',texto:"Porque as obras da carne são manifestas, as quais são: prostituição, impureza, lascívia," },
{name:'48520',l:'48',c:'5',v:'20',texto:"idolatria, feitiçarias, inimizades, porfias, emulações, iras, pelejas, dissensões, heresias," },
{name:'48521',l:'48',c:'5',v:'21',texto:"invejas, homicídios, bebedices, glutonarias e coisas semelhantes a estas, acerca das quais vos declaro, como já antes vos disse, que os que cometem tais coisas não herdarão o Reino de Deus." },
{name:'48522',l:'48',c:'5',v:'22',texto:"Mas o fruto do Espírito é: caridade, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança." },
{name:'48523',l:'48',c:'5',v:'23',texto:"Contra essas coisas não há lei." },
{name:'48524',l:'48',c:'5',v:'24',texto:"E os que são de Cristo crucificaram a carne com as suas paixões e concupiscências." },
{name:'48525',l:'48',c:'5',v:'25',texto:"Se vivemos no Espírito, andemos também no Espírito." },
{name:'48526',l:'48',c:'5',v:'26',texto:"Não sejamos cobiçosos de vanglórias, irritando-nos uns aos outros, invejando-nos uns aos outros." },
],
numVersiculos: 26,
},

c6: {
versiculos:[
{name:'4861',l:'48',c:'6',v:'1',texto:"Irmãos, se algum homem chegar a ser surpreendido nalguma ofensa, vós, que sois espirituais, encaminhai o tal com espírito de mansidão, olhando por ti mesmo, para que não sejas também tentado." },
{name:'4862',l:'48',c:'6',v:'2',texto:"Levai as cargas uns dos outros e assim cumprireis a lei de Cristo." },
{name:'4863',l:'48',c:'6',v:'3',texto:"Porque, se alguém cuida ser alguma coisa, não sendo nada, engana-se a si mesmo." },
{name:'4864',l:'48',c:'6',v:'4',texto:"Mas prove cada um a sua própria obra e terá glória só em si mesmo e não noutro." },
{name:'4865',l:'48',c:'6',v:'5',texto:"Porque cada qual levará a sua própria carga." },
{name:'4866',l:'48',c:'6',v:'6',texto:"E o que é instruído na palavra reparta de todos os seus bens com aquele que o instrui." },
{name:'4867',l:'48',c:'6',v:'7',texto:"Não erreis: Deus não se deixa escarnecer; porque tudo o que o homem semear, isso também ceifará." },
{name:'4868',l:'48',c:'6',v:'8',texto:"Porque o que semeia na sua carne da carne ceifará a corrupção; mas o que semeia no Espírito do Espírito ceifará a vida eterna." },
{name:'4869',l:'48',c:'6',v:'9',texto:"E não nos cansemos de fazer o bem, porque a seu tempo ceifaremos, se não houvermos desfalecido." },
{name:'48610',l:'48',c:'6',v:'10',texto:"Então, enquanto temos tempo, façamos o bem a todos, mas principalmente aos domésticos da fé." },
{name:'48611',l:'48',c:'6',v:'11',texto:"Vede com que grandes letras vos escrevi por minha mão." },
{name:'48612',l:'48',c:'6',v:'12',texto:"Todos os que querem mostrar boa aparência na carne, esses vos obrigam a circuncidar-vos, somente para não serem perseguidos por causa da cruz de Cristo." },
{name:'48613',l:'48',c:'6',v:'13',texto:"Porque nem ainda esses mesmos que se circuncidam guardam a lei, mas querem que vos circuncideis, para se gloriarem na vossa carne." },
{name:'48614',l:'48',c:'6',v:'14',texto:"Mas longe esteja de mim gloriar-me, a não ser na cruz de nosso Senhor Jesus Cristo, pela qual o mundo está crucificado para mim e eu, para o mundo." },
{name:'48615',l:'48',c:'6',v:'15',texto:"Porque, em Cristo Jesus, nem a circuncisão nem a incircuncisão têm virtude alguma, mas sim o ser uma nova criatura." },
{name:'48616',l:'48',c:'6',v:'16',texto:"E, a todos quantos andarem conforme esta regra, paz e misericórdia sobre eles e sobre o Israel de Deus." },
{name:'48617',l:'48',c:'6',v:'17',texto:"Desde agora, ninguém me inquiete; porque trago no meu corpo as marcas do Senhor Jesus." },
{name:'48618',l:'48',c:'6',v:'18',texto:"A graça de nosso Senhor Jesus Cristo seja, irmãos, com o vosso espírito. Amém!" },
],
numVersiculos: 18,
},

	
};
