BibliaJFA.efesios = {
	libro: "Efésios",
	numCapitulos: 6,

c1: {
versiculos:[
{name:'4911',l:'49',c:'1',v:'1',texto:"Paulo, apóstolo de Jesus Cristo, pela vontade de Deus, aos santos que estão em Éfeso e fiéis em Cristo Jesus:" },
{name:'4912',l:'49',c:'1',v:'2',texto:"a vós graça e paz, da parte de Deus, nosso Pai, e da do Senhor Jesus Cristo." },
{name:'4913',l:'49',c:'1',v:'3',texto:"Bendito o Deus e Pai de nosso Senhor Jesus Cristo, o qual nos abençoou com todas as bênçãos espirituais nos lugares celestiais em Cristo," },
{name:'4914',l:'49',c:'1',v:'4',texto:"como também nos elegeu nele antes da fundação do mundo, para que fôssemos santos e irrepreensíveis diante dele em caridade," },
{name:'4915',l:'49',c:'1',v:'5',texto:"e nos predestinou para filhos de adoção por Jesus Cristo, para si mesmo, segundo o beneplácito de sua vontade," },
{name:'4916',l:'49',c:'1',v:'6',texto:"para louvor e glória da sua graça, pela qual nos fez agradáveis a si no Amado." },
{name:'4917',l:'49',c:'1',v:'7',texto:"Em quem temos a redenção pelo seu sangue, a remissão das ofensas, segundo as riquezas da sua graça," },
{name:'4918',l:'49',c:'1',v:'8',texto:"que Ele tornou abundante para conosco em toda a sabedoria e prudência," },
{name:'4919',l:'49',c:'1',v:'9',texto:"descobrindo-nos o mistério da sua vontade, segundo o seu beneplácito, que propusera em si mesmo," },
{name:'49110',l:'49',c:'1',v:'10',texto:"de tornar a congregar em Cristo todas as coisas, na dispensação da plenitude dos tempos, tanto as que estão nos céus como as que estão na terra;" },
{name:'49111',l:'49',c:'1',v:'11',texto:"nele, digo, em quem também fomos feitos herança, havendo sido predestinados conforme o propósito daquele que faz todas as coisas, segundo o conselho da sua vontade," },
{name:'49112',l:'49',c:'1',v:'12',texto:"com o fim de sermos para louvor da sua glória, nós, os que primeiro esperamos em Cristo;" },
{name:'49113',l:'49',c:'1',v:'13',texto:"em quem também vós estais, depois que ouvistes a palavra da verdade, o evangelho da vossa salvação; e, tendo nele também crido, fostes selados com o Espírito Santo da promessa;" },
{name:'49114',l:'49',c:'1',v:'14',texto:"o qual é o penhor da nossa herança, para redenção da possessão de Deus, para louvor da sua glória." },
{name:'49115',l:'49',c:'1',v:'15',texto:"Pelo que, ouvindo eu também a fé que entre vós há no Senhor Jesus e a vossa caridade para com todos os santos," },
{name:'49116',l:'49',c:'1',v:'16',texto:"não cesso de dar graças a Deus por vós, lembrando-me de vós nas minhas orações," },
{name:'49117',l:'49',c:'1',v:'17',texto:"para que o Deus de nosso Senhor Jesus Cristo, o Pai da glória, vos dê em seu conhecimento o espírito de sabedoria e de revelação," },
{name:'49118',l:'49',c:'1',v:'18',texto:"tendo iluminados os olhos do vosso entendimento, para que saibais qual seja a esperança da sua vocação e quais as riquezas da glória da sua herança nos santos" },
{name:'49119',l:'49',c:'1',v:'19',texto:"e qual a sobreexcelente grandeza do seu poder sobre nós, os que cremos, segundo a operação da força do seu poder," },
{name:'49120',l:'49',c:'1',v:'20',texto:"que manifestou em Cristo, ressuscitando-o dos mortos e pondo-o à sua direita nos céus," },
{name:'49121',l:'49',c:'1',v:'21',texto:"acima de todo principado, e poder, e potestade, e domínio, e de todo nome que se nomeia, não só neste século, mas também no vindouro." },
{name:'49122',l:'49',c:'1',v:'22',texto:"E sujeitou todas as coisas a seus pés e, sobre todas as coisas, o constituiu como cabeça da igreja," },
{name:'49123',l:'49',c:'1',v:'23',texto:"que é o seu corpo, a plenitude daquele que cumpre tudo em todos." },
],
numVersiculos: 23,
},

c2: {
versiculos:[
{name:'4921',l:'49',c:'2',v:'1',texto:"E vos vivificou, estando vós mortos em ofensas e pecados," },
{name:'4922',l:'49',c:'2',v:'2',texto:"em que, noutro tempo, andastes, segundo o curso deste mundo, segundo o príncipe das potestades do ar, do espírito que, agora, opera nos filhos da desobediência;" },
{name:'4923',l:'49',c:'2',v:'3',texto:"entre os quais todos nós também, antes, andávamos nos desejos da nossa carne, fazendo a vontade da carne e dos pensamentos; e éramos por natureza filhos da ira, como os outros também." },
{name:'4924',l:'49',c:'2',v:'4',texto:"Mas Deus, que é riquíssimo em misericórdia, pelo seu muito amor com que nos amou," },
{name:'4925',l:'49',c:'2',v:'5',texto:"estando nós ainda mortos em nossas ofensas, nos vivificou juntamente com Cristo ( pela graça sois salvos )," },
{name:'4926',l:'49',c:'2',v:'6',texto:"e nos ressuscitou juntamente com ele, e nos fez assentar nos lugares celestiais, em Cristo Jesus;" },
{name:'4927',l:'49',c:'2',v:'7',texto:"para mostrar nos séculos vindouros as abundantes riquezas da sua graça, pela sua benignidade para conosco em Cristo Jesus." },
{name:'4928',l:'49',c:'2',v:'8',texto:"Porque pela graça sois salvos, por meio da fé; e isso não vem de vós; é dom de Deus." },
{name:'4929',l:'49',c:'2',v:'9',texto:"Não vem das obras, para que ninguém se glorie." },
{name:'49210',l:'49',c:'2',v:'10',texto:"Porque somos feitura sua, criados em Cristo Jesus para as boas obras, as quais Deus preparou para que andássemos nelas." },
{name:'49211',l:'49',c:'2',v:'11',texto:"Portanto, lembrai-vos de que vós, noutro tempo, éreis gentios na carne e chamados incircuncisão pelos que, na carne, se chamam circuncisão feita pela mão dos homens;" },
{name:'49212',l:'49',c:'2',v:'12',texto:"que, naquele tempo, estáveis sem Cristo, separados da comunidade de Israel e estranhos aos concertos da promessa, não tendo esperança e sem Deus no mundo." },
{name:'49213',l:'49',c:'2',v:'13',texto:"Mas, agora, em Cristo Jesus, vós, que antes estáveis longe, já pelo sangue de Cristo chegastes perto." },
{name:'49214',l:'49',c:'2',v:'14',texto:"Porque ele é a nossa paz, o qual de ambos os povos fez um; e, derribando a parede de separação que estava no meio," },
{name:'49215',l:'49',c:'2',v:'15',texto:"na sua carne, desfez a inimizade, isto é, a lei dos mandamentos, que consistia em ordenanças, para criar em si mesmo dos dois um novo homem, fazendo a paz," },
{name:'49216',l:'49',c:'2',v:'16',texto:"e, pela cruz, reconciliar ambos com Deus em um corpo, matando com ela as inimizades." },
{name:'49217',l:'49',c:'2',v:'17',texto:"E, vindo, ele evangelizou a paz a vós que estáveis longe e aos que estavam perto;" },
{name:'49218',l:'49',c:'2',v:'18',texto:"porque, por ele, ambos temos acesso ao Pai em um mesmo Espírito." },
{name:'49219',l:'49',c:'2',v:'19',texto:"Assim que já não sois estrangeiros, nem forasteiros, mas concidadãos dos Santos e da família de Deus;" },
{name:'49220',l:'49',c:'2',v:'20',texto:"edificados sobre o fundamento dos apóstolos e dos profetas, de que Jesus Cristo é a principal pedra da esquina;" },
{name:'49221',l:'49',c:'2',v:'21',texto:"no qual todo o edifício, bem ajustado, cresce para templo santo no Senhor," },
{name:'49222',l:'49',c:'2',v:'22',texto:"no qual também vós juntamente sois edificados para morada de Deus no Espírito." },
],
numVersiculos: 22,
},

c3: {
versiculos:[
{name:'4931',l:'49',c:'3',v:'1',texto:"Por esta causa, eu, Paulo, sou o prisioneiro de Jesus Cristo por vós, os gentios," },
{name:'4932',l:'49',c:'3',v:'2',texto:"se é que tendes ouvido a dispensação da graça de Deus, que para convosco me foi dada;" },
{name:'4933',l:'49',c:'3',v:'3',texto:"como me foi este mistério manifestado pela revelação como acima, em pouco, vos escrevi," },
{name:'4934',l:'49',c:'3',v:'4',texto:"pelo que, quando ledes, podeis perceber a minha compreensão do mistério de Cristo," },
{name:'4935',l:'49',c:'3',v:'5',texto:"o qual, noutros séculos, não foi manifestado aos filhos dos homens, como, agora, tem sido revelado pelo Espírito aos seus santos apóstolos e profetas," },
{name:'4936',l:'49',c:'3',v:'6',texto:"a saber, que os gentios são co-herdeiros, e de um mesmo corpo, e participantes da promessa em Cristo pelo evangelho;" },
{name:'4937',l:'49',c:'3',v:'7',texto:"do qual fui feito ministro, pelo dom da graça de Deus, que me foi dado segundo a operação do seu poder." },
{name:'4938',l:'49',c:'3',v:'8',texto:"A mim, o mínimo de todos os santos, me foi dada esta graça de anunciar entre os gentios, por meio do evangelho, as riquezas incompreensíveis de Cristo" },
{name:'4939',l:'49',c:'3',v:'9',texto:"e demonstrar a todos qual seja a dispensação do mistério, que, desde os séculos, esteve oculto em Deus, que tudo criou;" },
{name:'49310',l:'49',c:'3',v:'10',texto:"para que, agora, pela igreja, a multiforme sabedoria de Deus seja conhecida dos principados e potestades nos céus," },
{name:'49311',l:'49',c:'3',v:'11',texto:"segundo o eterno propósito que fez em Cristo Jesus, nosso Senhor," },
{name:'49312',l:'49',c:'3',v:'12',texto:"no qual temos ousadia e acesso com confiança, pela nossa fé nele." },
{name:'49313',l:'49',c:'3',v:'13',texto:"Portanto, vos peço que não desfaleçais nas minhas tribulações por vós, que são a vossa glória." },
{name:'49314',l:'49',c:'3',v:'14',texto:"Por causa disso, me ponho de joelhos perante o Pai de nosso Senhor Jesus Cristo," },
{name:'49315',l:'49',c:'3',v:'15',texto:"do qual toda a família nos céus e na terra toma o nome," },
{name:'49316',l:'49',c:'3',v:'16',texto:"para que, segundo as riquezas da sua glória, vos conceda que sejais corroborados com poder pelo seu Espírito no homem interior;" },
{name:'49317',l:'49',c:'3',v:'17',texto:"para que Cristo habite, pela fé, no vosso coração; a fim de, estando arraigados e fundados em amor," },
{name:'49318',l:'49',c:'3',v:'18',texto:"poderdes perfeitamente compreender, com todos os santos, qual seja a largura, e o comprimento, e a altura, e a profundidade" },
{name:'49319',l:'49',c:'3',v:'19',texto:"e conhecer o amor de Cristo, que excede todo entendimento, para que sejais cheios de toda a plenitude de Deus." },
{name:'49320',l:'49',c:'3',v:'20',texto:"Ora, àquele que é poderoso para fazer tudo muito mais abundantemente além daquilo que pedimos ou pensamos, segundo o poder que em nós opera," },
{name:'49321',l:'49',c:'3',v:'21',texto:"a esse glória na igreja, por Jesus Cristo, em todas as gerações, para todo o sempre. Amém!" },
],
numVersiculos: 21,
},

c4: {
versiculos:[
{name:'4941',l:'49',c:'4',v:'1',texto:"Rogo-vos, pois, eu, o preso do Senhor, que andeis como é digno da vocação com que fostes chamados," },
{name:'4942',l:'49',c:'4',v:'2',texto:"com toda a humildade e mansidão, com longanimidade, suportando-vos uns aos outros em amor," },
{name:'4943',l:'49',c:'4',v:'3',texto:"procurando guardar a unidade do Espírito pelo vínculo da paz:" },
{name:'4944',l:'49',c:'4',v:'4',texto:"há um só corpo e um só Espírito, como também fostes chamados em uma só esperança da vossa vocação;" },
{name:'4945',l:'49',c:'4',v:'5',texto:"um só Senhor, uma só fé, um só batismo;" },
{name:'4946',l:'49',c:'4',v:'6',texto:"um só Deus e Pai de todos, o qual é sobre todos, e por todos, e em todos." },
{name:'4947',l:'49',c:'4',v:'7',texto:"Mas a graça foi dada a cada um de nós segundo a medida do dom de Cristo." },
{name:'4948',l:'49',c:'4',v:'8',texto:"Pelo que diz: Subindo ao alto, levou cativo o cativeiro e deu dons aos homens." },
{name:'4949',l:'49',c:'4',v:'9',texto:"Ora, isto—ele subiu—que é, senão que também, antes, tinha descido às partes mais baixas da terra?" },
{name:'49410',l:'49',c:'4',v:'10',texto:"Aquele que desceu é também o mesmo que subiu acima de todos os céus, para cumprir todas as coisas." },
{name:'49411',l:'49',c:'4',v:'11',texto:"E ele mesmo deu uns para apóstolos, e outros para profetas, e outros para evangelistas, e outros para pastores e doutores," },
{name:'49412',l:'49',c:'4',v:'12',texto:"querendo o aperfeiçoamento dos santos, para a obra do ministério, para edificação do corpo de Cristo," },
{name:'49413',l:'49',c:'4',v:'13',texto:"até que todos cheguemos à unidade da fé e ao conhecimento do Filho de Deus, a varão perfeito, à medida da estatura completa de Cristo," },
{name:'49414',l:'49',c:'4',v:'14',texto:"para que não sejamos mais meninos inconstantes, levados em roda por todo vento de doutrina, pelo engano dos homens que, com astúcia, enganam fraudulosamente." },
{name:'49415',l:'49',c:'4',v:'15',texto:"Antes, seguindo a verdade em caridade, cresçamos em tudo naquele que é a cabeça, Cristo," },
{name:'49416',l:'49',c:'4',v:'16',texto:"do qual todo o corpo, bem ajustado e ligado pelo auxílio de todas as juntas, segundo a justa operação de cada parte, faz o aumento do corpo, para sua edificação em amor." },
{name:'49417',l:'49',c:'4',v:'17',texto:"E digo isto e testifico no Senhor, para que não andeis mais como andam também os outros gentios, na vaidade do seu sentido," },
{name:'49418',l:'49',c:'4',v:'18',texto:"entenebrecidos no entendimento, separados da vida de Deus, pela ignorância que há neles, pela dureza do seu coração," },
{name:'49419',l:'49',c:'4',v:'19',texto:"os quais, havendo perdido todo o sentimento, se entregaram à dissolução, para, com avidez, cometerem toda impureza." },
{name:'49420',l:'49',c:'4',v:'20',texto:"Mas vós não aprendestes assim a Cristo," },
{name:'49421',l:'49',c:'4',v:'21',texto:"se é que o tendes ouvido e nele fostes ensinados, como está a verdade em Jesus," },
{name:'49422',l:'49',c:'4',v:'22',texto:"que, quanto ao trato passado, vos despojeis do velho homem, que se corrompe pelas concupiscências do engano," },
{name:'49423',l:'49',c:'4',v:'23',texto:"e vos renoveis no espírito do vosso sentido," },
{name:'49424',l:'49',c:'4',v:'24',texto:"e vos revistais do novo homem, que, segundo Deus, é criado em verdadeira justiça e santidade." },
{name:'49425',l:'49',c:'4',v:'25',texto:"Pelo que deixai a mentira e falai a verdade cada um com o seu próximo; porque somos membros uns dos outros." },
{name:'49426',l:'49',c:'4',v:'26',texto:"Irai-vos e não pequeis; não se ponha o sol sobre a vossa ira." },
{name:'49427',l:'49',c:'4',v:'27',texto:"Não deis lugar ao diabo." },
{name:'49428',l:'49',c:'4',v:'28',texto:"Aquele que furtava não furte mais; antes, trabalhe, fazendo com as mãos o que é bom, para que tenha o que repartir com o que tiver necessidade." },
{name:'49429',l:'49',c:'4',v:'29',texto:"Não saia da vossa boca nenhuma palavra torpe, mas só a que for boa para promover a edificação, para que dê graça aos que a ouvem." },
{name:'49430',l:'49',c:'4',v:'30',texto:"E não entristeçais o Espírito Santo de Deus, no qual estais selados para o Dia da redenção." },
{name:'49431',l:'49',c:'4',v:'31',texto:"Toda amargura, e ira, e cólera, e gritaria, e blasfêmias, e toda malícia seja tirada de entre vós." },
{name:'49432',l:'49',c:'4',v:'32',texto:"Antes, sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo." },
],
numVersiculos: 32,
},

c5: {
versiculos:[
{name:'4951',l:'49',c:'5',v:'1',texto:"Sede, pois, imitadores de Deus, como filhos amados;" },
{name:'4952',l:'49',c:'5',v:'2',texto:"e andai em amor, como também Cristo vos amou e se entregou a si mesmo por nós, em oferta e sacrifício a Deus, em cheiro suave." },
{name:'4953',l:'49',c:'5',v:'3',texto:"Mas a prostituição e toda impureza ou avareza nem ainda se nomeiem entre vós, como convém a santos;" },
{name:'4954',l:'49',c:'5',v:'4',texto:"nem torpezas, nem parvoíces, nem chocarrices, que não convêm; mas, antes, ações de graças." },
{name:'4955',l:'49',c:'5',v:'5',texto:"Porque bem sabeis isto: que nenhum fornicador, ou impuro, ou avarento, o qual é idólatra, tem herança no Reino de Cristo e de Deus." },
{name:'4956',l:'49',c:'5',v:'6',texto:"Ninguém vos engane com palavras vãs; porque por essas coisas vem a ira de Deus sobre os filhos da desobediência." },
{name:'4957',l:'49',c:'5',v:'7',texto:"Portanto, não sejais seus companheiros." },
{name:'4958',l:'49',c:'5',v:'8',texto:"Porque, noutro tempo, éreis trevas, mas, agora, sois luz no Senhor; andai como filhos da luz" },
{name:'4959',l:'49',c:'5',v:'9',texto:"( porque o fruto do Espírito está em toda bondade, e justiça, e verdade )," },
{name:'49510',l:'49',c:'5',v:'10',texto:"aprovando o que é agradável ao Senhor." },
{name:'49511',l:'49',c:'5',v:'11',texto:"E não comuniqueis com as obras infrutuosas das trevas, mas, antes, condenai-as." },
{name:'49512',l:'49',c:'5',v:'12',texto:"Porque o que eles fazem em oculto, até dizê-lo é torpe." },
{name:'49513',l:'49',c:'5',v:'13',texto:"Mas todas essas coisas se manifestam, sendo condenadas pela luz, porque a luz tudo manifesta." },
{name:'49514',l:'49',c:'5',v:'14',texto:"Pelo que diz: Desperta, ó tu que dormes, e levanta-te dentre os mortos, e Cristo te esclarecerá." },
{name:'49515',l:'49',c:'5',v:'15',texto:"Portanto, vede prudentemente como andais, não como néscios, mas como sábios," },
{name:'49516',l:'49',c:'5',v:'16',texto:"remindo o tempo, porquanto os dias são maus." },
{name:'49517',l:'49',c:'5',v:'17',texto:"Pelo que não sejais insensatos, mas entendei qual seja a vontade do Senhor." },
{name:'49518',l:'49',c:'5',v:'18',texto:"E não vos embriagueis com vinho, em que há contenda, mas enchei-vos do Espírito," },
{name:'49519',l:'49',c:'5',v:'19',texto:"falando entre vós com salmos, e hinos, e cânticos espirituais, cantando e salmodiando ao Senhor no vosso coração," },
{name:'49520',l:'49',c:'5',v:'20',texto:"dando sempre graças por tudo a nosso Deus e Pai, em nome de nosso Senhor Jesus Cristo," },
{name:'49521',l:'49',c:'5',v:'21',texto:"sujeitando-vos uns aos outros no temor de Deus." },
{name:'49522',l:'49',c:'5',v:'22',texto:"Vós, mulheres, sujeitai-vos a vosso marido, como ao Senhor;" },
{name:'49523',l:'49',c:'5',v:'23',texto:"porque o marido é a cabeça da mulher, como também Cristo é a cabeça da igreja, sendo ele próprio o salvador do corpo." },
{name:'49524',l:'49',c:'5',v:'24',texto:"De sorte que, assim como a igreja está sujeita a Cristo, assim também as mulheres sejam em tudo sujeitas a seu marido." },
{name:'49525',l:'49',c:'5',v:'25',texto:"Vós, maridos, amai vossa mulher, como também Cristo amou a igreja e a si mesmo se entregou por ela," },
{name:'49526',l:'49',c:'5',v:'26',texto:"para a santificar, purificando-a com a lavagem da água, pela palavra," },
{name:'49527',l:'49',c:'5',v:'27',texto:"para a apresentar a si mesmo igreja gloriosa, sem mácula, nem ruga, nem coisa semelhante, mas santa e irrepreensível." },
{name:'49528',l:'49',c:'5',v:'28',texto:"Assim devem os maridos amar a sua própria mulher como a seu próprio corpo. Quem ama a sua mulher ama-se a si mesmo." },
{name:'49529',l:'49',c:'5',v:'29',texto:"Porque nunca ninguém aborreceu a sua própria carne; antes, a alimenta e sustenta, como também o Senhor à igreja;" },
{name:'49530',l:'49',c:'5',v:'30',texto:"porque somos membros do seu corpo." },
{name:'49531',l:'49',c:'5',v:'31',texto:"Por isso, deixará o homem seu pai e sua mãe e se unirá à sua mulher; e serão dois numa carne." },
{name:'49532',l:'49',c:'5',v:'32',texto:"Grande é este mistério; digo-o, porém, a respeito de Cristo e da igreja." },
{name:'49533',l:'49',c:'5',v:'33',texto:"Assim também vós, cada um em particular ame a sua própria mulher como a si mesmo, e a mulher reverencie o marido." },
],
numVersiculos: 33,
},

c6: {
versiculos:[
{name:'4961',l:'49',c:'6',v:'1',texto:"Vós, filhos, sede obedientes a vossos pais no Senhor, porque isto é justo." },
{name:'4962',l:'49',c:'6',v:'2',texto:"Honra a teu pai e a tua mãe, que é o primeiro mandamento com promessa," },
{name:'4963',l:'49',c:'6',v:'3',texto:"para que te vá bem, e vivas muito tempo sobre a terra." },
{name:'4964',l:'49',c:'6',v:'4',texto:"E vós, pais, não provoqueis a ira a vossos filhos, mas criai-os na doutrina e admoestação do Senhor." },
{name:'4965',l:'49',c:'6',v:'5',texto:"Vós, servos, obedecei a vosso senhor segundo a carne, com temor e tremor, na sinceridade de vosso coração, como a Cristo," },
{name:'4966',l:'49',c:'6',v:'6',texto:"não servindo à vista, como para agradar aos homens, mas como servos de Cristo, fazendo de coração a vontade de Deus;" },
{name:'4967',l:'49',c:'6',v:'7',texto:"servindo de boa vontade como ao Senhor e não como aos homens," },
{name:'4968',l:'49',c:'6',v:'8',texto:"sabendo que cada um receberá do Senhor todo o bem que fizer, seja servo, seja livre." },
{name:'4969',l:'49',c:'6',v:'9',texto:"E vós, senhores, fazei o mesmo para com eles, deixando as ameaças, sabendo também que o Senhor deles e vosso está no céu e que para com ele não há acepção de pessoas." },
{name:'49610',l:'49',c:'6',v:'10',texto:"No demais, irmãos meus, fortalecei-vos no Senhor e na força do seu poder." },
{name:'49611',l:'49',c:'6',v:'11',texto:"Revesti-vos de toda a armadura de Deus, para que possais estar firmes contra as astutas ciladas do diabo;" },
{name:'49612',l:'49',c:'6',v:'12',texto:"porque não temos que lutar contra carne e sangue, mas, sim, contra os principados, contra as potestades, contra os príncipes das trevas deste século, contra as hostes espirituais da maldade, nos lugares celestiais." },
{name:'49613',l:'49',c:'6',v:'13',texto:"Portanto, tomai toda a armadura de Deus, para que possais resistir no dia mau e, havendo feito tudo, ficar firmes." },
{name:'49614',l:'49',c:'6',v:'14',texto:"Estai, pois, firmes, tendo cingidos os vossos lombos com a verdade, e vestida a couraça da justiça," },
{name:'49615',l:'49',c:'6',v:'15',texto:"e calçados os pés na preparação do evangelho da paz;" },
{name:'49616',l:'49',c:'6',v:'16',texto:"tomando sobretudo o escudo da fé, com o qual podereis apagar todos os dardos inflamados do maligno." },
{name:'49617',l:'49',c:'6',v:'17',texto:"Tomai também o capacete da salvação e a espada do Espírito, que é a palavra de Deus," },
{name:'49618',l:'49',c:'6',v:'18',texto:"orando em todo tempo com toda oração e súplica no Espírito e vigiando nisso com toda perseverança e súplica por todos os santos" },
{name:'49619',l:'49',c:'6',v:'19',texto:"e por mim; para que me seja dada, no abrir da minha boca, a palavra com confiança, para fazer notório o mistério do evangelho," },
{name:'49620',l:'49',c:'6',v:'20',texto:"pelo qual sou embaixador em cadeias; para que possa falar dele livremente, como me convém falar." },
{name:'49621',l:'49',c:'6',v:'21',texto:"Ora, para que vós também possais saber dos meus negócios e o que eu faço, Tíquico, irmão amado e fiel ministro do Senhor, vos informará de tudo," },
{name:'49622',l:'49',c:'6',v:'22',texto:"o qual vos enviei para o mesmo fim, para que saibais do nosso estado, e ele console os vossos corações." },
{name:'49623',l:'49',c:'6',v:'23',texto:"Paz seja com os irmãos e caridade com fé, da parte de Deus Pai e da do Senhor Jesus Cristo." },
{name:'49624',l:'49',c:'6',v:'24',texto:"A graça seja com todos os que amam a nosso Senhor Jesus Cristo em sinceridade. Amém!" },
],
numVersiculos: 24,
},


};
