BibliaJFA.colosenses = {
	libro: "Colossenses",
	numCapitulos: 4,

c1: {
versiculos:[
{name:'5111',l:'51',c:'1',v:'1',texto:"Paulo, apóstolo de Jesus Cristo, pela vontade de Deus, e o irmão Timóteo," },
{name:'5112',l:'51',c:'1',v:'2',texto:"aos santos e irmãos fiéis em Cristo que estão em Colossos: graça a vós e paz, da parte de Deus, nosso Pai, e da do Senhor Jesus Cristo." },
{name:'5113',l:'51',c:'1',v:'3',texto:"Graças damos a Deus, Pai de nosso Senhor Jesus Cristo, orando sempre por vós," },
{name:'5114',l:'51',c:'1',v:'4',texto:"porquanto ouvimos da vossa fé em Cristo Jesus e da caridade que tendes para com todos os santos;" },
{name:'5115',l:'51',c:'1',v:'5',texto:"por causa da esperança que vos está reservada nos céus, da qual já, antes, ouvistes pela palavra da verdade do evangelho," },
{name:'5116',l:'51',c:'1',v:'6',texto:"que já chegou a vós, como também está em todo o mundo; e já vai frutificando, como também entre vós, desde o dia em que ouvistes e conhecestes a graça de Deus em verdade;" },
{name:'5117',l:'51',c:'1',v:'7',texto:"como aprendestes de Epafras, nosso amado conservo, que para vós é um fiel ministro de Cristo," },
{name:'5118',l:'51',c:'1',v:'8',texto:"o qual nos declarou também a vossa caridade no Espírito." },
{name:'5119',l:'51',c:'1',v:'9',texto:"Por esta razão, nós também, desde o dia em que o ouvimos, não cessamos de orar por vós e de pedir que sejais cheios do conhecimento da sua vontade, em toda a sabedoria e inteligência espiritual;" },
{name:'51110',l:'51',c:'1',v:'10',texto:"para que possais andar dignamente diante do Senhor, agradando-lhe em tudo, frutificando em toda boa obra e crescendo no conhecimento de Deus;" },
{name:'51111',l:'51',c:'1',v:'11',texto:"corroborados em toda a fortaleza, segundo a força da sua glória, em toda a paciência e longanimidade, com gozo," },
{name:'51112',l:'51',c:'1',v:'12',texto:"dando graças ao Pai, que nos fez idôneos para participar da herança dos santos na luz." },
{name:'51113',l:'51',c:'1',v:'13',texto:"Ele nos tirou da potestade das trevas e nos transportou para o Reino do Filho do seu amor," },
{name:'51114',l:'51',c:'1',v:'14',texto:"em quem temos a redenção pelo seu sangue, a saber, a remissão dos pecados;" },
{name:'51115',l:'51',c:'1',v:'15',texto:"o qual é imagem do Deus invisível, o primogênito de toda a criação;" },
{name:'51116',l:'51',c:'1',v:'16',texto:"porque nele foram criadas todas as coisas que há nos céus e na terra, visíveis e invisíveis, sejam tronos, sejam dominações, sejam principados, sejam potestades; tudo foi criado por ele e para ele." },
{name:'51117',l:'51',c:'1',v:'17',texto:"E ele é antes de todas as coisas, e todas as coisas subsistem por ele." },
{name:'51118',l:'51',c:'1',v:'18',texto:"E ele é a cabeça do corpo da igreja; é o princípio e o primogênito dentre os mortos, para que em tudo tenha a preeminência," },
{name:'51119',l:'51',c:'1',v:'19',texto:"porque foi do agrado do Pai que toda a plenitude nele habitasse" },
{name:'51120',l:'51',c:'1',v:'20',texto:"e que, havendo por ele feito a paz pelo sangue da sua cruz, por meio dele reconciliasse consigo mesmo todas as coisas, tanto as que estão na terra como as que estão nos céus." },
{name:'51121',l:'51',c:'1',v:'21',texto:"A vós também, que noutro tempo éreis estranhos e inimigos no entendimento pelas vossas obras más, agora, contudo, vos reconciliou" },
{name:'51122',l:'51',c:'1',v:'22',texto:"no corpo da sua carne, pela morte, para, perante ele, vos apresentar santos, e irrepreensíveis, e inculpáveis," },
{name:'51123',l:'51',c:'1',v:'23',texto:"se, na verdade, permanecerdes fundados e firmes na fé e não vos moverdes da esperança do evangelho que tendes ouvido, o qual foi pregado a toda criatura que há debaixo do céu, e do qual eu, Paulo, estou feito ministro." },
{name:'51124',l:'51',c:'1',v:'24',texto:"Regozijo-me, agora, no que padeço por vós e na minha carne cumpro o resto das aflições de Cristo, pelo seu corpo, que é a igreja;" },
{name:'51125',l:'51',c:'1',v:'25',texto:"da qual eu estou feito ministro segundo a dispensação de Deus, que me foi concedida para convosco, para cumprir a palavra de Deus:" },
{name:'51126',l:'51',c:'1',v:'26',texto:"o mistério que esteve oculto desde todos os séculos e em todas as gerações e que, agora, foi manifesto aos seus santos;" },
{name:'51127',l:'51',c:'1',v:'27',texto:"aos quais Deus quis fazer conhecer quais são as riquezas da glória deste mistério entre os gentios, que é Cristo em vós, esperança da glória;" },
{name:'51128',l:'51',c:'1',v:'28',texto:"a quem anunciamos, admoestando a todo homem e ensinando a todo homem em toda a sabedoria; para que apresentemos todo homem perfeito em Jesus Cristo;" },
{name:'51129',l:'51',c:'1',v:'29',texto:"e para isto também trabalho, combatendo segundo a sua eficácia, que opera em mim poderosamente." },
],
numVersiculos: 29,
},

c2: {
versiculos:[
{name:'5121',l:'51',c:'2',v:'1',texto:"Porque quero que saibais quão grande combate tenho por vós, e pelos que estão em Laodicéia, e por quantos não viram o meu rosto em carne;" },
{name:'5122',l:'51',c:'2',v:'2',texto:"para que os seus corações sejam consolados, e estejam unidos em caridade e enriquecidos da plenitude da inteligência, para conhecimento do mistério de Deus—Cristo," },
{name:'5123',l:'51',c:'2',v:'3',texto:"em quem estão escondidos todos os tesouros da sabedoria e da ciência." },
{name:'5124',l:'51',c:'2',v:'4',texto:"E digo isto para que ninguém vos engane com palavras persuasivas." },
{name:'5125',l:'51',c:'2',v:'5',texto:"Porque, ainda que esteja ausente quanto ao corpo, contudo, em espírito, estou convosco, regozijando-me e vendo a vossa ordem e a firmeza da vossa fé em Cristo." },
{name:'5126',l:'51',c:'2',v:'6',texto:"Como, pois, recebestes o Senhor Jesus Cristo, assim também andai nele," },
{name:'5127',l:'51',c:'2',v:'7',texto:"arraigados e edificados nele e confirmados na fé, assim como fostes ensinados, crescendo em ação de graças." },
{name:'5128',l:'51',c:'2',v:'8',texto:"Tende cuidado para que ninguém vos faça presa sua, por meio de filosofias e vãs sutilezas, segundo a tradição dos homens, segundo os rudimentos do mundo e não segundo Cristo;" },
{name:'5129',l:'51',c:'2',v:'9',texto:"porque nele habita corporalmente toda a plenitude da divindade." },
{name:'51210',l:'51',c:'2',v:'10',texto:"E estais perfeitos nele, que é a cabeça de todo principado e potestade;" },
{name:'51211',l:'51',c:'2',v:'11',texto:"no qual também estais circuncidados com a circuncisão não feita por mão no despojo do corpo da carne: a circuncisão de Cristo." },
{name:'51212',l:'51',c:'2',v:'12',texto:"Sepultados com ele no batismo, nele também ressuscitastes pela fé no poder de Deus, que o ressuscitou dos mortos." },
{name:'51213',l:'51',c:'2',v:'13',texto:"E, quando vós estáveis mortos nos pecados e na incircuncisão da vossa carne, vos vivificou juntamente com ele, perdoando-vos todas as ofensas," },
{name:'51214',l:'51',c:'2',v:'14',texto:"havendo riscado a cédula que era contra nós nas suas ordenanças, a qual de alguma maneira nos era contrária, e a tirou do meio de nós, cravando-a na cruz." },
{name:'51215',l:'51',c:'2',v:'15',texto:"E, despojando os principados e potestades, os expôs publicamente e deles triunfou em si mesmo." },
{name:'51216',l:'51',c:'2',v:'16',texto:"Portanto, ninguém vos julgue pelo comer, ou pelo beber, ou por causa dos dias de festa, ou da lua nova, ou dos sábados," },
{name:'51217',l:'51',c:'2',v:'17',texto:"que são sombras das coisas futuras, mas o corpo é de Cristo." },
{name:'51218',l:'51',c:'2',v:'18',texto:"Ninguém vos domine a seu bel-prazer, com pretexto de humildade e culto dos anjos, metendo-se em coisas que não viu; estando debalde inchado na sua carnal compreensão," },
{name:'51219',l:'51',c:'2',v:'19',texto:"e não ligado à cabeça, da qual todo o corpo, provido e organizado pelas juntas e ligaduras, vai crescendo em aumento de Deus." },
{name:'51220',l:'51',c:'2',v:'20',texto:"Se, pois, estais mortos com Cristo quanto aos rudimentos do mundo, por que vos carregam ainda de ordenanças, como se vivêsseis no mundo," },
{name:'51221',l:'51',c:'2',v:'21',texto:"tais como: não toques, não proves, não manuseies?" },
{name:'51222',l:'51',c:'2',v:'22',texto:"As quais coisas todas perecem pelo uso, segundo os preceitos e doutrinas dos homens;" },
{name:'51223',l:'51',c:'2',v:'23',texto:"as quais têm, na verdade, alguma aparência de sabedoria, em devoção voluntária, humildade e em disciplina do corpo, mas não são de valor algum, senão para a satisfação da carne." },
],
numVersiculos: 23,
},

c3: {
versiculos:[
{name:'5131',l:'51',c:'3',v:'1',texto:"Portanto, se já ressuscitastes com Cristo, buscai as coisas que são de cima, onde Cristo está assentado à destra de Deus." },
{name:'5132',l:'51',c:'3',v:'2',texto:"Pensai nas coisas que são de cima e não nas que são da terra;" },
{name:'5133',l:'51',c:'3',v:'3',texto:"porque já estais mortos, e a vossa vida está escondida com Cristo em Deus." },
{name:'5134',l:'51',c:'3',v:'4',texto:"Quando Cristo, que é a nossa vida, se manifestar, então, também vós vos manifestareis com ele em glória." },
{name:'5135',l:'51',c:'3',v:'5',texto:"Mortificai, pois, os vossos membros que estão sobre a terra: a prostituição, a impureza, o apetite desordenado, a vil concupiscência e a avareza, que é idolatria;" },
{name:'5136',l:'51',c:'3',v:'6',texto:"pelas quais coisas vem a ira de Deus sobre os filhos da desobediência;" },
{name:'5137',l:'51',c:'3',v:'7',texto:"nas quais também, em outro tempo, andastes, quando vivíeis nelas." },
{name:'5138',l:'51',c:'3',v:'8',texto:"Mas, agora, despojai-vos também de tudo: da ira, da cólera, da malícia, da maledicência, das palavras torpes da vossa boca." },
{name:'5139',l:'51',c:'3',v:'9',texto:"Não mintais uns aos outros, pois que já vos despistes do velho homem com os seus feitos" },
{name:'51310',l:'51',c:'3',v:'10',texto:"e vos vestistes do novo, que se renova para o conhecimento, segundo a imagem daquele que o criou;" },
{name:'51311',l:'51',c:'3',v:'11',texto:"onde não há grego nem judeu, circuncisão nem incircuncisão, bárbaro, cita, servo ou livre; mas Cristo é tudo em todos." },
{name:'51312',l:'51',c:'3',v:'12',texto:"Revesti-vos, pois, como eleitos de Deus, santos e amados, de entranhas de misericórdia, de benignidade, humildade, mansidão, longanimidade," },
{name:'51313',l:'51',c:'3',v:'13',texto:"suportando-vos uns aos outros e perdoando-vos uns aos outros, se algum tiver queixa contra outro; assim como Cristo vos perdoou, assim fazei vós também." },
{name:'51314',l:'51',c:'3',v:'14',texto:"E, sobre tudo isto, revesti-vos de caridade, que é o vínculo da perfeição." },
{name:'51315',l:'51',c:'3',v:'15',texto:"E a paz de Deus, para a qual também fostes chamados em um corpo, domine em vossos corações; e sede agradecidos." },
{name:'51316',l:'51',c:'3',v:'16',texto:"A palavra de Cristo habite em vós abundantemente, em toda a sabedoria, ensinando-vos e admoestando-vos uns aos outros, com salmos, hinos e cânticos espirituais; cantando ao Senhor com graça em vosso coração." },
{name:'51317',l:'51',c:'3',v:'17',texto:"E, quanto fizerdes por palavras ou por obras, fazei tudo em nome do Senhor Jesus, dando por ele graças a Deus Pai." },
{name:'51318',l:'51',c:'3',v:'18',texto:"Vós, mulheres, estai sujeitas a vosso próprio marido, como convém no Senhor." },
{name:'51319',l:'51',c:'3',v:'19',texto:"Vós, maridos, amai a vossa mulher e não vos irriteis contra ela." },
{name:'51320',l:'51',c:'3',v:'20',texto:"Vós, filhos, obedecei em tudo a vossos pais, porque isto é agradável ao Senhor." },
{name:'51321',l:'51',c:'3',v:'21',texto:"Vós, pais, não irriteis a vossos filhos, para que não percam o ânimo." },
{name:'51322',l:'51',c:'3',v:'22',texto:"Vós, servos, obedecei em tudo a vosso senhor segundo a carne, não servindo só na aparência, como para agradar aos homens, mas em simplicidade de coração, temendo a Deus." },
{name:'51323',l:'51',c:'3',v:'23',texto:"E, tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor e não aos homens," },
{name:'51324',l:'51',c:'3',v:'24',texto:"sabendo que recebereis do Senhor o galardão da herança, porque a Cristo, o Senhor, servis." },
{name:'51325',l:'51',c:'3',v:'25',texto:"Mas quem fizer agravo receberá o agravo que fizer; pois não há acepção de pessoas." },
],
numVersiculos: 25,
},

c4: {
versiculos:[
{name:'5141',l:'51',c:'4',v:'1',texto:"Vós, senhores, fazei o que for de justiça e eqüidade a vossos servos, sabendo que também tendes um Senhor nos céus." },
{name:'5142',l:'51',c:'4',v:'2',texto:"Perseverai em oração, velando nela com ação de graças;" },
{name:'5143',l:'51',c:'4',v:'3',texto:"orando também juntamente por nós, para que Deus nos abra a porta da palavra, a fim de falarmos do mistério de Cristo, pelo qual estou também preso;" },
{name:'5144',l:'51',c:'4',v:'4',texto:"para que o manifeste, como me convém falar." },
{name:'5145',l:'51',c:'4',v:'5',texto:"Andai com sabedoria para com os que estão de fora, remindo o tempo." },
{name:'5146',l:'51',c:'4',v:'6',texto:"A vossa palavra seja sempre agradável, temperada com sal, para que saibais como vos convém responder a cada um." },
{name:'5147',l:'51',c:'4',v:'7',texto:"Tíquico, irmão amado, e fiel ministro, e conservo no Senhor, vos fará saber o meu estado;" },
{name:'5148',l:'51',c:'4',v:'8',texto:"o qual vos enviei para o mesmo fim, para que saiba do vosso estado e console o vosso coração," },
{name:'5149',l:'51',c:'4',v:'9',texto:"juntamente com Onésimo, amado e fiel irmão, que é dos vossos; eles vos farão saber tudo o que por aqui se passa." },
{name:'51410',l:'51',c:'4',v:'10',texto:"Aristarco, que está preso comigo, vos saúda, e Marcos, o sobrinho de Barnabé, acerca do qual já recebestes mandamentos; se ele for ter convosco, recebei-o;" },
{name:'51411',l:'51',c:'4',v:'11',texto:"e Jesus, chamado Justo, os quais são da circuncisão; são estes unicamente os meus cooperadores no Reino de Deus e para mim têm sido consolação." },
{name:'51412',l:'51',c:'4',v:'12',texto:"Saúda-vos Epafras, que é dos vossos, servo de Cristo, combatendo sempre por vós em orações, para que vos conserveis firmes, perfeitos e consumados em toda a vontade de Deus." },
{name:'51413',l:'51',c:'4',v:'13',texto:"Pois eu lhe dou testemunho de que tem grande zelo por vós, e pelos que estão em Laodicéia, e pelos que estão em Hierápolis." },
{name:'51414',l:'51',c:'4',v:'14',texto:"Saúda-vos Lucas, o médico amado, e Demas." },
{name:'51415',l:'51',c:'4',v:'15',texto:"Saudai aos irmãos que estão em Laodicéia, e a Ninfa, e à igreja que está em sua casa." },
{name:'51416',l:'51',c:'4',v:'16',texto:"E, quando esta epístola tiver sido lida entre vós, fazei que também o seja na igreja dos laodicenses; e a que veio de Laodicéia, lede-a vós também." },
{name:'51417',l:'51',c:'4',v:'17',texto:"E dizei a Arquipo: Atenta para o ministério que recebeste no Senhor, para que o cumpras." },
{name:'51418',l:'51',c:'4',v:'18',texto:"Saudação de minha mão, de Paulo. Lembrai-vos das minhas prisões. A graça seja convosco. Amém!" },
],
numVersiculos: 18,
},


};
