BibliaJFA.tesalonicenses1 = {
	libro: "1 Tessalonicenses",
	numCapitulos: 5,

c1: {
versiculos:[
{name:'5211',l:'52',c:'1',v:'1',texto:"Paulo, e Silvano, e Timóteo, à igreja dos tessalonicenses, em Deus, o Pai, e no Senhor Jesus Cristo: graça e paz tenhais de Deus, nosso Pai, e do Senhor Jesus Cristo." },
{name:'5212',l:'52',c:'1',v:'2',texto:"Sempre damos graças a Deus por vós todos, fazendo menção de vós em nossas orações," },
{name:'5213',l:'52',c:'1',v:'3',texto:"lembrando-nos, sem cessar, da obra da vossa fé, do trabalho da caridade e da paciência da esperança em nosso Senhor Jesus Cristo, diante de nosso Deus e Pai," },
{name:'5214',l:'52',c:'1',v:'4',texto:"sabendo, amados irmãos, que a vossa eleição é de Deus;" },
{name:'5215',l:'52',c:'1',v:'5',texto:"porque o nosso evangelho não foi a vós somente em palavras, mas também em poder, e no Espírito Santo, e em muita certeza, como bem sabeis quais fomos entre vós, por amor de vós." },
{name:'5216',l:'52',c:'1',v:'6',texto:"E vós fostes feitos nossos imitadores e do Senhor, recebendo a palavra em muita tribulação, com gozo do Espírito Santo," },
{name:'5217',l:'52',c:'1',v:'7',texto:"de maneira que fostes exemplo para todos os fiéis na Macedônia e Acaia." },
{name:'5218',l:'52',c:'1',v:'8',texto:"Porque por vós soou a palavra do Senhor, não somente na Macedônia e Acaia, mas também em todos os lugares a vossa fé para com Deus se espalhou, de tal maneira que já dela não temos necessidade de falar coisa alguma;" },
{name:'5219',l:'52',c:'1',v:'9',texto:"porque eles mesmos anunciam de nós qual a entrada que tivemos para convosco, e como dos ídolos vos convertestes a Deus, para servir ao Deus vivo e verdadeiro" },
{name:'52110',l:'52',c:'1',v:'10',texto:"e esperar dos céus a seu Filho, a quem ressuscitou dos mortos, a saber, Jesus, que nos livra da ira futura." },
],
numVersiculos: 10,
},

c2: {
versiculos:[
{name:'5221',l:'52',c:'2',v:'1',texto:"Porque vós mesmos, irmãos, bem sabeis que a nossa entrada para convosco não foi vã;" },
{name:'5222',l:'52',c:'2',v:'2',texto:"mas, havendo primeiro padecido e sido agravados em Filipos, como sabeis, tornamo-nos ousados em nosso Deus, para vos falar o evangelho de Deus com grande combate." },
{name:'5223',l:'52',c:'2',v:'3',texto:"Porque a nossa exortação não foi com engano, nem com imundícia, nem com fraudulência;" },
{name:'5224',l:'52',c:'2',v:'4',texto:"mas, como fomos aprovados de Deus para que o evangelho nos fosse confiado, assim falamos, não como para agradar aos homens, mas a Deus, que prova o nosso coração." },
{name:'5225',l:'52',c:'2',v:'5',texto:"Porque, como bem sabeis, nunca usamos de palavras lisonjeiras, nem houve um pretexto de avareza; Deus é testemunha." },
{name:'5226',l:'52',c:'2',v:'6',texto:"E não buscamos glória dos homens, nem de vós, nem de outros, ainda que podíamos, como apóstolos de Cristo, ser-vos pesados;" },
{name:'5227',l:'52',c:'2',v:'7',texto:"antes, fomos brandos entre vós, como a ama que cria seus filhos." },
{name:'5228',l:'52',c:'2',v:'8',texto:"Assim nós, sendo-vos tão afeiçoados, de boa vontade quiséramos comunicar-vos, não somente o evangelho de Deus, mas ainda a nossa própria alma; porquanto nos éreis muito queridos." },
{name:'5229',l:'52',c:'2',v:'9',texto:"Porque bem vos lembrais, irmãos, do nosso trabalho e fadiga; pois, trabalhando noite e dia, para não sermos pesados a nenhum de vós, vos pregamos o evangelho de Deus." },
{name:'52210',l:'52',c:'2',v:'10',texto:"Vós e Deus sois testemunhas de quão santa, justa e irrepreensivelmente nos houvemos para convosco, os que crestes." },
{name:'52211',l:'52',c:'2',v:'11',texto:"Assim como bem sabeis de que modo vos exortávamos e consolávamos, a cada um de vós, como o pai a seus filhos," },
{name:'52212',l:'52',c:'2',v:'12',texto:"para que vos conduzísseis dignamente para com Deus, que vos chama para o seu reino e glória." },
{name:'52213',l:'52',c:'2',v:'13',texto:"Pelo que também damos, sem cessar, graças a Deus, pois, havendo recebido de nós a palavra da pregação de Deus, a recebestes, não como palavra de homens, mas ( segundo é, na verdade ) como palavra de Deus, a qual também opera em vós, os que crestes." },
{name:'52214',l:'52',c:'2',v:'14',texto:"Porque vós, irmãos, haveis sido feitos imitadores das igrejas de Deus que, na Judéia, estão em Jesus Cristo; porquanto também padecestes de vossos próprios concidadãos o mesmo que os judeus lhes fizeram a eles," },
{name:'52215',l:'52',c:'2',v:'15',texto:"os quais também mataram o Senhor Jesus e os seus próprios profetas, e nos têm perseguido, e não agradam a Deus, e são contrários a todos os homens." },
{name:'52216',l:'52',c:'2',v:'16',texto:"E nos impedem de pregar aos gentios as palavras da salvação, a fim de encherem sempre a medida de seus pecados; mas a ira de Deus caiu sobre eles até ao fim." },
{name:'52217',l:'52',c:'2',v:'17',texto:"Nós, porém, irmãos, sendo privados de vós por um momento de tempo, de vista, mas não do coração, tanto mais procuramos com grande desejo ver o vosso rosto." },
{name:'52218',l:'52',c:'2',v:'18',texto:"Pelo que bem quisemos, uma e outra vez, ir ter convosco, pelo menos eu, Paulo, mas Satanás no-lo impediu." },
{name:'52219',l:'52',c:'2',v:'19',texto:"Porque qual é a nossa esperança, ou gozo, ou coroa de glória? Porventura, não o sois vós também diante de nosso Senhor Jesus Cristo em sua vinda?" },
{name:'52220',l:'52',c:'2',v:'20',texto:"Na verdade, vós sois a nossa glória e gozo." },
],
numVersiculos: 20,
},

c3: {
versiculos:[
{name:'5231',l:'52',c:'3',v:'1',texto:"Pelo que, não podendo esperar mais, de boa mente quisemos deixar-nos ficar sós em Atenas;" },
{name:'5232',l:'52',c:'3',v:'2',texto:"e enviamos Timóteo, nosso irmão, e ministro de Deus, e nosso cooperador no evangelho de Cristo, para vos confortar e vos exortar acerca da vossa fé;" },
{name:'5233',l:'52',c:'3',v:'3',texto:"para que ninguém se comova por estas tribulações; porque vós mesmos sabeis que para isto fomos ordenados;" },
{name:'5234',l:'52',c:'3',v:'4',texto:"pois, estando ainda convosco, vos predizíamos que havíamos de ser afligidos, como sucedeu, e vós o sabeis." },
{name:'5235',l:'52',c:'3',v:'5',texto:"Portanto, não podendo eu também esperar mais, mandei-o saber da vossa fé, temendo que o tentador vos tentasse, e o nosso trabalho viesse a ser inútil." },
{name:'5236',l:'52',c:'3',v:'6',texto:"Vindo, porém, agora, Timóteo de vós para nós e trazendo-nos boas novas da vossa fé e caridade e de como sempre tendes boa lembrança de nós, desejando muito ver-nos, como nós também a vós," },
{name:'5237',l:'52',c:'3',v:'7',texto:"por esta razão, irmãos, ficamos consolados acerca de vós, em toda a nossa aflição e necessidade, pela vossa fé," },
{name:'5238',l:'52',c:'3',v:'8',texto:"porque, agora, vivemos, se estais firmes no Senhor." },
{name:'5239',l:'52',c:'3',v:'9',texto:"Porque que ação de graças poderemos dar a Deus por vós, por todo o gozo com que nos regozijamos por vossa causa diante do nosso Deus," },
{name:'52310',l:'52',c:'3',v:'10',texto:"orando abundantemente dia e noite, para que possamos ver o vosso rosto e supramos o que falta à vossa fé?" },
{name:'52311',l:'52',c:'3',v:'11',texto:"Ora, o mesmo nosso Deus e Pai e nosso Senhor Jesus Cristo encaminhem a nossa viagem para vós." },
{name:'52312',l:'52',c:'3',v:'12',texto:"E o Senhor vos aumente e faça crescer em caridade uns para com os outros e para com todos, como também nós para convosco;" },
{name:'52313',l:'52',c:'3',v:'13',texto:"para confortar o vosso coração, para que sejais irrepreensíveis em santidade diante de nosso Deus e Pai, na vinda de nosso Senhor Jesus Cristo, com todos os seus santos." },
],
numVersiculos: 13,
},

c4: {
versiculos:[
{name:'5241',l:'52',c:'4',v:'1',texto:"Finalmente, irmãos, vos rogamos e exortamos no Senhor Jesus que, assim como recebestes de nós, de que maneira convém andar e agradar a Deus, assim andai, para que continueis a progredir cada vez mais;" },
{name:'5242',l:'52',c:'4',v:'2',texto:"porque vós bem sabeis que mandamentos vos temos dado pelo Senhor Jesus." },
{name:'5243',l:'52',c:'4',v:'3',texto:"Porque esta é a vontade de Deus, a vossa santificação: que vos abstenhais da prostituição," },
{name:'5244',l:'52',c:'4',v:'4',texto:"que cada um de vós saiba possuir o seu vaso em santificação e honra," },
{name:'5245',l:'52',c:'4',v:'5',texto:"não na paixão de concupiscência, como os gentios, que não conhecem a Deus." },
{name:'5246',l:'52',c:'4',v:'6',texto:"Ninguém oprima ou engane a seu irmão em negócio algum, porque o Senhor é vingador de todas estas coisas, como também, antes, vo-lo dissemos e testificamos." },
{name:'5247',l:'52',c:'4',v:'7',texto:"Porque não nos chamou Deus para a imundícia, mas para a santificação." },
{name:'5248',l:'52',c:'4',v:'8',texto:"Portanto, quem despreza isto não despreza ao homem, mas, sim, a Deus, que nos deu também o seu Espírito Santo." },
{name:'5249',l:'52',c:'4',v:'9',texto:"Quanto, porém, à caridade fraternal, não necessitais de que vos escreva, visto que vós mesmos estais instruídos por Deus que vos ameis uns aos outros;" },
{name:'52410',l:'52',c:'4',v:'10',texto:"porque também já assim o fazeis para com todos os irmãos que estão por toda a Macedônia. Exortamo-vos, porém, a que ainda nisto continueis a progredir cada vez mais," },
{name:'52411',l:'52',c:'4',v:'11',texto:"e procureis viver quietos, e tratar dos vossos próprios negócios, e trabalhar com vossas próprias mãos, como já vo-lo temos mandado;" },
{name:'52412',l:'52',c:'4',v:'12',texto:"para que andeis honestamente para com os que estão de fora e não necessiteis de coisa alguma." },
{name:'52413',l:'52',c:'4',v:'13',texto:"Não quero, porém, irmãos, que sejais ignorantes acerca dos que já dormem, para que não vos entristeçais, como os demais, que não têm esperança." },
{name:'52414',l:'52',c:'4',v:'14',texto:"Porque, se cremos que Jesus morreu e ressuscitou, assim também aos que em Jesus dormem Deus os tornará a trazer com ele." },
{name:'52415',l:'52',c:'4',v:'15',texto:"Dizemo-vos, pois, isto pela palavra do Senhor: que nós, os que ficarmos vivos para a vinda do Senhor, não precederemos os que dormem." },
{name:'52416',l:'52',c:'4',v:'16',texto:"Porque o mesmo Senhor descerá do céu com alarido, e com voz de arcanjo, e com a trombeta de Deus; e os que morreram em Cristo ressuscitarão primeiro;" },
{name:'52417',l:'52',c:'4',v:'17',texto:"depois, nós, os que ficarmos vivos, seremos arrebatados juntamente com eles nas nuvens, a encontrar o Senhor nos ares, e assim estaremos sempre com o Senhor." },
{name:'52418',l:'52',c:'4',v:'18',texto:"Portanto, consolai-vos uns aos outros com estas palavras." },
],
numVersiculos: 18,
},

c5: {
versiculos:[
{name:'5251',l:'52',c:'5',v:'1',texto:"Mas, irmãos, acerca dos tempos e das estações, não necessitais de que se vos escreva;" },
{name:'5252',l:'52',c:'5',v:'2',texto:"porque vós mesmos sabeis muito bem que o Dia do Senhor virá como o ladrão de noite." },
{name:'5253',l:'52',c:'5',v:'3',texto:"Pois que, quando disserem: Há paz e segurança, então, lhes sobrevirá repentina destruição, como as dores de parto àquela que está grávida; e de modo nenhum escaparão." },
{name:'5254',l:'52',c:'5',v:'4',texto:"Mas vós, irmãos, já não estais em trevas, para que aquele Dia vos surpreenda como um ladrão;" },
{name:'5255',l:'52',c:'5',v:'5',texto:"porque todos vós sois filhos da luz e filhos do dia; nós não somos da noite nem das trevas." },
{name:'5256',l:'52',c:'5',v:'6',texto:"Não durmamos, pois, como os demais, mas vigiemos e sejamos sóbrios." },
{name:'5257',l:'52',c:'5',v:'7',texto:"Porque os que dormem dormem de noite, e os que se embebedam embebedam-se de noite." },
{name:'5258',l:'52',c:'5',v:'8',texto:"Mas nós, que somos do dia, sejamos sóbrios, vestindo-nos da couraça da fé e da caridade e tendo por capacete a esperança da salvação." },
{name:'5259',l:'52',c:'5',v:'9',texto:"Porque Deus não nos destinou para a ira, mas para a aquisição da salvação, por nosso Senhor Jesus Cristo," },
{name:'52510',l:'52',c:'5',v:'10',texto:"que morreu por nós, para que, quer vigiemos, quer durmamos, vivamos juntamente com ele." },
{name:'52511',l:'52',c:'5',v:'11',texto:"Pelo que exortai-vos uns aos outros e edificai-vos uns aos outros, como também o fazeis." },
{name:'52512',l:'52',c:'5',v:'12',texto:"E rogamo-vos, irmãos, que reconheçais os que trabalham entre vós, e que presidem sobre vós no Senhor, e vos admoestam;" },
{name:'52513',l:'52',c:'5',v:'13',texto:"e que os tenhais em grande estima e amor, por causa da sua obra. Tende paz entre vós." },
{name:'52514',l:'52',c:'5',v:'14',texto:"Rogamo-vos também, irmãos, que admoesteis os desordeiros, consoleis os de pouco ânimo, sustenteis os fracos e sejais pacientes para com todos." },
{name:'52515',l:'52',c:'5',v:'15',texto:"Vede que ninguém dê a outrem mal por mal, mas segui, sempre, o bem, tanto uns para com os outros como para com todos." },
{name:'52516',l:'52',c:'5',v:'16',texto:"Regozijai-vos sempre." },
{name:'52517',l:'52',c:'5',v:'17',texto:"Orai sem cessar." },
{name:'52518',l:'52',c:'5',v:'18',texto:"Em tudo dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco." },
{name:'52519',l:'52',c:'5',v:'19',texto:"Não extingais o Espírito." },
{name:'52520',l:'52',c:'5',v:'20',texto:"Não desprezeis as profecias." },
{name:'52521',l:'52',c:'5',v:'21',texto:"Examinai tudo. Retende o bem." },
{name:'52522',l:'52',c:'5',v:'22',texto:"Abstende-vos de toda aparência do mal." },
{name:'52523',l:'52',c:'5',v:'23',texto:"E o mesmo Deus de paz vos santifique em tudo; e todo o vosso espírito, e alma, e corpo sejam plenamente conservados irrepreensíveis para a vinda de nosso Senhor Jesus Cristo." },
{name:'52524',l:'52',c:'5',v:'24',texto:"Fiel é o que vos chama, o qual também o fará." },
{name:'52525',l:'52',c:'5',v:'25',texto:"Irmãos, orai por nós." },
{name:'52526',l:'52',c:'5',v:'26',texto:"Saudai a todos os irmãos com ósculo santo." },
{name:'52527',l:'52',c:'5',v:'27',texto:"Pelo Senhor vos conjuro que esta epístola seja lida a todos os santos irmãos." },
{name:'52528',l:'52',c:'5',v:'28',texto:"A graça de nosso Senhor Jesus Cristo seja convosco. Amém!" },
],
numVersiculos: 28,
},
	

};
