BibliaJFA.timoteo1 = {
	libro: "1 Timóteo",
	numCapitulos: 6,

c1: {
versiculos:[
{name:'5411',l:'54',c:'1',v:'1',texto:"Paulo, apóstolo de Jesus Cristo, segundo o mandado de Deus, nosso Salvador, e do Senhor Jesus Cristo, esperança nossa," },
{name:'5412',l:'54',c:'1',v:'2',texto:"a Timóteo, meu verdadeiro filho na fé: graça, misericórdia e paz, da parte de Deus, nosso Pai, e da de Cristo Jesus, nosso Senhor." },
{name:'5413',l:'54',c:'1',v:'3',texto:"Como te roguei, quando parti para a Macedônia, que ficasses em Éfeso, para advertires a alguns que não ensinem outra doutrina," },
{name:'5414',l:'54',c:'1',v:'4',texto:"nem se dêem a fábulas ou a genealogias intermináveis, que mais produzem questões do que edificação de Deus, que consiste na fé; assim o faço agora." },
{name:'5415',l:'54',c:'1',v:'5',texto:"Ora, o fim do mandamento é a caridade de um coração puro, e de uma boa consciência, e de uma fé não fingida." },
{name:'5416',l:'54',c:'1',v:'6',texto:"Do que desviando-se alguns, se entregaram a vãs contendas," },
{name:'5417',l:'54',c:'1',v:'7',texto:"querendo ser doutores da lei e não entendendo nem o que dizem nem o que afirmam." },
{name:'5418',l:'54',c:'1',v:'8',texto:"Sabemos, porém, que a lei é boa, se alguém dela usa legitimamente," },
{name:'5419',l:'54',c:'1',v:'9',texto:"sabendo isto: que a lei não é feita para o justo, mas para os injustos e obstinados, para os ímpios e pecadores, para os profanos e irreligiosos, para os parricidas e matricidas, para os homicidas," },
{name:'54110',l:'54',c:'1',v:'10',texto:"para os fornicadores, para os sodomitas, para os roubadores de homens, para os mentirosos, para os perjuros e para o que for contrário à sã doutrina," },
{name:'54111',l:'54',c:'1',v:'11',texto:"conforme o evangelho da glória do Deus bem-aventurado, que me foi confiado." },
{name:'54112',l:'54',c:'1',v:'12',texto:"E dou graças ao que me tem confortado, a Cristo Jesus, Senhor nosso, porque me teve por fiel, pondo-me no ministério," },
{name:'54113',l:'54',c:'1',v:'13',texto:"a mim, que, dantes, fui blasfemo, e perseguidor, e opressor; mas alcancei misericórdia, porque o fiz ignorantemente, na incredulidade." },
{name:'54114',l:'54',c:'1',v:'14',texto:"E a graça de nosso Senhor superabundou com a fé e o amor que há em Jesus Cristo." },
{name:'54115',l:'54',c:'1',v:'15',texto:"Esta é uma palavra fiel e digna de toda aceitação: que Cristo Jesus veio ao mundo, para salvar os pecadores, dos quais eu sou o principal." },
{name:'54116',l:'54',c:'1',v:'16',texto:"Mas, por isso, alcancei misericórdia, para que em mim, que sou o principal, Jesus Cristo mostrasse toda a sua longanimidade, para exemplo dos que haviam de crer nele para a vida eterna." },
{name:'54117',l:'54',c:'1',v:'17',texto:"Ora, ao Rei dos séculos, imortal, invisível, ao único Deus seja honra e glória para todo o sempre. Amém!" },
{name:'54118',l:'54',c:'1',v:'18',texto:"Este mandamento te dou, meu filho Timóteo, que, segundo as profecias que houve acerca de ti, milites por elas boa milícia," },
{name:'54119',l:'54',c:'1',v:'19',texto:"conservando a fé e a boa consciência, rejeitando a qual alguns fizeram naufrágio na fé." },
{name:'54120',l:'54',c:'1',v:'20',texto:"E entre esses foram Himeneu e Alexandre, os quais entreguei a Satanás, para que aprendam a não blasfemar." },
],
numVersiculos: 20,
},

c2: {
versiculos:[
{name:'5421',l:'54',c:'2',v:'1',texto:"Admoesto-te, pois, antes de tudo, que se façam deprecações, orações, intercessões e ações de graças por todos os homens," },
{name:'5422',l:'54',c:'2',v:'2',texto:"pelos reis e por todos os que estão em eminência, para que tenhamos uma vida quieta e sossegada, em toda a piedade e honestidade." },
{name:'5423',l:'54',c:'2',v:'3',texto:"Porque isto é bom e agradável diante de Deus, nosso Salvador," },
{name:'5424',l:'54',c:'2',v:'4',texto:"que quer que todos os homens se salvem e venham ao conhecimento da verdade." },
{name:'5425',l:'54',c:'2',v:'5',texto:"Porque há um só Deus e um só mediador entre Deus e os homens, Jesus Cristo, homem," },
{name:'5426',l:'54',c:'2',v:'6',texto:"o qual se deu a si mesmo em preço de redenção por todos, para servir de testemunho a seu tempo." },
{name:'5427',l:'54',c:'2',v:'7',texto:"Para o que ( digo a verdade em Cristo, não minto ) fui constituído pregador, e apóstolo, e doutor dos gentios, na fé e na verdade." },
{name:'5428',l:'54',c:'2',v:'8',texto:"Quero, pois, que os homens orem em todo o lugar, levantando mãos santas, sem ira nem contenda." },
{name:'5429',l:'54',c:'2',v:'9',texto:"Que do mesmo modo as mulheres se ataviem em traje honesto, com pudor e modéstia, não com tranças, ou com ouro, ou pérolas, ou vestidos preciosos," },
{name:'54210',l:'54',c:'2',v:'10',texto:"mas ( como convém a mulheres que fazem profissão de servir a Deus ) com boas obras." },
{name:'54211',l:'54',c:'2',v:'11',texto:"A mulher aprenda em silêncio, com toda a sujeição." },
{name:'54212',l:'54',c:'2',v:'12',texto:"Não permito, porém, que a mulher ensine, nem use de autoridade sobre o marido, mas que esteja em silêncio." },
{name:'54213',l:'54',c:'2',v:'13',texto:"Porque primeiro foi formado Adão, depois Eva." },
{name:'54214',l:'54',c:'2',v:'14',texto:"E Adão não foi enganado, mas a mulher, sendo enganada, caiu em transgressão." },
{name:'54215',l:'54',c:'2',v:'15',texto:"Salvar-se-á, porém, dando à luz filhos, se permanecer com modéstia na fé, na caridade e na santificação." },
],
numVersiculos: 15,
},

c3: {
versiculos:[
{name:'5431',l:'54',c:'3',v:'1',texto:"Esta é uma palavra fiel: Se alguém deseja o episcopado, excelente obra deseja." },
{name:'5432',l:'54',c:'3',v:'2',texto:"Convém, pois, que o bispo seja irrepreensível, marido de uma mulher, vigilante, sóbrio, honesto, hospitaleiro, apto para ensinar;" },
{name:'5433',l:'54',c:'3',v:'3',texto:"não dado ao vinho, não espancador, não cobiçoso de torpe ganância, mas moderado, não contencioso, não avarento;" },
{name:'5434',l:'54',c:'3',v:'4',texto:"que governe bem a sua própria casa, tendo seus filhos em sujeição, com toda a modéstia" },
{name:'5435',l:'54',c:'3',v:'5',texto:"( porque, se alguém não sabe governar a sua própria casa, terá cuidado da igreja de Deus? );" },
{name:'5436',l:'54',c:'3',v:'6',texto:"não neófito, para que, ensoberbecendo-se, não caia na condenação do diabo." },
{name:'5437',l:'54',c:'3',v:'7',texto:"Convém, também, que tenha bom testemunho dos que estão de fora, para que não caia em afronta e no laço do diabo." },
{name:'5438',l:'54',c:'3',v:'8',texto:"Da mesma sorte os diáconos sejam honestos, não de língua dobre, não dados a muito vinho, não cobiçosos de torpe ganância," },
{name:'5439',l:'54',c:'3',v:'9',texto:"guardando o mistério da fé em uma pura consciência." },
{name:'54310',l:'54',c:'3',v:'10',texto:"E também estes sejam primeiro provados, depois sirvam, se forem irrepreensíveis." },
{name:'54311',l:'54',c:'3',v:'11',texto:"Da mesma sorte as mulheres sejam honestas, não maldizentes, sóbrias e fiéis em tudo." },
{name:'54312',l:'54',c:'3',v:'12',texto:"Os diáconos sejam maridos de uma mulher e governem bem seus filhos e suas próprias casas." },
{name:'54313',l:'54',c:'3',v:'13',texto:"Porque os que servirem bem como diáconos adquirirão para si uma boa posição e muita confiança na fé que há em Cristo Jesus." },
{name:'54314',l:'54',c:'3',v:'14',texto:"Escrevo-te estas coisas, esperando ir ver-te bem depressa," },
{name:'54315',l:'54',c:'3',v:'15',texto:"mas, se tardar, para que saibas como convém andar na casa de Deus, que é a igreja do Deus vivo, a coluna e firmeza da verdade." },
{name:'54316',l:'54',c:'3',v:'16',texto:"E, sem dúvida alguma, grande é o mistério da piedade: Aquele que se manifestou em carne foi justificado em espírito, visto dos anjos, pregado aos gentios, crido no mundo e recebido acima, na glória." },
],
numVersiculos: 16,
},

c4: {
versiculos:[
{name:'5441',l:'54',c:'4',v:'1',texto:"Mas o Espírito expressamente diz que, nos últimos tempos, apostatarão alguns da fé, dando ouvidos a espíritos enganadores e a doutrinas de demônios," },
{name:'5442',l:'54',c:'4',v:'2',texto:"pela hipocrisia de homens que falam mentiras, tendo cauterizada a sua própria consciência," },
{name:'5443',l:'54',c:'4',v:'3',texto:"proibindo o casamento e ordenando a abstinência dos manjares que Deus criou para os fiéis e para os que conhecem a verdade, a fim de usarem deles com ações de graças;" },
{name:'5444',l:'54',c:'4',v:'4',texto:"porque toda criatura de Deus é boa, e não há nada que rejeitar, sendo recebido com ações de graças," },
{name:'5445',l:'54',c:'4',v:'5',texto:"porque, pela palavra de Deus e pela oração, é santificada." },
{name:'5446',l:'54',c:'4',v:'6',texto:"Propondo estas coisas aos irmãos, serás bom ministro de Jesus Cristo, criado com as palavras da fé e da boa doutrina que tens seguido." },
{name:'5447',l:'54',c:'4',v:'7',texto:"Mas rejeita as fábulas profanas e de velhas e exercita-te a ti mesmo em piedade." },
{name:'5448',l:'54',c:'4',v:'8',texto:"Porque o exercício corporal para pouco aproveita, mas a piedade para tudo é proveitosa, tendo a promessa da vida presente e da que há de vir." },
{name:'5449',l:'54',c:'4',v:'9',texto:"Esta palavra é fiel e digna de toda a aceitação." },
{name:'54410',l:'54',c:'4',v:'10',texto:"Porque para isto trabalhamos e lutamos, pois esperamos no Deus vivo, que é o Salvador de todos os homens, principalmente dos fiéis." },
{name:'54411',l:'54',c:'4',v:'11',texto:"Manda estas coisas e ensina-as." },
{name:'54412',l:'54',c:'4',v:'12',texto:"Ninguém despreze a tua mocidade; mas sê o exemplo dos fiéis, na palavra, no trato, na caridade, no espírito, na fé, na pureza." },
{name:'54413',l:'54',c:'4',v:'13',texto:"Persiste em ler, exortar e ensinar, até que eu vá." },
{name:'54414',l:'54',c:'4',v:'14',texto:"Não desprezes o dom que há em ti, o qual te foi dado por profecia, com a imposição das mãos do presbitério." },
{name:'54415',l:'54',c:'4',v:'15',texto:"Medita estas coisas, ocupa-te nelas, para que o teu aproveitamento seja manifesto a todos." },
{name:'54416',l:'54',c:'4',v:'16',texto:"Tem cuidado de ti mesmo e da doutrina; persevera nestas coisas; porque, fazendo isto, te salvarás, tanto a ti mesmo como aos que te ouvem." },
],
numVersiculos: 16,
},

c5: {
versiculos:[
{name:'5451',l:'54',c:'5',v:'1',texto:"Não repreendas asperamente os anciãos, mas admoesta-os como a pais; aos jovens, como a irmãos;" },
{name:'5452',l:'54',c:'5',v:'2',texto:"às mulheres idosas, como a mães, às moças, como a irmãs, em toda a pureza." },
{name:'5453',l:'54',c:'5',v:'3',texto:"Honra as viúvas que verdadeiramente são viúvas." },
{name:'5454',l:'54',c:'5',v:'4',texto:"Mas, se alguma viúva tiver filhos ou netos, aprendam primeiro a exercer piedade para com a sua própria família e a recompensar seus pais; porque isto é bom e agradável diante de Deus." },
{name:'5455',l:'54',c:'5',v:'5',texto:"Ora, a que é verdadeiramente viúva e desamparada espera em Deus e persevera de noite e de dia em rogos e orações;" },
{name:'5456',l:'54',c:'5',v:'6',texto:"mas a que vive em deleites, vivendo, está morta." },
{name:'5457',l:'54',c:'5',v:'7',texto:"Manda, pois, estas coisas, para que elas sejam irrepreensíveis." },
{name:'5458',l:'54',c:'5',v:'8',texto:"Mas, se alguém não tem cuidado dos seus e principalmente dos da sua família, negou a fé e é pior do que o infiel." },
{name:'5459',l:'54',c:'5',v:'9',texto:"Nunca seja inscrita viúva com menos de sessenta anos, e só a que tenha sido mulher de um só marido;" },
{name:'54510',l:'54',c:'5',v:'10',texto:"tendo testemunho de boas obras, se criou os filhos, se exercitou hospitalidade, se lavou os pés aos santos, se socorreu os aflitos, se praticou toda boa obra." },
{name:'54511',l:'54',c:'5',v:'11',texto:"Mas não admitas as viúvas mais novas, porque, quando se tornam levianas contra Cristo, querem casar-se;" },
{name:'54512',l:'54',c:'5',v:'12',texto:"tendo já a sua condenação por haverem aniquilado a primeira fé." },
{name:'54513',l:'54',c:'5',v:'13',texto:"E, além disto, aprendem também a andar ociosas de casa em casa; e não só ociosas, mas também paroleiras e curiosas, falando o que não convém." },
{name:'54514',l:'54',c:'5',v:'14',texto:"Quero, pois, que as que são moças se casem, gerem filhos, governem a casa e não dêem ocasião ao adversário de maldizer." },
{name:'54515',l:'54',c:'5',v:'15',texto:"Porque já algumas se desviaram, indo após Satanás." },
{name:'54516',l:'54',c:'5',v:'16',texto:"Se algum crente ou alguma crente tem viúvas, socorra-as, e não se sobrecarregue a igreja, para que se possam sustentar as que deveras são viúvas." },
{name:'54517',l:'54',c:'5',v:'17',texto:"Os presbíteros que governam bem sejam estimados por dignos de duplicada honra, principalmente os que trabalham na palavra e na doutrina." },
{name:'54518',l:'54',c:'5',v:'18',texto:"Porque diz a Escritura: Não ligarás a boca ao boi que debulha. E: Digno é o obreiro do seu salário." },
{name:'54519',l:'54',c:'5',v:'19',texto:"Não aceites acusação contra presbítero, senão com duas ou três testemunhas." },
{name:'54520',l:'54',c:'5',v:'20',texto:"Aos que pecarem, repreende-os na presença de todos, para que também os outros tenham temor." },
{name:'54521',l:'54',c:'5',v:'21',texto:"Conjuro-te, diante de Deus, e do Senhor Jesus Cristo, e dos anjos eleitos, que, sem prevenção, guardes estas coisas, nada fazendo por parcialidade." },
{name:'54522',l:'54',c:'5',v:'22',texto:"A ninguém imponhas precipitadamente as mãos, nem participes dos pecados alheios; conserva-te a ti mesmo puro." },
{name:'54523',l:'54',c:'5',v:'23',texto:"Não bebas mais água só, mas usa de um pouco de vinho, por causa do teu estômago e das tuas freqüentes enfermidades." },
{name:'54524',l:'54',c:'5',v:'24',texto:"Os pecados de alguns homens são manifestos, precedendo o juízo; e em alguns manifestam-se depois." },
{name:'54525',l:'54',c:'5',v:'25',texto:"Assim mesmo também as boas obras são manifestas, e as que são doutra maneira não podem ocultar-se." },
],
numVersiculos: 25,
},

c6: {
versiculos:[
{name:'5461',l:'54',c:'6',v:'1',texto:"Todos os servos que estão debaixo do jugo estimem a seus senhores por dignos de toda a honra, para que o nome de Deus e a doutrina não sejam blasfemados." },
{name:'5462',l:'54',c:'6',v:'2',texto:"E os que têm senhores crentes não os desprezem, por serem irmãos; antes, os sirvam melhor, porque eles, que participam do benefício, são crentes e amados. Isto ensina e exorta." },
{name:'5463',l:'54',c:'6',v:'3',texto:"Se alguém ensina alguma outra doutrina e se não conforma com as sãs palavras de nosso Senhor Jesus Cristo e com a doutrina que é segundo a piedade," },
{name:'5464',l:'54',c:'6',v:'4',texto:"é soberbo e nada sabe, mas delira acerca de questões e contendas de palavras, das quais nascem invejas, porfias, blasfêmias, ruins suspeitas," },
{name:'5465',l:'54',c:'6',v:'5',texto:"contendas de homens corruptos de entendimento e privados da verdade, cuidando que a piedade seja causa de ganho. Aparta-te dos tais." },
{name:'5466',l:'54',c:'6',v:'6',texto:"Mas é grande ganho a piedade com contentamento." },
{name:'5467',l:'54',c:'6',v:'7',texto:"Porque nada trouxemos para este mundo e manifesto é que nada podemos levar dele." },
{name:'5468',l:'54',c:'6',v:'8',texto:"Tendo, porém, sustento e com que nos cobrirmos, estejamos com isso contentes." },
{name:'5469',l:'54',c:'6',v:'9',texto:"Mas os que querem ser ricos caem em tentação, e em laço, e em muitas concupiscências loucas e nocivas, que submergem os homens na perdição e ruína." },
{name:'54610',l:'54',c:'6',v:'10',texto:"Porque o amor do dinheiro é a raiz de toda espécie de males; e nessa cobiça alguns se desviaram da fé e se traspassaram a si mesmos com muitas dores." },
{name:'54611',l:'54',c:'6',v:'11',texto:"Mas tu, ó homem de Deus, foge destas coisas e segue a justiça, a piedade, a fé, a caridade, a paciência, a mansidão." },
{name:'54612',l:'54',c:'6',v:'12',texto:"Milita a boa milícia da fé, toma posse da vida eterna, para a qual também foste chamado, tendo já feito boa confissão diante de muitas testemunhas." },
{name:'54613',l:'54',c:'6',v:'13',texto:"Mando-te diante de Deus, que todas as coisas vivifica, e de Cristo Jesus, que diante de Pôncio Pilatos deu o testemunho de boa confissão," },
{name:'54614',l:'54',c:'6',v:'14',texto:"que guardes este mandamento sem mácula e repreensão, até à aparição de nosso Senhor Jesus Cristo;" },
{name:'54615',l:'54',c:'6',v:'15',texto:"a qual, a seu tempo, mostrará o bem-aventurado e único poderoso Senhor, Rei dos reis e Senhor dos senhores;" },
{name:'54616',l:'54',c:'6',v:'16',texto:"aquele que tem, ele só, a imortalidade e habita na luz inacessível; a quem nenhum dos homens viu nem pode ver; ao qual seja honra e poder sempiterno. Amém!" },
{name:'54617',l:'54',c:'6',v:'17',texto:"Manda aos ricos deste mundo que não sejam altivos, nem ponham a esperança na incerteza das riquezas, mas em Deus, que abundantemente nos dá todas as coisas para delas gozarmos;" },
{name:'54618',l:'54',c:'6',v:'18',texto:"que façam o bem, enriqueçam em boas obras, repartam de boa mente e sejam comunicáveis;" },
{name:'54619',l:'54',c:'6',v:'19',texto:"que entesourem para si mesmos um bom fundamento para o futuro, para que possam alcançar a vida eterna." },
{name:'54620',l:'54',c:'6',v:'20',texto:"Ó Timóteo, guarda o depósito que te foi confiado, tendo horror aos clamores vãos e profanos e às oposições da falsamente chamada ciência;" },
{name:'54621',l:'54',c:'6',v:'21',texto:"a qual professando-a alguns, se desviaram da fé. A graça seja contigo. Amém!" },
],
numVersiculos: 21,
},
	

};
