BibliaJFA.tito = {
	libro: "Tito",
	numCapitulos: 3,

c1: {
versiculos:[
{name:'5611',l:'56',c:'1',v:'1',texto:"Paulo, servo de Deus e apóstolo de Jesus Cristo, segundo a fé dos eleitos de Deus e o conhecimento da verdade, que é segundo a piedade," },
{name:'5612',l:'56',c:'1',v:'2',texto:"em esperança da vida eterna, a qual Deus, que não pode mentir, prometeu antes dos tempos dos séculos," },
{name:'5613',l:'56',c:'1',v:'3',texto:"mas, a seu tempo, manifestou a sua palavra pela pregação que me foi confiada segundo o mandamento de Deus, nosso Salvador," },
{name:'5614',l:'56',c:'1',v:'4',texto:"a Tito, meu verdadeiro filho, segundo a fé comum: graça, misericórdia e paz, da parte de Deus Pai e da do Senhor Jesus Cristo, nosso Salvador." },
{name:'5615',l:'56',c:'1',v:'5',texto:"Por esta causa te deixei em Creta, para que pusesses em boa ordem as coisas que ainda restam e, de cidade em cidade, estabelecesses presbíteros, como já te mandei:" },
{name:'5616',l:'56',c:'1',v:'6',texto:"aquele que for irrepreensível, marido de uma mulher, que tenha filhos fiéis, que não possam ser acusados de dissolução nem são desobedientes." },
{name:'5617',l:'56',c:'1',v:'7',texto:"Porque convém que o bispo seja irrepreensível como despenseiro da casa de Deus, não soberbo, nem iracundo, nem dado ao vinho, nem espancador, nem cobiçoso de torpe ganância;" },
{name:'5618',l:'56',c:'1',v:'8',texto:"mas dado à hospitalidade, amigo do bem, moderado, justo, santo, temperante," },
{name:'5619',l:'56',c:'1',v:'9',texto:"retendo firme a fiel palavra, que é conforme a doutrina, para que seja poderoso, tanto para admoestar com a sã doutrina como para convencer os contradizentes." },
{name:'56110',l:'56',c:'1',v:'10',texto:"Porque há muitos desordenados, faladores, vãos e enganadores, principalmente os da circuncisão," },
{name:'56111',l:'56',c:'1',v:'11',texto:"aos quais convém tapar a boca; homens que transtornam casas inteiras, ensinando o que não convém, por torpe ganância." },
{name:'56112',l:'56',c:'1',v:'12',texto:"Um deles, seu próprio profeta, disse: Os cretenses são sempre mentirosos, bestas ruins, ventres preguiçosos." },
{name:'56113',l:'56',c:'1',v:'13',texto:"Este testemunho é verdadeiro. Portanto, repreende-os severamente, para que sejam sãos na fé," },
{name:'56114',l:'56',c:'1',v:'14',texto:"não dando ouvidos às fábulas judaicas, nem aos mandamentos de homens que se desviam da verdade." },
{name:'56115',l:'56',c:'1',v:'15',texto:"Todas as coisas são puras para os puros, mas nada é puro para os contaminados e infiéis; antes, o seu entendimento e consciência estão contaminados." },
{name:'56116',l:'56',c:'1',v:'16',texto:"Confessam que conhecem a Deus, mas negam-no com as obras, sendo abomináveis, e desobedientes, e reprovados para toda boa obra." },
],
numVersiculos: 16,
},

c2: {
versiculos:[
{name:'5621',l:'56',c:'2',v:'1',texto:"Tu, porém, fala o que convém à sã doutrina." },
{name:'5622',l:'56',c:'2',v:'2',texto:"Os velhos que sejam sóbrios, graves, prudentes, sãos na fé, na caridade e na paciência." },
{name:'5623',l:'56',c:'2',v:'3',texto:"As mulheres idosas, semelhantemente, que sejam sérias no seu viver, como convém a santas, não caluniadoras, não dadas a muito vinho, mestras no bem," },
{name:'5624',l:'56',c:'2',v:'4',texto:"para que ensinem as mulheres novas a serem prudentes, a amarem seus maridos, a amarem seus filhos," },
{name:'5625',l:'56',c:'2',v:'5',texto:"a serem moderadas, castas, boas donas de casa, sujeitas a seu marido, a fim de que a palavra de Deus não seja blasfemada." },
{name:'5626',l:'56',c:'2',v:'6',texto:"Exorta semelhantemente os jovens a que sejam moderados." },
{name:'5627',l:'56',c:'2',v:'7',texto:"Em tudo, te dá por exemplo de boas obras; na doutrina, mostra incorrupção, gravidade, sinceridade," },
{name:'5628',l:'56',c:'2',v:'8',texto:"linguagem sã e irrepreensível, para que o adversário se envergonhe, não tendo nenhum mal que dizer de nós." },
{name:'5629',l:'56',c:'2',v:'9',texto:"Exorta os servos a que se sujeitem a seu senhor e em tudo agradem, não contradizendo," },
{name:'56210',l:'56',c:'2',v:'10',texto:"não defraudando; antes, mostrando toda a boa lealdade, para que, em tudo, sejam ornamento da doutrina de Deus, nosso Salvador." },
{name:'56211',l:'56',c:'2',v:'11',texto:"Porque a graça de Deus se há manifestado, trazendo salvação a todos os homens," },
{name:'56212',l:'56',c:'2',v:'12',texto:"ensinando-nos que, renunciando à impiedade e às concupiscências mundanas, vivamos neste presente século sóbria, justa e piamente," },
{name:'56213',l:'56',c:'2',v:'13',texto:"aguardando a bem-aventurada esperança e o aparecimento da glória do grande Deus e nosso Senhor Jesus Cristo," },
{name:'56214',l:'56',c:'2',v:'14',texto:"o qual se deu a si mesmo por nós, para nos remir de toda iniqüidade e purificar para si um povo seu especial, zeloso de boas obras." },
{name:'56215',l:'56',c:'2',v:'15',texto:"Fala disto, e exorta, e repreende com toda a autoridade. Ninguém te despreze." },
],
numVersiculos: 15,
},

c3: {
versiculos:[
{name:'5631',l:'56',c:'3',v:'1',texto:"Admoesta-os a que se sujeitem aos principados e potestades, que lhes obedeçam e estejam preparados para toda boa obra;" },
{name:'5632',l:'56',c:'3',v:'2',texto:"que a ninguém infamem, nem sejam contenciosos, mas modestos, mostrando toda mansidão para com todos os homens." },
{name:'5633',l:'56',c:'3',v:'3',texto:"Porque também nós éramos, noutro tempo, insensatos, desobedientes, extraviados, servindo a várias concupiscências e deleites, vivendo em malícia e inveja, odiosos, odiando-nos uns aos outros." },
{name:'5634',l:'56',c:'3',v:'4',texto:"Mas, quando apareceu a benignidade e caridade de Deus, nosso Salvador, para com os homens," },
{name:'5635',l:'56',c:'3',v:'5',texto:"não pelas obras de justiça que houvéssemos feito, mas, segundo a sua misericórdia, nos salvou pela lavagem da regeneração e da renovação do Espírito Santo," },
{name:'5636',l:'56',c:'3',v:'6',texto:"que abundantemente ele derramou sobre nós por Jesus Cristo, nosso Salvador," },
{name:'5637',l:'56',c:'3',v:'7',texto:"para que, sendo justificados pela sua graça, sejamos feitos herdeiros, segundo a esperança da vida eterna." },
{name:'5638',l:'56',c:'3',v:'8',texto:"Fiel é a palavra, e isto quero que deveras afirmes, para que os que crêem em Deus procurem aplicar-se às boas obras; estas coisas são boas e proveitosas aos homens." },
{name:'5639',l:'56',c:'3',v:'9',texto:"Mas não entres em questões loucas, genealogias e contendas e nos debates acerca da lei; porque são coisas inúteis e vãs." },
{name:'56310',l:'56',c:'3',v:'10',texto:"Ao homem herege, depois de uma e outra admoestação, evita-o," },
{name:'56311',l:'56',c:'3',v:'11',texto:"sabendo que esse tal está pervertido e peca, estando já em si mesmo condenado." },
{name:'56312',l:'56',c:'3',v:'12',texto:"Quando te enviar Ártemas ou Tíquico, procura vir ter comigo a Nicópolis; porque deliberei invernar ali." },
{name:'56313',l:'56',c:'3',v:'13',texto:"Acompanha, com muito cuidado, Zenas, doutor da lei, e Apolo, para que nada lhes falte." },
{name:'56314',l:'56',c:'3',v:'14',texto:"E os nossos aprendam também a aplicar-se às boas obras, nas coisas necessárias, para que não sejam infrutuosos." },
{name:'56315',l:'56',c:'3',v:'15',texto:"Saúdam-te todos os que estão comigo. Saúda tu os que nos amam na fé. A graça seja com vós todos. Amém!" },
],
numVersiculos: 15,
},
	

};
