BibliaJFA.hebreos = {
	libro: "Hebreus",
	numCapitulos: 13,

c1: {
versiculos:[
{name:'5811',l:'58',c:'1',v:'1',texto:"Havendo Deus, antigamente, falado, muitas vezes e de muitas maneiras, aos pais, pelos profetas, a nós falou-nos, nestes últimos dias, pelo Filho," },
{name:'5812',l:'58',c:'1',v:'2',texto:"a quem constituiu herdeiro de tudo, por quem fez também o mundo." },
{name:'5813',l:'58',c:'1',v:'3',texto:"O qual, sendo o resplendor da sua glória, e a expressa imagem da sua pessoa, e sustentando todas as coisas pela palavra do seu poder, havendo feito por si mesmo a purificação dos nossos pecados, assentou-se à destra da Majestade, nas alturas;" },
{name:'5814',l:'58',c:'1',v:'4',texto:"feito tanto mais excelente do que os anjos, quanto herdou mais excelente nome do que eles." },
{name:'5815',l:'58',c:'1',v:'5',texto:"Porque a qual dos anjos disse jamais: Tu és meu Filho, hoje te gerei? E outra vez: Eu lhe serei por Pai, e ele me será por Filho?" },
{name:'5816',l:'58',c:'1',v:'6',texto:"E, quando outra vez introduz no mundo o Primogênito, diz: E todos os anjos de Deus o adorem." },
{name:'5817',l:'58',c:'1',v:'7',texto:"E, quanto aos anjos, diz: O que de seus anjos faz ventos e de seus ministros, labareda de fogo." },
{name:'5818',l:'58',c:'1',v:'8',texto:"Mas, do Filho, diz: Ó Deus, o teu trono subsiste pelos séculos dos séculos, cetro de eqüidade é o cetro do teu reino." },
{name:'5819',l:'58',c:'1',v:'9',texto:"Amaste a justiça e aborreceste a iniqüidade; por isso, Deus, o teu Deus, te ungiu com óleo de alegria, mais do que a teus companheiros." },
{name:'58110',l:'58',c:'1',v:'10',texto:"E: Tu, Senhor, no princípio, fundaste a terra, e os céus são obra de tuas mãos;" },
{name:'58111',l:'58',c:'1',v:'11',texto:"eles perecerão, mas tu permanecerás; e todos eles, como roupa, envelhecerão," },
{name:'58112',l:'58',c:'1',v:'12',texto:"e, como um manto, os enrolarás, e, como uma veste, se mudarão; mas tu és o mesmo, e os teus anos não acabarão." },
{name:'58113',l:'58',c:'1',v:'13',texto:"E a qual dos anjos disse jamais: Assenta-te à minha destra, até que ponha os teus inimigos por escabelo de teus pés?" },
{name:'58114',l:'58',c:'1',v:'14',texto:"Não são, porventura, todos eles espíritos ministradores, enviados para servir a favor daqueles que hão de herdar a salvação?" },
],
numVersiculos: 14,
},

c2: {
versiculos:[
{name:'5821',l:'58',c:'2',v:'1',texto:"Portanto, convém-nos atentar, com mais diligência, para as coisas que já temos ouvido, para que, em tempo algum, nos desviemos delas." },
{name:'5822',l:'58',c:'2',v:'2',texto:"Porque, se a palavra falada pelos anjos permaneceu firme, e toda transgressão e desobediência recebeu a justa retribuição," },
{name:'5823',l:'58',c:'2',v:'3',texto:"como escaparemos nós, se não atentarmos para uma tão grande salvação, a qual, começando a ser anunciada pelo Senhor, foi-nos, depois, confirmada pelos que a ouviram;" },
{name:'5824',l:'58',c:'2',v:'4',texto:"testificando também Deus com eles, por sinais, e milagres, e várias maravilhas, e dons do Espírito Santo, distribuídos por sua vontade?" },
{name:'5825',l:'58',c:'2',v:'5',texto:"Porque não foi aos anjos que sujeitou o mundo futuro, de que falamos;" },
{name:'5826',l:'58',c:'2',v:'6',texto:"mas, em certo lugar, testificou alguém, dizendo: Que é o homem, para que dele te lembres? Ou o filho do homem, para que o visites?" },
{name:'5827',l:'58',c:'2',v:'7',texto:"Tu o fizeste um pouco menor do que os anjos, de glória e de honra o coroaste e o constituíste sobre as obras de tuas mãos." },
{name:'5828',l:'58',c:'2',v:'8',texto:"Todas as coisas lhe sujeitaste debaixo dos pés. Ora, visto que lhe sujeitou todas as coisas, nada deixou que lhe não esteja sujeito. Mas, agora, ainda não vemos que todas as coisas lhe estejam sujeitas;" },
{name:'5829',l:'58',c:'2',v:'9',texto:"vemos, porém, coroado de glória e de honra aquele Jesus que fora feito um pouco menor do que os anjos, por causa da paixão da morte, para que, pela graça de Deus, provasse a morte por todos." },
{name:'58210',l:'58',c:'2',v:'10',texto:"Porque convinha que aquele, para quem são todas as coisas e mediante quem tudo existe, trazendo muitos filhos à glória, consagrasse, pelas aflições, o Príncipe da salvação deles." },
{name:'58211',l:'58',c:'2',v:'11',texto:"Porque, assim o que santifica como os que são santificados, são todos de um; por cuja causa não se envergonha de lhes chamar irmãos," },
{name:'58212',l:'58',c:'2',v:'12',texto:"dizendo: Anunciarei o teu nome a meus irmãos, cantar-te-ei louvores no meio da congregação." },
{name:'58213',l:'58',c:'2',v:'13',texto:"E outra vez: Porei nele a minha confiança. E outra vez: Eis-me aqui a mim e aos filhos que Deus me deu." },
{name:'58214',l:'58',c:'2',v:'14',texto:"E, visto como os filhos participam da carne e do sangue, também ele participou das mesmas coisas, para que, pela morte, aniquilasse o que tinha o império da morte, isto é, o diabo," },
{name:'58215',l:'58',c:'2',v:'15',texto:"e livrasse todos os que, com medo da morte, estavam por toda a vida sujeitos à servidão." },
{name:'58216',l:'58',c:'2',v:'16',texto:"Porque, na verdade, ele não tomou os anjos, mas tomou a descendência de Abraão." },
{name:'58217',l:'58',c:'2',v:'17',texto:"Pelo que convinha que, em tudo, fosse semelhante aos irmãos, para ser misericordioso e fiel sumo sacerdote naquilo que é de Deus, para expiar os pecados do povo." },
{name:'58218',l:'58',c:'2',v:'18',texto:"Porque, naquilo que ele mesmo, sendo tentado, padeceu, pode socorrer aos que são tentados." },
],
numVersiculos: 18,
},

c3: {
versiculos:[
{name:'5831',l:'58',c:'3',v:'1',texto:"Pelo que, irmãos santos, participantes da vocação celestial, considerai a Jesus Cristo, apóstolo e sumo sacerdote da nossa confissão," },
{name:'5832',l:'58',c:'3',v:'2',texto:"sendo fiel ao que o constituiu, como também o foi Moisés em toda a sua casa." },
{name:'5833',l:'58',c:'3',v:'3',texto:"Porque ele é tido por digno de tanto maior glória do que Moisés, quanto maior honra do que a casa tem aquele que a edificou." },
{name:'5834',l:'58',c:'3',v:'4',texto:"Porque toda casa é edificada por alguém, mas o que edificou todas as coisas é Deus." },
{name:'5835',l:'58',c:'3',v:'5',texto:"E, na verdade, Moisés foi fiel em toda a sua casa, como servo, para testemunho das coisas que se haviam de anunciar;" },
{name:'5836',l:'58',c:'3',v:'6',texto:"mas Cristo, como Filho, sobre a sua própria casa; a qual casa somos nós, se tão-somente conservarmos firme a confiança e a glória da esperança até ao fim." },
{name:'5837',l:'58',c:'3',v:'7',texto:"Portanto, como diz o Espírito Santo, se ouvirdes hoje a sua voz," },
{name:'5838',l:'58',c:'3',v:'8',texto:"não endureçais o vosso coração, como na provocação, no dia da tentação no deserto," },
{name:'5839',l:'58',c:'3',v:'9',texto:"onde vossos pais me tentaram, me provaram e viram, por quarenta anos, as minhas obras." },
{name:'58310',l:'58',c:'3',v:'10',texto:"Por isso, me indignei contra esta geração e disse: Estes sempre erram em seu coração e não conheceram os meus caminhos." },
{name:'58311',l:'58',c:'3',v:'11',texto:"Assim, jurei na minha ira que não entrarão no meu repouso." },
{name:'58312',l:'58',c:'3',v:'12',texto:"Vede, irmãos, que nunca haja em qualquer de vós um coração mau e infiel, para se apartar do Deus vivo." },
{name:'58313',l:'58',c:'3',v:'13',texto:"Antes, exortai-vos uns aos outros todos os dias, durante o tempo que se chama Hoje, para que nenhum de vós se endureça pelo engano do pecado." },
{name:'58314',l:'58',c:'3',v:'14',texto:"Porque nos tornamos participantes de Cristo, se retivermos firmemente o princípio da nossa confiança até ao fim." },
{name:'58315',l:'58',c:'3',v:'15',texto:"Enquanto se diz: Hoje, se ouvirdes a sua voz, não endureçais o vosso coração, como na provocação." },
{name:'58316',l:'58',c:'3',v:'16',texto:"Porque, havendo-a alguns ouvido, o provocaram; mas não todos os que saíram do Egito por meio de Moisés." },
{name:'58317',l:'58',c:'3',v:'17',texto:"Mas com quem se indignou por quarenta anos? Não foi, porventura, com os que pecaram, cujos corpos caíram no deserto?" },
{name:'58318',l:'58',c:'3',v:'18',texto:"E a quem jurou que não entrariam no seu repouso, senão aos que foram desobedientes?" },
{name:'58319',l:'58',c:'3',v:'19',texto:"E vemos que não puderam entrar por causa da sua incredulidade." },
],
numVersiculos: 19,
},

c4: {
versiculos:[
{name:'5841',l:'58',c:'4',v:'1',texto:"Temamos, pois, que, porventura, deixada a promessa de entrar no seu repouso, pareça que algum de vós fique para trás." },
{name:'5842',l:'58',c:'4',v:'2',texto:"Porque também a nós foram pregadas as boas-novas, como a eles, mas a palavra da pregação nada lhes aproveitou, porquanto não estava misturada com a fé naqueles que a ouviram." },
{name:'5843',l:'58',c:'4',v:'3',texto:"Porque nós, os que temos crido, entramos no repouso, tal como disse: Assim, jurei na minha ira que não entrarão no meu repouso; embora as suas obras estivessem acabadas desde a fundação do mundo." },
{name:'5844',l:'58',c:'4',v:'4',texto:"Porque, em certo lugar, disse assim do dia sétimo: E repousou Deus de todas as suas obras no sétimo dia." },
{name:'5845',l:'58',c:'4',v:'5',texto:"E outra vez neste lugar: Não entrarão no meu repouso." },
{name:'5846',l:'58',c:'4',v:'6',texto:"Visto, pois, que resta que alguns entrem nele e que aqueles a quem primeiro foram pregadas as boas-novas não entraram por causa da desobediência," },
{name:'5847',l:'58',c:'4',v:'7',texto:"determina, outra vez, um certo dia, Hoje, dizendo por Davi, muito tempo depois, como está dito: Hoje, se ouvirdes a sua voz, não endureçais o vosso coração." },
{name:'5848',l:'58',c:'4',v:'8',texto:"Porque, se Josué lhes houvesse dado repouso, não falaria, depois disso, de outro dia." },
{name:'5849',l:'58',c:'4',v:'9',texto:"Portanto, resta ainda um repouso para o povo de Deus." },
{name:'58410',l:'58',c:'4',v:'10',texto:"Porque aquele que entrou no seu repouso, ele próprio repousou de suas obras, como Deus das suas." },
{name:'58411',l:'58',c:'4',v:'11',texto:"Procuremos, pois, entrar naquele repouso, para que ninguém caia no mesmo exemplo de desobediência." },
{name:'58412',l:'58',c:'4',v:'12',texto:"Porque a palavra de Deus é viva, e eficaz, e mais penetrante do que qualquer espada de dois gumes, e penetra até à divisão da alma, e do espírito, e das juntas e medulas, e é apta para discernir os pensamentos e intenções do coração." },
{name:'58413',l:'58',c:'4',v:'13',texto:"E não há criatura alguma encoberta diante dele; antes, todas as coisas estão nuas e patentes aos olhos daquele com quem temos de tratar." },
{name:'58414',l:'58',c:'4',v:'14',texto:"Visto que temos um grande sumo sacerdote, Jesus, Filho de Deus, que penetrou nos céus, retenhamos firmemente a nossa confissão." },
{name:'58415',l:'58',c:'4',v:'15',texto:"Porque não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas; porém um que, como nós, em tudo foi tentado, mas sem pecado." },
{name:'58416',l:'58',c:'4',v:'16',texto:"Cheguemos, pois, com confiança ao trono da graça, para que possamos alcançar misericórdia e achar graça, a fim de sermos ajudados em tempo oportuno." },
],
numVersiculos: 16,
},

c5: {
versiculos:[
{name:'5851',l:'58',c:'5',v:'1',texto:"Porque todo sumo sacerdote, tomado dentre os homens, é constituído a favor dos homens nas coisas concernentes a Deus, para que ofereça dons e sacrifícios pelos pecados," },
{name:'5852',l:'58',c:'5',v:'2',texto:"e possa compadecer-se ternamente dos ignorantes e errados, pois também ele mesmo está rodeado de fraqueza." },
{name:'5853',l:'58',c:'5',v:'3',texto:"E, por esta causa, deve ele, tanto pelo povo como também por si mesmo, fazer oferta pelos pecados." },
{name:'5854',l:'58',c:'5',v:'4',texto:"E ninguém toma para si essa honra, senão o que é chamado por Deus, como Arão." },
{name:'5855',l:'58',c:'5',v:'5',texto:"Assim, também Cristo não se glorificou a si mesmo, para se fazer sumo sacerdote, mas glorificou aquele que lhe disse: Tu és meu Filho, hoje te gerei." },
{name:'5856',l:'58',c:'5',v:'6',texto:"Como também diz noutro lugar: Tu és sacerdote eternamente, segundo a ordem de Melquisedeque." },
{name:'5857',l:'58',c:'5',v:'7',texto:"O qual, nos dias da sua carne, oferecendo, com grande clamor e lágrimas, orações e súplicas ao que o podia livrar da morte, foi ouvido quanto ao que temia." },
{name:'5858',l:'58',c:'5',v:'8',texto:"Ainda que era Filho, aprendeu a obediência, por aquilo que padeceu." },
{name:'5859',l:'58',c:'5',v:'9',texto:"E, sendo ele consumado, veio a ser a causa de eterna salvação para todos os que lhe obedecem," },
{name:'58510',l:'58',c:'5',v:'10',texto:"chamado por Deus sumo sacerdote, segundo a ordem de Melquisedeque." },
{name:'58511',l:'58',c:'5',v:'11',texto:"Do qual muito temos que dizer, de difícil interpretação, porquanto vos fizestes negligentes para ouvir." },
{name:'58512',l:'58',c:'5',v:'12',texto:"Porque, devendo já ser mestres pelo tempo, ainda necessitais de que se vos torne a ensinar quais sejam os primeiros rudimentos das palavras de Deus; e vos haveis feito tais que necessitais de leite e não de sólido mantimento." },
{name:'58513',l:'58',c:'5',v:'13',texto:"Porque qualquer que ainda se alimenta de leite não está experimentado na palavra da justiça, porque é menino." },
{name:'58514',l:'58',c:'5',v:'14',texto:"Mas o mantimento sólido é para os perfeitos, os quais, em razão do costume, têm os sentidos exercitados para discernir tanto o bem como o mal." },
],
numVersiculos: 14,
},

c6: {
versiculos:[
{name:'5861',l:'58',c:'6',v:'1',texto:"Pelo que, deixando os rudimentos da doutrina de Cristo, prossigamos até a perfeição, não lançando de novo o fundamento do arrependimento de obras mortas e de fé em Deus," },
{name:'5862',l:'58',c:'6',v:'2',texto:"e da doutrina dos batismos, e da imposição das mãos, e da ressurreição dos mortos, e do juízo eterno." },
{name:'5863',l:'58',c:'6',v:'3',texto:"E isso faremos, se Deus o permitir." },
{name:'5864',l:'58',c:'6',v:'4',texto:"Porque é impossível que os que já uma vez foram iluminados, e provaram o dom celestial, e se fizeram participantes do Espírito Santo," },
{name:'5865',l:'58',c:'6',v:'5',texto:"e provaram a boa palavra de Deus e as virtudes do século futuro," },
{name:'5866',l:'58',c:'6',v:'6',texto:"e recaíram sejam outra vez renovados para arrependimento; pois assim, quanto a eles, de novo crucificam o Filho de Deus e o expõem ao vitupério." },
{name:'5867',l:'58',c:'6',v:'7',texto:"Porque a terra que embebe a chuva que muitas vezes cai sobre ela e produz erva proveitosa para aqueles por quem é lavrada recebe a bênção de Deus;" },
{name:'5868',l:'58',c:'6',v:'8',texto:"mas a que produz espinhos e abrolhos é reprovada e perto está da maldição; o seu fim é ser queimada." },
{name:'5869',l:'58',c:'6',v:'9',texto:"Mas de vós, ó amados, esperamos coisas melhores e coisas que acompanham a salvação, ainda que assim falamos." },
{name:'58610',l:'58',c:'6',v:'10',texto:"Porque Deus não é injusto para se esquecer da vossa obra e do trabalho da caridade que, para com o seu nome, mostrastes, enquanto servistes aos santos e ainda servis." },
{name:'58611',l:'58',c:'6',v:'11',texto:"Mas desejamos que cada um de vós mostre o mesmo cuidado até ao fim, para completa certeza da esperança;" },
{name:'58612',l:'58',c:'6',v:'12',texto:"para que vos não façais negligentes, mas sejais imitadores dos que, pela fé e paciência, herdam as promessas." },
{name:'58613',l:'58',c:'6',v:'13',texto:"Porque, quando Deus fez a promessa a Abraão, como não tinha outro maior por quem jurasse, jurou por si mesmo," },
{name:'58614',l:'58',c:'6',v:'14',texto:"dizendo: Certamente, abençoando, te abençoarei e, multiplicando, te multiplicarei." },
{name:'58615',l:'58',c:'6',v:'15',texto:"E assim, esperando com paciência, alcançou a promessa." },
{name:'58616',l:'58',c:'6',v:'16',texto:"Porque os homens certamente juram por alguém superior a eles, e o juramento para confirmação é, para eles, o fim de toda contenda." },
{name:'58617',l:'58',c:'6',v:'17',texto:"Pelo que, querendo Deus mostrar mais abundantemente a imutabilidade do seu conselho aos herdeiros da promessa, se interpôs com juramento," },
{name:'58618',l:'58',c:'6',v:'18',texto:"para que por duas coisas imutáveis, nas quais é impossível que Deus minta, tenhamos a firme consolação, nós, os que pomos o nosso refúgio em reter a esperança proposta;" },
{name:'58619',l:'58',c:'6',v:'19',texto:"a qual temos como âncora da alma segura e firme e que penetra até ao interior do véu," },
{name:'58620',l:'58',c:'6',v:'20',texto:"onde Jesus, nosso precursor, entrou por nós, feito eternamente sumo sacerdote, segundo a ordem de Melquisedeque." },
],
numVersiculos: 20,
},

c7: {
versiculos:[
{name:'5871',l:'58',c:'7',v:'1',texto:"Porque este Melquisedeque, que era rei de Salém e sacerdote do Deus Altíssimo, e que saiu ao encontro de Abraão quando ele regressava da matança dos reis, e o abençoou;" },
{name:'5872',l:'58',c:'7',v:'2',texto:"a quem também Abraão deu o dízimo de tudo, e primeiramente é, por interpretação, rei de justiça e depois também rei de Salém, que é rei de paz;" },
{name:'5873',l:'58',c:'7',v:'3',texto:"sem pai, sem mãe, sem genealogia, não tendo princípio de dias nem fim de vida, mas, sendo feito semelhante ao Filho de Deus, permanece sacerdote para sempre." },
{name:'5874',l:'58',c:'7',v:'4',texto:"Considerai, pois, quão grande era este, a quem até o patriarca Abraão deu os dízimos dos despojos." },
{name:'5875',l:'58',c:'7',v:'5',texto:"E os que dentre os filhos de Levi recebem o sacerdócio têm ordem, segundo a lei, de tomar o dízimo do povo, isto é, de seus irmãos, ainda que tenham descendido de Abraão." },
{name:'5876',l:'58',c:'7',v:'6',texto:"Mas aquele cuja genealogia não é contada entre eles tomou dízimos de Abraão e abençoou o que tinha as promessas." },
{name:'5877',l:'58',c:'7',v:'7',texto:"Ora, sem contradição alguma, o menor é abençoado pelo maior." },
{name:'5878',l:'58',c:'7',v:'8',texto:"E aqui certamente tomam dízimos homens que morrem; ali, porém, aquele de quem se testifica que vive." },
{name:'5879',l:'58',c:'7',v:'9',texto:"E, para assim dizer, por meio de Abraão, até Levi, que recebe dízimos, pagou dízimos." },
{name:'58710',l:'58',c:'7',v:'10',texto:"Porque ainda ele estava nos lombos de seu pai, quando Melquisedeque lhe saiu ao encontro." },
{name:'58711',l:'58',c:'7',v:'11',texto:"De sorte que, se a perfeição fosse pelo sacerdócio levítico ( porque sob ele o povo recebeu a lei ), que necessidade havia logo de que outro sacerdote se levantasse, segundo a ordem de Melquisedeque, e não fosse chamado segundo a ordem de Arão?" },
{name:'58712',l:'58',c:'7',v:'12',texto:"Porque, mudando-se o sacerdócio, necessariamente se faz também mudança da lei." },
{name:'58713',l:'58',c:'7',v:'13',texto:"Porque aquele de quem essas coisas se dizem pertence a outra tribo, da qual ninguém serviu ao altar," },
{name:'58714',l:'58',c:'7',v:'14',texto:"visto ser manifesto que nosso Senhor procedeu de Judá, e concernente a essa tribo nunca Moisés falou de sacerdócio." },
{name:'58715',l:'58',c:'7',v:'15',texto:"E muito mais manifesto é ainda se, à semelhança de Melquisedeque, se levantar outro sacerdote," },
{name:'58716',l:'58',c:'7',v:'16',texto:"que não foi feito segundo a lei do mandamento carnal, mas segundo a virtude da vida incorruptível." },
{name:'58717',l:'58',c:'7',v:'17',texto:"Porque dele assim se testifica: Tu és sacerdote eternamente, segundo a ordem de Melquisedeque." },
{name:'58718',l:'58',c:'7',v:'18',texto:"Porque o precedente mandamento é ab-rogado por causa da sua fraqueza e inutilidade" },
{name:'58719',l:'58',c:'7',v:'19',texto:"( pois a lei nenhuma coisa aperfeiçoou ), e desta sorte é introduzida uma melhor esperança, pela qual chegamos a Deus." },
{name:'58720',l:'58',c:'7',v:'20',texto:"E, visto como não é sem prestar juramento ( porque certamente aqueles, sem juramento, foram feitos sacerdotes," },
{name:'58721',l:'58',c:'7',v:'21',texto:"mas este, com juramento, por aquele que lhe disse: Jurou o Senhor e não se arrependerá: Tu és sacerdote eternamente, segundo a ordem de Melquisedeque. );" },
{name:'58722',l:'58',c:'7',v:'22',texto:"de tanto melhor concerto Jesus foi feito fiador." },
{name:'58723',l:'58',c:'7',v:'23',texto:"E, na verdade, aqueles foram feitos sacerdotes em grande número, porque, pela morte, foram impedidos de permanecer;" },
{name:'58724',l:'58',c:'7',v:'24',texto:"mas este, porque permanece eternamente, tem um sacerdócio perpétuo." },
{name:'58725',l:'58',c:'7',v:'25',texto:"Portanto, pode também salvar perfeitamente os que por ele se chegam a Deus, vivendo sempre para interceder por eles." },
{name:'58726',l:'58',c:'7',v:'26',texto:"Porque nos convinha tal sumo sacerdote, santo, inocente, imaculado, separado dos pecadores e feito mais sublime do que os céus," },
{name:'58727',l:'58',c:'7',v:'27',texto:"que não necessitasse, como os sumos sacerdotes, de oferecer cada dia sacrifícios, primeiramente, por seus próprios pecados e, depois, pelos do povo; porque isso fez ele, uma vez, oferecendo-se a si mesmo." },
{name:'58728',l:'58',c:'7',v:'28',texto:"Porque a lei constitui sumos sacerdotes a homens fracos, mas a palavra do juramento, que veio depois da lei, constitui ao Filho, perfeito para sempre." },
],
numVersiculos: 28,
},

c8: {
versiculos:[
{name:'5881',l:'58',c:'8',v:'1',texto:"Ora, a suma do que temos dito é que temos um sumo sacerdote tal, que está assentado nos céus à destra do trono da Majestade," },
{name:'5882',l:'58',c:'8',v:'2',texto:"ministro do santuário e do verdadeiro tabernáculo, o qual o Senhor fundou, e não o homem." },
{name:'5883',l:'58',c:'8',v:'3',texto:"Porque todo sumo sacerdote é constituído para oferecer dons e sacrifícios; pelo que era necessário que este também tivesse alguma coisa que oferecer." },
{name:'5884',l:'58',c:'8',v:'4',texto:"Ora, se ele estivesse na terra, nem tampouco sacerdote seria, havendo ainda sacerdotes que oferecem dons segundo a lei," },
{name:'5885',l:'58',c:'8',v:'5',texto:"os quais servem de exemplar e sombra das coisas celestiais, como Moisés divinamente foi avisado, estando já para acabar o tabernáculo; porque foi dito: Olha, faze tudo conforme o modelo que, no monte, se te mostrou." },
{name:'5886',l:'58',c:'8',v:'6',texto:"Mas agora alcançou ele ministério tanto mais excelente, quanto é mediador de um melhor concerto, que está confirmado em melhores promessas." },
{name:'5887',l:'58',c:'8',v:'7',texto:"Porque, se aquele primeiro fora irrepreensível, nunca se teria buscado lugar para o segundo." },
{name:'5888',l:'58',c:'8',v:'8',texto:"Porque, repreendendo-os, lhes diz: Eis que virão dias, diz o Senhor, em que com a casa de Israel e com a casa de Judá estabelecerei um novo concerto," },
{name:'5889',l:'58',c:'8',v:'9',texto:"não segundo o concerto que fiz com seus pais, no dia em que os tomei pela mão, para os tirar da terra do Egito; como não permaneceram naquele meu concerto, eu para eles não atentei, diz o Senhor." },
{name:'58810',l:'58',c:'8',v:'10',texto:"Porque este é o concerto que, depois daqueles dias, farei com a casa de Israel, diz o Senhor: porei as minhas leis no seu entendimento e em seu coração as escreverei; e eu lhes serei por Deus, e eles me serão por povo." },
{name:'58811',l:'58',c:'8',v:'11',texto:"E não ensinará cada um ao seu próximo, nem cada um ao seu irmão, dizendo: Conhece o Senhor; porque todos me conhecerão, desde o menor deles até ao maior." },
{name:'58812',l:'58',c:'8',v:'12',texto:"Porque serei misericordioso para com as suas iniqüidades e de seus pecados e de suas prevaricações não me lembrarei mais." },
{name:'58813',l:'58',c:'8',v:'13',texto:"Dizendo novo concerto, envelheceu o primeiro. Ora, o que foi tornado velho e se envelhece perto está de acabar." },
],
numVersiculos: 13,
},

c9: {
versiculos:[
{name:'5891',l:'58',c:'9',v:'1',texto:"Ora, também o primeiro tinha ordenanças de culto divino e um santuário terrestre." },
{name:'5892',l:'58',c:'9',v:'2',texto:"Porque um tabernáculo estava preparado, o primeiro, em que havia o candeeiro, e a mesa, e os pães da proposição; ao que se chama o Santuário." },
{name:'5893',l:'58',c:'9',v:'3',texto:"Mas, depois do segundo véu, estava o tabernáculo que se chama o Santo dos Santos," },
{name:'5894',l:'58',c:'9',v:'4',texto:"que tinha o incensário de ouro e a arca do concerto, coberta de ouro toda em redor, em que estava um vaso de ouro, que continha o maná, e a vara de Arão, que tinha florescido, e as tábuas do concerto;" },
{name:'5895',l:'58',c:'9',v:'5',texto:"e sobre a arca, os querubins da glória, que faziam sombra no propiciatório; das quais coisas não falaremos agora particularmente." },
{name:'5896',l:'58',c:'9',v:'6',texto:"Ora, estando essas coisas assim preparadas, a todo o tempo entravam os sacerdotes no primeiro tabernáculo, cumprindo os serviços;" },
{name:'5897',l:'58',c:'9',v:'7',texto:"mas, no segundo, só o sumo sacerdote, uma vez no ano, não sem sangue, que oferecia por si mesmo e pelas culpas do povo;" },
{name:'5898',l:'58',c:'9',v:'8',texto:"dando nisso a entender o Espírito Santo que ainda o caminho do Santuário não estava descoberto, enquanto se conservava em pé o primeiro tabernáculo," },
{name:'5899',l:'58',c:'9',v:'9',texto:"que é uma alegoria para o tempo presente, em que se oferecem dons e sacrifícios que, quanto à consciência, não podem aperfeiçoar aquele que faz o serviço," },
{name:'58910',l:'58',c:'9',v:'10',texto:"consistindo somente em manjares, e bebidas, e várias abluções e justificações da carne, impostas até ao tempo da correção." },
{name:'58911',l:'58',c:'9',v:'11',texto:"Mas, vindo Cristo, o sumo sacerdote dos bens futuros, por um maior e mais perfeito tabernáculo, não feito por mãos, isto é, não desta criação," },
{name:'58912',l:'58',c:'9',v:'12',texto:"nem por sangue de bodes e bezerros, mas por seu próprio sangue, entrou uma vez no santuário, havendo efetuado uma eterna redenção." },
{name:'58913',l:'58',c:'9',v:'13',texto:"Porque, se o sangue dos touros e bodes e a cinza de uma novilha, esparzida sobre os imundos, os santificam, quanto à purificação da carne," },
{name:'58914',l:'58',c:'9',v:'14',texto:"quanto mais o sangue de Cristo, que, pelo Espírito eterno, se ofereceu a si mesmo imaculado a Deus, purificará a vossa consciência das obras mortas, para servirdes ao Deus vivo?" },
{name:'58915',l:'58',c:'9',v:'15',texto:"E, por isso, é Mediador de um novo testamento, para que, intervindo a morte para remissão das transgressões que havia debaixo do primeiro testamento, os chamados recebam a promessa da herança eterna." },
{name:'58916',l:'58',c:'9',v:'16',texto:"Porque, onde há testamento, necessário é que intervenha a morte do testador." },
{name:'58917',l:'58',c:'9',v:'17',texto:"Porque um testamento tem força onde houve morte; ou terá ele algum valor enquanto o testador vive?" },
{name:'58918',l:'58',c:'9',v:'18',texto:"Pelo que também o primeiro não foi consagrado sem sangue;" },
{name:'58919',l:'58',c:'9',v:'19',texto:"porque, havendo Moisés anunciado a todo o povo todos os mandamentos segundo a lei, tomou o sangue dos bezerros e dos bodes, com água, lã purpúrea e hissopo, e aspergiu tanto o mesmo livro como todo o povo," },
{name:'58920',l:'58',c:'9',v:'20',texto:"dizendo: Este é o sangue do testamento que Deus vos tem mandado." },
{name:'58921',l:'58',c:'9',v:'21',texto:"E semelhantemente aspergiu com sangue o tabernáculo e todos os vasos do ministério." },
{name:'58922',l:'58',c:'9',v:'22',texto:"E quase todas as coisas, segundo a lei, se purificam com sangue; e sem derramamento de sangue não há remissão." },
{name:'58923',l:'58',c:'9',v:'23',texto:"De sorte que era bem necessário que as figuras das coisas que estão no céu assim se purificassem; mas as próprias coisas celestiais, com sacrifícios melhores do que estes." },
{name:'58924',l:'58',c:'9',v:'24',texto:"Porque Cristo não entrou num santuário feito por mãos, figura do verdadeiro, porém no mesmo céu, para agora comparecer, por nós, perante a face de Deus;" },
{name:'58925',l:'58',c:'9',v:'25',texto:"nem também para a si mesmo se oferecer muitas vezes, como o sumo sacerdote cada ano entra no Santuário com sangue alheio." },
{name:'58926',l:'58',c:'9',v:'26',texto:"Doutra maneira, necessário lhe fora padecer muitas vezes desde a fundação do mundo; mas, agora, na consumação dos séculos, uma vez se manifestou, para aniquilar o pecado pelo sacrifício de si mesmo." },
{name:'58927',l:'58',c:'9',v:'27',texto:"E, como aos homens está ordenado morrerem uma vez, vindo, depois disso, o juízo," },
{name:'58928',l:'58',c:'9',v:'28',texto:"assim também Cristo, oferecendo-se uma vez, para tirar os pecados de muitos, aparecerá segunda vez, sem pecado, aos que o esperam para a salvação." },
],
numVersiculos: 28,
},

c10: {
versiculos:[
{name:'58101',l:'58',c:'10',v:'1',texto:"Porque, tendo a lei a sombra dos bens futuros e não a imagem exata das coisas, nunca, pelos mesmos sacrifícios que continuamente se oferecem cada ano, pode aperfeiçoar os que a eles se chegam." },
{name:'58102',l:'58',c:'10',v:'2',texto:"Doutra maneira, teriam deixado de se oferecer, porque, purificados uma vez os ministrantes, nunca mais teriam consciência de pecado." },
{name:'58103',l:'58',c:'10',v:'3',texto:"Nesses sacrifícios, porém, cada ano, se faz comemoração dos pecados," },
{name:'58104',l:'58',c:'10',v:'4',texto:"porque é impossível que o sangue dos touros e dos bodes tire pecados." },
{name:'58105',l:'58',c:'10',v:'5',texto:"Pelo que, entrando no mundo, diz: Sacrifício e oferta não quiseste, mas corpo me preparaste;" },
{name:'58106',l:'58',c:'10',v:'6',texto:"holocaustos e oblações pelo pecado não te agradaram." },
{name:'58107',l:'58',c:'10',v:'7',texto:"Então, disse: Eis aqui venho ( no princípio do livro está escrito de mim ), para fazer, ó Deus, a tua vontade." },
{name:'58108',l:'58',c:'10',v:'8',texto:"Como acima diz: Sacrifício, e oferta, e holocaustos, e oblações pelo pecado não quiseste, nem te agradaram ( os quais se oferecem segundo a lei )." },
{name:'58109',l:'58',c:'10',v:'9',texto:"Então, disse: Eis aqui venho, para fazer, ó Deus, a tua vontade. Tira o primeiro, para estabelecer o segundo." },
{name:'581010',l:'58',c:'10',v:'10',texto:"Na qual vontade temos sido santificados pela oblação do corpo de Jesus Cristo, feita uma vez." },
{name:'581011',l:'58',c:'10',v:'11',texto:"E assim todo sacerdote aparece cada dia, ministrando e oferecendo muitas vezes os mesmos sacrifícios, que nunca podem tirar pecados;" },
{name:'581012',l:'58',c:'10',v:'12',texto:"mas este, havendo oferecido um único sacrifício pelos pecados, está assentado para sempre à destra de Deus," },
{name:'581013',l:'58',c:'10',v:'13',texto:"daqui em diante esperando até que os seus inimigos sejam postos por escabelo de seus pés." },
{name:'581014',l:'58',c:'10',v:'14',texto:"Porque, com uma só oblação, aperfeiçoou para sempre os que são santificados." },
{name:'581015',l:'58',c:'10',v:'15',texto:"E também o Espírito Santo no-lo testifica, porque, depois de haver dito:" },
{name:'581016',l:'58',c:'10',v:'16',texto:"Este é o concerto que farei com eles depois daqueles dias, diz o Senhor: Porei as minhas leis em seu coração e as escreverei em seus entendimentos, acrescenta:" },
{name:'581017',l:'58',c:'10',v:'17',texto:"E jamais me lembrarei de seus pecados e de suas iniqüidades." },
{name:'581018',l:'58',c:'10',v:'18',texto:"Ora, onde há remissão destes, não há mais oblação pelo pecado." },
{name:'581019',l:'58',c:'10',v:'19',texto:"Tendo, pois, irmãos, ousadia para entrar no Santuário, pelo sangue de Jesus," },
{name:'581020',l:'58',c:'10',v:'20',texto:"pelo novo e vivo caminho que ele nos consagrou, pelo véu, isto é, pela sua carne," },
{name:'581021',l:'58',c:'10',v:'21',texto:"e tendo um grande sacerdote sobre a casa de Deus," },
{name:'581022',l:'58',c:'10',v:'22',texto:"cheguemo-nos com verdadeiro coração, em inteira certeza de fé; tendo o coração purificado da má consciência e o corpo lavado com água limpa," },
{name:'581023',l:'58',c:'10',v:'23',texto:"retenhamos firmes a confissão da nossa esperança, porque fiel é o que prometeu." },
{name:'581024',l:'58',c:'10',v:'24',texto:"E consideremo-nos uns aos outros, para nos estimularmos à caridade e às boas obras," },
{name:'581025',l:'58',c:'10',v:'25',texto:"não deixando a nossa congregação, como é costume de alguns; antes, admoestando-nos uns aos outros; e tanto mais quanto vedes que se vai aproximando aquele Dia." },
{name:'581026',l:'58',c:'10',v:'26',texto:"Porque, se pecarmos voluntariamente, depois de termos recebido o conhecimento da verdade, já não resta mais sacrifício pelos pecados," },
{name:'581027',l:'58',c:'10',v:'27',texto:"mas uma certa expectação horrível de juízo e ardor de fogo, que há de devorar os adversários." },
{name:'581028',l:'58',c:'10',v:'28',texto:"Quebrantando alguém a lei de Moisés, morre sem misericórdia, só pela palavra de duas ou três testemunhas." },
{name:'581029',l:'58',c:'10',v:'29',texto:"De quanto maior castigo cuidais vós será julgado merecedor aquele que pisar o Filho de Deus, e tiver por profano o sangue do testamento, com que foi santificado, e fizer agravo ao Espírito da graça?" },
{name:'581030',l:'58',c:'10',v:'30',texto:"Porque bem conhecemos aquele que disse: Minha é a vingança, eu darei a recompensa, diz o Senhor. E outra vez: O Senhor julgará o seu povo." },
{name:'581031',l:'58',c:'10',v:'31',texto:"Horrenda coisa é cair nas mãos do Deus vivo." },
{name:'581032',l:'58',c:'10',v:'32',texto:"Lembrai-vos, porém, dos dias passados, em que, depois de serdes iluminados, suportastes grande combate de aflições." },
{name:'581033',l:'58',c:'10',v:'33',texto:"Em parte, fostes feitos espetáculo com vitupérios e tribulações e, em parte, fostes participantes com os que assim foram tratados." },
{name:'581034',l:'58',c:'10',v:'34',texto:"Porque também vos compadecestes dos que estavam nas prisões e com gozo permitistes a espoliação dos vossos bens, sabendo que, em vós mesmos, tendes nos céus uma possessão melhor e permanente." },
{name:'581035',l:'58',c:'10',v:'35',texto:"Não rejeiteis, pois, a vossa confiança, que tem grande e avultado galardão." },
{name:'581036',l:'58',c:'10',v:'36',texto:"Porque necessitais de paciência, para que, depois de haverdes feito a vontade de Deus, possais alcançar a promessa." },
{name:'581037',l:'58',c:'10',v:'37',texto:"Porque ainda um poucochinho de tempo, e o que há de vir virá e não tardará." },
{name:'581038',l:'58',c:'10',v:'38',texto:"Mas o justo viverá da fé; e, se ele recuar, a minha alma não tem prazer nele." },
{name:'581039',l:'58',c:'10',v:'39',texto:"Nós, porém, não somos daqueles que se retiram para a perdição, mas daqueles que crêem para a conservação da alma." },
],
numVersiculos: 39,
},

c11: {
versiculos:[
{name:'58111',l:'58',c:'11',v:'1',texto:"Ora, a fé é o firme fundamento das coisas que se esperam e a prova das coisas que se não vêem." },
{name:'58112',l:'58',c:'11',v:'2',texto:"Porque, por ela, os antigos alcançaram testemunho." },
{name:'58113',l:'58',c:'11',v:'3',texto:"Pela fé, entendemos que os mundos, pela palavra de Deus, foram criados; de maneira que aquilo que se vê não foi feito do que é aparente." },
{name:'58114',l:'58',c:'11',v:'4',texto:"Pela fé, Abel ofereceu a Deus maior sacrifício do que Caim, pelo qual alcançou testemunho de que era justo, dando Deus testemunho dos seus dons, e, por ela, depois de morto, ainda fala." },
{name:'58115',l:'58',c:'11',v:'5',texto:"Pela fé, Enoque foi trasladado para não ver a morte e não foi achado, porque Deus o trasladara, visto como, antes da sua trasladação, alcançou testemunho de que agradara a Deus." },
{name:'58116',l:'58',c:'11',v:'6',texto:"Ora, sem fé é impossível agradar-lhe, porque é necessário que aquele que se aproxima de Deus creia que ele existe e que é galardoador dos que o buscam." },
{name:'58117',l:'58',c:'11',v:'7',texto:"Pela fé, Noé, divinamente avisado das coisas que ainda não se viam, temeu, e, para salvação da sua família, preparou a arca, pela qual condenou o mundo, e foi feito herdeiro da justiça que é segundo a fé." },
{name:'58118',l:'58',c:'11',v:'8',texto:"Pela fé, Abraão, sendo chamado, obedeceu, indo para um lugar que havia de receber por herança; e saiu, sem saber para onde ia." },
{name:'58119',l:'58',c:'11',v:'9',texto:"Pela fé, habitou na terra da promessa, como em terra alheia, morando em cabanas com Isaque e Jacó, herdeiros com ele da mesma promessa." },
{name:'581110',l:'58',c:'11',v:'10',texto:"Porque esperava a cidade que tem fundamentos, da qual o artífice e construtor é Deus." },
{name:'581111',l:'58',c:'11',v:'11',texto:"Pela fé, também a mesma Sara recebeu a virtude de conceber e deu à luz já fora da idade; porquanto teve por fiel aquele que lho tinha prometido." },
{name:'581112',l:'58',c:'11',v:'12',texto:"Pelo que também de um, e esse já amortecido, descenderam tantos, em multidão, como as estrelas do céu, e como a areia inumerável que está na praia do mar." },
{name:'581113',l:'58',c:'11',v:'13',texto:"Todos estes morreram na fé, sem terem recebido as promessas, mas, vendo-as de longe, e crendo nelas, e abraçando-as, confessaram que eram estrangeiros e peregrinos na terra." },
{name:'581114',l:'58',c:'11',v:'14',texto:"Porque os que isso dizem claramente mostram que buscam uma pátria." },
{name:'581115',l:'58',c:'11',v:'15',texto:"E se, na verdade, se lembrassem daquela de onde haviam saído, teriam oportunidade de tornar." },
{name:'581116',l:'58',c:'11',v:'16',texto:"Mas, agora, desejam uma melhor, isto é, a celestial. Pelo que também Deus não se envergonha deles, de se chamar seu Deus, porque já lhes preparou uma cidade." },
{name:'581117',l:'58',c:'11',v:'17',texto:"Pela fé, ofereceu Abraão a Isaque, quando foi provado, sim, aquele que recebera as promessas ofereceu o seu unigênito." },
{name:'581118',l:'58',c:'11',v:'18',texto:"Sendo-lhe dito: Em Isaque será chamada a tua descendência, considerou que Deus era poderoso para até dos mortos o ressuscitar." },
{name:'581119',l:'58',c:'11',v:'19',texto:"E daí também, em figura, ele o recobrou." },
{name:'581120',l:'58',c:'11',v:'20',texto:"Pela fé, Isaque abençoou Jacó e Esaú, no tocante às coisas futuras." },
{name:'581121',l:'58',c:'11',v:'21',texto:"Pela fé, Jacó, próximo da morte, abençoou cada um dos filhos de José e adorou encostado à ponta do seu bordão." },
{name:'581122',l:'58',c:'11',v:'22',texto:"Pela fé, José, próximo da morte, fez menção da saída dos filhos de Israel e deu ordem acerca de seus ossos." },
{name:'581123',l:'58',c:'11',v:'23',texto:"Pela fé, Moisés, já nascido, foi escondido três meses por seus pais, porque viram que era um menino formoso; e não temeram o mandamento do rei." },
{name:'581124',l:'58',c:'11',v:'24',texto:"Pela fé, Moisés, sendo já grande, recusou ser chamado filho da filha de Faraó," },
{name:'581125',l:'58',c:'11',v:'25',texto:"Escolhendo, antes, ser maltratado com o povo de Deus do que por, um pouco de tempo, ter o gozo do pecado;" },
{name:'581126',l:'58',c:'11',v:'26',texto:"tendo, por maiores riquezas, o vitupério de Cristo do que os tesouros do Egito; porque tinha em vista a recompensa." },
{name:'581127',l:'58',c:'11',v:'27',texto:"Pela fé, deixou o Egito, não temendo a ira do rei; porque ficou firme, como vendo o invisível." },
{name:'581128',l:'58',c:'11',v:'28',texto:"Pela fé, celebrou a Páscoa e a aspersão do sangue, para que o destruidor dos primogênitos lhes não tocasse." },
{name:'581129',l:'58',c:'11',v:'29',texto:"Pela fé, passaram o mar Vermelho, como por terra seca; o que intentando os egípcios, se afogaram." },
{name:'581130',l:'58',c:'11',v:'30',texto:"Pela fé, caíram os muros de Jericó, sendo rodeados durante sete dias." },
{name:'581131',l:'58',c:'11',v:'31',texto:"Pela fé, Raabe, a meretriz, não pereceu com os incrédulos, acolhendo em paz os espias." },
{name:'581132',l:'58',c:'11',v:'32',texto:"E que mais direi? Faltar-me-ia o tempo contando de Gideão, e de Baraque, e de Sansão, e de Jefté, e de Davi, e de Samuel, e dos profetas," },
{name:'581133',l:'58',c:'11',v:'33',texto:"os quais, pela fé, venceram reinos, praticaram a justiça, alcançaram promessas, fecharam as bocas dos leões," },
{name:'581134',l:'58',c:'11',v:'34',texto:"apagaram a força do fogo, escaparam do fio da espada, da fraqueza tiraram forças, na batalha se esforçaram, puseram em fugida os exércitos dos estranhos." },
{name:'581135',l:'58',c:'11',v:'35',texto:"As mulheres receberam, pela ressurreição, os seus mortos; uns foram torturados, não aceitando o seu livramento, para alcançarem uma melhor ressurreição;" },
{name:'581136',l:'58',c:'11',v:'36',texto:"E outros experimentaram escárnios e açoites, e até cadeias e prisões." },
{name:'581137',l:'58',c:'11',v:'37',texto:"Foram apedrejados, serrados, tentados, mortos a fio de espada; andaram vestidos de peles de ovelhas e de cabras, desamparados, aflitos e maltratados" },
{name:'581138',l:'58',c:'11',v:'38',texto:"( homens dos quais o mundo não era digno ), errantes pelos desertos, e montes, e pelas covas e cavernas da terra." },
{name:'581139',l:'58',c:'11',v:'39',texto:"E todos estes, tendo tido testemunho pela fé, não alcançaram a promessa," },
{name:'581140',l:'58',c:'11',v:'40',texto:"provendo Deus alguma coisa melhor a nosso respeito, para que eles, sem nós, não fossem aperfeiçoados." },
],
numVersiculos: 40,
},

c12: {
versiculos:[
{name:'58121',l:'58',c:'12',v:'1',texto:"Portanto, nós também, pois, que estamos rodeados de uma tão grande nuvem de testemunhas, deixemos todo embaraço e o pecado que tão de perto nos rodeia e corramos, com paciência, a carreira que nos está proposta," },
{name:'58122',l:'58',c:'12',v:'2',texto:"olhando para Jesus, autor e consumador da fé, o qual, pelo gozo que lhe estava proposto, suportou a cruz, desprezando a afronta, e assentou-se à destra do trono de Deus." },
{name:'58123',l:'58',c:'12',v:'3',texto:"Considerai, pois, aquele que suportou tais contradições dos pecadores contra si mesmo, para que não enfraqueçais, desfalecendo em vossos ânimos." },
{name:'58124',l:'58',c:'12',v:'4',texto:"Ainda não resististes até ao sangue, combatendo contra o pecado." },
{name:'58125',l:'58',c:'12',v:'5',texto:"E já vos esquecestes da exortação que argumenta convosco como filhos: Filho meu, não desprezes a correção do Senhor e não desmaies quando, por ele, fores repreendido;" },
{name:'58126',l:'58',c:'12',v:'6',texto:"porque o Senhor corrige o que ama e açoita a qualquer que recebe por filho." },
{name:'58127',l:'58',c:'12',v:'7',texto:"Se suportais a correção, Deus vos trata como filhos; porque que filho há a quem o pai não corrija?" },
{name:'58128',l:'58',c:'12',v:'8',texto:"Mas, se estais sem disciplina, da qual todos são feitos participantes, sois, então, bastardos e não filhos." },
{name:'58129',l:'58',c:'12',v:'9',texto:"Além do que, tivemos nossos pais segundo a carne, para nos corrigirem, e nós os reverenciamos; não nos sujeitaremos muito mais ao Pai dos espíritos, para vivermos?" },
{name:'581210',l:'58',c:'12',v:'10',texto:"Porque aqueles, na verdade, por um pouco de tempo, nos corrigiam como bem lhes parecia; mas este, para nosso proveito, para sermos participantes da sua santidade." },
{name:'581211',l:'58',c:'12',v:'11',texto:"E, na verdade, toda correção, ao presente, não parece ser de gozo, senão de tristeza, mas, depois, produz um fruto pacífico de justiça nos exercitados por ela." },
{name:'581212',l:'58',c:'12',v:'12',texto:"Portanto, tornai a levantar as mãos cansadas e os joelhos desconjuntados," },
{name:'581213',l:'58',c:'12',v:'13',texto:"e fazei veredas direitas para os vossos pés, para que o que manqueja se não desvie inteiramente; antes, seja sarado." },
{name:'581214',l:'58',c:'12',v:'14',texto:"Segui a paz com todos e a santificação, sem a qual ninguém verá o Senhor," },
{name:'581215',l:'58',c:'12',v:'15',texto:"tendo cuidado de que ninguém se prive da graça de Deus, e de que nenhuma raiz de amargura, brotando, vos perturbe, e por ela muitos se contaminem." },
{name:'581216',l:'58',c:'12',v:'16',texto:"E ninguém seja fornicador ou profano, como Esaú, que, por um manjar, vendeu o seu direito de primogenitura." },
{name:'581217',l:'58',c:'12',v:'17',texto:"Porque bem sabeis que, querendo ele ainda depois herdar a bênção, foi rejeitado, porque não achou lugar de arrependimento, ainda que, com lágrimas, o buscou." },
{name:'581218',l:'58',c:'12',v:'18',texto:"Porque não chegastes ao monte palpável, aceso em fogo, e à escuridão, e às trevas, e à tempestade," },
{name:'581219',l:'58',c:'12',v:'19',texto:"e ao sonido da trombeta, e à voz das palavras, a qual, os que a ouviram pediram que se lhes não falasse mais;" },
{name:'581220',l:'58',c:'12',v:'20',texto:"porque não podiam suportar o que se lhes mandava: Se até um animal tocar o monte, será apedrejado." },
{name:'581221',l:'58',c:'12',v:'21',texto:"E tão terrível era a visão, que Moisés disse: Estou todo assombrado e tremendo." },
{name:'581222',l:'58',c:'12',v:'22',texto:"Mas chegastes ao monte Sião, e à cidade do Deus vivo, à Jerusalém celestial, e aos muitos milhares de anjos," },
{name:'581223',l:'58',c:'12',v:'23',texto:"à universal assembléia e igreja dos primogênitos, que estão inscritos nos céus, e a Deus, o Juiz de todos, e aos espíritos dos justos aperfeiçoados;" },
{name:'581224',l:'58',c:'12',v:'24',texto:"e a Jesus, o Mediador de uma nova aliança, e ao sangue da aspersão, que fala melhor do que o de Abel." },
{name:'581225',l:'58',c:'12',v:'25',texto:"Vede que não rejeiteis ao que fala; porque, se não escaparam aqueles que rejeitaram o que na terra os advertia, muito menos nós, se nos desviarmos daquele que é dos céus," },
{name:'581226',l:'58',c:'12',v:'26',texto:"a voz do qual moveu, então, a terra, mas, agora, anunciou, dizendo: Ainda uma vez comoverei, não só a terra, senão também o céu." },
{name:'581227',l:'58',c:'12',v:'27',texto:"E esta palavra: Ainda uma vez, mostra a mudança das coisas móveis, como coisas feitas, para que as imóveis permaneçam." },
{name:'581228',l:'58',c:'12',v:'28',texto:"Pelo que, tendo recebido um Reino que não pode ser abalado, retenhamos a graça, pela qual sirvamos a Deus agradavelmente com reverência e piedade;" },
{name:'581229',l:'58',c:'12',v:'29',texto:"porque o nosso Deus é um fogo consumidor." },
],
numVersiculos: 29,
},

c13: {
versiculos:[
{name:'58131',l:'58',c:'13',v:'1',texto:"Permaneça a caridade fraternal." },
{name:'58132',l:'58',c:'13',v:'2',texto:"Não vos esqueçais da hospitalidade, porque, por ela, alguns, não o sabendo, hospedaram anjos." },
{name:'58133',l:'58',c:'13',v:'3',texto:"Lembrai-vos dos presos, como se estivésseis presos com eles, e dos maltratados, como sendo-o vós mesmos também no corpo." },
{name:'58134',l:'58',c:'13',v:'4',texto:"Venerado seja entre todos o matrimônio e o leito sem mácula; porém aos que se dão à prostituição e aos adúlteros Deus os julgará." },
{name:'58135',l:'58',c:'13',v:'5',texto:"Sejam vossos costumes sem avareza, contentando-vos com o que tendes; porque ele disse: Não te deixarei, nem te desampararei." },
{name:'58136',l:'58',c:'13',v:'6',texto:"E, assim, com confiança, ousemos dizer: O Senhor é o meu ajudador, e não temerei o que me possa fazer o homem." },
{name:'58137',l:'58',c:'13',v:'7',texto:"Lembrai-vos dos vossos pastores, que vos falaram a palavra de Deus, a fé dos quais imitai, atentando para a sua maneira de viver." },
{name:'58138',l:'58',c:'13',v:'8',texto:"Jesus Cristo é o mesmo ontem, e hoje, e eternamente." },
{name:'58139',l:'58',c:'13',v:'9',texto:"Não vos deixeis levar em redor por doutrinas várias e estranhas, porque bom é que o coração se fortifique com graça e não com manjares, que de nada aproveitaram aos que a eles se entregaram." },
{name:'581310',l:'58',c:'13',v:'10',texto:"Temos um altar de que não têm direito de comer os que servem ao tabernáculo." },
{name:'581311',l:'58',c:'13',v:'11',texto:"Porque os corpos dos animais cujo sangue é, pelo pecado, trazido pelo sumo sacerdote para o Santuário, são queimados fora do arraial." },
{name:'581312',l:'58',c:'13',v:'12',texto:"E, por isso, também Jesus, para santificar o povo pelo seu próprio sangue, padeceu fora da porta." },
{name:'581313',l:'58',c:'13',v:'13',texto:"Saiamos, pois, a ele fora do arraial, levando o seu vitupério." },
{name:'581314',l:'58',c:'13',v:'14',texto:"Porque não temos aqui cidade permanente, mas buscamos a futura." },
{name:'581315',l:'58',c:'13',v:'15',texto:"Portanto, ofereçamos sempre, por ele, a Deus sacrifício de louvor, isto é, o fruto dos lábios que confessam o seu nome." },
{name:'581316',l:'58',c:'13',v:'16',texto:"E não vos esqueçais da beneficência e comunicação, porque, com tais sacrifícios, Deus se agrada." },
{name:'581317',l:'58',c:'13',v:'17',texto:"Obedecei a vossos pastores e sujeitai-vos a eles; porque velam por vossa alma, como aqueles que hão de dar conta delas; para que o façam com alegria e não gemendo, porque isso não vos seria útil." },
{name:'581318',l:'58',c:'13',v:'18',texto:"Orai por nós, porque confiamos que temos boa consciência, como aqueles que em tudo querem portar-se honestamente." },
{name:'581319',l:'58',c:'13',v:'19',texto:"E rogo-vos, com instância, que assim o façais para que eu mais depressa vos seja restituído." },
{name:'581320',l:'58',c:'13',v:'20',texto:"Ora, o Deus de paz, que pelo sangue do concerto eterno tornou a trazer dos mortos a nosso Senhor Jesus Cristo, grande Pastor das ovelhas," },
{name:'581321',l:'58',c:'13',v:'21',texto:"vos aperfeiçoe em toda a boa obra, para fazerdes a sua vontade, operando em vós o que perante ele é agradável por Cristo Jesus, ao qual seja glória para todo o sempre. Amém!" },
{name:'581322',l:'58',c:'13',v:'22',texto:"Rogo-vos, porém, irmãos, que suporteis a palavra desta exortação; porque abreviadamente vos escrevi." },
{name:'581323',l:'58',c:'13',v:'23',texto:"Sabei que já está solto o irmão Timóteo, com o qual ( se vier depressa ) vos verei." },
{name:'581324',l:'58',c:'13',v:'24',texto:"Saudai todos os vossos chefes e todos os santos. Os da Itália vos saúdam." },
{name:'581325',l:'58',c:'13',v:'25',texto:"A graça seja com todos vós. Amém!" },
],
numVersiculos: 25,
},
	

};
