BibliaJFA.santiago = {
	libro: "Tiago",
	numCapitulos: 5,

c1: {
versiculos:[
{name:'5911',l:'59',c:'1',v:'1',texto:"Tiago, servo de Deus e do Senhor Jesus Cristo, às doze tribos que andam dispersas: saúde." },
{name:'5912',l:'59',c:'1',v:'2',texto:"Meus irmãos, tende grande gozo quando cairdes em várias tentações," },
{name:'5913',l:'59',c:'1',v:'3',texto:"sabendo que a prova da vossa fé produz a paciência." },
{name:'5914',l:'59',c:'1',v:'4',texto:"Tenha, porém, a paciência a sua obra perfeita, para que sejais perfeitos e completos, sem faltar em coisa alguma." },
{name:'5915',l:'59',c:'1',v:'5',texto:"E, se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente e não o lança em rosto; e ser-lhe-á dada." },
{name:'5916',l:'59',c:'1',v:'6',texto:"Peça-a, porém, com fé, não duvidando; porque o que duvida é semelhante à onda do mar, que é levada pelo vento e lançada de uma para outra parte." },
{name:'5917',l:'59',c:'1',v:'7',texto:"Não pense tal homem que receberá do Senhor alguma coisa." },
{name:'5918',l:'59',c:'1',v:'8',texto:"O homem de coração dobre é inconstante em todos os seus caminhos." },
{name:'5919',l:'59',c:'1',v:'9',texto:"Mas glorie-se o irmão abatido na sua exaltação," },
{name:'59110',l:'59',c:'1',v:'10',texto:"e o rico, em seu abatimento, porque ele passará como a flor da erva." },
{name:'59111',l:'59',c:'1',v:'11',texto:"Porque sai o sol com ardor, e a erva seca, e a sua flor cai, e a formosa aparência do seu aspecto perece; assim se murchará também o rico em seus caminhos." },
{name:'59112',l:'59',c:'1',v:'12',texto:"Bem-aventurado o varão que sofre a tentação; porque, quando for provado, receberá a coroa da vida, a qual o Senhor tem prometido aos que o amam." },
{name:'59113',l:'59',c:'1',v:'13',texto:"Ninguém, sendo tentado, diga: De Deus sou tentado; porque Deus não pode ser tentado pelo mal e a ninguém tenta." },
{name:'59114',l:'59',c:'1',v:'14',texto:"Mas cada um é tentado, quando atraído e engodado pela sua própria concupiscência." },
{name:'59115',l:'59',c:'1',v:'15',texto:"Depois, havendo a concupiscência concebido, dá à luz o pecado; e o pecado, sendo consumado, gera a morte." },
{name:'59116',l:'59',c:'1',v:'16',texto:"Não erreis, meus amados irmãos." },
{name:'59117',l:'59',c:'1',v:'17',texto:"Toda boa dádiva e todo dom perfeito vêm do alto, descendo do Pai das luzes, em quem não há mudança, nem sombra de variação." },
{name:'59118',l:'59',c:'1',v:'18',texto:"Segundo a sua vontade, ele nos gerou pela palavra da verdade, para que fôssemos como primícias das suas criaturas." },
{name:'59119',l:'59',c:'1',v:'19',texto:"Sabeis isto, meus amados irmãos; mas todo o homem seja pronto para ouvir, tardio para falar, tardio para se irar." },
{name:'59120',l:'59',c:'1',v:'20',texto:"Porque a ira do homem não opera a justiça de Deus." },
{name:'59121',l:'59',c:'1',v:'21',texto:"Pelo que, rejeitando toda imundícia e acúmulo de malícia, recebei com mansidão a palavra em vós enxertada, a qual pode salvar a vossa alma." },
{name:'59122',l:'59',c:'1',v:'22',texto:"E sede cumpridores da palavra e não somente ouvintes, enganando-vos com falsos discursos." },
{name:'59123',l:'59',c:'1',v:'23',texto:"Porque, se alguém é ouvinte da palavra e não cumpridor, é semelhante ao varão que contempla ao espelho o seu rosto natural;" },
{name:'59124',l:'59',c:'1',v:'24',texto:"porque se contempla a si mesmo, e foi-se, e logo se esqueceu de como era." },
{name:'59125',l:'59',c:'1',v:'25',texto:"Aquele, porém, que atenta bem para a lei perfeita da liberdade e nisso persevera, não sendo ouvinte esquecido, mas fazedor da obra, este tal será bem-aventurado no seu feito." },
{name:'59126',l:'59',c:'1',v:'26',texto:"Se alguém entre vós cuida ser religioso e não refreia a sua língua, antes, engana o seu coração, a religião desse é vã." },
{name:'59127',l:'59',c:'1',v:'27',texto:"A religião pura e imaculada para com Deus, o Pai, é esta: visitar os órfãos e as viúvas nas suas tribulações e guardar-se da corrupção do mundo." },
],
numVersiculos: 27,
},

c2: {
versiculos:[
{name:'5921',l:'59',c:'2',v:'1',texto:"Meus irmãos, não tenhais a fé de nosso Senhor Jesus Cristo, Senhor da glória, em acepção de pessoas." },
{name:'5922',l:'59',c:'2',v:'2',texto:"Porque, se no vosso ajuntamento entrar algum homem com anel de ouro no dedo, com vestes preciosas, e entrar também algum pobre com sórdida vestimenta," },
{name:'5923',l:'59',c:'2',v:'3',texto:"e atentardes para o que traz a veste preciosa e lhe disserdes: Assenta-te tu aqui, num lugar de honra, e disserdes ao pobre: Tu, fica aí em pé ou assenta-te abaixo do meu estrado," },
{name:'5924',l:'59',c:'2',v:'4',texto:"porventura não fizestes distinção dentro de vós mesmos e não vos fizestes juízes de maus pensamentos?" },
{name:'5925',l:'59',c:'2',v:'5',texto:"Ouvi, meus amados irmãos. Porventura, não escolheu Deus aos pobres deste mundo para serem ricos na fé e herdeiros do Reino que prometeu aos que o amam?" },
{name:'5926',l:'59',c:'2',v:'6',texto:"Mas vós desonrastes o pobre. Porventura, não vos oprimem os ricos e não vos arrastam aos tribunais?" },
{name:'5927',l:'59',c:'2',v:'7',texto:"Porventura, não blasfemam eles o bom nome que sobre vós foi invocado?" },
{name:'5928',l:'59',c:'2',v:'8',texto:"Todavia, se cumprirdes, conforme a Escritura, a lei real: Amarás a teu próximo como a ti mesmo, bem fazeis." },
{name:'5929',l:'59',c:'2',v:'9',texto:"Mas, se fazeis acepção de pessoas, cometeis pecado e sois redargüidos pela lei como transgressores." },
{name:'59210',l:'59',c:'2',v:'10',texto:"Porque qualquer que guardar toda a lei e tropeçar em um só ponto tornou-se culpado de todos." },
{name:'59211',l:'59',c:'2',v:'11',texto:"Porque aquele que disse: Não cometerás adultério, também disse: Não matarás. Se tu, pois, não cometeres adultério, mas matares, estás feito transgressor da lei." },
{name:'59212',l:'59',c:'2',v:'12',texto:"Assim falai e assim procedei, como devendo ser julgados pela lei da liberdade." },
{name:'59213',l:'59',c:'2',v:'13',texto:"Porque o juízo será sem misericórdia sobre aquele que não fez misericórdia; e a misericórdia triunfa sobre o juízo." },
{name:'59214',l:'59',c:'2',v:'14',texto:"Meus irmãos, que aproveita se alguém disser que tem fé e não tiver as obras? Porventura, a fé pode salvá-lo?" },
{name:'59215',l:'59',c:'2',v:'15',texto:"E, se o irmão ou a irmã estiverem nus e tiverem falta de mantimento cotidiano," },
{name:'59216',l:'59',c:'2',v:'16',texto:"e algum de vós lhes disser: Ide em paz, aquentai-vos e fartai-vos; e lhes não derdes as coisas necessárias para o corpo, que proveito virá daí?" },
{name:'59217',l:'59',c:'2',v:'17',texto:"Assim também a fé, se não tiver as obras, é morta em si mesma." },
{name:'59218',l:'59',c:'2',v:'18',texto:"Mas dirá alguém: Tu tens a fé, e eu tenho as obras; mostra-me a tua fé sem as tuas obras, e eu te mostrarei a minha fé pelas minhas obras." },
{name:'59219',l:'59',c:'2',v:'19',texto:"Tu crês que há um só Deus? Fazes bem; também os demônios o crêem e estremecem." },
{name:'59220',l:'59',c:'2',v:'20',texto:"Mas, ó homem vão, queres tu saber que a fé sem as obras é morta?" },
{name:'59221',l:'59',c:'2',v:'21',texto:"Porventura Abraão, o nosso pai, não foi justificado pelas obras, quando ofereceu sobre o altar o seu filho Isaque?" },
{name:'59222',l:'59',c:'2',v:'22',texto:"Bem vês que a fé cooperou com as suas obras e que, pelas obras, a fé foi aperfeiçoada," },
{name:'59223',l:'59',c:'2',v:'23',texto:"e cumpriu-se a Escritura, que diz: E creu Abraão em Deus, e foi-lhe isso imputado como justiça, e foi chamado o amigo de Deus." },
{name:'59224',l:'59',c:'2',v:'24',texto:"Vedes, então, que o homem é justificado pelas obras e não somente pela fé." },
{name:'59225',l:'59',c:'2',v:'25',texto:"E de igual modo Raabe, a meretriz, não foi também justificada pelas obras, quando recolheu os emissários e os despediu por outro caminho?" },
{name:'59226',l:'59',c:'2',v:'26',texto:"Porque, assim como o corpo sem o espírito está morto, assim também a fé sem obras é morta." },
],
numVersiculos: 26,
},

c3: {
versiculos:[
{name:'5931',l:'59',c:'3',v:'1',texto:"Meus irmãos, muitos de vós não sejam mestres, sabendo que receberemos mais duro juízo." },
{name:'5932',l:'59',c:'3',v:'2',texto:"Porque todos tropeçamos em muitas coisas. Se alguém não tropeça em palavra, o tal varão é perfeito e poderoso para também refrear todo o corpo." },
{name:'5933',l:'59',c:'3',v:'3',texto:"Ora, nós pomos freio nas bocas dos cavalos, para que nos obedeçam; e conseguimos dirigir todo o seu corpo." },
{name:'5934',l:'59',c:'3',v:'4',texto:"Vede também as naus que, sendo tão grandes e levadas de impetuosos ventos, se viram com um bem pequeno leme para onde quer a vontade daquele que as governa." },
{name:'5935',l:'59',c:'3',v:'5',texto:"Assim também a língua é um pequeno membro e gloria-se de grandes coisas. Vede quão grande bosque um pequeno fogo incendeia." },
{name:'5936',l:'59',c:'3',v:'6',texto:"A língua também é um fogo; como mundo de iniqüidade, a língua está posta entre os nossos membros, e contamina todo o corpo, e inflama o curso da natureza, e é inflamada pelo inferno." },
{name:'5937',l:'59',c:'3',v:'7',texto:"Porque toda a natureza, tanto de bestas-feras como de aves, tanto de répteis como de animais do mar, se amansa e foi domada pela natureza humana;" },
{name:'5938',l:'59',c:'3',v:'8',texto:"mas nenhum homem pode domar a língua. É um mal que não se pode refrear; está cheia de peçonha mortal." },
{name:'5939',l:'59',c:'3',v:'9',texto:"Com ela bendizemos a Deus e Pai, e com ela amaldiçoamos os homens, feitos à semelhança de Deus:" },
{name:'59310',l:'59',c:'3',v:'10',texto:"de uma mesma boca procede bênção e maldição. Meus irmãos, não convém que isto se faça assim." },
{name:'59311',l:'59',c:'3',v:'11',texto:"Porventura, deita alguma fonte de um mesmo manancial água doce e água amargosa?" },
{name:'59312',l:'59',c:'3',v:'12',texto:"Meus irmãos, pode também a figueira produzir azeitonas ou a videira, figos? Assim, tampouco pode uma fonte dar água salgada e doce." },
{name:'59313',l:'59',c:'3',v:'13',texto:"Quem dentre vós é sábio e inteligente? Mostre, pelo seu bom trato, as suas obras em mansidão de sabedoria." },
{name:'59314',l:'59',c:'3',v:'14',texto:"Mas, se tendes amarga inveja e sentimento faccioso em vosso coração, não vos glorieis, nem mintais contra a verdade." },
{name:'59315',l:'59',c:'3',v:'15',texto:"Essa não é a sabedoria que vem do alto, mas é terrena, animal e diabólica." },
{name:'59316',l:'59',c:'3',v:'16',texto:"Porque, onde há inveja e espírito faccioso, aí há perturbação e toda obra perversa." },
{name:'59317',l:'59',c:'3',v:'17',texto:"Mas a sabedoria que vem do alto é, primeiramente, pura, depois, pacífica, moderada, tratável, cheia de misericórdia e de bons frutos, sem parcialidade e sem hipocrisia." },
{name:'59318',l:'59',c:'3',v:'18',texto:"Ora, o fruto da justiça semeia-se na paz, para os que exercitam a paz." },
],
numVersiculos: 18,
},

c4: {
versiculos:[
{name:'5941',l:'59',c:'4',v:'1',texto:"Donde vêm as guerras e pelejas entre vós? Porventura, não vêm disto, a saber, dos vossos deleites, que nos vossos membros guerreiam?" },
{name:'5942',l:'59',c:'4',v:'2',texto:"Cobiçais e nada tendes; sois invejosos e cobiçosos e não podeis alcançar; combateis e guerreais e nada tendes, porque não pedis." },
{name:'5943',l:'59',c:'4',v:'3',texto:"Pedis e não recebeis, porque pedis mal, para o gastardes em vossos deleites." },
{name:'5944',l:'59',c:'4',v:'4',texto:"Adúlteros e adúlteras, não sabeis vós que a amizade do mundo é inimizade contra Deus? Portanto, qualquer que quiser ser amigo do mundo constitui-se inimigo de Deus." },
{name:'5945',l:'59',c:'4',v:'5',texto:"Ou cuidais vós que em vão diz a Escritura: O Espírito que em nós habita tem ciúmes?" },
{name:'5946',l:'59',c:'4',v:'6',texto:"Antes, dá maior graça. Portanto, diz: Deus resiste aos soberbos, dá, porém, graça aos humildes." },
{name:'5947',l:'59',c:'4',v:'7',texto:"Sujeitai-vos, pois, a Deus; resisti ao diabo, e ele fugirá de vós." },
{name:'5948',l:'59',c:'4',v:'8',texto:"Chegai-vos a Deus, e ele se chegará a vós. Limpai as mãos, pecadores; e, vós de duplo ânimo, purificai o coração." },
{name:'5949',l:'59',c:'4',v:'9',texto:"Senti as vossas misérias, e lamentai, e chorai; converta-se o vosso riso em pranto, e o vosso gozo, em tristeza." },
{name:'59410',l:'59',c:'4',v:'10',texto:"Humilhai-vos perante o Senhor, e ele vos exaltará." },
{name:'59411',l:'59',c:'4',v:'11',texto:"Irmãos, não faleis mal uns dos outros. Quem fala mal de um irmão e julga a seu irmão fala mal da lei e julga a lei; e, se tu julgas a lei, já não és observador da lei, mas juiz." },
{name:'59412',l:'59',c:'4',v:'12',texto:"Há só um Legislador e um Juiz, que pode salvar e destruir. Tu, porém, quem és, que julgas a outrem?" },
{name:'59413',l:'59',c:'4',v:'13',texto:"Eia, agora, vós que dizeis: Hoje ou amanhã, iremos a tal cidade, e lá passaremos um ano, e contrataremos, e ganharemos." },
{name:'59414',l:'59',c:'4',v:'14',texto:"Digo-vos que não sabeis o que acontecerá amanhã. Porque que é a vossa vida? É um vapor que aparece por um pouco e depois se desvanece." },
{name:'59415',l:'59',c:'4',v:'15',texto:"Em lugar do que devíeis dizer: Se o Senhor quiser, e se vivermos, faremos isto ou aquilo." },
{name:'59416',l:'59',c:'4',v:'16',texto:"Mas, agora, vos gloriais em vossas presunções; toda glória tal como esta é maligna." },
{name:'59417',l:'59',c:'4',v:'17',texto:"Aquele, pois, que sabe fazer o bem e o não faz comete pecado." },
],
numVersiculos: 17,
},

c5: {
versiculos:[
{name:'5951',l:'59',c:'5',v:'1',texto:"Eia, pois, agora vós, ricos, chorai e pranteai por vossas misérias, que sobre vós hão de vir." },
{name:'5952',l:'59',c:'5',v:'2',texto:"As vossas riquezas estão apodrecidas, e as vossas vestes estão comidas da traça." },
{name:'5953',l:'59',c:'5',v:'3',texto:"O vosso ouro e a vossa prata se enferrujaram; e a sua ferrugem dará testemunho contra vós e comerá como fogo a vossa carne. Entesourastes para os últimos dias." },
{name:'5954',l:'59',c:'5',v:'4',texto:"Eis que o salário dos trabalhadores que ceifaram as vossas terras e que por vós foi diminuído clama; e os clamores dos que ceifaram entraram nos ouvidos do Senhor dos Exércitos." },
{name:'5955',l:'59',c:'5',v:'5',texto:"Deliciosamente, vivestes sobre a terra, e vos deleitastes, e cevastes o vosso coração, como num dia de matança." },
{name:'5956',l:'59',c:'5',v:'6',texto:"Condenastes e matastes o justo; ele não vos resistiu." },
{name:'5957',l:'59',c:'5',v:'7',texto:"Sede, pois, irmãos, pacientes até a vinda do Senhor. Eis que o lavrador espera o precioso fruto da terra, aguardando-o com paciência, até que receba a chuva temporã e serôdia." },
{name:'5958',l:'59',c:'5',v:'8',texto:"Sede vós também pacientes, fortalecei o vosso coração, porque já a vinda do Senhor está próxima." },
{name:'5959',l:'59',c:'5',v:'9',texto:"Irmãos, não vos queixeis uns contra os outros, para que não sejais condenados. Eis que o juiz está à porta." },
{name:'59510',l:'59',c:'5',v:'10',texto:"Meus irmãos, tomai por exemplo de aflição e paciência os profetas que falaram em nome do Senhor." },
{name:'59511',l:'59',c:'5',v:'11',texto:"Eis que temos por bem-aventurados os que sofreram. Ouvistes qual foi a paciência de Jó e vistes o fim que o Senhor lhe deu; porque o Senhor é muito misericordioso e piedoso." },
{name:'59512',l:'59',c:'5',v:'12',texto:"Mas, sobretudo, meus irmãos, não jureis nem pelo céu nem pela terra, nem façais qualquer outro juramento; mas que a vossa palavra seja sim, sim e não, não, para que não caiais em condenação." },
{name:'59513',l:'59',c:'5',v:'13',texto:"Está alguém entre vós aflito? Ore. Está alguém contente? Cante louvores." },
{name:'59514',l:'59',c:'5',v:'14',texto:"Está alguém entre vós doente? Chame os presbíteros da igreja, e orem sobre ele, ungindo-o com azeite em nome do Senhor;" },
{name:'59515',l:'59',c:'5',v:'15',texto:"e a oração da fé salvará o doente, e o Senhor o levantará; e, se houver cometido pecados, ser-lhe-ão perdoados." },
{name:'59516',l:'59',c:'5',v:'16',texto:"Confessai as vossas culpas uns aos outros e orai uns pelos outros, para que sareis; a oração feita por um justo pode muito em seus efeitos." },
{name:'59517',l:'59',c:'5',v:'17',texto:"Elias era homem sujeito às mesmas paixões que nós e, orando, pediu que não chovesse, e, por três anos e seis meses, não choveu sobre a terra." },
{name:'59518',l:'59',c:'5',v:'18',texto:"E orou outra vez, e o céu deu chuva, e a terra produziu o seu fruto." },
{name:'59519',l:'59',c:'5',v:'19',texto:"Irmãos, se algum de entre vós se tem desviado da verdade, e alguém o converter," },
{name:'59520',l:'59',c:'5',v:'20',texto:"saiba que aquele que fizer converter do erro do seu caminho um pecador salvará da morte uma alma e cobrirá uma multidão de pecados." },
],
numVersiculos: 20,
},
	

};
