BibliaJFA.pedro2 = {
	libro: "2 Pedro",
	numCapitulos: 3,

c1: {
versiculos:[
{name:'6111',l:'61',c:'1',v:'1',texto:"Simão Pedro, servo e apóstolo de Jesus Cristo, aos que conosco alcançaram fé igualmente preciosa pela justiça do nosso Deus e Salvador Jesus Cristo:" },
{name:'6112',l:'61',c:'1',v:'2',texto:"graça e paz vos sejam multiplicadas, pelo conhecimento de Deus e de Jesus, nosso Senhor." },
{name:'6113',l:'61',c:'1',v:'3',texto:"Visto como o seu divino poder nos deu tudo o que diz respeito à vida e piedade, pelo conhecimento daquele que nos chamou por sua glória e virtude," },
{name:'6114',l:'61',c:'1',v:'4',texto:"pelas quais ele nos tem dado grandíssimas e preciosas promessas, para que por elas fiqueis participantes da natureza divina, havendo escapado da corrupção, que, pela concupiscência, há no mundo," },
{name:'6115',l:'61',c:'1',v:'5',texto:"e vós também, pondo nisto mesmo toda a diligência, acrescentai à vossa fé a virtude, e à virtude, a ciência," },
{name:'6116',l:'61',c:'1',v:'6',texto:"e à ciência, a temperança, e à temperança, a paciência, e à paciência, a piedade," },
{name:'6117',l:'61',c:'1',v:'7',texto:"e à piedade, o amor fraternal, e ao amor fraternal, a caridade." },
{name:'6118',l:'61',c:'1',v:'8',texto:"Porque, se em vós houver e aumentarem estas coisas, não vos deixarão ociosos nem estéreis no conhecimento de nosso Senhor Jesus Cristo." },
{name:'6119',l:'61',c:'1',v:'9',texto:"Pois aquele em quem não há estas coisas é cego, nada vendo ao longe, havendo-se esquecido da purificação dos seus antigos pecados." },
{name:'61110',l:'61',c:'1',v:'10',texto:"Portanto, irmãos, procurai fazer cada vez mais firme a vossa vocação e eleição; porque, fazendo isto, nunca jamais tropeçareis." },
{name:'61111',l:'61',c:'1',v:'11',texto:"Porque assim vos será amplamente concedida a entrada no Reino eterno de nosso Senhor e Salvador Jesus Cristo." },
{name:'61112',l:'61',c:'1',v:'12',texto:"Pelo que não deixarei de exortar-vos sempre acerca destas coisas, ainda que bem as saibais e estejais confirmados na presente verdade." },
{name:'61113',l:'61',c:'1',v:'13',texto:"E tenho por justo, enquanto estiver neste tabernáculo, despertar-vos com admoestações," },
{name:'61114',l:'61',c:'1',v:'14',texto:"sabendo que brevemente hei de deixar este meu tabernáculo, como também nosso Senhor Jesus Cristo já mo tem revelado." },
{name:'61115',l:'61',c:'1',v:'15',texto:"Mas também eu procurarei, em toda a ocasião, que depois da minha morte tenhais lembrança destas coisas." },
{name:'61116',l:'61',c:'1',v:'16',texto:"Porque não vos fizemos saber a virtude e a vinda de nosso Senhor Jesus Cristo, seguindo fábulas artificialmente compostas, mas nós mesmos vimos a sua majestade," },
{name:'61117',l:'61',c:'1',v:'17',texto:"porquanto ele recebeu de Deus Pai honra e glória, quando da magnífica glória lhe foi dirigida a seguinte voz: Este é o meu Filho amado, em quem me tenho comprazido." },
{name:'61118',l:'61',c:'1',v:'18',texto:"E ouvimos esta voz dirigida do céu, estando nós com ele no monte santo." },
{name:'61119',l:'61',c:'1',v:'19',texto:"E temos, mui firme, a palavra dos profetas, à qual bem fazeis em estar atentos, como a uma luz que alumia em lugar escuro, até que o dia esclareça, e a estrela da alva apareça em vosso coração," },
{name:'61120',l:'61',c:'1',v:'20',texto:"sabendo primeiramente isto: que nenhuma profecia da Escritura é de particular interpretação;" },
{name:'61121',l:'61',c:'1',v:'21',texto:"porque a profecia nunca foi produzida por vontade de homem algum, mas os homens santos de Deus falaram inspirados pelo Espírito Santo." },
],
numVersiculos: 21,
},

c2: {
versiculos:[
{name:'6121',l:'61',c:'2',v:'1',texto:"E também houve entre o povo falsos profetas, como entre vós haverá também falsos doutores, que introduzirão encobertamente heresias de perdição e negarão o Senhor que os resgatou, trazendo sobre si mesmos repentina perdição." },
{name:'6122',l:'61',c:'2',v:'2',texto:"E muitos seguirão as suas dissoluções, pelos quais será blasfemado o caminho da verdade;" },
{name:'6123',l:'61',c:'2',v:'3',texto:"e, por avareza, farão de vós negócio com palavras fingidas; sobre os quais já de largo tempo não será tardia a sentença, e a sua perdição não dormita." },
{name:'6124',l:'61',c:'2',v:'4',texto:"Porque, se Deus não perdoou aos anjos que pecaram, mas, havendo-os lançado no inferno, os entregou às cadeias da escuridão, ficando reservados para o Juízo;" },
{name:'6125',l:'61',c:'2',v:'5',texto:"e não perdoou ao mundo antigo, mas guardou a Noé, pregoeiro da justiça, com mais sete pessoas, ao trazer o dilúvio sobre o mundo dos ímpios;" },
{name:'6126',l:'61',c:'2',v:'6',texto:"e condenou à subversão as cidades de Sodoma e Gomorra, reduzindo-as a cinza e pondo-as para exemplo aos que vivessem impiamente;" },
{name:'6127',l:'61',c:'2',v:'7',texto:"e livrou o justo Ló, enfadado da vida dissoluta dos homens abomináveis" },
{name:'6128',l:'61',c:'2',v:'8',texto:"( porque este justo, habitando entre eles, afligia todos os dias a sua alma justa, pelo que via e ouvia sobre as suas obras injustas )." },
{name:'6129',l:'61',c:'2',v:'9',texto:"Assim, sabe o Senhor livrar da tentação os piedosos e reservar os injustos para o Dia de Juízo, para serem castigados," },
{name:'61210',l:'61',c:'2',v:'10',texto:"mas principalmente aqueles que segundo a carne andam em concupiscências de imundícia e desprezam as dominações. Atrevidos, obstinados, não receiam blasfemar das autoridades;" },
{name:'61211',l:'61',c:'2',v:'11',texto:"enquanto os anjos, sendo maiores em força e poder, não pronunciam contra eles juízo blasfemo diante do Senhor." },
{name:'61212',l:'61',c:'2',v:'12',texto:"Mas estes, como animais irracionais, que seguem a natureza, feitos para serem presos e mortos, blasfemando do que não entendem, perecerão na sua corrupção," },
{name:'61213',l:'61',c:'2',v:'13',texto:"recebendo o galardão da injustiça; pois que tais homens têm prazer nos deleites cotidianos; nódoas são eles e máculas, deleitando-se em seus enganos, quando se banqueteiam convosco;" },
{name:'61214',l:'61',c:'2',v:'14',texto:"tendo os olhos cheios de adultério e não cessando de pecar, engodando as almas inconstantes, tendo o coração exercitado na avareza, filhos de maldição;" },
{name:'61215',l:'61',c:'2',v:'15',texto:"os quais, deixando o caminho direito, erraram seguindo o caminho de Balaão, filho de Beor, que amou o prêmio da injustiça." },
{name:'61216',l:'61',c:'2',v:'16',texto:"Mas teve a repreensão da sua transgressão; o mudo jumento, falando com voz humana, impediu a loucura do profeta." },
{name:'61217',l:'61',c:'2',v:'17',texto:"Estes são fontes sem água, nuvens levadas pela força do vento, para os quais a escuridão das trevas eternamente se reserva;" },
{name:'61218',l:'61',c:'2',v:'18',texto:"porque, falando coisas mui arrogantes de vaidades, engodam com as concupiscências da carne e com dissoluções aqueles que se estavam afastando dos que andam em erro," },
{name:'61219',l:'61',c:'2',v:'19',texto:"prometendo-lhes liberdade, sendo eles mesmos servos da corrupção. Porque de quem alguém é vencido, do tal faz-se também servo." },
{name:'61220',l:'61',c:'2',v:'20',texto:"Porquanto se, depois de terem escapado das corrupções do mundo, pelo conhecimento do Senhor e Salvador Jesus Cristo, forem outra vez envolvidos nelas e vencidos, tornou-se-lhes o último estado pior do que o primeiro." },
{name:'61221',l:'61',c:'2',v:'21',texto:"Porque melhor lhes fora não conhecerem o caminho da justiça do que, conhecendo-o, desviarem-se do santo mandamento que lhes fora dado." },
{name:'61222',l:'61',c:'2',v:'22',texto:"Deste modo, sobreveio-lhes o que por um verdadeiro provérbio se diz: O cão voltou ao seu próprio vômito; a porca lavada, ao espojadouro de lama." },
],
numVersiculos: 22,
},

c3: {
versiculos:[
{name:'6131',l:'61',c:'3',v:'1',texto:"Amados, escrevo-vos, agora, esta segunda carta, em ambas as quais desperto com exortação o vosso ânimo sincero," },
{name:'6132',l:'61',c:'3',v:'2',texto:"para que vos lembreis das palavras que primeiramente foram ditas pelos santos profetas e do mandamento do Senhor e Salvador, mediante os vossos apóstolos," },
{name:'6133',l:'61',c:'3',v:'3',texto:"sabendo primeiro isto: que nos últimos dias virão escarnecedores, andando segundo as suas próprias concupiscências" },
{name:'6134',l:'61',c:'3',v:'4',texto:"e dizendo: Onde está a promessa da sua vinda? Porque desde que os pais dormiram todas as coisas permanecem como desde o princípio da criação." },
{name:'6135',l:'61',c:'3',v:'5',texto:"Eles voluntariamente ignoram isto: que pela palavra de Deus já desde a antiguidade existiram os céus e a terra, que foi tirada da água e no meio da água subsiste;" },
{name:'6136',l:'61',c:'3',v:'6',texto:"pelas quais coisas pereceu o mundo de então, coberto com as águas do dilúvio." },
{name:'6137',l:'61',c:'3',v:'7',texto:"Mas os céus e a terra que agora existem pela mesma palavra se reservam como tesouro e se guardam para o fogo, até o Dia do Juízo e da perdição dos homens ímpios." },
{name:'6138',l:'61',c:'3',v:'8',texto:"Mas, amados, não ignoreis uma coisa: que um dia para o Senhor é como mil anos, e mil anos, como um dia." },
{name:'6139',l:'61',c:'3',v:'9',texto:"O Senhor não retarda a sua promessa, ainda que alguns a têm por tardia; mas é longânimo para convosco, não querendo que alguns se percam, senão que todos venham a arrepender-se." },
{name:'61310',l:'61',c:'3',v:'10',texto:"Mas o Dia do Senhor virá como o ladrão de noite, no qual os céus passarão com grande estrondo, e os elementos, ardendo, se desfarão, e a terra e as obras que nela há se queimarão." },
{name:'61311',l:'61',c:'3',v:'11',texto:"Havendo, pois, de perecer todas estas coisas, que pessoas vos convém ser em santo trato e piedade," },
{name:'61312',l:'61',c:'3',v:'12',texto:"aguardando e apressando-vos para a vinda do Dia de Deus, em que os céus, em fogo, se desfarão, e os elementos, ardendo, se fundirão?" },
{name:'61313',l:'61',c:'3',v:'13',texto:"Mas nós, segundo a sua promessa, aguardamos novos céus e nova terra, em que habita a justiça." },
{name:'61314',l:'61',c:'3',v:'14',texto:"Pelo que, amados, aguardando estas coisas, procurai que dele sejais achados imaculados e irrepreensíveis em paz" },
{name:'61315',l:'61',c:'3',v:'15',texto:"e tende por salvação a longanimidade de nosso Senhor, como também o nosso amado irmão Paulo vos escreveu, segundo a sabedoria que lhe foi dada," },
{name:'61316',l:'61',c:'3',v:'16',texto:"falando disto, como em todas as suas epístolas, entre as quais há pontos difíceis de entender, que os indoutos e inconstantes torcem e igualmente as outras Escrituras, para sua própria perdição." },
{name:'61317',l:'61',c:'3',v:'17',texto:"Vós, portanto, amados, sabendo isto de antemão, guardai-vos de que, pelo engano dos homens abomináveis, sejais juntamente arrebatados e descaiais da vossa firmeza;" },
{name:'61318',l:'61',c:'3',v:'18',texto:"antes, crescei na graça e conhecimento de nosso Senhor e Salvador Jesus Cristo. A ele seja dada a glória, assim agora como no dia da eternidade. Amém!" },
],
numVersiculos: 18,
},
	

};
