BibliaJFA.juan1 = {
	libro: "1 João",
	numCapitulos: 5,

c1: {
versiculos:[
{name:'6211',l:'62',c:'1',v:'1',texto:"O que era desde o princípio, o que vimos com os nossos olhos, o que temos contemplado, e as nossas mãos tocaram da Palavra da vida" },
{name:'6212',l:'62',c:'1',v:'2',texto:"( porque a vida foi manifestada, e nós a vimos, e testificamos dela, e vos anunciamos a vida eterna, que estava com o Pai e nos foi manifestada )," },
{name:'6213',l:'62',c:'1',v:'3',texto:"o que vimos e ouvimos, isso vos anunciamos, para que também tenhais comunhão conosco; e a nossa comunhão é com o Pai e com seu Filho Jesus Cristo." },
{name:'6214',l:'62',c:'1',v:'4',texto:"Estas coisas vos escrevemos, para que o vosso gozo se cumpra." },
{name:'6215',l:'62',c:'1',v:'5',texto:"E esta é a mensagem que dele ouvimos e vos anunciamos: que Deus é luz, e não há nele treva nenhuma." },
{name:'6216',l:'62',c:'1',v:'6',texto:"Se dissermos que temos comunhão com ele e andarmos em trevas, mentimos e não praticamos a verdade." },
{name:'6217',l:'62',c:'1',v:'7',texto:"Mas, se andarmos na luz, como ele na luz está, temos comunhão uns com os outros, e o sangue de Jesus Cristo, seu Filho, nos purifica de todo pecado." },
{name:'6218',l:'62',c:'1',v:'8',texto:"Se dissermos que não temos pecado, enganamo-nos a nós mesmos, e não há verdade em nós." },
{name:'6219',l:'62',c:'1',v:'9',texto:"Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça." },
{name:'62110',l:'62',c:'1',v:'10',texto:"Se dissermos que não pecamos, fazemo-lo mentiroso, e a sua palavra não está em nós." },
],
numVersiculos: 10,
},

c2: {
versiculos:[
{name:'6221',l:'62',c:'2',v:'1',texto:"Meus filhinhos, estas coisas vos escrevo para que não pequeis; e, se alguém pecar, temos um Advogado para com o Pai, Jesus Cristo, o Justo." },
{name:'6222',l:'62',c:'2',v:'2',texto:"E ele é a propiciação pelos nossos pecados e não somente pelos nossos, mas também pelos de todo o mundo." },
{name:'6223',l:'62',c:'2',v:'3',texto:"E nisto sabemos que o conhecemos: se guardarmos os seus mandamentos." },
{name:'6224',l:'62',c:'2',v:'4',texto:"Aquele que diz: Eu conheço-o e não guarda os seus mandamentos é mentiroso, e nele não está a verdade." },
{name:'6225',l:'62',c:'2',v:'5',texto:"Mas qualquer que guarda a sua palavra, o amor de Deus está nele verdadeiramente aperfeiçoado; nisto conhecemos que estamos nele." },
{name:'6226',l:'62',c:'2',v:'6',texto:"Aquele que diz que está nele também deve andar como ele andou." },
{name:'6227',l:'62',c:'2',v:'7',texto:"Irmãos, não vos escrevo mandamento novo, mas o mandamento antigo, que desde o princípio tivestes. Este mandamento antigo é a palavra que desde o princípio ouvistes." },
{name:'6228',l:'62',c:'2',v:'8',texto:"Outra vez vos escrevo um mandamento novo, que é verdadeiro nele e em vós; porque vão passando as trevas, e já a verdadeira luz alumia." },
{name:'6229',l:'62',c:'2',v:'9',texto:"Aquele que diz que está na luz e aborrece a seu irmão até agora está em trevas." },
{name:'62210',l:'62',c:'2',v:'10',texto:"Aquele que ama a seu irmão está na luz, e nele não há escândalo." },
{name:'62211',l:'62',c:'2',v:'11',texto:"Mas aquele que aborrece a seu irmão está em trevas, e anda em trevas, e não sabe para onde deva ir; porque as trevas lhe cegaram os olhos." },
{name:'62212',l:'62',c:'2',v:'12',texto:"Filhinhos, escrevo-vos porque, pelo seu nome, vos são perdoados os pecados." },
{name:'62213',l:'62',c:'2',v:'13',texto:"Pais, escrevo-vos, porque conhecestes aquele que é desde o princípio. Jovens, escrevo-vos, porque vencestes o maligno. Eu vos escrevi, filhos, porque conhecestes o Pai." },
{name:'62214',l:'62',c:'2',v:'14',texto:"Eu vos escrevi, pais, porque já conhecestes aquele que é desde o princípio. Eu vos escrevi, jovens, porque sois fortes, e a palavra de Deus está em vós, e já vencestes o maligno." },
{name:'62215',l:'62',c:'2',v:'15',texto:"Não ameis o mundo, nem o que no mundo há. Se alguém ama o mundo, o amor do Pai não está nele." },
{name:'62216',l:'62',c:'2',v:'16',texto:"Porque tudo o que há no mundo, a concupiscência da carne, a concupiscência dos olhos e a soberba da vida, não é do Pai, mas do mundo." },
{name:'62217',l:'62',c:'2',v:'17',texto:"E o mundo passa, e a sua concupiscência; mas aquele que faz a vontade de Deus permanece para sempre." },
{name:'62218',l:'62',c:'2',v:'18',texto:"Filhinhos, é já a última hora; e, como ouvistes que vem o anticristo, também agora muitos se têm feito anticristos; por onde conhecemos que é já a última hora." },
{name:'62219',l:'62',c:'2',v:'19',texto:"Saíram de nós, mas não eram de nós; porque, se fossem de nós, ficariam conosco; mas isto é para que se manifestasse que não são todos de nós." },
{name:'62220',l:'62',c:'2',v:'20',texto:"E vós tendes a unção do Santo e sabeis tudo." },
{name:'62221',l:'62',c:'2',v:'21',texto:"Não vos escrevi porque não soubésseis a verdade, mas porque a sabeis, e porque nenhuma mentira vem da verdade." },
{name:'62222',l:'62',c:'2',v:'22',texto:"Quem é o mentiroso, senão aquele que nega que Jesus é o Cristo? É o anticristo esse mesmo que nega o Pai e o Filho." },
{name:'62223',l:'62',c:'2',v:'23',texto:"Qualquer que nega o Filho também não tem o Pai; e aquele que confessa o Filho tem também o Pai." },
{name:'62224',l:'62',c:'2',v:'24',texto:"Portanto, o que desde o princípio ouvistes permaneça em vós. Se em vós permanecer o que desde o princípio ouvistes, também permanecereis no Filho e no Pai." },
{name:'62225',l:'62',c:'2',v:'25',texto:"E esta é a promessa que ele nos fez: a vida eterna." },
{name:'62226',l:'62',c:'2',v:'26',texto:"Estas coisas vos escrevi acerca dos que vos enganam." },
{name:'62227',l:'62',c:'2',v:'27',texto:"E a unção que vós recebestes dele fica em vós, e não tendes necessidade de que alguém vos ensine; mas, como a sua unção vos ensina todas as coisas, e é verdadeira, e não é mentira, como ela vos ensinou, assim nele permanecereis." },
{name:'62228',l:'62',c:'2',v:'28',texto:"E agora, filhinhos, permanecei nele, para que, quando ele se manifestar, tenhamos confiança e não sejamos confundidos por ele na sua vinda." },
{name:'62229',l:'62',c:'2',v:'29',texto:"Se sabeis que ele é justo, sabeis que todo aquele que pratica a justiça é nascido dele." },
],
numVersiculos: 29,
},

c3: {
versiculos:[
{name:'6231',l:'62',c:'3',v:'1',texto:"Vede quão grande caridade nos tem concedido o Pai: que fôssemos chamados filhos de Deus. Por isso, o mundo não nos conhece, porque não conhece a ele." },
{name:'6232',l:'62',c:'3',v:'2',texto:"Amados, agora somos filhos de Deus, e ainda não é manifesto o que havemos de ser. Mas sabemos que, quando ele se manifestar, seremos semelhantes a ele; porque assim como é o veremos." },
{name:'6233',l:'62',c:'3',v:'3',texto:"E qualquer que nele tem esta esperança purifica-se a si mesmo, como também ele é puro." },
{name:'6234',l:'62',c:'3',v:'4',texto:"Qualquer que comete o pecado também comete iniqüidade, porque o pecado é iniqüidade." },
{name:'6235',l:'62',c:'3',v:'5',texto:"E bem sabeis que ele se manifestou para tirar os nossos pecados; e nele não há pecado." },
{name:'6236',l:'62',c:'3',v:'6',texto:"Qualquer que permanece nele não peca; qualquer que peca não o viu nem o conheceu." },
{name:'6237',l:'62',c:'3',v:'7',texto:"Filhinhos, ninguém vos engane. Quem pratica justiça é justo, assim como ele é justo." },
{name:'6238',l:'62',c:'3',v:'8',texto:"Quem comete o pecado é do diabo, porque o diabo peca desde o princípio. Para isto o Filho de Deus se manifestou: para desfazer as obras do diabo." },
{name:'6239',l:'62',c:'3',v:'9',texto:"Qualquer que é nascido de Deus não comete pecado; porque a sua semente permanece nele; e não pode pecar, porque é nascido de Deus." },
{name:'62310',l:'62',c:'3',v:'10',texto:"Nisto são manifestos os filhos de Deus e os filhos do diabo: qualquer que não pratica a justiça e não ama a seu irmão não é de Deus." },
{name:'62311',l:'62',c:'3',v:'11',texto:"Porque esta é a mensagem que ouvistes desde o princípio: que nos amemos uns aos outros." },
{name:'62312',l:'62',c:'3',v:'12',texto:"Não como Caim, que era do maligno e matou a seu irmão. E por que causa o matou? Porque as suas obras eram más, e as de seu irmão, justas." },
{name:'62313',l:'62',c:'3',v:'13',texto:"Meus irmãos, não vos maravilheis, se o mundo vos aborrece." },
{name:'62314',l:'62',c:'3',v:'14',texto:"Nós sabemos que passamos da morte para a vida, porque amamos os irmãos; quem não ama a seu irmão permanece na morte." },
{name:'62315',l:'62',c:'3',v:'15',texto:"Qualquer que aborrece a seu irmão é homicida. E vós sabeis que nenhum homicida tem permanente nele a vida eterna." },
{name:'62316',l:'62',c:'3',v:'16',texto:"Conhecemos a caridade nisto: que ele deu a sua vida por nós, e nós devemos dar a vida pelos irmãos." },
{name:'62317',l:'62',c:'3',v:'17',texto:"Quem, pois, tiver bens do mundo e, vendo o seu irmão necessitado, lhe cerrar o seu coração, como estará nele a caridade de Deus?" },
{name:'62318',l:'62',c:'3',v:'18',texto:"Meus filhinhos, não amemos de palavra, nem de língua, mas por obra e em verdade." },
{name:'62319',l:'62',c:'3',v:'19',texto:"E nisto conhecemos que somos da verdade e diante dele asseguraremos nosso coração;" },
{name:'62320',l:'62',c:'3',v:'20',texto:"sabendo que, se o nosso coração nos condena, maior é Deus do que o nosso coração e conhece todas as coisas." },
{name:'62321',l:'62',c:'3',v:'21',texto:"Amados, se o nosso coração nos não condena, temos confiança para com Deus;" },
{name:'62322',l:'62',c:'3',v:'22',texto:"e qualquer coisa que lhe pedirmos, dele a receberemos, porque guardamos os seus mandamentos e fazemos o que é agradável à sua vista." },
{name:'62323',l:'62',c:'3',v:'23',texto:"E o seu mandamento é este: que creiamos no nome de seu Filho Jesus Cristo e nos amemos uns aos outros, segundo o seu mandamento." },
{name:'62324',l:'62',c:'3',v:'24',texto:"E aquele que guarda os seus mandamentos nele está, e ele nele. E nisto conhecemos que ele está em nós: pelo Espírito que nos tem dado." },
],
numVersiculos: 24,
},

c4: {
versiculos:[
{name:'6241',l:'62',c:'4',v:'1',texto:"Amados, não creiais em todo espírito, mas provai se os espíritos são de Deus, porque já muitos falsos profetas se têm levantado no mundo." },
{name:'6242',l:'62',c:'4',v:'2',texto:"Nisto conhecereis o Espírito de Deus: todo espírito que confessa que Jesus Cristo veio em carne é de Deus;" },
{name:'6243',l:'62',c:'4',v:'3',texto:"e todo espírito que não confessa que Jesus Cristo veio em carne não é de Deus; mas este é o espírito do anticristo, do qual já ouvistes que há de vir, e eis que está já no mundo." },
{name:'6244',l:'62',c:'4',v:'4',texto:"Filhinhos, sois de Deus e já os tendes vencido, porque maior é o que está em vós do que o que está no mundo." },
{name:'6245',l:'62',c:'4',v:'5',texto:"Do mundo são; por isso, falam do mundo, e o mundo os ouve." },
{name:'6246',l:'62',c:'4',v:'6',texto:"Nós somos de Deus; aquele que conhece a Deus ouve-nos; aquele que não é de Deus não nos ouve. Nisto conhecemos nós o espírito da verdade e o espírito do erro." },
{name:'6247',l:'62',c:'4',v:'7',texto:"Amados, amemo-nos uns aos outros, porque a caridade é de Deus; e qualquer que ama é nascido de Deus e conhece a Deus." },
{name:'6248',l:'62',c:'4',v:'8',texto:"Aquele que não ama não conhece a Deus, porque Deus é caridade." },
{name:'6249',l:'62',c:'4',v:'9',texto:"Nisto se manifestou a caridade de Deus para conosco: que Deus enviou seu Filho unigênito ao mundo, para que por ele vivamos." },
{name:'62410',l:'62',c:'4',v:'10',texto:"Nisto está a caridade: não em que nós tenhamos amado a Deus, mas em que ele nos amou e enviou seu Filho para propiciação pelos nossos pecados." },
{name:'62411',l:'62',c:'4',v:'11',texto:"Amados, se Deus assim nos amou, também nós devemos amar uns aos outros." },
{name:'62412',l:'62',c:'4',v:'12',texto:"Ninguém jamais viu a Deus; se nós amamos uns aos outros, Deus está em nós, e em nós é perfeita a sua caridade." },
{name:'62413',l:'62',c:'4',v:'13',texto:"Nisto conhecemos que estamos nele, e ele em nós, pois que nos deu do seu Espírito," },
{name:'62414',l:'62',c:'4',v:'14',texto:"e vimos, e testificamos que o Pai enviou seu Filho para Salvador do mundo." },
{name:'62415',l:'62',c:'4',v:'15',texto:"Qualquer que confessar que Jesus é o Filho de Deus, Deus está nele e ele em Deus." },
{name:'62416',l:'62',c:'4',v:'16',texto:"E nós conhecemos e cremos no amor que Deus nos tem. Deus é caridade e quem está em caridade está em Deus, e Deus, nele." },
{name:'62417',l:'62',c:'4',v:'17',texto:"Nisto é perfeita a caridade para conosco, para que no Dia do Juízo tenhamos confiança; porque, qual ele é, somos nós também neste mundo." },
{name:'62418',l:'62',c:'4',v:'18',texto:"Na caridade, não há temor; antes, a perfeita caridade lança fora o temor; porque o temor tem consigo a pena, e o que teme não é perfeito em caridade." },
{name:'62419',l:'62',c:'4',v:'19',texto:"Nós o amamos porque ele nos amou primeiro." },
{name:'62420',l:'62',c:'4',v:'20',texto:"Se alguém diz: Eu amo a Deus e aborrece a seu irmão, é mentiroso. Pois quem não ama seu irmão, ao qual viu, como pode amar a Deus, a quem não viu?" },
{name:'62421',l:'62',c:'4',v:'21',texto:"E dele temos este mandamento: que quem ama a Deus, ame também seu irmão." },
],
numVersiculos: 21,
},

c5: {
versiculos:[
{name:'6251',l:'62',c:'5',v:'1',texto:"Todo aquele que crê que Jesus é o Cristo é nascido de Deus; e todo aquele que ama ao que o gerou também ama ao que dele é nascido." },
{name:'6252',l:'62',c:'5',v:'2',texto:"Nisto conhecemos que amamos os filhos de Deus: quando amamos a Deus e guardamos os seus mandamentos." },
{name:'6253',l:'62',c:'5',v:'3',texto:"Porque esta é a caridade de Deus: que guardemos os seus mandamentos; e os seus mandamentos não são pesados." },
{name:'6254',l:'62',c:'5',v:'4',texto:"Porque todo o que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo: a nossa fé." },
{name:'6255',l:'62',c:'5',v:'5',texto:"Quem é que vence o mundo, senão aquele que crê que Jesus é o Filho de Deus?" },
{name:'6256',l:'62',c:'5',v:'6',texto:"Este é aquele que veio por água e sangue, isto é, Jesus Cristo; não só por água, mas por água e por sangue. E o Espírito é o que testifica, porque o Espírito é a verdade." },
{name:'6257',l:'62',c:'5',v:'7',texto:"Porque três são os que testificam no céu: o Pai, a Palavra e o Espírito Santo; e estes três são um." },
{name:'6258',l:'62',c:'5',v:'8',texto:"E três são os que testificam na terra: o Espírito, e a água, e o sangue; e estes três concordam num." },
{name:'6259',l:'62',c:'5',v:'9',texto:"Se recebemos o testemunho dos homens, o testemunho de Deus é maior; porque o testemunho de Deus é este, que de seu Filho testificou." },
{name:'62510',l:'62',c:'5',v:'10',texto:"Quem crê no Filho de Deus em si mesmo tem o testemunho; quem em Deus não crê mentiroso o fez, porquanto não creu no testemunho que Deus de seu Filho deu." },
{name:'62511',l:'62',c:'5',v:'11',texto:"E o testemunho é este: que Deus nos deu a vida eterna; e esta vida está em seu Filho." },
{name:'62512',l:'62',c:'5',v:'12',texto:"Quem tem o Filho tem a vida; quem não tem o Filho de Deus não tem a vida." },
{name:'62513',l:'62',c:'5',v:'13',texto:"Estas coisas vos escrevi, para que saibais que tendes a vida eterna e para que creiais no nome do Filho de Deus." },
{name:'62514',l:'62',c:'5',v:'14',texto:"E esta é a confiança que temos nele: que, se pedirmos alguma coisa, segundo a sua vontade, ele nos ouve." },
{name:'62515',l:'62',c:'5',v:'15',texto:"E, se sabemos que nos ouve em tudo o que pedimos, sabemos que alcançamos as petições que lhe fizemos." },
{name:'62516',l:'62',c:'5',v:'16',texto:"Se alguém vir seu irmão cometer pecado que não é para morte, orará, e Deus dará a vida àqueles que não pecarem para morte. Há pecado para morte, e por esse não digo que ore." },
{name:'62517',l:'62',c:'5',v:'17',texto:"Toda iniqüidade é pecado, e há pecado que não é para morte." },
{name:'62518',l:'62',c:'5',v:'18',texto:"Sabemos que todo aquele que é nascido de Deus não peca; mas o que de Deus é gerado conserva-se a si mesmo, e o maligno não lhe toca." },
{name:'62519',l:'62',c:'5',v:'19',texto:"Sabemos que somos de Deus e que todo o mundo está no maligno." },
{name:'62520',l:'62',c:'5',v:'20',texto:"E sabemos que já o Filho de Deus é vindo e nos deu entendimento para conhecermos o que é verdadeiro; e no que é verdadeiro estamos, isto é, em seu Filho Jesus Cristo. Este é o verdadeiro Deus e a vida eterna." },
{name:'62521',l:'62',c:'5',v:'21',texto:"Filhinhos, guardai-vos dos ídolos. Amém!" },
],
numVersiculos: 21,
},
	

};
