BibliaJFA.rut = {
	libro: "Rute",
	numCapitulos: 4,

c1: {
versiculos:[
{name:'811',l:'8',c:'1',v:'1',texto:"E sucedeu que, nos dias em que os juízes julgavam, houve uma fome na terra; pelo que um homem de Belém de Judá saiu a peregrinar nos campos de Moabe, ele, e sua mulher, e seus dois filhos." },
{name:'812',l:'8',c:'1',v:'2',texto:"E era o nome deste homem Elimeleque, e o nome de sua mulher, Noemi, e os nomes de seus dois filhos, Malom e Quiliom, efrateus, de Belém de Judá; e vieram aos campos de Moabe e ficaram ali." },
{name:'813',l:'8',c:'1',v:'3',texto:"E morreu Elimeleque, marido de Noemi; e ficou ela com os seus dois filhos," },
{name:'814',l:'8',c:'1',v:'4',texto:"os quais tomaram para si mulheres moabitas; e era o nome de uma Orfa, e o nome da outra, Rute; e ficaram ali quase dez anos." },
{name:'815',l:'8',c:'1',v:'5',texto:"E morreram também ambos, Malom e Quiliom, ficando assim esta mulher desamparada dos seus dois filhos e de seu marido." },
{name:'816',l:'8',c:'1',v:'6',texto:"Então, se levantou ela com as suas noras e voltou dos campos de Moabe, porquanto, na terra de Moabe, ouviu que o SENHOR tinha visitado o seu povo, dando-lhe pão." },
{name:'817',l:'8',c:'1',v:'7',texto:"Pelo que saiu do lugar onde estivera, e as suas duas noras, com ela. E, indo elas caminhando, para voltarem para a terra de Judá," },
{name:'818',l:'8',c:'1',v:'8',texto:"disse Noemi às suas duas noras: Ide, voltai cada uma à casa de sua mãe; e o SENHOR use convosco de benevolência, como vós usastes com os falecidos e comigo." },
{name:'819',l:'8',c:'1',v:'9',texto:"O SENHOR vos dê que acheis descanso cada uma em casa de seu marido. E, beijando-as ela, levantaram a sua voz, e choraram," },
{name:'8110',l:'8',c:'1',v:'10',texto:"e disseram-lhe: Certamente, voltaremos contigo ao teu povo." },
{name:'8111',l:'8',c:'1',v:'11',texto:"Porém Noemi disse: Tornai, minhas filhas, por que iríeis comigo? Tenho eu ainda no meu ventre mais filhos, para que vos fossem por maridos?" },
{name:'8112',l:'8',c:'1',v:'12',texto:"Tornai, filhas minhas, ide-vos embora, que já mui velha sou para ter marido; ainda quando eu dissesse: Tenho esperança, ou ainda que esta noite tivesse marido, e ainda tivesse filhos," },
{name:'8113',l:'8',c:'1',v:'13',texto:"esperá-los-íeis até que viessem a ser grandes? Deter-vos-íeis por eles, sem tomardes marido? Não, filhas minhas, que mais amargo é a mim do que a vós mesmas; porquanto a mão do SENHOR se descarregou contra mim." },
{name:'8114',l:'8',c:'1',v:'14',texto:"Então, levantaram a sua voz e tornaram a chorar; e Orfa beijou a sua sogra; porém Rute se apegou a ela." },
{name:'8115',l:'8',c:'1',v:'15',texto:"Pelo que disse: Eis que voltou tua cunhada ao seu povo e aos seus deuses; volta tu também após a tua cunhada." },
{name:'8116',l:'8',c:'1',v:'16',texto:"Disse, porém, Rute: Não me instes para que te deixe e me afaste de ti; porque, aonde quer que tu fores, irei eu e, onde quer que pousares à noite, ali pousarei eu; o teu povo é o meu povo, o teu Deus é o meu Deus." },
{name:'8117',l:'8',c:'1',v:'17',texto:"Onde quer que morreres, morrerei eu e ali serei sepultada; me faça assim o SENHOR e outro tanto, se outra coisa que não seja a morte me separar de ti." },
{name:'8118',l:'8',c:'1',v:'18',texto:"Vendo ela, pois, que de todo estava resolvida para ir com ela, deixou de lhe falar nisso." },
{name:'8119',l:'8',c:'1',v:'19',texto:"Assim, pois, foram-se ambas, até que chegaram a Belém; e sucedeu que, entrando elas em Belém, toda a cidade se comoveu por causa delas, e diziam: Não é esta Noemi?" },
{name:'8120',l:'8',c:'1',v:'20',texto:"Porém ela lhes dizia: Não me chameis Noemi; chamai-me Mara, porque grande amargura me tem dado o Todo-poderoso." },
{name:'8121',l:'8',c:'1',v:'21',texto:"Cheia parti, porém vazia o SENHOR me fez tornar; por que, pois, me chamareis Noemi? Pois o SENHOR testifica contra mim, e o Todo-poderoso me tem afligido tanto." },
{name:'8122',l:'8',c:'1',v:'22',texto:"Assim, Noemi voltou, e com ela, Rute, a moabita, sua nora, que voltava dos campos de Moabe; e chegaram a Belém no princípio da sega das cevadas." },
],
numVersiculos: 22,
},

c2: {
versiculos:[
{name:'821',l:'8',c:'2',v:'1',texto:"E tinha Noemi um parente de seu marido, homem valente e poderoso, da geração de Elimeleque; e era o seu nome Boaz." },
{name:'822',l:'8',c:'2',v:'2',texto:"E Rute, a moabita, disse a Noemi: Deixa-me ir ao campo, e apanharei espigas atrás daquele em cujos olhos eu achar graça. E ela lhe disse: Vai, minha filha." },
{name:'823',l:'8',c:'2',v:'3',texto:"Foi, pois, e chegou, e apanhava espigas no campo após os segadores; e caiu-lhe em sorte uma parte do campo de Boaz, que era da geração de Elimeleque." },
{name:'824',l:'8',c:'2',v:'4',texto:"E eis que Boaz veio de Belém e disse aos segadores: O SENHOR seja convosco. E disseram-lhe eles: O SENHOR te abençoe." },
{name:'825',l:'8',c:'2',v:'5',texto:"Depois, disse Boaz a seu moço que estava posto sobre os segadores: De quem é esta moça?" },
{name:'826',l:'8',c:'2',v:'6',texto:"E respondeu o moço que estava posto sobre os segadores e disse: Esta é a moça moabita que voltou com Noemi dos campos de Moabe." },
{name:'827',l:'8',c:'2',v:'7',texto:"Disse-me ela: Deixa-me colher espigas e ajuntá-las entre as gavelas após os segadores. Assim, ela veio e, desde pela manhã, está aqui até agora, a não ser um pouco que esteve sentada em casa." },
{name:'828',l:'8',c:'2',v:'8',texto:"Então, disse Boaz a Rute: Não ouves, filha minha? Não vás colher a outro campo, nem tampouco passes daqui; porém aqui te ajuntarás com as minhas moças." },
{name:'829',l:'8',c:'2',v:'9',texto:"Os teus olhos estarão atentos no campo que segarem, e irás após elas; não dei ordem aos moços, que te não toquem? Tendo tu sede, vai aos vasos e bebe do que os moços tirarem." },
{name:'8210',l:'8',c:'2',v:'10',texto:"Então, ela caiu sobre o seu rosto, e se inclinou à terra, e disse-lhe: Por que achei graça em teus olhos, para que faças caso de mim, sendo eu uma estrangeira?" },
{name:'8211',l:'8',c:'2',v:'11',texto:"E respondeu Boaz e disse-lhe: Bem se me contou quanto fizeste à tua sogra, depois da morte de teu marido, e deixaste a teu pai, e a tua mãe, e a terra onde nasceste, e vieste para um povo que, dantes, não conheceste." },
{name:'8212',l:'8',c:'2',v:'12',texto:"O SENHOR galardoe o teu feito, e seja cumprido o teu galardão do SENHOR, Deus de Israel, sob cujas asas te vieste abrigar." },
{name:'8213',l:'8',c:'2',v:'13',texto:"E disse ela: Ache eu graça em teus olhos, senhor meu, pois me consolaste e falaste ao coração da tua serva, não sendo eu nem ainda como uma das tuas criadas." },
{name:'8214',l:'8',c:'2',v:'14',texto:"E, sendo já hora de comer, disse-lhe Boaz: Achega-te aqui, e come do pão, e molha o teu bocado no vinagre. E ela se assentou ao lado dos segadores, e ele lhe deu do trigo tostado, e comeu e se fartou, e ainda lhe sobejou." },
{name:'8215',l:'8',c:'2',v:'15',texto:"E, levantando-se ela a colher, Boaz deu ordem aos seus moços, dizendo: Até entre as gavelas deixai-a colher e não lhe embaraceis." },
{name:'8216',l:'8',c:'2',v:'16',texto:"E deixai cair alguns punhados, e deixai-os ficar, para que os colha, e não a repreendais." },
{name:'8217',l:'8',c:'2',v:'17',texto:"E esteve ela apanhando naquele campo até à tarde e debulhou o que apanhou, e foi quase um efa de cevada." },
{name:'8218',l:'8',c:'2',v:'18',texto:"E tomou-o e veio à cidade; e viu sua sogra o que tinha apanhado; também tirou e deu-lhe o que lhe sobejara depois de fartar-se." },
{name:'8219',l:'8',c:'2',v:'19',texto:"Então, disse-lhe sua sogra: Onde colheste hoje e onde trabalhaste? Bendito seja aquele que te reconheceu. E relatou à sua sogra com quem tinha trabalhado e disse: O nome do homem com quem hoje trabalhei é Boaz." },
{name:'8220',l:'8',c:'2',v:'20',texto:"Então, Noemi disse à sua nora: Bendito seja do SENHOR, que ainda não tem deixado a sua beneficência nem para com os vivos nem para com os mortos. Disse-lhe mais Noemi: Este homem é nosso parente chegado e um dentre os nossos remidores." },
{name:'8221',l:'8',c:'2',v:'21',texto:"E disse Rute, a moabita: Também ainda me disse: Com os moços que tenho te ajuntarás, até que acabem toda a sega que tenho." },
{name:'8222',l:'8',c:'2',v:'22',texto:"E disse Noemi à sua nora, Rute: Melhor é, filha minha, que saias com as suas moças, para que noutro campo não te encontrem." },
{name:'8223',l:'8',c:'2',v:'23',texto:"Assim, ajuntou-se com as moças de Boaz, para colher, até que a sega das cevadas e dos trigos se acabou; e ficou com a sua sogra." },
],
numVersiculos: 23,
},

c3: {
versiculos:[
{name:'831',l:'8',c:'3',v:'1',texto:"E disse-lhe Noemi, sua sogra: Minha filha, não hei de eu buscar descanso, para que fiques bem?" },
{name:'832',l:'8',c:'3',v:'2',texto:"Ora, pois, não é Boaz, com cujas moças estiveste, de nossa parentela? Eis que esta noite padejará a cevada na eira." },
{name:'833',l:'8',c:'3',v:'3',texto:"Lava-te, pois, e unge-te, e veste as tuas vestes, e desce à eira; porém não te dês a conhecer ao homem, até que tenha acabado de comer e beber." },
{name:'834',l:'8',c:'3',v:'4',texto:"E há de ser que, quando ele se deitar, notarás o lugar em que se deitar; então, entra, e descobrir-lhe-ás os pés, e te deitarás, e ele te fará saber o que deves fazer." },
{name:'835',l:'8',c:'3',v:'5',texto:"E ela lhe disse: Tudo quanto me disseres farei." },
{name:'836',l:'8',c:'3',v:'6',texto:"Então, foi para a eira e fez conforme tudo quanto sua sogra lhe tinha ordenado." },
{name:'837',l:'8',c:'3',v:'7',texto:"Havendo, pois, Boaz comido e bebido, e estando já o seu coração alegre, veio deitar-se ao pé de um monte de cereais; então, veio ela de mansinho, e lhe descobriu os pés, e se deitou." },
{name:'838',l:'8',c:'3',v:'8',texto:"E sucedeu que, pela meia-noite, o homem estremeceu e se voltou; e eis que uma mulher jazia a seus pés." },
{name:'839',l:'8',c:'3',v:'9',texto:"E disse ele: Quem és tu? E ela disse: Sou Rute, tua serva; estende, pois, tua aba sobre a tua serva, porque tu és o remidor." },
{name:'8310',l:'8',c:'3',v:'10',texto:"E disse ele: Bendita sejas tu do SENHOR, minha filha; melhor fizeste esta tua última beneficência do que a primeira, pois após nenhuns jovens foste, quer pobres quer ricos." },
{name:'8311',l:'8',c:'3',v:'11',texto:"Agora, pois, minha filha, não temas; tudo quanto disseste te farei, pois toda a cidade do meu povo sabe que és mulher virtuosa." },
{name:'8312',l:'8',c:'3',v:'12',texto:"Porém, agora, é muito verdade que eu sou remidor; mas ainda outro remidor há mais chegado do que eu." },
{name:'8313',l:'8',c:'3',v:'13',texto:"Fica-te aqui esta noite, e será que, pela manhã, se ele te redimir, bem está, ele te redima; porém, se te não quiser redimir, vive o SENHOR, que eu te redimirei; deita-te aqui até à manhã." },
{name:'8314',l:'8',c:'3',v:'14',texto:"Ficou-se, pois, deitada a seus pés até pela manhã e levantou-se antes que pudesse um conhecer a outro, porquanto disse: Não se saiba que alguma mulher veio à eira." },
{name:'8315',l:'8',c:'3',v:'15',texto:"Disse mais: Dá cá o roupão que tens sobre ti e segura-o. E ela segurou-o; e ele mediu seis medidas de cevada e lhas pôs em cima; então, entrou na cidade." },
{name:'8316',l:'8',c:'3',v:'16',texto:"E veio à sua sogra, a qual disse: Como se te passaram as coisas, minha filha? E ela lhe contou tudo quanto aquele homem lhe fizera." },
{name:'8317',l:'8',c:'3',v:'17',texto:"Disse mais: Estas seis medidas de cevada me deu, porque me disse: Não vás vazia à tua sogra." },
{name:'8318',l:'8',c:'3',v:'18',texto:"Então, disse ela: Sossega, minha filha, até que saibas como irá o caso, porque aquele homem não descansará até que conclua hoje este negócio." },
],
numVersiculos: 18,
},

c4: {
versiculos:[
{name:'841',l:'8',c:'4',v:'1',texto:"E Boaz subiu à porta e assentou-se ali; e eis que o remidor de que Boaz tinha falado ia passando e disse-lhe: Ó fulano, desvia-te para cá e assenta-te aqui. E desviou-se para ali e assentou-se." },
{name:'842',l:'8',c:'4',v:'2',texto:"Então, tomou dez homens dos anciãos da cidade e disse: Assentai-vos aqui. E assentaram-se." },
{name:'843',l:'8',c:'4',v:'3',texto:"Então, disse ao remidor: Aquela parte da terra que foi de Elimeleque, nosso irmão, Noemi, que tornou da terra dos moabitas, a vendeu." },
{name:'844',l:'8',c:'4',v:'4',texto:"E disse eu: Manifestá-lo-ei em teus ouvidos, dizendo: Toma-a diante dos habitantes e diante dos anciãos do meu povo; se a hás de redimir, redime-a e, se não se houver de redimir, declara-mo, para que o saiba, pois outro não há, senão tu, que a redima, e eu depois de ti. Então, disse ele: Eu a redimirei." },
{name:'845',l:'8',c:'4',v:'5',texto:"Disse, porém, Boaz: No dia em que tomares a terra da mão de Noemi, também a tomarás da mão de Rute, a moabita, mulher do falecido, para suscitar o nome do falecido sobre a sua herdade." },
{name:'846',l:'8',c:'4',v:'6',texto:"Então, disse o remidor: Para mim não a poderei redimir, para que não cause dano à minha herdade; redime tu a minha remissão para ti, porque eu não a poderei redimir." },
{name:'847',l:'8',c:'4',v:'7',texto:"Havia, pois, já de muito tempo este costume em Israel, quanto à remissão e contrato, para confirmar todo negócio, que o homem descalçava o sapato e o dava ao seu próximo; e isto era por testemunho em Israel." },
{name:'848',l:'8',c:'4',v:'8',texto:"Disse, pois, o remidor a Boaz: Toma-a para ti. E descalçou o sapato." },
{name:'849',l:'8',c:'4',v:'9',texto:"Então, Boaz disse aos anciãos e a todo o povo: Sois, hoje, testemunhas de que tomei tudo quanto foi de Elimeleque, e de Quiliom, e de Malom da mão de Noemi;" },
{name:'8410',l:'8',c:'4',v:'10',texto:"e de que também tomo por mulher a Rute, a moabita, que foi mulher de Malom, para suscitar o nome do falecido sobre a sua herdade, para que o nome do falecido não seja desarraigado dentre seus irmãos e da porta do seu lugar; disto sois hoje testemunhas." },
{name:'8411',l:'8',c:'4',v:'11',texto:"E todo o povo que estava na porta e os anciãos disseram: Somos testemunhas; o SENHOR faça a esta mulher, que entra na tua casa, como a Raquel e como a Léia, que ambas edificaram a casa de Israel; e há-te já valorosamente em Efrata e faze-te nome afamado em Belém." },
{name:'8412',l:'8',c:'4',v:'12',texto:"E seja a tua casa como a casa de Perez ( que Tamar teve de Judá ), da semente que o SENHOR te der desta moça." },
{name:'8413',l:'8',c:'4',v:'13',texto:"Assim, tomou Boaz a Rute, e ela lhe foi por mulher; e ele entrou a ela, e o SENHOR lhe deu conceição, e ela teve um filho." },
{name:'8414',l:'8',c:'4',v:'14',texto:"Então, as mulheres disseram a Noemi: Bendito seja o SENHOR, que não deixou, hoje, de te dar remidor, e seja o seu nome afamado em Israel." },
{name:'8415',l:'8',c:'4',v:'15',texto:"Ele te será recriador da alma e conservará a tua velhice, pois tua nora, que te ama, o teve, e ela te é melhor do que sete filhos." },
{name:'8416',l:'8',c:'4',v:'16',texto:"E Noemi tomou o filho, e o pôs no seu regaço, e foi sua ama." },
{name:'8417',l:'8',c:'4',v:'17',texto:"E as vizinhas lhe deram um nome, dizendo: A Noemi nasceu um filho. E chamaram o seu nome Obede. Este é o pai de Jessé, pai de Davi." },
{name:'8418',l:'8',c:'4',v:'18',texto:"Estas são, pois, as gerações de Perez: Perez gerou a Esrom," },
{name:'8419',l:'8',c:'4',v:'19',texto:"e Esrom gerou a Arão, e Arão gerou a Aminadabe," },
{name:'8420',l:'8',c:'4',v:'20',texto:"e Aminadabe gerou a Naassom, e Naassom gerou a Salmom," },
{name:'8421',l:'8',c:'4',v:'21',texto:"e Salmom gerou a Boaz, e Boaz gerou a Obede," },
{name:'8422',l:'8',c:'4',v:'22',texto:"e Obede gerou a Jessé, e Jessé gerou a Davi." },
],
numVersiculos: 22,
},
	

};
