BibliaRVR60.cantares = {
	libro: "Cantares",
	numCapitulos: 8,

c1: {
versiculos:[
{name:'2211',l:'22',c:'1',v:'1',texto:"Cantar de los cantares, el cual es de Salomón." },
{name:'2212',l:'22',c:'1',v:'2',texto:"¡Oh, si él me besara con besos de su boca! Porque mejores son tus amores que el vino." },
{name:'2213',l:'22',c:'1',v:'3',texto:"A más del olor de tus suaves ungüentos, Tu nombre es como ungüento derramado; Por eso las doncellas te aman." },
{name:'2214',l:'22',c:'1',v:'4',texto:"Atráeme; en pos de ti correremos. El rey me ha metido en sus cámaras; Nos gozaremos y alegraremos en ti; Nos acordaremos de tus amores más que del vino; Con razón te aman." },
{name:'2215',l:'22',c:'1',v:'5',texto:"Morena soy, oh hijas de Jerusalén, pero codiciable Como las tiendas de Cedar, Como las cortinas de Salomón." },
{name:'2216',l:'22',c:'1',v:'6',texto:"No reparéis en que soy morena, Porque el sol me miró. Los hijos de mi madre se airaron contra mí; Me pusieron a guardar las viñas; Y mi viña, que era mía, no guardé." },
{name:'2217',l:'22',c:'1',v:'7',texto:"Hazme saber, oh tú a quien ama mi alma, Dónde apacientas, dónde sesteas al mediodía; Pues ¿por qué había de estar yo como errante Junto a los rebaños de tus compañeros? " },
{name:'2218',l:'22',c:'1',v:'8',texto:"Si tú no lo sabes, oh hermosa entre las mujeres, Ve, sigue las huellas del rebaño, Y apacienta tus cabritas junto a las cabañas de los pastores." },
{name:'2219',l:'22',c:'1',v:'9',texto:"A yegua de los carros de Faraón Te he comparado, amiga mía." },
{name:'22110',l:'22',c:'1',v:'10',texto:"Hermosas son tus mejillas entre los pendientes, Tu cuello entre los collares." },
{name:'22111',l:'22',c:'1',v:'11',texto:"Zarcillos de oro te haremos, Tachonados de plata." },
{name:'22112',l:'22',c:'1',v:'12',texto:"Mientras el rey estaba en su reclinatorio, Mi nardo dio su olor." },
{name:'22113',l:'22',c:'1',v:'13',texto:"Mi amado es para mí un manojito de mirra, Que reposa entre mis pechos." },
{name:'22114',l:'22',c:'1',v:'14',texto:"Racimo de flores de alheña en las viñas de En-gadi Es para mí mi amado." },
{name:'22115',l:'22',c:'1',v:'15',texto:"He aquí que tú eres hermosa, amiga mía; He aquí eres bella; tus ojos son como palomas." },
{name:'22116',l:'22',c:'1',v:'16',texto:"He aquí que tú eres hermoso, amado mío, y dulce; Nuestro lecho es de flores." },
{name:'22117',l:'22',c:'1',v:'17',texto:"Las vigas de nuestra casa son de cedro, Y de ciprés los artesonados." },
],
numVersiculos: 17,
},

c2: {
versiculos:[
{name:'2221',l:'22',c:'2',v:'1',texto:"Yo soy la rosa de Sarón, Y el lirio de los valles." },
{name:'2222',l:'22',c:'2',v:'2',texto:"Como el lirio entre los espinos, Así es mi amiga entre las doncellas." },
{name:'2223',l:'22',c:'2',v:'3',texto:"Como el manzano entre los árboles silvestres, Así es mi amado entre los jóvenes; Bajo la sombra del deseado me senté, Y su fruto fue dulce a mi paladar." },
{name:'2224',l:'22',c:'2',v:'4',texto:"Me llevó a la casa del banquete, Y su bandera sobre mí fue amor." },
{name:'2225',l:'22',c:'2',v:'5',texto:"Sustentadme con pasas, confortadme con manzanas; Porque estoy enferma de amor." },
{name:'2226',l:'22',c:'2',v:'6',texto:"Su izquierda esté debajo de mi cabeza, Y su derecha me abrace." },
{name:'2227',l:'22',c:'2',v:'7',texto:"Yo os conjuro, oh doncellas de Jerusalén, Por los corzos y por las ciervas del campo, Que no despertéis ni hagáis velar al amor, Hasta que quiera." },
{name:'2228',l:'22',c:'2',v:'8',texto:"¡La voz de mi amado! He aquí él viene Saltando sobre los montes, Brincando sobre los collados." },
{name:'2229',l:'22',c:'2',v:'9',texto:"Mi amado es semejante al corzo, O al cervatillo. Helo aquí, está tras nuestra pared, Mirando por las ventanas, Atisbando por las celosías." },
{name:'22210',l:'22',c:'2',v:'10',texto:"Mi amado habló, y me dijo: Levántate, oh amiga mía, hermosa mía, y ven." },
{name:'22211',l:'22',c:'2',v:'11',texto:"Porque he aquí ha pasado el invierno, Se ha mudado, la lluvia se fue; " },
{name:'22212',l:'22',c:'2',v:'12',texto:"Se han mostrado las flores en la tierra, El tiempo de la canción ha venido, Y en nuestro país se ha oído la voz de la tórtola." },
{name:'22213',l:'22',c:'2',v:'13',texto:"La higuera ha echado sus higos, Y las vides en cierne dieron olor; Levántate, oh amiga mía, hermosa mía, y ven." },
{name:'22214',l:'22',c:'2',v:'14',texto:"Paloma mía, que estás en los agujeros de la peña, en lo escondido de escarpados parajes, Muéstrame tu rostro, hazme oír tu voz; Porque dulce es la voz tuya, y hermoso tu aspecto." },
{name:'22215',l:'22',c:'2',v:'15',texto:"Cazadnos las zorras, las zorras pequeñas, que echan a perder las viñas; Porque nuestras viñas están en cierne." },
{name:'22216',l:'22',c:'2',v:'16',texto:"Mi amado es mío, y yo suya; El apacienta entre lirios." },
{name:'22217',l:'22',c:'2',v:'17',texto:"Hasta que apunte el día, y huyan las sombras, Vuélvete, amado mío; sé semejante al corzo, o como el cervatillo Sobre los montes de Beter." },
],
numVersiculos: 17,
},

c3: {
versiculos:[
{name:'2231',l:'22',c:'3',v:'1',texto:"Por las noches busqué en mi lecho al que ama mi alma; Lo busqué, y no lo hallé." },
{name:'2232',l:'22',c:'3',v:'2',texto:"Y dije: Me levantaré ahora, y rodearé por la ciudad; Por las calles y por las plazas Buscaré al que ama mi alma; Lo busqué, y no lo hallé." },
{name:'2233',l:'22',c:'3',v:'3',texto:"Me hallaron los guardas que rondan la ciudad, Y les dije: ¿Habéis visto al que ama mi alma? " },
{name:'2234',l:'22',c:'3',v:'4',texto:"Apenas hube pasado de ellos un poco, Hallé luego al que ama mi alma; Lo así, y no lo dejé, Hasta que lo metí en casa de mi madre, Y en la cámara de la que me dio a luz." },
{name:'2235',l:'22',c:'3',v:'5',texto:"Yo os conjuro, oh doncellas de Jerusalén, Por los corzos y por las ciervas del campo, Que no despertéis ni hagáis velar al amor, Hasta que quiera." },
{name:'2236',l:'22',c:'3',v:'6',texto:"¿Quién es ésta que sube del desierto como columna de humo, Sahumada de mirra y de incienso Y de todo polvo aromático? " },
{name:'2237',l:'22',c:'3',v:'7',texto:"He aquí es la litera de Salomón; Sesenta valientes la rodean, De los fuertes de Israel." },
{name:'2238',l:'22',c:'3',v:'8',texto:"Todos ellos tienen espadas, diestros en la guerra; Cada uno su espada sobre su muslo, Por los temores de la noche." },
{name:'2239',l:'22',c:'3',v:'9',texto:"El rey Salomón se hizo una carroza De madera del Líbano." },
{name:'22310',l:'22',c:'3',v:'10',texto:"Hizo sus columnas de plata, Su respaldo de oro, Su asiento de grana, Su interior recamado de amor Por las doncellas de Jerusalén." },
{name:'22311',l:'22',c:'3',v:'11',texto:"Salid, oh doncellas de Sion, y ved al rey Salomón Con la corona con que le coronó su madre en el día de su desposorio, Y el día del gozo de su corazón." },
],
numVersiculos: 11,
},

c4: {
versiculos:[
{name:'2241',l:'22',c:'4',v:'1',texto:"He aquí que tú eres hermosa, amiga mía; he aquí que tú eres hermosa; Tus ojos entre tus guedejas como de paloma; Tus cabellos como manada de cabras Que se recuestan en las laderas de Galaad." },
{name:'2242',l:'22',c:'4',v:'2',texto:"Tus dientes como manadas de ovejas trasquiladas, Que suben del lavadero, Todas con crías gemelas, Y ninguna entre ellas estéril." },
{name:'2243',l:'22',c:'4',v:'3',texto:"Tus labios como hilo de grana, Y tu habla hermosa; Tus mejillas, como cachos de granada detrás de tu velo." },
{name:'2244',l:'22',c:'4',v:'4',texto:"Tu cuello, como la torre de David, edificada para armería; Mil escudos están colgados en ella, Todos escudos de valientes." },
{name:'2245',l:'22',c:'4',v:'5',texto:"Tus dos pechos, como gemelos de gacela, Que se apacientan entre lirios." },
{name:'2246',l:'22',c:'4',v:'6',texto:"Hasta que apunte el día y huyan las sombras, Me iré al monte de la mirra, Y al collado del incienso." },
{name:'2247',l:'22',c:'4',v:'7',texto:"Toda tú eres hermosa, amiga mía, Y en ti no hay mancha." },
{name:'2248',l:'22',c:'4',v:'8',texto:"Ven conmigo desde el Líbano, oh esposa mía; Ven conmigo desde el Líbano. Mira desde la cumbre de Amana, Desde la cumbre de Senir y de Hermón, Desde las guaridas de los leones, Desde los montes de los leopardos." },
{name:'2249',l:'22',c:'4',v:'9',texto:"Prendiste mi corazón, hermana, esposa mía; Has apresado mi corazón con uno de tus ojos, Con una gargantilla de tu cuello." },
{name:'22410',l:'22',c:'4',v:'10',texto:"¡Cuán hermosos son tus amores, hermana, esposa mía! ¡Cuánto mejores que el vino tus amores, Y el olor de tus ungüentos que todas las especias aromáticas! " },
{name:'22411',l:'22',c:'4',v:'11',texto:"Como panal de miel destilan tus labios, oh esposa; Miel y leche hay debajo de tu lengua; Y el olor de tus vestidos como el olor del Líbano." },
{name:'22412',l:'22',c:'4',v:'12',texto:"Huerto cerrado eres, hermana mía, esposa mía; Fuente cerrada, fuente sellada." },
{name:'22413',l:'22',c:'4',v:'13',texto:"Tus renuevos son paraíso de granados, con frutos suaves, De flores de alheña y nardos; " },
{name:'22414',l:'22',c:'4',v:'14',texto:"Nardo y azafrán, caña aromática y canela, Con todos los árboles de incienso; Mirra y áloes, con todas las principales especias aromáticas." },
{name:'22415',l:'22',c:'4',v:'15',texto:"Fuente de huertos, Pozo de aguas vivas, Que corren del Líbano." },
{name:'22416',l:'22',c:'4',v:'16',texto:"Levántate, Aquilón, y ven, Austro; Soplad en mi huerto, despréndanse sus aromas. Venga mi amado a su huerto, Y coma de su dulce fruta." },
],
numVersiculos: 16,
},

c5: {
versiculos:[
{name:'2251',l:'22',c:'5',v:'1',texto:"Yo vine a mi huerto, oh hermana, esposa mía; He recogido mi mirra y mis aromas; He comido mi panal y mi miel, Mi vino y mi leche he bebido. Comed, amigos; bebed en abundancia, oh amados." },
{name:'2252',l:'22',c:'5',v:'2',texto:"Yo dormía, pero mi corazón velaba. Es la voz de mi amado que llama: Abreme, hermana mía, amiga mía, paloma mía, perfecta mía, Porque mi cabeza está llena de rocío, Mis cabellos de las gotas de la noche." },
{name:'2253',l:'22',c:'5',v:'3',texto:"Me he desnudado de mi ropa; ¿cómo me he de vestir? He lavado mis pies; ¿cómo los he de ensuciar? " },
{name:'2254',l:'22',c:'5',v:'4',texto:"Mi amado metió su mano por la ventanilla, Y mi corazón se conmovió dentro de mí." },
{name:'2255',l:'22',c:'5',v:'5',texto:"Yo me levanté para abrir a mi amado, Y mis manos gotearon mirra, Y mis dedos mirra, que corría Sobre la manecilla del cerrojo." },
{name:'2256',l:'22',c:'5',v:'6',texto:"Abrí yo a mi amado; Pero mi amado se había ido, había ya pasado; Y tras su hablar salió mi alma. Lo busqué, y no lo hallé; Lo llamé, y no me respondió." },
{name:'2257',l:'22',c:'5',v:'7',texto:"Me hallaron los guardas que rondan la ciudad; Me golpearon, me hirieron; Me quitaron mi manto de encima los guardas de los muros." },
{name:'2258',l:'22',c:'5',v:'8',texto:"Yo os conjuro, oh doncellas de Jerusalén, si halláis a mi amado, Que le hagáis saber que estoy enferma de amor." },
{name:'2259',l:'22',c:'5',v:'9',texto:"¿Qué es tu amado más que otro amado, Oh la más hermosa de todas las mujeres? ¿Qué es tu amado más que otro amado, Que así nos conjuras? " },
{name:'22510',l:'22',c:'5',v:'10',texto:"Mi amado es blanco y rubio, Señalado entre diez mil." },
{name:'22511',l:'22',c:'5',v:'11',texto:"Su cabeza como oro finísimo; Sus cabellos crespos, negros como el cuervo." },
{name:'22512',l:'22',c:'5',v:'12',texto:"Sus ojos, como palomas junto a los arroyos de las aguas, Que se lavan con leche, y a la perfección colocados." },
{name:'22513',l:'22',c:'5',v:'13',texto:"Sus mejillas, como una era de especias aromáticas, como fragantes flores; Sus labios, como lirios que destilan mirra fragante." },
{name:'22514',l:'22',c:'5',v:'14',texto:"Sus manos, como anillos de oro engastados de jacintos; Su cuerpo, como claro marfil cubierto de zafiros." },
{name:'22515',l:'22',c:'5',v:'15',texto:"Sus piernas, como columnas de mármol fundadas sobre basas de oro fino; Su aspecto como el Líbano, escogido como los cedros." },
{name:'22516',l:'22',c:'5',v:'16',texto:"Su paladar, dulcísimo, y todo él codiciable. Tal es mi amado, tal es mi amigo, Oh doncellas de Jerusalén." },
],
numVersiculos: 16,
},

c6: {
versiculos:[
{name:'2261',l:'22',c:'6',v:'1',texto:"¿A dónde se ha ido tu amado, oh la más hermosa de todas las mujeres? ¿A dónde se apartó tu amado, Y lo buscaremos contigo? " },
{name:'2262',l:'22',c:'6',v:'2',texto:"Mi amado descendió a su huerto, a las eras de las especias, Para apacentar en los huertos, y para recoger los lirios." },
{name:'2263',l:'22',c:'6',v:'3',texto:"Yo soy de mi amado, y mi amado es mío; El apacienta entre los lirios." },
{name:'2264',l:'22',c:'6',v:'4',texto:"Hermosa eres tú, oh amiga mía, como Tirsa; De desear, como Jerusalén; Imponente como ejércitos en orden." },
{name:'2265',l:'22',c:'6',v:'5',texto:"Aparta tus ojos de delante de mí, Porque ellos me vencieron. Tu cabello es como manada de cabras Que se recuestan en las laderas de Galaad." },
{name:'2266',l:'22',c:'6',v:'6',texto:"Tus dientes, como manadas de ovejas que suben del lavadero, Todas con crías gemelas, Y estéril no hay entre ellas." },
{name:'2267',l:'22',c:'6',v:'7',texto:"Como cachos de granada son tus mejillas Detrás de tu velo." },
{name:'2268',l:'22',c:'6',v:'8',texto:"Sesenta son las reinas, y ochenta las concubinas, Y las doncellas sin número; " },
{name:'2269',l:'22',c:'6',v:'9',texto:"Mas una es la paloma mía, la perfecta mía; Es la única de su madre, La escogida de la que la dio a luz. La vieron las doncellas, y la llamaron bienaventurada; Las reinas y las concubinas, y la alabaron." },
{name:'22610',l:'22',c:'6',v:'10',texto:"¿Quién es ésta que se muestra como el alba, Hermosa como la luna, Esclarecida como el sol, Imponente como ejércitos en orden? " },
{name:'22611',l:'22',c:'6',v:'11',texto:"Al huerto de los nogales descendí A ver los frutos del valle, Y para ver si brotaban las vides, Si florecían los granados." },
{name:'22612',l:'22',c:'6',v:'12',texto:"Antes que lo supiera, mi alma me puso Entre los carros de Aminadab." },
{name:'22613',l:'22',c:'6',v:'13',texto:"Vuélvete, vuélvete, oh sulamita; Vuélvete, vuélvete, y te miraremos. ¿Qué veréis en la sulamita? Algo como la reunión de dos campamentos." },
],
numVersiculos: 13,
},

c7: {
versiculos:[
{name:'2271',l:'22',c:'7',v:'1',texto:"¡Cuán hermosos son tus pies en las sandalias, Oh hija de príncipe! Los contornos de tus muslos son como joyas, Obra de mano de excelente maestro." },
{name:'2272',l:'22',c:'7',v:'2',texto:"Tu ombligo como una taza redonda Que no le falta bebida. Tu vientre como montón de trigo Cercado de lirios." },
{name:'2273',l:'22',c:'7',v:'3',texto:"Tus dos pechos, como gemelos de gacela." },
{name:'2274',l:'22',c:'7',v:'4',texto:"Tu cuello, como torre de marfil; Tus ojos, como los estanques de Hesbón junto a la puerta de Bat-rabim; Tu nariz, como la torre del Líbano, Que mira hacia Damasco." },
{name:'2275',l:'22',c:'7',v:'5',texto:"Tu cabeza encima de ti, como el Carmelo; Y el cabello de tu cabeza, como la púrpura del rey Suspendida en los corredores." },
{name:'2276',l:'22',c:'7',v:'6',texto:"¡Qué hermosa eres, y cuán suave, Oh amor deleitoso! " },
{name:'2277',l:'22',c:'7',v:'7',texto:"Tu estatura es semejante a la palmera, Y tus pechos a los racimos." },
{name:'2278',l:'22',c:'7',v:'8',texto:"Yo dije: Subiré a la palmera, Asiré sus ramas. Deja que tus pechos sean como racimos de vid, Y el olor de tu boca como de manzanas," },
{name:'2279',l:'22',c:'7',v:'9',texto:"Y tu paladar como el buen vino, Que se entra a mi amado suavemente, Y hace hablar los labios de los viejos." },
{name:'22710',l:'22',c:'7',v:'10',texto:"Yo soy de mi amado, Y conmigo tiene su contentamiento." },
{name:'22711',l:'22',c:'7',v:'11',texto:"Ven, oh amado mío, salgamos al campo, Moremos en las aldeas." },
{name:'22712',l:'22',c:'7',v:'12',texto:"Levantémonos de mañana a las viñas; Veamos si brotan las vides, si están en cierne, Si han florecido los granados; Allí te daré mis amores." },
{name:'22713',l:'22',c:'7',v:'13',texto:"Las mandrágoras han dado olor, Y a nuestras puertas hay toda suerte de dulces frutas, Nuevas y añejas, que para ti, oh amado mío, he guardado." },
],
numVersiculos: 13,
},

c8: {
versiculos:[
{name:'2281',l:'22',c:'8',v:'1',texto:"¡Oh, si tú fueras como un hermano mío Que mamó los pechos de mi madre! Entonces, hallándote fuera, te besaría, Y no me menospreciarían." },
{name:'2282',l:'22',c:'8',v:'2',texto:"Yo te llevaría, te metería en casa de mi madre; Tú me enseñarías, Y yo te haría beber vino Adobado del mosto de mis granadas." },
{name:'2283',l:'22',c:'8',v:'3',texto:"Su izquierda esté debajo de mi cabeza, Y su derecha me abrace." },
{name:'2284',l:'22',c:'8',v:'4',texto:"Os conjuro, oh doncellas de Jerusalén, Que no despertéis ni hagáis velar al amor, Hasta que quiera." },
{name:'2285',l:'22',c:'8',v:'5',texto:"¿Quién es ésta que sube del desierto, Recostada sobre su amado? Debajo de un manzano te desperté; Allí tuvo tu madre dolores, Allí tuvo dolores la que te dio a luz." },
{name:'2286',l:'22',c:'8',v:'6',texto:"Ponme como un sello sobre tu corazón, como una marca sobre tu brazo; Porque fuerte es como la muerte el amor; Duros como el Seol los celos; Sus brasas, brasas de fuego, fuerte llama." },
{name:'2287',l:'22',c:'8',v:'7',texto:"Las muchas aguas no podrán apagar el amor, Ni lo ahogarán los ríos. Si diese el hombre todos los bienes de su casa por este amor, De cierto lo menospreciarían." },
{name:'2288',l:'22',c:'8',v:'8',texto:"Tenemos una pequeña hermana, Que no tiene pechos; ¿Qué haremos a nuestra hermana Cuando de ella se hablare? " },
{name:'2289',l:'22',c:'8',v:'9',texto:"Si ella es muro, Edificaremos sobre él un palacio de plata; Si fuere puerta, La guarneceremos con tablas de cedro." },
{name:'22810',l:'22',c:'8',v:'10',texto:"Yo soy muro, y mis pechos como torres, Desde que fui en sus ojos como la que halla paz." },
{name:'22811',l:'22',c:'8',v:'11',texto:"Salomón tuvo una viña en Baal-hamón, La cual entregó a guardas, Cada uno de los cuales debía traer mil monedas de plata por su fruto." },
{name:'22812',l:'22',c:'8',v:'12',texto:"Mi viña, que es mía, está delante de mí; Las mil serán tuyas, oh Salomón, Y doscientas para los que guardan su fruto." },
{name:'22813',l:'22',c:'8',v:'13',texto:"Oh, tú que habitas en los huertos, Los compañeros escuchan tu voz; Házmela oír." },
{name:'22814',l:'22',c:'8',v:'14',texto:"Apresúrate, amado mío, Y sé semejante al corzo, o al cervatillo, Sobre las montañas de los aromas." },
],
numVersiculos: 14,
},
	

};
