BibliaRVR60.lamentaciones = {
	libro: "Lamentaciones",
	numCapitulos: 5,

c1: {
versiculos:[
{name:'2511',l:'25',c:'1',v:'1',texto:"¡Cómo ha quedado sola la ciudad populosa! La grande entre las naciones se ha vuelto como viuda, La señora de provincias ha sido hecha tributaria." },
{name:'2512',l:'25',c:'1',v:'2',texto:"Amargamente llora en la noche, y sus lágrimas están en sus mejillas. No tiene quien la consuele de todos sus amantes; Todos sus amigos le faltaron, se le volvieron enemigos." },
{name:'2513',l:'25',c:'1',v:'3',texto:"Judá ha ido en cautiverio a causa de la aflicción y de la dura servidumbre; Ella habitó entre las naciones, y no halló descanso; Todos sus perseguidores la alcanzaron entre las estrechuras." },
{name:'2514',l:'25',c:'1',v:'4',texto:"Las calzadas de Sion tienen luto, porque no hay quien venga a las fiestas solemnes; Todas sus puertas están asoladas, sus sacerdotes gimen, Sus vírgenes están afligidas, y ella tiene amargura." },
{name:'2515',l:'25',c:'1',v:'5',texto:"Sus enemigos han sido hechos príncipes, sus aborrecedores fueron prosperados, Porque Jehová la afligió por la multitud de sus rebeliones; Sus hijos fueron en cautividad delante del enemigo." },
{name:'2516',l:'25',c:'1',v:'6',texto:"Desapareció de la hija de Sion toda su hermosura; Sus príncipes fueron como ciervos que no hallan pasto, Y anduvieron sin fuerzas delante del perseguidor." },
{name:'2517',l:'25',c:'1',v:'7',texto:"Jerusalén, cuando cayó su pueblo en mano del enemigo y no hubo quien la ayudase, Se acordó de los días de su aflicción, y de sus rebeliones, Y de todas las cosas agradables que tuvo desde los tiempos antiguos. La miraron los enemigos, y se burlaron de su caída." },
{name:'2518',l:'25',c:'1',v:'8',texto:"Pecado cometió Jerusalén, por lo cual ella ha sido removida; Todos los que la honraban la han menospreciado, porque vieron su vergüenza; Y ella suspira, y se vuelve atrás." },
{name:'2519',l:'25',c:'1',v:'9',texto:"Su inmundicia está en sus faldas, y no se acordó de su fin; Por tanto, ella ha descendido sorprendentemente, y no tiene quien la consuele. Mira, oh Jehová, mi aflicción, porque el enemigo se ha engrandecido." },
{name:'25110',l:'25',c:'1',v:'10',texto:"Extendió su mano el enemigo a todas sus cosas preciosas; Ella ha visto entrar en su santuario a las naciones De las cuales mandaste que no entrasen en tu congregación." },
{name:'25111',l:'25',c:'1',v:'11',texto:"Todo su pueblo buscó su pan suspirando; Dieron por la comida todas sus cosas preciosas, para entretener la vida. Mira, oh Jehová, y ve que estoy abatida." },
{name:'25112',l:'25',c:'1',v:'12',texto:"¿No os conmueve a cuantos pasáis por el camino? Mirad, y ved si hay dolor como mi dolor que me ha venido; Porque Jehová me ha angustiado en el día de su ardiente furor." },
{name:'25113',l:'25',c:'1',v:'13',texto:"Desde lo alto envió fuego que consume mis huesos; Ha extendido red a mis pies, me volvió atrás, Me dejó desolada, y con dolor todo el día." },
{name:'25114',l:'25',c:'1',v:'14',texto:"El yugo de mis rebeliones ha sido atado por su mano; Ataduras han sido echadas sobre mi cerviz; ha debilitado mis fuerzas; Me ha entregado el Señor en manos contra las cuales no podré levantarme." },
{name:'25115',l:'25',c:'1',v:'15',texto:"El Señor ha hollado a todos mis hombres fuertes en medio de mí; Llamó contra mí compañía para quebrantar a mis jóvenes; Como lagar ha hollado el Señor a la virgen hija de Judá." },
{name:'25116',l:'25',c:'1',v:'16',texto:"Por esta causa lloro; mis ojos, mis ojos fluyen aguas, Porque se alejó de mí el consolador que dé reposo a mi alma; Mis hijos son destruidos, porque el enemigo prevaleció." },
{name:'25117',l:'25',c:'1',v:'17',texto:"Sion extendió sus manos; no tiene quien la consuele; Jehová dio mandamiento contra Jacob, que sus vecinos fuesen sus enemigos; Jerusalén fue objeto de abominación entre ellos." },
{name:'25118',l:'25',c:'1',v:'18',texto:"Jehová es justo; yo contra su palabra me rebelé. Oíd ahora, pueblos todos, y ved mi dolor; Mis vírgenes y mis jóvenes fueron llevados en cautiverio." },
{name:'25119',l:'25',c:'1',v:'19',texto:"Di voces a mis amantes, mas ellos me han engañado; Mis sacerdotes y mis ancianos en la ciudad perecieron, Buscando comida para sí con que entretener su vida." },
{name:'25120',l:'25',c:'1',v:'20',texto:"Mira, oh Jehová, estoy atribulada, mis entrañas hierven. Mi corazón se trastorna dentro de mí, porque me rebelé en gran manera. Por fuera hizo estragos la espada; por dentro señoreó la muerte." },
{name:'25121',l:'25',c:'1',v:'21',texto:"Oyeron que gemía, mas no hay consolador para mí; Todos mis enemigos han oído mi mal, se alegran de lo que tú hiciste. Harás venir el día que has anunciado, y serán como yo." },
{name:'25122',l:'25',c:'1',v:'22',texto:"Venga delante de ti toda su maldad, Y haz con ellos como hiciste conmigo por todas mis rebeliones; Porque muchos son mis suspiros, y mi corazón está adolorido." },
],
numVersiculos: 22,
},

c2: {
versiculos:[
{name:'2521',l:'25',c:'2',v:'1',texto:"¡Cómo oscureció el Señor en su furor a la hija de Sion! Derribó del cielo a la tierra la hermosura de Israel, Y no se acordó del estrado de sus pies en el día de su furor." },
{name:'2522',l:'25',c:'2',v:'2',texto:"Destruyó el Señor, y no perdonó; Destruyó en su furor todas las tiendas de Jacob; Echó por tierra las fortalezas de la hija de Judá, Humilló al reino y a sus príncipes." },
{name:'2523',l:'25',c:'2',v:'3',texto:"Cortó con el ardor de su ira todo el poderío de Israel; Retiró de él su diestra frente al enemigo, Y se encendió en Jacob como llama de fuego que ha devorado alrededor." },
{name:'2524',l:'25',c:'2',v:'4',texto:"Entesó su arco como enemigo, afirmó su mano derecha como adversario, Y destruyó cuanto era hermoso. En la tienda de la hija de Sion derramó como fuego su enojo." },
{name:'2525',l:'25',c:'2',v:'5',texto:"El Señor llegó a ser como enemigo, destruyó a Israel; Destruyó todos sus palacios, derribó sus fortalezas, Y multiplicó en la hija de Judá la tristeza y el lamento." },
{name:'2526',l:'25',c:'2',v:'6',texto:"Quitó su tienda como enramada de huerto; Destruyó el lugar en donde se congregaban; Jehová ha hecho olvidar las fiestas solemnes y los días de reposo en Sion, Y en el ardor de su ira ha desechado al rey y al sacerdote." },
{name:'2527',l:'25',c:'2',v:'7',texto:"Desechó el Señor su altar, menospreció su santuario; Ha entregado en mano del enemigo los muros de sus palacios; Hicieron resonar su voz en la casa de Jehová como en día de fiesta." },
{name:'2528',l:'25',c:'2',v:'8',texto:"Jehová determinó destruir el muro de la hija de Sion; Extendió el cordel, no retrajo su mano de la destrucción; Hizo, pues, que se lamentara el antemuro y el muro; fueron desolados juntamente." },
{name:'2529',l:'25',c:'2',v:'9',texto:"Sus puertas fueron echadas por tierra, destruyó y quebrantó sus cerrojos; Su rey y sus príncipes están entre las naciones donde no hay ley; Sus profetas tampoco hallaron visión de Jehová." },
{name:'25210',l:'25',c:'2',v:'10',texto:"Se sentaron en tierra, callaron los ancianos de la hija de Sion; Echaron polvo sobre sus cabezas, se ciñeron de cilicio; Las vírgenes de Jerusalén bajaron sus cabezas a tierra." },
{name:'25211',l:'25',c:'2',v:'11',texto:"Mis ojos desfallecieron de lágrimas, se conmovieron mis entrañas, Mi hígado se derramó por tierra a causa del quebrantamiento de la hija de mi pueblo, Cuando desfallecía el niño y el que mamaba, en las plazas de la ciudad." },
{name:'25212',l:'25',c:'2',v:'12',texto:"Decían a sus madres: ¿Dónde está el trigo y el vino? Desfallecían como heridos en las calles de la ciudad, Derramando sus almas en el regazo de sus madres." },
{name:'25213',l:'25',c:'2',v:'13',texto:"¿Qué testigo te traeré, o a quién te haré semejante, hija de Jerusalén? ¿A quién te compararé para consolarte, oh virgen hija de Sion? Porque grande como el mar es tu quebrantamiento; ¿quién te sanará? " },
{name:'25214',l:'25',c:'2',v:'14',texto:"Tus profetas vieron para ti vanidad y locura; Y no descubrieron tu pecado para impedir tu cautiverio, Sino que te predicaron vanas profecías y extravíos." },
{name:'25215',l:'25',c:'2',v:'15',texto:"Todos los que pasaban por el camino batieron las manos sobre ti; Silbaron, y movieron despectivamente sus cabezas sobre la hija de Jerusalén, diciendo: ¿Es esta la ciudad que decían de perfecta hermosura, el gozo de toda la tierra? " },
{name:'25216',l:'25',c:'2',v:'16',texto:"Todos tus enemigos abrieron contra ti su boca; Se burlaron, y crujieron los dientes; dijeron: Devorémosla; Ciertamente este es el día que esperábamos; lo hemos hallado, lo hemos visto." },
{name:'25217',l:'25',c:'2',v:'17',texto:"Jehová ha hecho lo que tenía determinado; Ha cumplido su palabra, la cual él había mandado desde tiempo antiguo. Destruyó, y no perdonó; Y ha hecho que el enemigo se alegre sobre ti, Y enalteció el poder de tus adversarios." },
{name:'25218',l:'25',c:'2',v:'18',texto:"El corazón de ellos clamaba al Señor; Oh hija de Sion, echa lágrimas cual arroyo día y noche; No descanses, ni cesen las niñas de tus ojos." },
{name:'25219',l:'25',c:'2',v:'19',texto:"Levántate, da voces en la noche, al comenzar las vigilias; Derrama como agua tu corazón ante la presencia del Señor; Alza tus manos a él implorando la vida de tus pequeñitos, Que desfallecen de hambre en las entradas de todas las calles." },
{name:'25220',l:'25',c:'2',v:'20',texto:"Mira, oh Jehová, y considera a quién has hecho así. ¿Han de comer las mujeres el fruto de sus entrañas, los pequeñitos a su tierno cuidado? ¿Han de ser muertos en el santuario del Señor el sacerdote y el profeta? " },
{name:'25221',l:'25',c:'2',v:'21',texto:"Niños y viejos yacían por tierra en las calles; Mis vírgenes y mis jóvenes cayeron a espada; Mataste en el día de tu furor; degollaste, no perdonaste." },
{name:'25222',l:'25',c:'2',v:'22',texto:"Has convocado de todas partes mis temores, como en un día de solemnidad; Y en el día del furor de Jehová no hubo quien escapase ni quedase vivo; Los que crié y mantuve, mi enemigo los acabó." },
],
numVersiculos: 22,
},

c3: {
versiculos:[
{name:'2531',l:'25',c:'3',v:'1',texto:"Yo soy el hombre que ha visto aflicción bajo el látigo de su enojo." },
{name:'2532',l:'25',c:'3',v:'2',texto:"Me guió y me llevó en tinieblas, y no en luz; " },
{name:'2533',l:'25',c:'3',v:'3',texto:"Ciertamente contra mí volvió y revolvió su mano todo el día." },
{name:'2534',l:'25',c:'3',v:'4',texto:"Hizo envejecer mi carne y mi piel; quebrantó mis huesos; " },
{name:'2535',l:'25',c:'3',v:'5',texto:"Edificó baluartes contra mí, y me rodeó de amargura y de trabajo." },
{name:'2536',l:'25',c:'3',v:'6',texto:"Me dejó en oscuridad, como los ya muertos de mucho tiempo." },
{name:'2537',l:'25',c:'3',v:'7',texto:"Me cercó por todos lados, y no puedo salir; ha hecho más pesadas mis cadenas; " },
{name:'2538',l:'25',c:'3',v:'8',texto:"Aun cuando clamé y di voces, cerró los oídos a mi oración; " },
{name:'2539',l:'25',c:'3',v:'9',texto:"Cercó mis caminos con piedra labrada, torció mis senderos." },
{name:'25310',l:'25',c:'3',v:'10',texto:"Fue para mí como oso que acecha, como león en escondrijos; " },
{name:'25311',l:'25',c:'3',v:'11',texto:"Torció mis caminos, y me despedazó; me dejó desolado." },
{name:'25312',l:'25',c:'3',v:'12',texto:"Entesó su arco, y me puso como blanco para la saeta." },
{name:'25313',l:'25',c:'3',v:'13',texto:"Hizo entrar en mis entrañas las saetas de su aljaba." },
{name:'25314',l:'25',c:'3',v:'14',texto:"Fui escarnio a todo mi pueblo, burla de ellos todos los días; " },
{name:'25315',l:'25',c:'3',v:'15',texto:"Me llenó de amarguras, me embriagó de ajenjos." },
{name:'25316',l:'25',c:'3',v:'16',texto:"Mis dientes quebró con cascajo, me cubrió de ceniza; " },
{name:'25317',l:'25',c:'3',v:'17',texto:"Y mi alma se alejó de la paz, me olvidé del bien," },
{name:'25318',l:'25',c:'3',v:'18',texto:"Y dije: Perecieron mis fuerzas, y mi esperanza en Jehová." },
{name:'25319',l:'25',c:'3',v:'19',texto:"Acuérdate de mi aflicción y de mi abatimiento, del ajenjo y de la hiel; " },
{name:'25320',l:'25',c:'3',v:'20',texto:"Lo tendré aún en memoria, porque mi alma está abatida dentro de mí; " },
{name:'25321',l:'25',c:'3',v:'21',texto:"Esto recapacitaré en mi corazón, por lo tanto esperaré." },
{name:'25322',l:'25',c:'3',v:'22',texto:"Por la misericordia de Jehová no hemos sido consumidos, porque nunca decayeron sus misericordias." },
{name:'25323',l:'25',c:'3',v:'23',texto:"Nuevas son cada mañana; grande es tu fidelidad." },
{name:'25324',l:'25',c:'3',v:'24',texto:"Mi porción es Jehová, dijo mi alma; por tanto, en él esperaré." },
{name:'25325',l:'25',c:'3',v:'25',texto:"Bueno es Jehová a los que en él esperan, al alma que le busca." },
{name:'25326',l:'25',c:'3',v:'26',texto:"Bueno es esperar en silencio la salvación de Jehová." },
{name:'25327',l:'25',c:'3',v:'27',texto:"Bueno le es al hombre llevar el yugo desde su juventud." },
{name:'25328',l:'25',c:'3',v:'28',texto:"Que se siente solo y calle, porque es Dios quien se lo impuso; " },
{name:'25329',l:'25',c:'3',v:'29',texto:"Ponga su boca en el polvo, por si aún hay esperanza; " },
{name:'25330',l:'25',c:'3',v:'30',texto:"Dé la mejilla al que le hiere, y sea colmado de afrentas." },
{name:'25331',l:'25',c:'3',v:'31',texto:"Porque el Señor no desecha para siempre; " },
{name:'25332',l:'25',c:'3',v:'32',texto:"Antes si aflige, también se compadece según la multitud de sus misericordias; " },
{name:'25333',l:'25',c:'3',v:'33',texto:"Porque no aflige ni entristece voluntariamente a los hijos de los hombres." },
{name:'25334',l:'25',c:'3',v:'34',texto:"Desmenuzar bajo los pies a todos los encarcelados de la tierra," },
{name:'25335',l:'25',c:'3',v:'35',texto:"Torcer el derecho del hombre delante de la presencia del Altísimo," },
{name:'25336',l:'25',c:'3',v:'36',texto:"Trastornar al hombre en su causa, el Señor no lo aprueba." },
{name:'25337',l:'25',c:'3',v:'37',texto:"¿Quién será aquel que diga que sucedió algo que el Señor no mandó? " },
{name:'25338',l:'25',c:'3',v:'38',texto:"¿De la boca del Altísimo no sale lo malo y lo bueno? " },
{name:'25339',l:'25',c:'3',v:'39',texto:"¿Por qué se lamenta el hombre viviente? Laméntese el hombre en su pecado." },
{name:'25340',l:'25',c:'3',v:'40',texto:"Escudriñemos nuestros caminos, y busquemos, y volvámonos a Jehová; " },
{name:'25341',l:'25',c:'3',v:'41',texto:"Levantemos nuestros corazones y manos a Dios en los cielos; " },
{name:'25342',l:'25',c:'3',v:'42',texto:"Nosotros nos hemos rebelado, y fuimos desleales; tú no perdonaste." },
{name:'25343',l:'25',c:'3',v:'43',texto:"Desplegaste la ira y nos perseguiste; mataste, y no perdonaste; " },
{name:'25344',l:'25',c:'3',v:'44',texto:"Te cubriste de nube para que no pasase la oración nuestra; " },
{name:'25345',l:'25',c:'3',v:'45',texto:"Nos volviste en oprobio y abominación en medio de los pueblos." },
{name:'25346',l:'25',c:'3',v:'46',texto:"Todos nuestros enemigos abrieron contra nosotros su boca; " },
{name:'25347',l:'25',c:'3',v:'47',texto:"Temor y lazo fueron para nosotros, asolamiento y quebranto; " },
{name:'25348',l:'25',c:'3',v:'48',texto:"Ríos de aguas echan mis ojos por el quebrantamiento de la hija de mi pueblo." },
{name:'25349',l:'25',c:'3',v:'49',texto:"Mis ojos destilan y no cesan, porque no hay alivio " },
{name:'25350',l:'25',c:'3',v:'50',texto:"Hasta que Jehová mire y vea desde los cielos; " },
{name:'25351',l:'25',c:'3',v:'51',texto:"Mis ojos contristaron mi alma por todas las hijas de mi ciudad." },
{name:'25352',l:'25',c:'3',v:'52',texto:"Mis enemigos me dieron caza como a ave, sin haber por qué; " },
{name:'25353',l:'25',c:'3',v:'53',texto:"Ataron mi vida en cisterna, pusieron piedra sobre mí; " },
{name:'25354',l:'25',c:'3',v:'54',texto:"Aguas cubrieron mi cabeza; yo dije: Muerto soy." },
{name:'25355',l:'25',c:'3',v:'55',texto:"Invoqué tu nombre, oh Jehová, desde la cárcel profunda; " },
{name:'25356',l:'25',c:'3',v:'56',texto:"Oíste mi voz; no escondas tu oído al clamor de mis suspiros." },
{name:'25357',l:'25',c:'3',v:'57',texto:"Te acercaste el día que te invoqué; dijiste: No temas." },
{name:'25358',l:'25',c:'3',v:'58',texto:"Abogaste, Señor, la causa de mi alma; redimiste mi vida." },
{name:'25359',l:'25',c:'3',v:'59',texto:"Tú has visto, oh Jehová, mi agravio; defiende mi causa." },
{name:'25360',l:'25',c:'3',v:'60',texto:"Has visto toda su venganza, todos sus pensamientos contra mí." },
{name:'25361',l:'25',c:'3',v:'61',texto:"Has oído el oprobio de ellos, oh Jehová, todas sus maquinaciones contra mí; " },
{name:'25362',l:'25',c:'3',v:'62',texto:"Los dichos de los que contra mí se levantaron, y su designio contra mí todo el día." },
{name:'25363',l:'25',c:'3',v:'63',texto:"Su sentarse y su levantarse mira; yo soy su canción." },
{name:'25364',l:'25',c:'3',v:'64',texto:"Dales el pago, oh Jehová, según la obra de sus manos." },
{name:'25365',l:'25',c:'3',v:'65',texto:"Entrégalos al endurecimiento de corazón; tu maldición caiga sobre ellos." },
{name:'25366',l:'25',c:'3',v:'66',texto:"Persíguelos en tu furor, y quebrántalos de debajo de los cielos, oh Jehová." },
],
numVersiculos: 66,
},

c4: {
versiculos:[
{name:'2541',l:'25',c:'4',v:'1',texto:"¡Cómo se ha ennegrecido el oro! ¡Cómo el buen oro ha perdido su brillo! Las piedras del santuario están esparcidas por las encrucijadas de todas las calles." },
{name:'2542',l:'25',c:'4',v:'2',texto:"Los hijos de Sion, preciados y estimados más que el oro puro, ¡Cómo son tenidos por vasijas de barro, obra de manos de alfarero! " },
{name:'2543',l:'25',c:'4',v:'3',texto:"Aun los chacales dan la teta, y amamantan a sus cachorros; La hija de mi pueblo es cruel como los avestruces en el desierto." },
{name:'2544',l:'25',c:'4',v:'4',texto:"La lengua del niño de pecho se pegó a su paladar por la sed; Los pequeñuelos pidieron pan, y no hubo quien se lo repartiese." },
{name:'2545',l:'25',c:'4',v:'5',texto:"Los que comían delicadamente fueron asolados en las calles; Los que se criaron entre púrpura se abrazaron a los estercoleros." },
{name:'2546',l:'25',c:'4',v:'6',texto:"Porque se aumentó la iniquidad de la hija de mi pueblo más que el pecado de Sodoma, Que fue destruida en un momento, sin que acamparan contra ella compañías." },
{name:'2547',l:'25',c:'4',v:'7',texto:"Sus nobles fueron más puros que la nieve, más blancos que la leche; Más rubios eran sus cuerpos que el coral, su talle más hermoso que el zafiro." },
{name:'2548',l:'25',c:'4',v:'8',texto:"Oscuro más que la negrura es su aspecto; no los conocen por las calles; Su piel está pegada a sus huesos, seca como un palo." },
{name:'2549',l:'25',c:'4',v:'9',texto:"Más dichosos fueron los muertos a espada que los muertos por el hambre; Porque éstos murieron poco a poco por falta de los frutos de la tierra." },
{name:'25410',l:'25',c:'4',v:'10',texto:"Las manos de mujeres piadosas cocieron a sus hijos; Sus propios hijos les sirvieron de comida en el día del quebrantamiento de la hija de mi pueblo." },
{name:'25411',l:'25',c:'4',v:'11',texto:"Cumplió Jehová su enojo, derramó el ardor de su ira; Y encendió en Sion fuego que consumió hasta sus cimientos." },
{name:'25412',l:'25',c:'4',v:'12',texto:"Nunca los reyes de la tierra, ni todos los que habitan en el mundo, Creyeron que el enemigo y el adversario entrara por las puertas de Jerusalén." },
{name:'25413',l:'25',c:'4',v:'13',texto:"Es por causa de los pecados de sus profetas, y las maldades de sus sacerdotes, Quienes derramaron en medio de ella la sangre de los justos." },
{name:'25414',l:'25',c:'4',v:'14',texto:"Titubearon como ciegos en las calles, fueron contaminados con sangre, De modo que no pudiesen tocarse sus vestiduras." },
{name:'25415',l:'25',c:'4',v:'15',texto:"¡Apartaos! ¡Inmundos! les gritaban; ¡Apartaos, apartaos, no toquéis! Huyeron y fueron dispersados; se dijo entre las naciones: Nunca más morarán aquí." },
{name:'25416',l:'25',c:'4',v:'16',texto:"La ira de Jehová los apartó, no los mirará más; No respetaron la presencia de los sacerdotes, ni tuvieron compasión de los viejos." },
{name:'25417',l:'25',c:'4',v:'17',texto:"Aun han desfallecido nuestros ojos esperando en vano nuestro socorro; En nuestra esperanza aguardamos a una nación que no puede salvar." },
{name:'25418',l:'25',c:'4',v:'18',texto:"Cazaron nuestros pasos, para que no anduviésemos por nuestras calles; Se acercó nuestro fin, se cumplieron nuestros días; porque llegó nuestro fin." },
{name:'25419',l:'25',c:'4',v:'19',texto:"Ligeros fueron nuestros perseguidores más que las águilas del cielo; Sobre los montes nos persiguieron, en el desierto nos pusieron emboscadas." },
{name:'25420',l:'25',c:'4',v:'20',texto:"El aliento de nuestras vidas, el ungido de Jehová, De quien habíamos dicho: A su sombra tendremos vida entre las naciones, fue apresado en sus lazos." },
{name:'25421',l:'25',c:'4',v:'21',texto:"Gózate y alégrate, hija de Edom, la que habitas en tierra de Uz; Aun hasta ti llegará la copa; te embriagarás, y vomitarás." },
{name:'25422',l:'25',c:'4',v:'22',texto:"Se ha cumplido tu castigo, oh hija de Sion; Nunca más te hará llevar cautiva. Castigará tu iniquidad, oh hija de Edom; Descubrirá tus pecados." },
],
numVersiculos: 22,
},

c5: {
versiculos:[
{name:'2551',l:'25',c:'5',v:'1',texto:"Acuérdate, oh Jehová, de lo que nos ha sucedido; Mira, y ve nuestro oprobio." },
{name:'2552',l:'25',c:'5',v:'2',texto:"Nuestra heredad ha pasado a extraños, Nuestras casas a forasteros." },
{name:'2553',l:'25',c:'5',v:'3',texto:"Huérfanos somos sin padre; Nuestras madres son como viudas." },
{name:'2554',l:'25',c:'5',v:'4',texto:"Nuestra agua bebemos por dinero; Compramos nuestra leña por precio." },
{name:'2555',l:'25',c:'5',v:'5',texto:"Padecemos persecución sobre nosotros; Nos fatigamos, y no hay para nosotros reposo." },
{name:'2556',l:'25',c:'5',v:'6',texto:"Al egipcio y al asirio extendimos la mano, para saciarnos de pan." },
{name:'2557',l:'25',c:'5',v:'7',texto:"Nuestros padres pecaron, y han muerto; Y nosotros llevamos su castigo." },
{name:'2558',l:'25',c:'5',v:'8',texto:"Siervos se enseñorearon de nosotros; No hubo quien nos librase de su mano." },
{name:'2559',l:'25',c:'5',v:'9',texto:"Con peligro de nuestras vidas traíamos nuestro pan Ante la espada del desierto." },
{name:'25510',l:'25',c:'5',v:'10',texto:"Nuestra piel se ennegreció como un horno A causa del ardor del hambre." },
{name:'25511',l:'25',c:'5',v:'11',texto:"Violaron a las mujeres en Sion, A las vírgenes en las ciudades de Judá." },
{name:'25512',l:'25',c:'5',v:'12',texto:"A los príncipes colgaron de las manos; No respetaron el rostro de los viejos." },
{name:'25513',l:'25',c:'5',v:'13',texto:"Llevaron a los jóvenes a moler, Y los muchachos desfallecieron bajo el peso de la leña." },
{name:'25514',l:'25',c:'5',v:'14',texto:"Los ancianos no se ven más en la puerta, Los jóvenes dejaron sus canciones." },
{name:'25515',l:'25',c:'5',v:'15',texto:"Cesó el gozo de nuestro corazón; Nuestra danza se cambió en luto." },
{name:'25516',l:'25',c:'5',v:'16',texto:"Cayó la corona de nuestra cabeza; ¡Ay ahora de nosotros! porque pecamos." },
{name:'25517',l:'25',c:'5',v:'17',texto:"Por esto fue entristecido nuestro corazón, Por esto se entenebrecieron nuestros ojos," },
{name:'25518',l:'25',c:'5',v:'18',texto:"Por el monte de Sion que está asolado; Zorras andan por él." },
{name:'25519',l:'25',c:'5',v:'19',texto:"Mas tú, Jehová, permanecerás para siempre; Tu trono de generación en generación." },
{name:'25520',l:'25',c:'5',v:'20',texto:"¿Por qué te olvidas completamente de nosotros, Y nos abandonas tan largo tiempo? " },
{name:'25521',l:'25',c:'5',v:'21',texto:"Vuélvenos, oh Jehová, a ti, y nos volveremos; Renueva nuestros días como al principio." },
{name:'25522',l:'25',c:'5',v:'22',texto:"Porque nos has desechado; Te has airado contra nosotros en gran manera." },
],
numVersiculos: 22,
},
	

};
