BibliaRVR60.joel = {
	libro: "Joel",
	numCapitulos: 3,

c1: {
versiculos:[
{name:'2911',l:'29',c:'1',v:'1',texto:"Palabra de Jehová que vino a Joel, hijo de Petuel." },
{name:'2912',l:'29',c:'1',v:'2',texto:"Oíd esto, ancianos, y escuchad, todos los moradores de la tierra. ¿Ha acontecido esto en vuestros días, o en los días de vuestros padres? " },
{name:'2913',l:'29',c:'1',v:'3',texto:"De esto contaréis a vuestros hijos, y vuestros hijos a sus hijos, y sus hijos a la otra generación." },
{name:'2914',l:'29',c:'1',v:'4',texto:"Lo que quedó de la oruga comió el saltón, y lo que quedó del saltón comió el revoltón; y la langosta comió lo que del revoltón había quedado." },
{name:'2915',l:'29',c:'1',v:'5',texto:"Despertad, borrachos, y llorad; gemid, todos los que bebéis vino, a causa del mosto, porque os es quitado de vuestra boca." },
{name:'2916',l:'29',c:'1',v:'6',texto:"Porque pueblo fuerte e innumerable subió a mi tierra; sus dientes son dientes de león, y sus muelas, muelas de león." },
{name:'2917',l:'29',c:'1',v:'7',texto:"Asoló mi vid, y descortezó mi higuera; del todo la desnudó y derribó; sus ramas quedaron blancas." },
{name:'2918',l:'29',c:'1',v:'8',texto:"Llora tú como joven vestida de cilicio por el marido de su juventud." },
{name:'2919',l:'29',c:'1',v:'9',texto:"Desapareció de la casa de Jehová la ofrenda y la libación; los sacerdotes ministros de Jehová están de duelo." },
{name:'29110',l:'29',c:'1',v:'10',texto:"El campo está asolado, se enlutó la tierra; porque el trigo fue destruido, se secó el mosto, se perdió el aceite." },
{name:'29111',l:'29',c:'1',v:'11',texto:"Confundíos, labradores; gemid, viñeros, por el trigo y la cebada, porque se perdió la mies del campo." },
{name:'29112',l:'29',c:'1',v:'12',texto:"La vid está seca, y pereció la higuera; el granado también, la palmera y el manzano; todos los árboles del campo se secaron, por lo cual se extinguió el gozo de los hijos de los hombres." },
{name:'29113',l:'29',c:'1',v:'13',texto:"Ceñíos y lamentad, sacerdotes; gemid, ministros del altar; venid, dormid en cilicio, ministros de mi Dios; porque quitada es de la casa de vuestro Dios la ofrenda y la libación." },
{name:'29114',l:'29',c:'1',v:'14',texto:"Proclamad ayuno, convocad a asamblea; congregad a los ancianos y a todos los moradores de la tierra en la casa de Jehová vuestro Dios, y clamad a Jehová." },
{name:'29115',l:'29',c:'1',v:'15',texto:"¡Ay del día! porque cercano está el día de Jehová, y vendrá como destrucción por el Todopoderoso." },
{name:'29116',l:'29',c:'1',v:'16',texto:"¿No fue arrebatado el alimento de delante de nuestros ojos, la alegría y el placer de la casa de nuestro Dios? " },
{name:'29117',l:'29',c:'1',v:'17',texto:"El grano se pudrió debajo de los terrones, los graneros fueron asolados, los alfolíes destruidos; porque se secó el trigo." },
{name:'29118',l:'29',c:'1',v:'18',texto:"¡Cómo gimieron las bestias! ¡cuán turbados anduvieron los hatos de los bueyes, porque no tuvieron pastos! También fueron asolados los rebaños de las ovejas." },
{name:'29119',l:'29',c:'1',v:'19',texto:"A ti, oh Jehová, clamaré; porque fuego consumió los pastos del desierto, y llama abrasó todos los árboles del campo." },
{name:'29120',l:'29',c:'1',v:'20',texto:"Las bestias del campo bramarán también a ti, porque se secaron los arroyos de las aguas, y fuego consumió las praderas del desierto." },
],
numVersiculos: 20,
},

c2: {
versiculos:[
{name:'2921',l:'29',c:'2',v:'1',texto:"Tocad trompeta en Sion, y dad alarma en mi santo monte; tiemblen todos los moradores de la tierra, porque viene el día de Jehová, porque está cercano." },
{name:'2922',l:'29',c:'2',v:'2',texto:"Día de tinieblas y de oscuridad, día de nube y de sombra; como sobre los montes se extiende el alba, así vendrá un pueblo grande y fuerte; semejante a él no lo hubo jamás, ni después de él lo habrá en años de muchas generaciones." },
{name:'2923',l:'29',c:'2',v:'3',texto:"Delante de él consumirá fuego, tras de él abrasará llama; como el huerto del Edén será la tierra delante de él, y detrás de él como desierto asolado; ni tampoco habrá quien de él escape." },
{name:'2924',l:'29',c:'2',v:'4',texto:"Su aspecto, como aspecto de caballos, y como gente de a caballo correrán." },
{name:'2925',l:'29',c:'2',v:'5',texto:"Como estruendo de carros saltarán sobre las cumbres de los montes; como sonido de llama de fuego que consume hojarascas, como pueblo fuerte dispuesto para la batalla." },
{name:'2926',l:'29',c:'2',v:'6',texto:"Delante de él temerán los pueblos; se pondrán pálidos todos los semblantes." },
{name:'2927',l:'29',c:'2',v:'7',texto:"Como valientes correrán, como hombres de guerra subirán el muro; cada cual marchará por su camino, y no torcerá su rumbo." },
{name:'2928',l:'29',c:'2',v:'8',texto:"Ninguno estrechará a su compañero, cada uno irá por su carrera; y aun cayendo sobre la espada no se herirán." },
{name:'2929',l:'29',c:'2',v:'9',texto:"Irán por la ciudad, correrán por el muro, subirán por las casas, entrarán por las ventanas a manera de ladrones." },
{name:'29210',l:'29',c:'2',v:'10',texto:"Delante de él temblará la tierra, se estremecerán los cielos; el sol y la luna se oscurecerán, y las estrellas retraerán su resplandor." },
{name:'29211',l:'29',c:'2',v:'11',texto:"Y Jehová dará su orden delante de su ejército; porque muy grande es su campamento; fuerte es el que ejecuta su orden; porque grande es el día de Jehová, y muy terrible; ¿quién podrá soportarlo? " },
{name:'29212',l:'29',c:'2',v:'12',texto:"Por eso pues, ahora, dice Jehová, convertíos a mí con todo vuestro corazón, con ayuno y lloro y lamento." },
{name:'29213',l:'29',c:'2',v:'13',texto:"Rasgad vuestro corazón, y no vuestros vestidos, y convertíos a Jehová vuestro Dios; porque misericordioso es y clemente, tardo para la ira y grande en misericordia, y que se duele del castigo." },
{name:'29214',l:'29',c:'2',v:'14',texto:"¿Quién sabe si volverá y se arrepentirá y dejará bendición tras de él, esto es, ofrenda y libación para Jehová vuestro Dios? " },
{name:'29215',l:'29',c:'2',v:'15',texto:"Tocad trompeta en Sion, proclamad ayuno, convocad asamblea." },
{name:'29216',l:'29',c:'2',v:'16',texto:"Reunid al pueblo, santificad la reunión, juntad a los ancianos, congregad a los niños y a los que maman, salga de su cámara el novio, y de su tálamo la novia." },
{name:'29217',l:'29',c:'2',v:'17',texto:"Entre la entrada y el altar lloren los sacerdotes ministros de Jehová, y digan: Perdona, oh Jehová, a tu pueblo, y no entregues al oprobio tu heredad, para que las naciones se enseñoreen de ella. ¿Por qué han de decir entre los pueblos: Dónde está su Dios? " },
{name:'29218',l:'29',c:'2',v:'18',texto:"Y Jehová, solícito por su tierra, perdonará a su pueblo." },
{name:'29219',l:'29',c:'2',v:'19',texto:"Responderá Jehová, y dirá a su pueblo: He aquí yo os envío pan, mosto y aceite, y seréis saciados de ellos; y nunca más os pondré en oprobio entre las naciones." },
{name:'29220',l:'29',c:'2',v:'20',texto:"Y haré alejar de vosotros al del norte, y lo echaré en tierra seca y desierta; su faz será hacia el mar oriental, y su fin al mar occidental; y exhalará su hedor, y subirá su pudrición, porque hizo grandes cosas." },
{name:'29221',l:'29',c:'2',v:'21',texto:"Tierra, no temas; alégrate y gózate, porque Jehová hará grandes cosas." },
{name:'29222',l:'29',c:'2',v:'22',texto:"Animales del campo, no temáis; porque los pastos del desierto reverdecerán, porque los árboles llevarán su fruto, la higuera y la vid darán sus frutos." },
{name:'29223',l:'29',c:'2',v:'23',texto:"Vosotros también, hijos de Sion, alegraos y gozaos en Jehová vuestro Dios; porque os ha dado la primera lluvia a su tiempo, y hará descender sobre vosotros lluvia temprana y tardía como al principio." },
{name:'29224',l:'29',c:'2',v:'24',texto:"Las eras se llenarán de trigo, y los lagares rebosarán de vino y aceite." },
{name:'29225',l:'29',c:'2',v:'25',texto:"Y os restituiré los años que comió la oruga, el saltón, el revoltón y la langosta, mi gran ejército que envié contra vosotros." },
{name:'29226',l:'29',c:'2',v:'26',texto:"Comeréis hasta saciaros, y alabaréis el nombre de Jehová vuestro Dios, el cual hizo maravillas con vosotros; y nunca jamás será mi pueblo avergonzado." },
{name:'29227',l:'29',c:'2',v:'27',texto:"Y conoceréis que en medio de Israel estoy yo, y que yo soy Jehová vuestro Dios, y no hay otro; y mi pueblo nunca jamás será avergonzado." },
{name:'29228',l:'29',c:'2',v:'28',texto:"Y después de esto derramaré mi Espíritu sobre toda carne, y profetizarán vuestros hijos y vuestras hijas; vuestros ancianos soñarán sueños, y vuestros jóvenes verán visiones." },
{name:'29229',l:'29',c:'2',v:'29',texto:"Y también sobre los siervos y sobre las siervas derramaré mi Espíritu en aquellos días." },
{name:'29230',l:'29',c:'2',v:'30',texto:"Y daré prodigios en el cielo y en la tierra, sangre, y fuego, y columnas de humo." },
{name:'29231',l:'29',c:'2',v:'31',texto:"El sol se convertirá en tinieblas, y la luna en sangre, antes que venga el día grande y espantoso de Jehová." },
{name:'29232',l:'29',c:'2',v:'32',texto:"Y todo aquel que invocare el nombre de Jehová será salvo; porque en el monte de Sion y en Jerusalén habrá salvación, como ha dicho Jehová, y entre el remanente al cual él habrá llamado." },
],
numVersiculos: 32,
},

c3: {
versiculos:[
{name:'2931',l:'29',c:'3',v:'1',texto:"Porque he aquí que en aquellos días, y en aquel tiempo en que haré volver la cautividad de Judá y de Jerusalén," },
{name:'2932',l:'29',c:'3',v:'2',texto:"reuniré a todas las naciones, y las haré descender al valle de Josafat, y allí entraré en juicio con ellas a causa de mi pueblo, y de Israel mi heredad, a quien ellas esparcieron entre las naciones, y repartieron mi tierra; " },
{name:'2933',l:'29',c:'3',v:'3',texto:"y echaron suertes sobre mi pueblo, y dieron los niños por una ramera, y vendieron las niñas por vino para beber." },
{name:'2934',l:'29',c:'3',v:'4',texto:"Y también, ¿qué tengo yo con vosotras, Tiro y Sidón, y todo el territorio de Filistea? ¿Queréis vengaros de mí? Y si de mí os vengáis, bien pronto haré yo recaer la paga sobre vuestra cabeza." },
{name:'2935',l:'29',c:'3',v:'5',texto:"Porque habéis llevado mi plata y mi oro, y mis cosas preciosas y hermosas metisteis en vuestros templos; " },
{name:'2936',l:'29',c:'3',v:'6',texto:"y vendisteis los hijos de Judá y los hijos de Jerusalén a los hijos de los griegos, para alejarlos de su tierra." },
{name:'2937',l:'29',c:'3',v:'7',texto:"He aquí yo los levantaré del lugar donde los vendisteis, y volveré vuestra paga sobre vuestra cabeza; " },
{name:'2938',l:'29',c:'3',v:'8',texto:"y venderé vuestros hijos y vuestras hijas a los hijos de Judá, y ellos los venderán a los sabeos, nación lejana; porque Jehová ha hablado." },
{name:'2939',l:'29',c:'3',v:'9',texto:"Proclamad esto entre las naciones, proclamad guerra, despertad a los valientes, acérquense, vengan todos los hombres de guerra." },
{name:'29310',l:'29',c:'3',v:'10',texto:"Forjad espadas de vuestros azadones, lanzas de vuestras hoces; diga el débil: Fuerte soy." },
{name:'29311',l:'29',c:'3',v:'11',texto:"Juntaos y venid, naciones todas de alrededor, y congregaos; haz venir allí, oh Jehová, a tus fuertes." },
{name:'29312',l:'29',c:'3',v:'12',texto:"Despiértense las naciones, y suban al valle de Josafat; porque allí me sentaré para juzgar a todas las naciones de alrededor." },
{name:'29313',l:'29',c:'3',v:'13',texto:"Echad la hoz, porque la mies está ya madura. Venid, descended, porque el lagar está lleno, rebosan las cubas; porque mucha es la maldad de ellos." },
{name:'29314',l:'29',c:'3',v:'14',texto:"Muchos pueblos en el valle de la decisión; porque cercano está el día de Jehová en el valle de la decisión." },
{name:'29315',l:'29',c:'3',v:'15',texto:"El sol y la luna se oscurecerán, y las estrellas retraerán su resplandor." },
{name:'29316',l:'29',c:'3',v:'16',texto:"Y Jehová rugirá desde Sion, y dará su voz desde Jerusalén, y temblarán los cielos y la tierra; pero Jehová será la esperanza de su pueblo, y la fortaleza de los hijos de Israel." },
{name:'29317',l:'29',c:'3',v:'17',texto:"Y conoceréis que yo soy Jehová vuestro Dios, que habito en Sion, mi santo monte; y Jerusalén será santa, y extraños no pasarán más por ella." },
{name:'29318',l:'29',c:'3',v:'18',texto:"Sucederá en aquel tiempo, que los montes destilarán mosto, y los collados fluirán leche, y por todos los arroyos de Judá correrán aguas; y saldrá una fuente de la casa de Jehová, y regará el valle de Sitim." },
{name:'29319',l:'29',c:'3',v:'19',texto:"Egipto será destruido, y Edom será vuelto en desierto asolado, por la injuria hecha a los hijos de Judá; porque derramaron en su tierra sangre inocente." },
{name:'29320',l:'29',c:'3',v:'20',texto:"Pero Judá será habitada para siempre, y Jerusalén por generación y generación." },
{name:'29321',l:'29',c:'3',v:'21',texto:"Y limpiaré la sangre de los que no había limpiado; y Jehová morará en Sion." },
],
numVersiculos: 21,
},


};
