BibliaRVR60.amos = {
	libro: "Amós",
	numCapitulos: 9,

c1: {
versiculos:[
{name:'3011',l:'30',c:'1',v:'1',texto:"Las palabras de Amós, que fue uno de los pastores de Tecoa, que profetizó acerca de Israel en días de Uzías rey de Judá y en días de Jeroboam hijo de Joás, rey de Israel, dos años antes del terremoto." },
{name:'3012',l:'30',c:'1',v:'2',texto:"Dijo: Jehová rugirá desde Sion, y dará su voz desde Jerusalén, y los campos de los pastores se enlutarán, y se secará la cumbre del Carmelo." },
{name:'3013',l:'30',c:'1',v:'3',texto:"Así ha dicho Jehová: Por tres pecados de Damasco, y por el cuarto, no revocaré su castigo; porque trillaron a Galaad con trillos de hierro." },
{name:'3014',l:'30',c:'1',v:'4',texto:"Prenderé fuego en la casa de Hazael, y consumirá los palacios de Ben-adad." },
{name:'3015',l:'30',c:'1',v:'5',texto:"Y quebraré los cerrojos de Damasco, y destruiré a los moradores del valle de Avén, y los gobernadores de Bet-edén; y el pueblo de Siria será transportado a Kir, dice Jehová." },
{name:'3016',l:'30',c:'1',v:'6',texto:"Así ha dicho Jehová: Por tres pecados de Gaza, y por el cuarto, no revocaré su castigo; porque llevó cautivo a todo un pueblo para entregarlo a Edom." },
{name:'3017',l:'30',c:'1',v:'7',texto:"Prenderé fuego en el muro de Gaza, y consumirá sus palacios." },
{name:'3018',l:'30',c:'1',v:'8',texto:"Y destruiré a los moradores de Asdod, y a los gobernadores de Ascalón; y volveré mi mano contra Ecrón, y el resto de los filisteos perecerá, ha dicho Jehová el Señor." },
{name:'3019',l:'30',c:'1',v:'9',texto:"Así ha dicho Jehová: Por tres pecados de Tiro, y por el cuarto, no revocaré su castigo; porque entregaron a todo un pueblo cautivo a Edom, y no se acordaron del pacto de hermanos." },
{name:'30110',l:'30',c:'1',v:'10',texto:"Prenderé fuego en el muro de Tiro, y consumirá sus palacios." },
{name:'30111',l:'30',c:'1',v:'11',texto:"Así ha dicho Jehová: Por tres pecados de Edom, y por el cuarto, no revocaré su castigo; porque persiguió a espada a su hermano, y violó todo afecto natural; y en su furor le ha robado siempre, y perpetuamente ha guardado el rencor." },
{name:'30112',l:'30',c:'1',v:'12',texto:"Prenderé fuego en Temán, y consumirá los palacios de Bosra." },
{name:'30113',l:'30',c:'1',v:'13',texto:"Así ha dicho Jehová: Por tres pecados de los hijos de Amón, y por el cuarto, no revocaré su castigo; porque para ensanchar sus tierras abrieron a las mujeres de Galaad que estaban encintas." },
{name:'30114',l:'30',c:'1',v:'14',texto:"Encenderé fuego en el muro de Rabá, y consumirá sus palacios con estruendo en el día de la batalla, con tempestad en día tempestuoso; " },
{name:'30115',l:'30',c:'1',v:'15',texto:"y su rey irá en cautiverio, él y todos sus príncipes, dice Jehová." },
],
numVersiculos: 15,
},

c2: {
versiculos:[
{name:'3021',l:'30',c:'2',v:'1',texto:"Así ha dicho Jehová: Por tres pecados de Moab, y por el cuarto, no revocaré su castigo; porque quemó los huesos del rey de Edom hasta calcinarlos." },
{name:'3022',l:'30',c:'2',v:'2',texto:"Prenderé fuego en Moab, y consumirá los palacios de Queriot; y morirá Moab con tumulto, con estrépito y sonido de trompeta." },
{name:'3023',l:'30',c:'2',v:'3',texto:"Y quitaré el juez de en medio de él, y mataré con él a todos sus príncipes, dice Jehová." },
{name:'3024',l:'30',c:'2',v:'4',texto:"Así ha dicho Jehová: Por tres pecados de Judá, y por el cuarto, no revocaré su castigo; porque menospreciaron la ley de Jehová, y no guardaron sus ordenanzas, y les hicieron errar sus mentiras, en pos de las cuales anduvieron sus padres." },
{name:'3025',l:'30',c:'2',v:'5',texto:"Prenderé, por tanto, fuego en Judá, el cual consumirá los palacios de Jerusalén." },
{name:'3026',l:'30',c:'2',v:'6',texto:"Así ha dicho Jehová: Por tres pecados de Israel, y por el cuarto, no revocaré su castigo; porque vendieron por dinero al justo, y al pobre por un par de zapatos." },
{name:'3027',l:'30',c:'2',v:'7',texto:"Pisotean en el polvo de la tierra las cabezas de los desvalidos, y tuercen el camino de los humildes; y el hijo y su padre se llegan a la misma joven, profanando mi santo nombre." },
{name:'3028',l:'30',c:'2',v:'8',texto:"Sobre las ropas empeñadas se acuestan junto a cualquier altar; y el vino de los multados beben en la casa de sus dioses." },
{name:'3029',l:'30',c:'2',v:'9',texto:"Yo destruí delante de ellos al amorreo, cuya altura era como la altura de los cedros, y fuerte como una encina; y destruí su fruto arriba y sus raíces abajo." },
{name:'30210',l:'30',c:'2',v:'10',texto:"Y a vosotros os hice subir de la tierra de Egipto, y os conduje por el desierto cuarenta años, para que entraseis en posesión de la tierra del amorreo." },
{name:'30211',l:'30',c:'2',v:'11',texto:"Y levanté de vuestros hijos para profetas, y de vuestros jóvenes para que fuesen nazareos. ¿No es esto así, dice Jehová, hijos de Israel? " },
{name:'30212',l:'30',c:'2',v:'12',texto:"Mas vosotros disteis de beber vino a los nazareos, y a los profetas mandasteis diciendo: No profeticéis." },
{name:'30213',l:'30',c:'2',v:'13',texto:"Pues he aquí, yo os apretaré en vuestro lugar, como se aprieta el carro lleno de gavillas; " },
{name:'30214',l:'30',c:'2',v:'14',texto:"y el ligero no podrá huir, y al fuerte no le ayudará su fuerza, ni el valiente librará su vida." },
{name:'30215',l:'30',c:'2',v:'15',texto:"El que maneja el arco no resistirá, ni escapará el ligero de pies, ni el que cabalga en caballo salvará su vida." },
{name:'30216',l:'30',c:'2',v:'16',texto:"El esforzado de entre los valientes huirá desnudo aquel día, dice Jehová." },
],
numVersiculos: 16,
},

c3: {
versiculos:[
{name:'3031',l:'30',c:'3',v:'1',texto:"Oíd esta palabra que ha hablado Jehová contra vosotros, hijos de Israel, contra toda la familia que hice subir de la tierra de Egipto. Dice así: " },
{name:'3032',l:'30',c:'3',v:'2',texto:"A vosotros solamente he conocido de todas las familias de la tierra; por tanto, os castigaré por todas vuestras maldades." },
{name:'3033',l:'30',c:'3',v:'3',texto:"¿Andarán dos juntos, si no estuvieren de acuerdo? " },
{name:'3034',l:'30',c:'3',v:'4',texto:"¿Rugirá el león en la selva sin haber presa? ¿Dará el leoncillo su rugido desde su guarida, si no apresare? " },
{name:'3035',l:'30',c:'3',v:'5',texto:"¿Caerá el ave en lazo sobre la tierra, sin haber cazador? ¿Se levantará el lazo de la tierra, si no ha atrapado algo? " },
{name:'3036',l:'30',c:'3',v:'6',texto:"¿Se tocará la trompeta en la ciudad, y no se alborotará el pueblo? ¿Habrá algún mal en la ciudad, el cual Jehová no haya hecho? " },
{name:'3037',l:'30',c:'3',v:'7',texto:"Porque no hará nada Jehová el Señor, sin que revele su secreto a sus siervos los profetas." },
{name:'3038',l:'30',c:'3',v:'8',texto:"Si el león ruge, ¿quién no temerá? Si habla Jehová el Señor, ¿quién no profetizará? " },
{name:'3039',l:'30',c:'3',v:'9',texto:"Proclamad en los palacios de Asdod, y en los palacios de la tierra de Egipto, y decid: Reuníos sobre los montes de Samaria, y ved las muchas opresiones en medio de ella, y las violencias cometidas en su medio." },
{name:'30310',l:'30',c:'3',v:'10',texto:"No saben hacer lo recto, dice Jehová, atesorando rapiña y despojo en sus palacios." },
{name:'30311',l:'30',c:'3',v:'11',texto:"Por tanto, Jehová el Señor ha dicho así: Un enemigo vendrá por todos lados de la tierra, y derribará tu fortaleza, y tus palacios serán saqueados." },
{name:'30312',l:'30',c:'3',v:'12',texto:"Así ha dicho Jehová: De la manera que el pastor libra de la boca del león dos piernas, o la punta de una oreja, así escaparán los hijos de Israel que moran en Samaria en el rincón de una cama, y al lado de un lecho." },
{name:'30313',l:'30',c:'3',v:'13',texto:"Oíd y testificad contra la casa de Jacob, ha dicho Jehová Dios de los ejércitos: " },
{name:'30314',l:'30',c:'3',v:'14',texto:"Que el día que castigue las rebeliones de Israel, castigaré también los altares de Bet-el; y serán cortados los cuernos del altar, y caerán a tierra." },
{name:'30315',l:'30',c:'3',v:'15',texto:"Y heriré la casa de invierno con la casa de verano, y las casas de marfil perecerán; y muchas casas serán arruinadas, dice Jehová." },
],
numVersiculos: 15,
},

c4: {
versiculos:[
{name:'3041',l:'30',c:'4',v:'1',texto:"Oíd esta palabra, vacas de Basán, que estáis en el monte de Samaria, que oprimís a los pobres y quebrantáis a los menesterosos, que decís a vuestros señores: Traed, y beberemos." },
{name:'3042',l:'30',c:'4',v:'2',texto:"Jehová el Señor juró por su santidad: He aquí, vienen sobre vosotras días en que os llevarán con ganchos, y a vuestros descendientes con anzuelos de pescador; " },
{name:'3043',l:'30',c:'4',v:'3',texto:"y saldréis por las brechas una tras otra, y seréis echadas del palacio, dice Jehová." },
{name:'3044',l:'30',c:'4',v:'4',texto:"Id a Bet-el, y prevaricad; aumentad en Gilgal la rebelión, y traed de mañana vuestros sacrificios, y vuestros diezmos cada tres días." },
{name:'3045',l:'30',c:'4',v:'5',texto:"Y ofreced sacrificio de alabanza con pan leudado, y proclamad, publicad ofrendas voluntarias, pues que así lo queréis, hijos de Israel, dice Jehová el Señor." },
{name:'3046',l:'30',c:'4',v:'6',texto:"Os hice estar a diente limpio en todas vuestras ciudades, y hubo falta de pan en todos vuestros pueblos; mas no os volvisteis a mí, dice Jehová." },
{name:'3047',l:'30',c:'4',v:'7',texto:"También os detuve la lluvia tres meses antes de la siega; e hice llover sobre una ciudad, y sobre otra ciudad no hice llover; sobre una parte llovió, y la parte sobre la cual no llovió, se secó." },
{name:'3048',l:'30',c:'4',v:'8',texto:"Y venían dos o tres ciudades a una ciudad para beber agua, y no se saciaban; con todo, no os volvisteis a mí, dice Jehová." },
{name:'3049',l:'30',c:'4',v:'9',texto:"Os herí con viento solano y con oruga; la langosta devoró vuestros muchos huertos y vuestras viñas, y vuestros higuerales y vuestros olivares; pero nunca os volvisteis a mí, dice Jehová." },
{name:'30410',l:'30',c:'4',v:'10',texto:"Envié contra vosotros mortandad tal como en Egipto; maté a espada a vuestros jóvenes, con cautiverio de vuestros caballos, e hice subir el hedor de vuestros campamentos hasta vuestras narices; mas no os volvisteis a mí, dice Jehová." },
{name:'30411',l:'30',c:'4',v:'11',texto:"Os trastorné como cuando Dios trastornó a Sodoma y a Gomorra, y fuisteis como tizón escapado del fuego; mas no os volvisteis a mí, dice Jehová." },
{name:'30412',l:'30',c:'4',v:'12',texto:"Por tanto, de esta manera te haré a ti, oh Israel; y porque te he de hacer esto, prepárate para venir al encuentro de tu Dios, oh Israel." },
{name:'30413',l:'30',c:'4',v:'13',texto:"Porque he aquí, el que forma los montes, y crea el viento, y anuncia al hombre su pensamiento; el que hace de las tinieblas mañana, y pasa sobre las alturas de la tierra; Jehová Dios de los ejércitos es su nombre." },
],
numVersiculos: 13,
},

c5: {
versiculos:[
{name:'3051',l:'30',c:'5',v:'1',texto:"Oíd esta palabra que yo levanto para lamentación sobre vosotros, casa de Israel." },
{name:'3052',l:'30',c:'5',v:'2',texto:"Cayó la virgen de Israel, y no podrá levantarse ya más; fue dejada sobre su tierra, no hay quien la levante." },
{name:'3053',l:'30',c:'5',v:'3',texto:"Porque así ha dicho Jehová el Señor: La ciudad que salga con mil, volverá con ciento, y la que salga con ciento volverá con diez, en la casa de Israel." },
{name:'3054',l:'30',c:'5',v:'4',texto:"Pero así dice Jehová a la casa de Israel: Buscadme, y viviréis; " },
{name:'3055',l:'30',c:'5',v:'5',texto:"y no busquéis a Bet-el, ni entréis en Gilgal, ni paséis a Beerseba; porque Gilgal será llevada en cautiverio, y Bet-el será deshecha." },
{name:'3056',l:'30',c:'5',v:'6',texto:"Buscad a Jehová, y vivid; no sea que acometa como fuego a la casa de José y la consuma, sin haber en Bet=el quien lo apague." },
{name:'3057',l:'30',c:'5',v:'7',texto:"Los que convertís en ajenjo el juicio, y la justicia la echáis por tierra," },
{name:'3058',l:'30',c:'5',v:'8',texto:"buscad al que hace las Pléyades y el Orión, y vuelve las tinieblas en mañana, y hace oscurecer el día como noche; el que llama a las aguas del mar, y las derrama sobre la faz de la tierra; Jehová es su nombre; " },
{name:'3059',l:'30',c:'5',v:'9',texto:"que da esfuerzo al despojador sobre el fuerte, y hace que el despojador venga sobre la fortaleza." },
{name:'30510',l:'30',c:'5',v:'10',texto:"Ellos aborrecieron al reprensor en la puerta de la ciudad, y al que hablaba lo recto abominaron." },
{name:'30511',l:'30',c:'5',v:'11',texto:"Por tanto, puesto que vejáis al pobre y recibís de él carga de trigo, edificasteis casas de piedra labrada, mas no las habitaréis; plantasteis hermosas viñas, mas no beberéis el vino de ellas." },
{name:'30512',l:'30',c:'5',v:'12',texto:"Porque yo sé de vuestras muchas rebeliones, y de vuestros grandes pecados; sé que afligís al justo, y recibís cohecho, y en los tribunales hacéis perder su causa a los pobres." },
{name:'30513',l:'30',c:'5',v:'13',texto:"Por tanto, el prudente en tal tiempo calla, porque el tiempo es malo." },
{name:'30514',l:'30',c:'5',v:'14',texto:"Buscad lo bueno, y no lo malo, para que viváis; porque así Jehová Dios de los ejércitos estará con vosotros, como decís." },
{name:'30515',l:'30',c:'5',v:'15',texto:"Aborreced el mal, y amad el bien, y estableced la justicia en juicio; quizá Jehová Dios de los ejércitos tendrá piedad del remanente de José." },
{name:'30516',l:'30',c:'5',v:'16',texto:"Por tanto, así ha dicho Jehová, Dios de los ejércitos: En todas las plazas habrá llanto, y en todas las calles dirán: ¡Ay! ¡Ay!, y al labrador llamarán a lloro, y a endecha a los que sepan endechar." },
{name:'30517',l:'30',c:'5',v:'17',texto:"Y en todas las viñas habrá llanto; porque pasaré en medio de ti, dice Jehová." },
{name:'30518',l:'30',c:'5',v:'18',texto:"¡Ay de los que desean el día de Jehová! ¿Para qué queréis este día de Jehová? Será de tinieblas, y no de luz; " },
{name:'30519',l:'30',c:'5',v:'19',texto:"como el que huye de delante del león, y se encuentra con el oso; o como si entrare en casa y apoyare su mano en la pared, y le muerde una culebra." },
{name:'30520',l:'30',c:'5',v:'20',texto:"¿No será el día de Jehová tinieblas, y no luz; oscuridad, que no tiene resplandor? " },
{name:'30521',l:'30',c:'5',v:'21',texto:"Aborrecí, abominé vuestras solemnidades, y no me complaceré en vuestras asambleas." },
{name:'30522',l:'30',c:'5',v:'22',texto:"Y si me ofreciereis vuestros holocaustos y vuestras ofrendas, no los recibiré, ni miraré a las ofrendas de paz de vuestros animales engordados." },
{name:'30523',l:'30',c:'5',v:'23',texto:"Quita de mí la multitud de tus cantares, pues no escucharé las salmodias de tus instrumentos." },
{name:'30524',l:'30',c:'5',v:'24',texto:"Pero corra el juicio como las aguas, y la justicia como impetuoso arroyo." },
{name:'30525',l:'30',c:'5',v:'25',texto:"¿Me ofrecisteis sacrificios y ofrendas en el desierto en cuarenta años, oh casa de Israel? " },
{name:'30526',l:'30',c:'5',v:'26',texto:"Antes bien, llevabais el tabernáculo de vuestro Moloc y Quiún, ídolos vuestros, la estrella de vuestros dioses que os hicisteis." },
{name:'30527',l:'30',c:'5',v:'27',texto:"Os haré, pues, transportar más allá de Damasco, ha dicho Jehová, cuyo nombre es Dios de los ejércitos." },
],
numVersiculos: 27,
},

c6: {
versiculos:[
{name:'3061',l:'30',c:'6',v:'1',texto:"¡Ay de los reposados en Sion, y de los confiados en el monte de Samaria, los notables y principales entre las naciones, a los cuales acude la casa de Israel! " },
{name:'3062',l:'30',c:'6',v:'2',texto:"Pasad a Calne, y mirad; y de allí id a la gran Hamat; descended luego a Gat de los filisteos; ved si son aquellos reinos mejores que estos reinos, si su extensión es mayor que la vuestra," },
{name:'3063',l:'30',c:'6',v:'3',texto:"oh vosotros que dilatáis el día malo, y acercáis la silla de iniquidad." },
{name:'3064',l:'30',c:'6',v:'4',texto:"Duermen en camas de marfil, y reposan sobre sus lechos; y comen los corderos del rebaño, y los novillos de en medio del engordadero; " },
{name:'3065',l:'30',c:'6',v:'5',texto:"gorjean al son de la flauta, e inventan instrumentos musicales, como David; " },
{name:'3066',l:'30',c:'6',v:'6',texto:"beben vino en tazones, y se ungen con los ungüentos más preciosos; y no se afligen por el quebrantamiento de José." },
{name:'3067',l:'30',c:'6',v:'7',texto:"Por tanto, ahora irán a la cabeza de los que van a cautividad, y se acercará el duelo de los que se entregan a los placeres." },
{name:'3068',l:'30',c:'6',v:'8',texto:"Jehová el Señor juró por sí mismo, Jehová Dios de los ejércitos ha dicho: Abomino la grandeza de Jacob, y aborrezco sus palacios; y entregaré al enemigo la ciudad y cuanto hay en ella." },
{name:'3069',l:'30',c:'6',v:'9',texto:"Y acontecerá que si diez hombres quedaren en una casa, morirán." },
{name:'30610',l:'30',c:'6',v:'10',texto:"Y un pariente tomará a cada uno, y lo quemará para sacar los huesos de casa; y dirá al que estará en los rincones de la casa: ¿Hay aún alguno contigo? Y dirá: No. Y dirá aquél: Calla, porque no podemos mencionar el nombre de Jehová." },
{name:'30611',l:'30',c:'6',v:'11',texto:"Porque he aquí, Jehová mandará, y herirá con hendiduras la casa mayor, y la casa menor con aberturas." },
{name:'30612',l:'30',c:'6',v:'12',texto:"¿Correrán los caballos por las peñas? ¿Ararán en ellas con bueyes? ¿Por qué habéis vosotros convertido el juicio en veneno, y el fruto de justicia en ajenjo? " },
{name:'30613',l:'30',c:'6',v:'13',texto:"Vosotros que os alegráis en nada, que decís: ¿No hemos adquirido poder con nuestra fuerza? " },
{name:'30614',l:'30',c:'6',v:'14',texto:"Pues he aquí, oh casa de Israel, dice Jehová Dios de los ejércitos, levantaré yo sobre vosotros a una nación que os oprimirá desde la entrada de Hamat hasta el arroyo del Arabá." },
],
numVersiculos: 14,
},

c7: {
versiculos:[
{name:'3071',l:'30',c:'7',v:'1',texto:"Así me ha mostrado Jehová el Señor: He aquí, él criaba langostas cuando comenzaba a crecer el heno tardío; y he aquí era el heno tardío después de las siegas del rey." },
{name:'3072',l:'30',c:'7',v:'2',texto:"Y aconteció que cuando acabó de comer la hierba de la tierra, yo dije: Señor Jehová, perdona ahora; ¿quién levantará a Jacob? porque es pequeño." },
{name:'3073',l:'30',c:'7',v:'3',texto:"Se arrepintió Jehová de esto: No será, dijo Jehová." },
{name:'3074',l:'30',c:'7',v:'4',texto:"Jehová el Señor me mostró así: He aquí, Jehová el Señor llamaba para juzgar con fuego; y consumió un gran abismo, y consumió una parte de la tierra." },
{name:'3075',l:'30',c:'7',v:'5',texto:"Y dije: Señor Jehová, cesa ahora; ¿quién levantará a Jacob? porque es pequeño." },
{name:'3076',l:'30',c:'7',v:'6',texto:"Se arrepintió Jehová de esto: No será esto tampoco, dijo Jehová el Señor." },
{name:'3077',l:'30',c:'7',v:'7',texto:"Me enseñó así: He aquí el Señor estaba sobre un muro hecho a plomo, y en su mano una plomada de albañil." },
{name:'3078',l:'30',c:'7',v:'8',texto:"Jehová entonces me dijo: ¿Qué ves, Amós? Y dije: Una plomada de albañil. Y el Señor dijo: He aquí, yo pongo plomada de albañil en medio de mi pueblo Israel; no lo toleraré más." },
{name:'3079',l:'30',c:'7',v:'9',texto:"Los lugares altos de Isaac serán destruidos, y los santuarios de Israel serán asolados, y me levantaré con espada sobre la casa de Jeroboam." },
{name:'30710',l:'30',c:'7',v:'10',texto:"Entonces el sacerdote Amasías de Bet-el envió a decir a Jeroboam rey de Israel: Amós se ha levantado contra ti en medio de la casa de Israel; la tierra no puede sufrir todas sus palabras." },
{name:'30711',l:'30',c:'7',v:'11',texto:"Porque así ha dicho Amós: Jeroboam morirá a espada, e Israel será llevado de su tierra en cautiverio." },
{name:'30712',l:'30',c:'7',v:'12',texto:"Y Amasías dijo a Amós: Vidente, vete, huye a tierra de Judá, y come allá tu pan, y profetiza allá; " },
{name:'30713',l:'30',c:'7',v:'13',texto:"y no profetices más en Bet-el, porque es santuario del rey, y capital del reino." },
{name:'30714',l:'30',c:'7',v:'14',texto:"Entonces respondió Amós, y dijo a Amasías: No soy profeta, ni soy hijo de profeta, sino que soy boyero, y recojo higos silvestres." },
{name:'30715',l:'30',c:'7',v:'15',texto:"Y Jehová me tomó de detrás del ganado, y me dijo: Ve y profetiza a mi pueblo Israel." },
{name:'30716',l:'30',c:'7',v:'16',texto:"Ahora, pues, oye palabra de Jehová. Tú dices: No profetices contra Israel, ni hables contra la casa de Isaac." },
{name:'30717',l:'30',c:'7',v:'17',texto:"Por tanto, así ha dicho Jehová: Tu mujer será ramera en medio de la ciudad, y tus hijos y tus hijas caerán a espada, y tu tierra será repartida por suertes; y tú morirás en tierra inmunda, e Israel será llevado cautivo lejos de su tierra." },
],
numVersiculos: 17,
},

c8: {
versiculos:[
{name:'3081',l:'30',c:'8',v:'1',texto:"Así me ha mostrado Jehová el Señor: He aquí un canastillo de fruta de verano." },
{name:'3082',l:'30',c:'8',v:'2',texto:"Y dijo: ¿Qué ves, Amós? Y respondí: Un canastillo de fruta de verano. Y me dijo Jehová: Ha venido el fin sobre mi pueblo Israel; no lo toleraré más." },
{name:'3083',l:'30',c:'8',v:'3',texto:"Y los cantores del templo gemirán en aquel día, dice Jehová el Señor; muchos serán los cuerpos muertos; en todo lugar los echarán fuera en silencio." },
{name:'3084',l:'30',c:'8',v:'4',texto:"Oíd esto, los que explotáis a los menesterosos, y arruináis a los pobres de la tierra," },
{name:'3085',l:'30',c:'8',v:'5',texto:"diciendo: ¿Cuándo pasará el mes, y venderemos el trigo; y la semana, y abriremos los graneros del pan, y achicaremos la medida, y subiremos el precio, y falsearemos con engaño la balanza," },
{name:'3086',l:'30',c:'8',v:'6',texto:"para comprar los pobres por dinero, y los necesitados por un par de zapatos, y venderemos los desechos del trigo? " },
{name:'3087',l:'30',c:'8',v:'7',texto:"Jehová juró por la gloria de Jacob: No me olvidaré jamás de todas sus obras." },
{name:'3088',l:'30',c:'8',v:'8',texto:"¿No se estremecerá la tierra sobre esto? ¿No llorará todo habitante de ella? Subirá toda, como un río, y crecerá y mermará como el río de Egipto." },
{name:'3089',l:'30',c:'8',v:'9',texto:"Acontecerá en aquel día, dice Jehová el Señor, que haré que se ponga el sol a mediodía, y cubriré de tinieblas la tierra en el día claro." },
{name:'30810',l:'30',c:'8',v:'10',texto:"Y cambiaré vuestras fiestas en lloro, y todos vuestros cantares en lamentaciones; y haré poner cilicio sobre todo lomo, y que se rape toda cabeza; y la volveré como en llanto de unigénito, y su postrimería como día amargo." },
{name:'30811',l:'30',c:'8',v:'11',texto:"He aquí vienen días, dice Jehová el Señor, en los cuales enviaré hambre a la tierra, no hambre de pan, ni sed de agua, sino de oír la palabra de Jehová." },
{name:'30812',l:'30',c:'8',v:'12',texto:"E irán errantes de mar a mar; desde el norte hasta el oriente discurrirán buscando palabra de Jehová, y no la hallarán." },
{name:'30813',l:'30',c:'8',v:'13',texto:"En aquel tiempo las doncellas hermosas y los jóvenes desmayarán de sed." },
{name:'30814',l:'30',c:'8',v:'14',texto:"Los que juran por el pecado de Samaria, y dicen: Por tu Dios, oh Dan, y: Por el camino de Beerseba, caerán, y nunca más se levantarán." },
],
numVersiculos: 14,
},

c9: {
versiculos:[
{name:'3091',l:'30',c:'9',v:'1',texto:"Vi al Señor que estaba sobre el altar, y dijo: Derriba el capitel, y estremézcanse las puertas, y hazlos pedazos sobre la cabeza de todos; y al postrero de ellos mataré a espada; no habrá de ellos quien huya, ni quien escape." },
{name:'3092',l:'30',c:'9',v:'2',texto:"Aunque cavasen hasta el Seol, de allá los tomará mi mano; y aunque subieren hasta el cielo, de allá los haré descender." },
{name:'3093',l:'30',c:'9',v:'3',texto:"Si se escondieren en la cumbre del Carmelo, allí los buscaré y los tomaré; y aunque se escondieren de delante de mis ojos en lo profundo del mar, allí mandaré a la serpiente y los morderá." },
{name:'3094',l:'30',c:'9',v:'4',texto:"Y si fueren en cautiverio delante de sus enemigos, allí mandaré la espada, y los matará; y pondré sobre ellos mis ojos para mal, y no para bien." },
{name:'3095',l:'30',c:'9',v:'5',texto:"El Señor, Jehová de los ejércitos, es el que toca la tierra, y se derretirá, y llorarán todos los que en ella moran; y crecerá toda como un río, y mermará luego como el río de Egipto." },
{name:'3096',l:'30',c:'9',v:'6',texto:"Él edificó en el cielo sus cámaras, y ha establecido su expansión sobre la tierra; él llama las aguas del mar, y sobre la faz de la tierra las derrama; Jehová es su nombre." },
{name:'3097',l:'30',c:'9',v:'7',texto:"Hijos de Israel, ¿no me sois vosotros como hijos de etíopes, dice Jehová? ¿No hice yo subir a Israel de la tierra de Egipto, y a los filisteos de Caftor, y de Kir a los arameos? " },
{name:'3098',l:'30',c:'9',v:'8',texto:"He aquí los ojos de Jehová el Señor están contra el reino pecador, y yo lo asolaré de la faz de la tierra; mas no destruiré del todo la casa de Jacob, dice Jehová." },
{name:'3099',l:'30',c:'9',v:'9',texto:"Porque he aquí yo mandaré y haré que la casa de Israel sea zarandeada entre todas las naciones, como se zarandea el grano en una criba, y no cae un granito en la tierra." },
{name:'30910',l:'30',c:'9',v:'10',texto:"A espada morirán todos los pecadores de mi pueblo, que dicen: No se acercará, ni nos alcanzará el mal." },
{name:'30911',l:'30',c:'9',v:'11',texto:"En aquel día yo levantaré el tabernáculo caído de David, y cerraré sus portillos y levantaré sus ruinas, y lo edificaré como en el tiempo pasado; " },
{name:'30912',l:'30',c:'9',v:'12',texto:"para que aquellos sobre los cuales es invocado mi nombre posean el resto de Edom, y a todas las naciones, dice Jehová que hace esto." },
{name:'30913',l:'30',c:'9',v:'13',texto:"He aquí vienen días, dice Jehová, en que el que ara alcanzará al segador, y el pisador de las uvas al que lleve la simiente; y los montes destilarán mosto, y todos los collados se derretirán." },
{name:'30914',l:'30',c:'9',v:'14',texto:"Y traeré del cautiverio a mi pueblo Israel, y edificarán ellos las ciudades asoladas, y las habitarán; plantarán viñas, y beberán el vino de ellas, y harán huertos, y comerán el fruto de ellos." },
{name:'30915',l:'30',c:'9',v:'15',texto:"Pues los plantaré sobre su tierra, y nunca más serán arrancados de su tierra que yo les di, ha dicho Jehová Dios tuyo." },
],
numVersiculos: 15,
},
	

};
