BibliaRVR60.miqueas = {
	libro: "Miqueas",
	numCapitulos: 7,

c1: {
versiculos:[
{name:'3311',l:'33',c:'1',v:'1',texto:"Palabra de Jehová que vino a Miqueas de Moreset en días de Jotam, Acaz y Ezequías, reyes de Judá; lo que vio sobre Samaria y Jerusalén." },
{name:'3312',l:'33',c:'1',v:'2',texto:"Oíd, pueblos todos; está atenta, tierra, y cuanto hay en ti; y Jehová el Señor, el Señor desde su santo templo, sea testigo contra vosotros." },
{name:'3313',l:'33',c:'1',v:'3',texto:"Porque he aquí, Jehová sale de su lugar, y descenderá y hollará las alturas de la tierra." },
{name:'3314',l:'33',c:'1',v:'4',texto:"Y se derretirán los montes debajo de él, y los valles se hendirán como la cera delante del fuego, como las aguas que corren por un precipicio." },
{name:'3315',l:'33',c:'1',v:'5',texto:"Todo esto por la rebelión de Jacob, y por los pecados de la casa de Israel. ¿Cuál es la rebelión de Jacob? ¿No es Samaria? ¿Y cuáles son los lugares altos de Judá? ¿No es Jerusalén? " },
{name:'3316',l:'33',c:'1',v:'6',texto:"Haré, pues, de Samaria montones de ruinas, y tierra para plantar viñas; y derramaré sus piedras por el valle, y descubriré sus cimientos." },
{name:'3317',l:'33',c:'1',v:'7',texto:"Y todas sus estatuas serán despedazadas, y todos sus dones serán quemados en fuego, y asolaré todos sus ídolos; porque de dones de rameras los juntó, y a dones de rameras volverán." },
{name:'3318',l:'33',c:'1',v:'8',texto:"Por esto lamentaré y aullaré, y andaré despojado y desnudo; haré aullido como de chacales, y lamento como de avestruces." },
{name:'3319',l:'33',c:'1',v:'9',texto:"Porque su llaga es dolorosa, y llegó hasta Judá; llegó hasta la puerta de mi pueblo, hasta Jerusalén." },
{name:'33110',l:'33',c:'1',v:'10',texto:"No lo digáis en Gat, ni lloréis mucho; revuélcate en el polvo de Bet-le-afra." },
{name:'33111',l:'33',c:'1',v:'11',texto:"Pásate, oh morador de Safir, desnudo y con vergüenza; el morador de Zaanán no sale; el llanto de Betesel os quitará su apoyo." },
{name:'33112',l:'33',c:'1',v:'12',texto:"Porque los moradores de Marot anhelaron ansiosamente el bien; pues de parte de Jehová el mal había descendido hasta la puerta de Jerusalén." },
{name:'33113',l:'33',c:'1',v:'13',texto:"Uncid al carro bestias veloces, oh moradores de Laquis, que fuisteis principio de pecado a la hija de Sion; porque en vosotros se hallaron las rebeliones de Israel." },
{name:'33114',l:'33',c:'1',v:'14',texto:"Por tanto, vosotros daréis dones a Moreset-gat; las casas de Aczib serán para engaño a los reyes de Israel." },
{name:'33115',l:'33',c:'1',v:'15',texto:"Aun os traeré nuevo poseedor, oh moradores de Maresa; la flor de Israel huirá hasta Adulam." },
{name:'33116',l:'33',c:'1',v:'16',texto:"Ráete y trasquílate por los hijos de tus delicias; hazte calvo como águila, porque en cautiverio se fueron de ti. ¡Ay de los que oprimen a los pobres! " },
],
numVersiculos: 16,
},

c2: {
versiculos:[
{name:'3321',l:'33',c:'2',v:'1',texto:"¡Ay de los que en sus camas piensan iniquidad y maquinan el mal, y cuando llega la mañana lo ejecutan, porque tienen en su mano el poder! " },
{name:'3322',l:'33',c:'2',v:'2',texto:"Codician las heredades, y las roban; y casas, y las toman; oprimen al hombre y a su casa, al hombre y a su heredad." },
{name:'3323',l:'33',c:'2',v:'3',texto:"Por tanto, así ha dicho Jehová: He aquí, yo pienso contra esta familia un mal del cual no sacaréis vuestros cuellos, ni andaréis erguidos; porque el tiempo será malo." },
{name:'3324',l:'33',c:'2',v:'4',texto:"En aquel tiempo levantarán sobre vosotros refrán, y se hará endecha de lamentación, diciendo: Del todo fuimos destruidos; él ha cambiado la porción de mi pueblo. ¡Cómo nos quitó nuestros campos! Los dio y los repartió a otros." },
{name:'3325',l:'33',c:'2',v:'5',texto:"Por tanto, no habrá quien a suerte reparta heredades en la congregación de Jehová." },
{name:'3326',l:'33',c:'2',v:'6',texto:"No profeticéis, dicen a los que profetizan; no les profeticen, porque no les alcanzará vergüenza." },
{name:'3327',l:'33',c:'2',v:'7',texto:"Tú que te dices casa de Jacob, ¿se ha acortado el Espíritu de Jehová? ¿Son estas sus obras? ¿No hacen mis palabras bien al que camina rectamente? " },
{name:'3328',l:'33',c:'2',v:'8',texto:"El que ayer era mi pueblo, se ha levantado como enemigo; de sobre el vestido quitasteis las capas atrevidamente a los que pasaban, como adversarios de guerra." },
{name:'3329',l:'33',c:'2',v:'9',texto:"A las mujeres de mi pueblo echasteis fuera de las casas que eran su delicia; a sus niños quitasteis mi perpetua alabanza." },
{name:'33210',l:'33',c:'2',v:'10',texto:"Levantaos y andad, porque no es este el lugar de reposo, pues está contaminado, corrompido grandemente." },
{name:'33211',l:'33',c:'2',v:'11',texto:"Si alguno andando con espíritu de falsedad mintiere diciendo: Yo te profetizaré de vino y de sidra; este tal será el profeta de este pueblo." },
{name:'33212',l:'33',c:'2',v:'12',texto:"De cierto te juntaré todo, oh Jacob; recogeré ciertamente el resto de Israel; lo reuniré como ovejas de Bosra, como rebaño en medio de su aprisco; harán estruendo por la multitud de hombres." },
{name:'33213',l:'33',c:'2',v:'13',texto:"Subirá el que abre caminos delante de ellos; abrirán camino y pasarán la puerta, y saldrán por ella; y su rey pasará delante de ellos, y a la cabeza de ellos Jehová." },
],
numVersiculos: 13,
},

c3: {
versiculos:[
{name:'3331',l:'33',c:'3',v:'1',texto:"Dije: Oíd ahora, príncipes de Jacob, y jefes de la casa de Israel: ¿No concierne a vosotros saber lo que es justo? " },
{name:'3332',l:'33',c:'3',v:'2',texto:"Vosotros que aborrecéis lo bueno y amáis lo malo, que les quitáis su piel y su carne de sobre los huesos; " },
{name:'3333',l:'33',c:'3',v:'3',texto:"que coméis asimismo la carne de mi pueblo, y les desolláis su piel de sobre ellos, y les quebrantáis los huesos y los rompéis como para el caldero, y como carnes en olla." },
{name:'3334',l:'33',c:'3',v:'4',texto:"Entonces clamaréis a Jehová, y no os responderá; antes esconderá de vosotros su rostro en aquel tiempo, por cuanto hicisteis malvadas obras." },
{name:'3335',l:'33',c:'3',v:'5',texto:"Así ha dicho Jehová acerca de los profetas que hacen errar a mi pueblo, y claman: Paz, cuando tienen algo que comer, y al que no les da de comer, proclaman guerra contra él: " },
{name:'3336',l:'33',c:'3',v:'6',texto:"Por tanto, de la profecía se os hará noche, y oscuridad del adivinar; y sobre los profetas se pondrá el sol, y el día se entenebrecerá sobre ellos." },
{name:'3337',l:'33',c:'3',v:'7',texto:"Y serán avergonzados los profetas, y se confundirán los adivinos; y ellos todos cerrarán sus labios, porque no hay respuesta de Dios." },
{name:'3338',l:'33',c:'3',v:'8',texto:"Mas yo estoy lleno de poder del Espíritu de Jehová, y de juicio y de fuerza, para denunciar a Jacob su rebelión, y a Israel su pecado." },
{name:'3339',l:'33',c:'3',v:'9',texto:"Oíd ahora esto, jefes de la casa de Jacob, y capitanes de la casa de Israel, que abomináis el juicio, y pervertís todo el derecho; " },
{name:'33310',l:'33',c:'3',v:'10',texto:"que edificáis a Sion con sangre, y a Jerusalén con injusticia." },
{name:'33311',l:'33',c:'3',v:'11',texto:"Sus jefes juzgan por cohecho, y sus sacerdotes enseñan por precio, y sus profetas adivinan por dinero; y se apoyan en Jehová, diciendo: ¿No está Jehová entre nosotros? No vendrá mal sobre nosotros." },
{name:'33312',l:'33',c:'3',v:'12',texto:"Por tanto, a causa de vosotros Sion será arada como campo, y Jerusalén vendrá a ser montones de ruinas, y el monte de la casa como cumbres de bosque." },
],
numVersiculos: 12,
},

c4: {
versiculos:[
{name:'3341',l:'33',c:'4',v:'1',texto:"Acontecerá en los postreros tiempos que el monte de la casa de Jehová será establecido por cabecera de montes, y más alto que los collados, y correrán a él los pueblos." },
{name:'3342',l:'33',c:'4',v:'2',texto:"Vendrán muchas naciones, y dirán: Venid, y subamos al monte de Jehová, y a la casa del Dios de Jacob; y nos enseñará en sus caminos, y andaremos por sus veredas; porque de Sion saldrá la ley, y de Jerusalén la palabra de Jehová." },
{name:'3343',l:'33',c:'4',v:'3',texto:"Y él juzgará entre muchos pueblos, y corregirá a naciones poderosas hasta muy lejos; y martillarán sus espadas para azadones, y sus lanzas para hoces; no alzará espada nación contra nación, ni se ensayarán más para la guerra." },
{name:'3344',l:'33',c:'4',v:'4',texto:"Y se sentará cada uno debajo de su vid y debajo de su higuera, y no habrá quien los amedrente; porque la boca de Jehová de los ejércitos lo ha hablado." },
{name:'3345',l:'33',c:'4',v:'5',texto:"Aunque todos los pueblos anden cada uno en el nombre de su dios, nosotros con todo andaremos en el nombre de Jehová nuestro Dios eternamente y para siempre." },
{name:'3346',l:'33',c:'4',v:'6',texto:"En aquel día, dice Jehová, juntaré la que cojea, y recogeré la descarriada, y a la que afligí; " },
{name:'3347',l:'33',c:'4',v:'7',texto:"y pondré a la coja como remanente, y a la descarriada como nación robusta; y Jehová reinará sobre ellos en el monte de Sion desde ahora y para siempre." },
{name:'3348',l:'33',c:'4',v:'8',texto:"Y tú, oh torre del rebaño, fortaleza de la hija de Sion, hasta ti vendrá el señorío primero, el reino de la hija de Jerusalén." },
{name:'3349',l:'33',c:'4',v:'9',texto:"Ahora, ¿por qué gritas tanto? ¿No hay rey en ti? ¿Pereció tu consejero, que te ha tomado dolor como de mujer de parto? " },
{name:'33410',l:'33',c:'4',v:'10',texto:"Duélete y gime, hija de Sion, como mujer que está de parto; porque ahora saldrás de la ciudad y morarás en el campo, y llegarás hasta Babilonia; allí serás librada, allí te redimirá Jehová de la mano de tus enemigos." },
{name:'33411',l:'33',c:'4',v:'11',texto:"Pero ahora se han juntado muchas naciones contra ti, y dicen: Sea profanada, y vean nuestros ojos su deseo en Sion." },
{name:'33412',l:'33',c:'4',v:'12',texto:"Mas ellos no conocieron los pensamientos de Jehová, ni entendieron su consejo; por lo cual los juntó como gavillas en la era." },
{name:'33413',l:'33',c:'4',v:'13',texto:"Levántate y trilla, hija de Sion, porque haré tu cuerno como de hierro, y tus uñas de bronce, y desmenuzarás a muchos pueblos; y consagrarás a Jehová su botín, y sus riquezas al Señor de toda la tierra." },
],
numVersiculos: 13,
},

c5: {
versiculos:[
{name:'3351',l:'33',c:'5',v:'1',texto:"Rodéate ahora de muros, hija de guerreros; nos han sitiado; con vara herirán en la mejilla al juez de Israel." },
{name:'3352',l:'33',c:'5',v:'2',texto:"Pero tú, Belén Efrata, pequeña para estar entre las familias de Judá, de ti me saldrá el que será Señor en Israel; y sus salidas son desde el principio, desde los días de la eternidad." },
{name:'3353',l:'33',c:'5',v:'3',texto:"Pero los dejará hasta el tiempo que dé a luz la que ha de dar a luz; y el resto de sus hermanos se volverá con los hijos de Israel." },
{name:'3354',l:'33',c:'5',v:'4',texto:"Y él estará, y apacentará con poder de Jehová, con grandeza del nombre de Jehová su Dios; y morarán seguros, porque ahora será engrandecido hasta los fines de la tierra." },
{name:'3355',l:'33',c:'5',v:'5',texto:"Y éste será nuestra paz. Cuando el asirio viniere a nuestra tierra, y cuando hollare nuestros palacios, entonces levantaremos contra él siete pastores, y ocho hombres principales; " },
{name:'3356',l:'33',c:'5',v:'6',texto:"y devastarán la tierra de Asiria a espada, y con sus espadas la tierra de Nimrod; y nos librará del asirio, cuando viniere contra nuestra tierra y hollare nuestros confines." },
{name:'3357',l:'33',c:'5',v:'7',texto:"El remanente de Jacob será en medio de muchos pueblos como el rocío de Jehová, como las lluvias sobre la hierba, las cuales no esperan a varón, ni aguardan a hijos de hombres." },
{name:'3358',l:'33',c:'5',v:'8',texto:"Asimismo el remanente de Jacob será entre las naciones, en medio de muchos pueblos, como el león entre las bestias de la selva, como el cachorro del león entre las manadas de las ovejas, el cual si pasare, y hollare, y arrebatare, no hay quien escape." },
{name:'3359',l:'33',c:'5',v:'9',texto:"Tu mano se alzará sobre tus enemigos, y todos tus adversarios serán destruidos." },
{name:'33510',l:'33',c:'5',v:'10',texto:"Acontecerá en aquel día, dice Jehová, que haré matar tus caballos de en medio de ti, y haré destruir tus carros." },
{name:'33511',l:'33',c:'5',v:'11',texto:"Haré también destruir las ciudades de tu tierra, y arruinaré todas tus fortalezas." },
{name:'33512',l:'33',c:'5',v:'12',texto:"Asimismo destruiré de tu mano las hechicerías, y no se hallarán en ti agoreros." },
{name:'33513',l:'33',c:'5',v:'13',texto:"Y haré destruir tus esculturas y tus imágenes de en medio de ti, y nunca más te inclinarás a la obra de tus manos." },
{name:'33514',l:'33',c:'5',v:'14',texto:"Arrancaré tus imágenes de Asera de en medio de ti, y destruiré tus ciudades; " },
{name:'33515',l:'33',c:'5',v:'15',texto:"y con ira y con furor haré venganza en las naciones que no obedecieron." },
],
numVersiculos: 15,
},

c6: {
versiculos:[
{name:'3361',l:'33',c:'6',v:'1',texto:"Oíd ahora lo que dice Jehová: Levántate, contiende contra los montes, y oigan los collados tu voz." },
{name:'3362',l:'33',c:'6',v:'2',texto:"Oíd, montes, y fuertes cimientos de la tierra, el pleito de Jehová; porque Jehová tiene pleito con su pueblo, y altercará con Israel." },
{name:'3363',l:'33',c:'6',v:'3',texto:"Pueblo mío, ¿qué te he hecho, o en qué te he molestado? Responde contra mí." },
{name:'3364',l:'33',c:'6',v:'4',texto:"Porque yo te hice subir de la tierra de Egipto, y de la casa de servidumbre te redimí; y envié delante de ti a Moisés, a Aarón y a María." },
{name:'3365',l:'33',c:'6',v:'5',texto:"Pueblo mío, acuérdate ahora qué aconsejó Balac rey de Moab, y qué le respondió Balaam hijo de Beor, desde Sitim hasta Gilgal, para que conozcas las justicias de Jehová." },
{name:'3366',l:'33',c:'6',v:'6',texto:"¿Con qué me presentaré ante Jehová, y adoraré al Dios Altísimo? ¿Me presentaré ante él con holocaustos, con becerros de un año? " },
{name:'3367',l:'33',c:'6',v:'7',texto:"¿Se agradará Jehová de millares de carneros, o de diez mil arroyos de aceite? ¿Daré mi primogénito por mi rebelión, el fruto de mis entrañas por el pecado de mi alma? " },
{name:'3368',l:'33',c:'6',v:'8',texto:"Oh hombre, él te ha declarado lo que es bueno, y qué pide Jehová de ti: solamente hacer justicia, y amar misericordia, y humillarte ante tu Dios." },
{name:'3369',l:'33',c:'6',v:'9',texto:"La voz de Jehová clama a la ciudad; es sabio temer a tu nombre. Prestad atención al castigo, y a quien lo establece." },
{name:'33610',l:'33',c:'6',v:'10',texto:"¿Hay aún en casa del impío tesoros de impiedad, y medida escasa que es detestable? " },
{name:'33611',l:'33',c:'6',v:'11',texto:"¿Daré por inocente al que tiene balanza falsa y bolsa de pesas engañosas? " },
{name:'33612',l:'33',c:'6',v:'12',texto:"Sus ricos se colmaron de rapiña, y sus moradores hablaron mentira, y su lengua es engañosa en su boca." },
{name:'33613',l:'33',c:'6',v:'13',texto:"Por eso yo también te hice enflaquecer hiriéndote, asolándote por tus pecados." },
{name:'33614',l:'33',c:'6',v:'14',texto:"Comerás, y no te saciarás, y tu abatimiento estará en medio de ti; recogerás, mas no salvarás, y lo que salvares, lo entregaré yo a la espada." },
{name:'33615',l:'33',c:'6',v:'15',texto:"Sembrarás, mas no segarás; pisarás aceitunas, mas no te ungirás con el aceite; y mosto, mas no beberás el vino." },
{name:'33616',l:'33',c:'6',v:'16',texto:"Porque los mandamientos de Omri se han guardado, y toda obra de la casa de Acab; y en los consejos de ellos anduvisteis, para que yo te pusiese en asolamiento, y tus moradores para burla. Llevaréis, por tanto, el oprobio de mi pueblo." },
],
numVersiculos: 16,
},

c7: {
versiculos:[
{name:'3371',l:'33',c:'7',v:'1',texto:"¡Ay de mí! porque estoy como cuando han recogido los frutos del verano, como cuando han rebuscado después de la vendimia, y no queda racimo para comer; mi alma deseó los primeros frutos." },
{name:'3372',l:'33',c:'7',v:'2',texto:"Faltó el misericordioso de la tierra, y ninguno hay recto entre los hombres; todos acechan por sangre; cada cual arma red a su hermano." },
{name:'3373',l:'33',c:'7',v:'3',texto:"Para completar la maldad con sus manos, el príncipe demanda, y el juez juzga por recompensa; y el grande habla el antojo de su alma, y lo confirman." },
{name:'3374',l:'33',c:'7',v:'4',texto:"El mejor de ellos es como el espino; el más recto, como zarzal; el día de tu castigo viene, el que anunciaron tus atalayas; ahora será su confusión." },
{name:'3375',l:'33',c:'7',v:'5',texto:"No creáis en amigo, ni confiéis en príncipe; de la que duerme a tu lado cuídate, no abras tu boca." },
{name:'3376',l:'33',c:'7',v:'6',texto:"Porque el hijo deshonra al padre, la hija se levanta contra la madre, la nuera contra su suegra, y los enemigos del hombre son los de su casa." },
{name:'3377',l:'33',c:'7',v:'7',texto:"Mas yo a Jehová miraré, esperaré al Dios de mi salvación; el Dios mío me oirá." },
{name:'3378',l:'33',c:'7',v:'8',texto:"Tú, enemiga mía, no te alegres de mí, porque aunque caí, me levantaré; aunque more en tinieblas, Jehová será mi luz." },
{name:'3379',l:'33',c:'7',v:'9',texto:"La ira de Jehová soportaré, porque pequé contra él, hasta que juzgue mi causa y haga mi justicia; él me sacará a luz; veré su justicia." },
{name:'33710',l:'33',c:'7',v:'10',texto:"Y mi enemiga lo verá, y la cubrirá vergüenza; la que me decía: ¿Dónde está Jehová tu Dios? Mis ojos la verán; ahora será hollada como lodo de las calles." },
{name:'33711',l:'33',c:'7',v:'11',texto:"Viene el día en que se edificarán tus muros; aquel día se extenderán los límites." },
{name:'33712',l:'33',c:'7',v:'12',texto:"En ese día vendrán hasta ti desde Asiria y las ciudades fortificadas, y desde las ciudades fortificadas hasta el Río, y de mar a mar, y de monte a monte." },
{name:'33713',l:'33',c:'7',v:'13',texto:"Y será asolada la tierra a causa de sus moradores, por el fruto de sus obras." },
{name:'33714',l:'33',c:'7',v:'14',texto:"Apacienta tu pueblo con tu cayado, el rebaño de tu heredad, que mora solo en la montaña, en campo fértil; busque pasto en Basán y Galaad, como en el tiempo pasado." },
{name:'33715',l:'33',c:'7',v:'15',texto:"Yo les mostraré maravillas como el día que saliste de Egipto." },
{name:'33716',l:'33',c:'7',v:'16',texto:"Las naciones verán, y se avergonzarán de todo su poderío; pondrán la mano sobre su boca, ensordecerán sus oídos." },
{name:'33717',l:'33',c:'7',v:'17',texto:"Lamerán el polvo como la culebra; como las serpientes de la tierra, temblarán en sus encierros; se volverán amedrentados ante Jehová nuestro Dios, y temerán a causa de ti." },
{name:'33718',l:'33',c:'7',v:'18',texto:"¿Qué Dios como tú, que perdona la maldad, y olvida el pecado del remanente de su heredad? No retuvo para siempre su enojo, porque se deleita en misericordia." },
{name:'33719',l:'33',c:'7',v:'19',texto:"Él volverá a tener misericordia de nosotros; sepultará nuestras iniquidades, y echará en lo profundo del mar todos nuestros pecados." },
{name:'33720',l:'33',c:'7',v:'20',texto:"Cumplirás la verdad a Jacob, y a Abraham la misericordia, que juraste a nuestros padres desde tiempos antiguos." },
],
numVersiculos: 20,
},


};
