BibliaRVR60.habacuc = {
	libro: "Habacuc",
	numCapitulos: 3,

c1: {
versiculos:[
{name:'3511',l:'35',c:'1',v:'1',texto:"La profecía que vio el profeta Habacuc." },
{name:'3512',l:'35',c:'1',v:'2',texto:"¿Hasta cuándo, oh Jehová, clamaré, y no oirás; y daré voces a ti a causa de la violencia, y no salvarás? " },
{name:'3513',l:'35',c:'1',v:'3',texto:"¿Por qué me haces ver iniquidad, y haces que vea molestia? Destrucción y violencia están delante de mí, y pleito y contienda se levantan." },
{name:'3514',l:'35',c:'1',v:'4',texto:"Por lo cual la ley es debilitada, y el juicio no sale según la verdad; por cuanto el impío asedia al justo, por eso sale torcida la justicia." },
{name:'3515',l:'35',c:'1',v:'5',texto:"Mirad entre las naciones, y ved, y asombraos; porque haré una obra en vuestros días, que aun cuando se os contare, no la creeréis." },
{name:'3516',l:'35',c:'1',v:'6',texto:"Porque he aquí, yo levanto a los caldeos, nación cruel y presurosa, que camina por la anchura de la tierra para poseer las moradas ajenas." },
{name:'3517',l:'35',c:'1',v:'7',texto:"Formidable es y terrible; de ella misma procede su justicia y su dignidad." },
{name:'3518',l:'35',c:'1',v:'8',texto:"Sus caballos serán más ligeros que leopardos, y más feroces que lobos nocturnos, y sus jinetes se multiplicarán; vendrán de lejos sus jinetes, y volarán como águilas que se apresuran a devorar." },
{name:'3519',l:'35',c:'1',v:'9',texto:"Toda ella vendrá a la presa; el terror va delante de ella, y recogerá cautivos como arena." },
{name:'35110',l:'35',c:'1',v:'10',texto:"Escarnecerá a los reyes, y de los príncipes hará burla; se reirá de toda fortaleza, y levantará terraplén y la tomará." },
{name:'35111',l:'35',c:'1',v:'11',texto:"Luego pasará como el huracán, y ofenderá atribuyendo su fuerza a su dios." },
{name:'35112',l:'35',c:'1',v:'12',texto:"¿No eres tú desde el principio, oh Jehová, Dios mío, Santo mío? No moriremos. Oh Jehová, para juicio lo pusiste; y tú, oh Roca, lo fundaste para castigar." },
{name:'35113',l:'35',c:'1',v:'13',texto:"Muy limpio eres de ojos para ver el mal, ni puedes ver el agravio; ¿por qué ves a los menospreciadores, y callas cuando destruye el impío al más justo que él," },
{name:'35114',l:'35',c:'1',v:'14',texto:"y haces que sean los hombres como los peces del mar, como reptiles que no tienen quien los gobierne? " },
{name:'35115',l:'35',c:'1',v:'15',texto:"Sacará a todos con anzuelo, los recogerá con su red, y los juntará en sus mallas; por lo cual se alegrará y se regocijará." },
{name:'35116',l:'35',c:'1',v:'16',texto:"Por esto hará sacrificios a su red, y ofrecerá sahumerios a sus mallas; porque con ellas engordó su porción, y engrasó su comida." },
{name:'35117',l:'35',c:'1',v:'17',texto:"¿Vaciará por eso su red, y no tendrá piedad de aniquilar naciones continuamente? " },
],
numVersiculos: 17,
},

c2: {
versiculos:[
{name:'3521',l:'35',c:'2',v:'1',texto:"Sobre mi guarda estaré, y sobre la fortaleza afirmaré el pie, y velaré para ver lo que se me dirá, y qué he de responder tocante a mi queja." },
{name:'3522',l:'35',c:'2',v:'2',texto:"Y Jehová me respondió, y dijo: Escribe la visión, y declárala en tablas, para que corra el que leyere en ella." },
{name:'3523',l:'35',c:'2',v:'3',texto:"Aunque la visión tardará aún por un tiempo, mas se apresura hacia el fin, y no mentirá; aunque tardare, espéralo, porque sin duda vendrá, no tardará." },
{name:'3524',l:'35',c:'2',v:'4',texto:"He aquí que aquel cuya alma no es recta, se enorgullece; mas el justo por su fe vivirá." },
{name:'3525',l:'35',c:'2',v:'5',texto:"Y también, el que es dado al vino es traicionero, hombre soberbio, que no permanecerá; ensanchó como el Seol su alma, y es como la muerte, que no se saciará; antes reunió para sí todas las gentes, y juntó para sí todos los pueblos." },
{name:'3526',l:'35',c:'2',v:'6',texto:"¿No han de levantar todos éstos refrán sobre él, y sarcasmos contra él? Dirán: ¡Ay del que multiplicó lo que no era suyo! ¿Hasta cuándo había de acumular sobre sí prenda tras prenda? " },
{name:'3527',l:'35',c:'2',v:'7',texto:"¿No se levantarán de repente tus deudores, y se despertarán los que te harán temblar, y serás despojo para ellos? " },
{name:'3528',l:'35',c:'2',v:'8',texto:"Por cuanto tú has despojado a muchas naciones, todos los otros pueblos te despojarán, a causa de la sangre de los hombres, y de los robos de la tierra, de las ciudades y de todos los que habitan en ellas." },
{name:'3529',l:'35',c:'2',v:'9',texto:"¡Ay del que codicia injusta ganancia para su casa, para poner en alto su nido, para escaparse del poder del mal! " },
{name:'35210',l:'35',c:'2',v:'10',texto:"Tomaste consejo vergonzoso para tu casa, asolaste muchos pueblos, y has pecado contra tu vida." },
{name:'35211',l:'35',c:'2',v:'11',texto:"Porque la piedra clamará desde el muro, y la tabla del enmaderado le responderá." },
{name:'35212',l:'35',c:'2',v:'12',texto:"¡Ay del que edifica la ciudad con sangre, y del que funda una ciudad con iniquidad! " },
{name:'35213',l:'35',c:'2',v:'13',texto:"¿No es esto de Jehová de los ejércitos? Los pueblos, pues, trabajarán para el fuego, y las naciones se fatigarán en vano." },
{name:'35214',l:'35',c:'2',v:'14',texto:"Porque la tierra será llena del conocimiento de la gloria de Jehová, como las aguas cubren el mar." },
{name:'35215',l:'35',c:'2',v:'15',texto:"¡Ay del que da de beber a su prójimo! ¡Ay de ti, que le acercas tu hiel, y le embriagas para mirar su desnudez! " },
{name:'35216',l:'35',c:'2',v:'16',texto:"Te has llenado de deshonra más que de honra; bebe tú también, y serás descubierto; el cáliz de la mano derecha de Jehová vendrá hasta ti, y vómito de afrenta sobre tu gloria." },
{name:'35217',l:'35',c:'2',v:'17',texto:"Porque la rapiña del Líbano caerá sobre ti, y la destrucción de las fieras te quebrantará, a causa de la sangre de los hombres, y del robo de la tierra, de las ciudades y de todos los que en ellas habitaban." },
{name:'35218',l:'35',c:'2',v:'18',texto:"¿De qué sirve la escultura que esculpió el que la hizo? ¿la estatua de fundición que enseña mentira, para que haciendo imágenes mudas confíe el hacedor en su obra? " },
{name:'35219',l:'35',c:'2',v:'19',texto:"¡Ay del que dice al palo: Despiértate; y a la piedra muda: Levántate! ¿Podrá él enseñar? He aquí está cubierto de oro y plata, y no hay espíritu dentro de él." },
{name:'35220',l:'35',c:'2',v:'20',texto:"Mas Jehová está en su santo templo; calle delante de él toda la tierra." },
],
numVersiculos: 20,
},

c3: {
versiculos:[
{name:'3531',l:'35',c:'3',v:'1',texto:"Oración del profeta Habacuc, sobre Sigionot." },
{name:'3532',l:'35',c:'3',v:'2',texto:"Oh Jehová, he oído tu palabra, y temí. Oh Jehová, aviva tu obra en medio de los tiempos, En medio de los tiempos hazla conocer; En la ira acuérdate de la misericordia." },
{name:'3533',l:'35',c:'3',v:'3',texto:"Dios vendrá de Temán, Y el Santo desde el monte de Parán. Selah Su gloria cubrió los cielos, Y la tierra se llenó de su alabanza." },
{name:'3534',l:'35',c:'3',v:'4',texto:"Y el resplandor fue como la luz; Rayos brillantes salían de su mano, Y allí estaba escondido su poder." },
{name:'3535',l:'35',c:'3',v:'5',texto:"Delante de su rostro iba mortandad, Y a sus pies salían carbones encendidos." },
{name:'3536',l:'35',c:'3',v:'6',texto:"Se levantó, y midió la tierra; Miró, e hizo temblar las gentes; Los montes antiguos fueron desmenuzados, Los collados antiguos se humillaron. Sus caminos son eternos." },
{name:'3537',l:'35',c:'3',v:'7',texto:"He visto las tiendas de Cusán en aflicción; Las tiendas de la tierra de Madián temblaron." },
{name:'3538',l:'35',c:'3',v:'8',texto:"¿Te airaste, oh Jehová, contra los ríos? ¿Contra los ríos te airaste? ¿Fue tu ira contra el mar Cuando montaste en tus caballos, Y en tus carros de victoria? " },
{name:'3539',l:'35',c:'3',v:'9',texto:"Se descubrió enteramente tu arco; Los juramentos a las tribus fueron palabra segura. Selah Hendiste la tierra con ríos." },
{name:'35310',l:'35',c:'3',v:'10',texto:"Te vieron y tuvieron temor los montes; Pasó la inundación de las aguas; El abismo dio su voz, A lo alto alzó sus manos." },
{name:'35311',l:'35',c:'3',v:'11',texto:"El sol y la luna se pararon en su lugar; A la luz de tus saetas anduvieron, Y al resplandor de tu fulgente lanza." },
{name:'35312',l:'35',c:'3',v:'12',texto:"Con ira hollaste la tierra, Con furor trillaste las naciones." },
{name:'35313',l:'35',c:'3',v:'13',texto:"Saliste para socorrer a tu pueblo, Para socorrer a tu ungido. Traspasaste la cabeza de la casa del impío, Descubriendo el cimiento hasta la roca. Selah " },
{name:'35314',l:'35',c:'3',v:'14',texto:"Horadaste con sus propios dardos las cabezas de sus guerreros, Que como tempestad acometieron para dispersarme, Cuyo regocijo era como para devorar al pobre encubiertamente." },
{name:'35315',l:'35',c:'3',v:'15',texto:"Caminaste en el mar con tus caballos, Sobre la mole de las grandes aguas." },
{name:'35316',l:'35',c:'3',v:'16',texto:"Oí, y se conmovieron mis entrañas; A la voz temblaron mis labios; Pudrición entró en mis huesos, y dentro de mí me estremecí; Si bien estaré quieto en el día de la angustia, Cuando suba al pueblo el que lo invadirá con sus tropas." },
{name:'35317',l:'35',c:'3',v:'17',texto:"Aunque la higuera no florezca, Ni en las vides haya frutos, Aunque falte el producto del olivo, Y los labrados no den mantenimiento, Y las ovejas sean quitadas de la majada, Y no haya vacas en los corrales; " },
{name:'35318',l:'35',c:'3',v:'18',texto:"Con todo, yo me alegraré en Jehová, Y me gozaré en el Dios de mi salvación." },
{name:'35319',l:'35',c:'3',v:'19',texto:"Jehová el Señor es mi fortaleza, El cual hace mis pies como de ciervas, Y en mis alturas me hace andar. Al jefe de los cantores, sobre mis instrumentos de cuerdas." },
],
numVersiculos: 19,
},


};
