BibliaRVR60.hageo = {
	libro: "Hageo",
	numCapitulos: 2,

c1: {
versiculos:[
{name:'3711',l:'37',c:'1',v:'1',texto:"En el año segundo del rey Darío, en el mes sexto, en el primer día del mes, vino palabra de Jehová por medio del profeta Hageo a Zorobabel hijo de Salatiel, gobernador de Judá, y a Josué hijo de Josadac, sumo sacerdote, diciendo: " },
{name:'3712',l:'37',c:'1',v:'2',texto:"Así ha hablado Jehová de los ejércitos, diciendo: Este pueblo dice: No ha llegado aún el tiempo, el tiempo de que la casa de Jehová sea reedificada." },
{name:'3713',l:'37',c:'1',v:'3',texto:"Entonces vino palabra de Jehová por medio del profeta Hageo, diciendo: " },
{name:'3714',l:'37',c:'1',v:'4',texto:"¿Es para vosotros tiempo, para vosotros, de habitar en vuestras casas artesonadas, y esta casa está desierta? " },
{name:'3715',l:'37',c:'1',v:'5',texto:"Pues así ha dicho Jehová de los ejércitos: Meditad bien sobre vuestros caminos." },
{name:'3716',l:'37',c:'1',v:'6',texto:"Sembráis mucho, y recogéis poco; coméis, y no os saciáis; bebéis, y no quedáis satisfechos; os vestís, y no os calentáis; y el que trabaja a jornal recibe su jornal en saco roto." },
{name:'3717',l:'37',c:'1',v:'7',texto:"Así ha dicho Jehová de los ejércitos: Meditad sobre vuestros caminos." },
{name:'3718',l:'37',c:'1',v:'8',texto:"Subid al monte, y traed madera, y reedificad la casa; y pondré en ella mi voluntad, y seré glorificado, ha dicho Jehová." },
{name:'3719',l:'37',c:'1',v:'9',texto:"Buscáis mucho, y halláis poco; y encerráis en casa, y yo lo disiparé en un soplo. ¿Por qué? dice Jehová de los ejércitos. Por cuanto mi casa está desierta, y cada uno de vosotros corre a su propia casa." },
{name:'37110',l:'37',c:'1',v:'10',texto:"Por eso se detuvo de los cielos sobre vosotros la lluvia, y la tierra detuvo sus frutos." },
{name:'37111',l:'37',c:'1',v:'11',texto:"Y llamé la sequía sobre esta tierra, y sobre los montes, sobre el trigo, sobre el vino, sobre el aceite, sobre todo lo que la tierra produce, sobre los hombres y sobre las bestias, y sobre todo trabajo de manos." },
{name:'37112',l:'37',c:'1',v:'12',texto:"Y oyó Zorobabel hijo de Salatiel, y Josué hijo de Josadac, sumo sacerdote, y todo el resto del pueblo, la voz de Jehová su Dios, y las palabras del profeta Hageo, como le había enviado Jehová su Dios; y temió el pueblo delante de Jehová." },
{name:'37113',l:'37',c:'1',v:'13',texto:"Entonces Hageo, enviado de Jehová, habló por mandato de Jehová al pueblo, diciendo: Yo estoy con vosotros, dice Jehová." },
{name:'37114',l:'37',c:'1',v:'14',texto:"Y despertó Jehová el espíritu de Zorobabel hijo de Salatiel, gobernador de Judá, y el espíritu de Josué hijo de Josadac, sumo sacerdote, y el espíritu de todo el resto del pueblo; y vinieron y trabajaron en la casa de Jehová de los ejércitos, su Dios," },
{name:'37115',l:'37',c:'1',v:'15',texto:"en el día veinticuatro del mes sexto, en el segundo año del rey Darío." },
],
numVersiculos: 15,
},

c2: {
versiculos:[
{name:'3721',l:'37',c:'2',v:'1',texto:"En el mes séptimo, a los veintiún días del mes, vino palabra de Jehová por medio del profeta Hageo, diciendo: " },
{name:'3722',l:'37',c:'2',v:'2',texto:"Habla ahora a Zorobabel hijo de Salatiel, gobernador de Judá, y a Josué hijo de Josadac, sumo sacerdote, y al resto del pueblo, diciendo: " },
{name:'3723',l:'37',c:'2',v:'3',texto:"¿Quién ha quedado entre vosotros que haya visto esta casa en su gloria primera, y cómo la veis ahora? ¿No es ella como nada delante de vuestros ojos? " },
{name:'3724',l:'37',c:'2',v:'4',texto:"Pues ahora, Zorobabel, esfuérzate, dice Jehová; esfuérzate también, Josué hijo de Josadac, sumo sacerdote; y cobrad ánimo, pueblo todo de la tierra, dice Jehová, y trabajad; porque yo estoy con vosotros, dice Jehová de los ejércitos." },
{name:'3725',l:'37',c:'2',v:'5',texto:"Según el pacto que hice con vosotros cuando salisteis de Egipto, así mi Espíritu estará en medio de vosotros, no temáis." },
{name:'3726',l:'37',c:'2',v:'6',texto:"Porque así dice Jehová de los ejércitos: De aquí a poco yo haré temblar los cielos y la tierra, el mar y la tierra seca; " },
{name:'3727',l:'37',c:'2',v:'7',texto:"y haré temblar a todas las naciones, y vendrá el Deseado de todas las naciones; y llenaré de gloria esta casa, ha dicho Jehová de los ejércitos." },
{name:'3728',l:'37',c:'2',v:'8',texto:"Mía es la plata, y mío es el oro, dice Jehová de los ejércitos." },
{name:'3729',l:'37',c:'2',v:'9',texto:"La gloria postrera de esta casa será mayor que la primera, ha dicho Jehová de los ejércitos; y daré paz en este lugar, dice Jehová de los ejércitos." },
{name:'37210',l:'37',c:'2',v:'10',texto:"A los veinticuatro días del noveno mes, en el segundo año de Darío, vino palabra de Jehová por medio del profeta Hageo, diciendo: " },
{name:'37211',l:'37',c:'2',v:'11',texto:"Así ha dicho Jehová de los ejércitos: Pregunta ahora a los sacerdotes acerca de la ley, diciendo: " },
{name:'37212',l:'37',c:'2',v:'12',texto:"Si alguno llevare carne santificada en la falda de su ropa, y con el vuelo de ella tocare pan, o vianda, o vino, o aceite, o cualquier otra comida, ¿será santificada? Y respondieron los sacerdotes y dijeron: No." },
{name:'37213',l:'37',c:'2',v:'13',texto:"Y dijo Hageo: Si un inmundo a causa de cuerpo muerto tocare alguna cosa de estas, ¿será inmunda? Y respondieron los sacerdotes, y dijeron: Inmunda será." },
{name:'37214',l:'37',c:'2',v:'14',texto:"Y respondió Hageo y dijo: Así es este pueblo y esta gente delante de mí, dice Jehová; y asimismo toda obra de sus manos; y todo lo que aquí ofrecen es inmundo." },
{name:'37215',l:'37',c:'2',v:'15',texto:"Ahora, pues, meditad en vuestro corazón desde este día en adelante, antes que pongan piedra sobre piedra en el templo de Jehová." },
{name:'37216',l:'37',c:'2',v:'16',texto:"Antes que sucediesen estas cosas, venían al montón de veinte efas, y había diez; venían al lagar para sacar cincuenta cántaros, y había veinte." },
{name:'37217',l:'37',c:'2',v:'17',texto:"Os herí con viento solano, con tizoncillo y con granizo en toda obra de vuestras manos; mas no os convertisteis a mí, dice Jehová." },
{name:'37218',l:'37',c:'2',v:'18',texto:"Meditad, pues, en vuestro corazón, desde este día en adelante, desde el día veinticuatro del noveno mes, desde el día que se echó el cimiento del templo de Jehová; meditad, pues, en vuestro corazón." },
{name:'37219',l:'37',c:'2',v:'19',texto:"¿No está aún la simiente en el granero? Ni la vid, ni la higuera, ni el granado, ni el árbol de olivo ha florecido todavía; mas desde este día os bendeciré." },
{name:'37220',l:'37',c:'2',v:'20',texto:"Vino por segunda vez palabra de Jehová a Hageo, a los veinticuatro días del mismo mes, diciendo: " },
{name:'37221',l:'37',c:'2',v:'21',texto:"Habla a Zorobabel gobernador de Judá, diciendo: Yo haré temblar los cielos y la tierra; " },
{name:'37222',l:'37',c:'2',v:'22',texto:"y trastornaré el trono de los reinos, y destruiré la fuerza de los reinos de las naciones; trastornaré los carros y los que en ellos suben, y vendrán abajo los caballos y sus jinetes, cada cual por la espada de su hermano." },
{name:'37223',l:'37',c:'2',v:'23',texto:"En aquel día, dice Jehová de los ejércitos, te tomaré, oh Zorobabel hijo de Salatiel, siervo mío, dice Jehová, y te pondré como anillo de sellar; porque yo te escogí, dice Jehová de los ejércitos." },
],
numVersiculos: 23,
},
	

};
