BibliaRVR60.romanos = {
	libro: "Romanos",
	numCapitulos: 16,

c1: {
versiculos:[
{name:'4511',l:'45',c:'1',v:'1',texto:"Pablo, siervo de Jesucristo, llamado a ser apóstol, apartado para el evangelio de Dios," },
{name:'4512',l:'45',c:'1',v:'2',texto:"que él había prometido antes por sus profetas en las santas Escrituras," },
{name:'4513',l:'45',c:'1',v:'3',texto:"acerca de su Hijo, nuestro Señor Jesucristo, que era del linaje de David según la carne," },
{name:'4514',l:'45',c:'1',v:'4',texto:"que fue declarado Hijo de Dios con poder, según el Espíritu de santidad, por la resurrección de entre los muertos," },
{name:'4515',l:'45',c:'1',v:'5',texto:"y por quien recibimos la gracia y el apostolado, para la obediencia a la fe en todas las naciones por amor de su nombre; " },
{name:'4516',l:'45',c:'1',v:'6',texto:"entre las cuales estáis también vosotros, llamados a ser de Jesucristo; " },
{name:'4517',l:'45',c:'1',v:'7',texto:"a todos los que estáis en Roma, amados de Dios, llamados a ser santos: Gracia y paz a vosotros, de Dios nuestro Padre y del Señor Jesucristo." },
{name:'4518',l:'45',c:'1',v:'8',texto:"Primeramente doy gracias a mi Dios mediante Jesucristo con respecto a todos vosotros, de que vuestra fe se divulga por todo el mundo." },
{name:'4519',l:'45',c:'1',v:'9',texto:"Porque testigo me es Dios, a quien sirvo en mi espíritu en el evangelio de su Hijo, de que sin cesar hago mención de vosotros siempre en mis oraciones," },
{name:'45110',l:'45',c:'1',v:'10',texto:"rogando que de alguna manera tenga al fin, por la voluntad de Dios, un próspero viaje para ir a vosotros." },
{name:'45111',l:'45',c:'1',v:'11',texto:"Porque deseo veros, para comunicaros algún don espiritual, a fin de que seáis confirmados; " },
{name:'45112',l:'45',c:'1',v:'12',texto:"esto es, para ser mutuamente confortados por la fe que nos es común a vosotros y a mí." },
{name:'45113',l:'45',c:'1',v:'13',texto:"Pero no quiero, hermanos, que ignoréis que muchas veces me he propuesto ir a vosotros (pero hasta ahora he sido estorbado), para tener también entre vosotros algún fruto, como entre los demás gentiles." },
{name:'45114',l:'45',c:'1',v:'14',texto:"A griegos y a no griegos, a sabios y a no sabios soy deudor." },
{name:'45115',l:'45',c:'1',v:'15',texto:"Así que, en cuanto a mí, pronto estoy a anunciaros el evangelio también a vosotros que estáis en Roma." },
{name:'45116',l:'45',c:'1',v:'16',texto:"Porque no me avergüenzo del evangelio, porque es poder de Dios para salvación a todo aquel que cree; al judío primeramente, y también al griego." },
{name:'45117',l:'45',c:'1',v:'17',texto:"Porque en el evangelio la justicia de Dios se revela por fe y para fe, como está escrito: Mas el justo por la fe vivirá." },
{name:'45118',l:'45',c:'1',v:'18',texto:"Porque la ira de Dios se revela desde el cielo contra toda impiedad e injusticia de los hombres que detienen con injusticia la verdad; " },
{name:'45119',l:'45',c:'1',v:'19',texto:"porque lo que de Dios se conoce les es manifiesto, pues Dios se lo manifestó." },
{name:'45120',l:'45',c:'1',v:'20',texto:"Porque las cosas invisibles de él, su eterno poder y deidad, se hacen claramente visibles desde la creación del mundo, siendo entendidas por medio de las cosas hechas, de modo que no tienen excusa." },
{name:'45121',l:'45',c:'1',v:'21',texto:"Pues habiendo conocido a Dios, no le glorificaron como a Dios, ni le dieron gracias, sino que se envanecieron en sus razonamientos, y su necio corazón fue entenebrecido." },
{name:'45122',l:'45',c:'1',v:'22',texto:"Profesando ser sabios, se hicieron necios," },
{name:'45123',l:'45',c:'1',v:'23',texto:"y cambiaron la gloria del Dios incorruptible en semejanza de imagen de hombre corruptible, de aves, de cuadrúpedos y de reptiles." },
{name:'45124',l:'45',c:'1',v:'24',texto:"Por lo cual también Dios los entregó a la inmundicia, en las concupiscencias de sus corazones, de modo que deshonraron entre sí sus propios cuerpos," },
{name:'45125',l:'45',c:'1',v:'25',texto:"ya que cambiaron la verdad de Dios por la mentira, honrando y dando culto a las criaturas antes que al Creador, el cual es bendito por los siglos. Amén." },
{name:'45126',l:'45',c:'1',v:'26',texto:"Por esto Dios los entregó a pasiones vergonzosas; pues aun sus mujeres cambiaron el uso natural por el que es contra naturaleza," },
{name:'45127',l:'45',c:'1',v:'27',texto:"y de igual modo también los hombres, dejando el uso natural de la mujer, se encendieron en su lascivia unos con otros, cometiendo hechos vergonzosos hombres con hombres, y recibiendo en sí mismos la retribución debida a su extravío." },
{name:'45128',l:'45',c:'1',v:'28',texto:"Y como ellos no aprobaron tener en cuenta a Dios, Dios los entregó a una mente reprobada, para hacer cosas que no convienen; " },
{name:'45129',l:'45',c:'1',v:'29',texto:"estando atestados de toda injusticia, fornicación, perversidad, avaricia, maldad; llenos de envidia, homicidios, contiendas, engaños y malignidades; " },
{name:'45130',l:'45',c:'1',v:'30',texto:"murmuradores, detractores, aborrecedores de Dios, injuriosos, soberbios, altivos, inventores de males, desobedientes a los padres," },
{name:'45131',l:'45',c:'1',v:'31',texto:"necios, desleales, sin afecto natural, implacables, sin misericordia; " },
{name:'45132',l:'45',c:'1',v:'32',texto:"quienes habiendo entendido el juicio de Dios, que los que practican tales cosas son dignos de muerte, no sólo las hacen, sino que también se complacen con los que las practican." },
],
numVersiculos: 32,
},

c2: {
versiculos:[
{name:'4521',l:'45',c:'2',v:'1',texto:"Por lo cual eres inexcusable, oh hombre, quienquiera que seas tú que juzgas; pues en lo que juzgas a otro, te condenas a ti mismo; porque tú que juzgas haces lo mismo." },
{name:'4522',l:'45',c:'2',v:'2',texto:"Mas sabemos que el juicio de Dios contra los que practican tales cosas es según verdad." },
{name:'4523',l:'45',c:'2',v:'3',texto:"¿Y piensas esto, oh hombre, tú que juzgas a los que tal hacen, y haces lo mismo, que tú escaparás del juicio de Dios? " },
{name:'4524',l:'45',c:'2',v:'4',texto:"¿O menosprecias las riquezas de su benignidad, paciencia y longanimidad, ignorando que su benignidad te guía al arrepentimiento? " },
{name:'4525',l:'45',c:'2',v:'5',texto:"Pero por tu dureza y por tu corazón no arrepentido, atesoras para ti mismo ira para el día de la ira y de la revelación del justo juicio de Dios," },
{name:'4526',l:'45',c:'2',v:'6',texto:"el cual pagará a cada uno conforme a sus obras: " },
{name:'4527',l:'45',c:'2',v:'7',texto:"vida eterna a los que, perseverando en bien hacer, buscan gloria y honra e inmortalidad," },
{name:'4528',l:'45',c:'2',v:'8',texto:"pero ira y enojo a los que son contenciosos y no obedecen a la verdad, sino que obedecen a la injusticia; " },
{name:'4529',l:'45',c:'2',v:'9',texto:"tribulación y angustia sobre todo ser humano que hace lo malo, el judío primeramente y también el griego," },
{name:'45210',l:'45',c:'2',v:'10',texto:"pero gloria y honra y paz a todo el que hace lo bueno, al judío primeramente y también al griego; " },
{name:'45211',l:'45',c:'2',v:'11',texto:"porque no hay acepción de personas para con Dios." },
{name:'45212',l:'45',c:'2',v:'12',texto:"Porque todos los que sin ley han pecado, sin ley también perecerán; y todos los que bajo la ley han pecado, por la ley serán juzgados; " },
{name:'45213',l:'45',c:'2',v:'13',texto:"porque no son los oidores de la ley los justos ante Dios, sino los hacedores de la ley serán justificados." },
{name:'45214',l:'45',c:'2',v:'14',texto:"Porque cuando los gentiles que no tienen ley, hacen por naturaleza lo que es de la ley, éstos, aunque no tengan ley, son ley para sí mismos," },
{name:'45215',l:'45',c:'2',v:'15',texto:"mostrando la obra de la ley escrita en sus corazones, dando testimonio su conciencia, y acusándoles o defendiéndoles sus razonamientos," },
{name:'45216',l:'45',c:'2',v:'16',texto:"en el día en que Dios juzgará por Jesucristo los secretos de los hombres, conforme a mi evangelio." },
{name:'45217',l:'45',c:'2',v:'17',texto:"He aquí, tú tienes el sobrenombre de judío, y te apoyas en la ley, y te glorías en Dios," },
{name:'45218',l:'45',c:'2',v:'18',texto:"y conoces su voluntad, e instruido por la ley apruebas lo mejor," },
{name:'45219',l:'45',c:'2',v:'19',texto:"y confías en que eres guía de los ciegos, luz de los que están en tinieblas," },
{name:'45220',l:'45',c:'2',v:'20',texto:"instructor de los indoctos, maestro de niños, que tienes en la ley la forma de la ciencia y de la verdad." },
{name:'45221',l:'45',c:'2',v:'21',texto:"Tú, pues, que enseñas a otro, ¿no te enseñas a ti mismo? Tú que predicas que no se ha de hurtar, ¿hurtas? " },
{name:'45222',l:'45',c:'2',v:'22',texto:"Tú que dices que no se ha de adulterar, ¿adulteras? Tú que abominas de los ídolos, ¿cometes sacrilegio? " },
{name:'45223',l:'45',c:'2',v:'23',texto:"Tú que te jactas de la ley, ¿con infracción de la ley deshonras a Dios? " },
{name:'45224',l:'45',c:'2',v:'24',texto:"Porque como está escrito, el nombre de Dios es blasfemado entre los gentiles por causa de vosotros." },
{name:'45225',l:'45',c:'2',v:'25',texto:"Pues en verdad la circuncisión aprovecha, si guardas la ley; pero si eres transgresor de la ley, tu circuncisión viene a ser incircuncisión." },
{name:'45226',l:'45',c:'2',v:'26',texto:"Si, pues, el incircunciso guardare las ordenanzas de la ley, ¿no será tenida su incircuncisión como circuncisión? " },
{name:'45227',l:'45',c:'2',v:'27',texto:"Y el que físicamente es incircunciso, pero guarda perfectamente la ley, te condenará a ti, que con la letra de la ley y con la circuncisión eres transgresor de la ley." },
{name:'45228',l:'45',c:'2',v:'28',texto:"Pues no es judío el que lo es exteriormente, ni es la circuncisión la que se hace exteriormente en la carne; " },
{name:'45229',l:'45',c:'2',v:'29',texto:"sino que es judío el que lo es en lo interior, y la circuncisión es la del corazón, en espíritu, no en letra; la alabanza del cual no viene de los hombres, sino de Dios." },
],
numVersiculos: 29,
},

c3: {
versiculos:[
{name:'4531',l:'45',c:'3',v:'1',texto:"¿Qué ventaja tiene, pues, el judío? ¿o de qué aprovecha la circuncisión? " },
{name:'4532',l:'45',c:'3',v:'2',texto:"Mucho, en todas maneras. Primero, ciertamente, que les ha sido confiada la palabra de Dios." },
{name:'4533',l:'45',c:'3',v:'3',texto:"¿Pues qué, si algunos de ellos han sido incrédulos? ¿Su incredulidad habrá hecho nula la fidelidad de Dios? " },
{name:'4534',l:'45',c:'3',v:'4',texto:"De ninguna manera; antes bien sea Dios veraz, y todo hombre mentiroso; como está escrito: Para que seas justificado en tus palabras, Y venzas cuando fueres juzgado." },
{name:'4535',l:'45',c:'3',v:'5',texto:"Y si nuestra injusticia hace resaltar la justicia de Dios, ¿qué diremos? ¿Será injusto Dios que da castigo? (Hablo como hombre.) " },
{name:'4536',l:'45',c:'3',v:'6',texto:"En ninguna manera; de otro modo, ¿cómo juzgaría Dios al mundo? " },
{name:'4537',l:'45',c:'3',v:'7',texto:"Pero si por mi mentira la verdad de Dios abundó para su gloria, ¿por qué aún soy juzgado como pecador? " },
{name:'4538',l:'45',c:'3',v:'8',texto:"¿Y por qué no decir (como se nos calumnia, y como algunos, cuya condenación es justa, afirma que nosotros decimos): Hagamos males para que vengan bienes? " },
{name:'4539',l:'45',c:'3',v:'9',texto:"¿Qué, pues? Somos nosotros mejores que ellos? En ninguna manera; pues ya hemos acusado a judíos y a gentiles, que todos están bajo pecado." },
{name:'45310',l:'45',c:'3',v:'10',texto:"Como está escrito: No hay justo, ni aun uno; " },
{name:'45311',l:'45',c:'3',v:'11',texto:"No hay quien entienda. No hay quien busque a Dios." },
{name:'45312',l:'45',c:'3',v:'12',texto:"Todos se desviaron, a una se hicieron inútiles; No hay quien haga lo bueno, no hay ni siquiera uno." },
{name:'45313',l:'45',c:'3',v:'13',texto:"Sepulcro abierto es su garganta; Con su lengua engañan. Veneno de áspides hay debajo de sus labios; " },
{name:'45314',l:'45',c:'3',v:'14',texto:"Su boca está llena de maldición y de amargura." },
{name:'45315',l:'45',c:'3',v:'15',texto:"Sus pies se apresuran para derramar sangre; " },
{name:'45316',l:'45',c:'3',v:'16',texto:"Quebranto y desventura hay en sus caminos; " },
{name:'45317',l:'45',c:'3',v:'17',texto:"Y no conocieron camino de paz." },
{name:'45318',l:'45',c:'3',v:'18',texto:"No hay temor de Dios delante de sus ojos." },
{name:'45319',l:'45',c:'3',v:'19',texto:"Pero sabemos que todo lo que la ley dice, lo dice a los que están bajo la ley, para que toda boca se cierre y todo el mundo quede bajo el juicio de Dios; " },
{name:'45320',l:'45',c:'3',v:'20',texto:"ya que por las obras de la ley ningún ser humano será justificado delante de él; porque por medio de la ley es el conocimiento del pecado." },
{name:'45321',l:'45',c:'3',v:'21',texto:"Pero ahora, aparte de la ley, se ha manifestado la justicia de Dios, testificada por la ley y por los profetas; " },
{name:'45322',l:'45',c:'3',v:'22',texto:"la justicia de Dios por medio de la fe en Jesucristo, para todos los que creen en él. Porque no hay diferencia," },
{name:'45323',l:'45',c:'3',v:'23',texto:"por cuanto todos pecaron, y están destituidos de la gloria de Dios," },
{name:'45324',l:'45',c:'3',v:'24',texto:"siendo justificados gratuitamente por su gracia, mediante la redención que es en Cristo Jesús," },
{name:'45325',l:'45',c:'3',v:'25',texto:"a quien Dios puso como propiciación por medio de la fe en su sangre, para manifestar su justicia, a causa de haber pasado por alto, en su paciencia, los pecados pasados," },
{name:'45326',l:'45',c:'3',v:'26',texto:"con la mira de manifestar en este tiempo su justicia, a fin de que él sea el justo, y el que justifica al que es de la fe de Jesús." },
{name:'45327',l:'45',c:'3',v:'27',texto:"¿Dónde, pues, está la jactancia? Queda excluida. ¿Por cuál ley? ¿Por la de las obras? No, sino por la ley de la fe." },
{name:'45328',l:'45',c:'3',v:'28',texto:"Concluimos, pues, que el hombre es justificado por fe sin las obras de la ley." },
{name:'45329',l:'45',c:'3',v:'29',texto:"¿Es Dios solamente Dios de los judíos? ¿No es también Dios de los gentiles? Ciertamente, también de los gentiles." },
{name:'45330',l:'45',c:'3',v:'30',texto:"Porque Dios es uno, y él justificará por la fe a los de la circuncisión, y por medio de la fe a los de la incircuncisión." },
{name:'45331',l:'45',c:'3',v:'31',texto:"¿Luego por la fe invalidamos la ley? En ninguna manera, sino que confirmamos la ley." },
],
numVersiculos: 31,
},

c4: {
versiculos:[
{name:'4541',l:'45',c:'4',v:'1',texto:"¿Qué, pues, diremos que halló Abraham, nuestro padre según la carne? " },
{name:'4542',l:'45',c:'4',v:'2',texto:"Porque si Abraham fue justificado por las obras, tiene de qué gloriarse, pero no para con Dios." },
{name:'4543',l:'45',c:'4',v:'3',texto:"Porque ¿qué dice la Escritura? Creyó Abraham a Dios, y le fue contado por justicia." },
{name:'4544',l:'45',c:'4',v:'4',texto:"Pero al que obra, no se le cuenta el salario como gracia, sino como deuda; " },
{name:'4545',l:'45',c:'4',v:'5',texto:"mas al que no obra, sino cree en aquel que justifica al impío, su fe le es contada por justicia." },
{name:'4546',l:'45',c:'4',v:'6',texto:"Como también David habla de la bienaventuranza del hombre a quien Dios atribuye justicia sin obras," },
{name:'4547',l:'45',c:'4',v:'7',texto:"diciendo: Bienaventurados aquellos cuyas iniquidades son perdonadas, Y cuyos pecados son cubiertos." },
{name:'4548',l:'45',c:'4',v:'8',texto:"Bienaventurado el varón a quien el Señor no inculpa de pecado." },
{name:'4549',l:'45',c:'4',v:'9',texto:"¿Es, pues, esta bienaventuranza solamente para los de la circuncisión, o también para los de la incircuncisión? Porque decimos que a Abraham le fue contada la fe por justicia." },
{name:'45410',l:'45',c:'4',v:'10',texto:"¿Cómo, pues, le fue contada? ¿Estando en la circuncisión, o en la incircuncisión? No en la circuncisión, sino en la incircuncisión." },
{name:'45411',l:'45',c:'4',v:'11',texto:"Y recibió la circuncisión como señal, como sello de la justicia de la fe que tuvo estando aún incircunciso; para que fuese padre de todos los creyentes no circuncidados, a fin de que también a ellos la fe les sea contada por justicia; " },
{name:'45412',l:'45',c:'4',v:'12',texto:"y padre de la circuncisión, para los que no solamente son de la circuncisión, sino que también siguen las pisadas de la fe que tuvo nuestro padre Abraham antes de ser circuncidado." },
{name:'45413',l:'45',c:'4',v:'13',texto:"Porque no por la ley fue dada a Abraham o a su descendencia la promesa de que sería heredero del mundo, sino por la justicia de la fe." },
{name:'45414',l:'45',c:'4',v:'14',texto:"Porque si los que son de la ley son los herederos, vana resulta la fe, y anulada la promesa." },
{name:'45415',l:'45',c:'4',v:'15',texto:"Pues la ley produce ira; pero donde no hay ley, tampoco hay transgresión." },
{name:'45416',l:'45',c:'4',v:'16',texto:"Por tanto, es por fe, para que sea por gracia, a fin de que la promesa sea firme para toda su descendencia; no solamente para la que es de la ley, sino también para la que es de la fe de Abraham, el cual es padre de todos nosotros." },
{name:'45417',l:'45',c:'4',v:'17',texto:"(como está escrito: Te he puesto por padre de muchas gentes) delante de Dios, a quien creyó, el cual da vida a los muertos, y llama las cosas que no son, como si fuesen." },
{name:'45418',l:'45',c:'4',v:'18',texto:"Él creyó en esperanza contra esperanza, para llegar a ser padre de muchas gentes, conforme a lo que se le había dicho: Así será tu descendencia." },
{name:'45419',l:'45',c:'4',v:'19',texto:"Y no se debilitó en la fe al considerar su cuerpo, que estaba ya como muerto (siendo de casi cien años), o la esterilidad de la matriz de Sara." },
{name:'45420',l:'45',c:'4',v:'20',texto:"Tampoco dudó, por incredulidad, de la promesa de Dios, sino que se fortaleció en fe, dando gloria a Dios," },
{name:'45421',l:'45',c:'4',v:'21',texto:"plenamente convencido de que era también poderoso para hacer todo lo que había prometido; " },
{name:'45422',l:'45',c:'4',v:'22',texto:"por lo cual también su fe le fue contada por justicia." },
{name:'45423',l:'45',c:'4',v:'23',texto:"Y no solamente con respecto a él se escribió que le fue contada," },
{name:'45424',l:'45',c:'4',v:'24',texto:"sino también con respecto a nosotros a quienes ha de ser contada, esto es, a los que creemos en el que levantó de los muertos a Jesús, Señor nuestro," },
{name:'45425',l:'45',c:'4',v:'25',texto:"el cual fue entregado por nuestras transgresiones, y resucitado para nuestra justificación." },
],
numVersiculos: 25,
},

c5: {
versiculos:[
{name:'4551',l:'45',c:'5',v:'1',texto:"Justificados, pues, por la fe, tenemos paz para con Dios por medio de nuestro Señor Jesucristo; " },
{name:'4552',l:'45',c:'5',v:'2',texto:"por quien también tenemos entrada por la fe a esta gracia en la cual estamos firmes, y nos gloriamos en la esperanza de la gloria de Dios." },
{name:'4553',l:'45',c:'5',v:'3',texto:"Y no sólo esto, sino que también nos gloriamos en las tribulaciones, sabiendo que la tribulación produce paciencia; " },
{name:'4554',l:'45',c:'5',v:'4',texto:"y la paciencia, prueba; y la prueba, esperanza; " },
{name:'4555',l:'45',c:'5',v:'5',texto:"y la esperanza no avergüenza; porque el amor de Dios ha sido derramado en nuestros corazones por el Espíritu Santo que nos fue dado." },
{name:'4556',l:'45',c:'5',v:'6',texto:"Porque Cristo, cuando aún éramos débiles, a su tiempo murió por los impíos." },
{name:'4557',l:'45',c:'5',v:'7',texto:"Ciertamente, apenas morirá alguno por un justo; con todo, pudiera ser que alguno osara morir por el bueno." },
{name:'4558',l:'45',c:'5',v:'8',texto:"Mas Dios muestra su amor para con nosotros, en que siendo aún pecadores, Cristo murió por nosotros." },
{name:'4559',l:'45',c:'5',v:'9',texto:"Pues mucho más, estando ya justificados en su sangre, por él seremos salvos de la ira." },
{name:'45510',l:'45',c:'5',v:'10',texto:"Porque si siendo enemigos, fuimos reconciliados con Dios por la muerte de su Hijo, mucho más, estando reconciliados, seremos salvos por su vida." },
{name:'45511',l:'45',c:'5',v:'11',texto:"Y no sólo esto, sino que también nos gloriamos en Dios por el Señor nuestro Jesucristo, por quien hemos recibido ahora la reconciliación." },
{name:'45512',l:'45',c:'5',v:'12',texto:"Por tanto, como el pecado entró en el mundo por un hombre, y por el pecado la muerte, así la muerte pasó a todos los hombres, por cuanto todos pecaron." },
{name:'45513',l:'45',c:'5',v:'13',texto:"Pues antes de la ley, había pecado en el mundo; pero donde no hay ley, no se inculpa de pecado." },
{name:'45514',l:'45',c:'5',v:'14',texto:"No obstante, reinó la muerte desde Adán hasta Moisés, aun en los que no pecaron a la manera de la transgresión de Adán, el cual es figura del que había de venir." },
{name:'45515',l:'45',c:'5',v:'15',texto:"Pero el don no fue como la transgresión; porque si por la transgresión de aquel uno murieron los muchos, abundaron mucho más para los muchos la gracia y el don de Dios por la gracia de un hombre, Jesucristo." },
{name:'45516',l:'45',c:'5',v:'16',texto:"Y con el don no sucede como en el caso de aquel uno que pecó; porque ciertamente el juicio vino a causa de un solo pecado para condenación, pero el don vino a causa de muchas transgresiones para justificación." },
{name:'45517',l:'45',c:'5',v:'17',texto:"Pues si por la transgresión de uno solo reinó la muerte, mucho más reinarán en vida por uno solo, Jesucristo, los que reciben la abundancia de la gracia y del don de la justicia." },
{name:'45518',l:'45',c:'5',v:'18',texto:"Así que, como por la transgresión de uno vino la condenación a todos los hombres, de la misma manera por la justicia de uno vino a todos los hombres la justificación de vida." },
{name:'45519',l:'45',c:'5',v:'19',texto:"Porque así como por la desobediencia de un hombre los muchos fueron constituidos pecadores, así también por la obediencia de uno, los muchos serán constituidos justos." },
{name:'45520',l:'45',c:'5',v:'20',texto:"Pero la ley se introdujo para que el pecado abundase; mas cuando el pecado abundó, sobreabundó la gracia; " },
{name:'45521',l:'45',c:'5',v:'21',texto:"para que así como el pecado reinó para muerte, así también la gracia reine por la justicia para vida eterna mediante Jesucristo, Señor nuestro." },
],
numVersiculos: 21,
},

c6: {
versiculos:[
{name:'4561',l:'45',c:'6',v:'1',texto:"¿Qué, pues, diremos? ¿Perseveraremos en el pecado para que la gracia abunde? " },
{name:'4562',l:'45',c:'6',v:'2',texto:"En ninguna manera. Porque los que hemos muerto al pecado, ¿cómo viviremos aún en él? " },
{name:'4563',l:'45',c:'6',v:'3',texto:"¿O no sabéis que todos los que hemos sido bautizados en Cristo Jesús, hemos sido bautizados en su muerte? " },
{name:'4564',l:'45',c:'6',v:'4',texto:"Porque somos sepultados juntamente con él para muerte por el bautismo, a fin de que como Cristo resucitó de los muertos por la gloria del Padre, así también nosotros andemos en vida nueva." },
{name:'4565',l:'45',c:'6',v:'5',texto:"Porque si fuimos plantados juntamente con él en la semejanza de su muerte, así también lo seremos en la de su resurrección; " },
{name:'4566',l:'45',c:'6',v:'6',texto:"sabiendo esto, que nuestro viejo hombre fue crucificado juntamente con él, para que el cuerpo del pecado sea destruido, a fin de que no sirvamos más al pecado." },
{name:'4567',l:'45',c:'6',v:'7',texto:"Porque el que ha muerto, ha sido justificado del pecado." },
{name:'4568',l:'45',c:'6',v:'8',texto:"Y si morimos con Cristo, creemos que también viviremos con él; " },
{name:'4569',l:'45',c:'6',v:'9',texto:"sabiendo que Cristo, habiendo resucitado de los muertos, ya no muere; la muerte no se enseñorea más de él." },
{name:'45610',l:'45',c:'6',v:'10',texto:"Porque en cuanto murió, al pecado murió una vez por todas; mas en cuanto vive, para Dios vive." },
{name:'45611',l:'45',c:'6',v:'11',texto:"Así también vosotros consideraos muertos al pecado, pero vivos para Dios en Cristo Jesús, Señor nuestro." },
{name:'45612',l:'45',c:'6',v:'12',texto:"No reine, pues, el pecado en vuestro cuerpo mortal, de modo que lo obedezcáis en sus concupiscencias; " },
{name:'45613',l:'45',c:'6',v:'13',texto:"ni tampoco presentéis vuestros miembros al pecado como instrumentos de iniquidad, sino presentaos vosotros mismos a Dios como vivos de entre los muertos, y vuestros miembros a Dios como instrumentos de justicia." },
{name:'45614',l:'45',c:'6',v:'14',texto:"Porque el pecado no se enseñoreará de vosotros; pues no estáis bajo la ley, sino bajo la gracia." },
{name:'45615',l:'45',c:'6',v:'15',texto:"¿Qué, pues? ¿Pecaremos, porque no estamos bajo la ley, sino bajo la gracia? En ninguna manera." },
{name:'45616',l:'45',c:'6',v:'16',texto:"¿No sabéis que si os sometéis a alguien como esclavos para obedecerle, sois esclavos de aquel a quien obedecéis, sea del pecado para muerte, o sea de la obediencia para justicia? " },
{name:'45617',l:'45',c:'6',v:'17',texto:"Pero gracias a Dios, que aunque erais esclavos del pecado, habéis obedecido de corazón a aquella forma de doctrina a la cual fuisteis entregados; " },
{name:'45618',l:'45',c:'6',v:'18',texto:"y libertados del pecado, vinisteis a ser siervos de la justicia." },
{name:'45619',l:'45',c:'6',v:'19',texto:"Hablo como humano, por vuestra humana debilidad; que así como para iniquidad presentasteis vuestros miembros para servir a la inmundicia y a la iniquidad, así ahora para santificación presentad vuestros miembros para servir a la justicia." },
{name:'45620',l:'45',c:'6',v:'20',texto:"Porque cuando erais esclavos del pecado, erais libres acerca de la justicia." },
{name:'45621',l:'45',c:'6',v:'21',texto:"¿Pero qué fruto teníais de aquellas cosas de las cuales ahora os avergonzáis? Porque el fin de ellas es muerte." },
{name:'45622',l:'45',c:'6',v:'22',texto:"Mas ahora que habéis sido libertados del pecado y hechos siervos de Dios, tenéis por vuestro fruto la santificación, y como fin, la vida eterna." },
{name:'45623',l:'45',c:'6',v:'23',texto:"Porque la paga del pecado es muerte, mas la dádiva de Dios es vida eterna en Cristo Jesús Señor nuestro." },
],
numVersiculos: 23,
},

c7: {
versiculos:[
{name:'4571',l:'45',c:'7',v:'1',texto:"¿Acaso ignoráis, hermanos (pues hablo con los que conocen la ley), que la ley se enseñorea del hombre entre tanto que éste vive? " },
{name:'4572',l:'45',c:'7',v:'2',texto:"Porque la mujer casada está sujeta por la ley al marido mientras éste vive; pero si el marido muere, ella queda libre de la ley del marido." },
{name:'4573',l:'45',c:'7',v:'3',texto:"Así que, si en vida del marido se uniere a otro varón, será llamada adúltera; pero si su marido muriere, es libre de esa ley, de tal manera que si se uniere a otro marido, no será adúltera." },
{name:'4574',l:'45',c:'7',v:'4',texto:"Así también vosotros, hermanos míos, habéis muerto a la ley mediante el cuerpo de Cristo, para que seáis de otro, del que resucitó de los muertos, a fin de que llevemos fruto para Dios." },
{name:'4575',l:'45',c:'7',v:'5',texto:"Porque mientras estábamos en la carne, las pasiones pecaminosas que eran por la ley obraban en nuestros miembros llevando fruto para muerte." },
{name:'4576',l:'45',c:'7',v:'6',texto:"Pero ahora estamos libres de la ley, por haber muerto para aquella en que estábamos sujetos, de modo que sirvamos bajo el régimen nuevo del Espíritu y no bajo el régimen viejo de la letra." },
{name:'4577',l:'45',c:'7',v:'7',texto:"¿Qué diremos, pues? ¿La ley es pecado? En ninguna manera. Pero yo no conocí el pecado sino por la ley; porque tampoco conociera la codicia, si la ley no dijera: No codiciarás." },
{name:'4578',l:'45',c:'7',v:'8',texto:"Mas el pecado, tomando ocasión por el mandamiento, produjo en mí toda codicia; porque sin la ley el pecado está muerto." },
{name:'4579',l:'45',c:'7',v:'9',texto:"Y yo sin la ley vivía en un tiempo; pero venido el mandamiento, el pecado revivió y yo morí." },
{name:'45710',l:'45',c:'7',v:'10',texto:"Y hallé que el mismo mandamiento que era para vida, a mí me resultó para muerte; " },
{name:'45711',l:'45',c:'7',v:'11',texto:"porque el pecado, tomando ocasión por el mandamiento, me engañó, y por él me mató." },
{name:'45712',l:'45',c:'7',v:'12',texto:"De manera que la ley a la verdad es santa, y el mandamiento santo, justo y bueno." },
{name:'45713',l:'45',c:'7',v:'13',texto:"¿Luego lo que es bueno, vino a ser muerte para mí? En ninguna manera; sino que el pecado, para mostrarse pecado, produjo en mí la muerte por medio de lo que es bueno, a fin de que por el mandamiento el pecado llegase a ser sobremanera pecaminoso." },
{name:'45714',l:'45',c:'7',v:'14',texto:"Porque sabemos que la ley es espiritual; mas yo soy carnal, vendido al pecado." },
{name:'45715',l:'45',c:'7',v:'15',texto:"Porque lo que hago, no lo entiendo; pues no hago lo que quiero, sino lo que aborrezco, eso hago." },
{name:'45716',l:'45',c:'7',v:'16',texto:"Y si lo que no quiero, esto hago, apruebo que la ley es buena." },
{name:'45717',l:'45',c:'7',v:'17',texto:"De manera que ya no soy yo quien hace aquello, sino el pecado que mora en mí." },
{name:'45718',l:'45',c:'7',v:'18',texto:"Y yo sé que en mí, esto es, en mi carne, no mora el bien; porque el querer el bien está en mí, pero no el hacerlo." },
{name:'45719',l:'45',c:'7',v:'19',texto:"Porque no hago el bien que quiero, sino el mal que no quiero, eso hago." },
{name:'45720',l:'45',c:'7',v:'20',texto:"Y si hago lo que no quiero, ya no lo hago yo, sino el pecado que mora en mí." },
{name:'45721',l:'45',c:'7',v:'21',texto:"Así que, queriendo yo hacer el bien, hallo esta ley: que el mal está en mí." },
{name:'45722',l:'45',c:'7',v:'22',texto:"Porque según el hombre interior, me deleito en la ley de Dios; " },
{name:'45723',l:'45',c:'7',v:'23',texto:"pero veo otra ley en mis miembros, que se rebela contra la ley de mi mente, y que me lleva cautivo a la ley del pecado que está en mis miembros." },
{name:'45724',l:'45',c:'7',v:'24',texto:"¡Miserable de mí! ¿quién me librará de este cuerpo de muerte? " },
{name:'45725',l:'45',c:'7',v:'25',texto:"Gracias doy a Dios, por Jesucristo Señor nuestro. Así que, yo mismo con la mente sirvo a la ley de Dios, mas con la carne a la ley del pecado." },
],
numVersiculos: 25,
},

c8: {
versiculos:[
{name:'4581',l:'45',c:'8',v:'1',texto:"Ahora, pues, ninguna condenación hay para los que están en Cristo Jesús, los que no andan conforme a la carne, sino conforme al Espíritu." },
{name:'4582',l:'45',c:'8',v:'2',texto:"Porque la ley del Espíritu de vida en Cristo Jesús me ha librado de la ley del pecado y de la muerte." },
{name:'4583',l:'45',c:'8',v:'3',texto:"Porque lo que era imposible para la ley, por cuanto era débil por la carne, Dios, enviando a su Hijo en semejanza de carne de pecado y a causa del pecado, condenó al pecado en la carne; " },
{name:'4584',l:'45',c:'8',v:'4',texto:"para que la justicia de la ley se cumpliese en nosotros, que no andamos conforme a la carne, sino conforme al Espíritu." },
{name:'4585',l:'45',c:'8',v:'5',texto:"Porque los que son de la carne piensan en las cosas de la carne; pero los que son del Espíritu, en las cosas del Espíritu." },
{name:'4586',l:'45',c:'8',v:'6',texto:"Porque el ocuparse de la carne es muerte, pero el ocuparse del Espíritu es vida y paz." },
{name:'4587',l:'45',c:'8',v:'7',texto:"Por cuanto los designios de la carne son enemistad contra Dios; porque no se sujetan a la ley de Dios, ni tampoco pueden; " },
{name:'4588',l:'45',c:'8',v:'8',texto:"y los que viven según la carne no pueden agradar a Dios." },
{name:'4589',l:'45',c:'8',v:'9',texto:"Mas vosotros no vivís según la carne, sino según el Espíritu, si es que el Espíritu de Dios mora en vosotros. Y si alguno no tiene el Espíritu de Cristo, no es de él." },
{name:'45810',l:'45',c:'8',v:'10',texto:"Pero si Cristo está en vosotros, el cuerpo en verdad está muerto a causa del pecado, mas el espíritu vive a causa de la justicia." },
{name:'45811',l:'45',c:'8',v:'11',texto:"Y si el Espíritu de aquel que levantó de los muertos a Jesús mora en vosotros, el que levantó de los muertos a Cristo Jesús vivificará también vuestros cuerpos mortales por su Espíritu que mora en vosotros." },
{name:'45812',l:'45',c:'8',v:'12',texto:"Así que, hermanos, deudores somos, no a la carne, para que vivamos conforme a la carne; " },
{name:'45813',l:'45',c:'8',v:'13',texto:"porque si vivís conforme a la carne, moriréis; mas si por el Espíritu hacéis morir las obras de la carne, viviréis." },
{name:'45814',l:'45',c:'8',v:'14',texto:"Porque todos los que son guiados por el Espíritu de Dios, éstos son hijos de Dios." },
{name:'45815',l:'45',c:'8',v:'15',texto:"Pues no habéis recibido el espíritu de esclavitud para estar otra vez en temor, sino que habéis recibido el espíritu de adopción, por el cual clamamos: ¡Abba, Padre! " },
{name:'45816',l:'45',c:'8',v:'16',texto:"El Espíritu mismo da testimonio a nuestro espíritu, de que somos hijos de Dios." },
{name:'45817',l:'45',c:'8',v:'17',texto:"Y si hijos, también herederos; herederos de Dios y coherederos con Cristo, si es que padecemos juntamente con él, para que juntamente con él seamos glorificados." },
{name:'45818',l:'45',c:'8',v:'18',texto:"Pues tengo por cierto que las aflicciones del tiempo presente no son comparables con la gloria venidera que en nosotros ha de manifestarse." },
{name:'45819',l:'45',c:'8',v:'19',texto:"Porque el anhelo ardiente de la creación es el aguardar la manifestación de los hijos de Dios." },
{name:'45820',l:'45',c:'8',v:'20',texto:"Porque la creación fue sujetada a vanidad, no por su propia voluntad, sino por causa del que la sujetó en esperanza; " },
{name:'45821',l:'45',c:'8',v:'21',texto:"porque también la creación misma será libertada de la esclavitud de corrupción, a la libertad gloriosa de los hijos de Dios." },
{name:'45822',l:'45',c:'8',v:'22',texto:"Porque sabemos que toda la creación gime a una, y a una está con dolores de parto hasta ahora; " },
{name:'45823',l:'45',c:'8',v:'23',texto:"y no sólo ella, sino que también nosotros mismos, que tenemos las primicias del Espíritu, nosotros también gemimos dentro de nosotros mismos, esperando la adopción, la redención de nuestro cuerpo." },
{name:'45824',l:'45',c:'8',v:'24',texto:"Porque en esperanza fuimos salvos; pero la esperanza que se ve, no es esperanza; porque lo que alguno ve, ¿a qué esperarlo? " },
{name:'45825',l:'45',c:'8',v:'25',texto:"Pero si esperamos lo que no vemos, con paciencia lo aguardamos." },
{name:'45826',l:'45',c:'8',v:'26',texto:"Y de igual manera el Espíritu nos ayuda en nuestra debilidad; pues qué hemos de pedir como conviene, no lo sabemos, pero el Espíritu mismo intercede por nosotros con gemidos indecibles." },
{name:'45827',l:'45',c:'8',v:'27',texto:"Mas el que escudriña los corazones sabe cuál es la intención del Espíritu, porque conforme a la voluntad de Dios intercede por los santos." },
{name:'45828',l:'45',c:'8',v:'28',texto:"Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien, esto es, a los que conforme a su propósito son llamados." },
{name:'45829',l:'45',c:'8',v:'29',texto:"Porque a los que antes conoció, también los predestinó para que fuesen hechos conformes a la imagen de su Hijo, para que él sea el primogénito entre muchos hermanos." },
{name:'45830',l:'45',c:'8',v:'30',texto:"Y a los que predestinó, a éstos también llamó; y a los que llamó, a éstos también justificó; y a los que justificó, a éstos también glorificó." },
{name:'45831',l:'45',c:'8',v:'31',texto:"¿Qué, pues, diremos a esto? Si Dios es por nosotros, ¿quién contra nosotros? " },
{name:'45832',l:'45',c:'8',v:'32',texto:"El que no escatimó ni a su propio Hijo, sino que lo entregó por todos nosotros, ¿cómo no nos dará también con él todas las cosas? " },
{name:'45833',l:'45',c:'8',v:'33',texto:"¿Quién acusará a los escogidos de Dios? Dios es el que justifica." },
{name:'45834',l:'45',c:'8',v:'34',texto:"¿Quién es el que condenará? Cristo es el que murió; más aun, el que también resucitó, el que además está a la diestra de Dios, el que también intercede por nosotros." },
{name:'45835',l:'45',c:'8',v:'35',texto:"¿Quién nos separará del amor de Cristo? ¿Tribulación, o angustia, o persecución, o hambre, o desnudez, o peligro, o espada? " },
{name:'45836',l:'45',c:'8',v:'36',texto:"Como está escrito: Por causa de ti somos muertos todo el tiempo; Somos contados como ovejas de matadero." },
{name:'45837',l:'45',c:'8',v:'37',texto:"Antes, en todas estas cosas somos más que vencedores por medio de aquel que nos amo." },
{name:'45838',l:'45',c:'8',v:'38',texto:"Por lo cual estoy seguro de que ni la muerte, ni la vida, ni ángeles, ni principados, ni potestades, ni lo presente, ni lo por venir," },
{name:'45839',l:'45',c:'8',v:'39',texto:"ni lo alto, ni lo profundo, ni ninguna otra cosa creada nos podrá separar del amor de Dios, que es en Cristo Jesús Señor nuestro." },
],
numVersiculos: 39,
},

c9: {
versiculos:[
{name:'4591',l:'45',c:'9',v:'1',texto:"Verdad digo en Cristo, no miento, y mi conciencia me da testimonio en el Espíritu Santo," },
{name:'4592',l:'45',c:'9',v:'2',texto:"que tengo gran tristeza y continuo dolor en mi corazón." },
{name:'4593',l:'45',c:'9',v:'3',texto:"Porque deseara yo mismo ser anatema, separado de Cristo, por amor a mis hermanos, los que son mis parientes según la carne; " },
{name:'4594',l:'45',c:'9',v:'4',texto:"que son israelitas, de los cuales son la adopción, la gloria, el pacto, la promulgación de la ley, el culto y las promesas; " },
{name:'4595',l:'45',c:'9',v:'5',texto:"de quienes son los patriarcas, y de los cuales, según la carne, vino Cristo, el cual es Dios sobre todas las cosas, bendito por los siglos. Amén." },
{name:'4596',l:'45',c:'9',v:'6',texto:"No que la palabra de Dios haya fallado; porque no todos los que descienden de Israel son israelitas," },
{name:'4597',l:'45',c:'9',v:'7',texto:"ni por ser descendientes de Abraham, son todos hijos; sino: En Isaac te será llamada descendencia." },
{name:'4598',l:'45',c:'9',v:'8',texto:"Esto es: No los que son hijos según la carne son los hijos de Dios, sino que los que son hijos según la promesa son contados como descendientes." },
{name:'4599',l:'45',c:'9',v:'9',texto:"Porque la palabra de la promesa es esta: Por este tiempo vendré, y Sara tendrá un hijo." },
{name:'45910',l:'45',c:'9',v:'10',texto:"Y no sólo esto, sino también cuando Rebeca concibió de uno, de Isaac nuestro padre " },
{name:'45911',l:'45',c:'9',v:'11',texto:"(pues no habían aún nacido, ni habían hecho aún ni bien ni mal, para que el propósito de Dios conforme a la elección permaneciese, no por las obras sino por el que llama), " },
{name:'45912',l:'45',c:'9',v:'12',texto:"se le dijo: El mayor servirá al menor." },
{name:'45913',l:'45',c:'9',v:'13',texto:"Como está escrito: A Jacob amé, mas a Esaú aborrecí." },
{name:'45914',l:'45',c:'9',v:'14',texto:"¿Qué, pues, diremos? ¿Que hay injusticia en Dios? En ninguna manera." },
{name:'45915',l:'45',c:'9',v:'15',texto:"Pues a Moisés dice: Tendré misericordia del que yo tenga misericordia, y me compadeceré del que yo me compadezca." },
{name:'45916',l:'45',c:'9',v:'16',texto:"Así que no depende del que quiere, ni del que corre, sino de Dios que tiene misericordia." },
{name:'45917',l:'45',c:'9',v:'17',texto:"Porque la Escritura dice a Faraón: Para esto mismo te he levantado, para mostrar en ti mi poder, y para que mi nombre sea anunciado por toda la tierra." },
{name:'45918',l:'45',c:'9',v:'18',texto:"De manera que de quien quiere, tiene misericordia, y al que quiere endurecer, endurece." },
{name:'45919',l:'45',c:'9',v:'19',texto:"Pero me dirás: ¿Por qué, pues, inculpa? porque ¿quién ha resistido a su voluntad? " },
{name:'45920',l:'45',c:'9',v:'20',texto:"Mas antes, oh hombre, ¿quién eres tú, para que alterques con Dios? ¿Dirá el vaso de barro al que lo formó: ¿Por qué me has hecho así? " },
{name:'45921',l:'45',c:'9',v:'21',texto:"¿O no tiene potestad el alfarero sobre el barro, para hacer de la misma masa un vaso para honra y otro para deshonra? " },
{name:'45922',l:'45',c:'9',v:'22',texto:"¿Y qué, si Dios, queriendo mostrar su ira y hacer notorio su poder, soportó con mucha paciencia los vasos de ira preparados para destrucción," },
{name:'45923',l:'45',c:'9',v:'23',texto:"y para hacer notorias las riquezas de su gloria, las mostró para con los vasos de misericordia que él preparó de antemano para gloria," },
{name:'45924',l:'45',c:'9',v:'24',texto:"a los cuales también ha llamado, esto es, a nosotros, no sólo de los judíos, sino también de los gentiles? " },
{name:'45925',l:'45',c:'9',v:'25',texto:"Como también en Oseas dice: Llamaré pueblo mío al que no era mi pueblo, Y a la no amada, amada." },
{name:'45926',l:'45',c:'9',v:'26',texto:"Y en el lugar donde se les dijo: Vosotros no sois pueblo mío, Allí serán llamados hijos del Dios viviente." },
{name:'45927',l:'45',c:'9',v:'27',texto:"También Isaías clama tocante a Israel: Si fuere el número de los hijos de Israel como la arena del mar, tan sólo el remanente será salvo; " },
{name:'45928',l:'45',c:'9',v:'28',texto:"porque el Señor ejecutará su sentencia sobre la tierra en justicia y con prontitud." },
{name:'45929',l:'45',c:'9',v:'29',texto:"Y como antes dijo Isaías: Si el Señor de los ejércitos no nos hubiera dejado descendencia, Como Sodoma habríamos venido a ser, y a Gomorra seríamos semejantes." },
{name:'45930',l:'45',c:'9',v:'30',texto:"¿Qué, pues, diremos? Que los gentiles, que no iban tras la justicia, han alcanzado la justicia, es decir, la justicia que es por fe; " },
{name:'45931',l:'45',c:'9',v:'31',texto:"mas Israel, que iba tras una ley de justicia, no la alcanzó." },
{name:'45932',l:'45',c:'9',v:'32',texto:"¿Por qué? Porque iban tras ella no por fe, sino como por obras de la ley, pues tropezaron en la piedra de tropiezo," },
{name:'45933',l:'45',c:'9',v:'33',texto:"como está escrito: He aquí pongo en Sion piedra de tropiezo y roca de caída; Y el que creyere en él, no será avergonzado." },
],
numVersiculos: 33,
},

c10: {
versiculos:[
{name:'45101',l:'45',c:'10',v:'1',texto:"Hermanos, ciertamente el anhelo de mi corazón, y mi oración a Dios por Israel, es para salvación." },
{name:'45102',l:'45',c:'10',v:'2',texto:"Porque yo les doy testimonio de que tienen celo de Dios, pero no conforme a ciencia." },
{name:'45103',l:'45',c:'10',v:'3',texto:"Porque ignorando la justicia de Dios, y procurando establecer la suya propia, no se han sujetado a la justicia de Dios; " },
{name:'45104',l:'45',c:'10',v:'4',texto:"porque el fin de la ley es Cristo, para justicia a todo aquel que cree." },
{name:'45105',l:'45',c:'10',v:'5',texto:"Porque de la justicia que es por la ley Moisés escribe así: El hombre que haga estas cosas, vivirá por ellas." },
{name:'45106',l:'45',c:'10',v:'6',texto:"Pero la justicia que es por la fe dice así: No digas en tu corazón: ¿Quién subirá al cielo? (esto es, para traer abajo a Cristo); " },
{name:'45107',l:'45',c:'10',v:'7',texto:"o, ¿quién descenderá al abismo? (esto es, para hacer subir a Cristo de entre los muertos)." },
{name:'45108',l:'45',c:'10',v:'8',texto:"Mas ¿qué dice? Cerca de ti está la palabra, en tu boca y en tu corazón. Esta es la palabra de fe que predicamos: " },
{name:'45109',l:'45',c:'10',v:'9',texto:"que si confesares con tu boca que Jesús es el Señor, y creyeres en tu corazón que Dios le levantó de los muertos, serás salvo." },
{name:'451010',l:'45',c:'10',v:'10',texto:"Porque con el corazón se cree para justicia, pero con la boca se confiesa para salvación." },
{name:'451011',l:'45',c:'10',v:'11',texto:"Pues la Escritura dice: Todo aquel que en él creyere, no será avergonzado." },
{name:'451012',l:'45',c:'10',v:'12',texto:"Porque no hay diferencia entre judío y griego, pues el mismo que es Señor de todos, es rico para con todos los que le invocan; " },
{name:'451013',l:'45',c:'10',v:'13',texto:"porque todo aquel que invocare el nombre del Señor, será salvo." },
{name:'451014',l:'45',c:'10',v:'14',texto:"¿Cómo, pues, invocarán a aquel en el cual no han creído? ¿Y cómo creerán en aquel de quien no han oído? ¿Y cómo oirán sin haber quien les predique? " },
{name:'451015',l:'45',c:'10',v:'15',texto:"¿Y cómo predicarán si no fueren enviados? Como está escrito: ¡Cuán hermosos son los pies de los que anuncian la paz, de los que anuncian buenas nuevas! " },
{name:'451016',l:'45',c:'10',v:'16',texto:"Mas no todos obedecieron al evangelio; pues Isaías dice: Señor, ¿quién ha creído a nuestro anuncio? " },
{name:'451017',l:'45',c:'10',v:'17',texto:"Así que la fe es por el oír, y el oír, por la palabra de Dios." },
{name:'451018',l:'45',c:'10',v:'18',texto:"Pero digo: ¿No han oído? Antes bien, Por toda la tierra ha salido la voz de ellos, Y hasta los fines de la tierra sus palabras." },
{name:'451019',l:'45',c:'10',v:'19',texto:"También digo: ¿No ha conocido esto Israel? Primeramente Moisés dice: Yo os provocaré a celos con un pueblo que no es pueblo; Con pueblo insensato os provocaré a ira." },
{name:'451020',l:'45',c:'10',v:'20',texto:"E Isaías dice resueltamente: Fui hallado de los que no me buscaban; Me manifesté a los que no preguntaban por mí." },
{name:'451021',l:'45',c:'10',v:'21',texto:"Pero acerca de Israel dice: Todo el día extendí mis manos a un pueblo rebelde y contradictor." },
],
numVersiculos: 21,
},

c11: {
versiculos:[
{name:'45111',l:'45',c:'11',v:'1',texto:"Digo, pues: ¿Ha desechado Dios a su pueblo? En ninguna manera. Porque también yo soy israelita, de la descendencia de Abraham, de la tribu de Benjamín." },
{name:'45112',l:'45',c:'11',v:'2',texto:"No ha desechado Dios a su pueblo, al cual desde antes conoció. ¿O no sabéis qué dice de Elías la Escritura, cómo invoca a Dios contra Israel, diciendo: " },
{name:'45113',l:'45',c:'11',v:'3',texto:"Señor, a tus profetas han dado muerte, y tus altares han derribado; y sólo yo he quedado, y procuran matarme? " },
{name:'45114',l:'45',c:'11',v:'4',texto:"Pero ¿qué le dice la divina respuesta? Me he reservado siete mil hombres, que no han doblado la rodilla delante de Baal." },
{name:'45115',l:'45',c:'11',v:'5',texto:"Así también aun en este tiempo ha quedado un remanente escogido por gracia." },
{name:'45116',l:'45',c:'11',v:'6',texto:"Y si por gracia, ya no es por obras; de otra manera la gracia ya no es gracia. Y si por obras, ya no es gracia; de otra manera la obra ya no es obra." },
{name:'45117',l:'45',c:'11',v:'7',texto:"¿Qué pues? Lo que buscaba Israel, no lo ha alcanzado; pero los escogidos sí lo han alcanzado, y los demás fueron endurecidos; " },
{name:'45118',l:'45',c:'11',v:'8',texto:"como está escrito: Dios les dio espíritu de estupor, ojos con que no vean y oídos con que no oigan, hasta el día de hoy." },
{name:'45119',l:'45',c:'11',v:'9',texto:"Y David dice: Sea vuelto su convite en trampa y en red, En tropezadero y en retribución; " },
{name:'451110',l:'45',c:'11',v:'10',texto:"Sean oscurecidos sus ojos para que no vean, Y agóbiales la espalda para siempre." },
{name:'451111',l:'45',c:'11',v:'11',texto:"Digo, pues: ¿Han tropezado los de Israel para que cayesen? En ninguna manera; pero por su transgresión vino la salvación a los gentiles, para provocarles a celos." },
{name:'451112',l:'45',c:'11',v:'12',texto:"Y si su transgresión es la riqueza del mundo, y su defección la riqueza de los gentiles, ¿cuánto más su plena restauración? " },
{name:'451113',l:'45',c:'11',v:'13',texto:"Porque a vosotros hablo, gentiles. Por cuanto yo soy apóstol a los gentiles, honro mi ministerio," },
{name:'451114',l:'45',c:'11',v:'14',texto:"por si en alguna manera pueda provocar a celos a los de mi sangre, y hacer salvos a algunos de ellos." },
{name:'451115',l:'45',c:'11',v:'15',texto:"Porque si su exclusión es la reconciliación del mundo, ¿qué será su admisión, sino vida de entre los muertos? " },
{name:'451116',l:'45',c:'11',v:'16',texto:"Si las primicias son santas, también lo es la masa restante; y si la raíz es santa, también lo son las ramas." },
{name:'451117',l:'45',c:'11',v:'17',texto:"Pues si algunas de las ramas fueron desgajadas, y tú, siendo olivo silvestre, has sido injertado en lugar de ellas, y has sido hecho participante de la raíz y de la rica savia del olivo," },
{name:'451118',l:'45',c:'11',v:'18',texto:"no te jactes contra las ramas; y si te jactas, sabe que no sustentas tú a la raíz, sino la raíz a ti." },
{name:'451119',l:'45',c:'11',v:'19',texto:"Pues las ramas, dirás, fueron desgajadas para que yo fuese injertado." },
{name:'451120',l:'45',c:'11',v:'20',texto:"Bien; por su incredulidad fueron desgajadas, pero tú por la fe estás en pie. No te ensoberbezcas, sino teme." },
{name:'451121',l:'45',c:'11',v:'21',texto:"Porque si Dios no perdonó a las ramas naturales, a ti tampoco te perdonará." },
{name:'451122',l:'45',c:'11',v:'22',texto:"Mira, pues, la bondad y la severidad de Dios; la severidad ciertamente para con los que cayeron, pero la bondad para contigo, si permaneces en esa bondad; pues de otra manera tú también serás cortado." },
{name:'451123',l:'45',c:'11',v:'23',texto:"Y aun ellos, si no permanecieren en incredulidad, serán injertados, pues poderoso es Dios para volverlos a injertar." },
{name:'451124',l:'45',c:'11',v:'24',texto:"Porque si tú fuiste cortado del que por naturaleza es olivo silvestre, y contra naturaleza fuiste injertado en el buen olivo, ¿cuánto más éstos, que son las ramas naturales, serán injertados en su propio olivo? " },
{name:'451125',l:'45',c:'11',v:'25',texto:"Porque no quiero, hermanos, que ignoréis este misterio, para que no seáis arrogantes en cuanto a vosotros mismos: que ha acontecido a Israel endurecimiento en parte, hasta que haya entrado la plenitud de los gentiles; " },
{name:'451126',l:'45',c:'11',v:'26',texto:"y luego todo Israel será salvo, como está escrito: Vendrá de Sion el Libertador, Que apartará de Jacob la impiedad." },
{name:'451127',l:'45',c:'11',v:'27',texto:"Y este será mi pacto con ellos, Cuando yo quite sus pecados." },
{name:'451128',l:'45',c:'11',v:'28',texto:"Así que en cuanto al evangelio, son enemigos por causa de vosotros; pero en cuanto a la elección, son amados por causa de los padres." },
{name:'451129',l:'45',c:'11',v:'29',texto:"Porque irrevocables son los dones y el llamamiento de Dios." },
{name:'451130',l:'45',c:'11',v:'30',texto:"Pues como vosotros también en otro tiempo erais desobedientes a Dios, pero ahora habéis alcanzado misericordia por la desobediencia de ellos," },
{name:'451131',l:'45',c:'11',v:'31',texto:"así también éstos ahora han sido desobedientes, para que por la misericordia concedida a vosotros, ellos también alcancen misericordia." },
{name:'451132',l:'45',c:'11',v:'32',texto:"Porque Dios sujetó a todos en desobediencia, para tener misericordia de todos." },
{name:'451133',l:'45',c:'11',v:'33',texto:"¡Oh profundidad de las riquezas de la sabiduría y de la ciencia de Dios! ¡Cuán insondables son sus juicios, e inescrutables sus caminos! " },
{name:'451134',l:'45',c:'11',v:'34',texto:"Porque ¿quién entendió la mente del Señor? ¿O quién fue su consejero? " },
{name:'451135',l:'45',c:'11',v:'35',texto:"¿O quién le dio a él primero, para que le fuese recompensado? " },
{name:'451136',l:'45',c:'11',v:'36',texto:"Porque de él, y por él, y para él, son todas las cosas. A él sea la gloria por los siglos. Amén." },
],
numVersiculos: 36,
},

c12: {
versiculos:[
{name:'45121',l:'45',c:'12',v:'1',texto:"Así que, hermanos, os ruego por las misericordias de Dios, que presentéis vuestros cuerpos en sacrificio vivo, santo, agradable a Dios, que es vuestro culto racional." },
{name:'45122',l:'45',c:'12',v:'2',texto:"No os conforméis a este siglo, sino transformaos por medio de la renovación de vuestro entendimiento, para que comprobéis cuál sea la buena voluntad de Dios, agradable y perfecta." },
{name:'45123',l:'45',c:'12',v:'3',texto:"Digo, pues, por la gracia que me es dada, a cada cual que está entre vosotros, que no tenga más alto concepto de sí que el que debe tener, sino que piense de sí con cordura, conforme a la medida de fe que Dios repartió a cada uno." },
{name:'45124',l:'45',c:'12',v:'4',texto:"Porque de la manera que en un cuerpo tenemos muchos miembros, pero no todos los miembros tienen la misma función," },
{name:'45125',l:'45',c:'12',v:'5',texto:"así nosotros, siendo muchos, somos un cuerpo en Cristo, y todos miembros los unos de los otros." },
{name:'45126',l:'45',c:'12',v:'6',texto:"De manera que, teniendo diferentes dones, según la gracia que nos es dada, si el de profecía, úsese conforme a la medida de la fe; " },
{name:'45127',l:'45',c:'12',v:'7',texto:"o si de servicio, en servir; o el que enseña, en la enseñanza; " },
{name:'45128',l:'45',c:'12',v:'8',texto:"el que exhorta, en la exhortación; el que reparte, con liberalidad; el que preside, con solicitud; el que hace misericordia, con alegría." },
{name:'45129',l:'45',c:'12',v:'9',texto:"El amor sea sin fingimiento. Aborreced lo malo, seguid lo bueno." },
{name:'451210',l:'45',c:'12',v:'10',texto:"Amaos los unos a los otros con amor fraternal; en cuanto a honra, prefiriéndoos los unos a los otros." },
{name:'451211',l:'45',c:'12',v:'11',texto:"En lo que requiere diligencia, no perezosos; fervientes en espíritu, sirviendo al Señor; " },
{name:'451212',l:'45',c:'12',v:'12',texto:"gozosos en la esperanza; sufridos en la tribulación; constantes en la oración; " },
{name:'451213',l:'45',c:'12',v:'13',texto:"compartiendo para las necesidades de los santos; practicando la hospitalidad." },
{name:'451214',l:'45',c:'12',v:'14',texto:"Bendecid a los que os persiguen; bendecid, y no maldigáis." },
{name:'451215',l:'45',c:'12',v:'15',texto:"Gozaos con los que se gozan; llorad con los que lloran." },
{name:'451216',l:'45',c:'12',v:'16',texto:"Unánimes entre vosotros; no altivos, sino asociándoos con los humildes. No seáis sabios en vuestra propia opinión." },
{name:'451217',l:'45',c:'12',v:'17',texto:"No paguéis a nadie mal por mal; procurad lo bueno delante de todos los hombres." },
{name:'451218',l:'45',c:'12',v:'18',texto:"Si es posible, en cuanto dependa de vosotros, estad en paz con todos los hombres." },
{name:'451219',l:'45',c:'12',v:'19',texto:"No os venguéis vosotros mismos, amados míos, sino dejad lugar a la ira de Dios; porque escrito está: Mía es la venganza, yo pagaré, dice el Señor." },
{name:'451220',l:'45',c:'12',v:'20',texto:"Así que, si tu enemigo tuviere hambre, dale de comer; si tuviere sed, dale de beber; pues haciendo esto, ascuas de fuego amontonarás sobre su cabeza." },
{name:'451221',l:'45',c:'12',v:'21',texto:"No seas vencido de lo malo, sino vence con el bien el mal." },
],
numVersiculos: 21,
},

c13: {
versiculos:[
{name:'45131',l:'45',c:'13',v:'1',texto:"Sométase toda persona a las autoridades superiores; porque no hay autoridad sino de parte de Dios, y las que hay, por Dios han sido establecidas." },
{name:'45132',l:'45',c:'13',v:'2',texto:"De modo que quien se opone a la autoridad, a lo establecido por Dios resiste; y los que resisten, acarrean condenación para sí mismos." },
{name:'45133',l:'45',c:'13',v:'3',texto:"Porque los magistrados no están para infundir temor al que hace el bien, sino al malo. ¿Quieres, pues, no temer la autoridad? Haz lo bueno, y tendrás alabanza de ella; " },
{name:'45134',l:'45',c:'13',v:'4',texto:"porque es servidor de Dios para tu bien. Pero si haces lo malo, teme; porque no en vano lleva la espada, pues es servidor de Dios, vengador para castigar al que hace lo malo." },
{name:'45135',l:'45',c:'13',v:'5',texto:"Por lo cual es necesario estarle sujetos, no solamente por razón del castigo, sino también por causa de la conciencia." },
{name:'45136',l:'45',c:'13',v:'6',texto:"Pues por esto pagáis también los tributos, porque son servidores de Dios que atienden continuamente a esto mismo." },
{name:'45137',l:'45',c:'13',v:'7',texto:"Pagad a todos lo que debéis: al que tributo, tributo; al que impuesto, impuesto; al que respeto, respeto; al que honra, honra." },
{name:'45138',l:'45',c:'13',v:'8',texto:"No debáis a nadie nada, sino el amaros unos a otros; porque el que ama al prójimo, ha cumplido la ley." },
{name:'45139',l:'45',c:'13',v:'9',texto:"Porque: No adulterarás, no matarás, no hurtarás, no dirás falso testimonio, no codiciarás, y cualquier otro mandamiento, en esta sentencia se resume: Amarás a tu prójimo como a ti mismo." },
{name:'451310',l:'45',c:'13',v:'10',texto:"El amor no hace mal al prójimo; así que el cumplimiento de la ley es el amor." },
{name:'451311',l:'45',c:'13',v:'11',texto:"Y esto, conociendo el tiempo, que es ya hora de levantarnos del sueño; porque ahora está más cerca de nosotros nuestra salvación que cuando creímos." },
{name:'451312',l:'45',c:'13',v:'12',texto:"La noche está avanzada, y se acerca el día. Desechemos, pues, las obras de las tinieblas, y vistámonos las armas de la luz." },
{name:'451313',l:'45',c:'13',v:'13',texto:"Andemos como de día, honestamente; no en glotonerías y borracheras, no en lujurias y lascivias, no en contiendas y envidia," },
{name:'451314',l:'45',c:'13',v:'14',texto:"sino vestíos del Señor Jesucristo, y no proveáis para los deseos de la carne." },
],
numVersiculos: 14,
},

c14: {
versiculos:[
{name:'45141',l:'45',c:'14',v:'1',texto:"Recibid al débil en la fe, pero no para contender sobre opiniones." },
{name:'45142',l:'45',c:'14',v:'2',texto:"Porque uno cree que se ha de comer de todo; otro, que es débil, come legumbres." },
{name:'45143',l:'45',c:'14',v:'3',texto:"El que come, no menosprecie al que no come, y el que no come, no juzgue al que come; porque Dios le ha recibido." },
{name:'45144',l:'45',c:'14',v:'4',texto:"¿Tú quién eres, que juzgas al criado ajeno? Para su propio señor está en pie, o cae; pero estará firme, porque poderoso es el Señor para hacerle estar firme." },
{name:'45145',l:'45',c:'14',v:'5',texto:"Uno hace diferencia entre día y día; otro juzga iguales todos los días. Cada uno esté plenamente convencido en su propia mente." },
{name:'45146',l:'45',c:'14',v:'6',texto:"El que hace caso del día, lo hace para el Señor; y el que no hace caso del día, para el Señor no lo hace. El que come, para el Señor come, porque da gracias a Dios; y el que no come, para el Señor no come, y da gracias a Dios." },
{name:'45147',l:'45',c:'14',v:'7',texto:"Porque ninguno de nosotros vive para sí, y ninguno muere para sí." },
{name:'45148',l:'45',c:'14',v:'8',texto:"Pues si vivimos, para el Señor vivimos; y si morimos, para el Señor morimos. Así pues, sea que vivamos, o que muramos, del Señor somos." },
{name:'45149',l:'45',c:'14',v:'9',texto:"Porque Cristo para esto murió y resucitó, y volvió a vivir, para ser Señor así de los muertos como de los que viven." },
{name:'451410',l:'45',c:'14',v:'10',texto:"Pero tú, ¿por qué juzgas a tu hermano? O tú también, ¿por qué menosprecias a tu hermano? Porque todos compareceremos ante el tribunal de Cristo." },
{name:'451411',l:'45',c:'14',v:'11',texto:"Porque escrito está: Vivo yo, dice el Señor, que ante mí se doblará toda rodilla, Y toda lengua confesará a Dios." },
{name:'451412',l:'45',c:'14',v:'12',texto:"De manera que cada uno de nosotros dará a Dios cuenta de sí." },
{name:'451413',l:'45',c:'14',v:'13',texto:"Así que, ya no nos juzguemos más los unos a los otros, sino más bien decidid no poner tropiezo u ocasión de caer al hermano." },
{name:'451414',l:'45',c:'14',v:'14',texto:"Yo sé, y confío en el Señor Jesús, que nada es inmundo en sí mismo; mas para el que piensa que algo es inmundo, para él lo es." },
{name:'451415',l:'45',c:'14',v:'15',texto:"Pero si por causa de la comida tu hermano es contristado, ya no andas conforme al amor. No hagas que por la comida tuya se pierda aquel por quien Cristo murió." },
{name:'451416',l:'45',c:'14',v:'16',texto:"No sea, pues, vituperado vuestro bien; " },
{name:'451417',l:'45',c:'14',v:'17',texto:"porque el reino de Dios no es comida ni bebida, sino justicia, paz y gozo en el Espíritu Santo." },
{name:'451418',l:'45',c:'14',v:'18',texto:"Porque el que en esto sirve a Cristo, agrada a Dios, y es aprobado por los hombres." },
{name:'451419',l:'45',c:'14',v:'19',texto:"Así que, sigamos lo que contribuye a la paz y a la mutua edificación." },
{name:'451420',l:'45',c:'14',v:'20',texto:"No destruyas la obra de Dios por causa de la comida. Todas las cosas a la verdad son limpias; pero es malo que el hombre haga tropezar a otros con lo que come." },
{name:'451421',l:'45',c:'14',v:'21',texto:"Bueno es no comer carne, ni beber vino, ni nada en que tu hermano tropiece, o se ofenda, o se debilite." },
{name:'451422',l:'45',c:'14',v:'22',texto:"¿Tienes tú fe? Tenla para contigo delante de Dios. Bienaventurado el que no se condena a sí mismo en lo que aprueba." },
{name:'451423',l:'45',c:'14',v:'23',texto:"Pero el que duda sobre lo que come, es condenado, porque no lo hace con fe; y todo lo que no proviene de fe, es pecado." },
],
numVersiculos: 23,
},

c15: {
versiculos:[
{name:'45151',l:'45',c:'15',v:'1',texto:"Así que, los que somos fuertes debemos soportar las flaquezas de los débiles, y no agradarnos a nosotros mismos." },
{name:'45152',l:'45',c:'15',v:'2',texto:"Cada uno de nosotros agrade a su prójimo en lo que es bueno, para edificación." },
{name:'45153',l:'45',c:'15',v:'3',texto:"Porque ni aun Cristo se agradó a sí mismo; antes bien, como está escrito: Los vituperios de los que te vituperaban, cayeron sobre mí." },
{name:'45154',l:'45',c:'15',v:'4',texto:"Porque las cosas que se escribieron antes, para nuestra enseñanza se escribieron, a fin de que por la paciencia y la consolación de las Escrituras, tengamos esperanza." },
{name:'45155',l:'45',c:'15',v:'5',texto:"Pero el Dios de la paciencia y de la consolación os dé entre vosotros un mismo sentir según Cristo Jesús," },
{name:'45156',l:'45',c:'15',v:'6',texto:"para que unánimes, a una voz, glorifiquéis al Dios y Padre de nuestro Señor Jesucristo." },
{name:'45157',l:'45',c:'15',v:'7',texto:"Por tanto, recibíos los unos a los otros, como también Cristo nos recibió, para gloria de Dios." },
{name:'45158',l:'45',c:'15',v:'8',texto:"Pues os digo, que Cristo Jesús vino a ser siervo de la circuncisión para mostrar la verdad de Dios, para confirmar las promesas hechas a los padres," },
{name:'45159',l:'45',c:'15',v:'9',texto:"y para que los gentiles glorifiquen a Dios por su misericordia, como está escrito: Por tanto, yo te confesaré entre los gentiles, Y cantaré a tu nombre." },
{name:'451510',l:'45',c:'15',v:'10',texto:"Y otra vez dice: Alegraos, gentiles, con su pueblo." },
{name:'451511',l:'45',c:'15',v:'11',texto:"Y otra vez: Alabad al Señor todos los gentiles, Y magnificadle todos los pueblos." },
{name:'451512',l:'45',c:'15',v:'12',texto:"Y otra vez dice Isaías: Estará la raíz de Isaí, Y el que se levantará a regir los gentiles; Los gentiles esperarán en él." },
{name:'451513',l:'45',c:'15',v:'13',texto:"Y el Dios de esperanza os llene de todo gozo y paz en el creer, para que abundéis en esperanza por el poder del Espíritu Santo." },
{name:'451514',l:'45',c:'15',v:'14',texto:"Pero estoy seguro de vosotros, hermanos míos, de que vosotros mismos estáis llenos de bondad, llenos de todo conocimiento, de tal manera que podéis amonestaros los unos a los otros." },
{name:'451515',l:'45',c:'15',v:'15',texto:"Mas os he escrito, hermanos, en parte con atrevimiento, como para haceros recordar, por la gracia que de Dios me es dada " },
{name:'451516',l:'45',c:'15',v:'16',texto:"para ser ministro de Jesucristo a los gentiles, ministrando el evangelio de Dios, para que los gentiles le sean ofrenda agradable, santificada por el Espíritu Santo." },
{name:'451517',l:'45',c:'15',v:'17',texto:"Tengo, pues, de qué gloriarme en Cristo Jesús en lo que a Dios se refiere." },
{name:'451518',l:'45',c:'15',v:'18',texto:"Porque no osaría hablar sino de lo que Cristo ha hecho por medio de mí para la obediencia de los gentiles, con la palabra y con las obras," },
{name:'451519',l:'45',c:'15',v:'19',texto:"con potencia de señales y prodigios, en el poder del Espíritu de Dios; de manera que desde Jerusalén, y por los alrededores hasta Ilírico, todo lo he llenado del evangelio de Cristo." },
{name:'451520',l:'45',c:'15',v:'20',texto:"Y de esta manera me esforcé a predicar el evangelio, no donde Cristo ya hubiese sido nombrado, para no edificar sobre fundamento ajeno," },
{name:'451521',l:'45',c:'15',v:'21',texto:"sino, como está escrito: Aquellos a quienes nunca les fue anunciado acerca de él, verán; Y los que nunca han oído de él, entenderán." },
{name:'451522',l:'45',c:'15',v:'22',texto:"Por esta causa me he visto impedido muchas veces de ir a vosotros." },
{name:'451523',l:'45',c:'15',v:'23',texto:"Pero ahora, no teniendo más campo en estas regiones, y deseando desde hace muchos años ir a vosotros," },
{name:'451524',l:'45',c:'15',v:'24',texto:"cuando vaya a España, iré a vosotros; porque espero veros al pasar, y ser encaminado allá por vosotros, una vez que haya gozado con vosotros." },
{name:'451525',l:'45',c:'15',v:'25',texto:"Mas ahora voy a Jerusalén para ministrar a los santos." },
{name:'451526',l:'45',c:'15',v:'26',texto:"Porque Macedonia y Acaya tuvieron a bien hacer una ofrenda para los pobres que hay entre los santos que están en Jerusalén." },
{name:'451527',l:'45',c:'15',v:'27',texto:"Pues les pareció bueno, y son deudores a ellos; porque si los gentiles han sido hechos participantes de sus bienes espirituales, deben también ellos ministrarles de los materiales." },
{name:'451528',l:'45',c:'15',v:'28',texto:"Así que, cuando haya concluido esto, y les haya entregado este fruto, pasaré entre vosotros rumbo a España." },
{name:'451529',l:'45',c:'15',v:'29',texto:"Y sé que cuando vaya a vosotros, llegaré con abundancia de la bendición del evangelio de Cristo." },
{name:'451530',l:'45',c:'15',v:'30',texto:"Pero os ruego, hermanos, por nuestro Señor Jesucristo y por el amor del Espíritu, que me ayudéis orando por mí a Dios," },
{name:'451531',l:'45',c:'15',v:'31',texto:"para que sea librado de los rebeldes que están en Judea, y que la ofrenda de mi servicio a los santos en Jerusalén sea acepta; " },
{name:'451532',l:'45',c:'15',v:'32',texto:"para que con gozo llegue a vosotros por la voluntad de Dios, y que sea recreado juntamente con vosotros." },
{name:'451533',l:'45',c:'15',v:'33',texto:"Y el Dios de paz sea con todos vosotros. Amén." },
],
numVersiculos: 33,
},

c16: {
versiculos:[
{name:'45161',l:'45',c:'16',v:'1',texto:"Os recomiendo además nuestra hermana Febe, la cual es diaconisa de la iglesia en Cencrea; " },
{name:'45162',l:'45',c:'16',v:'2',texto:"que la recibáis en el Señor, como es digno de los santos, y que la ayudéis en cualquier cosa en que necesite de vosotros; porque ella ha ayudado a muchos, y a mí mismo." },
{name:'45163',l:'45',c:'16',v:'3',texto:"Saludad a Priscila y a Aquila, mis colaboradores en Cristo Jesús," },
{name:'45164',l:'45',c:'16',v:'4',texto:"que expusieron su vida por mí; a los cuales no sólo yo doy gracias, sino también todas las iglesias de los gentiles." },
{name:'45165',l:'45',c:'16',v:'5',texto:"Saludad también a la iglesia de su casa. Saludad a Epeneto, amado mío, que es el primer fruto de Acaya para Cristo." },
{name:'45166',l:'45',c:'16',v:'6',texto:"Saludad a María, la cual ha trabajado mucho entre vosotros." },
{name:'45167',l:'45',c:'16',v:'7',texto:"Saludad a Andrónico y a Junias, mis parientes y mis compañeros de prisiones, los cuales son muy estimados entre los apóstoles, y que también fueron antes de mí en Cristo." },
{name:'45168',l:'45',c:'16',v:'8',texto:"Saludad a Amplias, amado mío en el Señor." },
{name:'45169',l:'45',c:'16',v:'9',texto:"Saludad a Urbano, nuestro colaborador en Cristo Jesús, y a Estaquis, amado mío." },
{name:'451610',l:'45',c:'16',v:'10',texto:"Saludad a Apeles, aprobado en Cristo. Saludad a los de la casa de Aristóbulo." },
{name:'451611',l:'45',c:'16',v:'11',texto:"Saludad a Herodión, mi pariente. Saludad a los de la casa de Narciso, los cuales están en el Señor." },
{name:'451612',l:'45',c:'16',v:'12',texto:"Saludad a Trifena y a Trifosa, las cuales trabajan en el Señor. Saludad a la amada Pérsida, la cual ha trabajado mucho en el Señor." },
{name:'451613',l:'45',c:'16',v:'13',texto:"Saludad a Rufo, escogido en el Señor, y a su madre y mía." },
{name:'451614',l:'45',c:'16',v:'14',texto:"Saludad a Asíncrito, a Flegonte, a Hermas, a Patrobas, a Hermes y a los hermanos que están con ellos." },
{name:'451615',l:'45',c:'16',v:'15',texto:"Saludad a Filólogo, a Julia, a Nereo y a su hermana, a Olimpas y a todos los santos que están con ellos." },
{name:'451616',l:'45',c:'16',v:'16',texto:"Saludaos los unos a los otros con ósculo santo. Os saludan todas las iglesias de Cristo." },
{name:'451617',l:'45',c:'16',v:'17',texto:"Mas os ruego, hermanos, que os fijéis en los que causan divisiones y tropiezos en contra de la doctrina que vosotros habéis aprendido, y que os apartéis de ellos." },
{name:'451618',l:'45',c:'16',v:'18',texto:"Porque tales personas no sirven a nuestro Señor Jesucristo, sino a sus propios vientres, y con suaves palabras y lisonjas engañan los corazones de los ingenuos." },
{name:'451619',l:'45',c:'16',v:'19',texto:"Porque vuestra obediencia ha venido a ser notoria a todos, así que me gozo de vosotros; pero quiero que seáis sabios para el bien, e ingenuos para el mal." },
{name:'451620',l:'45',c:'16',v:'20',texto:"Y el Dios de paz aplastará en breve a Satanás bajo vuestros pies. La gracia de nuestro Señor Jesucristo sea con vosotros." },
{name:'451621',l:'45',c:'16',v:'21',texto:"Os saludan Timoteo mi colaborador, y Lucio, Jasón y Sosípater, mis parientes." },
{name:'451622',l:'45',c:'16',v:'22',texto:"Yo Tercio, que escribí la epístola, os saludo en el Señor." },
{name:'451623',l:'45',c:'16',v:'23',texto:"Os saluda Gayo, hospedador mío y de toda la iglesia. Os saluda Erasto, tesorero de la ciudad, y el hermano Cuarto." },
{name:'451624',l:'45',c:'16',v:'24',texto:"La gracia de nuestro Señor Jesucristo sea con todos vosotros. Amén." },
{name:'451625',l:'45',c:'16',v:'25',texto:"Y al que puede confirmaros según mi evangelio y la predicación de Jesucristo, según la revelación del misterio que se ha mantenido oculto desde tiempos eternos," },
{name:'451626',l:'45',c:'16',v:'26',texto:"pero que ha sido manifestado ahora, y que por las Escrituras de los profetas, según el mandamiento del Dios eterno, se ha dado a conocer a todas las gentes para que obedezcan a la fe," },
{name:'451627',l:'45',c:'16',v:'27',texto:"al único y sabio Dios, sea gloria mediante Jesucristo para siempre. Amén." },
],
numVersiculos: 27,
},
	

};
