BibliaRVR60.corintios1 = {
	libro: "1 Corintios",
	numCapitulos: 16,

c1: {
versiculos:[
{name:'4611',l:'46',c:'1',v:'1',texto:"Pablo, llamado a ser apóstol de Jesucristo por la voluntad de Dios, y el hermano Sóstenes," },
{name:'4612',l:'46',c:'1',v:'2',texto:"a la iglesia de Dios que está en Corinto, a los santificados en Cristo Jesús, llamados a ser santos con todos los que en cualquier lugar invocan el nombre de nuestro Señor Jesucristo, Señor de ellos y nuestro: " },
{name:'4613',l:'46',c:'1',v:'3',texto:"Gracia y paz a vosotros, de Dios nuestro Padre y del Señor Jesucristo." },
{name:'4614',l:'46',c:'1',v:'4',texto:"Gracias doy a mi Dios siempre por vosotros, por la gracia de Dios que os fue dada en Cristo Jesús; " },
{name:'4615',l:'46',c:'1',v:'5',texto:"porque en todas las cosas fuisteis enriquecidos en él, en toda palabra y en toda ciencia; " },
{name:'4616',l:'46',c:'1',v:'6',texto:"así como el testimonio acerca de Cristo ha sido confirmado en vosotros," },
{name:'4617',l:'46',c:'1',v:'7',texto:"de tal manera que nada os falta en ningún don, esperando la manifestación de nuestro Señor Jesucristo; " },
{name:'4618',l:'46',c:'1',v:'8',texto:"el cual también os confirmará hasta el fin, para que seáis irreprensibles en el día de nuestro Señor Jesucristo." },
{name:'4619',l:'46',c:'1',v:'9',texto:"Fiel es Dios, por el cual fuisteis llamados a la comunión con su Hijo Jesucristo nuestro Señor. ¿Está dividido Cristo? " },
{name:'46110',l:'46',c:'1',v:'10',texto:"Os ruego, pues, hermanos, por el nombre de nuestro Señor Jesucristo, que habléis todos una misma cosa, y que no haya entre vosotros divisiones, sino que estéis perfectamente unidos en una misma mente y en un mismo parecer." },
{name:'46111',l:'46',c:'1',v:'11',texto:"Porque he sido informado acerca de vosotros, hermanos míos, por los de Cloé, que hay entre vosotros contiendas." },
{name:'46112',l:'46',c:'1',v:'12',texto:"Quiero decir, que cada uno de vosotros dice: Yo soy de Pablo; y yo de Apolos; y yo de Cefas; y yo de Cristo." },
{name:'46113',l:'46',c:'1',v:'13',texto:"¿Acaso está dividido Cristo? ¿Fue crucificado Pablo por vosotros? ¿O fuisteis bautizados en el nombre de Pablo? " },
{name:'46114',l:'46',c:'1',v:'14',texto:"Doy gracias a Dios de que a ninguno de vosotros he bautizado, sino a Crispo y a Gayo," },
{name:'46115',l:'46',c:'1',v:'15',texto:"para que ninguno diga que fuisteis bautizados en mi nombre." },
{name:'46116',l:'46',c:'1',v:'16',texto:"También bauticé a la familia de Estéfanas; de los demás, no sé si he bautizado a algún otro." },
{name:'46117',l:'46',c:'1',v:'17',texto:"Pues no me envió Cristo a bautizar, sino a predicar el evangelio; no con sabiduría de palabras, para que no se haga vana la cruz de Cristo." },
{name:'46118',l:'46',c:'1',v:'18',texto:"Porque la palabra de la cruz es locura a los que se pierden; pero a los que se salvan, esto es, a nosotros, es poder de Dios." },
{name:'46119',l:'46',c:'1',v:'19',texto:"Pues está escrito: Destruiré la sabiduría de los sabios, Y desecharé el entendimiento de los entendidos." },
{name:'46120',l:'46',c:'1',v:'20',texto:"¿Dónde está el sabio? ¿Dónde está el escriba? ¿Dónde está el disputador de este siglo? ¿No ha enloquecido Dios la sabiduría del mundo? " },
{name:'46121',l:'46',c:'1',v:'21',texto:"Pues ya que en la sabiduría de Dios, el mundo no conoció a Dios mediante la sabiduría, agradó a Dios salvar a los creyentes por la locura de la predicación." },
{name:'46122',l:'46',c:'1',v:'22',texto:"Porque los judíos piden señales, y los griegos buscan sabiduría; " },
{name:'46123',l:'46',c:'1',v:'23',texto:"pero nosotros predicamos a Cristo crucificado, para los judíos ciertamente tropezadero, y para los gentiles locura; " },
{name:'46124',l:'46',c:'1',v:'24',texto:"mas para los llamados, así judíos como griegos, Cristo poder de Dios, y sabiduría de Dios." },
{name:'46125',l:'46',c:'1',v:'25',texto:"Porque lo insensato de Dios es más sabio que los hombres, y lo débil de Dios es más fuerte que los hombres." },
{name:'46126',l:'46',c:'1',v:'26',texto:"Pues mirad, hermanos, vuestra vocación, que no sois muchos sabios según la carne, ni muchos poderosos, ni muchos nobles; " },
{name:'46127',l:'46',c:'1',v:'27',texto:"sino que lo necio del mundo escogió Dios, para avergonzar a los sabios; y lo débil del mundo escogió Dios, para avergonzar a lo fuerte; " },
{name:'46128',l:'46',c:'1',v:'28',texto:"y lo vil del mundo y lo menospreciado escogió Dios, y lo que no es, para deshacer lo que es," },
{name:'46129',l:'46',c:'1',v:'29',texto:"a fin de que nadie se jacte en su presencia." },
{name:'46130',l:'46',c:'1',v:'30',texto:"Mas por él estáis vosotros en Cristo Jesús, el cual nos ha sido hecho por Dios sabiduría, justificación, santificación y redención; " },
{name:'46131',l:'46',c:'1',v:'31',texto:"para que, como está escrito: El que se gloría, gloríese en el Señor." },
],
numVersiculos: 31,
},

c2: {
versiculos:[
{name:'4621',l:'46',c:'2',v:'1',texto:"Así que, hermanos, cuando fui a vosotros para anunciaros el testimonio de Dios, no fui con excelencia de palabras o de sabiduría." },
{name:'4622',l:'46',c:'2',v:'2',texto:"Pues me propuse no saber entre vosotros cosa alguna sino a Jesucristo, y a éste crucificado." },
{name:'4623',l:'46',c:'2',v:'3',texto:"Y estuve entre vosotros con debilidad, y mucho temor y temblor; " },
{name:'4624',l:'46',c:'2',v:'4',texto:"y ni mi palabra ni mi predicación fue con palabras persuasivas de humana sabiduría, sino con demostración del Espíritu y de poder," },
{name:'4625',l:'46',c:'2',v:'5',texto:"para que vuestra fe no esté fundada en la sabiduría de los hombres, sino en el poder de Dios." },
{name:'4626',l:'46',c:'2',v:'6',texto:"Sin embargo, hablamos sabiduría entre los que han alcanzado madurez; y sabiduría, no de este siglo, ni de los príncipes de este siglo, que perecen." },
{name:'4627',l:'46',c:'2',v:'7',texto:"Mas hablamos sabiduría de Dios en misterio, la sabiduría oculta, la cual Dios predestinó antes de los siglos para nuestra gloria," },
{name:'4628',l:'46',c:'2',v:'8',texto:"la que ninguno de los príncipes de este siglo conoció; porque si la hubieran conocido, nunca habrían crucificado al Señor de gloria." },
{name:'4629',l:'46',c:'2',v:'9',texto:"Antes bien, como está escrito: Cosas que ojo no vio, ni oído oyó, Ni han subido en corazón de hombre, Son las que Dios ha preparado para los que le aman." },
{name:'46210',l:'46',c:'2',v:'10',texto:"Pero Dios nos las reveló a nosotros por el Espíritu; porque el Espíritu todo lo escudriña, aun lo profundo de Dios." },
{name:'46211',l:'46',c:'2',v:'11',texto:"Porque ¿quién de los hombres sabe las cosas del hombre, sino el espíritu del hombre que está en él? Así tampoco nadie conoció las cosas de Dios, sino el Espíritu de Dios." },
{name:'46212',l:'46',c:'2',v:'12',texto:"Y nosotros no hemos recibido el espíritu del mundo, sino el Espíritu que proviene de Dios, para que sepamos lo que Dios nos ha concedido," },
{name:'46213',l:'46',c:'2',v:'13',texto:"lo cual también hablamos, no con palabras enseñadas por sabiduría humana, sino con las que enseña el Espíritu, acomodando lo espiritual a lo espiritual." },
{name:'46214',l:'46',c:'2',v:'14',texto:"Pero el hombre natural no percibe las cosas que son del Espíritu de Dios, porque para él son locura, y no las puede entender, porque se han de discernir espiritualmente." },
{name:'46215',l:'46',c:'2',v:'15',texto:"En cambio el espiritual juzga todas las cosas; pero él no es juzgado de nadie." },
{name:'46216',l:'46',c:'2',v:'16',texto:"Porque ¿quién conoció la mente del Señor? ¿Quién le instruirá? Mas nosotros tenemos la mente de Cristo." },
],
numVersiculos: 16,
},

c3: {
versiculos:[
{name:'4631',l:'46',c:'3',v:'1',texto:"De manera que yo, hermanos, no pude hablaros como a espirituales, sino como a carnales, como a niños en Cristo." },
{name:'4632',l:'46',c:'3',v:'2',texto:"Os di a beber leche, y no vianda; porque aún no erais capaces, ni sois capaces todavía," },
{name:'4633',l:'46',c:'3',v:'3',texto:"porque aún sois carnales; pues habiendo entre vosotros celos, contiendas y disensiones, ¿no sois carnales, y andáis como hombres? " },
{name:'4634',l:'46',c:'3',v:'4',texto:"Porque diciendo el uno: Yo ciertamente soy de Pablo; y el otro: Yo soy de Apolos, ¿no sois carnales? " },
{name:'4635',l:'46',c:'3',v:'5',texto:"¿Qué, pues, es Pablo, y qué es Apolos? Servidores por medio de los cuales habéis creído; y eso según lo que a cada uno concedió el Señor." },
{name:'4636',l:'46',c:'3',v:'6',texto:"Yo planté, Apolos regó; pero el crecimiento lo ha dado Dios." },
{name:'4637',l:'46',c:'3',v:'7',texto:"Así que ni el que planta es algo, ni el que riega, sino Dios, que da el crecimiento." },
{name:'4638',l:'46',c:'3',v:'8',texto:"Y el que planta y el que riega son una misma cosa; aunque cada uno recibirá su recompensa conforme a su labor." },
{name:'4639',l:'46',c:'3',v:'9',texto:"Porque nosotros somos colaboradores de Dios, y vosotros sois labranza de Dios, edificio de Dios." },
{name:'46310',l:'46',c:'3',v:'10',texto:"Conforme a la gracia de Dios que me ha sido dada, yo como perito arquitecto puse el fundamento, y otro edifica encima; pero cada uno mire cómo sobreedifica." },
{name:'46311',l:'46',c:'3',v:'11',texto:"Porque nadie puede poner otro fundamento que el que está puesto, el cual es Jesucristo." },
{name:'46312',l:'46',c:'3',v:'12',texto:"Y si sobre este fundamento alguno edificare oro, plata, piedras preciosas, madera, heno, hojarasca," },
{name:'46313',l:'46',c:'3',v:'13',texto:"la obra de cada uno se hará manifiesta; porque el día la declarará, pues por el fuego será revelada; y la obra de cada uno cuál sea, el fuego la probará." },
{name:'46314',l:'46',c:'3',v:'14',texto:"Si permaneciere la obra de alguno que sobreedificó, recibirá recompensa." },
{name:'46315',l:'46',c:'3',v:'15',texto:"Si la obra de alguno se quemare, él sufrirá pérdida, si bien él mismo será salvo, aunque así como por fuego." },
{name:'46316',l:'46',c:'3',v:'16',texto:"¿No sabéis que sois templo de Dios, y que el Espíritu de Dios mora en vosotros? " },
{name:'46317',l:'46',c:'3',v:'17',texto:"Si alguno destruyere el templo de Dios, Dios le destruirá a él; porque el templo de Dios, el cual sois vosotros, santo es." },
{name:'46318',l:'46',c:'3',v:'18',texto:"Nadie se engañe a sí mismo; si alguno entre vosotros se cree sabio en este siglo, hágase ignorante, para que llegue a ser sabio." },
{name:'46319',l:'46',c:'3',v:'19',texto:"Porque la sabiduría de este mundo es insensatez para con Dios; pues escrito está: Él prende a los sabios en la astucia de ellos." },
{name:'46320',l:'46',c:'3',v:'20',texto:"Y otra vez: El Señor conoce los pensamientos de los sabios, que son vanos." },
{name:'46321',l:'46',c:'3',v:'21',texto:"Así que, ninguno se gloríe en los hombres; porque todo es vuestro: " },
{name:'46322',l:'46',c:'3',v:'22',texto:"sea Pablo, sea Apolos, sea Cefas, sea el mundo, sea la vida, sea la muerte, sea lo presente, sea lo por venir, todo es vuestro," },
{name:'46323',l:'46',c:'3',v:'23',texto:"y vosotros de Cristo, y Cristo de Dios." },
],
numVersiculos: 23,
},

c4: {
versiculos:[
{name:'4641',l:'46',c:'4',v:'1',texto:"Así, pues, téngannos los hombres por servidores de Cristo, y administradores de los misterios de Dios." },
{name:'4642',l:'46',c:'4',v:'2',texto:"Ahora bien, se requiere de los administradores, que cada uno sea hallado fiel." },
{name:'4643',l:'46',c:'4',v:'3',texto:"Yo en muy poco tengo el ser juzgado por vosotros, o por tribunal humano; y ni aun yo me juzgo a mí mismo." },
{name:'4644',l:'46',c:'4',v:'4',texto:"Porque aunque de nada tengo mala conciencia, no por eso soy justificado; pero el que me juzga es el Señor." },
{name:'4645',l:'46',c:'4',v:'5',texto:"Así que, no juzguéis nada antes de tiempo, hasta que venga el Señor, el cual aclarará también lo oculto de las tinieblas, y manifestará las intenciones de los corazones; y entonces cada uno recibirá su alabanza de Dios." },
{name:'4646',l:'46',c:'4',v:'6',texto:"Pero esto, hermanos, lo he presentado como ejemplo en mí y en Apolos por amor de vosotros, para que en nosotros aprendáis a no pensar más de lo que está escrito, no sea que por causa de uno, os envanezcáis unos contra otros." },
{name:'4647',l:'46',c:'4',v:'7',texto:"Porque ¿quién te distingue? ¿o qué tienes que no hayas recibido? Y si lo recibiste, ¿por qué te glorías como si no lo hubieras recibido? " },
{name:'4648',l:'46',c:'4',v:'8',texto:"Ya estáis saciados, ya estáis ricos, sin nosotros reináis. ¡Y ojalá reinaseis, para que nosotros reinásemos también juntamente con vosotros! " },
{name:'4649',l:'46',c:'4',v:'9',texto:"Porque según pienso, Dios nos ha exhibido a nosotros los apóstoles como postreros, como a sentenciados a muerte; pues hemos llegado a ser espectáculo al mundo, a los ángeles y a los hombres." },
{name:'46410',l:'46',c:'4',v:'10',texto:"Nosotros somos insensatos por amor de Cristo, mas vosotros prudentes en Cristo; nosotros débiles, mas vosotros fuertes; vosotros honorables, mas nosotros despreciados." },
{name:'46411',l:'46',c:'4',v:'11',texto:"Hasta esta hora padecemos hambre, tenemos sed, estamos desnudos, somos abofeteados, y no tenemos morada fija." },
{name:'46412',l:'46',c:'4',v:'12',texto:"Nos fatigamos trabajando con nuestras propias manos; nos maldicen, y bendecimos; padecemos persecución, y la soportamos." },
{name:'46413',l:'46',c:'4',v:'13',texto:"Nos difaman, y rogamos; hemos venido a ser hasta ahora como la escoria del mundo, el desecho de todos." },
{name:'46414',l:'46',c:'4',v:'14',texto:"No escribo esto para avergonzaros, sino para amonestaros como a hijos míos amados." },
{name:'46415',l:'46',c:'4',v:'15',texto:"Porque aunque tengáis diez mil ayos en Cristo, no tendréis muchos padres; pues en Cristo Jesús yo os engendré por medio del evangelio." },
{name:'46416',l:'46',c:'4',v:'16',texto:"Por tanto, os ruego que me imitéis." },
{name:'46417',l:'46',c:'4',v:'17',texto:"Por esto mismo os he enviado a Timoteo, que es mi hijo amado y fiel en el Señor, el cual os recordará mi proceder en Cristo, de la manera que enseño en todas partes y en todas las iglesias." },
{name:'46418',l:'46',c:'4',v:'18',texto:"Mas algunos están envanecidos, como si yo nunca hubiese de ir a vosotros." },
{name:'46419',l:'46',c:'4',v:'19',texto:"Pero iré pronto a vosotros, si el Señor quiere, y conoceré, no las palabras, sino el poder de los que andan envanecidos." },
{name:'46420',l:'46',c:'4',v:'20',texto:"Porque el reino de Dios no consiste en palabras, sino en poder." },
{name:'46421',l:'46',c:'4',v:'21',texto:"¿Qué queréis? ¿Iré a vosotros con vara, o con amor y espíritu de mansedumbre? " },
],
numVersiculos: 21,
},

c5: {
versiculos:[
{name:'4651',l:'46',c:'5',v:'1',texto:"De cierto se oye que hay entre vosotros fornicación, y tal fornicación cual ni aun se nombra entre los gentiles; tanto que alguno tiene la mujer de su padre." },
{name:'4652',l:'46',c:'5',v:'2',texto:"Y vosotros estáis envanecidos. ¿No debierais más bien haberos lamentado, para que fuese quitado de en medio de vosotros el que cometió tal acción? " },
{name:'4653',l:'46',c:'5',v:'3',texto:"Ciertamente yo, como ausente en cuerpo, pero presente en espíritu, ya como presente he juzgado al que tal cosa ha hecho." },
{name:'4654',l:'46',c:'5',v:'4',texto:"En el nombre de nuestro Señor Jesucristo, reunidos vosotros y mi espíritu, con el poder de nuestro Señor Jesucristo," },
{name:'4655',l:'46',c:'5',v:'5',texto:"el tal sea entregado a Satanás para destrucción de la carne, a fin de que el espíritu sea salvo en el día del Señor Jesús." },
{name:'4656',l:'46',c:'5',v:'6',texto:"No es buena vuestra jactancia. ¿No sabéis que un poco de levadura leuda toda la masa? " },
{name:'4657',l:'46',c:'5',v:'7',texto:"Limpiaos, pues, de la vieja levadura, para que seáis nueva masa, sin levadura como sois; porque nuestra pascua, que es Cristo, ya fue sacrificada por nosotros." },
{name:'4658',l:'46',c:'5',v:'8',texto:"Así que celebremos la fiesta, no con la vieja levadura, ni con la levadura de malicia y de maldad, sino con panes sin levadura, de sinceridad y de verdad." },
{name:'4659',l:'46',c:'5',v:'9',texto:"Os he escrito por carta, que no os juntéis con los fornicarios; " },
{name:'46510',l:'46',c:'5',v:'10',texto:"no absolutamente con los fornicarios de este mundo, o con los avaros, o con los ladrones, o con los idólatras; pues en tal caso os sería necesario salir del mundo." },
{name:'46511',l:'46',c:'5',v:'11',texto:"Más bien os escribí que no os juntéis con ninguno que, llamándose hermano, fuere fornicario, o avaro, o idólatra, o maldiciente, o borracho, o ladrón; con el tal ni aun comáis." },
{name:'46512',l:'46',c:'5',v:'12',texto:"Porque ¿qué razón tendría yo para juzgar a los que están fuera? ¿No juzgáis vosotros a los que están dentro? " },
{name:'46513',l:'46',c:'5',v:'13',texto:"Porque a los que están fuera, Dios juzgará. Quitad, pues, a ese perverso de entre vosotros." },
],
numVersiculos: 13,
},

c6: {
versiculos:[
{name:'4661',l:'46',c:'6',v:'1',texto:"¿Osa alguno de vosotros, cuando tiene algo contra otro, ir a juicio delante de los injustos, y no delante de los santos? " },
{name:'4662',l:'46',c:'6',v:'2',texto:"¿O no sabéis que los santos han de juzgar al mundo? Y si el mundo ha de ser juzgado por vosotros, ¿sois indignos de juzgar cosas muy pequeñas? " },
{name:'4663',l:'46',c:'6',v:'3',texto:"¿O no sabéis que hemos de juzgar a los ángeles? ¿Cuánto más las cosas de esta vida? " },
{name:'4664',l:'46',c:'6',v:'4',texto:"Si, pues, tenéis juicios sobre cosas de esta vida, ¿ponéis para juzgar a los que son de menor estima en la iglesia? " },
{name:'4665',l:'46',c:'6',v:'5',texto:"Para avergonzaros lo digo. ¿Pues qué, no hay entre vosotros sabio, ni aun uno, que pueda juzgar entre sus hermanos," },
{name:'4666',l:'46',c:'6',v:'6',texto:"sino que el hermano con el hermano pleitea en juicio, y esto ante los incrédulos? " },
{name:'4667',l:'46',c:'6',v:'7',texto:"Así que, por cierto es ya una falta en vosotros que tengáis pleitos entre vosotros mismos. ¿Por qué no sufrís más bien el agravio? ¿Por qué no sufrís más bien el ser defraudados? " },
{name:'4668',l:'46',c:'6',v:'8',texto:"Pero vosotros cometéis el agravio, y defraudáis, y esto a los hermanos." },
{name:'4669',l:'46',c:'6',v:'9',texto:"¿No sabéis que los injustos no heredarán el reino de Dios? No erréis; ni los fornicarios, ni los idólatras, ni los adúlteros, ni los afeminados, ni los que se echan con varones," },
{name:'46610',l:'46',c:'6',v:'10',texto:"ni los ladrones, ni los avaros, ni los borrachos, ni los maldicientes, ni los estafadores, heredarán el reino de Dios." },
{name:'46611',l:'46',c:'6',v:'11',texto:"Y esto erais algunos; mas ya habéis sido lavados, ya habéis sido santificados, ya habéis sido justificados en el nombre del Señor Jesús, y por el Espíritu de nuestro Dios." },
{name:'46612',l:'46',c:'6',v:'12',texto:"Todas las cosas me son lícitas, mas no todas convienen; todas las cosas me son lícitas, mas yo no me dejaré dominar de ninguna." },
{name:'46613',l:'46',c:'6',v:'13',texto:"Las viandas para el vientre, y el vientre para las viandas; pero tanto al uno como a las otras destruirá Dios. Pero el cuerpo no es para la fornicación, sino para el Señor, y el Señor para el cuerpo." },
{name:'46614',l:'46',c:'6',v:'14',texto:"Y Dios, que levantó al Señor, también a nosotros nos levantará con su poder." },
{name:'46615',l:'46',c:'6',v:'15',texto:"¿No sabéis que vuestros cuerpos son miembros de Cristo? ¿Quitaré, pues, los miembros de Cristo y los haré miembros de una ramera? De ningún modo." },
{name:'46616',l:'46',c:'6',v:'16',texto:"¿O no sabéis que el que se une con una ramera, es un cuerpo con ella? Porque dice: Los dos serán una sola carne." },
{name:'46617',l:'46',c:'6',v:'17',texto:"Pero el que se une al Señor, un espíritu es con él." },
{name:'46618',l:'46',c:'6',v:'18',texto:"Huid de la fornicación. Cualquier otro pecado que el hombre cometa, está fuera del cuerpo; mas el que fornica, contra su propio cuerpo peca." },
{name:'46619',l:'46',c:'6',v:'19',texto:"¿O ignoráis que vuestro cuerpo es templo del Espíritu Santo, el cual está en vosotros, el cual tenéis de Dios, y que no sois vuestros? " },
{name:'46620',l:'46',c:'6',v:'20',texto:"Porque habéis sido comprados por precio; glorificad, pues, a Dios en vuestro cuerpo y en vuestro espíritu, los cuales son de Dios." },
],
numVersiculos: 20,
},

c7: {
versiculos:[
{name:'4671',l:'46',c:'7',v:'1',texto:"En cuanto a las cosas de que me escribisteis, bueno le sería al hombre no tocar mujer; " },
{name:'4672',l:'46',c:'7',v:'2',texto:"pero a causa de las fornicaciones, cada uno tenga su propia mujer, y cada una tenga su propio marido." },
{name:'4673',l:'46',c:'7',v:'3',texto:"El marido cumpla con la mujer el deber conyugal, y asimismo la mujer con el marido." },
{name:'4674',l:'46',c:'7',v:'4',texto:"La mujer no tiene potestad sobre su propio cuerpo, sino el marido; ni tampoco tiene el marido potestad sobre su propio cuerpo, sino la mujer." },
{name:'4675',l:'46',c:'7',v:'5',texto:"No os neguéis el uno al otro, a no ser por algún tiempo de mutuo consentimiento, para ocuparos sosegadamente en la oración; y volved a juntaros en uno, para que no os tiente Satanás a causa de vuestra incontinencia." },
{name:'4676',l:'46',c:'7',v:'6',texto:"Mas esto digo por vía de concesión, no por mandamiento." },
{name:'4677',l:'46',c:'7',v:'7',texto:"Quisiera más bien que todos los hombres fuesen como yo; pero cada uno tiene su propio don de Dios, uno a la verdad de un modo, y otro de otro." },
{name:'4678',l:'46',c:'7',v:'8',texto:"Digo, pues, a los solteros y a las viudas, que bueno les fuera quedarse como yo; " },
{name:'4679',l:'46',c:'7',v:'9',texto:"pero si no tienen don de continencia, cásense, pues mejor es casarse que estarse quemando." },
{name:'46710',l:'46',c:'7',v:'10',texto:"Pero a los que están unidos en matrimonio, mando, no yo, sino el Señor: Que la mujer no se separe del marido; " },
{name:'46711',l:'46',c:'7',v:'11',texto:"y si se separa, quédese sin casar, o reconcíliese con su marido; y que el marido no abandone a su mujer." },
{name:'46712',l:'46',c:'7',v:'12',texto:"Y a los demás yo digo, no el Señor: Si algún hermano tiene mujer que no sea creyente, y ella consiente en vivir con él, no la abandone." },
{name:'46713',l:'46',c:'7',v:'13',texto:"Y si una mujer tiene marido que no sea creyente, y él consiente en vivir con ella, no lo abandone." },
{name:'46714',l:'46',c:'7',v:'14',texto:"Porque el marido incrédulo es santificado en la mujer, y la mujer incrédula en el marido; pues de otra manera vuestros hijos serían inmundos, mientras que ahora son santos." },
{name:'46715',l:'46',c:'7',v:'15',texto:"Pero si el incrédulo se separa, sepárese; pues no está el hermano o la hermana sujeto a servidumbre en semejante caso, sino que a paz nos llamó Dios." },
{name:'46716',l:'46',c:'7',v:'16',texto:"Porque ¿qué sabes tú, oh mujer, si quizá harás salvo a tu marido? ¿O qué sabes tú, oh marido, si quizá harás salva a tu mujer? " },
{name:'46717',l:'46',c:'7',v:'17',texto:"Pero cada uno como el Señor le repartió, y como Dios llamó a cada uno, así haga; esto ordeno en todas las iglesias." },
{name:'46718',l:'46',c:'7',v:'18',texto:"¿Fue llamado alguno siendo circunciso? Quédese circunciso. ¿Fue llamado alguno siendo incircunciso? No se circuncide." },
{name:'46719',l:'46',c:'7',v:'19',texto:"La circuncisión nada es, y la incircuncisión nada es, sino el guardar los mandamientos de Dios." },
{name:'46720',l:'46',c:'7',v:'20',texto:"Cada uno en el estado en que fue llamado, en él se quede." },
{name:'46721',l:'46',c:'7',v:'21',texto:"¿Fuiste llamado siendo esclavo? No te dé cuidado; pero también, si puedes hacerte libre, procúralo más." },
{name:'46722',l:'46',c:'7',v:'22',texto:"Porque el que en el Señor fue llamado siendo esclavo, liberto es del Señor; asimismo el que fue llamado siendo libre, esclavo es de Cristo." },
{name:'46723',l:'46',c:'7',v:'23',texto:"Por precio fuisteis comprados; no os hagáis esclavos de los hombres." },
{name:'46724',l:'46',c:'7',v:'24',texto:"Cada uno, hermanos, en el estado en que fue llamado, así permanezca para con Dios." },
{name:'46725',l:'46',c:'7',v:'25',texto:"En cuanto a las vírgenes no tengo mandamiento del Señor; mas doy mi parecer, como quien ha alcanzado misericordia del Señor para ser fiel." },
{name:'46726',l:'46',c:'7',v:'26',texto:"Tengo, pues, esto por bueno a causa de la necesidad que apremia; que hará bien el hombre en quedarse como está." },
{name:'46727',l:'46',c:'7',v:'27',texto:"¿Estás ligado a mujer? No procures soltarte. ¿Estás libre de mujer? No procures casarte." },
{name:'46728',l:'46',c:'7',v:'28',texto:"Mas también si te casas, no pecas; y si la doncella se casa, no peca; pero los tales tendrán aflicción de la carne, y yo os la quisiera evitar." },
{name:'46729',l:'46',c:'7',v:'29',texto:"Pero esto digo, hermanos: que el tiempo es corto; resta, pues, que los que tienen esposa sean como si no la tuviesen; " },
{name:'46730',l:'46',c:'7',v:'30',texto:"y los que lloran, como si no llorasen; y los que se alegran, como si no se alegrasen; y los que compran, como si no poseyesen; " },
{name:'46731',l:'46',c:'7',v:'31',texto:"y los que disfrutan de este mundo, como si no lo disfrutasen; porque la apariencia de este mundo se pasa." },
{name:'46732',l:'46',c:'7',v:'32',texto:"Quisiera, pues, que estuvieseis sin congoja. El soltero tiene cuidado de las cosas del Señor, de cómo agradar al Señor; " },
{name:'46733',l:'46',c:'7',v:'33',texto:"pero el casado tiene cuidado de las cosas del mundo, de cómo agradar a su mujer." },
{name:'46734',l:'46',c:'7',v:'34',texto:"Hay asimismo diferencia entre la casada y la doncella. La doncella tiene cuidado de las cosas del Señor, para ser santa así en cuerpo como en espíritu; pero la casada tiene cuidado de las cosas del mundo, de cómo agradar a su marido." },
{name:'46735',l:'46',c:'7',v:'35',texto:"Esto lo digo para vuestro provecho; no para tenderos lazo, sino para lo honesto y decente, y para que sin impedimento os acerquéis al Señor." },
{name:'46736',l:'46',c:'7',v:'36',texto:"Pero si alguno piensa que es impropio para su hija virgen que pase ya de edad, y es necesario que así sea, haga lo que quiera, no peca; que se case." },
{name:'46737',l:'46',c:'7',v:'37',texto:"Pero el que está firme en su corazón, sin tener necesidad, sino que es dueño de su propia voluntad, y ha resuelto en su corazón guardar a su hija virgen, bien hace." },
{name:'46738',l:'46',c:'7',v:'38',texto:"De manera que el que la da en casamiento hace bien, y el que no la da en casamiento hace mejor." },
{name:'46739',l:'46',c:'7',v:'39',texto:"La mujer casada está ligada por la ley mientras su marido vive; pero si su marido muriere, libre es para casarse con quien quiera, con tal que sea en el Señor." },
{name:'46740',l:'46',c:'7',v:'40',texto:"Pero a mi juicio, más dichosa será si se quedare así; y pienso que también yo tengo el Espíritu de Dios." },
],
numVersiculos: 40,
},

c8: {
versiculos:[
{name:'4681',l:'46',c:'8',v:'1',texto:"En cuanto a lo sacrificado a los ídolos, sabemos que todos tenemos conocimiento. El conocimiento envanece, pero el amor edifica." },
{name:'4682',l:'46',c:'8',v:'2',texto:"Y si alguno se imagina que sabe algo, aún no sabe nada como debe saberlo." },
{name:'4683',l:'46',c:'8',v:'3',texto:"Pero si alguno ama a Dios, es conocido por él." },
{name:'4684',l:'46',c:'8',v:'4',texto:"Acerca, pues, de las viandas que se sacrifican a los ídolos, sabemos que un ídolo nada es en el mundo, y que no hay más que un Dios." },
{name:'4685',l:'46',c:'8',v:'5',texto:"Pues aunque haya algunos que se llamen dioses, sea en el cielo, o en la tierra (como hay muchos dioses y muchos señores), " },
{name:'4686',l:'46',c:'8',v:'6',texto:"para nosotros, sin embargo, sólo hay un Dios, el Padre, del cual proceden todas las cosas, y nosotros somos para él; y un Señor, Jesucristo, por medio del cual son todas las cosas, y nosotros por medio de él." },
{name:'4687',l:'46',c:'8',v:'7',texto:"Pero no en todos hay este conocimiento; porque algunos, habituados hasta aquí a los ídolos, comen como sacrificado a ídolos, y su conciencia, siendo débil, se contamina." },
{name:'4688',l:'46',c:'8',v:'8',texto:"Si bien la vianda no nos hace más aceptos ante Dios; pues ni porque comamos, seremos más, ni porque no comamos, seremos menos." },
{name:'4689',l:'46',c:'8',v:'9',texto:"Pero mirad que esta libertad vuestra no venga a ser tropezadero para los débiles." },
{name:'46810',l:'46',c:'8',v:'10',texto:"Porque si alguno te ve a ti, que tienes conocimiento, sentado a la mesa en un lugar de ídolos, la conciencia de aquel que es débil, ¿no será estimulada a comer de lo sacrificado a los ídolos? " },
{name:'46811',l:'46',c:'8',v:'11',texto:"Y por el conocimiento tuyo, se perderá el hermano débil por quien Cristo murió." },
{name:'46812',l:'46',c:'8',v:'12',texto:"De esta manera, pues, pecando contra los hermanos e hiriendo su débil conciencia, contra Cristo pecáis." },
{name:'46813',l:'46',c:'8',v:'13',texto:"Por lo cual, si la comida le es a mi hermano ocasión de caer, no comeré carne jamás, para no poner tropiezo a mi hermano." },
],
numVersiculos: 13,
},

c9: {
versiculos:[
{name:'4691',l:'46',c:'9',v:'1',texto:"¿No soy apóstol? ¿No soy libre? ¿No he visto a Jesús el Señor nuestro? ¿No sois vosotros mi obra en el Señor? " },
{name:'4692',l:'46',c:'9',v:'2',texto:"Si para otros no soy apóstol, para vosotros ciertamente lo soy; porque el sello de mi apostolado sois vosotros en el Señor." },
{name:'4693',l:'46',c:'9',v:'3',texto:"Contra los que me acusan, esta es mi defensa: " },
{name:'4694',l:'46',c:'9',v:'4',texto:"¿Acaso no tenemos derecho de comer y beber? " },
{name:'4695',l:'46',c:'9',v:'5',texto:"¿No tenemos derecho de traer con nosotros una hermana por mujer como también los otros apóstoles, y los hermanos del Señor, y Cefas? " },
{name:'4696',l:'46',c:'9',v:'6',texto:"¿O sólo yo y Bernabé no tenemos derecho de no trabajar? " },
{name:'4697',l:'46',c:'9',v:'7',texto:"¿Quién fue jamás soldado a sus propias expensas? ¿Quién planta viña y no come de su fruto? ¿O quién apacienta el rebaño y no toma de la leche del rebaño? " },
{name:'4698',l:'46',c:'9',v:'8',texto:"¿Digo esto sólo como hombre? ¿No dice esto también la ley? " },
{name:'4699',l:'46',c:'9',v:'9',texto:"Porque en la ley de Moisés está escrito: No pondrás bozal al buey que trilla. ¿Tiene Dios cuidado de los bueyes," },
{name:'46910',l:'46',c:'9',v:'10',texto:"o lo dice enteramente por nosotros? Pues por nosotros se escribió; porque con esperanza debe arar el que ara, y el que trilla, con esperanza de recibir del fruto." },
{name:'46911',l:'46',c:'9',v:'11',texto:"Si nosotros sembramos entre vosotros lo espiritual, ¿es gran cosa si segáremos de vosotros lo material? " },
{name:'46912',l:'46',c:'9',v:'12',texto:"Si otros participan de este derecho sobre vosotros, ¿cuánto más nosotros? Pero no hemos usado de este derecho, sino que lo soportamos todo, por no poner ningún obstáculo al evangelio de Cristo." },
{name:'46913',l:'46',c:'9',v:'13',texto:"¿No sabéis que los que trabajan en las cosas sagradas, comen del templo, y que los que sirven al altar, del altar participan? " },
{name:'46914',l:'46',c:'9',v:'14',texto:"Así también ordenó el Señor a los que anuncian el evangelio, que vivan del evangelio." },
{name:'46915',l:'46',c:'9',v:'15',texto:"Pero yo de nada de esto me he aprovechado, ni tampoco he escrito esto para que se haga así conmigo; porque prefiero morir, antes que nadie desvanezca esta mi gloria." },
{name:'46916',l:'46',c:'9',v:'16',texto:"Pues si anuncio el evangelio, no tengo por qué gloriarme; porque me es impuesta necesidad; y ¡ay de mí si no anunciare el evangelio! " },
{name:'46917',l:'46',c:'9',v:'17',texto:"Por lo cual, si lo hago de buena voluntad, recompensa tendré; pero si de mala voluntad, la comisión me ha sido encomendada." },
{name:'46918',l:'46',c:'9',v:'18',texto:"¿Cuál, pues, es mi galardón? Que predicando el evangelio, presente gratuitamente el evangelio de Cristo, para no abusar de mi derecho en el evangelio." },
{name:'46919',l:'46',c:'9',v:'19',texto:"Por lo cual, siendo libre de todos, me he hecho siervo de todos para ganar a mayor número." },
{name:'46920',l:'46',c:'9',v:'20',texto:"Me he hecho a los judíos como judío, para ganar a los judíos; a los que están sujetos a la ley (aunque yo no esté sujeto a la ley) como sujeto a la ley, para ganar a los que están sujetos a la ley; " },
{name:'46921',l:'46',c:'9',v:'21',texto:"a los que están sin ley, como si yo estuviera sin ley (no estando yo sin ley de Dios, sino bajo la ley de Cristo), para ganar a los que están sin ley." },
{name:'46922',l:'46',c:'9',v:'22',texto:"Me he hecho débil a los débiles, para ganar a los débiles; a todos me he hecho de todo, para que de todos modos salve a algunos." },
{name:'46923',l:'46',c:'9',v:'23',texto:"Y esto hago por causa del evangelio, para hacerme copartícipe de él." },
{name:'46924',l:'46',c:'9',v:'24',texto:"¿No sabéis que los que corren en el estadio, todos a la verdad corren, pero uno solo se lleva el premio? Corred de tal manera que lo obtengáis." },
{name:'46925',l:'46',c:'9',v:'25',texto:"Todo aquel que lucha, de todo se abstiene; ellos, a la verdad, para recibir una corona corruptible, pero nosotros, una incorruptible." },
{name:'46926',l:'46',c:'9',v:'26',texto:"Así que, yo de esta manera corro, no como a la ventura; de esta manera peleo, no como quien golpea el aire," },
{name:'46927',l:'46',c:'9',v:'27',texto:"sino que golpeo mi cuerpo, y lo pongo en servidumbre, no sea que habiendo sido heraldo para otros, yo mismo venga a ser eliminado." },
],
numVersiculos: 27,
},

c10: {
versiculos:[
{name:'46101',l:'46',c:'10',v:'1',texto:"Porque no quiero, hermanos, que ignoréis que nuestros padres todos estuvieron bajo la nube, y todos pasaron el mar; " },
{name:'46102',l:'46',c:'10',v:'2',texto:"y todos en Moisés fueron bautizados en la nube y en el mar," },
{name:'46103',l:'46',c:'10',v:'3',texto:"y todos comieron el mismo alimento espiritual," },
{name:'46104',l:'46',c:'10',v:'4',texto:"y todos bebieron la misma bebida espiritual; porque bebían de la roca espiritual que los seguía, y la roca era Cristo." },
{name:'46105',l:'46',c:'10',v:'5',texto:"Pero de los más de ellos no se agradó Dios; por lo cual quedaron postrados en el desierto." },
{name:'46106',l:'46',c:'10',v:'6',texto:"Mas estas cosas sucedieron como ejemplos para nosotros, para que no codiciemos cosas malas, como ellos codiciaron." },
{name:'46107',l:'46',c:'10',v:'7',texto:"Ni seáis idólatras, como algunos de ellos, según está escrito: Se sentó el pueblo a comer y a beber, y se levantó a jugar." },
{name:'46108',l:'46',c:'10',v:'8',texto:"Ni forniquemos, como algunos de ellos fornicaron, y cayeron en un día veintitrés mil." },
{name:'46109',l:'46',c:'10',v:'9',texto:"Ni tentemos al Señor, como también algunos de ellos le tentaron, y perecieron por las serpientes." },
{name:'461010',l:'46',c:'10',v:'10',texto:"Ni murmuréis, como algunos de ellos murmuraron, y perecieron por el destructor." },
{name:'461011',l:'46',c:'10',v:'11',texto:"Y estas cosas les acontecieron como ejemplo, y están escritas para amonestarnos a nosotros, a quienes han alcanzado los fines de los siglos." },
{name:'461012',l:'46',c:'10',v:'12',texto:"Así que, el que piensa estar firme, mire que no caiga." },
{name:'461013',l:'46',c:'10',v:'13',texto:"No os ha sobrevenido ninguna tentación que no sea humana; pero fiel es Dios, que no os dejará ser tentados más de lo que podéis resistir, sino que dará también juntamente con la tentación la salida, para que podáis soportar." },
{name:'461014',l:'46',c:'10',v:'14',texto:"Por tanto, amados míos, huid de la idolatría." },
{name:'461015',l:'46',c:'10',v:'15',texto:"Como a sensatos os hablo; juzgad vosotros lo que digo." },
{name:'461016',l:'46',c:'10',v:'16',texto:"La copa de bendición que bendecimos, ¿no es la comunión de la sangre de Cristo? El pan que partimos, ¿no es la comunión del cuerpo de Cristo? " },
{name:'461017',l:'46',c:'10',v:'17',texto:"Siendo uno solo el pan, nosotros, con ser muchos, somos un cuerpo; pues todos participamos de aquel mismo pan." },
{name:'461018',l:'46',c:'10',v:'18',texto:"Mirad a Israel según la carne; los que comen de los sacrificios, ¿no son partícipes del altar? " },
{name:'461019',l:'46',c:'10',v:'19',texto:"¿Qué digo, pues? ¿Que el ídolo es algo, o que sea algo lo que se sacrifica a los ídolos? " },
{name:'461020',l:'46',c:'10',v:'20',texto:"Antes digo que lo que los gentiles sacrifican, a los demonios lo sacrifican, y no a Dios; y no quiero que vosotros os hagáis partícipes con los demonios." },
{name:'461021',l:'46',c:'10',v:'21',texto:"No podéis beber la copa del Señor, y la copa de los demonios; no podéis participar de la mesa del Señor, y de la mesa de los demonios." },
{name:'461022',l:'46',c:'10',v:'22',texto:"¿O provocaremos a celos al Señor? ¿Somos más fuertes que él? " },
{name:'461023',l:'46',c:'10',v:'23',texto:"Todo me es lícito, pero no todo conviene; todo me es lícito, pero no todo edifica." },
{name:'461024',l:'46',c:'10',v:'24',texto:"Ninguno busque su propio bien, sino el del otro." },
{name:'461025',l:'46',c:'10',v:'25',texto:"De todo lo que se vende en la carnicería, comed, sin preguntar nada por motivos de conciencia; " },
{name:'461026',l:'46',c:'10',v:'26',texto:"porque del Señor es la tierra y su plenitud." },
{name:'461027',l:'46',c:'10',v:'27',texto:"Si algún incrédulo os invita, y queréis ir, de todo lo que se os ponga delante comed, sin preguntar nada por motivos de conciencia." },
{name:'461028',l:'46',c:'10',v:'28',texto:"Mas si alguien os dijere: Esto fue sacrificado a los ídolos; no lo comáis, por causa de aquel que lo declaró, y por motivos de conciencia; porque del Señor es la tierra y su plenitud." },
{name:'461029',l:'46',c:'10',v:'29',texto:"La conciencia, digo, no la tuya, sino la del otro. Pues ¿por qué se ha de juzgar mi libertad por la conciencia de otro? " },
{name:'461030',l:'46',c:'10',v:'30',texto:"Y si yo con agradecimiento participo, ¿por qué he de ser censurado por aquello de que doy gracias? " },
{name:'461031',l:'46',c:'10',v:'31',texto:"Si, pues, coméis o bebéis, o hacéis otra cosa, hacedlo todo para la gloria de Dios." },
{name:'461032',l:'46',c:'10',v:'32',texto:"No seáis tropiezo ni a judíos, ni a gentiles, ni a la iglesia de Dios; " },
{name:'461033',l:'46',c:'10',v:'33',texto:"como también yo en todas las cosas agrado a todos, no procurando mi propio beneficio, sino el de muchos, para que sean salvos." },
],
numVersiculos: 33,
},

c11: {
versiculos:[
{name:'46111',l:'46',c:'11',v:'1',texto:"Sed imitadores de mí, así como yo de Cristo." },
{name:'46112',l:'46',c:'11',v:'2',texto:"Os alabo, hermanos, porque en todo os acordáis de mí, y retenéis las instrucciones tal como os las entregué." },
{name:'46113',l:'46',c:'11',v:'3',texto:"Pero quiero que sepáis que Cristo es la cabeza de todo varón, y el varón es la cabeza de la mujer, y Dios la cabeza de Cristo." },
{name:'46114',l:'46',c:'11',v:'4',texto:"Todo varón que ora o profetiza con la cabeza cubierta, afrenta su cabeza." },
{name:'46115',l:'46',c:'11',v:'5',texto:"Pero toda mujer que ora o profetiza con la cabeza descubierta, afrenta su cabeza; porque lo mismo es que si se hubiese rapado." },
{name:'46116',l:'46',c:'11',v:'6',texto:"Porque si la mujer no se cubre, que se corte también el cabello; y si le es vergonzoso a la mujer cortarse el cabello o raparse, que se cubra." },
{name:'46117',l:'46',c:'11',v:'7',texto:"Porque el varón no debe cubrirse la cabeza, pues él es imagen y gloria de Dios; pero la mujer es gloria del varón." },
{name:'46118',l:'46',c:'11',v:'8',texto:"Porque el varón no procede de la mujer, sino la mujer del varón," },
{name:'46119',l:'46',c:'11',v:'9',texto:"y tampoco el varón fue creado por causa de la mujer, sino la mujer por causa del varón." },
{name:'461110',l:'46',c:'11',v:'10',texto:"Por lo cual la mujer debe tener señal de autoridad sobre su cabeza, por causa de los ángeles." },
{name:'461111',l:'46',c:'11',v:'11',texto:"Pero en el Señor, ni el varón es sin la mujer, ni la mujer sin el varón; " },
{name:'461112',l:'46',c:'11',v:'12',texto:"porque así como la mujer procede del varón, también el varón nace de la mujer; pero todo procede de Dios." },
{name:'461113',l:'46',c:'11',v:'13',texto:"Juzgad vosotros mismos: ¿Es propio que la mujer ore a Dios sin cubrirse la cabeza? " },
{name:'461114',l:'46',c:'11',v:'14',texto:"La naturaleza misma ¿no os enseña que al varón le es deshonroso dejarse crecer el cabello? " },
{name:'461115',l:'46',c:'11',v:'15',texto:"Por el contrario, a la mujer dejarse crecer el cabello le es honroso; porque en lugar de velo le es dado el cabello." },
{name:'461116',l:'46',c:'11',v:'16',texto:"Con todo eso, si alguno quiere ser contencioso, nosotros no tenemos tal costumbre, ni las iglesias de Dios." },
{name:'461117',l:'46',c:'11',v:'17',texto:"Pero al anunciaros esto que sigue, no os alabo; porque no os congregáis para lo mejor, sino para lo peor." },
{name:'461118',l:'46',c:'11',v:'18',texto:"Pues en primer lugar, cuando os reunís como iglesia, oigo que hay entre vosotros divisiones; y en parte lo creo." },
{name:'461119',l:'46',c:'11',v:'19',texto:"Porque es preciso que entre vosotros haya disensiones, para que se hagan manifiestos entre vosotros los que son aprobados." },
{name:'461120',l:'46',c:'11',v:'20',texto:"Cuando, pues, os reunís vosotros, esto no es comer la cena del Señor." },
{name:'461121',l:'46',c:'11',v:'21',texto:"Porque al comer, cada uno se adelanta a tomar su propia cena; y uno tiene hambre, y otro se embriaga." },
{name:'461122',l:'46',c:'11',v:'22',texto:"Pues qué, ¿no tenéis casas en que comáis y bebáis? ¿O menospreciáis la iglesia de Dios, y avergonzáis a los que no tienen nada? ¿Qué os diré? ¿Os alabaré? En esto no os alabo." },
{name:'461123',l:'46',c:'11',v:'23',texto:"Porque yo recibí del Señor lo que también os he enseñado: Que el Señor Jesús, la noche que fue entregado, tomó pan; " },
{name:'461124',l:'46',c:'11',v:'24',texto:"y habiendo dado gracias, lo partió, y dijo: Tomad, comed; esto es mi cuerpo que por vosotros es partido; haced esto en memoria de mí." },
{name:'461125',l:'46',c:'11',v:'25',texto:"Asimismo tomó también la copa, después de haber cenado, diciendo: Esta copa es el nuevo pacto en mi sangre; haced esto todas las veces que la bebiereis, en memoria de mí." },
{name:'461126',l:'46',c:'11',v:'26',texto:"Así, pues, todas las veces que comiereis este pan, y bebiereis esta copa, la muerte del Señor anunciáis hasta que él venga." },
{name:'461127',l:'46',c:'11',v:'27',texto:"De manera que cualquiera que comiere este pan o bebiere esta copa del Señor indignamente, será culpado del cuerpo y de la sangre del Señor." },
{name:'461128',l:'46',c:'11',v:'28',texto:"Por tanto, pruébese cada uno a sí mismo, y coma así del pan, y beba de la copa." },
{name:'461129',l:'46',c:'11',v:'29',texto:"Porque el que come y bebe indignamente, sin discernir el cuerpo del Señor, juicio come y bebe para sí." },
{name:'461130',l:'46',c:'11',v:'30',texto:"Por lo cual hay muchos enfermos y debilitados entre vosotros, y muchos duermen." },
{name:'461131',l:'46',c:'11',v:'31',texto:"Si, pues, nos examinásemos a nosotros mismos, no seríamos juzgados; " },
{name:'461132',l:'46',c:'11',v:'32',texto:"mas siendo juzgados, somos castigados por el Señor, para que no seamos condenados con el mundo." },
{name:'461133',l:'46',c:'11',v:'33',texto:"Así que, hermanos míos, cuando os reunís a comer, esperaos unos a otros." },
{name:'461134',l:'46',c:'11',v:'34',texto:"Si alguno tuviere hambre, coma en su casa, para que no os reunáis para juicio. Las demás cosas las pondré en orden cuando yo fuere." },
],
numVersiculos: 34,
},

c12: {
versiculos:[
{name:'46121',l:'46',c:'12',v:'1',texto:"No quiero, hermanos, que ignoréis acerca de los dones espirituales." },
{name:'46122',l:'46',c:'12',v:'2',texto:"Sabéis que cuando erais gentiles, se os extraviaba llevándoos, como se os llevaba, a los ídolos mudos." },
{name:'46123',l:'46',c:'12',v:'3',texto:"Por tanto, os hago saber que nadie que hable por el Espíritu de Dios llama anatema a Jesús; y nadie puede llamar a Jesús Señor, sino por el Espíritu Santo." },
{name:'46124',l:'46',c:'12',v:'4',texto:"Ahora bien, hay diversidad de dones, pero el Espíritu es el mismo." },
{name:'46125',l:'46',c:'12',v:'5',texto:"Y hay diversidad de ministerios, pero el Señor es el mismo." },
{name:'46126',l:'46',c:'12',v:'6',texto:"Y hay diversidad de operaciones, pero Dios, que hace todas las cosas en todos, es el mismo." },
{name:'46127',l:'46',c:'12',v:'7',texto:"Pero a cada uno le es dada la manifestación del Espíritu para provecho." },
{name:'46128',l:'46',c:'12',v:'8',texto:"Porque a éste es dada por el Espíritu palabra de sabiduría; a otro, palabra de ciencia según el mismo Espíritu; " },
{name:'46129',l:'46',c:'12',v:'9',texto:"a otro, fe por el mismo Espíritu; y a otro, dones de sanidades por el mismo Espíritu." },
{name:'461210',l:'46',c:'12',v:'10',texto:"A otro, el hacer milagros; a otro, profecía; a otro, discernimiento de espíritus; a otro, diversos géneros de lenguas; y a otro, interpretación de lenguas." },
{name:'461211',l:'46',c:'12',v:'11',texto:"Pero todas estas cosas las hace uno y el mismo Espíritu, repartiendo a cada uno en particular como él quiere." },
{name:'461212',l:'46',c:'12',v:'12',texto:"Porque así como el cuerpo es uno, y tiene muchos miembros, pero todos los miembros del cuerpo, siendo muchos, son un solo cuerpo, así también Cristo." },
{name:'461213',l:'46',c:'12',v:'13',texto:"Porque por un solo Espíritu fuimos todos bautizados en un cuerpo, sean judíos o griegos, sean esclavos o libres; y a todos se nos dio a beber de un mismo Espíritu." },
{name:'461214',l:'46',c:'12',v:'14',texto:"Además, el cuerpo no es un solo miembro, sino muchos." },
{name:'461215',l:'46',c:'12',v:'15',texto:"Si dijere el pie: Porque no soy mano, no soy del cuerpo, ¿por eso no será del cuerpo? " },
{name:'461216',l:'46',c:'12',v:'16',texto:"Y si dijere la oreja: Porque no soy ojo, no soy del cuerpo, ¿por eso no será del cuerpo? " },
{name:'461217',l:'46',c:'12',v:'17',texto:"Si todo el cuerpo fuese ojo, ¿dónde estaría el oído? Si todo fuese oído, ¿dónde estaría el olfato? " },
{name:'461218',l:'46',c:'12',v:'18',texto:"Mas ahora Dios ha colocado los miembros cada uno de ellos en el cuerpo, como él quiso." },
{name:'461219',l:'46',c:'12',v:'19',texto:"Porque si todos fueran un solo miembro, ¿dónde estaría el cuerpo? " },
{name:'461220',l:'46',c:'12',v:'20',texto:"Pero ahora son muchos los miembros, pero el cuerpo es uno solo." },
{name:'461221',l:'46',c:'12',v:'21',texto:"Ni el ojo puede decir a la mano: No te necesito, ni tampoco la cabeza a los pies: No tengo necesidad de vosotros." },
{name:'461222',l:'46',c:'12',v:'22',texto:"Antes bien los miembros del cuerpo que parecen más débiles, son los más necesarios; " },
{name:'461223',l:'46',c:'12',v:'23',texto:"y a aquellos del cuerpo que nos parecen menos dignos, a éstos vestimos más dignamente; y los que en nosotros son menos decorosos, se tratan con más decoro." },
{name:'461224',l:'46',c:'12',v:'24',texto:"Porque los que en nosotros son más decorosos, no tienen necesidad; pero Dios ordenó el cuerpo, dando más abundante honor al que le faltaba," },
{name:'461225',l:'46',c:'12',v:'25',texto:"para que no haya desavenencia en el cuerpo, sino que los miembros todos se preocupen los unos por los otros." },
{name:'461226',l:'46',c:'12',v:'26',texto:"De manera que si un miembro padece, todos los miembros se duelen con él, y si un miembro recibe honra, todos los miembros con él se gozan." },
{name:'461227',l:'46',c:'12',v:'27',texto:"Vosotros, pues, sois el cuerpo de Cristo, y miembros cada uno en particular." },
{name:'461228',l:'46',c:'12',v:'28',texto:"Y a unos puso Dios en la iglesia, primeramente apóstoles, luego profetas, lo tercero maestros, luego los que hacen milagros, después los que sanan, los que ayudan, los que administran, los que tienen don de lenguas." },
{name:'461229',l:'46',c:'12',v:'29',texto:"¿Son todos apóstoles? ¿son todos profetas? ¿todos maestros? ¿hacen todos milagros? " },
{name:'461230',l:'46',c:'12',v:'30',texto:"¿Tienen todos dones de sanidad? ¿hablan todos lenguas? ¿interpretan todos? " },
{name:'461231',l:'46',c:'12',v:'31',texto:"Procurad, pues, los dones mejores. Mas yo os muestro un camino aun más excelente." },
],
numVersiculos: 31,
},

c13: {
versiculos:[
{name:'46131',l:'46',c:'13',v:'1',texto:"Si yo hablase lenguas humanas y angélicas, y no tengo amor, vengo a ser como metal que resuena, o címbalo que retiñe." },
{name:'46132',l:'46',c:'13',v:'2',texto:"Y si tuviese profecía, y entendiese todos los misterios y toda ciencia, y si tuviese toda la fe, de tal manera que trasladase los montes, y no tengo amor, nada soy." },
{name:'46133',l:'46',c:'13',v:'3',texto:"Y si repartiese todos mis bienes para dar de comer a los pobres, y si entregase mi cuerpo para ser quemado, y no tengo amor, de nada me sirve." },
{name:'46134',l:'46',c:'13',v:'4',texto:"El amor es sufrido, es benigno; el amor no tiene envidia, el amor no es jactancioso, no se envanece; " },
{name:'46135',l:'46',c:'13',v:'5',texto:"no hace nada indebido, no busca lo suyo, no se irrita, no guarda rencor; " },
{name:'46136',l:'46',c:'13',v:'6',texto:"no se goza de la injusticia, mas se goza de la verdad." },
{name:'46137',l:'46',c:'13',v:'7',texto:"Todo lo sufre, todo lo cree, todo lo espera, todo lo soporta." },
{name:'46138',l:'46',c:'13',v:'8',texto:"El amor nunca deja de ser; pero las profecías se acabarán, y cesarán las lenguas, y la ciencia acabará." },
{name:'46139',l:'46',c:'13',v:'9',texto:"Porque en parte conocemos, y en parte profetizamos; " },
{name:'461310',l:'46',c:'13',v:'10',texto:"mas cuando venga lo perfecto, entonces lo que es en parte se acabará." },
{name:'461311',l:'46',c:'13',v:'11',texto:"Cuando yo era niño, hablaba como niño, pensaba como niño, juzgaba como niño; mas cuando ya fui hombre, dejé lo que era de niño." },
{name:'461312',l:'46',c:'13',v:'12',texto:"Ahora vemos por espejo, oscuramente; mas entonces veremos cara a cara. Ahora conozco en parte; pero entonces conoceré como fui conocido." },
{name:'461313',l:'46',c:'13',v:'13',texto:"Y ahora permanecen la fe, la esperanza y el amor, estos tres; pero el mayor de ellos es el amor." },
],
numVersiculos: 13,
},

c14: {
versiculos:[
{name:'46141',l:'46',c:'14',v:'1',texto:"Seguid el amor; y procurad los dones espirituales, pero sobre todo que profeticéis." },
{name:'46142',l:'46',c:'14',v:'2',texto:"Porque el que habla en lenguas no habla a los hombres, sino a Dios; pues nadie le entiende, aunque por el Espíritu habla misterios." },
{name:'46143',l:'46',c:'14',v:'3',texto:"Pero el que profetiza habla a los hombres para edificación, exhortación y consolación." },
{name:'46144',l:'46',c:'14',v:'4',texto:"El que habla en lengua extraña, a sí mismo se edifica; pero el que profetiza, edifica a la iglesia." },
{name:'46145',l:'46',c:'14',v:'5',texto:"Así que, quisiera que todos vosotros hablaseis en lenguas, pero más que profetizaseis; porque mayor es el que profetiza que el que habla en lenguas, a no ser que las interprete para que la iglesia reciba edificación." },
{name:'46146',l:'46',c:'14',v:'6',texto:"Ahora pues, hermanos, si yo voy a vosotros hablando en lenguas, ¿qué os aprovechará, si no os hablare con revelación, o con ciencia, o con profecía, o con doctrina? " },
{name:'46147',l:'46',c:'14',v:'7',texto:"Ciertamente las cosas inanimadas que producen sonidos, como la flauta o la cítara, si no dieren distinción de voces, ¿cómo se sabrá lo que se toca con la flauta o con la cítara? " },
{name:'46148',l:'46',c:'14',v:'8',texto:"Y si la trompeta diere sonido incierto, ¿quién se preparará para la batalla? " },
{name:'46149',l:'46',c:'14',v:'9',texto:"Así también vosotros, si por la lengua no diereis palabra bien comprensible, ¿cómo se entenderá lo que decís? Porque hablaréis al aire." },
{name:'461410',l:'46',c:'14',v:'10',texto:"Tantas clases de idiomas hay, seguramente, en el mundo, y ninguno de ellos carece de significado." },
{name:'461411',l:'46',c:'14',v:'11',texto:"Pero si yo ignoro el valor de las palabras, seré como extranjero para el que habla, y el que habla será como extranjero para mí." },
{name:'461412',l:'46',c:'14',v:'12',texto:"Así también vosotros; pues que anheláis dones espirituales, procurad abundar en ellos para edificación de la iglesia." },
{name:'461413',l:'46',c:'14',v:'13',texto:"Por lo cual, el que habla en lengua extraña, pida en oración poder interpretarla." },
{name:'461414',l:'46',c:'14',v:'14',texto:"Porque si yo oro en lengua desconocida, mi espíritu ora, pero mi entendimiento queda sin fruto." },
{name:'461415',l:'46',c:'14',v:'15',texto:"¿Qué, pues? Oraré con el espíritu, pero oraré también con el entendimiento; cantaré con el espíritu, pero cantaré también con el entendimiento." },
{name:'461416',l:'46',c:'14',v:'16',texto:"Porque si bendices sólo con el espíritu, el que ocupa lugar de simple oyente, ¿cómo dirá el Amén a tu acción de gracias? pues no sabe lo que has dicho." },
{name:'461417',l:'46',c:'14',v:'17',texto:"Porque tú, a la verdad, bien das gracias; pero el otro no es edificado." },
{name:'461418',l:'46',c:'14',v:'18',texto:"Doy gracias a Dios que hablo en lenguas más que todos vosotros; " },
{name:'461419',l:'46',c:'14',v:'19',texto:"pero en la iglesia prefiero hablar cinco palabras con mi entendimiento, para enseñar también a otros, que diez mil palabras en lengua desconocida." },
{name:'461420',l:'46',c:'14',v:'20',texto:"Hermanos, no seáis niños en el modo de pensar, sino sed niños en la malicia, pero maduros en el modo de pensar." },
{name:'461421',l:'46',c:'14',v:'21',texto:"En la ley está escrito: En otras lenguas y con otros labios hablaré a este pueblo; y ni aun así me oirán, dice el Señor." },
{name:'461422',l:'46',c:'14',v:'22',texto:"Así que, las lenguas son por señal, no a los creyentes, sino a los incrédulos; pero la profecía, no a los incrédulos, sino a los creyentes." },
{name:'461423',l:'46',c:'14',v:'23',texto:"Si, pues, toda la iglesia se reúne en un solo lugar, y todos hablan en lenguas, y entran indoctos o incrédulos, ¿no dirán que estáis locos? " },
{name:'461424',l:'46',c:'14',v:'24',texto:"Pero si todos profetizan, y entra algún incrédulo o indocto, por todos es convencido, por todos es juzgado; " },
{name:'461425',l:'46',c:'14',v:'25',texto:"lo oculto de su corazón se hace manifiesto; y así, postrándose sobre el rostro, adorará a Dios, declarando que verdaderamente Dios está entre vosotros." },
{name:'461426',l:'46',c:'14',v:'26',texto:"¿Qué hay, pues, hermanos? Cuando os reunís, cada uno de vosotros tiene salmo, tiene doctrina, tiene lengua, tiene revelación, tiene interpretación. Hágase todo para edificación." },
{name:'461427',l:'46',c:'14',v:'27',texto:"Si habla alguno en lengua extraña, sea esto por dos, o a lo más tres, y por turno; y uno interprete." },
{name:'461428',l:'46',c:'14',v:'28',texto:"Y si no hay intérprete, calle en la iglesia, y hable para sí mismo y para Dios." },
{name:'461429',l:'46',c:'14',v:'29',texto:"Asimismo, los profetas hablen dos o tres, y los demás juzguen." },
{name:'461430',l:'46',c:'14',v:'30',texto:"Y si algo le fuere revelado a otro que estuviere sentado, calle el primero." },
{name:'461431',l:'46',c:'14',v:'31',texto:"Porque podéis profetizar todos uno por uno, para que todos aprendan, y todos sean exhortados." },
{name:'461432',l:'46',c:'14',v:'32',texto:"Y los espíritus de los profetas están sujetos a los profetas; " },
{name:'461433',l:'46',c:'14',v:'33',texto:"pues Dios no es Dios de confusión, sino de paz. Como en todas las iglesias de los santos," },
{name:'461434',l:'46',c:'14',v:'34',texto:"vuestras mujeres callen en las congregaciones; porque no les es permitido hablar, sino que estén sujetas, como también la ley lo dice." },
{name:'461435',l:'46',c:'14',v:'35',texto:"Y si quieren aprender algo, pregunten en casa a sus maridos; porque es indecoroso que una mujer hable en la congregación." },
{name:'461436',l:'46',c:'14',v:'36',texto:"¿Acaso ha salido de vosotros la palabra de Dios, o sólo a vosotros ha llegado? " },
{name:'461437',l:'46',c:'14',v:'37',texto:"Si alguno se cree profeta, o espiritual, reconozca que lo que os escribo son mandamientos del Señor." },
{name:'461438',l:'46',c:'14',v:'38',texto:"Mas el que ignora, ignore." },
{name:'461439',l:'46',c:'14',v:'39',texto:"Así que, hermanos, procurad profetizar, y no impidáis el hablar lenguas; " },
{name:'461440',l:'46',c:'14',v:'40',texto:"pero hágase todo decentemente y con orden." },
],
numVersiculos: 40,
},

c15: {
versiculos:[
{name:'46151',l:'46',c:'15',v:'1',texto:"Además os declaro, hermanos, el evangelio que os he predicado, el cual también recibisteis, en el cual también perseveráis; " },
{name:'46152',l:'46',c:'15',v:'2',texto:"por el cual asimismo, si retenéis la palabra que os he predicado, sois salvos, si no creísteis en vano." },
{name:'46153',l:'46',c:'15',v:'3',texto:"Porque primeramente os he enseñado lo que asimismo recibí: Que Cristo murió por nuestros pecados, conforme a las Escrituras; " },
{name:'46154',l:'46',c:'15',v:'4',texto:"y que fue sepultado, y que resucitó al tercer día, conforme a las Escrituras; " },
{name:'46155',l:'46',c:'15',v:'5',texto:"y que apareció a Cefas, y después a los doce." },
{name:'46156',l:'46',c:'15',v:'6',texto:"Después apareció a más de quinientos hermanos a la vez, de los cuales muchos viven aún, y otros ya duermen." },
{name:'46157',l:'46',c:'15',v:'7',texto:"Después apareció a Jacobo; después a todos los apóstoles; " },
{name:'46158',l:'46',c:'15',v:'8',texto:"y al último de todos, como a un abortivo, me apareció a mí." },
{name:'46159',l:'46',c:'15',v:'9',texto:"Porque yo soy el más pequeño de los apóstoles, que no soy digno de ser llamado apóstol, porque perseguí a la iglesia de Dios." },
{name:'461510',l:'46',c:'15',v:'10',texto:"Pero por la gracia de Dios soy lo que soy; y su gracia no ha sido en vano para conmigo, antes he trabajado más que todos ellos; pero no yo, sino la gracia de Dios conmigo." },
{name:'461511',l:'46',c:'15',v:'11',texto:"Porque o sea yo o sean ellos, así predicamos, y así habéis creído." },
{name:'461512',l:'46',c:'15',v:'12',texto:"Pero si se predica de Cristo que resucitó de los muertos, ¿cómo dicen algunos entre vosotros que no hay resurrección de muertos? " },
{name:'461513',l:'46',c:'15',v:'13',texto:"Porque si no hay resurrección de muertos, tampoco Cristo resucitó." },
{name:'461514',l:'46',c:'15',v:'14',texto:"Y si Cristo no resucitó, vana es entonces nuestra predicación, vana es también vuestra fe." },
{name:'461515',l:'46',c:'15',v:'15',texto:"Y somos hallados falsos testigos de Dios; porque hemos testificado de Dios que él resucitó a Cristo, al cual no resucitó, si en verdad los muertos no resucitan." },
{name:'461516',l:'46',c:'15',v:'16',texto:"Porque si los muertos no resucitan, tampoco Cristo resucitó; " },
{name:'461517',l:'46',c:'15',v:'17',texto:"y si Cristo no resucitó, vuestra fe es vana; aún estáis en vuestros pecados." },
{name:'461518',l:'46',c:'15',v:'18',texto:"Entonces también los que durmieron en Cristo perecieron." },
{name:'461519',l:'46',c:'15',v:'19',texto:"Si en esta vida solamente esperamos en Cristo, somos los más dignos de conmiseración de todos los hombres." },
{name:'461520',l:'46',c:'15',v:'20',texto:"Mas ahora Cristo ha resucitado de los muertos; primicias de los que durmieron es hecho." },
{name:'461521',l:'46',c:'15',v:'21',texto:"Porque por cuanto la muerte entró por un hombre, también por un hombre la resurrección de los muertos." },
{name:'461522',l:'46',c:'15',v:'22',texto:"Porque así como en Adán todos mueren, también en Cristo todos serán vivificados." },
{name:'461523',l:'46',c:'15',v:'23',texto:"Pero cada uno en su debido orden: Cristo, las primicias; luego los que son de Cristo, en su venida." },
{name:'461524',l:'46',c:'15',v:'24',texto:"Luego el fin, cuando entregue el reino al Dios y Padre, cuando haya suprimido todo dominio, toda autoridad y potencia." },
{name:'461525',l:'46',c:'15',v:'25',texto:"Porque preciso es que él reine hasta que haya puesto a todos sus enemigos debajo de sus pies." },
{name:'461526',l:'46',c:'15',v:'26',texto:"Y el postrer enemigo que será destruido es la muerte." },
{name:'461527',l:'46',c:'15',v:'27',texto:"Porque todas las cosas las sujetó debajo de sus pies. Y cuando dice que todas las cosas han sido sujetadas a él, claramente se exceptúa aquel que sujetó a él todas las cosas." },
{name:'461528',l:'46',c:'15',v:'28',texto:"Pero luego que todas las cosas le estén sujetas, entonces también el Hijo mismo se sujetará al que le sujetó a él todas las cosas, para que Dios sea todo en todos." },
{name:'461529',l:'46',c:'15',v:'29',texto:"De otro modo, ¿qué harán los que se bautizan por los muertos, si en ninguna manera los muertos resucitan? ¿Por qué, pues, se bautizan por los muertos? " },
{name:'461530',l:'46',c:'15',v:'30',texto:"¿Y por qué nosotros peligramos a toda hora? " },
{name:'461531',l:'46',c:'15',v:'31',texto:"Os aseguro, hermanos, por la gloria que de vosotros tengo en nuestro Señor Jesucristo, que cada día muero." },
{name:'461532',l:'46',c:'15',v:'32',texto:"Si como hombre batallé en Efeso contra fieras, ¿qué me aprovecha? Si los muertos no resucitan, comamos y bebamos, porque mañana moriremos." },
{name:'461533',l:'46',c:'15',v:'33',texto:"No erréis; las malas conversaciones corrompen las buenas costumbres." },
{name:'461534',l:'46',c:'15',v:'34',texto:"Velad debidamente, y no pequéis; porque algunos no conocen a Dios; para vergüenza vuestra lo digo." },
{name:'461535',l:'46',c:'15',v:'35',texto:"Pero dirá alguno: ¿Cómo resucitarán los muertos? ¿Con qué cuerpo vendrán? " },
{name:'461536',l:'46',c:'15',v:'36',texto:"Necio, lo que tú siembras no se vivifica, si no muere antes." },
{name:'461537',l:'46',c:'15',v:'37',texto:"Y lo que siembras no es el cuerpo que ha de salir, sino el grano desnudo, ya sea de trigo o de otro grano; " },
{name:'461538',l:'46',c:'15',v:'38',texto:"pero Dios le da el cuerpo como él quiso, y a cada semilla su propio cuerpo." },
{name:'461539',l:'46',c:'15',v:'39',texto:"No toda carne es la misma carne, sino que una carne es la de los hombres, otra carne la de las bestias, otra la de los peces, y otra la de las aves." },
{name:'461540',l:'46',c:'15',v:'40',texto:"Y hay cuerpos celestiales, y cuerpos terrenales; pero una es la gloria de los celestiales, y otra la de los terrenales." },
{name:'461541',l:'46',c:'15',v:'41',texto:"Una es la gloria del sol, otra la gloria de la luna, y otra la gloria de las estrellas, pues una estrella es diferente de otra en gloria." },
{name:'461542',l:'46',c:'15',v:'42',texto:"Así también es la resurrección de los muertos. Se siembra en corrupción, resucitará en incorrupción." },
{name:'461543',l:'46',c:'15',v:'43',texto:"Se siembra en deshonra, resucitará en gloria; se siembra en debilidad, resucitará en poder." },
{name:'461544',l:'46',c:'15',v:'44',texto:"Se siembra cuerpo animal, resucitará cuerpo espiritual. Hay cuerpo animal, y hay cuerpo espiritual." },
{name:'461545',l:'46',c:'15',v:'45',texto:"Así también está escrito: Fue hecho el primer hombre Adán alma viviente; el postrer Adán, espíritu vivificante." },
{name:'461546',l:'46',c:'15',v:'46',texto:"Mas lo espiritual no es primero, sino lo animal; luego lo espiritual." },
{name:'461547',l:'46',c:'15',v:'47',texto:"El primer hombre es de la tierra, terrenal; el segundo hombre, que es el Señor, es del cielo." },
{name:'461548',l:'46',c:'15',v:'48',texto:"Cual el terrenal, tales también los terrenales; y cual el celestial, tales también los celestiales." },
{name:'461549',l:'46',c:'15',v:'49',texto:"Y así como hemos traído la imagen del terrenal, traeremos también la imagen del celestial." },
{name:'461550',l:'46',c:'15',v:'50',texto:"Pero esto digo, hermanos: que la carne y la sangre no pueden heredar el reino de Dios, ni la corrupción hereda la incorrupción." },
{name:'461551',l:'46',c:'15',v:'51',texto:"He aquí, os digo un misterio: No todos dormiremos; pero todos seremos transformados," },
{name:'461552',l:'46',c:'15',v:'52',texto:"en un momento, en un abrir y cerrar de ojos, a la final trompeta; porque se tocará la trompeta, y los muertos serán resucitados incorruptibles, y nosotros seremos transformados." },
{name:'461553',l:'46',c:'15',v:'53',texto:"Porque es necesario que esto corruptible se vista de incorrupción, y esto mortal se vista de inmortalidad." },
{name:'461554',l:'46',c:'15',v:'54',texto:"Y cuando esto corruptible se haya vestido de incorrupción, y esto mortal se haya vestido de inmortalidad, entonces se cumplirá la palabra que está escrita: Sorbida es la muerte en victoria." },
{name:'461555',l:'46',c:'15',v:'55',texto:"¿Dónde está, oh muerte, tu aguijón? ¿Dónde, oh sepulcro, tu victoria? " },
{name:'461556',l:'46',c:'15',v:'56',texto:"ya que el aguijón de la muerte es el pecado, y el poder del pecado, la ley." },
{name:'461557',l:'46',c:'15',v:'57',texto:"Mas gracias sean dadas a Dios, que nos da la victoria por medio de nuestro Señor Jesucristo." },
{name:'461558',l:'46',c:'15',v:'58',texto:"Así que, hermanos míos amados, estad firmes y constantes, creciendo en la obra del Señor siempre, sabiendo que vuestro trabajo en el Señor no es en vano." },
],
numVersiculos: 58,
},

c16: {
versiculos:[
{name:'46161',l:'46',c:'16',v:'1',texto:"En cuanto a la ofrenda para los santos, haced vosotros también de la manera que ordené en las iglesias de Galacia." },
{name:'46162',l:'46',c:'16',v:'2',texto:"Cada primer día de la semana cada uno de vosotros ponga aparte algo, según haya prosperado, guardándolo, para que cuando yo llegue no se recojan entonces ofrendas." },
{name:'46163',l:'46',c:'16',v:'3',texto:"Y cuando haya llegado, a quienes hubiereis designado por carta, a éstos enviaré para que lleven vuestro donativo a Jerusalén." },
{name:'46164',l:'46',c:'16',v:'4',texto:"Y si fuere propio que yo también vaya, irán conmigo." },
{name:'46165',l:'46',c:'16',v:'5',texto:"Iré a vosotros, cuando haya pasado por Macedonia, pues por Macedonia tengo que pasar." },
{name:'46166',l:'46',c:'16',v:'6',texto:"Y podrá ser que me quede con vosotros, o aun pase el invierno, para que vosotros me encaminéis a donde haya de ir." },
{name:'46167',l:'46',c:'16',v:'7',texto:"Porque no quiero veros ahora de paso, pues espero estar con vosotros algún tiempo, si el Señor lo permite." },
{name:'46168',l:'46',c:'16',v:'8',texto:"Pero estaré en Efeso hasta Pentecostés; " },
{name:'46169',l:'46',c:'16',v:'9',texto:"porque se me ha abierto puerta grande y eficaz, y muchos son los adversarios." },
{name:'461610',l:'46',c:'16',v:'10',texto:"Y si llega Timoteo, mirad que esté con vosotros con tranquilidad, porque él hace la obra del Señor así como yo." },
{name:'461611',l:'46',c:'16',v:'11',texto:"Por tanto, nadie le tenga en poco, sino encaminadle en paz, para que venga a mí, porque le espero con los hermanos." },
{name:'461612',l:'46',c:'16',v:'12',texto:"Acerca del hermano Apolos, mucho le rogué que fuese a vosotros con los hermanos, mas de ninguna manera tuvo voluntad de ir por ahora; pero irá cuando tenga oportunidad." },
{name:'461613',l:'46',c:'16',v:'13',texto:"Velad, estad firmes en la fe; portaos varonilmente, y esforzaos." },
{name:'461614',l:'46',c:'16',v:'14',texto:"Todas vuestras cosas sean hechas con amor." },
{name:'461615',l:'46',c:'16',v:'15',texto:"Hermanos, ya sabéis que la familia de Estéfanas es las primicias de Acaya, y que ellos se han dedicado al servicio de los santos." },
{name:'461616',l:'46',c:'16',v:'16',texto:"Os ruego que os sujetéis a personas como ellos, y a todos los que ayudan y trabajan." },
{name:'461617',l:'46',c:'16',v:'17',texto:"Me regocijo con la venida de Estéfanas, de Fortunato y de Acaico, pues ellos han suplido vuestra ausencia." },
{name:'461618',l:'46',c:'16',v:'18',texto:"Porque confortaron mi espíritu y el vuestro; reconoced, pues, a tales personas." },
{name:'461619',l:'46',c:'16',v:'19',texto:"Las iglesias de Asia os saludan. Aquila y Priscila, con la iglesia que está en su casa, os saludan mucho en el Señor." },
{name:'461620',l:'46',c:'16',v:'20',texto:"Os saludan todos los hermanos. Saludaos los unos a los otros con ósculo santo." },
{name:'461621',l:'46',c:'16',v:'21',texto:"Yo, Pablo, os escribo esta salutación de mi propia mano." },
{name:'461622',l:'46',c:'16',v:'22',texto:"El que no amare al Señor Jesucristo, sea anatema. El Señor viene." },
{name:'461623',l:'46',c:'16',v:'23',texto:"La gracia del Señor Jesucristo esté con vosotros." },
{name:'461624',l:'46',c:'16',v:'24',texto:"Mi amor en Cristo Jesús esté con todos vosotros. Amén." },
],
numVersiculos: 24,
},


};
