BibliaRVR60.galatas = {
	libro: "Gálatas",
	numCapitulos: 6,

c1: {
versiculos:[
{name:'4811',l:'48',c:'1',v:'1',texto:"Pablo, apóstol (no de hombres ni por hombre, sino por Jesucristo y por Dios el Padre que lo resucitó de los muertos), " },
{name:'4812',l:'48',c:'1',v:'2',texto:"y todos los hermanos que están conmigo, a las iglesias de Galacia: " },
{name:'4813',l:'48',c:'1',v:'3',texto:"Gracia y paz sean a vosotros, de Dios el Padre y de nuestro Señor Jesucristo," },
{name:'4814',l:'48',c:'1',v:'4',texto:"el cual se dio a sí mismo por nuestros pecados para librarnos del presente siglo malo, conforme a la voluntad de nuestro Dios y Padre," },
{name:'4815',l:'48',c:'1',v:'5',texto:"a quien sea la gloria por los siglos de los siglos. Amén." },
{name:'4816',l:'48',c:'1',v:'6',texto:"Estoy maravillado de que tan pronto os hayáis alejado del que os llamó por la gracia de Cristo, para seguir un evangelio diferente." },
{name:'4817',l:'48',c:'1',v:'7',texto:"No que haya otro, sino que hay algunos que os perturban y quieren pervertir el evangelio de Cristo." },
{name:'4818',l:'48',c:'1',v:'8',texto:"Mas si aun nosotros, o un ángel del cielo, os anunciare otro evangelio diferente del que os hemos anunciado, sea anatema." },
{name:'4819',l:'48',c:'1',v:'9',texto:"Como antes hemos dicho, también ahora lo repito: Si alguno os predica diferente evangelio del que habéis recibido, sea anatema." },
{name:'48110',l:'48',c:'1',v:'10',texto:"Pues, ¿busco ahora el favor de los hombres, o el de Dios? ¿O trato de agradar a los hombres? Pues si todavía agradara a los hombres, no sería siervo de Cristo." },
{name:'48111',l:'48',c:'1',v:'11',texto:"Mas os hago saber, hermanos, que el evangelio anunciado por mí, no es según hombre; " },
{name:'48112',l:'48',c:'1',v:'12',texto:"pues yo ni lo recibí ni lo aprendí de hombre alguno, sino por revelación de Jesucristo." },
{name:'48113',l:'48',c:'1',v:'13',texto:"Porque ya habéis oído acerca de mi conducta en otro tiempo en el judaísmo, que perseguía sobremanera a la iglesia de Dios, y la asolaba; " },
{name:'48114',l:'48',c:'1',v:'14',texto:"y en el judaísmo aventajaba a muchos de mis contemporáneos en mi nación, siendo mucho más celoso de las tradiciones de mis padres." },
{name:'48115',l:'48',c:'1',v:'15',texto:"Pero cuando agradó a Dios, que me apartó desde el vientre de mi madre, y me llamó por su gracia," },
{name:'48116',l:'48',c:'1',v:'16',texto:"revelar a su Hijo en mí, para que yo le predicase entre los gentiles, no consulté en seguida con carne y sangre," },
{name:'48117',l:'48',c:'1',v:'17',texto:"ni subí a Jerusalén a los que eran apóstoles antes que yo; sino que fui a Arabia, y volví de nuevo a Damasco." },
{name:'48118',l:'48',c:'1',v:'18',texto:"Después, pasados tres años, subí a Jerusalén para ver a Pedro, y permanecí con él quince días; " },
{name:'48119',l:'48',c:'1',v:'19',texto:"pero no vi a ningún otro de los apóstoles, sino a Jacobo el hermano del Señor." },
{name:'48120',l:'48',c:'1',v:'20',texto:"En esto que os escribo, he aquí delante de Dios que no miento." },
{name:'48121',l:'48',c:'1',v:'21',texto:"Después fui a las regiones de Siria y de Cilicia," },
{name:'48122',l:'48',c:'1',v:'22',texto:"y no era conocido de vista a las iglesias de Judea, que eran en Cristo; " },
{name:'48123',l:'48',c:'1',v:'23',texto:"solamente oían decir: Aquel que en otro tiempo nos perseguía, ahora predica la fe que en otro tiempo asolaba." },
{name:'48124',l:'48',c:'1',v:'24',texto:"Y glorificaban a Dios en mí." },
],
numVersiculos: 24,
},

c2: {
versiculos:[
{name:'4821',l:'48',c:'2',v:'1',texto:"Después, pasados catorce años, subí otra vez a Jerusalén con Bernabé, llevando también conmigo a Tito." },
{name:'4822',l:'48',c:'2',v:'2',texto:"Pero subí según una revelación, y para no correr o haber corrido en vano, expuse en privado a los que tenían cierta reputación el evangelio que predico entre los gentiles." },
{name:'4823',l:'48',c:'2',v:'3',texto:"Mas ni aun Tito, que estaba conmigo, con todo y ser griego, fue obligado a circuncidarse; " },
{name:'4824',l:'48',c:'2',v:'4',texto:"y esto a pesar de los falsos hermanos introducidos a escondidas, que entraban para espiar nuestra libertad que tenemos en Cristo Jesús, para reducirnos a esclavitud," },
{name:'4825',l:'48',c:'2',v:'5',texto:"a los cuales ni por un momento accedimos a someternos, para que la verdad del evangelio permaneciese con vosotros." },
{name:'4826',l:'48',c:'2',v:'6',texto:"Pero de los que tenían reputación de ser algo (lo que hayan sido en otro tiempo nada me importa; Dios no hace acepción de personas), a mí, pues, los de reputación nada nuevo me comunicaron." },
{name:'4827',l:'48',c:'2',v:'7',texto:"Antes por el contrario, como vieron que me había sido encomendado el evangelio de la incircuncisión, como a Pedro el de la circuncisión " },
{name:'4828',l:'48',c:'2',v:'8',texto:"(pues el que actuó en Pedro para el apostolado de la circuncisión, actuó también en mí para con los gentiles), " },
{name:'4829',l:'48',c:'2',v:'9',texto:"y reconociendo la gracia que me había sido dada, Jacobo, Cefas y Juan, que eran considerados como columnas, nos dieron a mí y a Bernabé la diestra en señal de compañerismo, para que nosotros fuésemos a los gentiles, y ellos a la circuncisión." },
{name:'48210',l:'48',c:'2',v:'10',texto:"Solamente nos pidieron que nos acordásemos de los pobres; lo cual también procuré con diligencia hacer." },
{name:'48211',l:'48',c:'2',v:'11',texto:"Pero cuando Pedro vino a Antioquía, le resistí cara a cara, porque era de condenar." },
{name:'48212',l:'48',c:'2',v:'12',texto:"Pues antes que viniesen algunos de parte de Jacobo, comía con los gentiles; pero después que vinieron, se retraía y se apartaba, porque tenía miedo de los de la circuncisión." },
{name:'48213',l:'48',c:'2',v:'13',texto:"Y en su simulación participaban también los otros judíos, de tal manera que aun Bernabé fue también arrastrado por la hipocresía de ellos." },
{name:'48214',l:'48',c:'2',v:'14',texto:"Pero cuando vi que no andaban rectamente conforme a la verdad del evangelio, dije a Pedro delante de todos: Si tú, siendo judío, vives como los gentiles y no como judío, ¿por qué obligas a los gentiles a judaizar? " },
{name:'48215',l:'48',c:'2',v:'15',texto:"Nosotros, judíos de nacimiento, y no pecadores de entre los gentiles," },
{name:'48216',l:'48',c:'2',v:'16',texto:"sabiendo que el hombre no es justificado por las obras de la ley, sino por la fe de Jesucristo, nosotros también hemos creído en Jesucristo, para ser justificados por la fe de Cristo y no por las obras de la ley, por cuanto por las obras de la ley nadie será justificado." },
{name:'48217',l:'48',c:'2',v:'17',texto:"Y si buscando ser justificados en Cristo, también nosotros somos hallados pecadores, ¿es por eso Cristo ministro de pecado? En ninguna manera." },
{name:'48218',l:'48',c:'2',v:'18',texto:"Porque si las cosas que destruí, las mismas vuelvo a edificar, transgresor me hago." },
{name:'48219',l:'48',c:'2',v:'19',texto:"Porque yo por la ley soy muerto para la ley, a fin de vivir para Dios." },
{name:'48220',l:'48',c:'2',v:'20',texto:"Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí; y lo que ahora vivo en la carne, lo vivo en la fe del Hijo de Dios, el cual me amó y se entregó a sí mismo por mí." },
{name:'48221',l:'48',c:'2',v:'21',texto:"No desecho la gracia de Dios; pues si por la ley fuese la justicia, entonces por demás murió Cristo." },
],
numVersiculos: 21,
},

c3: {
versiculos:[
{name:'4831',l:'48',c:'3',v:'1',texto:"¡Oh gálatas insensatos! ¿quién os fascinó para no obedecer a la verdad, a vosotros ante cuyos ojos Jesucristo fue ya presentado claramente entre vosotros como crucificado? " },
{name:'4832',l:'48',c:'3',v:'2',texto:"Esto solo quiero saber de vosotros: ¿Recibisteis el Espíritu por las obras de la ley, o por el oír con fe? " },
{name:'4833',l:'48',c:'3',v:'3',texto:"¿Tan necios sois? ¿Habiendo comenzado por el Espíritu, ahora vais a acabar por la carne? " },
{name:'4834',l:'48',c:'3',v:'4',texto:"¿Tantas cosas habéis padecido en vano? si es que realmente fue en vano." },
{name:'4835',l:'48',c:'3',v:'5',texto:"Aquel, pues, que os suministra el Espíritu, y hace maravillas entre vosotros, ¿lo hace por las obras de la ley, o por el oír con fe? " },
{name:'4836',l:'48',c:'3',v:'6',texto:"Así Abraham creyó a Dios, y le fue contado por justicia." },
{name:'4837',l:'48',c:'3',v:'7',texto:"Sabed, por tanto, que los que son de fe, éstos son hijos de Abraham." },
{name:'4838',l:'48',c:'3',v:'8',texto:"Y la Escritura, previendo que Dios había de justificar por la fe a los gentiles, dio de antemano la buena nueva a Abraham, diciendo: En ti serán benditas todas las naciones." },
{name:'4839',l:'48',c:'3',v:'9',texto:"De modo que los de la fe son bendecidos con el creyente Abraham." },
{name:'48310',l:'48',c:'3',v:'10',texto:"Porque todos los que dependen de las obras de la ley están bajo maldición, pues escrito está: Maldito todo aquel que no permaneciere en todas las cosas escritas en el libro de la ley, para hacerlas." },
{name:'48311',l:'48',c:'3',v:'11',texto:"Y que por la ley ninguno se justifica para con Dios, es evidente, porque: El justo por la fe vivirá; " },
{name:'48312',l:'48',c:'3',v:'12',texto:"y la ley no es de fe, sino que dice: El que hiciere estas cosas vivirá por ellas." },
{name:'48313',l:'48',c:'3',v:'13',texto:"Cristo nos redimió de la maldición de la ley, hecho por nosotros maldición (porque está escrito: Maldito todo el que es colgado en un madero), " },
{name:'48314',l:'48',c:'3',v:'14',texto:"para que en Cristo Jesús la bendición de Abraham alcanzase a los gentiles, a fin de que por la fe recibiésemos la promesa del Espíritu." },
{name:'48315',l:'48',c:'3',v:'15',texto:"Hermanos, hablo en términos humanos: Un pacto, aunque sea de hombre, una vez ratificado, nadie lo invalida, ni le añade." },
{name:'48316',l:'48',c:'3',v:'16',texto:"Ahora bien, a Abraham fueron hechas las promesas, y a su simiente. No dice: Y a las simientes, como si hablase de muchos, sino como de uno: Y a tu simiente, la cual es Cristo." },
{name:'48317',l:'48',c:'3',v:'17',texto:"Esto, pues, digo: El pacto previamente ratificado por Dios para con Cristo, la ley que vino cuatrocientos treinta años después, no lo abroga, para invalidar la promesa." },
{name:'48318',l:'48',c:'3',v:'18',texto:"Porque si la herencia es por la ley, ya no es por la promesa; pero Dios la concedió a Abraham mediante la promesa." },
{name:'48319',l:'48',c:'3',v:'19',texto:"Entonces, ¿para qué sirve la ley? Fue añadida a causa de las transgresiones, hasta que viniese la simiente a quien fue hecha la promesa; y fue ordenada por medio de ángeles en mano de un mediador." },
{name:'48320',l:'48',c:'3',v:'20',texto:"Y el mediador no lo es de uno solo; pero Dios es uno." },
{name:'48321',l:'48',c:'3',v:'21',texto:"¿Luego la ley es contraria a las promesas de Dios? En ninguna manera; porque si la ley dada pudiera vivificar, la justicia fuera verdaderamente por la ley." },
{name:'48322',l:'48',c:'3',v:'22',texto:"Mas la Escritura lo encerró todo bajo pecado, para que la promesa que es por la fe en Jesucristo fuese dada a los creyentes." },
{name:'48323',l:'48',c:'3',v:'23',texto:"Pero antes que viniese la fe, estábamos confinados bajo la ley, encerrados para aquella fe que iba a ser revelada." },
{name:'48324',l:'48',c:'3',v:'24',texto:"De manera que la ley ha sido nuestro ayo, para llevarnos a Cristo, a fin de que fuésemos justificados por la fe." },
{name:'48325',l:'48',c:'3',v:'25',texto:"Pero venida la fe, ya no estamos bajo ayo," },
{name:'48326',l:'48',c:'3',v:'26',texto:"pues todos sois hijos de Dios por la fe en Cristo Jesús; " },
{name:'48327',l:'48',c:'3',v:'27',texto:"porque todos los que habéis sido bautizados en Cristo, de Cristo estáis revestidos." },
{name:'48328',l:'48',c:'3',v:'28',texto:"Ya no hay judío ni griego; no hay esclavo ni libre; no hay varón ni mujer; porque todos vosotros sois uno en Cristo Jesús." },
{name:'48329',l:'48',c:'3',v:'29',texto:"Y si vosotros sois de Cristo, ciertamente linaje de Abraham sois, y herederos según la promesa." },
],
numVersiculos: 29,
},

c4: {
versiculos:[
{name:'4841',l:'48',c:'4',v:'1',texto:"Pero también digo: Entre tanto que el heredero es niño, en nada difiere del esclavo, aunque es señor de todo; " },
{name:'4842',l:'48',c:'4',v:'2',texto:"sino que está bajo tutores y curadores hasta el tiempo señalado por el padre." },
{name:'4843',l:'48',c:'4',v:'3',texto:"Así también nosotros, cuando éramos niños, estábamos en esclavitud bajo los rudimentos del mundo." },
{name:'4844',l:'48',c:'4',v:'4',texto:"Pero cuando vino el cumplimiento del tiempo, Dios envió a su Hijo, nacido de mujer y nacido bajo la ley," },
{name:'4845',l:'48',c:'4',v:'5',texto:"para que redimiese a los que estaban bajo la ley, a fin de que recibiésemos la adopción de hijos." },
{name:'4846',l:'48',c:'4',v:'6',texto:"Y por cuanto sois hijos, Dios envió a vuestros corazones el Espíritu de su Hijo, el cual clama: ¡Abba, Padre! " },
{name:'4847',l:'48',c:'4',v:'7',texto:"Así que ya no eres esclavo, sino hijo; y si hijo, también heredero de Dios por medio de Cristo." },
{name:'4848',l:'48',c:'4',v:'8',texto:"Ciertamente, en otro tiempo, no conociendo a Dios, servíais a los que por naturaleza no son dioses; " },
{name:'4849',l:'48',c:'4',v:'9',texto:"mas ahora, conociendo a Dios, o más bien, siendo conocidos por Dios, ¿cómo es que os volvéis de nuevo a los débiles y pobres rudimentos, a los cuales os queréis volver a esclavizar? " },
{name:'48410',l:'48',c:'4',v:'10',texto:"Guardáis los días, los meses, los tiempos y los años." },
{name:'48411',l:'48',c:'4',v:'11',texto:"Me temo de vosotros, que haya trabajado en vano con vosotros." },
{name:'48412',l:'48',c:'4',v:'12',texto:"Os ruego, hermanos, que os hagáis como yo, porque yo también me hice como vosotros. Ningún agravio me habéis hecho." },
{name:'48413',l:'48',c:'4',v:'13',texto:"Pues vosotros sabéis que a causa de una enfermedad del cuerpo os anuncié el evangelio al principio; " },
{name:'48414',l:'48',c:'4',v:'14',texto:"y no me despreciasteis ni desechasteis por la prueba que tenía en mi cuerpo, antes bien me recibisteis como a un ángel de Dios, como a Cristo Jesús." },
{name:'48415',l:'48',c:'4',v:'15',texto:"¿Dónde, pues, está esa satisfacción que experimentabais? Porque os doy testimonio de que si hubieseis podido, os hubierais sacado vuestros propios ojos para dármelos." },
{name:'48416',l:'48',c:'4',v:'16',texto:"¿Me he hecho, pues, vuestro enemigo, por deciros la verdad? " },
{name:'48417',l:'48',c:'4',v:'17',texto:"Tienen celo por vosotros, pero no para bien, sino que quieren apartaros de nosotros para que vosotros tengáis celo por ellos." },
{name:'48418',l:'48',c:'4',v:'18',texto:"Bueno es mostrar celo en lo bueno siempre, y no solamente cuando estoy presente con vosotros." },
{name:'48419',l:'48',c:'4',v:'19',texto:"Hijitos míos, por quienes vuelvo a sufrir dolores de parto, hasta que Cristo sea formado en vosotros," },
{name:'48420',l:'48',c:'4',v:'20',texto:"quisiera estar con vosotros ahora mismo y cambiar de tono, pues estoy perplejo en cuanto a vosotros." },
{name:'48421',l:'48',c:'4',v:'21',texto:"Decidme, los que queréis estar bajo la ley: ¿no habéis oído la ley? " },
{name:'48422',l:'48',c:'4',v:'22',texto:"Porque está escrito que Abraham tuvo dos hijos; uno de la esclava, el otro de la libre." },
{name:'48423',l:'48',c:'4',v:'23',texto:"Pero el de la esclava nació según la carne; mas el de la libre, por la promesa." },
{name:'48424',l:'48',c:'4',v:'24',texto:"Lo cual es una alegoría, pues estas mujeres son los dos pactos; el uno proviene del monte Sinaí, el cual da hijos para esclavitud; éste es Agar." },
{name:'48425',l:'48',c:'4',v:'25',texto:"Porque Agar es el monte Sinaí en Arabia, y corresponde a la Jerusalén actual, pues ésta, junto con sus hijos, está en esclavitud." },
{name:'48426',l:'48',c:'4',v:'26',texto:"Mas la Jerusalén de arriba, la cual es madre de todos nosotros, es libre." },
{name:'48427',l:'48',c:'4',v:'27',texto:"Porque está escrito: Regocíjate, oh estéril, tú que no das a luz; Prorrumpe en júbilo y clama, tú que no tienes dolores de parto; Porque más son los hijos de las desolada, que de la que tiene marido." },
{name:'48428',l:'48',c:'4',v:'28',texto:"Así que, hermanos, nosotros, como Isaac, somos hijos de la promesa." },
{name:'48429',l:'48',c:'4',v:'29',texto:"Pero como entonces el que había nacido según la carne perseguía al que había nacido según el Espíritu, así también ahora." },
{name:'48430',l:'48',c:'4',v:'30',texto:"Mas ¿qué dice la Escritura? Echa fuera a la esclava y a su hijo, porque no heredará el hijo de la esclava con el hijo de la libre." },
{name:'48431',l:'48',c:'4',v:'31',texto:"De manera, hermanos, que no somos hijos de la esclava, sino de la libre." },
],
numVersiculos: 31,
},

c5: {
versiculos:[
{name:'4851',l:'48',c:'5',v:'1',texto:"Estad, pues, firmes en la libertad con que Cristo nos hizo libres, y no estéis otra vez sujetos al yugo de esclavitud." },
{name:'4852',l:'48',c:'5',v:'2',texto:"He aquí, yo Pablo os digo que si os circuncidáis, de nada os aprovechará Cristo." },
{name:'4853',l:'48',c:'5',v:'3',texto:"Y otra vez testifico a todo hombre que se circuncida, que está obligado a guardar toda la ley." },
{name:'4854',l:'48',c:'5',v:'4',texto:"De Cristo os desligasteis, los que por la ley os justificáis; de la gracia habéis caído." },
{name:'4855',l:'48',c:'5',v:'5',texto:"Pues nosotros por el Espíritu aguardamos por fe la esperanza de la justicia; " },
{name:'4856',l:'48',c:'5',v:'6',texto:"porque en Cristo Jesús ni la circuncisión vale algo, ni la incircuncisión, sino la fe que obra por el amor." },
{name:'4857',l:'48',c:'5',v:'7',texto:"Vosotros corríais bien; ¿quién os estorbó para no obedecer a la verdad? " },
{name:'4858',l:'48',c:'5',v:'8',texto:"Esta persuasión no procede de aquel que os llama." },
{name:'4859',l:'48',c:'5',v:'9',texto:"Un poco de levadura leuda toda la masa." },
{name:'48510',l:'48',c:'5',v:'10',texto:"Yo confío respecto de vosotros en el Señor, que no pensaréis de otro modo; mas el que os perturba llevará la sentencia, quienquiera que sea." },
{name:'48511',l:'48',c:'5',v:'11',texto:"Y yo, hermanos, si aún predico la circuncisión, ¿por qué padezco persecución todavía? En tal caso se ha quitado el tropiezo de la cruz." },
{name:'48512',l:'48',c:'5',v:'12',texto:"¡Ojalá se mutilasen los que os perturban! " },
{name:'48513',l:'48',c:'5',v:'13',texto:"Porque vosotros, hermanos, a libertad fuisteis llamados; solamente que no uséis la libertad como ocasión para la carne, sino servíos por amor los unos a los otros." },
{name:'48514',l:'48',c:'5',v:'14',texto:"Porque toda la ley en esta sola palabra se cumple: Amarás a tu prójimo como a ti mismo." },
{name:'48515',l:'48',c:'5',v:'15',texto:"Pero si os mordéis y os coméis unos a otros, mirad que también no os consumáis unos a otros." },
{name:'48516',l:'48',c:'5',v:'16',texto:"Digo, pues: Andad en el Espíritu, y no satisfagáis los deseos de la carne." },
{name:'48517',l:'48',c:'5',v:'17',texto:"Porque el deseo de la carne es contra el Espíritu, y el del Espíritu es contra la carne; y éstos se oponen entre sí, para que no hagáis lo que quisiereis." },
{name:'48518',l:'48',c:'5',v:'18',texto:"Pero si sois guiados por el Espíritu, no estáis bajo la ley." },
{name:'48519',l:'48',c:'5',v:'19',texto:"Y manifiestas son las obras de la carne, que son: adulterio, fornicación, inmundicia, lascivia," },
{name:'48520',l:'48',c:'5',v:'20',texto:"idolatría, hechicerías, enemistades, pleitos, celos, iras, contiendas, disensiones, herejías," },
{name:'48521',l:'48',c:'5',v:'21',texto:"envidias, homicidios, borracheras, orgías, y cosas semejantes a estas; acerca de las cuales os amonesto, como ya os lo he dicho antes, que los que practican tales cosas no heredarán el reino de Dios." },
{name:'48522',l:'48',c:'5',v:'22',texto:"Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe," },
{name:'48523',l:'48',c:'5',v:'23',texto:"mansedumbre, templanza; contra tales cosas no hay ley." },
{name:'48524',l:'48',c:'5',v:'24',texto:"Pero los que son de Cristo han crucificado la carne con sus pasiones y deseos." },
{name:'48525',l:'48',c:'5',v:'25',texto:"Si vivimos por el Espíritu, andemos también por el Espíritu." },
{name:'48526',l:'48',c:'5',v:'26',texto:"No nos hagamos vanagloriosos, irritándonos unos a otros, envidiándonos unos a otros." },
],
numVersiculos: 26,
},

c6: {
versiculos:[
{name:'4861',l:'48',c:'6',v:'1',texto:"Hermanos, si alguno fuere sorprendido en alguna falta, vosotros que sois espirituales, restauradle con espíritu de mansedumbre, considerándote a ti mismo, no sea que tú también seas tentado." },
{name:'4862',l:'48',c:'6',v:'2',texto:"Sobrellevad los unos las cargas de los otros, y cumplid así la ley de Cristo." },
{name:'4863',l:'48',c:'6',v:'3',texto:"Porque el que se cree ser algo, no siendo nada, a sí mismo se engaña." },
{name:'4864',l:'48',c:'6',v:'4',texto:"Así que, cada uno someta a prueba su propia obra, y entonces tendrá motivo de gloriarse sólo respecto de sí mismo, y no en otro; " },
{name:'4865',l:'48',c:'6',v:'5',texto:"porque cada uno llevará su propia carga." },
{name:'4866',l:'48',c:'6',v:'6',texto:"El que es enseñado en la palabra, haga partícipe de toda cosa buena al que lo instruye." },
{name:'4867',l:'48',c:'6',v:'7',texto:"No os engañéis; Dios no puede ser burlado: pues todo lo que el hombre sembrare, eso también segará." },
{name:'4868',l:'48',c:'6',v:'8',texto:"Porque el que siembra para su carne, de la carne segará corrupción; mas el que siembra para el Espíritu, del Espíritu segará vida eterna." },
{name:'4869',l:'48',c:'6',v:'9',texto:"No nos cansemos, pues, de hacer bien; porque a su tiempo segaremos, si no desmayamos." },
{name:'48610',l:'48',c:'6',v:'10',texto:"Así que, según tengamos oportunidad, hagamos bien a todos, y mayormente a los de la familia de la fe." },
{name:'48611',l:'48',c:'6',v:'11',texto:"Mirad con cuán grandes letras os escribo de mi propia mano." },
{name:'48612',l:'48',c:'6',v:'12',texto:"Todos los que quieren agradar en la carne, éstos os obligan a que os circuncidéis, solamente para no padecer persecución a causa de la cruz de Cristo." },
{name:'48613',l:'48',c:'6',v:'13',texto:"Porque ni aun los mismos que se circuncidan guardan la ley; pero quieren que vosotros os circuncidéis, para gloriarse en vuestra carne." },
{name:'48614',l:'48',c:'6',v:'14',texto:"Pero lejos esté de mí gloriarme, sino en la cruz de nuestro Señor Jesucristo, por quien el mundo me es crucificado a mí, y yo al mundo." },
{name:'48615',l:'48',c:'6',v:'15',texto:"Porque en Cristo Jesús ni la circuncisión vale nada, ni la incircuncisión, sino una nueva creación." },
{name:'48616',l:'48',c:'6',v:'16',texto:"Y a todos los que anden conforme a esta regla, paz y misericordia sea a ellos, y al Israel de Dios." },
{name:'48617',l:'48',c:'6',v:'17',texto:"De aquí en adelante nadie me cause molestias; porque yo traigo en mi cuerpo las marcas del Señor Jesús." },
{name:'48618',l:'48',c:'6',v:'18',texto:"Hermanos, la gracia de nuestro Señor Jesucristo sea con vuestro espíritu. Amén." },
],
numVersiculos: 18,
},
	

};
