BibliaRVR60.efesios = {
	libro: "Efesios",
	numCapitulos: 6,

c1: {
versiculos:[
{name:'4911',l:'49',c:'1',v:'1',texto:"Pablo, apóstol de Jesucristo por la voluntad de Dios, a los santos y fieles en Cristo Jesús que están en Efeso: " },
{name:'4912',l:'49',c:'1',v:'2',texto:"Gracia y paz a vosotros, de Dios nuestro Padre y del Señor Jesucristo." },
{name:'4913',l:'49',c:'1',v:'3',texto:"Bendito sea el Dios y Padre de nuestro Señor Jesucristo, que nos bendijo con toda bendición espiritual en los lugares celestiales en Cristo," },
{name:'4914',l:'49',c:'1',v:'4',texto:"según nos escogió en él antes de la fundación del mundo, para que fuésemos santos y sin mancha delante de él," },
{name:'4915',l:'49',c:'1',v:'5',texto:"en amor habiéndonos predestinado para ser adoptados hijos suyos por medio de Jesucristo, según el puro afecto de su voluntad," },
{name:'4916',l:'49',c:'1',v:'6',texto:"para alabanza de la gloria de su gracia, con la cual nos hizo aceptos en el Amado," },
{name:'4917',l:'49',c:'1',v:'7',texto:"en quien tenemos redención por su sangre, el perdón de pecados según las riquezas de su gracia," },
{name:'4918',l:'49',c:'1',v:'8',texto:"que hizo sobreabundar para con nosotros en toda sabiduría e inteligencia," },
{name:'4919',l:'49',c:'1',v:'9',texto:"dándonos a conocer el misterio de su voluntad, según su beneplácito, el cual se había propuesto en si mismo," },
{name:'49110',l:'49',c:'1',v:'10',texto:"de reunir todas las cosas en Cristo, en la dispensación del cumplimiento de los tiempos, así las que están en los cielos, como las que están en la tierra." },
{name:'49111',l:'49',c:'1',v:'11',texto:"En él asimismo tuvimos herencia, habiendo sido predestinados conforme al propósito del que hace todas las cosas según el designio de su voluntad," },
{name:'49112',l:'49',c:'1',v:'12',texto:"a fin de que seamos para alabanza de su gloria, nosotros los que primeramente esperábamos en Cristo." },
{name:'49113',l:'49',c:'1',v:'13',texto:"En él también vosotros, habiendo oído la palabra de verdad, el evangelio de vuestra salvación, y habiendo creído en él, fuisteis sellados con el Espíritu Santo de la promesa," },
{name:'49114',l:'49',c:'1',v:'14',texto:"que es las arras de nuestra herencia hasta la redención de la posesión adquirida, para alabanza de su gloria." },
{name:'49115',l:'49',c:'1',v:'15',texto:"Por esta causa también yo, habiendo oído de vuestra fe en el Señor Jesús, y de vuestro amor para con todos los santos," },
{name:'49116',l:'49',c:'1',v:'16',texto:"no ceso de dar gracias por vosotros, haciendo memoria de vosotros en mis oraciones," },
{name:'49117',l:'49',c:'1',v:'17',texto:"para que el Dios de nuestro Señor Jesucristo, el Padre de gloria, os dé espíritu de sabiduría y de revelación en el conocimiento de él," },
{name:'49118',l:'49',c:'1',v:'18',texto:"alumbrando los ojos de vuestro entendimiento, para que sepáis cuál es la esperanza a que él os ha llamado, y cuáles las riquezas de la gloria de su herencia en los santos," },
{name:'49119',l:'49',c:'1',v:'19',texto:"y cuál la supereminente grandeza de su poder para con nosotros los que creemos, según la operación del poder de su fuerza," },
{name:'49120',l:'49',c:'1',v:'20',texto:"la cual operó en Cristo, resucitándole de los muertos y sentándole a su diestra en los lugares celestiales," },
{name:'49121',l:'49',c:'1',v:'21',texto:"sobre todo principado y autoridad y poder y señorío, y sobre todo nombre que se nombra, no sólo en este siglo, sino también en el venidero; " },
{name:'49122',l:'49',c:'1',v:'22',texto:"y sometió todas las cosas bajo sus pies, y lo dio por cabeza sobre todas las cosas a la iglesia," },
{name:'49123',l:'49',c:'1',v:'23',texto:"la cual es su cuerpo, la plenitud de Aquel que todo lo llena en todo." },
],
numVersiculos: 23,
},

c2: {
versiculos:[
{name:'4921',l:'49',c:'2',v:'1',texto:"Y él os dio vida a vosotros, cuando estabais muertos en vuestros delitos y pecados," },
{name:'4922',l:'49',c:'2',v:'2',texto:"en los cuales anduvisteis en otro tiempo, siguiendo la corriente de este mundo, conforme al príncipe de la potestad del aire, el espíritu que ahora opera en los hijos de desobediencia," },
{name:'4923',l:'49',c:'2',v:'3',texto:"entre los cuales también todos nosotros vivimos en otro tiempo en los deseos de nuestra carne, haciendo la voluntad de la carne y de los pensamientos, y éramos por naturaleza hijos de ira, lo mismo que los demás." },
{name:'4924',l:'49',c:'2',v:'4',texto:"Pero Dios, que es rico en misericordia, por su gran amor con que nos amó," },
{name:'4925',l:'49',c:'2',v:'5',texto:"aun estando nosotros muertos en pecados, nos dio vida juntamente con Cristo (por gracia sois salvos), " },
{name:'4926',l:'49',c:'2',v:'6',texto:"y juntamente con él nos resucitó, y asimismo nos hizo sentar en los lugares celestiales con Cristo Jesús," },
{name:'4927',l:'49',c:'2',v:'7',texto:"para mostrar en los siglos venideros las abundantes riquezas de su gracia en su bondad para con nosotros en Cristo Jesús." },
{name:'4928',l:'49',c:'2',v:'8',texto:"Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios; " },
{name:'4929',l:'49',c:'2',v:'9',texto:"no por obras, para que nadie se gloríe." },
{name:'49210',l:'49',c:'2',v:'10',texto:"Porque somos hechura suya, creados en Cristo Jesús para buenas obras, las cuales Dios preparó de antemano para que anduviésemos en ellas." },
{name:'49211',l:'49',c:'2',v:'11',texto:"Por tanto, acordaos de que en otro tiempo vosotros, los gentiles en cuanto a la carne, erais llamados incircuncisión por la llamada circuncisión hecha con mano en la carne." },
{name:'49212',l:'49',c:'2',v:'12',texto:"En aquel tiempo estabais sin Cristo, alejados de la ciudadanía de Israel y ajenos a los pactos de la promesa, sin esperanza y sin Dios en el mundo." },
{name:'49213',l:'49',c:'2',v:'13',texto:"Pero ahora en Cristo Jesús, vosotros que en otro tiempo estabais lejos, habéis sido hechos cercanos por la sangre de Cristo." },
{name:'49214',l:'49',c:'2',v:'14',texto:"Porque él es nuestra paz, que de ambos pueblos hizo uno, derribando la pared intermedia de separación," },
{name:'49215',l:'49',c:'2',v:'15',texto:"aboliendo en su carne las enemistades, la ley de los mandamientos expresados en ordenanzas, para crear en sí mismo de los dos un solo y nuevo hombre, haciendo la paz," },
{name:'49216',l:'49',c:'2',v:'16',texto:"y mediante la cruz reconciliar con Dios a ambos en un solo cuerpo, matando en ella las enemistades." },
{name:'49217',l:'49',c:'2',v:'17',texto:"Y vino y anunció las buenas nuevas de paz a vosotros que estabais lejos, y a los que estaban cerca; " },
{name:'49218',l:'49',c:'2',v:'18',texto:"porque por medio de él los unos y los otros tenemos entrada por un mismo Espíritu al Padre." },
{name:'49219',l:'49',c:'2',v:'19',texto:"Así que ya no sois extranjeros ni advenedizos, sino conciudadanos de los santos, y miembros de la familia de Dios," },
{name:'49220',l:'49',c:'2',v:'20',texto:"edificados sobre el fundamento de los apóstoles y profetas, siendo la principal piedra del ángulo Jesucristo mismo," },
{name:'49221',l:'49',c:'2',v:'21',texto:"en quien todo el edificio, bien coordinado, va creciendo para ser un templo santo en el Señor; " },
{name:'49222',l:'49',c:'2',v:'22',texto:"en quien vosotros también sois juntamente edificados para morada de Dios en el Espíritu." },
],
numVersiculos: 22,
},

c3: {
versiculos:[
{name:'4931',l:'49',c:'3',v:'1',texto:"Por esta causa yo Pablo, prisionero de Cristo Jesús por vosotros los gentiles; " },
{name:'4932',l:'49',c:'3',v:'2',texto:"si es que habéis oído de la administración de la gracia de Dios que me fue dada para con vosotros; " },
{name:'4933',l:'49',c:'3',v:'3',texto:"que por revelación me fue declarado el misterio, como antes lo he escrito brevemente," },
{name:'4934',l:'49',c:'3',v:'4',texto:"leyendo lo cual podéis entender cuál sea mi conocimiento en el misterio de Cristo," },
{name:'4935',l:'49',c:'3',v:'5',texto:"misterio que en otras generaciones no se dio a conocer a los hijos de los hombres, como ahora es revelado a sus santos apóstoles y profetas por el Espíritu: " },
{name:'4936',l:'49',c:'3',v:'6',texto:"que los gentiles son coherederos y miembros del mismo cuerpo, y copartícipes de la promesa en Cristo Jesús por medio del evangelio," },
{name:'4937',l:'49',c:'3',v:'7',texto:"del cual yo fui hecho ministro por el don de la gracia de Dios que me ha sido dado según la operación de su poder." },
{name:'4938',l:'49',c:'3',v:'8',texto:"A mí, que soy menos que el más pequeño de todos los santos, me fue dada esta gracia de anunciar entre los gentiles el evangelio de las inescrutables riquezas de Cristo," },
{name:'4939',l:'49',c:'3',v:'9',texto:"y de aclarar a todos cuál sea la dispensación del misterio escondido desde los siglos en Dios, que creó todas las cosas; " },
{name:'49310',l:'49',c:'3',v:'10',texto:"para que la multiforme sabiduría de Dios sea ahora dada a conocer por medio de la iglesia a los principados y potestades en los lugares celestiales," },
{name:'49311',l:'49',c:'3',v:'11',texto:"conforme al propósito eterno que hizo en Cristo Jesús nuestro Señor," },
{name:'49312',l:'49',c:'3',v:'12',texto:"en quien tenemos seguridad y acceso con confianza por medio de la fe en él; " },
{name:'49313',l:'49',c:'3',v:'13',texto:"por lo cual pido que no desmayéis a causa de mis tribulaciones por vosotros, las cuales son vuestra gloria." },
{name:'49314',l:'49',c:'3',v:'14',texto:"Por esta causa doblo mis rodillas ante el Padre de nuestro Señor Jesucristo," },
{name:'49315',l:'49',c:'3',v:'15',texto:"de quien toma nombre toda familia en los cielos y en la tierra," },
{name:'49316',l:'49',c:'3',v:'16',texto:"para que os dé, conforme a las riquezas de su gloria, el ser fortalecidos con poder en el hombre interior por su Espíritu; " },
{name:'49317',l:'49',c:'3',v:'17',texto:"para que habite Cristo por la fe en vuestros corazones, a fin de que, arraigados y cimentados en amor," },
{name:'49318',l:'49',c:'3',v:'18',texto:"seáis plenamente capaces de comprender con todos los santos cuál sea la anchura, la longitud, la profundidad y la altura," },
{name:'49319',l:'49',c:'3',v:'19',texto:"y de conocer el amor de Cristo, que excede a todo conocimiento, para que seáis llenos de toda la plenitud de Dios." },
{name:'49320',l:'49',c:'3',v:'20',texto:"Y a Aquel que es poderoso para hacer todas las cosas mucho más abundantemente de lo que pedimos o entendemos, según el poder que actúa en nosotros," },
{name:'49321',l:'49',c:'3',v:'21',texto:"a él sea gloria en la iglesia en Cristo Jesús por todas las edades, por los siglos de los siglos. Amén." },
],
numVersiculos: 21,
},

c4: {
versiculos:[
{name:'4941',l:'49',c:'4',v:'1',texto:"Yo pues, preso en el Señor, os ruego que andéis como es digno de la vocación con que fuisteis llamados," },
{name:'4942',l:'49',c:'4',v:'2',texto:"con toda humildad y mansedumbre, soportándoos con paciencia los unos a los otros en amor," },
{name:'4943',l:'49',c:'4',v:'3',texto:"solícitos en guardar la unidad del Espíritu en el vínculo de la paz; " },
{name:'4944',l:'49',c:'4',v:'4',texto:"un cuerpo, y un Espíritu, como fuisteis también llamados en una misma esperanza de vuestra vocación; " },
{name:'4945',l:'49',c:'4',v:'5',texto:"un Señor, una fe, un bautismo," },
{name:'4946',l:'49',c:'4',v:'6',texto:"un Dios y Padre de todos, el cual es sobre todos, y por todos, y en todos." },
{name:'4947',l:'49',c:'4',v:'7',texto:"Pero a cada uno de nosotros fue dada la gracia conforme a la medida del don de Cristo." },
{name:'4948',l:'49',c:'4',v:'8',texto:"Por lo cual dice: Subiendo a lo alto, llevó cautiva la cautividad, Y dio dones a los hombres." },
{name:'4949',l:'49',c:'4',v:'9',texto:"Y eso de que subió, ¿qué es, sino que también había descendido primero a las partes más bajas de la tierra? " },
{name:'49410',l:'49',c:'4',v:'10',texto:"El que descendió, es el mismo que también subió por encima de todos los cielos para llenarlo todo." },
{name:'49411',l:'49',c:'4',v:'11',texto:"Y él mismo constituyó a unos, apóstoles; a otros, profetas; a otros, evangelistas; a otros, pastores y maestros," },
{name:'49412',l:'49',c:'4',v:'12',texto:"a fin de perfeccionar a los santos para la obra del ministerio, para la edificación del cuerpo de Cristo," },
{name:'49413',l:'49',c:'4',v:'13',texto:"hasta que todos lleguemos a la unidad de la fe y del conocimiento del Hijo de Dios, a un varón perfecto, a la medida de la estatura de la plenitud de Cristo; " },
{name:'49414',l:'49',c:'4',v:'14',texto:"para que ya no seamos niños fluctuantes, llevados por doquiera de todo viento de doctrina, por estratagema de hombres que para engañar emplean con astucia las artimañas del error," },
{name:'49415',l:'49',c:'4',v:'15',texto:"sino que siguiendo la verdad en amor, crezcamos en todo en aquel que es la cabeza, esto es, Cristo," },
{name:'49416',l:'49',c:'4',v:'16',texto:"de quien todo el cuerpo, bien concertado y unido entre sí por todas las coyunturas que se ayudan mutuamente, según la actividad propia de cada miembro, recibe su crecimiento para ir edificándose en amor." },
{name:'49417',l:'49',c:'4',v:'17',texto:"Esto, pues, digo y requiero en el Señor: que ya no andéis como los otros gentiles, que andan en la vanidad de su mente," },
{name:'49418',l:'49',c:'4',v:'18',texto:"teniendo el entendimiento entenebrecido, ajenos de la vida de Dios por la ignorancia que en ellos hay, por la dureza de su corazón; " },
{name:'49419',l:'49',c:'4',v:'19',texto:"los cuales, después que perdieron toda sensibilidad, se entregaron a la lascivia para cometer con avidez toda clase de impureza." },
{name:'49420',l:'49',c:'4',v:'20',texto:"Mas vosotros no habéis aprendido así a Cristo," },
{name:'49421',l:'49',c:'4',v:'21',texto:"si en verdad le habéis oído, y habéis sido por él enseñados, conforme a la verdad que está en Jesús." },
{name:'49422',l:'49',c:'4',v:'22',texto:"En cuanto a la pasada manera de vivir, despojaos del viejo hombre, que está viciado conforme a los deseos engañosos," },
{name:'49423',l:'49',c:'4',v:'23',texto:"y renovaos en el espíritu de vuestra mente," },
{name:'49424',l:'49',c:'4',v:'24',texto:"y vestíos del nuevo hombre, creado según Dios en la justicia y santidad de la verdad." },
{name:'49425',l:'49',c:'4',v:'25',texto:"Por lo cual, desechando la mentira, hablad verdad cada uno con su prójimo; porque somos miembros los unos de los otros." },
{name:'49426',l:'49',c:'4',v:'26',texto:"Airaos, pero no pequéis; no se ponga el sol sobre vuestro enojo," },
{name:'49427',l:'49',c:'4',v:'27',texto:"ni deis lugar al diablo." },
{name:'49428',l:'49',c:'4',v:'28',texto:"El que hurtaba, no hurte más, sino trabaje, haciendo con sus manos lo que es bueno, para que tenga qué compartir con el que padece necesidad." },
{name:'49429',l:'49',c:'4',v:'29',texto:"Ninguna palabra corrompida salga de vuestra boca, sino la que sea buena para la necesaria edificación, a fin de dar gracia a los oyentes." },
{name:'49430',l:'49',c:'4',v:'30',texto:"Y no contristéis al Espíritu Santo de Dios, con el cual fuisteis sellados para el día de la redención." },
{name:'49431',l:'49',c:'4',v:'31',texto:"Quítense de vosotros toda amargura, enojo, ira, gritería y maledicencia, y toda malicia." },
{name:'49432',l:'49',c:'4',v:'32',texto:"Antes sed benignos unos con otros, misericordiosos, perdonándoos unos a otros, como Dios también os perdonó a vosotros en Cristo." },
],
numVersiculos: 32,
},

c5: {
versiculos:[
{name:'4951',l:'49',c:'5',v:'1',texto:"Sed, pues, imitadores de Dios como hijos amados." },
{name:'4952',l:'49',c:'5',v:'2',texto:"Y andad en amor, como también Cristo nos amó, y se entregó a sí mismo por nosotros, ofrenda y sacrificio a Dios en olor fragante." },
{name:'4953',l:'49',c:'5',v:'3',texto:"Pero fornicación y toda inmundicia, o avaricia, ni aun se nombre entre vosotros, como conviene a santos; " },
{name:'4954',l:'49',c:'5',v:'4',texto:"ni palabras deshonestas, ni necedades, ni truhanerías, que no convienen, sino antes bien acciones de gracias." },
{name:'4955',l:'49',c:'5',v:'5',texto:"Porque sabéis esto, que ningún fornicario, o inmundo, o avaro, que es idólatra, tiene herencia en el reino de Cristo y de Dios." },
{name:'4956',l:'49',c:'5',v:'6',texto:"Nadie os engañe con palabras vanas, porque por estas cosas viene la ira de Dios sobre los hijos de desobediencia." },
{name:'4957',l:'49',c:'5',v:'7',texto:"No seáis, pues, partícipes con ellos." },
{name:'4958',l:'49',c:'5',v:'8',texto:"Porque en otro tiempo erais tinieblas, mas ahora sois luz en el Señor; andad como hijos de luz " },
{name:'4959',l:'49',c:'5',v:'9',texto:"(porque el fruto del Espíritu es en toda bondad, justicia y verdad), " },
{name:'49510',l:'49',c:'5',v:'10',texto:"comprobando lo que es agradable al Señor." },
{name:'49511',l:'49',c:'5',v:'11',texto:"Y no participéis en las obras infructuosas de las tinieblas, sino más bien reprendedlas; " },
{name:'49512',l:'49',c:'5',v:'12',texto:"porque vergonzoso es aun hablar de lo que ellos hacen en secreto." },
{name:'49513',l:'49',c:'5',v:'13',texto:"Mas todas las cosas, cuando son puestas en evidencia por la luz, son hechas manifiestas; porque la luz es lo que manifiesta todo." },
{name:'49514',l:'49',c:'5',v:'14',texto:"Por lo cual dice: Despiértate, tú que duermes, Y levántate de los muertos, Y te alumbrará Cristo." },
{name:'49515',l:'49',c:'5',v:'15',texto:"Mirad, pues, con diligencia cómo andéis, no como necios sino como sabios," },
{name:'49516',l:'49',c:'5',v:'16',texto:"aprovechando bien el tiempo, porque los días son malos." },
{name:'49517',l:'49',c:'5',v:'17',texto:"Por tanto, no seáis insensatos, sino entendidos de cuál sea la voluntad del Señor." },
{name:'49518',l:'49',c:'5',v:'18',texto:"No os embriaguéis con vino, en lo cual hay disolución; antes bien sed llenos del Espíritu," },
{name:'49519',l:'49',c:'5',v:'19',texto:"hablando entre vosotros con salmos, con himnos y cánticos espirituales, cantando y alabando al Señor en vuestros corazones; " },
{name:'49520',l:'49',c:'5',v:'20',texto:"dando siempre gracias por todo al Dios y Padre, en el nombre de nuestro Señor Jesucristo." },
{name:'49521',l:'49',c:'5',v:'21',texto:"Someteos unos a otros en el temor de Dios." },
{name:'49522',l:'49',c:'5',v:'22',texto:"Las casadas estén sujetas a sus propios maridos, como al Señor; " },
{name:'49523',l:'49',c:'5',v:'23',texto:"porque el marido es cabeza de la mujer, así como Cristo es cabeza de la iglesia, la cual es su cuerpo, y él es su Salvador." },
{name:'49524',l:'49',c:'5',v:'24',texto:"Así que, como la iglesia está sujeta a Cristo, así también las casadas lo estén a sus maridos en todo." },
{name:'49525',l:'49',c:'5',v:'25',texto:"Maridos, amad a vuestras mujeres, así como Cristo amó a la iglesia, y se entregó a sí mismo por ella," },
{name:'49526',l:'49',c:'5',v:'26',texto:"para santificarla, habiéndola purificado en el lavamiento del agua por la palabra," },
{name:'49527',l:'49',c:'5',v:'27',texto:"a fin de presentársela a sí mismo, una iglesia gloriosa, que no tuviese mancha ni arruga ni cosa semejante, sino que fuese santa y sin mancha." },
{name:'49528',l:'49',c:'5',v:'28',texto:"Así también los maridos deben amar a sus mujeres como a sus mismos cuerpos. El que ama a su mujer, a sí mismo se ama." },
{name:'49529',l:'49',c:'5',v:'29',texto:"Porque nadie aborreció jamás a su propia carne, sino que la sustenta y la cuida, como también Cristo a la iglesia," },
{name:'49530',l:'49',c:'5',v:'30',texto:"porque somos miembros de su cuerpo, de su carne y de sus huesos." },
{name:'49531',l:'49',c:'5',v:'31',texto:"Por esto dejará el hombre a su padre y a su madre, y se unirá a su mujer, y los dos serán una sola carne." },
{name:'49532',l:'49',c:'5',v:'32',texto:"Grande es este misterio; mas yo digo esto respecto de Cristo y de la iglesia." },
{name:'49533',l:'49',c:'5',v:'33',texto:"Por lo demás, cada uno de vosotros ame también a su mujer como a sí mismo; y la mujer respete a su marido." },
],
numVersiculos: 33,
},

c6: {
versiculos:[
{name:'4961',l:'49',c:'6',v:'1',texto:"Hijos, obedeced en el Señor a vuestros padres, porque esto es justo." },
{name:'4962',l:'49',c:'6',v:'2',texto:"Honra a tu padre y a tu madre, que es el primer mandamiento con promesa; " },
{name:'4963',l:'49',c:'6',v:'3',texto:"para que te vaya bien, y seas de larga vida sobre la tierra." },
{name:'4964',l:'49',c:'6',v:'4',texto:"Y vosotros, padres, no provoquéis a ira a vuestros hijos, sino criadlos en disciplina y amonestación del Señor." },
{name:'4965',l:'49',c:'6',v:'5',texto:"Siervos, obedeced a vuestros amos terrenales con temor y temblor, con sencillez de vuestro corazón, como a Cristo; " },
{name:'4966',l:'49',c:'6',v:'6',texto:"no sirviendo al ojo, como los que quieren agradar a los hombres, sino como siervos de Cristo, de corazón haciendo la voluntad de Dios; " },
{name:'4967',l:'49',c:'6',v:'7',texto:"sirviendo de buena voluntad, como al Señor y no a los hombres," },
{name:'4968',l:'49',c:'6',v:'8',texto:"sabiendo que el bien que cada uno hiciere, ése recibirá del Señor, sea siervo o sea libre." },
{name:'4969',l:'49',c:'6',v:'9',texto:"Y vosotros, amos, haced con ellos lo mismo, dejando las amenazas, sabiendo que el Señor de ellos y vuestro está en los cielos, y que para él no hay acepción de personas." },
{name:'49610',l:'49',c:'6',v:'10',texto:"Por lo demás, hermanos míos, fortaleceos en el Señor, y en el poder de su fuerza." },
{name:'49611',l:'49',c:'6',v:'11',texto:"Vestíos de toda la armadura de Dios, para que podáis estar firmes contra las asechanzas del diablo." },
{name:'49612',l:'49',c:'6',v:'12',texto:"Porque no tenemos lucha contra sangre y carne, sino contra principados, contra potestades, contra los gobernadores de las tinieblas de este siglo, contra huestes espirituales de maldad en las regiones celestes." },
{name:'49613',l:'49',c:'6',v:'13',texto:"Por tanto, tomad toda la armadura de Dios, para que podáis resistir en el día malo, y habiendo acabado todo, estar firmes." },
{name:'49614',l:'49',c:'6',v:'14',texto:"Estad, pues, firmes, ceñidos vuestros lomos con la verdad, y vestidos con la coraza de justicia," },
{name:'49615',l:'49',c:'6',v:'15',texto:"y calzados los pies con el apresto del evangelio de la paz." },
{name:'49616',l:'49',c:'6',v:'16',texto:"Sobre todo, tomad el escudo de la fe, con que podáis apagar todos los dardos de fuego del maligno." },
{name:'49617',l:'49',c:'6',v:'17',texto:"Y tomad el yelmo de la salvación, y la espada del Espíritu, que es la palabra de Dios; " },
{name:'49618',l:'49',c:'6',v:'18',texto:"orando en todo tiempo con toda oración y súplica en el Espíritu, y velando en ello con toda perseverancia y súplica por todos los santos; " },
{name:'49619',l:'49',c:'6',v:'19',texto:"y por mí, a fin de que al abrir mi boca me sea dada palabra para dar a conocer con denuedo el misterio del evangelio," },
{name:'49620',l:'49',c:'6',v:'20',texto:"por el cual soy embajador en cadenas; que con denuedo hable de él, como debo hablar." },
{name:'49621',l:'49',c:'6',v:'21',texto:"Para que también vosotros sepáis mis asuntos, y lo que hago, todo os lo hará saber Tíquico, hermano amado y fiel ministro en el Señor," },
{name:'49622',l:'49',c:'6',v:'22',texto:"el cual envié a vosotros para esto mismo, para que sepáis lo tocante a nosotros, y que consuele vuestros corazones." },
{name:'49623',l:'49',c:'6',v:'23',texto:"Paz sea a los hermanos, y amor con fe, de Dios Padre y del Señor Jesucristo." },
{name:'49624',l:'49',c:'6',v:'24',texto:"La gracia sea con todos los que aman a nuestro Señor Jesucristo con amor inalterable. Amén." },
],
numVersiculos: 24,
},


};
