BibliaRVR60.filipenses = {
	libro: "Filipenses",
	numCapitulos: 4,

c1: {
versiculos:[
{name:'5011',l:'50',c:'1',v:'1',texto:"Pablo y Timoteo, siervos de Jesucristo, a todos los santos en Cristo Jesús que están en Filipos, con los obispos y diáconos: " },
{name:'5012',l:'50',c:'1',v:'2',texto:"Gracia y paz a vosotros, de Dios nuestro Padre y del Señor Jesucristo." },
{name:'5013',l:'50',c:'1',v:'3',texto:"Doy gracias a mi Dios siempre que me acuerdo de vosotros," },
{name:'5014',l:'50',c:'1',v:'4',texto:"siempre en todas mis oraciones rogando con gozo por todos vosotros," },
{name:'5015',l:'50',c:'1',v:'5',texto:"por vuestra comunión en el evangelio, desde el primer día hasta ahora; " },
{name:'5016',l:'50',c:'1',v:'6',texto:"estando persuadido de esto, que el que comenzó en vosotros la buena obra, la perfeccionará hasta el día de Jesucristo; " },
{name:'5017',l:'50',c:'1',v:'7',texto:"como me es justo sentir esto de todos vosotros, por cuanto os tengo en el corazón; y en mis prisiones, y en la defensa y confirmación del evangelio, todos vosotros sois participantes conmigo de la gracia." },
{name:'5018',l:'50',c:'1',v:'8',texto:"Porque Dios me es testigo de cómo os amo a todos vosotros con el entrañable amor de Jesucristo." },
{name:'5019',l:'50',c:'1',v:'9',texto:"Y esto pido en oración, que vuestro amor abunde aun más y más en ciencia y en todo conocimiento," },
{name:'50110',l:'50',c:'1',v:'10',texto:"para que aprobéis lo mejor, a fin de que seáis sinceros e irreprensibles para el día de Cristo," },
{name:'50111',l:'50',c:'1',v:'11',texto:"llenos de frutos de justicia que son por medio de Jesucristo, para gloria y alabanza de Dios." },
{name:'50112',l:'50',c:'1',v:'12',texto:"Quiero que sepáis, hermanos, que las cosas que me han sucedido, han redundado más bien para el progreso del evangelio," },
{name:'50113',l:'50',c:'1',v:'13',texto:"de tal manera que mis prisiones se han hecho patentes en Cristo en todo el pretorio, y a todos los demás." },
{name:'50114',l:'50',c:'1',v:'14',texto:"Y la mayoría de los hermanos, cobrando ánimo en el Señor con mis prisiones, se atreven mucho más a hablar la palabra sin temor." },
{name:'50115',l:'50',c:'1',v:'15',texto:"Algunos, a la verdad, predican a Cristo por envidia y contienda; pero otros de buena voluntad." },
{name:'50116',l:'50',c:'1',v:'16',texto:"Los unos anuncian a Cristo por contención, no sinceramente, pensando añadir aflicción a mis prisiones; " },
{name:'50117',l:'50',c:'1',v:'17',texto:"pero los otros por amor, sabiendo que estoy puesto para la defensa del evangelio." },
{name:'50118',l:'50',c:'1',v:'18',texto:"¿Qué, pues? Que no obstante, de todas maneras, o por pretexto o por verdad, Cristo es anunciado; y en esto me gozo, y me gozaré aún." },
{name:'50119',l:'50',c:'1',v:'19',texto:"Porque sé que por vuestra oración y la suministración del Espíritu de Jesucristo, esto resultará en mi liberación," },
{name:'50120',l:'50',c:'1',v:'20',texto:"conforme a mi anhelo y esperanza de que en nada seré avergonzado; antes bien con toda confianza, como siempre, ahora también será magnificado Cristo en mi cuerpo, o por vida o por muerte." },
{name:'50121',l:'50',c:'1',v:'21',texto:"Porque para mí el vivir es Cristo, y el morir es ganancia." },
{name:'50122',l:'50',c:'1',v:'22',texto:"Mas si el vivir en la carne resulta para mí en beneficio de la obra, no sé entonces qué escoger." },
{name:'50123',l:'50',c:'1',v:'23',texto:"Porque de ambas cosas estoy puesto en estrecho, teniendo deseo de partir y estar con Cristo, lo cual es muchísimo mejor; " },
{name:'50124',l:'50',c:'1',v:'24',texto:"pero quedar en la carne es más necesario por causa de vosotros." },
{name:'50125',l:'50',c:'1',v:'25',texto:"Y confiado en esto, sé que quedaré, que aún permaneceré con todos vosotros, para vuestro provecho y gozo de la fe," },
{name:'50126',l:'50',c:'1',v:'26',texto:"para que abunde vuestra gloria de mí en Cristo Jesús por mi presencia otra vez entre vosotros." },
{name:'50127',l:'50',c:'1',v:'27',texto:"Solamente que os comportéis como es digno del evangelio de Cristo, para que o sea que vaya a veros, o que esté ausente, oiga de vosotros que estáis firmes en un mismo espíritu, combatiendo unánimes por la fe del evangelio," },
{name:'50128',l:'50',c:'1',v:'28',texto:"y en nada intimidados por los que se oponen, que para ellos ciertamente es indicio de perdición, mas para vosotros de salvación; y esto de Dios." },
{name:'50129',l:'50',c:'1',v:'29',texto:"Porque a vosotros os es concedido a causa de Cristo, no sólo que creáis en él, sino también que padezcáis por él," },
{name:'50130',l:'50',c:'1',v:'30',texto:"teniendo el mismo conflicto que habéis visto en mí, y ahora oís que hay en mí." },
],
numVersiculos: 30,
},

c2: {
versiculos:[
{name:'5021',l:'50',c:'2',v:'1',texto:"Por tanto, si hay alguna consolación en Cristo, si algún consuelo de amor, si alguna comunión del Espíritu, si algún afecto entrañable, si alguna misericordia," },
{name:'5022',l:'50',c:'2',v:'2',texto:"completad mi gozo, sintiendo lo mismo, teniendo el mismo amor, unánimes, sintiendo una misma cosa." },
{name:'5023',l:'50',c:'2',v:'3',texto:"Nada hagáis por contienda o por vanagloria; antes bien con humildad, estimando cada uno a los demás como superiores a él mismo; " },
{name:'5024',l:'50',c:'2',v:'4',texto:"no mirando cada uno por lo suyo propio, sino cada cual también por lo de los otros." },
{name:'5025',l:'50',c:'2',v:'5',texto:"Haya, pues, en vosotros este sentir que hubo también en Cristo Jesús," },
{name:'5026',l:'50',c:'2',v:'6',texto:"el cual, siendo en forma de Dios, no estimó el ser igual a Dios como cosa a que aferrarse," },
{name:'5027',l:'50',c:'2',v:'7',texto:"sino que se despojó a sí mismo, tomando forma de siervo, hecho semejante a los hombres; " },
{name:'5028',l:'50',c:'2',v:'8',texto:"y estando en la condición de hombre, se humilló a sí mismo, haciéndose obediente hasta la muerte, y muerte de cruz." },
{name:'5029',l:'50',c:'2',v:'9',texto:"Por lo cual Dios también le exaltó hasta lo sumo, y le dio un nombre que es sobre todo nombre," },
{name:'50210',l:'50',c:'2',v:'10',texto:"para que en el nombre de Jesús se doble toda rodilla de los que están en los cielos, y en la tierra, y debajo de la tierra; " },
{name:'50211',l:'50',c:'2',v:'11',texto:"y toda lengua confiese que Jesucristo es el Señor, para gloria de Dios Padre." },
{name:'50212',l:'50',c:'2',v:'12',texto:"Por tanto, amados míos, como siempre habéis obedecido, no como en mi presencia solamente, sino mucho más ahora en mi ausencia, ocupaos en vuestra salvación con temor y temblor," },
{name:'50213',l:'50',c:'2',v:'13',texto:"porque Dios es el que en vosotros produce así el querer como el hacer, por su buena voluntad." },
{name:'50214',l:'50',c:'2',v:'14',texto:"Haced todo sin murmuraciones y contiendas," },
{name:'50215',l:'50',c:'2',v:'15',texto:"para que seáis irreprensibles y sencillos, hijos de Dios sin mancha en medio de una generación maligna y perversa, en medio de la cual resplandecéis como luminares en el mundo; " },
{name:'50216',l:'50',c:'2',v:'16',texto:"asidos de la palabra de vida, para que en el día de Cristo yo pueda gloriarme de que no he corrido en vano, ni en vano he trabajado." },
{name:'50217',l:'50',c:'2',v:'17',texto:"Y aunque sea derramado en libación sobre el sacrificio y servicio de vuestra fe, me gozo y regocijo con todos vosotros." },
{name:'50218',l:'50',c:'2',v:'18',texto:"Y asimismo gozaos y regocijaos también vosotros conmigo." },
{name:'50219',l:'50',c:'2',v:'19',texto:"Espero en el Señor Jesús enviaros pronto a Timoteo, para que yo también esté de buen ánimo al saber de vuestro estado; " },
{name:'50220',l:'50',c:'2',v:'20',texto:"pues a ninguno tengo del mismo ánimo, y que tan sinceramente se interese por vosotros." },
{name:'50221',l:'50',c:'2',v:'21',texto:"Porque todos buscan lo suyo propio, no lo que es de Cristo Jesús." },
{name:'50222',l:'50',c:'2',v:'22',texto:"Pero ya conocéis los méritos de él, que como hijo a padre ha servido conmigo en el evangelio." },
{name:'50223',l:'50',c:'2',v:'23',texto:"Así que a éste espero enviaros, luego que yo vea cómo van mis asuntos; " },
{name:'50224',l:'50',c:'2',v:'24',texto:"y confío en el Señor que yo también iré pronto a vosotros." },
{name:'50225',l:'50',c:'2',v:'25',texto:"Mas tuve por necesario enviaros a Epafrodito, mi hermano y colaborador y compañero de milicia, vuestro mensajero, y ministrador de mis necesidades; " },
{name:'50226',l:'50',c:'2',v:'26',texto:"porque él tenía gran deseo de veros a todos vosotros, y gravemente se angustió porque habíais oído que había enfermado." },
{name:'50227',l:'50',c:'2',v:'27',texto:"Pues en verdad estuvo enfermo, a punto de morir; pero Dios tuvo misericordia de él, y no solamente de él, sino también de mí, para que yo no tuviese tristeza sobre tristeza." },
{name:'50228',l:'50',c:'2',v:'28',texto:"Así que le envío con mayor solicitud, para que al verle de nuevo, os gocéis, y yo esté con menos tristeza." },
{name:'50229',l:'50',c:'2',v:'29',texto:"Recibidle, pues, en el Señor, con todo gozo, y tened en estima a los que son como él; " },
{name:'50230',l:'50',c:'2',v:'30',texto:"porque por la obra de Cristo estuvo próximo a la muerte, exponiendo su vida para suplir lo que faltaba en vuestro servicio por mí." },
],
numVersiculos: 30,
},

c3: {
versiculos:[
{name:'5031',l:'50',c:'3',v:'1',texto:"Por lo demás, hermanos, gozaos en el Señor. A mí no me es molesto el escribiros las mismas cosas, y para vosotros es seguro." },
{name:'5032',l:'50',c:'3',v:'2',texto:"Guardaos de los perros, guardaos de los malos obreros, guardaos de los mutiladores del cuerpo." },
{name:'5033',l:'50',c:'3',v:'3',texto:"Porque nosotros somos la circuncisión, los que en espíritu servimos a Dios y nos gloriamos en Cristo Jesús, no teniendo confianza en la carne." },
{name:'5034',l:'50',c:'3',v:'4',texto:"Aunque yo tengo también de qué confiar en la carne. Si alguno piensa que tiene de qué confiar en la carne, yo más: " },
{name:'5035',l:'50',c:'3',v:'5',texto:"circuncidado al octavo día, del linaje de Israel, de la tribu de Benjamín, hebreo de hebreos; en cuanto a la ley, fariseo; " },
{name:'5036',l:'50',c:'3',v:'6',texto:"en cuanto a celo, perseguidor de la iglesia; en cuanto a la justicia que es en la ley, irreprensible." },
{name:'5037',l:'50',c:'3',v:'7',texto:"Pero cuantas cosas eran para mí ganancia, las he estimado como pérdida por amor de Cristo." },
{name:'5038',l:'50',c:'3',v:'8',texto:"Y ciertamente, aun estimo todas las cosas como pérdida por la excelencia del conocimiento de Cristo Jesús, mi Señor, por amor del cual lo he perdido todo, y lo tengo por basura, para ganar a Cristo," },
{name:'5039',l:'50',c:'3',v:'9',texto:"y ser hallado en él, no teniendo mi propia justicia, que es por la ley, sino la que es por la fe de Cristo, la justicia que es de Dios por la fe; " },
{name:'50310',l:'50',c:'3',v:'10',texto:"a fin de conocerle, y el poder de su resurrección, y la participación de sus padecimientos, llegando a ser semejante a él en su muerte," },
{name:'50311',l:'50',c:'3',v:'11',texto:"si en alguna manera llegase a la resurrección de entre los muertos." },
{name:'50312',l:'50',c:'3',v:'12',texto:"No que lo haya alcanzado ya, ni que ya sea perfecto; sino que prosigo, por ver si logro asir aquello para lo cual fui también asido por Cristo Jesús." },
{name:'50313',l:'50',c:'3',v:'13',texto:"Hermanos, yo mismo no pretendo haberlo ya alcanzado; pero una cosa hago: olvidando ciertamente lo que queda atrás, y extendiéndome a lo que está delante," },
{name:'50314',l:'50',c:'3',v:'14',texto:"prosigo a la meta, al premio del supremo llamamiento de Dios en Cristo Jesús." },
{name:'50315',l:'50',c:'3',v:'15',texto:"Así que, todos los que somos perfectos, esto mismo sintamos; y si otra cosa sentís, esto también os lo revelará Dios." },
{name:'50316',l:'50',c:'3',v:'16',texto:"Pero en aquello a que hemos llegado, sigamos una misma regla, sintamos una misma cosa." },
{name:'50317',l:'50',c:'3',v:'17',texto:"Hermanos, sed imitadores de mí, y mirad a los que así se conducen según el ejemplo que tenéis en nosotros." },
{name:'50318',l:'50',c:'3',v:'18',texto:"Porque por ahí andan muchos, de los cuales os dije muchas veces, y aun ahora lo digo llorando, que son enemigos de la cruz de Cristo; " },
{name:'50319',l:'50',c:'3',v:'19',texto:"el fin de los cuales será perdición, cuyo dios es el vientre, y cuya gloria es su vergüenza; que sólo piensan en lo terrenal." },
{name:'50320',l:'50',c:'3',v:'20',texto:"Mas nuestra ciudadanía está en los cielos, de donde también esperamos al Salvador, al Señor Jesucristo; " },
{name:'50321',l:'50',c:'3',v:'21',texto:"el cual transformará el cuerpo de la humillación nuestra, para que sea semejante al cuerpo de la gloria suya, por el poder con el cual puede también sujetar a sí mismo todas las cosas." },
],
numVersiculos: 21,
},

c4: {
versiculos:[
{name:'5041',l:'50',c:'4',v:'1',texto:"Así que, hermanos míos amados y deseados, gozo y corona mía, estad así firmes en el Señor, amados." },
{name:'5042',l:'50',c:'4',v:'2',texto:"Ruego a Evodia y a Síntique, que sean de un mismo sentir en el Señor." },
{name:'5043',l:'50',c:'4',v:'3',texto:"Asimismo te ruego también a ti, compañero fiel, que ayudes a éstas que combatieron juntamente conmigo en el evangelio, con Clemente también y los demás colaboradores míos, cuyos nombres están en el libro de la vida." },
{name:'5044',l:'50',c:'4',v:'4',texto:"Regocijaos en el Señor siempre. Otra vez digo: ¡Regocijaos! " },
{name:'5045',l:'50',c:'4',v:'5',texto:"Vuestra gentileza sea conocida de todos los hombres. El Señor está cerca." },
{name:'5046',l:'50',c:'4',v:'6',texto:"Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con acción de gracias." },
{name:'5047',l:'50',c:'4',v:'7',texto:"Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús." },
{name:'5048',l:'50',c:'4',v:'8',texto:"Por lo demás, hermanos, todo lo que es verdadero, todo lo honesto, todo lo justo, todo lo puro, todo lo amable, todo lo que es de buen nombre; si hay virtud alguna, si algo digno de alabanza, en esto pensad." },
{name:'5049',l:'50',c:'4',v:'9',texto:"Lo que aprendisteis y recibisteis y oísteis y visteis en mí, esto haced; y el Dios de paz estará con vosotros." },
{name:'50410',l:'50',c:'4',v:'10',texto:"En gran manera me gocé en el Señor de que ya al fin habéis revivido vuestro cuidado de mí; de lo cual también estabais solícitos, pero os faltaba la oportunidad." },
{name:'50411',l:'50',c:'4',v:'11',texto:"No lo digo porque tenga escasez, pues he aprendido a contentarme, cualquiera que sea mi situación." },
{name:'50412',l:'50',c:'4',v:'12',texto:"Sé vivir humildemente, y sé tener abundancia; en todo y por todo estoy enseñado, así para estar saciado como para tener hambre, así para tener abundancia como para padecer necesidad." },
{name:'50413',l:'50',c:'4',v:'13',texto:"Todo lo puedo en Cristo que me fortalece." },
{name:'50414',l:'50',c:'4',v:'14',texto:"Sin embargo, bien hicisteis en participar conmigo en mi tribulación." },
{name:'50415',l:'50',c:'4',v:'15',texto:"Y sabéis también vosotros, oh filipenses, que al principio de la predicación del evangelio, cuando partí de Macedonia, ninguna iglesia participó conmigo en razón de dar y recibir, sino vosotros solos; " },
{name:'50416',l:'50',c:'4',v:'16',texto:"pues aun a Tesalónica me enviasteis una y otra vez para mis necesidades." },
{name:'50417',l:'50',c:'4',v:'17',texto:"No es que busque dádivas, sino que busco fruto que abunde en vuestra cuenta." },
{name:'50418',l:'50',c:'4',v:'18',texto:"Pero todo lo he recibido, y tengo abundancia; estoy lleno, habiendo recibido de Epafrodito lo que enviasteis; olor fragante, sacrificio acepto, agradable a Dios." },
{name:'50419',l:'50',c:'4',v:'19',texto:"Mi Dios, pues, suplirá todo lo que os falta conforme a sus riquezas en gloria en Cristo Jesús." },
{name:'50420',l:'50',c:'4',v:'20',texto:"Al Dios y Padre nuestro sea gloria por los siglos de los siglos. Amén." },
{name:'50421',l:'50',c:'4',v:'21',texto:"Saludad a todos los santos en Cristo Jesús. Los hermanos que están conmigo os saludan." },
{name:'50422',l:'50',c:'4',v:'22',texto:"Todos los santos os saludan, y especialmente los de la casa de César." },
{name:'50423',l:'50',c:'4',v:'23',texto:"La gracia de nuestro Señor Jesucristo sea con todos vosotros. Amén." },
],
numVersiculos: 23,
},


};
