BibliaRVR60.tesalonicenses1 = {
	libro: "1 Tesalonicenses",
	numCapitulos: 5,

c1: {
versiculos:[
{name:'5211',l:'52',c:'1',v:'1',texto:"Pablo, Silvano y Timoteo, a la iglesia de los tesalonicenses en Dios Padre y en el Señor Jesucristo: Gracia y paz sean a vosotros, de Dios nuestro Padre y del Señor Jesucristo." },
{name:'5212',l:'52',c:'1',v:'2',texto:"Damos siempre gracias a Dios por todos vosotros, haciendo memoria de vosotros en nuestras oraciones," },
{name:'5213',l:'52',c:'1',v:'3',texto:"acordándonos sin cesar delante del Dios y Padre nuestro de la obra de vuestra fe, del trabajo de vuestro amor y de vuestra constancia en la esperanza en nuestro Señor Jesucristo." },
{name:'5214',l:'52',c:'1',v:'4',texto:"Porque conocemos, hermanos amados de Dios, vuestra elección; " },
{name:'5215',l:'52',c:'1',v:'5',texto:"pues nuestro evangelio no llegó a vosotros en palabras solamente, sino también en poder, en el Espíritu Santo y en plena certidumbre, como bien sabéis cuáles fuimos entre vosotros por amor de vosotros." },
{name:'5216',l:'52',c:'1',v:'6',texto:"Y vosotros vinisteis a ser imitadores de nosotros y del Señor, recibiendo la palabra en medio de gran tribulación, con gozo del Espíritu Santo," },
{name:'5217',l:'52',c:'1',v:'7',texto:"de tal manera que habéis sido ejemplo a todos los de Macedonia y de Acaya que han creído." },
{name:'5218',l:'52',c:'1',v:'8',texto:"Porque partiendo de vosotros ha sido divulgada la palabra del Señor, no sólo en Macedonia y Acaya, sino que también en todo lugar vuestra fe en Dios se ha extendido, de modo que nosotros no tenemos necesidad de hablar nada; " },
{name:'5219',l:'52',c:'1',v:'9',texto:"porque ellos mismos cuentan de nosotros la manera en que nos recibisteis, y cómo os convertisteis de los ídolos a Dios, para servir al Dios vivo y verdadero," },
{name:'52110',l:'52',c:'1',v:'10',texto:"y esperar de los cielos a su Hijo, al cual resucitó de los muertos, a Jesús, quien nos libra de la ira venidera." },
],
numVersiculos: 10,
},

c2: {
versiculos:[
{name:'5221',l:'52',c:'2',v:'1',texto:"Porque vosotros mismos sabéis, hermanos, que nuestra visita a vosotros no resultó vana; " },
{name:'5222',l:'52',c:'2',v:'2',texto:"pues habiendo antes padecido y sido ultrajados en Filipos, como sabéis, tuvimos denuedo en nuestro Dios para anunciaros el evangelio de Dios en medio de gran oposición." },
{name:'5223',l:'52',c:'2',v:'3',texto:"Porque nuestra exhortación no procedió de error ni de impureza, ni fue por engaño," },
{name:'5224',l:'52',c:'2',v:'4',texto:"sino que según fuimos aprobados por Dios para que se nos confiase el evangelio, así hablamos; no como para agradar a los hombres, sino a Dios, que prueba nuestros corazones." },
{name:'5225',l:'52',c:'2',v:'5',texto:"Porque nunca usamos de palabras lisonjeras, como sabéis, ni encubrimos avaricia; Dios es testigo; " },
{name:'5226',l:'52',c:'2',v:'6',texto:"ni buscamos gloria de los hombres; ni de vosotros, ni de otros, aunque podíamos seros carga como apóstoles de Cristo." },
{name:'5227',l:'52',c:'2',v:'7',texto:"Antes fuimos tiernos entre vosotros, como la nodriza que cuida con ternura a sus propios hijos." },
{name:'5228',l:'52',c:'2',v:'8',texto:"Tan grande es nuestro afecto por vosotros, que hubiéramos querido entregaros no sólo el evangelio de Dios, sino también nuestras propias vidas; porque habéis llegado a sernos muy queridos." },
{name:'5229',l:'52',c:'2',v:'9',texto:"Porque os acordáis, hermanos, de nuestro trabajo y fatiga; cómo trabajando de noche y de día, para no ser gravosos a ninguno de vosotros, os predicamos el evangelio de Dios." },
{name:'52210',l:'52',c:'2',v:'10',texto:"Vosotros sois testigos, y Dios también, de cuán santa, justa e irreprensiblemente nos comportamos con vosotros los creyentes; " },
{name:'52211',l:'52',c:'2',v:'11',texto:"así como también sabéis de qué modo, como el padre a sus hijos, exhortábamos y consolábamos a cada uno de vosotros," },
{name:'52212',l:'52',c:'2',v:'12',texto:"y os encargábamos que anduvieseis como es digno de Dios, que os llamó a su reino y gloria." },
{name:'52213',l:'52',c:'2',v:'13',texto:"Por lo cual también nosotros sin cesar damos gracias a Dios, de que cuando recibisteis la palabra de Dios que oísteis de nosotros, la recibisteis no como palabra de hombres, sino según es en verdad, la palabra de Dios, la cual actúa en vosotros los creyentes." },
{name:'52214',l:'52',c:'2',v:'14',texto:"Porque vosotros, hermanos, vinisteis a ser imitadores de las iglesias de Dios en Cristo Jesús que están en Judea; pues habéis padecido de los de vuestra propia nación las mismas cosas que ellas padecieron de los judíos," },
{name:'52215',l:'52',c:'2',v:'15',texto:"los cuales mataron al Señor Jesús y a sus propios profetas, y a nosotros nos expulsaron; y no agradan a Dios, y se oponen a todos los hombres," },
{name:'52216',l:'52',c:'2',v:'16',texto:"impidiéndonos hablar a los gentiles para que éstos se salven; así colman ellos siempre la medida de sus pecados, pues vino sobre ellos la ira hasta el extremo." },
{name:'52217',l:'52',c:'2',v:'17',texto:"Pero nosotros, hermanos, separados de vosotros por un poco de tiempo, de vista pero no de corazón, tanto más procuramos con mucho deseo ver vuestro rostro; " },
{name:'52218',l:'52',c:'2',v:'18',texto:"por lo cual quisimos ir a vosotros, yo Pablo ciertamente una y otra vez; pero Satanás nos estorbó." },
{name:'52219',l:'52',c:'2',v:'19',texto:"Porque ¿cuál es nuestra esperanza, o gozo, o corona de que me gloríe? ¿No lo sois vosotros, delante de nuestro Señor Jesucristo, en su venida? " },
{name:'52220',l:'52',c:'2',v:'20',texto:"Vosotros sois nuestra gloria y gozo." },
],
numVersiculos: 20,
},

c3: {
versiculos:[
{name:'5231',l:'52',c:'3',v:'1',texto:"Por lo cual, no pudiendo soportarlo más, acordamos quedarnos solos en Atenas," },
{name:'5232',l:'52',c:'3',v:'2',texto:"y enviamos a Timoteo nuestro hermano, servidor de Dios y colaborador nuestro en el evangelio de Cristo, para confirmaros y exhortaros respecto a vuestra fe," },
{name:'5233',l:'52',c:'3',v:'3',texto:"a fin de que nadie se inquiete por estas tribulaciones; porque vosotros mismos sabéis que para esto estamos puestos." },
{name:'5234',l:'52',c:'3',v:'4',texto:"Porque también estando con vosotros, os predecíamos que íbamos a pasar tribulaciones, como ha acontecido y sabéis." },
{name:'5235',l:'52',c:'3',v:'5',texto:"Por lo cual también yo, no pudiendo soportar más, envié para informarme de vuestra fe, no sea que os hubiese tentado el tentador, y que nuestro trabajo resultase en vano." },
{name:'5236',l:'52',c:'3',v:'6',texto:"Pero cuando Timoteo volvió de vosotros a nosotros, y nos dio buenas noticias de vuestra fe y amor, y que siempre nos recordáis con cariño, deseando vernos, como también nosotros a vosotros," },
{name:'5237',l:'52',c:'3',v:'7',texto:"por ello, hermanos, en medio de toda nuestra necesidad y aflicción fuimos consolados de vosotros por medio de vuestra fe; " },
{name:'5238',l:'52',c:'3',v:'8',texto:"porque ahora vivimos, si vosotros estáis firmes en el Señor." },
{name:'5239',l:'52',c:'3',v:'9',texto:"Por lo cual, ¿qué acción de gracias podremos dar a Dios por vosotros, por todo el gozo con que nos gozamos a causa de vosotros delante de nuestro Dios," },
{name:'52310',l:'52',c:'3',v:'10',texto:"orando de noche y de día con gran insistencia, para que veamos vuestro rostro, y completemos lo que falte a vuestra fe? " },
{name:'52311',l:'52',c:'3',v:'11',texto:"Mas el mismo Dios y Padre nuestro, y nuestro Señor Jesucristo, dirija nuestro camino a vosotros." },
{name:'52312',l:'52',c:'3',v:'12',texto:"Y el Señor os haga crecer y abundar en amor unos para con otros y para con todos, como también lo hacemos nosotros para con vosotros," },
{name:'52313',l:'52',c:'3',v:'13',texto:"para que sean afirmados vuestros corazones, irreprensibles en santidad delante de Dios nuestro Padre, en la venida de nuestro Señor Jesucristo con todos sus santos." },
],
numVersiculos: 13,
},

c4: {
versiculos:[
{name:'5241',l:'52',c:'4',v:'1',texto:"Por lo demás, hermanos, os rogamos y exhortamos en el Señor Jesús, que de la manera que aprendisteis de nosotros cómo os conviene conduciros y agradar a Dios, así abundéis más y más." },
{name:'5242',l:'52',c:'4',v:'2',texto:"Porque ya sabéis qué instrucciones os dimos por el Señor Jesús; " },
{name:'5243',l:'52',c:'4',v:'3',texto:"pues la voluntad de Dios es vuestra santificación; que os apartéis de fornicación; " },
{name:'5244',l:'52',c:'4',v:'4',texto:"que cada uno de vosotros sepa tener su propia esposa en santidad y honor; " },
{name:'5245',l:'52',c:'4',v:'5',texto:"no en pasión de concupiscencia, como los gentiles que no conocen a Dios; " },
{name:'5246',l:'52',c:'4',v:'6',texto:"que ninguno agravie ni engañe en nada a su hermano; porque el Señor es vengador de todo esto, como ya os hemos dicho y testificado." },
{name:'5247',l:'52',c:'4',v:'7',texto:"Pues no nos ha llamado Dios a inmundicia, sino a santificación." },
{name:'5248',l:'52',c:'4',v:'8',texto:"Así que, el que desecha esto, no desecha a hombre, sino a Dios, que también nos dio su Espíritu Santo." },
{name:'5249',l:'52',c:'4',v:'9',texto:"Pero acerca del amor fraternal no tenéis necesidad de que os escriba, porque vosotros mismos habéis aprendido de Dios que os améis unos a otros; " },
{name:'52410',l:'52',c:'4',v:'10',texto:"y también lo hacéis así con todos los hermanos que están por toda Macedonia. Pero os rogamos, hermanos, que abundéis en ello más y más; " },
{name:'52411',l:'52',c:'4',v:'11',texto:"y que procuréis tener tranquilidad, y ocuparos en vuestros negocios, y trabajar con vuestras manos de la manera que os hemos mandado," },
{name:'52412',l:'52',c:'4',v:'12',texto:"a fin de que os conduzcáis honradamente para con los de afuera, y no tengáis necesidad de nada." },
{name:'52413',l:'52',c:'4',v:'13',texto:"Tampoco queremos, hermanos, que ignoréis acerca de los que duermen, para que no os entristezcáis como los otros que no tienen esperanza." },
{name:'52414',l:'52',c:'4',v:'14',texto:"Porque si creemos que Jesús murió y resucitó, así también traerá Dios con Jesús a los que durmieron en él." },
{name:'52415',l:'52',c:'4',v:'15',texto:"Por lo cual os decimos esto en palabra del Señor: que nosotros que vivimos, que habremos quedado hasta la venida del Señor, no precederemos a los que durmieron." },
{name:'52416',l:'52',c:'4',v:'16',texto:"Porque el Señor mismo con voz de mando, con voz de arcángel, y con trompeta de Dios, descenderá del cielo; y los muertos en Cristo resucitarán primero." },
{name:'52417',l:'52',c:'4',v:'17',texto:"Luego nosotros los que vivimos, los que hayamos quedado, seremos arrebatados juntamente con ellos en las nubes para recibir al Señor en el aire, y así estaremos siempre con el Señor." },
{name:'52418',l:'52',c:'4',v:'18',texto:"Por tanto, alentaos los unos a los otros con estas palabras." },
],
numVersiculos: 18,
},

c5: {
versiculos:[
{name:'5251',l:'52',c:'5',v:'1',texto:"Pero acerca de los tiempos y de las ocasiones, no tenéis necesidad, hermanos, de que yo os escriba." },
{name:'5252',l:'52',c:'5',v:'2',texto:"Porque vosotros sabéis perfectamente que el día del Señor vendrá así como ladrón en la noche; " },
{name:'5253',l:'52',c:'5',v:'3',texto:"que cuando digan: Paz y seguridad, entonces vendrá sobre ellos destrucción repentina, como los dolores a la mujer encinta, y no escaparán." },
{name:'5254',l:'52',c:'5',v:'4',texto:"Mas vosotros, hermanos, no estáis en tinieblas, para que aquel día os sorprenda como ladrón." },
{name:'5255',l:'52',c:'5',v:'5',texto:"Porque todos vosotros sois hijos de luz e hijos del día; no somos de la noche ni de las tinieblas." },
{name:'5256',l:'52',c:'5',v:'6',texto:"Por tanto, no durmamos como los demás, sino velemos y seamos sobrios." },
{name:'5257',l:'52',c:'5',v:'7',texto:"Pues los que duermen, de noche duermen, y los que se embriagan, de noche se embriagan." },
{name:'5258',l:'52',c:'5',v:'8',texto:"Pero nosotros, que somos del día, seamos sobrios, habiéndonos vestido con la coraza de fe y de amor, y con la esperanza de salvación como yelmo." },
{name:'5259',l:'52',c:'5',v:'9',texto:"Porque no nos ha puesto Dios para ira, sino para alcanzar salvación por medio de nuestro Señor Jesucristo," },
{name:'52510',l:'52',c:'5',v:'10',texto:"quien murió por nosotros para que ya sea que velemos, o que durmamos, vivamos juntamente con él." },
{name:'52511',l:'52',c:'5',v:'11',texto:"Por lo cual, animaos unos a otros, y edificaos unos a otros, así como lo hacéis." },
{name:'52512',l:'52',c:'5',v:'12',texto:"Os rogamos, hermanos, que reconozcáis a los que trabajan entre vosotros, y os presiden en el Señor, y os amonestan; " },
{name:'52513',l:'52',c:'5',v:'13',texto:"y que los tengáis en mucha estima y amor por causa de su obra. Tened paz entre vosotros." },
{name:'52514',l:'52',c:'5',v:'14',texto:"También os rogamos, hermanos, que amonestéis a los ociosos, que alentéis a los de poco ánimo, que sostengáis a los débiles, que seáis pacientes para con todos." },
{name:'52515',l:'52',c:'5',v:'15',texto:"Mirad que ninguno pague a otro mal por mal; antes seguid siempre lo bueno unos para con otros, y para con todos." },
{name:'52516',l:'52',c:'5',v:'16',texto:"Estad siempre gozosos." },
{name:'52517',l:'52',c:'5',v:'17',texto:"Orad sin cesar." },
{name:'52518',l:'52',c:'5',v:'18',texto:"Dad gracias en todo, porque esta es la voluntad de Dios para con vosotros en Cristo Jesús." },
{name:'52519',l:'52',c:'5',v:'19',texto:"No apaguéis al Espíritu." },
{name:'52520',l:'52',c:'5',v:'20',texto:"No menospreciéis las profecías." },
{name:'52521',l:'52',c:'5',v:'21',texto:"Examinadlo todo; retened lo bueno." },
{name:'52522',l:'52',c:'5',v:'22',texto:"Absteneos de toda especie de mal." },
{name:'52523',l:'52',c:'5',v:'23',texto:"Y el mismo Dios de paz os santifique por completo; y todo vuestro ser, espíritu, alma y cuerpo, sea guardado irreprensible para la venida de nuestro Señor Jesucristo." },
{name:'52524',l:'52',c:'5',v:'24',texto:"Fiel es el que os llama, el cual también lo hará." },
{name:'52525',l:'52',c:'5',v:'25',texto:"Hermanos, orad por nosotros." },
{name:'52526',l:'52',c:'5',v:'26',texto:"Saludad a todos los hermanos con ósculo santo." },
{name:'52527',l:'52',c:'5',v:'27',texto:"Os conjuro por el Señor, que esta carta se lea a todos los santos hermanos." },
{name:'52528',l:'52',c:'5',v:'28',texto:"La gracia de nuestro Señor Jesucristo sea con vosotros. Amén." },
],
numVersiculos: 28,
},
	

};
