BibliaRVR60.timoteo1 = {
	libro: "1 Timoteo",
	numCapitulos: 6,

c1: {
versiculos:[
{name:'5411',l:'54',c:'1',v:'1',texto:"Pablo, apóstol de Jesucristo por mandato de Dios nuestro Salvador, y del Señor Jesucristo nuestra esperanza," },
{name:'5412',l:'54',c:'1',v:'2',texto:"a Timoteo, verdadero hijo en la fe: Gracia, misericordia y paz, de Dios nuestro Padre y de Cristo Jesús nuestro Señor." },
{name:'5413',l:'54',c:'1',v:'3',texto:"Como te rogué que te quedases en Efeso, cuando fui a Macedonia, para que mandases a algunos que no enseñen diferente doctrina," },
{name:'5414',l:'54',c:'1',v:'4',texto:"ni presten atención a fábulas y genealogías interminables, que acarrean disputas más bien que edificación de Dios que es por fe, así te encargo ahora." },
{name:'5415',l:'54',c:'1',v:'5',texto:"Pues el propósito de este mandamiento es el amor nacido de corazón limpio, y de buena conciencia, y de fe no fingida," },
{name:'5416',l:'54',c:'1',v:'6',texto:"de las cuales cosas desviándose algunos, se apartaron a vana palabrería," },
{name:'5417',l:'54',c:'1',v:'7',texto:"queriendo ser doctores de la ley, sin entender ni lo que hablan ni lo que afirman." },
{name:'5418',l:'54',c:'1',v:'8',texto:"Pero sabemos que la ley es buena, si uno la usa legítimamente; " },
{name:'5419',l:'54',c:'1',v:'9',texto:"conociendo esto, que la ley no fue dada para el justo, sino para los transgresores y desobedientes, para los impíos y pecadores, para los irreverentes y profanos, para los parricidas y matricidas, para los homicidas," },
{name:'54110',l:'54',c:'1',v:'10',texto:"para los fornicarios, para los sodomitas, para los secuestradores, para los mentirosos y perjuros, y para cuanto se oponga a la sana doctrina," },
{name:'54111',l:'54',c:'1',v:'11',texto:"según el glorioso evangelio del Dios bendito, que a mí me ha sido encomendado." },
{name:'54112',l:'54',c:'1',v:'12',texto:"Doy gracias al que me fortaleció, a Cristo Jesús nuestro Señor, porque me tuvo por fiel, poniéndome en el ministerio," },
{name:'54113',l:'54',c:'1',v:'13',texto:"habiendo yo sido antes blasfemo, perseguidor e injuriador; mas fui recibido a misericordia porque lo hice por ignorancia, en incredulidad." },
{name:'54114',l:'54',c:'1',v:'14',texto:"Pero la gracia de nuestro Señor fue más abundante con la fe y el amor que es en Cristo Jesús." },
{name:'54115',l:'54',c:'1',v:'15',texto:"Palabra fiel y digna de ser recibida por todos: que Cristo Jesús vino al mundo para salvar a los pecadores, de los cuales yo soy el primero." },
{name:'54116',l:'54',c:'1',v:'16',texto:"Pero por esto fui recibido a misericordia, para que Jesucristo mostrase en mí el primero toda su clemencia, para ejemplo de los que habrían de creer en él para vida eterna." },
{name:'54117',l:'54',c:'1',v:'17',texto:"Por tanto, al Rey de los siglos, inmortal, invisible, al único y sabio Dios, sea honor y gloria por los siglos de los siglos. Amén." },
{name:'54118',l:'54',c:'1',v:'18',texto:"Este mandamiento, hijo Timoteo, te encargo, para que conforme a las profecías que se hicieron antes en cuanto a ti, milites por ellas la buena milicia," },
{name:'54119',l:'54',c:'1',v:'19',texto:"manteniendo la fe y buena conciencia, desechando la cual naufragaron en cuanto a la fe algunos," },
{name:'54120',l:'54',c:'1',v:'20',texto:"de los cuales son Himeneo y Alejandro, a quienes entregué a Satanás para que aprendan a no blasfemar." },
],
numVersiculos: 20,
},

c2: {
versiculos:[
{name:'5421',l:'54',c:'2',v:'1',texto:"Exhorto ante todo, a que se hagan rogativas, oraciones, peticiones y acciones de gracias, por todos los hombres; " },
{name:'5422',l:'54',c:'2',v:'2',texto:"por los reyes y por todos los que están en eminencia, para que vivamos quieta y reposadamente en toda piedad y honestidad." },
{name:'5423',l:'54',c:'2',v:'3',texto:"Porque esto es bueno y agradable delante de Dios nuestro Salvador," },
{name:'5424',l:'54',c:'2',v:'4',texto:"el cual quiere que todos los hombres sean salvos y vengan al conocimiento de la verdad." },
{name:'5425',l:'54',c:'2',v:'5',texto:"Porque hay un solo Dios, y un solo mediador entre Dios y los hombres, Jesucristo hombre," },
{name:'5426',l:'54',c:'2',v:'6',texto:"el cual se dio a sí mismo en rescate por todos, de lo cual se dio testimonio a su debido tiempo." },
{name:'5427',l:'54',c:'2',v:'7',texto:"Para esto yo fui constituido predicador y apóstol (digo verdad en Cristo, no miento), y maestro de los gentiles en fe y verdad." },
{name:'5428',l:'54',c:'2',v:'8',texto:"Quiero, pues, que los hombres oren en todo lugar, levantando manos santas, sin ira ni contienda." },
{name:'5429',l:'54',c:'2',v:'9',texto:"Asimismo que las mujeres se atavíen de ropa decorosa, con pudor y modestia; no con peinado ostentoso, ni oro, ni perlas, ni vestidos costosos," },
{name:'54210',l:'54',c:'2',v:'10',texto:"sino con buenas obras, como corresponde a mujeres que profesan piedad." },
{name:'54211',l:'54',c:'2',v:'11',texto:"La mujer aprenda en silencio, con toda sujeción." },
{name:'54212',l:'54',c:'2',v:'12',texto:"Porque no permito a la mujer enseñar, ni ejercer dominio sobre el hombre, sino estar en silencio." },
{name:'54213',l:'54',c:'2',v:'13',texto:"Porque Adán fue formado primero, después Eva; " },
{name:'54214',l:'54',c:'2',v:'14',texto:"y Adán no fue engañado, sino que la mujer, siendo engañada, incurrió en transgresión." },
{name:'54215',l:'54',c:'2',v:'15',texto:"Pero se salvará engendrando hijos, si permaneciere en fe, amor y santificación, con modestia." },
],
numVersiculos: 15,
},

c3: {
versiculos:[
{name:'5431',l:'54',c:'3',v:'1',texto:"Palabra fiel: Si alguno anhela obispado, buena obra desea." },
{name:'5432',l:'54',c:'3',v:'2',texto:"Pero es necesario que el obispo sea irreprensible, marido de una sola mujer, sobrio, prudente, decoroso, hospedador, apto para enseñar; " },
{name:'5433',l:'54',c:'3',v:'3',texto:"no dado al vino, no pendenciero, no codicioso de ganancias deshonestas, sino amable, apacible, no avaro; " },
{name:'5434',l:'54',c:'3',v:'4',texto:"que gobierne bien su casa, que tenga a sus hijos en sujeción con toda honestidad " },
{name:'5435',l:'54',c:'3',v:'5',texto:"(pues el que no sabe gobernar su propia casa, ¿cómo cuidará de la iglesia de Dios?); " },
{name:'5436',l:'54',c:'3',v:'6',texto:"no un neófito, no sea que envaneciéndose caiga en la condenación del diablo." },
{name:'5437',l:'54',c:'3',v:'7',texto:"También es necesario que tenga buen testimonio de los de afuera, para que no caiga en descrédito y en lazo del diablo." },
{name:'5438',l:'54',c:'3',v:'8',texto:"Los diáconos asimismo deben ser honestos, sin doblez, no dados a mucho vino, no codiciosos de ganancias deshonestas; " },
{name:'5439',l:'54',c:'3',v:'9',texto:"que guarden el misterio de la fe con limpia conciencia." },
{name:'54310',l:'54',c:'3',v:'10',texto:"Y éstos también sean sometidos a prueba primero, y entonces ejerzan el diaconado, si son irreprensibles." },
{name:'54311',l:'54',c:'3',v:'11',texto:"Las mujeres asimismo sean honestas, no calumniadoras, sino sobrias, fieles en todo." },
{name:'54312',l:'54',c:'3',v:'12',texto:"Los diáconos sean maridos de una sola mujer, y que gobiernen bien sus hijos y sus casas." },
{name:'54313',l:'54',c:'3',v:'13',texto:"Porque los que ejerzan bien el diaconado, ganan para sí un grado honroso, y mucha confianza en la fe que es en Cristo Jesús." },
{name:'54314',l:'54',c:'3',v:'14',texto:"Esto te escribo, aunque tengo la esperanza de ir pronto a verte," },
{name:'54315',l:'54',c:'3',v:'15',texto:"para que si tardo, sepas cómo debes conducirte en la casa de Dios, que es la iglesia del Dios viviente, columna y baluarte de la verdad." },
{name:'54316',l:'54',c:'3',v:'16',texto:"E indiscutiblemente, grande es el misterio de la piedad: Dios fue manifestado en carne, Justificado en el Espíritu, Visto de los ángeles, Predicado a los gentiles, Creído en el mundo, Recibido arriba en gloria." },
],
numVersiculos: 16,
},

c4: {
versiculos:[
{name:'5441',l:'54',c:'4',v:'1',texto:"Pero el Espíritu dice claramente que en los postreros tiempos algunos apostatarán de la fe, escuchando a espíritus engañadores y a doctrinas de demonios; " },
{name:'5442',l:'54',c:'4',v:'2',texto:"por la hipocresía de mentirosos que, teniendo cauterizada la conciencia," },
{name:'5443',l:'54',c:'4',v:'3',texto:"prohibirán casarse, y mandarán abstenerse de alimentos que Dios creó para que con acción de gracias participasen de ellos los creyentes y los que han conocido la verdad." },
{name:'5444',l:'54',c:'4',v:'4',texto:"Porque todo lo que Dios creó es bueno, y nada es de desecharse, si se toma con acción de gracias; " },
{name:'5445',l:'54',c:'4',v:'5',texto:"porque por la palabra de Dios y por la oración es santificado." },
{name:'5446',l:'54',c:'4',v:'6',texto:"Si esto enseñas a los hermanos, serás buen ministro de Jesucristo, nutrido con las palabras de la fe y de la buena doctrina que has seguido." },
{name:'5447',l:'54',c:'4',v:'7',texto:"Desecha las fábulas profanas y de viejas. Ejercítate para la piedad; " },
{name:'5448',l:'54',c:'4',v:'8',texto:"porque el ejercicio corporal para poco es provechoso, pero la piedad para todo aprovecha, pues tiene promesa de esta vida presente, y de la venidera." },
{name:'5449',l:'54',c:'4',v:'9',texto:"Palabra fiel es esta, y digna de ser recibida por todos." },
{name:'54410',l:'54',c:'4',v:'10',texto:"que por esto mismo trabajamos y sufrimos oprobios, porque esperamos en el Dios viviente, que es el Salvador de todos los hombres, mayormente de los que creen." },
{name:'54411',l:'54',c:'4',v:'11',texto:"Esto manda y enseña." },
{name:'54412',l:'54',c:'4',v:'12',texto:"Ninguno tenga en poco tu juventud, sino sé ejemplo de los creyentes en palabra, conducta, amor, espíritu, fe y pureza." },
{name:'54413',l:'54',c:'4',v:'13',texto:"Entre tanto que voy, ocúpate en la lectura, la exhortación y la enseñanza." },
{name:'54414',l:'54',c:'4',v:'14',texto:"No descuides el don que hay en ti, que te fue dado mediante profecía con la imposición de las manos del presbiterio." },
{name:'54415',l:'54',c:'4',v:'15',texto:"Ocúpate en estas cosas; permanece en ellas, para que tu aprovechamiento sea manifiesto a todos." },
{name:'54416',l:'54',c:'4',v:'16',texto:"Ten cuidado de ti mismo y de la doctrina; persiste en ello, pues haciendo esto, te salvarás a ti mismo y a los que te oyeren." },
],
numVersiculos: 16,
},

c5: {
versiculos:[
{name:'5451',l:'54',c:'5',v:'1',texto:"No reprendas al anciano, sino exhórtale como a padre; a los más jóvenes, como a hermanos; " },
{name:'5452',l:'54',c:'5',v:'2',texto:"a las ancianas, como a madres; a las jovencitas, como a hermanas, con toda pureza." },
{name:'5453',l:'54',c:'5',v:'3',texto:"Honra a las viudas que en verdad lo son." },
{name:'5454',l:'54',c:'5',v:'4',texto:"Pero si alguna viuda tiene hijos, o nietos, aprendan éstos primero a ser piadosos para con su propia familia, y a recompensar a sus padres; porque esto es lo bueno y agradable delante de Dios." },
{name:'5455',l:'54',c:'5',v:'5',texto:"Mas la que en verdad es viuda y ha quedado sola, espera en Dios, y es diligente en súplicas y oraciones noche y día." },
{name:'5456',l:'54',c:'5',v:'6',texto:"Pero la que se entrega a los placeres, viviendo está muerta." },
{name:'5457',l:'54',c:'5',v:'7',texto:"Manda también estas cosas, para que sean irreprensibles; " },
{name:'5458',l:'54',c:'5',v:'8',texto:"porque si alguno no provee para los suyos, y mayormente para los de su casa, ha negado la fe, y es peor que un incrédulo." },
{name:'5459',l:'54',c:'5',v:'9',texto:"Sea puesta en la lista sólo la viuda no menor de sesenta años, que haya sido esposa de un solo marido," },
{name:'54510',l:'54',c:'5',v:'10',texto:"que tenga testimonio de buenas obras; si ha criado hijos; si ha practicado la hospitalidad; si ha lavado los pies de los santos; si ha socorrido a los afligidos; si ha practicado toda buena obra." },
{name:'54511',l:'54',c:'5',v:'11',texto:"Pero viudas más jóvenes no admitas; porque cuando, impulsadas por sus deseos, se rebelan contra Cristo, quieren casarse," },
{name:'54512',l:'54',c:'5',v:'12',texto:"incurriendo así en condenación, por haber quebrantado su primera fe." },
{name:'54513',l:'54',c:'5',v:'13',texto:"Y también aprenden a ser ociosas, andando de casa en casa; y no solamente ociosas, sino también chismosas y entremetidas, hablando lo que no debieran." },
{name:'54514',l:'54',c:'5',v:'14',texto:"Quiero, pues, que las viudas jóvenes se casen, críen hijos, gobiernen su casa; que no den al adversario ninguna ocasión de maledicencia." },
{name:'54515',l:'54',c:'5',v:'15',texto:"Porque ya algunas se han apartado en pos de Satanás." },
{name:'54516',l:'54',c:'5',v:'16',texto:"Si algún creyente o alguna creyente tiene viudas, que las mantenga, y no sea gravada la iglesia, a fin de que haya lo suficiente para las que en verdad son viudas." },
{name:'54517',l:'54',c:'5',v:'17',texto:"Los ancianos que gobiernan bien, sean tenidos por dignos de doble honor, mayormente los que trabajan en predicar y enseñar." },
{name:'54518',l:'54',c:'5',v:'18',texto:"Pues la Escritura dice: No pondrás bozal al buey que trilla; y: Digno es el obrero de su salario." },
{name:'54519',l:'54',c:'5',v:'19',texto:"Contra un anciano no admitas acusación sino con dos o tres testigos." },
{name:'54520',l:'54',c:'5',v:'20',texto:"A los que persisten en pecar, repréndelos delante de todos, para que los demás también teman." },
{name:'54521',l:'54',c:'5',v:'21',texto:"Te encarezco delante de Dios y del Señor Jesucristo, y de sus ángeles escogidos, que guardes estas cosas sin prejuicios, no haciendo nada con parcialidad." },
{name:'54522',l:'54',c:'5',v:'22',texto:"No impongas con ligereza las manos a ninguno, ni participes en pecados ajenos. Consérvate puro." },
{name:'54523',l:'54',c:'5',v:'23',texto:"Ya no bebas agua, sino usa de un poco de vino por causa de tu estómago y de tus frecuentes enfermedades." },
{name:'54524',l:'54',c:'5',v:'24',texto:"Los pecados de algunos hombres se hacen patentes antes que ellos vengan a juicio, mas a otros se les descubren después." },
{name:'54525',l:'54',c:'5',v:'25',texto:"Asimismo se hacen manifiestas las buenas obras; y las que son de otra manera, no pueden permanecer ocultas." },
],
numVersiculos: 25,
},

c6: {
versiculos:[
{name:'5461',l:'54',c:'6',v:'1',texto:"Todos los que están bajo el yugo de esclavitud, tengan a sus amos por dignos de todo honor, para que no sea blasfemado el nombre de Dios y la doctrina." },
{name:'5462',l:'54',c:'6',v:'2',texto:"Y los que tienen amos creyentes, no los tengan en menos por ser hermanos, sino sírvanles mejor, por cuanto son creyentes y amados los que se benefician de su buen servicio. Esto enseña y exhorta." },
{name:'5463',l:'54',c:'6',v:'3',texto:"Si alguno enseña otra cosa, y no se conforma a las sanas palabras de nuestro Señor Jesucristo, y a la doctrina que es conforme a la piedad," },
{name:'5464',l:'54',c:'6',v:'4',texto:"está envanecido, nada sabe, y delira acerca de cuestiones y contiendas de palabras, de las cuales nacen envidias, pleitos, blasfemias, malas sospechas," },
{name:'5465',l:'54',c:'6',v:'5',texto:"disputas necias de hombres corruptos de entendimiento y privados de la verdad, que toman la piedad como fuente de ganancia; apártate de los tales." },
{name:'5466',l:'54',c:'6',v:'6',texto:"Pero gran ganancia es la piedad acompañada de contentamiento; " },
{name:'5467',l:'54',c:'6',v:'7',texto:"porque nada hemos traído a este mundo, y sin duda nada podremos sacar." },
{name:'5468',l:'54',c:'6',v:'8',texto:"Así que, teniendo sustento y abrigo, estemos contentos con esto." },
{name:'5469',l:'54',c:'6',v:'9',texto:"Porque los que quieren enriquecerse caen en tentación y lazo, y en muchas codicias necias y dañosas, que hunden a los hombres en destrucción y perdición; " },
{name:'54610',l:'54',c:'6',v:'10',texto:"porque raíz de todos los males es el amor al dinero, el cual codiciando algunos, se extraviaron de la fe, y fueron traspasados de muchos dolores." },
{name:'54611',l:'54',c:'6',v:'11',texto:"Mas tú, oh hombre de Dios, huye de estas cosas, y sigue la justicia, la piedad, la fe, el amor, la paciencia, la mansedumbre." },
{name:'54612',l:'54',c:'6',v:'12',texto:"Pelea la buena batalla de la fe, echa mano de la vida eterna, a la cual asimismo fuiste llamado, habiendo hecho la buena profesión delante de muchos testigos." },
{name:'54613',l:'54',c:'6',v:'13',texto:"Te mando delante de Dios, que da vida a todas las cosas, y de Jesucristo, que dio testimonio de la buena profesión delante de Poncio Pilato," },
{name:'54614',l:'54',c:'6',v:'14',texto:"que guardes el mandamiento sin mácula ni reprensión, hasta la aparición de nuestro Señor Jesucristo," },
{name:'54615',l:'54',c:'6',v:'15',texto:"la cual a su tiempo mostrará el bienaventurado y solo Soberano, Rey de reyes, y Señor de señores," },
{name:'54616',l:'54',c:'6',v:'16',texto:"el único que tiene inmortalidad, que habita en luz inaccesible; a quien ninguno de los hombres ha visto ni puede ver, al cual sea la honra y el imperio sempiterno. Amén." },
{name:'54617',l:'54',c:'6',v:'17',texto:"A los ricos de este siglo manda que no sean altivos, ni pongan la esperanza en las riquezas, las cuales son inciertas, sino en el Dios vivo, que nos da todas las cosas en abundancia para que las disfrutemos." },
{name:'54618',l:'54',c:'6',v:'18',texto:"Que hagan bien, que sean ricos en buenas obras, dadivosos, generosos; " },
{name:'54619',l:'54',c:'6',v:'19',texto:"atesorando para sí buen fundamento para lo por venir, que echen mano de la vida eterna." },
{name:'54620',l:'54',c:'6',v:'20',texto:"Oh Timoteo, guarda lo que se te ha encomendado, evitando las profanas pláticas sobre cosas vanas, y los argumentos de la falsamente llamada ciencia," },
{name:'54621',l:'54',c:'6',v:'21',texto:"la cual profesando algunos, se desviaron de la fe. La gracia sea contigo. Amén." },
],
numVersiculos: 21,
},
	

};
