BibliaRVR60.timoteo2 = {
	libro: "2 Timoteo",
	numCapitulos: 4,

c1: {
versiculos:[
{name:'5511',l:'55',c:'1',v:'1',texto:"Pablo, apóstol de Jesucristo por la voluntad de Dios, según la promesa de la vida que es en Cristo Jesús," },
{name:'5512',l:'55',c:'1',v:'2',texto:"a Timoteo, amado hijo: Gracia, misericordia y paz, de Dios Padre y de Jesucristo nuestro Señor." },
{name:'5513',l:'55',c:'1',v:'3',texto:"Doy gracias a Dios, al cual sirvo desde mis mayores con limpia conciencia, de que sin cesar me acuerdo de ti en mis oraciones noche y día; " },
{name:'5514',l:'55',c:'1',v:'4',texto:"deseando verte, al acordarme de tus lágrimas, para llenarme de gozo; " },
{name:'5515',l:'55',c:'1',v:'5',texto:"trayendo a la memoria la fe no fingida que hay en ti, la cual habitó primero en tu abuela Loida, y en tu madre Eunice, y estoy seguro que en ti también." },
{name:'5516',l:'55',c:'1',v:'6',texto:"Por lo cual te aconsejo que avives el fuego del don de Dios que está en ti por la imposición de mis manos." },
{name:'5517',l:'55',c:'1',v:'7',texto:"Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio." },
{name:'5518',l:'55',c:'1',v:'8',texto:"Por tanto, no te avergüences de dar testimonio de nuestro Señor, ni de mí, preso suyo, sino participa de las aflicciones por el evangelio según el poder de Dios," },
{name:'5519',l:'55',c:'1',v:'9',texto:"quien nos salvó y llamó con llamamiento santo, no conforme a nuestras obras, sino según el propósito suyo y la gracia que nos fue dada en Cristo Jesús antes de los tiempos de los siglos," },
{name:'55110',l:'55',c:'1',v:'10',texto:"pero que ahora ha sido manifestada por la aparición de nuestro Salvador Jesucristo, el cual quitó la muerte y sacó a luz la vida y la inmortalidad por el evangelio," },
{name:'55111',l:'55',c:'1',v:'11',texto:"del cual yo fui constituido predicador, apóstol y maestro de los gentiles." },
{name:'55112',l:'55',c:'1',v:'12',texto:"Por lo cual asimismo padezco esto; pero no me avergüenzo, porque yo sé a quién he creído, y estoy seguro que es poderoso para guardar mi depósito para aquel día." },
{name:'55113',l:'55',c:'1',v:'13',texto:"Retén la forma de las sanas palabras que de mí oíste, en la fe y amor que es en Cristo Jesús." },
{name:'55114',l:'55',c:'1',v:'14',texto:"Guarda el buen depósito por el Espíritu Santo que mora en nosotros." },
{name:'55115',l:'55',c:'1',v:'15',texto:"Ya sabes esto, que me abandonaron todos los que están en Asia, de los cuales son Figelo y Hermógenes." },
{name:'55116',l:'55',c:'1',v:'16',texto:"Tenga el Señor misericordia de la casa de Onesíforo, porque muchas veces me confortó, y no se avergonzó de mis cadenas," },
{name:'55117',l:'55',c:'1',v:'17',texto:"sino que cuando estuvo en Roma, me buscó solícitamente y me halló." },
{name:'55118',l:'55',c:'1',v:'18',texto:"Concédale el Señor que halle misericordia cerca del Señor en aquel día. Y cuánto nos ayudó en Efeso, tú lo sabes mejor." },
],
numVersiculos: 18,
},

c2: {
versiculos:[
{name:'5521',l:'55',c:'2',v:'1',texto:"Tú, pues, hijo mío, esfuérzate en la gracia que es en Cristo Jesús." },
{name:'5522',l:'55',c:'2',v:'2',texto:"Lo que has oído de mí ante muchos testigos, esto encarga a hombres fieles que sean idóneos para enseñar también a otros." },
{name:'5523',l:'55',c:'2',v:'3',texto:"Tú, pues, sufre penalidades como buen soldado de Jesucristo." },
{name:'5524',l:'55',c:'2',v:'4',texto:"Ninguno que milita se enreda en los negocios de la vida, a fin de agradar a aquel que lo tomó por soldado." },
{name:'5525',l:'55',c:'2',v:'5',texto:"Y también el que lucha como atleta, no es coronado si no lucha legítimamente." },
{name:'5526',l:'55',c:'2',v:'6',texto:"El labrador, para participar de los frutos, debe trabajar primero." },
{name:'5527',l:'55',c:'2',v:'7',texto:"Considera lo que digo, y el Señor te dé entendimiento en todo." },
{name:'5528',l:'55',c:'2',v:'8',texto:"Acuérdate de Jesucristo, del linaje de David, resucitado de los muertos conforme a mi evangelio," },
{name:'5529',l:'55',c:'2',v:'9',texto:"en el cual sufro penalidades, hasta prisiones a modo de malhechor; mas la palabra de Dios no está presa." },
{name:'55210',l:'55',c:'2',v:'10',texto:"Por tanto, todo lo soporto por amor de los escogidos, para que ellos también obtengan la salvación que es en Cristo Jesús con gloria eterna." },
{name:'55211',l:'55',c:'2',v:'11',texto:"Palabra fiel es esta: Si somos muertos con él, también viviremos con él; " },
{name:'55212',l:'55',c:'2',v:'12',texto:"Si sufrimos, también reinaremos con él; Si le negáremos, él también nos negará." },
{name:'55213',l:'55',c:'2',v:'13',texto:"Si fuéremos infieles, él permanece fiel; El no puede negarse a sí mismo." },
{name:'55214',l:'55',c:'2',v:'14',texto:"Recuérdales esto, exhortándoles delante del Señor a que no contiendan sobre palabras, lo cual para nada aprovecha, sino que es para perdición de los oyentes." },
{name:'55215',l:'55',c:'2',v:'15',texto:"Procura con diligencia presentarte a Dios aprobado, como obrero que no tiene de qué avergonzarse, que usa bien la palabra de verdad." },
{name:'55216',l:'55',c:'2',v:'16',texto:"Mas evita profanas y vanas palabrerías, porque conducirán más y más a la impiedad." },
{name:'55217',l:'55',c:'2',v:'17',texto:"Y su palabra carcomerá como gangrena; de los cuales son Himeneo y Fileto," },
{name:'55218',l:'55',c:'2',v:'18',texto:"que se desviaron de la verdad, diciendo que la resurrección ya se efectuó, y trastornan la fe de algunos." },
{name:'55219',l:'55',c:'2',v:'19',texto:"Pero el fundamento de Dios está firme, teniendo este sello: Conoce el Señor a los que son suyos; y: Apártese de iniquidad todo aquel que invoca el nombre de Cristo." },
{name:'55220',l:'55',c:'2',v:'20',texto:"Pero en una casa grande, no solamente hay utensilios de oro y de plata, sino también de madera y de barro; y unos son para usos honrosos, y otros para usos viles." },
{name:'55221',l:'55',c:'2',v:'21',texto:"Así que, si alguno se limpia de estas cosas, será instrumento para honra, santificado, útil al Señor, y dispuesto para toda buena obra." },
{name:'55222',l:'55',c:'2',v:'22',texto:"Huye también de las pasiones juveniles, y sigue la justicia, la fe, el amor y la paz, con los que de corazón limpio invocan al Señor." },
{name:'55223',l:'55',c:'2',v:'23',texto:"Pero desecha las cuestiones necias e insensatas, sabiendo que engendran contiendas." },
{name:'55224',l:'55',c:'2',v:'24',texto:"Porque el siervo del Señor no debe ser contencioso, sino amable para con todos, apto para enseñar, sufrido; " },
{name:'55225',l:'55',c:'2',v:'25',texto:"que con mansedumbre corrija a los que se oponen, por si quizá Dios les conceda que se arrepientan para conocer la verdad," },
{name:'55226',l:'55',c:'2',v:'26',texto:"y escapen del lazo del diablo, en que están cautivos a voluntad de él." },
],
numVersiculos: 26,
},

c3: {
versiculos:[
{name:'5531',l:'55',c:'3',v:'1',texto:"También debes saber esto: que en los postreros días vendrán tiempos peligrosos." },
{name:'5532',l:'55',c:'3',v:'2',texto:"Porque habrá hombres amadores de sí mismos, avaros, vanagloriosos, soberbios, blasfemos, desobedientes a los padres, ingratos, impíos," },
{name:'5533',l:'55',c:'3',v:'3',texto:"sin afecto natural, implacables, calumniadores, intemperantes, crueles, aborrecedores de lo bueno," },
{name:'5534',l:'55',c:'3',v:'4',texto:"traidores, impetuosos, infatuados, amadores de los deleites más que de Dios," },
{name:'5535',l:'55',c:'3',v:'5',texto:"que tendrán apariencia de piedad, pero negarán la eficacia de ella; a éstos evita." },
{name:'5536',l:'55',c:'3',v:'6',texto:"Porque de éstos son los que se meten en las casas y llevan cautivas a las mujercillas cargadas de pecados, arrastradas por diversas concupiscencias." },
{name:'5537',l:'55',c:'3',v:'7',texto:"Estas siempre están aprendiendo, y nunca pueden llegar al conocimiento de la verdad." },
{name:'5538',l:'55',c:'3',v:'8',texto:"Y de la manera que Janes y Jambres resistieron a Moisés, así también éstos resisten a la verdad; hombres corruptos de entendimiento, réprobos en cuanto a la fe." },
{name:'5539',l:'55',c:'3',v:'9',texto:"Mas no irán más adelante; porque su insensatez será manifiesta a todos, como también lo fue la de aquéllos." },
{name:'55310',l:'55',c:'3',v:'10',texto:"Pero tú has seguido mi doctrina, conducta, propósito, fe, longanimidad, amor, paciencia," },
{name:'55311',l:'55',c:'3',v:'11',texto:"persecuciones, padecimientos, como los que me sobrevinieron en Antioquía, en Iconio, en Listra; persecuciones que he sufrido, y de todas me ha librado el Señor." },
{name:'55312',l:'55',c:'3',v:'12',texto:"Y también todos los que quieren vivir piadosamente en Cristo Jesús padecerán persecución; " },
{name:'55313',l:'55',c:'3',v:'13',texto:"mas los malos hombres y los engañadores irán de mal en peor, engañando y siendo engañados." },
{name:'55314',l:'55',c:'3',v:'14',texto:"Pero persiste tú en lo que has aprendido y te persuadiste, sabiendo de quién has aprendido; " },
{name:'55315',l:'55',c:'3',v:'15',texto:"y que desde la niñez has sabido las Sagradas Escrituras, las cuales te pueden hacer sabio para la salvación por la fe que es en Cristo Jesús." },
{name:'55316',l:'55',c:'3',v:'16',texto:"Toda la Escritura es inspirada por Dios, y útil para enseñar, para redargüir, para corregir, para instruir en justicia," },
{name:'55317',l:'55',c:'3',v:'17',texto:"a fin de que el hombre de Dios sea perfecto, enteramente preparado para toda buena obra." },
],
numVersiculos: 17,
},

c4: {
versiculos:[
{name:'5541',l:'55',c:'4',v:'1',texto:"Te encarezco delante de Dios y del Señor Jesucristo, que juzgará a los vivos y a los muertos en su manifestación y en su reino," },
{name:'5542',l:'55',c:'4',v:'2',texto:"que prediques la palabra; que instes a tiempo y fuera de tiempo; redarguye, reprende, exhorta con toda paciencia y doctrina." },
{name:'5543',l:'55',c:'4',v:'3',texto:"Porque vendrá tiempo cuando no sufrirán la sana doctrina, sino que teniendo comezón de oír, se amontonarán maestros conforme a sus propias concupiscencias," },
{name:'5544',l:'55',c:'4',v:'4',texto:"y apartarán de la verdad el oído y se volverán a las fábulas." },
{name:'5545',l:'55',c:'4',v:'5',texto:"Pero tú sé sobrio en todo, soporta las aflicciones, haz obra de evangelista, cumple tu ministerio." },
{name:'5546',l:'55',c:'4',v:'6',texto:"Porque yo ya estoy para ser sacrificado, y el tiempo de mi partida está cercano." },
{name:'5547',l:'55',c:'4',v:'7',texto:"He peleado la buena batalla, he acabado la carrera, he guardado la fe." },
{name:'5548',l:'55',c:'4',v:'8',texto:"Por lo demás, me está guardada la corona de justicia, la cual me dará el Señor, juez justo, en aquel día; y no sólo a mí, sino también a todos los que aman su venida." },
{name:'5549',l:'55',c:'4',v:'9',texto:"Procura venir pronto a verme," },
{name:'55410',l:'55',c:'4',v:'10',texto:"porque Demas me ha desamparado, amando este mundo, y se ha ido a Tesalónica. Crescente fue a Galacia, y Tito a Dalmacia." },
{name:'55411',l:'55',c:'4',v:'11',texto:"Sólo Lucas está conmigo. Toma a Marcos y tráele contigo, porque me es útil para el ministerio." },
{name:'55412',l:'55',c:'4',v:'12',texto:"A Tíquico lo envié a Efeso." },
{name:'55413',l:'55',c:'4',v:'13',texto:"Trae, cuando vengas, el capote que dejé en Troas en casa de Carpo, y los libros, mayormente los pergaminos." },
{name:'55414',l:'55',c:'4',v:'14',texto:"Alejandro el calderero me ha causado muchos males; el Señor le pague conforme a sus hechos." },
{name:'55415',l:'55',c:'4',v:'15',texto:"Guárdate tú también de él, pues en gran manera se ha opuesto a nuestras palabras." },
{name:'55416',l:'55',c:'4',v:'16',texto:"En mi primera defensa ninguno estuvo a mi lado, sino que todos me desampararon; no les sea tomado en cuenta." },
{name:'55417',l:'55',c:'4',v:'17',texto:"Pero el Señor estuvo a mi lado, y me dio fuerzas, para que por mí fuese cumplida la predicación, y que todos los gentiles oyesen. Así fui librado de la boca del león." },
{name:'55418',l:'55',c:'4',v:'18',texto:"Y el Señor me librará de toda obra mala, y me preservará para su reino celestial. A él sea gloria por los siglos de los siglos. Amén." },
{name:'55419',l:'55',c:'4',v:'19',texto:"Saluda a Prisca y a Aquila, y a la casa de Onesíforo." },
{name:'55420',l:'55',c:'4',v:'20',texto:"Erasto se quedó en Corinto, y a Trófimo dejé en Mileto enfermo." },
{name:'55421',l:'55',c:'4',v:'21',texto:"Procura venir antes del invierno. Eubulo te saluda, y Pudente, Lino, Claudia y todos los hermanos." },
{name:'55422',l:'55',c:'4',v:'22',texto:"El Señor Jesucristo esté con tu espíritu. La gracia sea con vosotros. Amén." },
],
numVersiculos: 22,
},
	

};
