BibliaRVR60.santiago = {
	libro: "Santiago",
	numCapitulos: 5,

c1: {
versiculos:[
{name:'5911',l:'59',c:'1',v:'1',texto:"Santiago, siervo de Dios y del Señor Jesucristo, a las doce tribus que están en la dispersión: Salud." },
{name:'5912',l:'59',c:'1',v:'2',texto:"Hermanos míos, tened por sumo gozo cuando os halléis en diversas pruebas," },
{name:'5913',l:'59',c:'1',v:'3',texto:"sabiendo que la prueba de vuestra fe produce paciencia." },
{name:'5914',l:'59',c:'1',v:'4',texto:"Mas tenga la paciencia su obra completa, para que seáis perfectos y cabales, sin que os falte cosa alguna." },
{name:'5915',l:'59',c:'1',v:'5',texto:"Y si alguno de vosotros tiene falta de sabiduría, pídala a Dios, el cual da a todos abundantemente y sin reproche, y le será dada." },
{name:'5916',l:'59',c:'1',v:'6',texto:"Pero pida con fe, no dudando nada; porque el que duda es semejante a la onda del mar, que es arrastrada por el viento y echada de una parte a otra." },
{name:'5917',l:'59',c:'1',v:'7',texto:"No piense, pues, quien tal haga, que recibirá cosa alguna del Señor." },
{name:'5918',l:'59',c:'1',v:'8',texto:"El hombre de doble ánimo es inconstante en todos sus caminos." },
{name:'5919',l:'59',c:'1',v:'9',texto:"El hermano que es de humilde condición, gloríese en su exaltación; " },
{name:'59110',l:'59',c:'1',v:'10',texto:"pero el que es rico, en su humillación; porque él pasará como la flor de la hierba." },
{name:'59111',l:'59',c:'1',v:'11',texto:"Porque cuando sale el sol con calor abrasador, la hierba se seca, su flor se cae, y perece su hermosa apariencia; así también se marchitará el rico en todas sus empresas." },
{name:'59112',l:'59',c:'1',v:'12',texto:"Bienaventurado el varón que soporta la tentación; porque cuando haya resistido la prueba, recibirá la corona de vida, que Dios ha prometido a los que le aman." },
{name:'59113',l:'59',c:'1',v:'13',texto:"Cuando alguno es tentado, no diga que es tentado de parte de Dios; porque Dios no puede ser tentado por el mal, ni él tienta a nadie; " },
{name:'59114',l:'59',c:'1',v:'14',texto:"sino que cada uno es tentado, cuando de su propia concupiscencia es atraído y seducido." },
{name:'59115',l:'59',c:'1',v:'15',texto:"Entonces la concupiscencia, después que ha concebido, da a luz el pecado; y el pecado, siendo consumado, da a luz la muerte." },
{name:'59116',l:'59',c:'1',v:'16',texto:"Amados hermanos míos, no erréis." },
{name:'59117',l:'59',c:'1',v:'17',texto:"Toda buena dádiva y todo don perfecto desciende de lo alto, del Padre de las luces, en el cual no hay mudanza, ni sombra de variación." },
{name:'59118',l:'59',c:'1',v:'18',texto:"El, de su voluntad, nos hizo nacer por la palabra de verdad, para que seamos primicias de sus criaturas." },
{name:'59119',l:'59',c:'1',v:'19',texto:"Por esto, mis amados hermanos, todo hombre sea pronto para oír, tardo para hablar, tardo para airarse; " },
{name:'59120',l:'59',c:'1',v:'20',texto:"porque la ira del hombre no obra la justicia de Dios." },
{name:'59121',l:'59',c:'1',v:'21',texto:"Por lo cual, desechando toda inmundicia y abundancia de malicia, recibid con mansedumbre la palabra implantada, la cual puede salvar vuestras almas." },
{name:'59122',l:'59',c:'1',v:'22',texto:"Pero sed hacedores de la palabra, y no tan solamente oidores, engañándoos a vosotros mismos." },
{name:'59123',l:'59',c:'1',v:'23',texto:"Porque si alguno es oidor de la palabra pero no hacedor de ella, éste es semejante al hombre que considera en un espejo su rostro natural." },
{name:'59124',l:'59',c:'1',v:'24',texto:"Porque él se considera a sí mismo, y se va, y luego olvida cómo era." },
{name:'59125',l:'59',c:'1',v:'25',texto:"Mas el que mira atentamente en la perfecta ley, la de la libertad, y persevera en ella, no siendo oidor olvidadizo, sino hacedor de la obra, éste será bienaventurado en lo que hace." },
{name:'59126',l:'59',c:'1',v:'26',texto:"Si alguno se cree religioso entre vosotros, y no refrena su lengua, sino que engaña su corazón, la religión del tal es vana." },
{name:'59127',l:'59',c:'1',v:'27',texto:"La religión pura y sin mácula delante de Dios el Padre es esta: Visitar a los huérfanos y a las viudas en sus tribulaciones, y guardarse sin mancha del mundo." },
],
numVersiculos: 27,
},

c2: {
versiculos:[
{name:'5921',l:'59',c:'2',v:'1',texto:"Hermanos míos, que vuestra fe en nuestro glorioso Señor Jesucristo sea sin acepción de personas." },
{name:'5922',l:'59',c:'2',v:'2',texto:"Porque si en vuestra congregación entra un hombre con anillo de oro y con ropa espléndida, y también entra un pobre con vestido andrajoso," },
{name:'5923',l:'59',c:'2',v:'3',texto:"y miráis con agrado al que trae la ropa espléndida y le decís: Siéntate tú aquí en buen lugar; y decís al pobre: Estate tú allí en pie, o siéntate aquí bajo mi estrado; " },
{name:'5924',l:'59',c:'2',v:'4',texto:"¿no hacéis distinciones entre vosotros mismos, y venís a ser jueces con malos pensamientos? " },
{name:'5925',l:'59',c:'2',v:'5',texto:"Hermanos míos amados, oíd: ¿No ha elegido Dios a los pobres de este mundo, para que sean ricos en fe y herederos del reino que ha prometido a los que le aman? " },
{name:'5926',l:'59',c:'2',v:'6',texto:"Pero vosotros habéis afrentado al pobre. ¿No os oprimen los ricos, y no son ellos los mismos que os arrastran a los tribunales? " },
{name:'5927',l:'59',c:'2',v:'7',texto:"¿No blasfeman ellos el buen nombre que fue invocado sobre vosotros? " },
{name:'5928',l:'59',c:'2',v:'8',texto:"Si en verdad cumplís la ley real, conforme a la Escritura: Amarás a tu prójimo como a ti mismo, bien hacéis; " },
{name:'5929',l:'59',c:'2',v:'9',texto:"pero si hacéis acepción de personas, cometéis pecado, y quedáis convictos por la ley como transgresores." },
{name:'59210',l:'59',c:'2',v:'10',texto:"Porque cualquiera que guardare toda la ley, pero ofendiere en un punto, se hace culpable de todos." },
{name:'59211',l:'59',c:'2',v:'11',texto:"Porque el que dijo: No cometerás adulterio, también ha dicho: No matarás. Ahora bien, si no cometes adulterio, pero matas, ya te has hecho transgresor de la ley." },
{name:'59212',l:'59',c:'2',v:'12',texto:"Así hablad, y así haced, como los que habéis de ser juzgados por la ley de la libertad." },
{name:'59213',l:'59',c:'2',v:'13',texto:"Porque juicio sin misericordia se hará con aquel que no hiciere misericordia; y la misericordia triunfa sobre el juicio." },
{name:'59214',l:'59',c:'2',v:'14',texto:"Hermanos míos, ¿de qué aprovechará si alguno dice que tiene fe, y no tiene obras? ¿Podrá la fe salvarle? " },
{name:'59215',l:'59',c:'2',v:'15',texto:"Y si un hermano o una hermana están desnudos, y tienen necesidad del mantenimiento de cada día," },
{name:'59216',l:'59',c:'2',v:'16',texto:"y alguno de vosotros les dice: Id en paz, calentaos y saciaos, pero no les dais las cosas que son necesarias para el cuerpo, ¿de qué aprovecha? " },
{name:'59217',l:'59',c:'2',v:'17',texto:"Así también la fe, si no tiene obras, es muerta en sí misma." },
{name:'59218',l:'59',c:'2',v:'18',texto:"Pero alguno dirá: Tú tienes fe, y yo tengo obras. Muéstrame tu fe sin tus obras, y yo te mostraré mi fe por mis obras." },
{name:'59219',l:'59',c:'2',v:'19',texto:"Tú crees que Dios es uno; bien haces. También los demonios creen, y tiemblan." },
{name:'59220',l:'59',c:'2',v:'20',texto:"¿Mas quieres saber, hombre vano, que la fe sin obras es muerta? " },
{name:'59221',l:'59',c:'2',v:'21',texto:"¿No fue justificado por las obras Abraham nuestro padre, cuando ofreció a su hijo Isaac sobre el altar? " },
{name:'59222',l:'59',c:'2',v:'22',texto:"¿No ves que la fe actuó juntamente con sus obras, y que la fe se perfeccionó por las obras? " },
{name:'59223',l:'59',c:'2',v:'23',texto:"Y se cumplió la Escritura que dice: Abraham creyó a Dios, y le fue contado por justicia, y fue llamado amigo de Dios." },
{name:'59224',l:'59',c:'2',v:'24',texto:"Vosotros veis, pues, que el hombre es justificado por las obras, y no solamente por la fe." },
{name:'59225',l:'59',c:'2',v:'25',texto:"Asimismo también Rahab la ramera, ¿no fue justificada por obras, cuando recibió a los mensajeros y los envió por otro camino? " },
{name:'59226',l:'59',c:'2',v:'26',texto:"Porque como el cuerpo sin espíritu está muerto, así también la fe sin obras está muerta." },
],
numVersiculos: 26,
},

c3: {
versiculos:[
{name:'5931',l:'59',c:'3',v:'1',texto:"Hermanos míos, no os hagáis maestros muchos de vosotros, sabiendo que recibiremos mayor condenación." },
{name:'5932',l:'59',c:'3',v:'2',texto:"Porque todos ofendemos muchas veces. Si alguno no ofende en palabra, éste es varón perfecto, capaz también de refrenar todo el cuerpo." },
{name:'5933',l:'59',c:'3',v:'3',texto:"He aquí nosotros ponemos freno en la boca de los caballos para que nos obedezcan, y dirigimos así todo su cuerpo." },
{name:'5934',l:'59',c:'3',v:'4',texto:"Mirad también las naves; aunque tan grandes, y llevadas de impetuosos vientos, son gobernadas con un muy pequeño timón por donde el que las gobierna quiere." },
{name:'5935',l:'59',c:'3',v:'5',texto:"Así también la lengua es un miembro pequeño, pero se jacta de grandes cosas. He aquí, ¡cuán grande bosque enciende un pequeño fuego! " },
{name:'5936',l:'59',c:'3',v:'6',texto:"Y la lengua es un fuego, un mundo de maldad. La lengua está puesta entre nuestros miembros, y contamina todo el cuerpo, e inflama la rueda de la creación, y ella misma es inflamada por el infierno." },
{name:'5937',l:'59',c:'3',v:'7',texto:"Porque toda naturaleza de bestias, y de aves, y de serpientes, y de seres del mar, se doma y ha sido domada por la naturaleza humana; " },
{name:'5938',l:'59',c:'3',v:'8',texto:"pero ningún hombre puede domar la lengua, que es un mal que no puede ser refrenado, llena de veneno mortal." },
{name:'5939',l:'59',c:'3',v:'9',texto:"Con ella bendecimos al Dios y Padre, y con ella maldecimos a los hombres, que están hechos a la semejanza de Dios." },
{name:'59310',l:'59',c:'3',v:'10',texto:"De una misma boca proceden bendición y maldición. Hermanos míos, esto no debe ser así." },
{name:'59311',l:'59',c:'3',v:'11',texto:"¿Acaso alguna fuente echa por una misma abertura agua dulce y amarga? " },
{name:'59312',l:'59',c:'3',v:'12',texto:"Hermanos míos, ¿puede acaso la higuera producir aceitunas, o la vid higos? Así también ninguna fuente puede dar agua salada y dulce." },
{name:'59313',l:'59',c:'3',v:'13',texto:"¿Quién es sabio y entendido entre vosotros? Muestre por la buena conducta sus obras en sabia mansedumbre." },
{name:'59314',l:'59',c:'3',v:'14',texto:"Pero si tenéis celos amargos y contención en vuestro corazón, no os jactéis, ni mintáis contra la verdad; " },
{name:'59315',l:'59',c:'3',v:'15',texto:"porque esta sabiduría no es la que desciende de lo alto, sino terrenal, animal, diabólica." },
{name:'59316',l:'59',c:'3',v:'16',texto:"Porque donde hay celos y contención, allí hay perturbación y toda obra perversa." },
{name:'59317',l:'59',c:'3',v:'17',texto:"Pero la sabiduría que es de lo alto es primeramente pura, después pacífica, amable, benigna, llena de misericordia y de buenos frutos, sin incertidumbre ni hipocresía." },
{name:'59318',l:'59',c:'3',v:'18',texto:"Y el fruto de justicia se siembra en paz para aquellos que hacen la paz." },
],
numVersiculos: 18,
},

c4: {
versiculos:[
{name:'5941',l:'59',c:'4',v:'1',texto:"¿De dónde vienen las guerras y los pleitos entre vosotros? ¿No es de vuestras pasiones, las cuales combaten en vuestros miembros? " },
{name:'5942',l:'59',c:'4',v:'2',texto:"Codiciáis, y no tenéis; matáis y ardéis de envidia, y no podéis alcanzar; combatís y lucháis, pero no tenéis lo que deseáis, porque no pedís." },
{name:'5943',l:'59',c:'4',v:'3',texto:"Pedís, y no recibís, porque pedís mal, para gastar en vuestros deleites." },
{name:'5944',l:'59',c:'4',v:'4',texto:"¡Oh almas adúlteras! ¿No sabéis que la amistad del mundo es enemistad contra Dios? Cualquiera, pues, que quiera ser amigo del mundo, se constituye enemigo de Dios." },
{name:'5945',l:'59',c:'4',v:'5',texto:"¿O pensáis que la Escritura dice en vano: El Espíritu que él ha hecho morar en nosotros nos anhela celosamente? " },
{name:'5946',l:'59',c:'4',v:'6',texto:"Pero él da mayor gracia. Por esto dice: Dios resiste a los soberbios, y da gracia a los humildes." },
{name:'5947',l:'59',c:'4',v:'7',texto:"Someteos, pues, a Dios; resistid al diablo, y huirá de vosotros." },
{name:'5948',l:'59',c:'4',v:'8',texto:"Acercaos a Dios, y él se acercará a vosotros. Pecadores, limpiad las manos; y vosotros los de doble ánimo, purificad vuestros corazones." },
{name:'5949',l:'59',c:'4',v:'9',texto:"Afligíos, y lamentad, y llorad. Vuestra risa se convierta en lloro, y vuestro gozo en tristeza." },
{name:'59410',l:'59',c:'4',v:'10',texto:"Humillaos delante del Señor, y él os exaltará." },
{name:'59411',l:'59',c:'4',v:'11',texto:"Hermanos, no murmuréis los unos de los otros. El que murmura del hermano y juzga a su hermano, murmura de la ley y juzga a la ley; pero si tú juzgas a la ley, no eres hacedor de la ley, sino juez." },
{name:'59412',l:'59',c:'4',v:'12',texto:"Uno solo es el dador de la ley, que puede salvar y perder; pero tú, ¿quién eres para que juzgues a otro? " },
{name:'59413',l:'59',c:'4',v:'13',texto:"¡Vamos ahora! los que decís: Hoy y mañana iremos a tal ciudad, y estaremos allá un año, y traficaremos, y ganaremos; " },
{name:'59414',l:'59',c:'4',v:'14',texto:"cuando no sabéis lo que será mañana. Porque ¿qué es vuestra vida? Ciertamente es neblina que se aparece por un poco de tiempo, y luego se desvanece." },
{name:'59415',l:'59',c:'4',v:'15',texto:"En lugar de lo cual deberíais decir: Si el Señor quiere, viviremos y haremos esto o aquello." },
{name:'59416',l:'59',c:'4',v:'16',texto:"Pero ahora os jactáis en vuestras soberbias. Toda jactancia semejante es mala; " },
{name:'59417',l:'59',c:'4',v:'17',texto:"y al que sabe hacer lo bueno, y no lo hace, le es pecado." },
],
numVersiculos: 17,
},

c5: {
versiculos:[
{name:'5951',l:'59',c:'5',v:'1',texto:"¡Vamos ahora, ricos! Llorad y aullad por las miserias que os vendrán." },
{name:'5952',l:'59',c:'5',v:'2',texto:"Vuestras riquezas están podridas, y vuestras ropas están comidas de polilla." },
{name:'5953',l:'59',c:'5',v:'3',texto:"Vuestro oro y plata están enmohecidos; y su moho testificará contra vosotros, y devorará del todo vuestras carnes como fuego. Habéis acumulado tesoros para los días postreros." },
{name:'5954',l:'59',c:'5',v:'4',texto:"He aquí, clama el jornal de los obreros que han cosechado vuestras tierras, el cual por engaño no les ha sido pagado por vosotros; y los clamores de los que habían segado han entrado en los oídos del Señor de los ejércitos." },
{name:'5955',l:'59',c:'5',v:'5',texto:"Habéis vivido en deleites sobre la tierra, y sido disolutos; habéis engordado vuestros corazones como en día de matanza." },
{name:'5956',l:'59',c:'5',v:'6',texto:"Habéis condenado y dado muerte al justo, y él no os hace resistencia." },
{name:'5957',l:'59',c:'5',v:'7',texto:"Por tanto, hermanos, tened paciencia hasta la venida del Señor. Mirad cómo el labrador espera el precioso fruto de la tierra, aguardando con paciencia hasta que reciba la lluvia temprana y la tardía." },
{name:'5958',l:'59',c:'5',v:'8',texto:"Tened también vosotros paciencia, y afirmad vuestros corazones; porque la venida del Señor se acerca." },
{name:'5959',l:'59',c:'5',v:'9',texto:"Hermanos, no os quejéis unos contra otros, para que no seáis condenados; he aquí, el juez está delante de la puerta." },
{name:'59510',l:'59',c:'5',v:'10',texto:"Hermanos míos, tomad como ejemplo de aflicción y de paciencia a los profetas que hablaron en nombre del Señor." },
{name:'59511',l:'59',c:'5',v:'11',texto:"He aquí, tenemos por bienaventurados a los que sufren. Habéis oído de la paciencia de Job, y habéis visto el fin del Señor, que el Señor es muy misericordioso y compasivo." },
{name:'59512',l:'59',c:'5',v:'12',texto:"Pero sobre todo, hermanos míos, no juréis, ni por el cielo, ni por la tierra, ni por ningún otro juramento; sino que vuestro sí sea sí, y vuestro no sea no, para que no caigáis en condenación." },
{name:'59513',l:'59',c:'5',v:'13',texto:"¿Está alguno entre vosotros afligido? Haga oración. ¿Está alguno alegre? Cante alabanzas." },
{name:'59514',l:'59',c:'5',v:'14',texto:"¿Está alguno enfermo entre vosotros? Llame a los ancianos de la iglesia, y oren por él, ungiéndole con aceite en el nombre del Señor." },
{name:'59515',l:'59',c:'5',v:'15',texto:"Y la oración de fe salvará al enfermo, y el Señor lo levantará; y si hubiere cometido pecados, le serán perdonados." },
{name:'59516',l:'59',c:'5',v:'16',texto:"Confesaos vuestras ofensas unos a otros, y orad unos por otros, para que seáis sanados. La oración eficaz del justo puede mucho." },
{name:'59517',l:'59',c:'5',v:'17',texto:"Elías era hombre sujeto a pasiones semejantes a las nuestras, y oró fervientemente para que no lloviese, y no llovió sobre la tierra por tres años y seis meses." },
{name:'59518',l:'59',c:'5',v:'18',texto:"Y otra vez oró, y el cielo dio lluvia, y la tierra produjo su fruto." },
{name:'59519',l:'59',c:'5',v:'19',texto:"Hermanos, si alguno de entre vosotros se ha extraviado de la verdad, y alguno le hace volver," },
{name:'59520',l:'59',c:'5',v:'20',texto:"sepa que el que haga volver al pecador del error de su camino, salvará de muerte un alma, y cubrirá multitud de pecados." },
],
numVersiculos: 20,
},
	

};
