BibliaRVR60.juan1 = {
	libro: "1 Juan",
	numCapitulos: 5,

c1: {
versiculos:[
{name:'6211',l:'62',c:'1',v:'1',texto:"Lo que era desde el principio, lo que hemos oído, lo que hemos visto con nuestros ojos, lo que hemos contemplado, y palparon nuestras manos tocante al Verbo de vida " },
{name:'6212',l:'62',c:'1',v:'2',texto:"(porque la vida fue manifestada, y la hemos visto, y testificamos, y os anunciamos la vida eterna, la cual estaba con el Padre, y se nos manifestó); " },
{name:'6213',l:'62',c:'1',v:'3',texto:"lo que hemos visto y oído, eso os anunciamos, para que también vosotros tengáis comunión con nosotros; y nuestra comunión verdaderamente es con el Padre, y con su Hijo Jesucristo." },
{name:'6214',l:'62',c:'1',v:'4',texto:"Estas cosas os escribimos, para que vuestro gozo sea cumplido." },
{name:'6215',l:'62',c:'1',v:'5',texto:"Este es el mensaje que hemos oído de él, y os anunciamos: Dios es luz, y no hay ningunas tinieblas en él." },
{name:'6216',l:'62',c:'1',v:'6',texto:"Si decimos que tenemos comunión con él, y andamos en tinieblas, mentimos, y no practicamos la verdad; " },
{name:'6217',l:'62',c:'1',v:'7',texto:"pero si andamos en luz, como él está en luz, tenemos comunión unos con otros, y la sangre de Jesucristo su Hijo nos limpia de todo pecado." },
{name:'6218',l:'62',c:'1',v:'8',texto:"Si decimos que no tenemos pecado, nos engañamos a nosotros mismos, y la verdad no está en nosotros." },
{name:'6219',l:'62',c:'1',v:'9',texto:"Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados, y limpiarnos de toda maldad." },
{name:'62110',l:'62',c:'1',v:'10',texto:"Si decimos que no hemos pecado, le hacemos a él mentiroso, y su palabra no está en nosotros." },
],
numVersiculos: 10,
},

c2: {
versiculos:[
{name:'6221',l:'62',c:'2',v:'1',texto:"Hijitos míos, estas cosas os escribo para que no pequéis; y si alguno hubiere pecado, abogado tenemos para con el Padre, a Jesucristo el justo." },
{name:'6222',l:'62',c:'2',v:'2',texto:"Y él es la propiciación por nuestros pecados; y no solamente por los nuestros, sino también por los de todo el mundo." },
{name:'6223',l:'62',c:'2',v:'3',texto:"Y en esto sabemos que nosotros le conocemos, si guardamos sus mandamientos." },
{name:'6224',l:'62',c:'2',v:'4',texto:"El que dice: Yo le conozco, y no guarda sus mandamientos, el tal es mentiroso, y la verdad no está en él; " },
{name:'6225',l:'62',c:'2',v:'5',texto:"pero el que guarda su palabra, en éste verdaderamente el amor de Dios se ha perfeccionado; por esto sabemos que estamos en él." },
{name:'6226',l:'62',c:'2',v:'6',texto:"El que dice que permanece en él, debe andar como él anduvo." },
{name:'6227',l:'62',c:'2',v:'7',texto:"Hermanos, no os escribo mandamiento nuevo, sino el mandamiento antiguo que habéis tenido desde el principio; este mandamiento antiguo es la palabra que habéis oído desde el principio." },
{name:'6228',l:'62',c:'2',v:'8',texto:"Sin embargo, os escribo un mandamiento nuevo, que es verdadero en él y en vosotros, porque las tinieblas van pasando, y la luz verdadera ya alumbra." },
{name:'6229',l:'62',c:'2',v:'9',texto:"El que dice que está en la luz, y aborrece a su hermano, está todavía en tinieblas." },
{name:'62210',l:'62',c:'2',v:'10',texto:"El que ama a su hermano, permanece en la luz, y en él no hay tropiezo." },
{name:'62211',l:'62',c:'2',v:'11',texto:"Pero el que aborrece a su hermano está en tinieblas, y anda en tinieblas, y no sabe a dónde va, porque las tinieblas le han cegado los ojos." },
{name:'62212',l:'62',c:'2',v:'12',texto:"Os escribo a vosotros, hijitos, porque vuestros pecados os han sido perdonados por su nombre." },
{name:'62213',l:'62',c:'2',v:'13',texto:"Os escribo a vosotros, padres, porque conocéis al que es desde el principio. Os escribo a vosotros, jóvenes, porque habéis vencido al maligno. Os escribo a vosotros, hijitos, porque habéis conocido al Padre." },
{name:'62214',l:'62',c:'2',v:'14',texto:"Os he escrito a vosotros, padres, porque habéis conocido al que es desde el principio. Os he escrito a vosotros, jóvenes, porque sois fuertes, y la palabra de Dios permanece en vosotros, y habéis vencido al maligno." },
{name:'62215',l:'62',c:'2',v:'15',texto:"No améis al mundo, ni las cosas que están en el mundo. Si alguno ama al mundo, el amor del Padre no está en él." },
{name:'62216',l:'62',c:'2',v:'16',texto:"Porque todo lo que hay en el mundo, los deseos de la carne, los deseos de los ojos, y la vanagloria de la vida, no proviene del Padre, sino del mundo." },
{name:'62217',l:'62',c:'2',v:'17',texto:"Y el mundo pasa, y sus deseos; pero el que hace la voluntad de Dios permanece para siempre." },
{name:'62218',l:'62',c:'2',v:'18',texto:"Hijitos, ya es el último tiempo; y según vosotros oísteis que el anticristo viene, así ahora han surgido muchos anticristos; por esto conocemos que es el último tiempo." },
{name:'62219',l:'62',c:'2',v:'19',texto:"Salieron de nosotros, pero no eran de nosotros; porque si hubiesen sido de nosotros, habrían permanecido con nosotros; pero salieron para que se manifestase que no todos son de nosotros." },
{name:'62220',l:'62',c:'2',v:'20',texto:"Pero vosotros tenéis la unción del Santo, y conocéis todas las cosas." },
{name:'62221',l:'62',c:'2',v:'21',texto:"No os he escrito como si ignoraseis la verdad, sino porque la conocéis, y porque ninguna mentira procede de la verdad." },
{name:'62222',l:'62',c:'2',v:'22',texto:"¿Quién es el mentiroso, sino el que niega que Jesús es el Cristo? Este es anticristo, el que niega al Padre y al Hijo." },
{name:'62223',l:'62',c:'2',v:'23',texto:"Todo aquel que niega al Hijo, tampoco tiene al Padre. El que confiesa al Hijo, tiene también al Padre." },
{name:'62224',l:'62',c:'2',v:'24',texto:"Lo que habéis oído desde el principio, permanezca en vosotros. Si lo que habéis oído desde el principio permanece en vosotros, también vosotros permaneceréis en el Hijo y en el Padre." },
{name:'62225',l:'62',c:'2',v:'25',texto:"Y esta es la promesa que él nos hizo, la vida eterna." },
{name:'62226',l:'62',c:'2',v:'26',texto:"Os he escrito esto sobre los que os engañan." },
{name:'62227',l:'62',c:'2',v:'27',texto:"Pero la unción que vosotros recibisteis de él permanece en vosotros, y no tenéis necesidad de que nadie os enseñe; así como la unción misma os enseña todas las cosas, y es verdadera, y no es mentira, según ella os ha enseñado, permaneced en él." },
{name:'62228',l:'62',c:'2',v:'28',texto:"Y ahora, hijitos, permaneced en él, para que cuando se manifieste, tengamos confianza, para que en su venida no nos alejemos de él avergonzados." },
{name:'62229',l:'62',c:'2',v:'29',texto:"Si sabéis que él es justo, sabed también que todo el que hace justicia es nacido de él." },
],
numVersiculos: 29,
},

c3: {
versiculos:[
{name:'6231',l:'62',c:'3',v:'1',texto:"Mirad cuál amor nos ha dado el Padre, para que seamos llamados hijos de Dios; por esto el mundo no nos conoce, porque no le conoció a él." },
{name:'6232',l:'62',c:'3',v:'2',texto:"Amados, ahora somos hijos de Dios, y aún no se ha manifestado lo que hemos de ser; pero sabemos que cuando él se manifieste, seremos semejantes a él, porque le veremos tal como él es." },
{name:'6233',l:'62',c:'3',v:'3',texto:"Y todo aquel que tiene esta esperanza en él, se purifica a sí mismo, así como él es puro." },
{name:'6234',l:'62',c:'3',v:'4',texto:"Todo aquel que comete pecado, infringe también la ley; pues el pecado es infracción de la ley." },
{name:'6235',l:'62',c:'3',v:'5',texto:"Y sabéis que él apareció para quitar nuestros pecados, y no hay pecado en él." },
{name:'6236',l:'62',c:'3',v:'6',texto:"Todo aquel que permanece en él, no peca; todo aquel que peca, no le ha visto, ni le ha conocido." },
{name:'6237',l:'62',c:'3',v:'7',texto:"Hijitos, nadie os engañe; el que hace justicia es justo, como él es justo." },
{name:'6238',l:'62',c:'3',v:'8',texto:"El que practica el pecado es del diablo; porque el diablo peca desde el principio. Para esto apareció el Hijo de Dios, para deshacer las obras del diablo." },
{name:'6239',l:'62',c:'3',v:'9',texto:"Todo aquel que es nacido de Dios, no practica el pecado, porque la simiente de Dios permanece en él; y no puede pecar, porque es nacido de Dios." },
{name:'62310',l:'62',c:'3',v:'10',texto:"En esto se manifiestan los hijos de Dios, y los hijos del diablo: todo aquel que no hace justicia, y que no ama a su hermano, no es de Dios." },
{name:'62311',l:'62',c:'3',v:'11',texto:"Porque este es el mensaje que habéis oído desde el principio: Que nos amemos unos a otros." },
{name:'62312',l:'62',c:'3',v:'12',texto:"No como Caín, que era del maligno y mató a su hermano. ¿Y por qué causa le mató? Porque sus obras eran malas, y las de su hermano justas." },
{name:'62313',l:'62',c:'3',v:'13',texto:"Hermanos míos, no os extrañéis si el mundo os aborrece." },
{name:'62314',l:'62',c:'3',v:'14',texto:"Nosotros sabemos que hemos pasado de muerte a vida, en que amamos a los hermanos. El que no ama a su hermano, permanece en muerte." },
{name:'62315',l:'62',c:'3',v:'15',texto:"Todo aquel que aborrece a su hermano es homicida; y sabéis que ningún homicida tiene vida eterna permanente en él." },
{name:'62316',l:'62',c:'3',v:'16',texto:"En esto hemos conocido el amor, en que él puso su vida por nosotros; también nosotros debemos poner nuestras vidas por los hermanos." },
{name:'62317',l:'62',c:'3',v:'17',texto:"Pero el que tiene bienes de este mundo y ve a su hermano tener necesidad, y cierra contra él su corazón, ¿cómo mora el amor de Dios en él? " },
{name:'62318',l:'62',c:'3',v:'18',texto:"Hijitos míos, no amemos de palabra ni de lengua, sino de hecho y en verdad." },
{name:'62319',l:'62',c:'3',v:'19',texto:"Y en esto conocemos que somos de la verdad, y aseguraremos nuestros corazones delante de él; " },
{name:'62320',l:'62',c:'3',v:'20',texto:"pues si nuestro corazón nos reprende, mayor que nuestro corazón es Dios, y él sabe todas las cosas." },
{name:'62321',l:'62',c:'3',v:'21',texto:"Amados, si nuestro corazón no nos reprende, confianza tenemos en Dios; " },
{name:'62322',l:'62',c:'3',v:'22',texto:"y cualquiera cosa que pidiéremos la recibiremos de él, porque guardamos sus mandamientos, y hacemos las cosas que son agradables delante de él." },
{name:'62323',l:'62',c:'3',v:'23',texto:"Y este es su mandamiento: Que creamos en el nombre de su Hijo Jesucristo, y nos amemos unos a otros como nos lo ha mandado." },
{name:'62324',l:'62',c:'3',v:'24',texto:"Y el que guarda sus mandamientos, permanece en Dios, y Dios en él. Y en esto sabemos que él permanece en nosotros, por el Espíritu que nos ha dado." },
],
numVersiculos: 24,
},

c4: {
versiculos:[
{name:'6241',l:'62',c:'4',v:'1',texto:"Amados, no creáis a todo espíritu, sino probad los espíritus si son de Dios; porque muchos falsos profetas han salido por el mundo." },
{name:'6242',l:'62',c:'4',v:'2',texto:"En esto conoced el Espíritu de Dios: Todo espíritu que confiesa que Jesucristo ha venido en carne, es de Dios; " },
{name:'6243',l:'62',c:'4',v:'3',texto:"y todo espíritu que no confiesa que Jesucristo ha venido en carne, no es de Dios; y este es el espíritu del anticristo, el cual vosotros habéis oído que viene, y que ahora ya está en el mundo." },
{name:'6244',l:'62',c:'4',v:'4',texto:"Hijitos, vosotros sois de Dios, y los habéis vencido; porque mayor es el que está en vosotros, que el que está en el mundo." },
{name:'6245',l:'62',c:'4',v:'5',texto:"Ellos son del mundo; por eso hablan del mundo, y el mundo los oye." },
{name:'6246',l:'62',c:'4',v:'6',texto:"Nosotros somos de Dios; el que conoce a Dios, nos oye; el que no es de Dios, no nos oye. En esto conocemos el espíritu de verdad y el espíritu de error." },
{name:'6247',l:'62',c:'4',v:'7',texto:"Amados, amémonos unos a otros; porque el amor es de Dios. Todo aquel que ama, es nacido de Dios, y conoce a Dios." },
{name:'6248',l:'62',c:'4',v:'8',texto:"El que no ama, no ha conocido a Dios; porque Dios es amor." },
{name:'6249',l:'62',c:'4',v:'9',texto:"En esto se mostró el amor de Dios para con nosotros, en que Dios envió a su Hijo unigénito al mundo, para que vivamos por él." },
{name:'62410',l:'62',c:'4',v:'10',texto:"En esto consiste el amor: no en que nosotros hayamos amado a Dios, sino en que él nos amó a nosotros, y envió a su Hijo en propiciación por nuestros pecados." },
{name:'62411',l:'62',c:'4',v:'11',texto:"Amados, si Dios nos ha amado así, debemos también nosotros amarnos unos a otros." },
{name:'62412',l:'62',c:'4',v:'12',texto:"Nadie ha visto jamás a Dios. Si nos amamos unos a otros, Dios permanece en nosotros, y su amor se ha perfeccionado en nosotros." },
{name:'62413',l:'62',c:'4',v:'13',texto:"En esto conocemos que permanecemos en él, y él en nosotros, en que nos ha dado de su Espíritu." },
{name:'62414',l:'62',c:'4',v:'14',texto:"Y nosotros hemos visto y testificamos que el Padre ha enviado al Hijo, el Salvador del mundo." },
{name:'62415',l:'62',c:'4',v:'15',texto:"Todo aquel que confiese que Jesús es el Hijo de Dios, Dios permanece en él, y él en Dios." },
{name:'62416',l:'62',c:'4',v:'16',texto:"Y nosotros hemos conocido y creído el amor que Dios tiene para con nosotros. Dios es amor; y el que permanece en amor, permanece en Dios, y Dios en él." },
{name:'62417',l:'62',c:'4',v:'17',texto:"En esto se ha perfeccionado el amor en nosotros, para que tengamos confianza en el día del juicio; pues como él es, así somos nosotros en este mundo." },
{name:'62418',l:'62',c:'4',v:'18',texto:"En el amor no hay temor, sino que el perfecto amor echa fuera el temor; porque el temor lleva en sí castigo. De donde el que teme, no ha sido perfeccionado en el amor." },
{name:'62419',l:'62',c:'4',v:'19',texto:"Nosotros le amamos a él, porque él nos amó primero." },
{name:'62420',l:'62',c:'4',v:'20',texto:"Si alguno dice: Yo amo a Dios, y aborrece a su hermano, es mentiroso. Pues el que no ama a su hermano a quien ha visto, ¿cómo puede amar a Dios a quien no ha visto? " },
{name:'62421',l:'62',c:'4',v:'21',texto:"Y nosotros tenemos este mandamiento de él: El que ama a Dios, ame también a su hermano." },
],
numVersiculos: 21,
},

c5: {
versiculos:[
{name:'6251',l:'62',c:'5',v:'1',texto:"Todo aquel que cree que Jesús es el Cristo, es nacido de Dios; y todo aquel que ama al que engendró, ama también al que ha sido engendrado por él." },
{name:'6252',l:'62',c:'5',v:'2',texto:"En esto conocemos que amamos a los hijos de Dios, cuando amamos a Dios, y guardamos sus mandamientos." },
{name:'6253',l:'62',c:'5',v:'3',texto:"Pues este es el amor a Dios, que guardemos sus mandamientos; y sus mandamientos no son gravosos." },
{name:'6254',l:'62',c:'5',v:'4',texto:"Porque todo lo que es nacido de Dios vence al mundo; y esta es la victoria que ha vencido al mundo, nuestra fe." },
{name:'6255',l:'62',c:'5',v:'5',texto:"¿Quién es el que vence al mundo, sino el que cree que Jesús es el Hijo de Dios? " },
{name:'6256',l:'62',c:'5',v:'6',texto:"Este es Jesucristo, que vino mediante agua y sangre; no mediante agua solamente, sino mediante agua y sangre. Y el Espíritu es el que da testimonio; porque el Espíritu es la verdad." },
{name:'6257',l:'62',c:'5',v:'7',texto:"Porque tres son los que dan testimonio en el cielo: el Padre, el Verbo y el Espíritu Santo; y estos tres son uno." },
{name:'6258',l:'62',c:'5',v:'8',texto:"Y tres son los que dan testimonio en la tierra: el Espíritu, el agua y la sangre; y estos tres concuerdan." },
{name:'6259',l:'62',c:'5',v:'9',texto:"Si recibimos el testimonio de los hombres, mayor es el testimonio de Dios; porque este es el testimonio con que Dios ha testificado acerca de su Hijo." },
{name:'62510',l:'62',c:'5',v:'10',texto:"El que cree en el Hijo de Dios, tiene el testimonio en sí mismo; el que no cree a Dios, le ha hecho mentiroso, porque no ha creído en el testimonio que Dios ha dado acerca de su Hijo." },
{name:'62511',l:'62',c:'5',v:'11',texto:"Y este es el testimonio: que Dios nos ha dado vida eterna; y esta vida está en su Hijo." },
{name:'62512',l:'62',c:'5',v:'12',texto:"El que tiene al Hijo, tiene la vida; el que no tiene al Hijo de Dios no tiene la vida." },
{name:'62513',l:'62',c:'5',v:'13',texto:"Estas cosas os he escrito a vosotros que creéis en el nombre del Hijo de Dios, para que sepáis que tenéis vida eterna, y para que creáis en el nombre del Hijo de Dios." },
{name:'62514',l:'62',c:'5',v:'14',texto:"Y esta es la confianza que tenemos en él, que si pedimos alguna cosa conforme a su voluntad, él nos oye." },
{name:'62515',l:'62',c:'5',v:'15',texto:"Y si sabemos que él nos oye en cualquiera cosa que pidamos, sabemos que tenemos las peticiones que le hayamos hecho." },
{name:'62516',l:'62',c:'5',v:'16',texto:"Si alguno viere a su hermano cometer pecado que no sea de muerte, pedirá, y Dios le dará vida; esto es para los que cometen pecado que no sea de muerte. Hay pecado de muerte, por el cual yo no digo que se pida." },
{name:'62517',l:'62',c:'5',v:'17',texto:"Toda injusticia es pecado; pero hay pecado no de muerte." },
{name:'62518',l:'62',c:'5',v:'18',texto:"Sabemos que todo aquel que ha nacido de Dios, no practica el pecado, pues Aquel que fue engendrado por Dios le guarda, y el maligno no le toca." },
{name:'62519',l:'62',c:'5',v:'19',texto:"Sabemos que somos de Dios, y el mundo entero está bajo el maligno." },
{name:'62520',l:'62',c:'5',v:'20',texto:"Pero sabemos que el Hijo de Dios ha venido, y nos ha dado entendimiento para conocer al que es verdadero; y estamos en el verdadero, en su Hijo Jesucristo. Este es el verdadero Dios, y la vida eterna." },
{name:'62521',l:'62',c:'5',v:'21',texto:"Hijitos, guardaos de los ídolos. Amén." },
],
numVersiculos: 21,
},
	

};
