BibliaRVR60.apocalipsis = {
	libro: "Apocalipsis",
	numCapitulos: 22,

c1: {
versiculos:[
{name:'6611',l:'66',c:'1',v:'1',texto:"La revelación de Jesucristo, que Dios le dio, para manifestar a sus siervos las cosas que deben suceder pronto; y la declaró enviándola por medio de su ángel a su siervo Juan," },
{name:'6612',l:'66',c:'1',v:'2',texto:"que ha dado testimonio de la palabra de Dios, y del testimonio de Jesucristo, y de todas las cosas que ha visto." },
{name:'6613',l:'66',c:'1',v:'3',texto:"Bienaventurado el que lee, y los que oyen las palabras de esta profecía, y guardan las cosas en ella escritas; porque el tiempo está cerca." },
{name:'6614',l:'66',c:'1',v:'4',texto:"Juan, a las siete iglesias que están en Asia: Gracia y paz a vosotros, del que es y que era y que ha de venir, y de los siete espíritus que están delante de su trono; " },
{name:'6615',l:'66',c:'1',v:'5',texto:"y de Jesucristo el testigo fiel, el primogénito de los muertos, y el soberano de los reyes de la tierra. Al que nos amó, y nos lavó de nuestros pecados con su sangre," },
{name:'6616',l:'66',c:'1',v:'6',texto:"y nos hizo reyes y sacerdotes para Dios, su Padre; a él sea gloria e imperio por los siglos de los siglos. Amén." },
{name:'6617',l:'66',c:'1',v:'7',texto:"He aquí que viene con las nubes, y todo ojo le verá, y los que le traspasaron; y todos los linajes de la tierra harán lamentación por él. Sí, amén." },
{name:'6618',l:'66',c:'1',v:'8',texto:"Yo soy el Alfa y la Omega, principio y fin, dice el Señor, el que es y que era y que ha de venir, el Todopoderoso." },
{name:'6619',l:'66',c:'1',v:'9',texto:"Yo Juan, vuestro hermano, y copartícipe vuestro en la tribulación, en el reino y en la paciencia de Jesucristo, estaba en la isla llamada Patmos, por causa de la palabra de Dios y el testimonio de Jesucristo." },
{name:'66110',l:'66',c:'1',v:'10',texto:"Yo estaba en el Espíritu en el día del Señor, y oí detrás de mí una gran voz como de trompeta," },
{name:'66111',l:'66',c:'1',v:'11',texto:"que decía: Yo soy el Alfa y la Omega, el primero y el último. Escribe en un libro lo que ves, y envíalo a las siete iglesias que están en Asia: a Efeso, Esmirna, Pérgamo, Tiatira, Sardis, Filadelfia y Laodicea." },
{name:'66112',l:'66',c:'1',v:'12',texto:"Y me volví para ver la voz que hablaba conmigo; y vuelto, vi siete candeleros de oro," },
{name:'66113',l:'66',c:'1',v:'13',texto:"y en medio de los siete candeleros, a uno semejante al Hijo del Hombre, vestido de una ropa que llegaba hasta los pies, y ceñido por el pecho con un cinto de oro." },
{name:'66114',l:'66',c:'1',v:'14',texto:"Su cabeza y sus cabellos eran blancos como blanca lana, como nieve; sus ojos como llama de fuego; " },
{name:'66115',l:'66',c:'1',v:'15',texto:"y sus pies semejantes al bronce bruñido, refulgente como en un horno; y su voz como estruendo de muchas aguas." },
{name:'66116',l:'66',c:'1',v:'16',texto:"Tenía en su diestra siete estrellas; de su boca salía una espada aguda de dos filos; y su rostro era como el sol cuando resplandece en su fuerza." },
{name:'66117',l:'66',c:'1',v:'17',texto:"Cuando le vi, caí como muerto a sus pies. Y él puso su diestra sobre mí, diciéndome: No temas; yo soy el primero y el último; " },
{name:'66118',l:'66',c:'1',v:'18',texto:"y el que vivo, y estuve muerto; mas he aquí que vivo por los siglos de los siglos, amén. Y tengo las llaves de la muerte y del Hades." },
{name:'66119',l:'66',c:'1',v:'19',texto:"Escribe las cosas que has visto, y las que son, y las que han de ser después de estas." },
{name:'66120',l:'66',c:'1',v:'20',texto:"El misterio de las siete estrellas que has visto en mi diestra, y de los siete candeleros de oro: las siete estrellas son los ángeles de las siete iglesias, y los siete candeleros que has visto, son las siete iglesias." },
],
numVersiculos: 20,
},

c2: {
versiculos:[
{name:'6621',l:'66',c:'2',v:'1',texto:"Escribe al ángel de la iglesia en Efeso: El que tiene las siete estrellas en su diestra, el que anda en medio de los siete candeleros de oro, dice esto: " },
{name:'6622',l:'66',c:'2',v:'2',texto:"Yo conozco tus obras, y tu arduo trabajo y paciencia; y que no puedes soportar a los malos, y has probado a los que se dicen ser apóstoles, y no lo son, y los has hallado mentirosos; " },
{name:'6623',l:'66',c:'2',v:'3',texto:"y has sufrido, y has tenido paciencia, y has trabajado arduamente por amor de mi nombre, y no has desmayado." },
{name:'6624',l:'66',c:'2',v:'4',texto:"Pero tengo contra ti, que has dejado tu primer amor." },
{name:'6625',l:'66',c:'2',v:'5',texto:"Recuerda, por tanto, de dónde has caído, y arrepiéntete, y haz las primeras obras; pues si no, vendré pronto a ti, y quitaré tu candelero de su lugar, si no te hubieres arrepentido." },
{name:'6626',l:'66',c:'2',v:'6',texto:"Pero tienes esto, que aborreces las obras de los nicolaítas, las cuales yo también aborrezco." },
{name:'6627',l:'66',c:'2',v:'7',texto:"El que tiene oído, oiga lo que el Espíritu dice a las iglesias. Al que venciere, le daré a comer del árbol de la vida, el cual está en medio del paraíso de Dios." },
{name:'6628',l:'66',c:'2',v:'8',texto:"Y escribe al ángel de la iglesia en Esmirna: El primero y el postrero, el que estuvo muerto y vivió, dice esto: " },
{name:'6629',l:'66',c:'2',v:'9',texto:"Yo conozco tus obras, y tu tribulación, y tu pobreza (pero tú eres rico), y la blasfemia de los que se dicen ser judíos, y no lo son, sino sinagoga de Satanás." },
{name:'66210',l:'66',c:'2',v:'10',texto:"No temas en nada lo que vas a padecer. He aquí, el diablo echará a algunos de vosotros en la cárcel, para que seáis probados, y tendréis tribulación por diez días. Sé fiel hasta la muerte, y yo te daré la corona de la vida." },
{name:'66211',l:'66',c:'2',v:'11',texto:"El que tiene oído, oiga lo que el Espíritu dice a las iglesias. El que venciere, no sufrirá daño de la segunda muerte." },
{name:'66212',l:'66',c:'2',v:'12',texto:"Y escribe al ángel de la iglesia en Pérgamo: El que tiene la espada aguda de dos filos dice esto: " },
{name:'66213',l:'66',c:'2',v:'13',texto:"Yo conozco tus obras, y dónde moras, donde está el trono de Satanás; pero retienes mi nombre, y no has negado mi fe, ni aun en los días en que Antipas mi testigo fiel fue muerto entre vosotros, donde mora Satanás." },
{name:'66214',l:'66',c:'2',v:'14',texto:"Pero tengo unas pocas cosas contra ti: que tienes ahí a los que retienen la doctrina de Balaam, que enseñaba a Balac a poner tropiezo ante los hijos de Israel, a comer de cosas sacrificadas a los ídolos, y a cometer fornicación." },
{name:'66215',l:'66',c:'2',v:'15',texto:"Y también tienes a los que retienen la doctrina de los nicolaítas, la que yo aborrezco." },
{name:'66216',l:'66',c:'2',v:'16',texto:"Por tanto, arrepiéntete; pues si no, vendré a ti pronto, y pelearé contra ellos con la espada de mi boca." },
{name:'66217',l:'66',c:'2',v:'17',texto:"El que tiene oído, oiga lo que el Espíritu dice a las iglesias. Al que venciere, daré a comer del maná escondido, y le daré una piedrecita blanca, y en la piedrecita escrito un nombre nuevo, el cual ninguno conoce sino aquel que lo recibe." },
{name:'66218',l:'66',c:'2',v:'18',texto:"Y escribe al ángel de la iglesia en Tiatira: El Hijo de Dios, el que tiene ojos como llama de fuego, y pies semejantes al bronce bruñido, dice esto: " },
{name:'66219',l:'66',c:'2',v:'19',texto:"Yo conozco tus obras, y amor, y fe, y servicio, y tu paciencia, y que tus obras postreras son más que las primeras." },
{name:'66220',l:'66',c:'2',v:'20',texto:"Pero tengo unas pocas cosas contra ti: que toleras que esa mujer Jezabel, que se dice profetisa, enseñe y seduzca a mis siervos a fornicar y a comer cosas sacrificadas a los ídolos." },
{name:'66221',l:'66',c:'2',v:'21',texto:"Y le he dado tiempo para que se arrepienta, pero no quiere arrepentirse de su fornicación." },
{name:'66222',l:'66',c:'2',v:'22',texto:"He aquí, yo la arrojo en cama, y en gran tribulación a los que con ella adulteran, si no se arrepienten de las obras de ella." },
{name:'66223',l:'66',c:'2',v:'23',texto:"Y a sus hijos heriré de muerte, y todas las iglesias sabrán que yo soy el que escudriña la mente y el corazón; y os daré a cada uno según vuestras obras." },
{name:'66224',l:'66',c:'2',v:'24',texto:"Pero a vosotros y a los demás que están en Tiatira, a cuantos no tienen esa doctrina, y no han conocido lo que ellos llaman las profundidades de Satanás, yo os digo: No os impondré otra carga; " },
{name:'66225',l:'66',c:'2',v:'25',texto:"pero lo que tenéis, retenedlo hasta que yo venga." },
{name:'66226',l:'66',c:'2',v:'26',texto:"Al que venciere y guardare mis obras hasta el fin, yo le daré autoridad sobre las naciones," },
{name:'66227',l:'66',c:'2',v:'27',texto:"y las regirá con vara de hierro, y serán quebradas como vaso de alfarero; como yo también la he recibido de mi Padre; " },
{name:'66228',l:'66',c:'2',v:'28',texto:"y le daré la estrella de la mañana." },
{name:'66229',l:'66',c:'2',v:'29',texto:"El que tiene oído, oiga lo que el Espíritu dice a las iglesias." },
],
numVersiculos: 29,
},

c3: {
versiculos:[
{name:'6631',l:'66',c:'3',v:'1',texto:"Escribe al ángel de la iglesia en Sardis: El que tiene los siete espíritus de Dios, y las siete estrellas, dice esto: Yo conozco tus obras, que tienes nombre de que vives, y estás muerto." },
{name:'6632',l:'66',c:'3',v:'2',texto:"Sé vigilante, y afirma las otras cosas que están para morir; porque no he hallado tus obras perfectas delante de Dios." },
{name:'6633',l:'66',c:'3',v:'3',texto:"Acuérdate, pues, de lo que has recibido y oído; y guárdalo, y arrepiéntete. Pues si no velas, vendré sobre ti como ladrón, y no sabrás a qué hora vendré sobre ti." },
{name:'6634',l:'66',c:'3',v:'4',texto:"Pero tienes unas pocas personas en Sardis que no han manchado sus vestiduras; y andarán conmigo en vestiduras blancas, porque son dignas." },
{name:'6635',l:'66',c:'3',v:'5',texto:"El que venciere será vestido de vestiduras blancas; y no borraré su nombre del libro de la vida, y confesaré su nombre delante de mi Padre, y delante de sus ángeles." },
{name:'6636',l:'66',c:'3',v:'6',texto:"El que tiene oído, oiga lo que el Espíritu dice a las iglesias." },
{name:'6637',l:'66',c:'3',v:'7',texto:"Escribe al ángel de la iglesia en Filadelfia: Esto dice el Santo, el Verdadero, el que tiene la llave de David, el que abre y ninguno cierra, y cierra y ninguno abre: " },
{name:'6638',l:'66',c:'3',v:'8',texto:"Yo conozco tus obras; he aquí, he puesto delante de ti una puerta abierta, la cual nadie puede cerrar; porque aunque tienes poca fuerza, has guardado mi palabra, y no has negado mi nombre." },
{name:'6639',l:'66',c:'3',v:'9',texto:"He aquí, yo entrego de la sinagoga de Satanás a los que se dicen ser judíos y no lo son, sino que mienten; he aquí, yo haré que vengan y se postren a tus pies, y reconozcan que yo te he amado." },
{name:'66310',l:'66',c:'3',v:'10',texto:"Por cuanto has guardado la palabra de mi paciencia, yo también te guardaré de la hora de la prueba que ha de venir sobre el mundo entero, para probar a los que moran sobre la tierra." },
{name:'66311',l:'66',c:'3',v:'11',texto:"He aquí, yo vengo pronto; retén lo que tienes, para que ninguno tome tu corona." },
{name:'66312',l:'66',c:'3',v:'12',texto:"Al que venciere, yo lo haré columna en el templo de mi Dios, y nunca más saldrá de allí; y escribiré sobre él el nombre de mi Dios, y el nombre de la ciudad de mi Dios, la nueva Jerusalén, la cual desciende del cielo, de mi Dios, y mi nombre nuevo." },
{name:'66313',l:'66',c:'3',v:'13',texto:"El que tiene oído, oiga lo que el Espíritu dice a las iglesias." },
{name:'66314',l:'66',c:'3',v:'14',texto:"Y escribe al ángel de la iglesia en Laodicea: He aquí el Amén, el testigo fiel y verdadero, el principio de la creación de Dios, dice esto: " },
{name:'66315',l:'66',c:'3',v:'15',texto:"Yo conozco tus obras, que ni eres frío ni caliente. ¡Ojalá fueses frío o caliente! " },
{name:'66316',l:'66',c:'3',v:'16',texto:"Pero por cuanto eres tibio, y no frío ni caliente, te vomitaré de mi boca." },
{name:'66317',l:'66',c:'3',v:'17',texto:"Porque tú dices: Yo soy rico, y me he enriquecido, y de ninguna cosa tengo necesidad; y no sabes que tú eres un desventurado, miserable, pobre, ciego y desnudo." },
{name:'66318',l:'66',c:'3',v:'18',texto:"Por tanto, yo te aconsejo que de mí compres oro refinado en fuego, para que seas rico, y vestiduras blancas para vestirte, y que no se descubra la vergüenza de tu desnudez; y unge tus ojos con colirio, para que veas." },
{name:'66319',l:'66',c:'3',v:'19',texto:"Yo reprendo y castigo a todos los que amo; sé, pues, celoso, y arrepiéntete." },
{name:'66320',l:'66',c:'3',v:'20',texto:"He aquí, yo estoy a la puerta y llamo; si alguno oye mi voz y abre la puerta, entraré a él, y cenaré con él, y él conmigo." },
{name:'66321',l:'66',c:'3',v:'21',texto:"Al que venciere, le daré que se siente conmigo en mi trono, así como yo he vencido, y me he sentado con mi Padre en su trono." },
{name:'66322',l:'66',c:'3',v:'22',texto:"El que tiene oído, oiga lo que el Espíritu dice a las iglesias." },
],
numVersiculos: 22,
},

c4: {
versiculos:[
{name:'6641',l:'66',c:'4',v:'1',texto:"Después de esto miré, y he aquí una puerta abierta en el cielo; y la primera voz que oí, como de trompeta, hablando conmigo, dijo: Sube acá, y yo te mostraré las cosas que sucederán después de estas." },
{name:'6642',l:'66',c:'4',v:'2',texto:"Y al instante yo estaba en el Espíritu; y he aquí, un trono establecido en el cielo, y en el trono, uno sentado." },
{name:'6643',l:'66',c:'4',v:'3',texto:"Y el aspecto del que estaba sentado era semejante a piedra de jaspe y de cornalina; y había alrededor del trono un arco iris, semejante en aspecto a la esmeralda." },
{name:'6644',l:'66',c:'4',v:'4',texto:"Y alrededor del trono había veinticuatro tronos; y vi sentados en los tronos a veinticuatro ancianos, vestidos de ropas blancas, con coronas de oro en sus cabezas." },
{name:'6645',l:'66',c:'4',v:'5',texto:"Y del trono salían relámpagos y truenos y voces; y delante del trono ardían siete lámparas de fuego, las cuales son los siete espíritus de Dios." },
{name:'6646',l:'66',c:'4',v:'6',texto:"Y delante del trono había como un mar de vidrio semejante al cristal; y junto al trono, y alrededor del trono, cuatro seres vivientes llenos de ojos delante y detrás." },
{name:'6647',l:'66',c:'4',v:'7',texto:"El primer ser viviente era semejante a un león; el segundo era semejante a un becerro; el tercero tenía rostro como de hombre; y el cuarto era semejante a un águila volando." },
{name:'6648',l:'66',c:'4',v:'8',texto:"Y los cuatro seres vivientes tenían cada uno seis alas, y alrededor y por dentro estaban llenos de ojos; y no cesaban día y noche de decir: Santo, santo, santo es el Señor Dios Todopoderoso, el que era, el que es, y el que ha de venir." },
{name:'6649',l:'66',c:'4',v:'9',texto:"Y siempre que aquellos seres vivientes dan gloria y honra y acción de gracias al que está sentado en el trono, al que vive por los siglos de los siglos," },
{name:'66410',l:'66',c:'4',v:'10',texto:"los veinticuatro ancianos se postran delante del que está sentado en el trono, y adoran al que vive por los siglos de los siglos, y echan sus coronas delante del trono, diciendo: " },
{name:'66411',l:'66',c:'4',v:'11',texto:"Señor, digno eres de recibir la gloria y la honra y el poder; porque tú creaste todas las cosas, y por tu voluntad existen y fueron creadas." },
],
numVersiculos: 11,
},

c5: {
versiculos:[
{name:'6651',l:'66',c:'5',v:'1',texto:"Y vi en la mano derecha del que estaba sentado en el trono un libro escrito por dentro y por fuera, sellado con siete sellos." },
{name:'6652',l:'66',c:'5',v:'2',texto:"Y vi a un ángel fuerte que pregonaba a gran voz: ¿Quién es digno de abrir el libro y desatar sus sellos? " },
{name:'6653',l:'66',c:'5',v:'3',texto:"Y ninguno, ni en el cielo ni en la tierra ni debajo de la tierra, podía abrir el libro, ni aun mirarlo." },
{name:'6654',l:'66',c:'5',v:'4',texto:"Y lloraba yo mucho, porque no se había hallado a ninguno digno de abrir el libro, ni de leerlo, ni de mirarlo." },
{name:'6655',l:'66',c:'5',v:'5',texto:"Y uno de los ancianos me dijo: No llores. He aquí que el León de la tribu de Judá, la raíz de David, ha vencido para abrir el libro y desatar sus siete sellos." },
{name:'6656',l:'66',c:'5',v:'6',texto:"Y miré, y vi que en medio del trono y de los cuatro seres vivientes, y en medio de los ancianos, estaba en pie un Cordero como inmolado, que tenía siete cuernos, y siete ojos, los cuales son los siete espíritus de Dios enviados por toda la tierra." },
{name:'6657',l:'66',c:'5',v:'7',texto:"Y vino, y tomó el libro de la mano derecha del que estaba sentado en el trono." },
{name:'6658',l:'66',c:'5',v:'8',texto:"Y cuando hubo tomado el libro, los cuatro seres vivientes y los veinticuatro ancianos se postraron delante del Cordero; todos tenían arpas, y copas de oro llenas de incienso, que son las oraciones de los santos; " },
{name:'6659',l:'66',c:'5',v:'9',texto:"y cantaban un nuevo cántico, diciendo: Digno eres de tomar el libro y de abrir sus sellos; porque tú fuiste inmolado, y con tu sangre nos has redimido para Dios, de todo linaje y lengua y pueblo y nación; " },
{name:'66510',l:'66',c:'5',v:'10',texto:"y nos has hecho para nuestro Dios reyes y sacerdotes, y reinaremos sobre la tierra." },
{name:'66511',l:'66',c:'5',v:'11',texto:"Y miré, y oí la voz de muchos ángeles alrededor del trono, y de los seres vivientes, y de los ancianos; y su número era millones de millones," },
{name:'66512',l:'66',c:'5',v:'12',texto:"que decían a gran voz: El Cordero que fue inmolado es digno de tomar el poder, las riquezas, la sabiduría, la fortaleza, la honra, la gloria y la alabanza." },
{name:'66513',l:'66',c:'5',v:'13',texto:"Y a todo lo creado que está en el cielo, y sobre la tierra, y debajo de la tierra, y en el mar, y a todas las cosas que en ellos hay, oí decir: Al que está sentado en el trono, y al Cordero, sea la alabanza, la honra, la gloria y el poder, por los siglos de los siglos." },
{name:'66514',l:'66',c:'5',v:'14',texto:"Los cuatro seres vivientes decían: Amén; y los veinticuatro ancianos se postraron sobre sus rostros y adoraron al que vive por los siglos de los siglos." },
],
numVersiculos: 14,
},

c6: {
versiculos:[
{name:'6661',l:'66',c:'6',v:'1',texto:"Vi cuando el Cordero abrió uno de los sellos, y oí a uno de los cuatro seres vivientes decir como con voz de trueno: Ven y mira." },
{name:'6662',l:'66',c:'6',v:'2',texto:"Y miré, y he aquí un caballo blanco; y el que lo montaba tenía un arco; y le fue dada una corona, y salió venciendo, y para vencer." },
{name:'6663',l:'66',c:'6',v:'3',texto:"Cuando abrió el segundo sello, oí al segundo ser viviente, que decía: Ven y mira." },
{name:'6664',l:'66',c:'6',v:'4',texto:"Y salió otro caballo, bermejo; y al que lo montaba le fue dado poder de quitar de la tierra la paz, y que se matasen unos a otros; y se le dio una gran espada." },
{name:'6665',l:'66',c:'6',v:'5',texto:"Cuando abrió el tercer sello, oí al tercer ser viviente, que decía: Ven y mira. Y miré, y he aquí un caballo negro; y el que lo montaba tenía una balanza en la mano." },
{name:'6666',l:'66',c:'6',v:'6',texto:"Y oí una voz de en medio de los cuatro seres vivientes, que decía: Dos libras de trigo por un denario, y seis libras de cebada por un denario; pero no dañes el aceite ni el vino." },
{name:'6667',l:'66',c:'6',v:'7',texto:"Cuando abrió el cuarto sello, oí la voz del cuarto ser viviente, que decía: Ven y mira." },
{name:'6668',l:'66',c:'6',v:'8',texto:"Miré, y he aquí un caballo amarillo, y el que lo montaba tenía por nombre Muerte, y el Hades le seguía; y le fue dada potestad sobre la cuarta parte de la tierra, para matar con espada, con hambre, con mortandad, y con las fieras de la tierra." },
{name:'6669',l:'66',c:'6',v:'9',texto:"Cuando abrió el quinto sello, vi bajo el altar las almas de los que habían sido muertos por causa de la palabra de Dios y por el testimonio que tenían." },
{name:'66610',l:'66',c:'6',v:'10',texto:"Y clamaban a gran voz, diciendo: ¿Hasta cuándo, Señor, santo y verdadero, no juzgas y vengas nuestra sangre en los que moran en la tierra? " },
{name:'66611',l:'66',c:'6',v:'11',texto:"Y se les dieron vestiduras blancas, y se les dijo que descansasen todavía un poco de tiempo, hasta que se completara el número de sus consiervos y sus hermanos, que también habían de ser muertos como ellos." },
{name:'66612',l:'66',c:'6',v:'12',texto:"Miré cuando abrió el sexto sello, y he aquí hubo un gran terremoto; y el sol se puso negro como tela de cilicio, y la luna se volvió toda como sangre; " },
{name:'66613',l:'66',c:'6',v:'13',texto:"y las estrellas del cielo cayeron sobre la tierra, como la higuera deja caer sus higos cuando es sacudida por un fuerte viento." },
{name:'66614',l:'66',c:'6',v:'14',texto:"Y el cielo se desvaneció como un pergamino que se enrolla; y todo monte y toda isla se removió de su lugar." },
{name:'66615',l:'66',c:'6',v:'15',texto:"Y los reyes de la tierra, y los grandes, los ricos, los capitanes, los poderosos, y todo siervo y todo libre, se escondieron en las cuevas y entre las peñas de los montes; " },
{name:'66616',l:'66',c:'6',v:'16',texto:"y decían a los montes y a las peñas: Caed sobre nosotros, y escondednos del rostro de aquel que está sentado sobre el trono, y de la ira del Cordero; " },
{name:'66617',l:'66',c:'6',v:'17',texto:"porque el gran día de su ira ha llegado; ¿y quién podrá sostenerse en pie? " },
],
numVersiculos: 17,
},

c7: {
versiculos:[
{name:'6671',l:'66',c:'7',v:'1',texto:"Después de esto vi a cuatro ángeles en pie sobre los cuatro ángulos de la tierra, que detenían los cuatro vientos de la tierra, para que no soplase viento alguno sobre la tierra, ni sobre el mar, ni sobre ningún árbol." },
{name:'6672',l:'66',c:'7',v:'2',texto:"Vi también a otro ángel que subía de donde sale el sol, y tenía el sello del Dios vivo; y clamó a gran voz a los cuatro ángeles, a quienes se les había dado el poder de hacer daño a la tierra y al mar," },
{name:'6673',l:'66',c:'7',v:'3',texto:"diciendo: No hagáis daño a la tierra, ni al mar, ni a los árboles, hasta que hayamos sellado en sus frentes a los siervos de nuestro Dios." },
{name:'6674',l:'66',c:'7',v:'4',texto:"Y oí el número de los sellados: ciento cuarenta y cuatro mil sellados de todas las tribus de los hijos de Israel." },
{name:'6675',l:'66',c:'7',v:'5',texto:"De la tribu de Judá, doce mil sellados. De la tribu de Rubén, doce mil sellados. De la tribu de Gad, doce mil sellados." },
{name:'6676',l:'66',c:'7',v:'6',texto:"De la tribu de Aser, doce mil sellados. De la tribu de Neftalí, doce mil sellados. De la tribu de Manasés, doce mil sellados." },
{name:'6677',l:'66',c:'7',v:'7',texto:"De la tribu de Simeón, doce mil sellados. De la tribu de Leví, doce mil sellados. De la tribu de Isacar, doce mil sellados." },
{name:'6678',l:'66',c:'7',v:'8',texto:"De la tribu de Zabulón, doce mil sellados. De la tribu de José, doce mil sellados. De la tribu de Benjamín, doce mil sellados." },
{name:'6679',l:'66',c:'7',v:'9',texto:"Después de esto miré, y he aquí una gran multitud, la cual nadie podía contar, de todas naciones y tribus y pueblos y lenguas, que estaban delante del trono y en la presencia del Cordero, vestidos de ropas blancas, y con palmas en las manos; " },
{name:'66710',l:'66',c:'7',v:'10',texto:"y clamaban a gran voz, diciendo: La salvación pertenece a nuestro Dios que está sentado en el trono, y al Cordero." },
{name:'66711',l:'66',c:'7',v:'11',texto:"Y todos los ángeles estaban en pie alrededor del trono, y de los ancianos y de los cuatro seres vivientes; y se postraron sobre sus rostros delante del trono, y adoraron a Dios," },
{name:'66712',l:'66',c:'7',v:'12',texto:"diciendo: Amén. La bendición y la gloria y la sabiduría y la acción de gracias y la honra y el poder y la fortaleza, sean a nuestro Dios por los siglos de los siglos. Amén." },
{name:'66713',l:'66',c:'7',v:'13',texto:"Entonces uno de los ancianos habló, diciéndome: Estos que están vestidos de ropas blancas, ¿quiénes son, y de dónde han venido? " },
{name:'66714',l:'66',c:'7',v:'14',texto:"Yo le dije: Señor, tú lo sabes. Y él me dijo: Estos son los que han salido de la gran tribulación, y han lavado sus ropas, y las han emblanquecido en la sangre del Cordero." },
{name:'66715',l:'66',c:'7',v:'15',texto:"Por esto están delante del trono de Dios, y le sirven día y noche en su templo; y el que está sentado sobre el trono extenderá su tabernáculo sobre ellos." },
{name:'66716',l:'66',c:'7',v:'16',texto:"Ya no tendrán hambre ni sed, y el sol no caerá más sobre ellos, ni calor alguno; " },
{name:'66717',l:'66',c:'7',v:'17',texto:"porque el Cordero que está en medio del trono los pastoreará, y los guiará a fuentes de aguas de vida; y Dios enjugará toda lágrima de los ojos de ellos." },
],
numVersiculos: 17,
},

c8: {
versiculos:[
{name:'6681',l:'66',c:'8',v:'1',texto:"Cuando abrió el séptimo sello, se hizo silencio en el cielo como por media hora." },
{name:'6682',l:'66',c:'8',v:'2',texto:"Y vi a los siete ángeles que estaban en pie ante Dios; y se les dieron siete trompetas." },
{name:'6683',l:'66',c:'8',v:'3',texto:"Otro ángel vino entonces y se paró ante el altar, con un incensario de oro; y se le dio mucho incienso para añadirlo a las oraciones de todos los santos, sobre el altar de oro que estaba delante del trono." },
{name:'6684',l:'66',c:'8',v:'4',texto:"Y de la mano del ángel subió a la presencia de Dios el humo del incienso con las oraciones de los santos." },
{name:'6685',l:'66',c:'8',v:'5',texto:"Y el ángel tomó el incensario, y lo llenó del fuego del altar, y lo arrojó a la tierra; y hubo truenos, y voces, y relámpagos, y un terremoto." },
{name:'6686',l:'66',c:'8',v:'6',texto:"Y los siete ángeles que tenían las siete trompetas se dispusieron a tocarlas." },
{name:'6687',l:'66',c:'8',v:'7',texto:"El primer ángel tocó la trompeta, y hubo granizo y fuego mezclados con sangre, que fueron lanzados sobre la tierra; y la tercera parte de los árboles se quemó, y se quemó toda la hierba verde." },
{name:'6688',l:'66',c:'8',v:'8',texto:"El segundo ángel tocó la trompeta, y como una gran montaña ardiendo en fuego fue precipitada en el mar; y la tercera parte del mar se convirtió en sangre." },
{name:'6689',l:'66',c:'8',v:'9',texto:"Y murió la tercera parte de los seres vivientes que estaban en el mar, y la tercera parte de las naves fue destruida." },
{name:'66810',l:'66',c:'8',v:'10',texto:"El tercer ángel tocó la trompeta, y cayó del cielo una gran estrella, ardiendo como una antorcha, y cayó sobre la tercera parte de los ríos, y sobre las fuentes de las aguas." },
{name:'66811',l:'66',c:'8',v:'11',texto:"Y el nombre de la estrella es Ajenjo. Y la tercera parte de las aguas se convirtió en ajenjo; y muchos hombres murieron a causa de esas aguas, porque se hicieron amargas." },
{name:'66812',l:'66',c:'8',v:'12',texto:"El cuarto ángel tocó la trompeta, y fue herida la tercera parte del sol, y la tercera parte de la luna, y la tercera parte de las estrellas, para que se oscureciese la tercera parte de ellos, y no hubiese luz en la tercera parte del día, y asimismo de la noche." },
{name:'66813',l:'66',c:'8',v:'13',texto:"Y miré, y oí a un ángel volar por en medio del cielo, diciendo a gran voz: ¡Ay, ay, ay, de los que moran en la tierra, a causa de los otros toques de trompeta que están para sonar los tres ángeles! " },
],
numVersiculos: 13,
},

c9: {
versiculos:[
{name:'6691',l:'66',c:'9',v:'1',texto:"El quinto ángel tocó la trompeta, y vi una estrella que cayó del cielo a la tierra; y se le dio la llave del pozo del abismo." },
{name:'6692',l:'66',c:'9',v:'2',texto:"Y abrió el pozo del abismo, y subió humo del pozo como humo de un gran horno; y se oscureció el sol y el aire por el humo del pozo." },
{name:'6693',l:'66',c:'9',v:'3',texto:"Y del humo salieron langostas sobre la tierra; y se les dio poder, como tienen poder los escorpiones de la tierra." },
{name:'6694',l:'66',c:'9',v:'4',texto:"Y se les mandó que no dañasen a la hierba de la tierra, ni a cosa verde alguna, ni a ningún árbol, sino solamente a los hombres que no tuviesen el sello de Dios en sus frentes." },
{name:'6695',l:'66',c:'9',v:'5',texto:"Y les fue dado, no que los matasen, sino que los atormentasen cinco meses; y su tormento era como tormento de escorpión cuando hiere al hombre." },
{name:'6696',l:'66',c:'9',v:'6',texto:"Y en aquellos días los hombres buscarán la muerte, pero no la hallarán; y ansiarán morir, pero la muerte huirá de ellos." },
{name:'6697',l:'66',c:'9',v:'7',texto:"El aspecto de las langostas era semejante a caballos preparados para la guerra; en las cabezas tenían como coronas de oro; sus caras eran como caras humanas; " },
{name:'6698',l:'66',c:'9',v:'8',texto:"tenían cabello como cabello de mujer; sus dientes eran como de leones; " },
{name:'6699',l:'66',c:'9',v:'9',texto:"tenían corazas como corazas de hierro; el ruido de sus alas era como el estruendo de muchos carros de caballos corriendo a la batalla; " },
{name:'66910',l:'66',c:'9',v:'10',texto:"tenían colas como de escorpiones, y también aguijones; y en sus colas tenían poder para dañar a los hombres durante cinco meses." },
{name:'66911',l:'66',c:'9',v:'11',texto:"Y tienen por rey sobre ellos al ángel del abismo, cuyo nombre en hebreo es Abadón, y en griego, Apolión." },
{name:'66912',l:'66',c:'9',v:'12',texto:"El primer ay pasó; he aquí, vienen aún dos ayes después de esto." },
{name:'66913',l:'66',c:'9',v:'13',texto:"El sexto ángel tocó la trompeta, y oí una voz de entre los cuatro cuernos del altar de oro que estaba delante de Dios," },
{name:'66914',l:'66',c:'9',v:'14',texto:"diciendo al sexto ángel que tenía la trompeta: Desata a los cuatro ángeles que están atados junto al gran río Eufrates." },
{name:'66915',l:'66',c:'9',v:'15',texto:"Y fueron desatados los cuatro ángeles que estaban preparados para la hora, día, mes y año, a fin de matar a la tercera parte de los hombres." },
{name:'66916',l:'66',c:'9',v:'16',texto:"Y el número de los ejércitos de los jinetes era doscientos millones. Yo oí su número." },
{name:'66917',l:'66',c:'9',v:'17',texto:"Así vi en visión los caballos y a sus jinetes, los cuales tenían corazas de fuego, de zafiro y de azufre. Y las cabezas de los caballos eran como cabezas de leones; y de su boca salían fuego, humo y azufre." },
{name:'66918',l:'66',c:'9',v:'18',texto:"Por estas tres plagas fue muerta la tercera parte de los hombres; por el fuego, el humo y el azufre que salían de su boca." },
{name:'66919',l:'66',c:'9',v:'19',texto:"Pues el poder de los caballos estaba en su boca y en sus colas; porque sus colas, semejantes a serpientes, tenían cabezas, y con ellas dañaban." },
{name:'66920',l:'66',c:'9',v:'20',texto:"Y los otros hombres que no fueron muertos con estas plagas, ni aun así se arrepintieron de las obras de sus manos, ni dejaron de adorar a los demonios, y a las imágenes de oro, de plata, de bronce, de piedra y de madera, las cuales no pueden ver, ni oír, ni andar; " },
{name:'66921',l:'66',c:'9',v:'21',texto:"y no se arrepintieron de sus homicidios, ni de sus hechicerías, ni de su fornicación, ni de sus hurtos." },
],
numVersiculos: 21,
},

c10: {
versiculos:[
{name:'66101',l:'66',c:'10',v:'1',texto:"Vi descender del cielo a otro ángel fuerte, envuelto en una nube, con el arco iris sobre su cabeza; y su rostro era como el sol, y sus pies como columnas de fuego." },
{name:'66102',l:'66',c:'10',v:'2',texto:"Tenía en su mano un librito abierto; y puso su pie derecho sobre el mar, y el izquierdo sobre la tierra; " },
{name:'66103',l:'66',c:'10',v:'3',texto:"y clamó a gran voz, como ruge un león; y cuando hubo clamado, siete truenos emitieron sus voces." },
{name:'66104',l:'66',c:'10',v:'4',texto:"Cuando los siete truenos hubieron emitido sus voces, yo iba a escribir; pero oí una voz del cielo que me decía: Sella las cosas que los siete truenos han dicho, y no las escribas." },
{name:'66105',l:'66',c:'10',v:'5',texto:"Y el ángel que vi en pie sobre el mar y sobre la tierra, levantó su mano al cielo," },
{name:'66106',l:'66',c:'10',v:'6',texto:"y juró por el que vive por los siglos de los siglos, que creó el cielo y las cosas que están en él, y la tierra y las cosas que están en ella, y el mar y las cosas que están en él, que el tiempo no sería más," },
{name:'66107',l:'66',c:'10',v:'7',texto:"sino que en los días de la voz del séptimo ángel, cuando él comience a tocar la trompeta, el misterio de Dios se consumará, como él lo anunció a sus siervos los profetas." },
{name:'66108',l:'66',c:'10',v:'8',texto:"La voz que oí del cielo habló otra vez conmigo, y dijo: Ve y toma el librito que está abierto en la mano del ángel que está en pie sobre el mar y sobre la tierra." },
{name:'66109',l:'66',c:'10',v:'9',texto:"Y fui al ángel, diciéndole que me diese el librito. Y él me dijo: Toma, y cómelo; y te amargará el vientre, pero en tu boca será dulce como la miel." },
{name:'661010',l:'66',c:'10',v:'10',texto:"Entonces tomé el librito de la mano del ángel, y lo comí; y era dulce en mi boca como la miel, pero cuando lo hube comido, amargó mi vientre." },
{name:'661011',l:'66',c:'10',v:'11',texto:"Y él me dijo: Es necesario que profetices otra vez sobre muchos pueblos, naciones, lenguas y reyes." },
],
numVersiculos: 11,
},

c11: {
versiculos:[
{name:'66111',l:'66',c:'11',v:'1',texto:"Entonces me fue dada una caña semejante a una vara de medir, y se me dijo: Levántate, y mide el templo de Dios, y el altar, y a los que adoran en él." },
{name:'66112',l:'66',c:'11',v:'2',texto:"Pero el patio que está fuera del templo déjalo aparte, y no lo midas, porque ha sido entregado a los gentiles; y ellos hollarán la ciudad santa cuarenta y dos meses." },
{name:'66113',l:'66',c:'11',v:'3',texto:"Y daré a mis dos testigos que profeticen por mil doscientos sesenta días, vestidos de cilicio." },
{name:'66114',l:'66',c:'11',v:'4',texto:"Estos testigos son los dos olivos, y los dos candeleros que están en pie delante del Dios de la tierra." },
{name:'66115',l:'66',c:'11',v:'5',texto:"Si alguno quiere dañarlos, sale fuego de la boca de ellos, y devora a sus enemigos; y si alguno quiere hacerles daño, debe morir él de la misma manera." },
{name:'66116',l:'66',c:'11',v:'6',texto:"Estos tienen poder para cerrar el cielo, a fin de que no llueva en los días de su profecía; y tienen poder sobre las aguas para convertirlas en sangre, y para herir la tierra con toda plaga, cuantas veces quieran." },
{name:'66117',l:'66',c:'11',v:'7',texto:"Cuando hayan acabado su testimonio, la bestia que sube del abismo hará guerra contra ellos, y los vencerá y los matará." },
{name:'66118',l:'66',c:'11',v:'8',texto:"Y sus cadáveres estarán en la plaza de la grande ciudad que en sentido espiritual se llama Sodoma y Egipto, donde también nuestro Señor fue crucificado." },
{name:'66119',l:'66',c:'11',v:'9',texto:"Y los de los pueblos, tribus, lenguas y naciones verán sus cadáveres por tres días y medio, y no permitirán que sean sepultados." },
{name:'661110',l:'66',c:'11',v:'10',texto:"Y los moradores de la tierra se regocijarán sobre ellos y se alegrarán, y se enviarán regalos unos a otros; porque estos dos profetas habían atormentado a los moradores de la tierra." },
{name:'661111',l:'66',c:'11',v:'11',texto:"Pero después de tres días y medio entró en ellos el espíritu de vida enviado por Dios, y se levantaron sobre sus pies, y cayó gran temor sobre los que los vieron." },
{name:'661112',l:'66',c:'11',v:'12',texto:"Y oyeron una gran voz del cielo, que les decía: Subid acá. Y subieron al cielo en una nube; y sus enemigos los vieron." },
{name:'661113',l:'66',c:'11',v:'13',texto:"En aquella hora hubo un gran terremoto, y la décima parte de la ciudad se derrumbó, y por el terremoto murieron en número de siete mil hombres; y los demás se aterrorizaron, y dieron gloria al Dios del cielo." },
{name:'661114',l:'66',c:'11',v:'14',texto:"El segundo ay pasó; he aquí, el tercer ay viene pronto." },
{name:'661115',l:'66',c:'11',v:'15',texto:"El séptimo ángel tocó la trompeta, y hubo grandes voces en el cielo, que decían: Los reinos del mundo han venido a ser de nuestro Señor y de su Cristo; y él reinará por los siglos de los siglos." },
{name:'661116',l:'66',c:'11',v:'16',texto:"Y los veinticuatro ancianos que estaban sentados delante de Dios en sus tronos, se postraron sobre sus rostros, y adoraron a Dios," },
{name:'661117',l:'66',c:'11',v:'17',texto:"diciendo: Te damos gracias, Señor Dios Todopoderoso, el que eres y que eras y que has de venir, porque has tomado tu gran poder, y has reinado." },
{name:'661118',l:'66',c:'11',v:'18',texto:"Y se airaron las naciones, y tu ira ha venido, y el tiempo de juzgar a los muertos, y de dar el galardón a tus siervos los profetas, a los santos, y a los que temen tu nombre, a los pequeños y a los grandes, y de destruir a los que destruyen la tierra." },
{name:'661119',l:'66',c:'11',v:'19',texto:"Y el templo de Dios fue abierto en el cielo, y el arca de su pacto se veía en el templo. Y hubo relámpagos, voces, truenos, un terremoto y grande granizo." },
],
numVersiculos: 19,
},

c12: {
versiculos:[
{name:'66121',l:'66',c:'12',v:'1',texto:"Apareció en el cielo una gran señal: una mujer vestida del sol, con la luna debajo de sus pies, y sobre su cabeza una corona de doce estrellas." },
{name:'66122',l:'66',c:'12',v:'2',texto:"Y estando encinta, clamaba con dolores de parto, en la angustia del alumbramiento." },
{name:'66123',l:'66',c:'12',v:'3',texto:"También apareció otra señal en el cielo: he aquí un gran dragón escarlata, que tenía siete cabezas y diez cuernos, y en sus cabezas siete diademas; " },
{name:'66124',l:'66',c:'12',v:'4',texto:"y su cola arrastraba la tercera parte de las estrellas del cielo, y las arrojó sobre la tierra. Y el dragón se paró frente a la mujer que estaba para dar a luz, a fin de devorar a su hijo tan pronto como naciese." },
{name:'66125',l:'66',c:'12',v:'5',texto:"Y ella dio a luz un hijo varón, que regirá con vara de hierro a todas las naciones; y su hijo fue arrebatado para Dios y para su trono." },
{name:'66126',l:'66',c:'12',v:'6',texto:"Y la mujer huyó al desierto, donde tiene lugar preparado por Dios, para que allí la sustenten por mil doscientos sesenta días." },
{name:'66127',l:'66',c:'12',v:'7',texto:"Después hubo una gran batalla en el cielo: Miguel y sus ángeles luchaban contra el dragón; y luchaban el dragón y sus ángeles; " },
{name:'66128',l:'66',c:'12',v:'8',texto:"pero no prevalecieron, ni se halló ya lugar para ellos en el cielo." },
{name:'66129',l:'66',c:'12',v:'9',texto:"Y fue lanzado fuera el gran dragón, la serpiente antigua, que se llama diablo y Satanás, el cual engaña al mundo entero; fue arrojado a la tierra, y sus ángeles fueron arrojados con él." },
{name:'661210',l:'66',c:'12',v:'10',texto:"Entonces oí una gran voz en el cielo, que decía: Ahora ha venido la salvación, el poder, y el reino de nuestro Dios, y la autoridad de su Cristo; porque ha sido lanzado fuera el acusador de nuestros hermanos, el que los acusaba delante de nuestro Dios día y noche." },
{name:'661211',l:'66',c:'12',v:'11',texto:"Y ellos le han vencido por medio de la sangre del Cordero y de la palabra del testimonio de ellos, y menospreciaron sus vidas hasta la muerte." },
{name:'661212',l:'66',c:'12',v:'12',texto:"Por lo cual alegraos, cielos, y los que moráis en ellos. ¡Ay de los moradores de la tierra y del mar! porque el diablo ha descendido a vosotros con gran ira, sabiendo que tiene poco tiempo." },
{name:'661213',l:'66',c:'12',v:'13',texto:"Y cuando vio el dragón que había sido arrojado a la tierra, persiguió a la mujer que había dado a luz al hijo varón." },
{name:'661214',l:'66',c:'12',v:'14',texto:"Y se le dieron a la mujer las dos alas de la gran águila, para que volase de delante de la serpiente al desierto, a su lugar, donde es sustentada por un tiempo, y tiempos, y la mitad de un tiempo." },
{name:'661215',l:'66',c:'12',v:'15',texto:"Y la serpiente arrojó de su boca, tras la mujer, agua como un río, para que fuese arrastrada por el río." },
{name:'661216',l:'66',c:'12',v:'16',texto:"Pero la tierra ayudó a la mujer, pues la tierra abrió su boca y tragó el río que el dragón había echado de su boca." },
{name:'661217',l:'66',c:'12',v:'17',texto:"Entonces el dragón se llenó de ira contra la mujer; y se fue a hacer guerra contra el resto de la descendencia de ella, los que guardan los mandamientos de Dios y tienen el testimonio de Jesucristo." },
],
numVersiculos: 17,
},

c13: {
versiculos:[
{name:'66131',l:'66',c:'13',v:'1',texto:"Me paré sobre la arena del mar, y vi subir del mar una bestia que tenía siete cabezas y diez cuernos; y en sus cuernos diez diademas; y sobre sus cabezas, un nombre blasfemo." },
{name:'66132',l:'66',c:'13',v:'2',texto:"Y la bestia que vi era semejante a un leopardo, y sus pies como de oso, y su boca como boca de león. Y el dragón le dio su poder y su trono, y grande autoridad." },
{name:'66133',l:'66',c:'13',v:'3',texto:"Vi una de sus cabezas como herida de muerte, pero su herida mortal fue sanada; y se maravilló toda la tierra en pos de la bestia," },
{name:'66134',l:'66',c:'13',v:'4',texto:"y adoraron al dragón que había dado autoridad a la bestia, y adoraron a la bestia, diciendo: ¿Quién como la bestia, y quién podrá luchar contra ella? " },
{name:'66135',l:'66',c:'13',v:'5',texto:"También se le dio boca que hablaba grandes cosas y blasfemias; y se le dio autoridad para actuar cuarenta y dos meses." },
{name:'66136',l:'66',c:'13',v:'6',texto:"Y abrió su boca en blasfemias contra Dios, para blasfemar de su nombre, de su tabernáculo, y de los que moran en el cielo." },
{name:'66137',l:'66',c:'13',v:'7',texto:"Y se le permitió hacer guerra contra los santos, y vencerlos. También se le dio autoridad sobre toda tribu, pueblo, lengua y nación." },
{name:'66138',l:'66',c:'13',v:'8',texto:"Y la adoraron todos los moradores de la tierra cuyos nombres no estaban escritos en el libro de la vida del Cordero que fue inmolado desde el principio del mundo." },
{name:'66139',l:'66',c:'13',v:'9',texto:"Si alguno tiene oído, oiga." },
{name:'661310',l:'66',c:'13',v:'10',texto:"Si alguno lleva en cautividad, va en cautividad; si alguno mata a espada, a espada debe ser muerto. Aquí está la paciencia y la fe de los santos." },
{name:'661311',l:'66',c:'13',v:'11',texto:"Después vi otra bestia que subía de la tierra; y tenía dos cuernos semejantes a los de un cordero, pero hablaba como dragón." },
{name:'661312',l:'66',c:'13',v:'12',texto:"Y ejerce toda la autoridad de la primera bestia en presencia de ella, y hace que la tierra y los moradores de ella adoren a la primera bestia, cuya herida mortal fue sanada." },
{name:'661313',l:'66',c:'13',v:'13',texto:"También hace grandes señales, de tal manera que aun hace descender fuego del cielo a la tierra delante de los hombres." },
{name:'661314',l:'66',c:'13',v:'14',texto:"Y engaña a los moradores de la tierra con las señales que se le ha permitido hacer en presencia de la bestia, mandando a los moradores de la tierra que le hagan imagen a la bestia que tiene la herida de espada, y vivió." },
{name:'661315',l:'66',c:'13',v:'15',texto:"Y se le permitió infundir aliento a la imagen de la bestia, para que la imagen hablase e hiciese matar a todo el que no la adorase." },
{name:'661316',l:'66',c:'13',v:'16',texto:"Y hacía que a todos, pequeños y grandes, ricos y pobres, libres y esclavos, se les pusiese una marca en la mano derecha, o en la frente; " },
{name:'661317',l:'66',c:'13',v:'17',texto:"y que ninguno pudiese comprar ni vender, sino el que tuviese la marca o el nombre de la bestia, o el número de su nombre." },
{name:'661318',l:'66',c:'13',v:'18',texto:"Aquí hay sabiduría. El que tiene entendimiento, cuente el número de la bestia, pues es número de hombre. Y su número es seiscientos sesenta y seis. El cántico de los ciento cuarenta y cuatro mil," },
],
numVersiculos: 18,
},

c14: {
versiculos:[
{name:'66141',l:'66',c:'14',v:'1',texto:"Después miré, y he aquí el Cordero estaba en pie sobre el monte de Sion, y con él ciento cuarenta y cuatro mil, que tenían el nombre de él y el de su Padre escrito en la frente." },
{name:'66142',l:'66',c:'14',v:'2',texto:"Y oí una voz del cielo como estruendo de muchas aguas, y como sonido de un gran trueno; y la voz que oí era como de arpistas que tocaban sus arpas." },
{name:'66143',l:'66',c:'14',v:'3',texto:"Y cantaban un cántico nuevo delante del trono, y delante de los cuatro seres vivientes, y de los ancianos; y nadie podía aprender el cántico sino aquellos ciento cuarenta y cuatro mil que fueron redimidos de entre los de la tierra." },
{name:'66144',l:'66',c:'14',v:'4',texto:"Estos son los que no se contaminaron con mujeres, pues son vírgenes. Estos son los que siguen al Cordero por dondequiera que va. Estos fueron redimidos de entre los hombres como primicias para Dios y para el Cordero; " },
{name:'66145',l:'66',c:'14',v:'5',texto:"y en sus bocas no fue hallada mentira, pues son sin mancha delante del trono de Dios." },
{name:'66146',l:'66',c:'14',v:'6',texto:"Vi volar por en medio del cielo a otro ángel, que tenía el evangelio eterno para predicarlo a los moradores de la tierra, a toda nación, tribu, lengua y pueblo," },
{name:'66147',l:'66',c:'14',v:'7',texto:"diciendo a gran voz: Temed a Dios, y dadle gloria, porque la hora de su juicio ha llegado; y adorad a aquel que hizo el cielo y la tierra, el mar y las fuentes de las aguas." },
{name:'66148',l:'66',c:'14',v:'8',texto:"Otro ángel le siguió, diciendo: Ha caído, ha caído Babilonia, la gran ciudad, porque ha hecho beber a todas las naciones del vino del furor de su fornicación." },
{name:'66149',l:'66',c:'14',v:'9',texto:"Y el tercer ángel los siguió, diciendo a gran voz: Si alguno adora a la bestia y a su imagen, y recibe la marca en su frente o en su mano," },
{name:'661410',l:'66',c:'14',v:'10',texto:"él también beberá del vino de la ira de Dios, que ha sido vaciado puro en el cáliz de su ira; y será atormentado con fuego y azufre delante de los santos ángeles y del Cordero; " },
{name:'661411',l:'66',c:'14',v:'11',texto:"y el humo de su tormento sube por los siglos de los siglos. Y no tienen reposo de día ni de noche los que adoran a la bestia y a su imagen, ni nadie que reciba la marca de su nombre." },
{name:'661412',l:'66',c:'14',v:'12',texto:"Aquí está la paciencia de los santos, los que guardan los mandamientos de Dios y la fe de Jesús." },
{name:'661413',l:'66',c:'14',v:'13',texto:"Oí una voz que desde el cielo me decía: Escribe: Bienaventurados de aquí en adelante los muertos que mueren en el Señor. Sí, dice el Espíritu, descansarán de sus trabajos, porque sus obras con ellos siguen." },
{name:'661414',l:'66',c:'14',v:'14',texto:"Miré, y he aquí una nube blanca; y sobre la nube uno sentado semejante al Hijo del Hombre, que tenía en la cabeza una corona de oro, y en la mano una hoz aguda." },
{name:'661415',l:'66',c:'14',v:'15',texto:"Y del templo salió otro ángel, clamando a gran voz al que estaba sentado sobre la nube: Mete tu hoz, y siega; porque la hora de segar ha llegado, pues la mies de la tierra está madura." },
{name:'661416',l:'66',c:'14',v:'16',texto:"Y el que estaba sentado sobre la nube metió su hoz en la tierra, y la tierra fue segada." },
{name:'661417',l:'66',c:'14',v:'17',texto:"Salió otro ángel del templo que está en el cielo, teniendo también una hoz aguda." },
{name:'661418',l:'66',c:'14',v:'18',texto:"Y salió del altar otro ángel, que tenía poder sobre el fuego, y llamó a gran voz al que tenía la hoz aguda, diciendo: Mete tu hoz aguda, y vendimia los racimos de la tierra, porque sus uvas están maduras." },
{name:'661419',l:'66',c:'14',v:'19',texto:"Y el ángel arrojó su hoz en la tierra, y vendimió la viña de la tierra, y echó las uvas en el gran lagar de la ira de Dios." },
{name:'661420',l:'66',c:'14',v:'20',texto:"Y fue pisado el lagar fuera de la ciudad, y del lagar salió sangre hasta los frenos de los caballos, por mil seiscientos estadios." },
],
numVersiculos: 20,
},

c15: {
versiculos:[
{name:'66151',l:'66',c:'15',v:'1',texto:"Vi en el cielo otra señal, grande y admirable: siete ángeles que tenían las siete plagas postreras; porque en ellas se consumaba la ira de Dios." },
{name:'66152',l:'66',c:'15',v:'2',texto:"Vi también como un mar de vidrio mezclado con fuego; y a los que habían alcanzado la victoria sobre la bestia y su imagen, y su marca y el número de su nombre, en pie sobre el mar de vidrio, con las arpas de Dios." },
{name:'66153',l:'66',c:'15',v:'3',texto:"Y cantan el cántico de Moisés siervo de Dios, y el cántico del Cordero, diciendo: Grandes y maravillosas son tus obras, Señor Dios Todopoderoso; justos y verdaderos son tus caminos, Rey de los santos." },
{name:'66154',l:'66',c:'15',v:'4',texto:"¿Quién no te temerá, oh Señor, y glorificará tu nombre? pues sólo tú eres santo; por lo cual todas las naciones vendrán y te adorarán, porque tus juicios se han manifestado." },
{name:'66155',l:'66',c:'15',v:'5',texto:"Después de estas cosas miré, y he aquí fue abierto en el cielo el templo del tabernáculo del testimonio; " },
{name:'66156',l:'66',c:'15',v:'6',texto:"y del templo salieron los siete ángeles que tenían las siete plagas, vestidos de lino limpio y resplandeciente, y ceñidos alrededor del pecho con cintos de oro." },
{name:'66157',l:'66',c:'15',v:'7',texto:"Y uno de los cuatro seres vivientes dio a los siete ángeles siete copas de oro, llenas de la ira de Dios, que vive por los siglos de los siglos." },
{name:'66158',l:'66',c:'15',v:'8',texto:"Y el templo se llenó de humo por la gloria de Dios, y por su poder; y nadie podía entrar en el templo hasta que se hubiesen cumplido las siete plagas de los siete ángeles." },
],
numVersiculos: 8,
},

c16: {
versiculos:[
{name:'66161',l:'66',c:'16',v:'1',texto:"Oí una gran voz que decía desde el templo a los siete ángeles: Id y derramad sobre la tierra las siete copas de la ira de Dios." },
{name:'66162',l:'66',c:'16',v:'2',texto:"Fue el primero, y derramó su copa sobre la tierra, y vino una úlcera maligna y pestilente sobre los hombres que tenían la marca de la bestia, y que adoraban su imagen." },
{name:'66163',l:'66',c:'16',v:'3',texto:"El segundo ángel derramó su copa sobre el mar, y éste se convirtió en sangre como de muerto; y murió todo ser vivo que había en el mar." },
{name:'66164',l:'66',c:'16',v:'4',texto:"El tercer ángel derramó su copa sobre los ríos, y sobre las fuentes de las aguas, y se convirtieron en sangre." },
{name:'66165',l:'66',c:'16',v:'5',texto:"Y oí al ángel de las aguas, que decía: Justo eres tú, oh Señor, el que eres y que eras, el Santo, porque has juzgado estas cosas." },
{name:'66166',l:'66',c:'16',v:'6',texto:"Por cuanto derramaron la sangre de los santos y de los profetas, también tú les has dado a beber sangre; pues lo merecen." },
{name:'66167',l:'66',c:'16',v:'7',texto:"También oí a otro, que desde el altar decía: Ciertamente, Señor Dios Todopoderoso, tus juicios son verdaderos y justos." },
{name:'66168',l:'66',c:'16',v:'8',texto:"El cuarto ángel derramó su copa sobre el sol, al cual fue dado quemar a los hombres con fuego." },
{name:'66169',l:'66',c:'16',v:'9',texto:"Y los hombres se quemaron con el gran calor, y blasfemaron el nombre de Dios, que tiene poder sobre estas plagas, y no se arrepintieron para darle gloria." },
{name:'661610',l:'66',c:'16',v:'10',texto:"El quinto ángel derramó su copa sobre el trono de la bestia; y su reino se cubrió de tinieblas, y mordían de dolor sus lenguas," },
{name:'661611',l:'66',c:'16',v:'11',texto:"y blasfemaron contra el Dios del cielo por sus dolores y por sus úlceras, y no se arrepintieron de sus obras." },
{name:'661612',l:'66',c:'16',v:'12',texto:"El sexto ángel derramó su copa sobre el gran río Eufrates; y el agua de éste se secó, para que estuviese preparado el camino a los reyes del oriente." },
{name:'661613',l:'66',c:'16',v:'13',texto:"Y vi salir de la boca del dragón, y de la boca de la bestia, y de la boca del falso profeta, tres espíritus inmundos a manera de ranas; " },
{name:'661614',l:'66',c:'16',v:'14',texto:"pues son espíritus de demonios, que hacen señales, y van a los reyes de la tierra en todo el mundo, para reunirlos a la batalla de aquel gran día del Dios Todopoderoso." },
{name:'661615',l:'66',c:'16',v:'15',texto:"He aquí, yo vengo como ladrón. Bienaventurado el que vela, y guarda sus ropas, para que no ande desnudo, y vean su vergüenza." },
{name:'661616',l:'66',c:'16',v:'16',texto:"Y los reunió en el lugar que en hebreo se llama Armagedón." },
{name:'661617',l:'66',c:'16',v:'17',texto:"El séptimo ángel derramó su copa por el aire; y salió una gran voz del templo del cielo, del trono, diciendo: Hecho está." },
{name:'661618',l:'66',c:'16',v:'18',texto:"Entonces hubo relámpagos y voces y truenos, y un gran temblor de tierra, un terremoto tan grande, cual no lo hubo jamás desde que los hombres han estado sobre la tierra." },
{name:'661619',l:'66',c:'16',v:'19',texto:"Y la gran ciudad fue dividida en tres partes, y las ciudades de las naciones cayeron; y la gran Babilonia vino en memoria delante de Dios, para darle el cáliz del vino del ardor de su ira." },
{name:'661620',l:'66',c:'16',v:'20',texto:"Y toda isla huyó, y los montes no fueron hallados." },
{name:'661621',l:'66',c:'16',v:'21',texto:"Y cayó del cielo sobre los hombres un enorme granizo como del peso de un talento; y los hombres blasfemaron contra Dios por la plaga del granizo; porque su plaga fue sobremanera grande." },
],
numVersiculos: 21,
},

c17: {
versiculos:[
{name:'66171',l:'66',c:'17',v:'1',texto:"Vino entonces uno de los siete ángeles que tenían las siete copas, y habló conmigo diciéndome: Ven acá, y te mostraré la sentencia contra la gran ramera, la que está sentada sobre muchas aguas; " },
{name:'66172',l:'66',c:'17',v:'2',texto:"con la cual han fornicado los reyes de la tierra, y los moradores de la tierra se han embriagado con el vino de su fornicación." },
{name:'66173',l:'66',c:'17',v:'3',texto:"Y me llevó en el Espíritu al desierto; y vi a una mujer sentada sobre una bestia escarlata llena de nombres de blasfemia, que tenía siete cabezas y diez cuernos." },
{name:'66174',l:'66',c:'17',v:'4',texto:"Y la mujer estaba vestida de púrpura y escarlata, y adornada de oro de piedras preciosas y de perlas, y tenía en la mano un cáliz de oro lleno de abominaciones y de la inmundicia de su fornicación; " },
{name:'66175',l:'66',c:'17',v:'5',texto:"y en su frente un nombre escrito, un misterio: BABILONIA LA GRANDE, LA MADRE DE LAS RAMERAS Y DE LAS ABOMINACIONES DE LA TIERRA." },
{name:'66176',l:'66',c:'17',v:'6',texto:"Vi a la mujer ebria de la sangre de los santos, y de la sangre de los mártires de Jesús; y cuando la vi, quedé asombrado con gran asombro." },
{name:'66177',l:'66',c:'17',v:'7',texto:"Y el ángel me dijo: ¿Por qué te asombras? Yo te diré el misterio de la mujer, y de la bestia que la trae, la cual tiene las siete cabezas y los diez cuernos." },
{name:'66178',l:'66',c:'17',v:'8',texto:"La bestia que has visto, era, y no es; y está para subir del abismo e ir a perdición; y los moradores de la tierra, aquellos cuyos nombres no están escritos desde la fundación del mundo en el libro de la vida, se asombrarán viendo la bestia que era y no es, y será." },
{name:'66179',l:'66',c:'17',v:'9',texto:"Esto, para la mente que tenga sabiduría: Las siete cabezas son siete montes, sobre los cuales se sienta la mujer," },
{name:'661710',l:'66',c:'17',v:'10',texto:"y son siete reyes. Cinco de ellos han caído; uno es, y el otro aún no ha venido; y cuando venga, es necesario que dure breve tiempo." },
{name:'661711',l:'66',c:'17',v:'11',texto:"La bestia que era, y no es, es también el octavo; y es de entre los siete, y va a la perdición." },
{name:'661712',l:'66',c:'17',v:'12',texto:"Y los diez cuernos que has visto, son diez reyes, que aún no han recibido reino; pero por una hora recibirán autoridad como reyes juntamente con la bestia." },
{name:'661713',l:'66',c:'17',v:'13',texto:"Estos tienen un mismo propósito, y entregarán su poder y su autoridad a la bestia." },
{name:'661714',l:'66',c:'17',v:'14',texto:"Pelearán contra el Cordero, y el Cordero los vencerá, porque él es Señor de señores y Rey de reyes; y los que están con él son llamados y elegidos y fieles." },
{name:'661715',l:'66',c:'17',v:'15',texto:"Me dijo también: Las aguas que has visto donde la ramera se sienta, son pueblos, muchedumbres, naciones y lenguas." },
{name:'661716',l:'66',c:'17',v:'16',texto:"Y los diez cuernos que viste en la bestia, éstos aborrecerán a la ramera, y la dejarán desolada y desnuda; y devorarán sus carnes, y la quemarán con fuego; " },
{name:'661717',l:'66',c:'17',v:'17',texto:"porque Dios ha puesto en sus corazones el ejecutar lo que él quiso: ponerse de acuerdo, y dar su reino a la bestia, hasta que se cumplan las palabras de Dios." },
{name:'661718',l:'66',c:'17',v:'18',texto:"Y la mujer que has visto es la gran ciudad que reina sobre los reyes de la tierra." },
],
numVersiculos: 18,
},

c18: {
versiculos:[
{name:'66181',l:'66',c:'18',v:'1',texto:"Después de esto vi a otro ángel descender del cielo con gran poder; y la tierra fue alumbrada con su gloria." },
{name:'66182',l:'66',c:'18',v:'2',texto:"Y clamó con voz potente, diciendo: Ha caído, ha caído la gran Babilonia, y se ha hecho habitación de demonios y guarida de todo espíritu inmundo, y albergue de toda ave inmunda y aborrecible." },
{name:'66183',l:'66',c:'18',v:'3',texto:"Porque todas las naciones han bebido del vino del furor de su fornicación; y los reyes de la tierra han fornicado con ella, y los mercaderes de la tierra se han enriquecido de la potencia de sus deleites." },
{name:'66184',l:'66',c:'18',v:'4',texto:"Y oí otra voz del cielo, que decía: Salid de ella, pueblo mío, para que no seáis partícipes de sus pecados, ni recibáis parte de sus plagas; " },
{name:'66185',l:'66',c:'18',v:'5',texto:"porque sus pecados han llegado hasta el cielo, y Dios se ha acordado de sus maldades." },
{name:'66186',l:'66',c:'18',v:'6',texto:"Dadle a ella como ella os ha dado, y pagadle doble según sus obras; en el cáliz en que ella preparó bebida, preparadle a ella el doble." },
{name:'66187',l:'66',c:'18',v:'7',texto:"Cuanto ella se ha glorificado y ha vivido en deleites, tanto dadle de tormento y llanto; porque dice en su corazón: Yo estoy sentada como reina, y no soy viuda, y no veré llanto; " },
{name:'66188',l:'66',c:'18',v:'8',texto:"por lo cual en un solo día vendrán sus plagas; muerte, llanto y hambre, y será quemada con fuego; porque poderoso es Dios el Señor, que la juzga." },
{name:'66189',l:'66',c:'18',v:'9',texto:"Y los reyes de la tierra que han fornicado con ella, y con ella han vivido en deleites, llorarán y harán lamentación sobre ella, cuando vean el humo de su incendio," },
{name:'661810',l:'66',c:'18',v:'10',texto:"parándose lejos por el temor de su tormento, diciendo: ¡Ay, ay, de la gran ciudad de Babilonia, la ciudad fuerte; porque en una hora vino tu juicio! " },
{name:'661811',l:'66',c:'18',v:'11',texto:"Y los mercaderes de la tierra lloran y hacen lamentación sobre ella, porque ninguno compra más sus mercaderías; " },
{name:'661812',l:'66',c:'18',v:'12',texto:"mercadería de oro, de plata, de piedras preciosas, de perlas, de lino fino, de púrpura, de seda, de escarlata, de toda madera olorosa, de todo objeto de marfil, de todo objeto de madera preciosa, de cobre, de hierro y de mármol; " },
{name:'661813',l:'66',c:'18',v:'13',texto:"y canela, especias aromáticas, incienso, mirra, olíbano, vino, aceite, flor de harina, trigo, bestias, ovejas, caballos y carros, y esclavos, almas de hombres." },
{name:'661814',l:'66',c:'18',v:'14',texto:"Los frutos codiciados por tu alma se apartaron de ti, y todas las cosas exquisitas y espléndidas te han faltado, y nunca más las hallarás." },
{name:'661815',l:'66',c:'18',v:'15',texto:"Los mercaderes de estas cosas, que se han enriquecido a costa de ella, se pararán lejos por el temor de su tormento, llorando y lamentando," },
{name:'661816',l:'66',c:'18',v:'16',texto:"y diciendo: ¡Ay, ay, de la gran ciudad, que estaba vestida de lino fino, de púrpura y de escarlata, y estaba adornada de oro, de piedras preciosas y de perlas! " },
{name:'661817',l:'66',c:'18',v:'17',texto:"Porque en una hora han sido consumidas tantas riquezas. Y todo piloto, y todos los que viajan en naves, y marineros, y todos los que trabajan en el mar, se pararon lejos; " },
{name:'661818',l:'66',c:'18',v:'18',texto:"y viendo el humo de su incendio, dieron voces, diciendo: ¿Qué ciudad era semejante a esta gran ciudad? " },
{name:'661819',l:'66',c:'18',v:'19',texto:"Y echaron polvo sobre sus cabezas, y dieron voces, llorando y lamentando, diciendo: ¡Ay, ay de la gran ciudad, en la cual todos los que tenían naves en el mar se habían enriquecido de sus riquezas; pues en una hora ha sido desolada! " },
{name:'661820',l:'66',c:'18',v:'20',texto:"Alégrate sobre ella, cielo, y vosotros, santos, apóstoles y profetas; porque Dios os ha hecho justicia en ella." },
{name:'661821',l:'66',c:'18',v:'21',texto:"Y un ángel poderoso tomó una piedra, como una gran piedra de molino, y la arrojó en el mar, diciendo: Con el mismo ímpetu será derribada Babilonia, la gran ciudad, y nunca más será hallada." },
{name:'661822',l:'66',c:'18',v:'22',texto:"Y voz de arpistas, de músicos, de flautistas y de trompeteros no se oirá más en ti; y ningún artífice de oficio alguno se hallará más en ti, ni ruido de molino se oirá más en ti." },
{name:'661823',l:'66',c:'18',v:'23',texto:"Luz de lámpara no alumbrará más en ti, ni voz de esposo y de esposa se oirá más en ti; porque tus mercaderes eran los grandes de la tierra; pues por tus hechicerías fueron engañadas todas las naciones." },
{name:'661824',l:'66',c:'18',v:'24',texto:"Y en ella se halló la sangre de los profetas y de los santos, y de todos los que han sido muertos en la tierra." },
],
numVersiculos: 24,
},

c19: {
versiculos:[
{name:'66191',l:'66',c:'19',v:'1',texto:"Después de esto oí una gran voz de gran multitud en el cielo, que decía: ¡Aleluya! Salvación y honra y gloria y poder son del Señor Dios nuestro; " },
{name:'66192',l:'66',c:'19',v:'2',texto:"porque sus juicios son verdaderos y justos; pues ha juzgado a la gran ramera que ha corrompido a la tierra con su fornicación, y ha vengado la sangre de sus siervos de la mano de ella." },
{name:'66193',l:'66',c:'19',v:'3',texto:"Otra vez dijeron: ¡Aleluya! Y el humo de ella sube por los siglos de los siglos." },
{name:'66194',l:'66',c:'19',v:'4',texto:"Y los veinticuatro ancianos y los cuatro seres vivientes se postraron en tierra y adoraron a Dios, que estaba sentado en el trono, y decían: ¡Amén! ¡Aleluya! " },
{name:'66195',l:'66',c:'19',v:'5',texto:"Y salió del trono una voz que decía: Alabad a nuestro Dios todos sus siervos, y los que le teméis, así pequeños como grandes." },
{name:'66196',l:'66',c:'19',v:'6',texto:"Y oí como la voz de una gran multitud, como el estruendo de muchas aguas, y como la voz de grandes truenos, que decía: ¡Aleluya, porque el Señor nuestro Dios Todopoderoso reina! " },
{name:'66197',l:'66',c:'19',v:'7',texto:"Gocémonos y alegrémonos y démosle gloria; porque han llegado las bodas del Cordero, y su esposa se ha preparado." },
{name:'66198',l:'66',c:'19',v:'8',texto:"Y a ella se le ha concedido que se vista de lino fino, limpio y resplandeciente; porque el lino fino es las acciones justas de los santos." },
{name:'66199',l:'66',c:'19',v:'9',texto:"Y el ángel me dijo: Escribe: Bienaventurados los que son llamados a la cena de las bodas del Cordero. Y me dijo: Estas son palabras verdaderas de Dios." },
{name:'661910',l:'66',c:'19',v:'10',texto:"Yo me postré a sus pies para adorarle. Y él me dijo: Mira, no lo hagas; yo soy consiervo tuyo, y de tus hermanos que retienen el testimonio de Jesús. Adora a Dios; porque el testimonio de Jesús es el espíritu de la profecía." },
{name:'661911',l:'66',c:'19',v:'11',texto:"Entonces vi el cielo abierto; y he aquí un caballo blanco, y el que lo montaba se llamaba Fiel y Verdadero, y con justicia juzga y pelea." },
{name:'661912',l:'66',c:'19',v:'12',texto:"Sus ojos eran como llama de fuego, y había en su cabeza muchas diademas; y tenía un nombre escrito que ninguno conocía sino él mismo." },
{name:'661913',l:'66',c:'19',v:'13',texto:"Estaba vestido de una ropa teñida en sangre; y su nombre es: EL VERBO DE DIOS." },
{name:'661914',l:'66',c:'19',v:'14',texto:"Y los ejércitos celestiales, vestidos de lino finísimo, blanco y limpio, le seguían en caballos blancos." },
{name:'661915',l:'66',c:'19',v:'15',texto:"De su boca sale una espada aguda, para herir con ella a las naciones, y él las regirá con vara de hierro; y él pisa el lagar del vino del furor y de la ira del Dios Todopoderoso." },
{name:'661916',l:'66',c:'19',v:'16',texto:"Y en su vestidura y en su muslo tiene escrito este nombre: REY DE REYES Y SEÑOR DE SEÑORES." },
{name:'661917',l:'66',c:'19',v:'17',texto:"Y vi a un ángel que estaba en pie en el sol, y clamó a gran voz, diciendo a todas las aves que vuelan en medio del cielo: Venid, y congregaos a la gran cena de Dios," },
{name:'661918',l:'66',c:'19',v:'18',texto:"para que comáis carnes de reyes y de capitanes, y carnes de fuertes, carnes de caballos y de sus jinetes, y carnes de todos, libres y esclavos, pequeños y grandes." },
{name:'661919',l:'66',c:'19',v:'19',texto:"Y vi a la bestia, a los reyes de la tierra y a sus ejércitos, reunidos para guerrear contra el que montaba el caballo, y contra su ejército." },
{name:'661920',l:'66',c:'19',v:'20',texto:"Y la bestia fue apresada, y con ella el falso profeta que había hecho delante de ella las señales con las cuales había engañado a los que recibieron la marca de la bestia, y habían adorado su imagen. Estos dos fueron lanzados vivos dentro de un lago de fuego que arde con azufre." },
{name:'661921',l:'66',c:'19',v:'21',texto:"Y los demás fueron muertos con la espada que salía de la boca del que montaba el caballo, y todas las aves se saciaron de las carnes de ellos." },
],
numVersiculos: 21,
},

c20: {
versiculos:[
{name:'66201',l:'66',c:'20',v:'1',texto:"Vi a un ángel que descendía del cielo, con la llave del abismo, y una gran cadena en la mano." },
{name:'66202',l:'66',c:'20',v:'2',texto:"Y prendió al dragón, la serpiente antigua, que es el diablo y Satanás, y lo ató por mil años; " },
{name:'66203',l:'66',c:'20',v:'3',texto:"y lo arrojó al abismo, y lo encerró, y puso su sello sobre él, para que no engañase más a las naciones, hasta que fuesen cumplidos mil años; y después de esto debe ser desatado por un poco de tiempo." },
{name:'66204',l:'66',c:'20',v:'4',texto:"Y vi tronos, y se sentaron sobre ellos los que recibieron facultad de juzgar; y vi las almas de los decapitados por causa del testimonio de Jesús y por la palabra de Dios, los que no habían adorado a la bestia ni a su imagen, y que no recibieron la marca en sus frentes ni en sus manos; y vivieron y reinaron con Cristo mil años." },
{name:'66205',l:'66',c:'20',v:'5',texto:"Pero los otros muertos no volvieron a vivir hasta que se cumplieron mil años. Esta es la primera resurrección." },
{name:'66206',l:'66',c:'20',v:'6',texto:"Bienaventurado y santo el que tiene parte en la primera resurrección; la segunda muerte no tiene potestad sobre éstos, sino que serán sacerdotes de Dios y de Cristo, y reinarán con él mil años." },
{name:'66207',l:'66',c:'20',v:'7',texto:"Cuando los mil años se cumplan, Satanás será suelto de su prisión," },
{name:'66208',l:'66',c:'20',v:'8',texto:"y saldrá a engañar a las naciones que están en los cuatro ángulos de la tierra, a Gog y a Magog, a fin de reunirlos para la batalla; el número de los cuales es como la arena del mar." },
{name:'66209',l:'66',c:'20',v:'9',texto:"Y subieron sobre la anchura de la tierra, y rodearon el campamento de los santos y la ciudad amada; y de Dios descendió fuego del cielo, y los consumió." },
{name:'662010',l:'66',c:'20',v:'10',texto:"Y el diablo que los engañaba fue lanzado en el lago de fuego y azufre, donde estaban la bestia y el falso profeta; y serán atormentados día y noche por los siglos de los siglos." },
{name:'662011',l:'66',c:'20',v:'11',texto:"Y vi un gran trono blanco y al que estaba sentado en él, de delante del cual huyeron la tierra y el cielo, y ningún lugar se encontró para ellos." },
{name:'662012',l:'66',c:'20',v:'12',texto:"Y vi a los muertos, grandes y pequeños, de pie ante Dios; y los libros fueron abiertos, y otro libro fue abierto, el cual es el libro de la vida; y fueron juzgados los muertos por las cosas que estaban escritas en los libros, según sus obras." },
{name:'662013',l:'66',c:'20',v:'13',texto:"Y el mar entregó los muertos que había en él; y la muerte y el Hades entregaron los muertos que había en ellos; y fueron juzgados cada uno según sus obras." },
{name:'662014',l:'66',c:'20',v:'14',texto:"Y la muerte y el Hades fueron lanzados al lago de fuego. Esta es la muerte segunda." },
{name:'662015',l:'66',c:'20',v:'15',texto:"Y el que no se halló inscrito en el libro de la vida fue lanzado al lago de fuego." },
],
numVersiculos: 15,
},

c21: {
versiculos:[
{name:'66211',l:'66',c:'21',v:'1',texto:"Vi un cielo nuevo y una tierra nueva; porque el primer cielo y la primera tierra pasaron, y el mar ya no existía más." },
{name:'66212',l:'66',c:'21',v:'2',texto:"Y yo Juan vi la santa ciudad, la nueva Jerusalén, descender del cielo, de Dios, dispuesta como una esposa ataviada para su marido." },
{name:'66213',l:'66',c:'21',v:'3',texto:"Y oí una gran voz del cielo que decía: He aquí el tabernáculo de Dios con los hombres, y él morará con ellos; y ellos serán su pueblo, y Dios mismo estará con ellos como su Dios." },
{name:'66214',l:'66',c:'21',v:'4',texto:"Enjugará Dios toda lágrima de los ojos de ellos; y ya no habrá muerte, ni habrá más llanto, ni clamor, ni dolor; porque las primeras cosas pasaron." },
{name:'66215',l:'66',c:'21',v:'5',texto:"Y el que estaba sentado en el trono dijo: He aquí, yo hago nuevas todas las cosas. Y me dijo: Escribe; porque estas palabras son fieles y verdaderas." },
{name:'66216',l:'66',c:'21',v:'6',texto:"Y me dijo: Hecho está. Yo soy el Alfa y la Omega, el principio y el fin. Al que tuviere sed, yo le daré gratuitamente de la fuente del agua de la vida." },
{name:'66217',l:'66',c:'21',v:'7',texto:"El que venciere heredará todas las cosas, y yo seré su Dios, y él será mi hijo." },
{name:'66218',l:'66',c:'21',v:'8',texto:"Pero los cobardes e incrédulos, los abominables y homicidas, los fornicarios y hechiceros, los idólatras y todos los mentirosos tendrán su parte en el lago que arde con fuego y azufre, que es la muerte segunda." },
{name:'66219',l:'66',c:'21',v:'9',texto:"Vino entonces a mí uno de los siete ángeles que tenían las siete copas llenas de las siete plagas postreras, y habló conmigo, diciendo: Ven acá, yo te mostraré la desposada, la esposa del Cordero." },
{name:'662110',l:'66',c:'21',v:'10',texto:"Y me llevó en el Espíritu a un monte grande y alto, y me mostró la gran ciudad santa de Jerusalén, que descendía del cielo, de Dios," },
{name:'662111',l:'66',c:'21',v:'11',texto:"teniendo la gloria de Dios. Y su fulgor era semejante al de una piedra preciosísima, como piedra de jaspe, diáfana como el cristal." },
{name:'662112',l:'66',c:'21',v:'12',texto:"Tenía un muro grande y alto con doce puertas; y en las puertas, doce ángeles, y nombres inscritos, que son los de las doce tribus de los hijos de Israel; " },
{name:'662113',l:'66',c:'21',v:'13',texto:"al oriente tres puertas; al norte tres puertas; al sur tres puertas; al occidente tres puertas." },
{name:'662114',l:'66',c:'21',v:'14',texto:"Y el muro de la ciudad tenía doce cimientos, y sobre ellos los doce nombres de los doce apóstoles del Cordero." },
{name:'662115',l:'66',c:'21',v:'15',texto:"El que hablaba conmigo tenía una caña de medir, de oro, para medir la ciudad, sus puertas y su muro." },
{name:'662116',l:'66',c:'21',v:'16',texto:"La ciudad se halla establecida en cuadro, y su longitud es igual a su anchura; y él midió la ciudad con la caña, doce mil estadios; la longitud, la altura y la anchura de ella son iguales." },
{name:'662117',l:'66',c:'21',v:'17',texto:"Y midió su muro, ciento cuarenta y cuatro codos, de medida de hombre, la cual es de ángel." },
{name:'662118',l:'66',c:'21',v:'18',texto:"El material de su muro era de jaspe; pero la ciudad era de oro puro, semejante al vidrio limpio; " },
{name:'662119',l:'66',c:'21',v:'19',texto:"y los cimientos del muro de la ciudad estaban adornados con toda piedra preciosa. El primer cimiento era jaspe; el segundo, zafiro; el tercero, ágata; el cuarto, esmeralda; " },
{name:'662120',l:'66',c:'21',v:'20',texto:"el quinto, ónice; el sexto, cornalina; el séptimo, crisólito; el octavo, berilo; el noveno, topacio; el décimo, crisopraso; el undécimo, jacinto; el duodécimo, amatista." },
{name:'662121',l:'66',c:'21',v:'21',texto:"Las doce puertas eran doce perlas; cada una de las puertas era una perla. Y la calle de la ciudad era de oro puro, transparente como vidrio." },
{name:'662122',l:'66',c:'21',v:'22',texto:"Y no vi en ella templo; porque el Señor Dios Todopoderoso es el templo de ella, y el Cordero." },
{name:'662123',l:'66',c:'21',v:'23',texto:"La ciudad no tiene necesidad de sol ni de luna que brillen en ella; porque la gloria de Dios la ilumina, y el Cordero es su lumbrera." },
{name:'662124',l:'66',c:'21',v:'24',texto:"Y las naciones que hubieren sido salvas andarán a la luz de ella; y los reyes de la tierra traerán su gloria y honor a ella." },
{name:'662125',l:'66',c:'21',v:'25',texto:"Sus puertas nunca serán cerradas de día, pues allí no habrá noche." },
{name:'662126',l:'66',c:'21',v:'26',texto:"Y llevarán la gloria y la honra de las naciones a ella." },
{name:'662127',l:'66',c:'21',v:'27',texto:"No entrará en ella ninguna cosa inmunda, o que hace abominación y mentira, sino solamente los que están inscritos en el libro de la vida del Cordero." },
],
numVersiculos: 27,
},

c22: {
versiculos:[
{name:'66221',l:'66',c:'22',v:'1',texto:"Después me mostró un río limpio de agua de vida, resplandeciente como cristal, que salía del trono de Dios y del Cordero." },
{name:'66222',l:'66',c:'22',v:'2',texto:"En medio de la calle de la ciudad, y a uno y otro lado del río, estaba el árbol de la vida, que produce doce frutos, dando cada mes su fruto; y las hojas del árbol eran para la sanidad de las naciones." },
{name:'66223',l:'66',c:'22',v:'3',texto:"Y no habrá más maldición; y el trono de Dios y del Cordero estará en ella, y sus siervos le servirán," },
{name:'66224',l:'66',c:'22',v:'4',texto:"y verán su rostro, y su nombre estará en sus frentes." },
{name:'66225',l:'66',c:'22',v:'5',texto:"No habrá allí más noche; y no tienen necesidad de luz de lámpara, ni de luz del sol, porque Dios el Señor los iluminará; y reinarán por los siglos de los siglos." },
{name:'66226',l:'66',c:'22',v:'6',texto:"Y me dijo: Estas palabras son fieles y verdaderas. Y el Señor, el Dios de los espíritus de los profetas, ha enviado su ángel, para mostrar a sus siervos las cosas que deben suceder pronto." },
{name:'66227',l:'66',c:'22',v:'7',texto:"¡He aquí, vengo pronto! Bienaventurado el que guarda las palabras de la profecía de este libro." },
{name:'66228',l:'66',c:'22',v:'8',texto:"Yo Juan soy el que oyó y vio estas cosas. Y después que las hube oído y visto, me postré para adorar a los pies del ángel que me mostraba estas cosas." },
{name:'66229',l:'66',c:'22',v:'9',texto:"Pero él me dijo: Mira, no lo hagas; porque yo soy consiervo tuyo, de tus hermanos los profetas, y de los que guardan las palabras de este libro. Adora a Dios." },
{name:'662210',l:'66',c:'22',v:'10',texto:"Y me dijo: No selles las palabras de la profecía de este libro, porque el tiempo está cerca." },
{name:'662211',l:'66',c:'22',v:'11',texto:"El que es injusto, sea injusto todavía; y el que es inmundo, sea inmundo todavía; y el que es justo, practique la justicia todavía; y el que es santo, santifíquese todavía." },
{name:'662212',l:'66',c:'22',v:'12',texto:"He aquí yo vengo pronto, y mi galardón conmigo, para recompensar a cada uno según sea su obra." },
{name:'662213',l:'66',c:'22',v:'13',texto:"Yo soy el Alfa y la Omega, el principio y el fin, el primero y el último." },
{name:'662214',l:'66',c:'22',v:'14',texto:"Bienaventurados los que lavan sus ropas, para tener derecho al árbol de la vida, y para entrar por las puertas en la ciudad." },
{name:'662215',l:'66',c:'22',v:'15',texto:"Mas los perros estarán fuera, y los hechiceros, los fornicarios, los homicidas, los idólatras, y todo aquel que ama y hace mentira." },
{name:'662216',l:'66',c:'22',v:'16',texto:"Yo Jesús he enviado mi ángel para daros testimonio de estas cosas en las iglesias. Yo soy la raíz y el linaje de David, la estrella resplandeciente de la mañana." },
{name:'662217',l:'66',c:'22',v:'17',texto:"Y el Espíritu y la Esposa dicen: Ven. Y el que oye, diga: Ven. Y el que tiene sed, venga; y el que quiera, tome del agua de la vida gratuitamente." },
{name:'662218',l:'66',c:'22',v:'18',texto:"Yo testifico a todo aquel que oye las palabras de la profecía de este libro: Si alguno añadiere a estas cosas, Dios traerá sobre él las plagas que están escritas en este libro." },
{name:'662219',l:'66',c:'22',v:'19',texto:"Y si alguno quitare de las palabras del libro de esta profecía, Dios quitará su parte del libro de la vida, y de la santa ciudad y de las cosas que están escritas en este libro." },
{name:'662220',l:'66',c:'22',v:'20',texto:"El que da testimonio de estas cosas dice: Ciertamente vengo en breve. Amén; sí, ven, Señor Jesús." },
{name:'662221',l:'66',c:'22',v:'21',texto:"La gracia de nuestro Señor Jesucristo sea con todos vosotros. Amén." },
],
numVersiculos: 21,
},
	

};
